max_clauses(1).
max_vars(7).
max_body(7).

head_pred(next,1).
body_pred(does,2).
body_pred(my_input,1).
body_pred(my_true,1).
body_pred(my_succ,2).
body_pred(role,1).
body_pred(c_p,1).
body_pred(c_q,1).
body_pred(c_r,1).
body_pred(c_a,1).
body_pred(c_b,1).
body_pred(c_c,1).
body_pred(not_my_true,1).

type(next,(prop,)).
type(does,(agent,action)).
type(my_input,(agent,action)).
type(my_true,(prop,)).
type(my_succ,(prop,prop)).
type(role,(agent,)).
type(c_p,(prop,)).
type(c_q,(prop,)).
type(c_r,(prop,)).
type(c_a,(action,)).
type(c_b,(action,)).
type(c_c,(action,)).
type(not_my_true,(prop,)).

prop(antitransitive,my_succ).
prop(antitriangular,my_succ).
prop(asymmetric_ab_ba,my_succ).
prop(pab_qac,(does,my_input)).
prop(postcon,(my_succ,c_p)).
prop(postcon,(my_succ,c_q)).
prop(postcon,(my_succ,c_r)).
prop(postcon,(my_succ,not_my_true)).
prop(pre_postcon,(c_p,my_succ,c_p)).
prop(pre_postcon,(c_p,my_succ,c_q)).
prop(pre_postcon,(c_p,my_succ,c_r)).
prop(pre_postcon,(c_p,my_succ,my_true)).
prop(pre_postcon,(c_p,my_succ,not_my_true)).
prop(pre_postcon,(c_q,my_succ,c_p)).
prop(pre_postcon,(c_q,my_succ,c_q)).
prop(pre_postcon,(c_q,my_succ,c_r)).
prop(pre_postcon,(c_q,my_succ,my_true)).
prop(pre_postcon,(c_q,my_succ,not_my_true)).
prop(pre_postcon,(c_r,my_succ,c_p)).
prop(pre_postcon,(c_r,my_succ,c_q)).
prop(pre_postcon,(c_r,my_succ,c_r)).
prop(pre_postcon,(c_r,my_succ,my_true)).
prop(pre_postcon,(c_r,my_succ,not_my_true)).
prop(pre_postcon,(my_true,my_succ,c_p)).
prop(pre_postcon,(my_true,my_succ,c_q)).
prop(pre_postcon,(my_true,my_succ,c_r)).
prop(pre_postcon,(my_true,my_succ,my_true)).
prop(pre_postcon,(my_true,my_succ,not_my_true)).
prop(pre_postcon,(not_my_true,my_succ,c_p)).
prop(pre_postcon,(not_my_true,my_succ,c_q)).
prop(pre_postcon,(not_my_true,my_succ,c_r)).
prop(pre_postcon,(not_my_true,my_succ,my_true)).
prop(pre_postcon,(not_my_true,my_succ,not_my_true)).
prop(pre_postcon,(role,my_input,c_a)).
prop(pre_postcon,(role,my_input,c_b)).
prop(pre_postcon,(role,my_input,c_c)).
prop(precon,(c_p,my_succ)).
prop(precon,(c_q,my_succ)).
prop(precon,(c_r,my_succ)).
prop(precon,(not_my_true,my_succ)).
prop(singleton,c_a).
prop(singleton,c_b).
prop(singleton,c_c).
prop(singleton,c_p).
prop(singleton,c_q).
prop(singleton,c_r).
prop(singleton,role).
prop(unique_a_b,does).
prop(unique_a_b,my_succ).
prop(unique_b_a,does).
prop(unique_b_a,my_succ).
prop(countk,c_a,1).
prop(countk,c_b,1).
prop(countk,c_c,1).
prop(countk,c_p,1).
prop(countk,c_q,1).
prop(countk,c_r,1).
prop(countk,role,1).
prop(unsat_pair,c_b,c_a).
prop(unsat_pair,c_c,c_a).
prop(unsat_pair,c_c,c_b).
prop(unsat_pair,c_q,c_p).
prop(unsat_pair,c_r,c_p).
prop(unsat_pair,c_r,c_q).
prop(unsat_pair,not_my_true,my_true).
prop(countk,my_true,3).
