neg(next_has_arson(1,blue)).
neg(next_has_arson(1,red)).
neg(next_has_arson(10,red)).
neg(next_has_arson(100,blue)).
neg(next_has_arson(100,red)).
neg(next_has_arson(101,blue)).
neg(next_has_arson(101,red)).
neg(next_has_arson(102,blue)).
neg(next_has_arson(102,red)).
neg(next_has_arson(103,blue)).
neg(next_has_arson(103,red)).
neg(next_has_arson(104,blue)).
neg(next_has_arson(104,red)).
neg(next_has_arson(105,blue)).
neg(next_has_arson(105,red)).
neg(next_has_arson(106,blue)).
neg(next_has_arson(106,red)).
neg(next_has_arson(107,blue)).
neg(next_has_arson(107,red)).
neg(next_has_arson(108,blue)).
neg(next_has_arson(108,red)).
neg(next_has_arson(11,red)).
neg(next_has_arson(110,blue)).
neg(next_has_arson(110,red)).
neg(next_has_arson(111,blue)).
neg(next_has_arson(111,red)).
neg(next_has_arson(112,blue)).
neg(next_has_arson(112,red)).
neg(next_has_arson(113,blue)).
neg(next_has_arson(113,red)).
neg(next_has_arson(114,blue)).
neg(next_has_arson(114,red)).
neg(next_has_arson(115,blue)).
neg(next_has_arson(115,red)).
neg(next_has_arson(116,blue)).
neg(next_has_arson(116,red)).
neg(next_has_arson(117,blue)).
neg(next_has_arson(117,red)).
neg(next_has_arson(118,blue)).
neg(next_has_arson(118,red)).
neg(next_has_arson(119,blue)).
neg(next_has_arson(119,red)).
neg(next_has_arson(12,red)).
neg(next_has_arson(120,blue)).
neg(next_has_arson(120,red)).
neg(next_has_arson(121,red)).
neg(next_has_arson(122,blue)).
neg(next_has_arson(122,red)).
neg(next_has_arson(123,blue)).
neg(next_has_arson(123,red)).
neg(next_has_arson(124,blue)).
neg(next_has_arson(124,red)).
neg(next_has_arson(125,blue)).
neg(next_has_arson(125,red)).
neg(next_has_arson(126,blue)).
neg(next_has_arson(126,red)).
neg(next_has_arson(127,blue)).
neg(next_has_arson(127,red)).
neg(next_has_arson(128,blue)).
neg(next_has_arson(128,red)).
neg(next_has_arson(13,blue)).
neg(next_has_arson(13,red)).
neg(next_has_arson(130,blue)).
neg(next_has_arson(130,red)).
neg(next_has_arson(131,blue)).
neg(next_has_arson(131,red)).
neg(next_has_arson(132,blue)).
neg(next_has_arson(132,red)).
neg(next_has_arson(133,blue)).
neg(next_has_arson(133,red)).
neg(next_has_arson(134,blue)).
neg(next_has_arson(134,red)).
neg(next_has_arson(135,blue)).
neg(next_has_arson(135,red)).
neg(next_has_arson(136,red)).
neg(next_has_arson(137,blue)).
neg(next_has_arson(137,red)).
neg(next_has_arson(138,blue)).
neg(next_has_arson(138,red)).
neg(next_has_arson(139,blue)).
neg(next_has_arson(139,red)).
neg(next_has_arson(14,blue)).
neg(next_has_arson(14,red)).
neg(next_has_arson(140,blue)).
neg(next_has_arson(140,red)).
neg(next_has_arson(141,blue)).
neg(next_has_arson(141,red)).
neg(next_has_arson(142,blue)).
neg(next_has_arson(142,red)).
neg(next_has_arson(143,blue)).
neg(next_has_arson(143,red)).
neg(next_has_arson(144,blue)).
neg(next_has_arson(144,red)).
neg(next_has_arson(146,red)).
neg(next_has_arson(147,blue)).
neg(next_has_arson(147,red)).
neg(next_has_arson(148,blue)).
neg(next_has_arson(148,red)).
neg(next_has_arson(149,red)).
neg(next_has_arson(15,blue)).
neg(next_has_arson(15,red)).
neg(next_has_arson(150,blue)).
neg(next_has_arson(150,red)).
neg(next_has_arson(151,blue)).
neg(next_has_arson(151,red)).
neg(next_has_arson(153,red)).
neg(next_has_arson(154,blue)).
neg(next_has_arson(154,red)).
neg(next_has_arson(155,blue)).
neg(next_has_arson(155,red)).
neg(next_has_arson(156,blue)).
neg(next_has_arson(156,red)).
neg(next_has_arson(157,blue)).
neg(next_has_arson(157,red)).
neg(next_has_arson(158,blue)).
neg(next_has_arson(158,red)).
neg(next_has_arson(159,blue)).
neg(next_has_arson(159,red)).
neg(next_has_arson(160,blue)).
neg(next_has_arson(160,red)).
neg(next_has_arson(161,blue)).
neg(next_has_arson(161,red)).
neg(next_has_arson(162,blue)).
neg(next_has_arson(162,red)).
neg(next_has_arson(163,blue)).
neg(next_has_arson(163,red)).
neg(next_has_arson(164,red)).
neg(next_has_arson(165,blue)).
neg(next_has_arson(165,red)).
neg(next_has_arson(167,blue)).
neg(next_has_arson(167,red)).
neg(next_has_arson(168,blue)).
neg(next_has_arson(168,red)).
neg(next_has_arson(169,red)).
neg(next_has_arson(17,blue)).
neg(next_has_arson(17,red)).
neg(next_has_arson(170,blue)).
neg(next_has_arson(170,red)).
neg(next_has_arson(171,blue)).
neg(next_has_arson(171,red)).
neg(next_has_arson(172,blue)).
neg(next_has_arson(172,red)).
neg(next_has_arson(173,blue)).
neg(next_has_arson(173,red)).
neg(next_has_arson(174,blue)).
neg(next_has_arson(174,red)).
neg(next_has_arson(175,blue)).
neg(next_has_arson(175,red)).
neg(next_has_arson(176,blue)).
neg(next_has_arson(176,red)).
neg(next_has_arson(177,blue)).
neg(next_has_arson(177,red)).
neg(next_has_arson(178,blue)).
neg(next_has_arson(178,red)).
neg(next_has_arson(179,blue)).
neg(next_has_arson(179,red)).
neg(next_has_arson(18,blue)).
neg(next_has_arson(18,red)).
neg(next_has_arson(180,blue)).
neg(next_has_arson(180,red)).
neg(next_has_arson(181,blue)).
neg(next_has_arson(181,red)).
neg(next_has_arson(182,blue)).
neg(next_has_arson(182,red)).
neg(next_has_arson(183,blue)).
neg(next_has_arson(183,red)).
neg(next_has_arson(185,red)).
neg(next_has_arson(186,blue)).
neg(next_has_arson(186,red)).
neg(next_has_arson(187,blue)).
neg(next_has_arson(187,red)).
neg(next_has_arson(188,blue)).
neg(next_has_arson(188,red)).
neg(next_has_arson(189,blue)).
neg(next_has_arson(189,red)).
neg(next_has_arson(19,blue)).
neg(next_has_arson(19,red)).
neg(next_has_arson(190,blue)).
neg(next_has_arson(190,red)).
neg(next_has_arson(191,blue)).
neg(next_has_arson(191,red)).
neg(next_has_arson(192,blue)).
neg(next_has_arson(192,red)).
neg(next_has_arson(193,blue)).
neg(next_has_arson(193,red)).
neg(next_has_arson(195,blue)).
neg(next_has_arson(195,red)).
neg(next_has_arson(196,blue)).
neg(next_has_arson(196,red)).
neg(next_has_arson(197,blue)).
neg(next_has_arson(197,red)).
neg(next_has_arson(198,blue)).
neg(next_has_arson(198,red)).
neg(next_has_arson(199,blue)).
neg(next_has_arson(199,red)).
neg(next_has_arson(2,blue)).
neg(next_has_arson(2,red)).
neg(next_has_arson(20,blue)).
neg(next_has_arson(20,red)).
neg(next_has_arson(200,blue)).
neg(next_has_arson(200,red)).
neg(next_has_arson(201,blue)).
neg(next_has_arson(201,red)).
neg(next_has_arson(202,blue)).
neg(next_has_arson(202,red)).
neg(next_has_arson(203,blue)).
neg(next_has_arson(203,red)).
neg(next_has_arson(204,red)).
neg(next_has_arson(205,blue)).
neg(next_has_arson(205,red)).
neg(next_has_arson(206,blue)).
neg(next_has_arson(206,red)).
neg(next_has_arson(207,blue)).
neg(next_has_arson(207,red)).
neg(next_has_arson(208,blue)).
neg(next_has_arson(208,red)).
neg(next_has_arson(209,blue)).
neg(next_has_arson(209,red)).
neg(next_has_arson(21,blue)).
neg(next_has_arson(21,red)).
neg(next_has_arson(210,red)).
neg(next_has_arson(211,blue)).
neg(next_has_arson(211,red)).
neg(next_has_arson(212,blue)).
neg(next_has_arson(212,red)).
neg(next_has_arson(213,blue)).
neg(next_has_arson(213,red)).
neg(next_has_arson(214,red)).
neg(next_has_arson(215,blue)).
neg(next_has_arson(215,red)).
neg(next_has_arson(216,blue)).
neg(next_has_arson(216,red)).
neg(next_has_arson(217,blue)).
neg(next_has_arson(217,red)).
neg(next_has_arson(218,blue)).
neg(next_has_arson(218,red)).
neg(next_has_arson(219,blue)).
neg(next_has_arson(219,red)).
neg(next_has_arson(22,blue)).
neg(next_has_arson(22,red)).
neg(next_has_arson(220,blue)).
neg(next_has_arson(220,red)).
neg(next_has_arson(221,red)).
neg(next_has_arson(222,blue)).
neg(next_has_arson(222,red)).
neg(next_has_arson(223,blue)).
neg(next_has_arson(223,red)).
neg(next_has_arson(225,blue)).
neg(next_has_arson(225,red)).
neg(next_has_arson(227,blue)).
neg(next_has_arson(227,red)).
neg(next_has_arson(228,blue)).
neg(next_has_arson(228,red)).
neg(next_has_arson(229,blue)).
neg(next_has_arson(229,red)).
neg(next_has_arson(23,blue)).
neg(next_has_arson(23,red)).
neg(next_has_arson(230,blue)).
neg(next_has_arson(230,red)).
neg(next_has_arson(231,blue)).
neg(next_has_arson(231,red)).
neg(next_has_arson(232,blue)).
neg(next_has_arson(232,red)).
neg(next_has_arson(233,blue)).
neg(next_has_arson(233,red)).
neg(next_has_arson(234,blue)).
neg(next_has_arson(234,red)).
neg(next_has_arson(235,blue)).
neg(next_has_arson(235,red)).
neg(next_has_arson(236,blue)).
neg(next_has_arson(236,red)).
neg(next_has_arson(238,blue)).
neg(next_has_arson(238,red)).
neg(next_has_arson(239,blue)).
neg(next_has_arson(239,red)).
neg(next_has_arson(24,blue)).
neg(next_has_arson(24,red)).
neg(next_has_arson(240,blue)).
neg(next_has_arson(240,red)).
neg(next_has_arson(241,blue)).
neg(next_has_arson(241,red)).
neg(next_has_arson(242,blue)).
neg(next_has_arson(242,red)).
neg(next_has_arson(243,blue)).
neg(next_has_arson(243,red)).
neg(next_has_arson(244,blue)).
neg(next_has_arson(244,red)).
neg(next_has_arson(245,blue)).
neg(next_has_arson(245,red)).
neg(next_has_arson(246,blue)).
neg(next_has_arson(246,red)).
neg(next_has_arson(247,blue)).
neg(next_has_arson(247,red)).
neg(next_has_arson(248,blue)).
neg(next_has_arson(248,red)).
neg(next_has_arson(249,blue)).
neg(next_has_arson(249,red)).
neg(next_has_arson(25,blue)).
neg(next_has_arson(25,red)).
neg(next_has_arson(250,blue)).
neg(next_has_arson(250,red)).
neg(next_has_arson(251,blue)).
neg(next_has_arson(251,red)).
neg(next_has_arson(252,blue)).
neg(next_has_arson(252,red)).
neg(next_has_arson(253,blue)).
neg(next_has_arson(253,red)).
neg(next_has_arson(254,blue)).
neg(next_has_arson(254,red)).
neg(next_has_arson(255,blue)).
neg(next_has_arson(255,red)).
neg(next_has_arson(256,blue)).
neg(next_has_arson(256,red)).
neg(next_has_arson(257,blue)).
neg(next_has_arson(257,red)).
neg(next_has_arson(259,blue)).
neg(next_has_arson(259,red)).
neg(next_has_arson(26,blue)).
neg(next_has_arson(26,red)).
neg(next_has_arson(260,blue)).
neg(next_has_arson(260,red)).
neg(next_has_arson(261,blue)).
neg(next_has_arson(261,red)).
neg(next_has_arson(262,red)).
neg(next_has_arson(263,blue)).
neg(next_has_arson(263,red)).
neg(next_has_arson(264,blue)).
neg(next_has_arson(264,red)).
neg(next_has_arson(265,blue)).
neg(next_has_arson(265,red)).
neg(next_has_arson(266,blue)).
neg(next_has_arson(266,red)).
neg(next_has_arson(267,red)).
neg(next_has_arson(268,red)).
neg(next_has_arson(269,blue)).
neg(next_has_arson(269,red)).
neg(next_has_arson(27,blue)).
neg(next_has_arson(27,red)).
neg(next_has_arson(270,blue)).
neg(next_has_arson(270,red)).
neg(next_has_arson(271,blue)).
neg(next_has_arson(271,red)).
neg(next_has_arson(272,blue)).
neg(next_has_arson(272,red)).
neg(next_has_arson(273,blue)).
neg(next_has_arson(274,blue)).
neg(next_has_arson(274,red)).
neg(next_has_arson(275,blue)).
neg(next_has_arson(275,red)).
neg(next_has_arson(276,blue)).
neg(next_has_arson(276,red)).
neg(next_has_arson(277,blue)).
neg(next_has_arson(277,red)).
neg(next_has_arson(278,blue)).
neg(next_has_arson(278,red)).
neg(next_has_arson(28,blue)).
neg(next_has_arson(28,red)).
neg(next_has_arson(280,blue)).
neg(next_has_arson(280,red)).
neg(next_has_arson(282,blue)).
neg(next_has_arson(282,red)).
neg(next_has_arson(283,blue)).
neg(next_has_arson(283,red)).
neg(next_has_arson(284,blue)).
neg(next_has_arson(284,red)).
neg(next_has_arson(285,blue)).
neg(next_has_arson(285,red)).
neg(next_has_arson(286,red)).
neg(next_has_arson(288,blue)).
neg(next_has_arson(288,red)).
neg(next_has_arson(289,red)).
neg(next_has_arson(29,blue)).
neg(next_has_arson(29,red)).
neg(next_has_arson(290,blue)).
neg(next_has_arson(290,red)).
neg(next_has_arson(291,blue)).
neg(next_has_arson(291,red)).
neg(next_has_arson(292,blue)).
neg(next_has_arson(292,red)).
neg(next_has_arson(293,blue)).
neg(next_has_arson(293,red)).
neg(next_has_arson(294,blue)).
neg(next_has_arson(294,red)).
neg(next_has_arson(295,blue)).
neg(next_has_arson(295,red)).
neg(next_has_arson(296,blue)).
neg(next_has_arson(296,red)).
neg(next_has_arson(297,blue)).
neg(next_has_arson(297,red)).
neg(next_has_arson(298,blue)).
neg(next_has_arson(298,red)).
neg(next_has_arson(299,blue)).
neg(next_has_arson(299,red)).
neg(next_has_arson(3,red)).
neg(next_has_arson(30,blue)).
neg(next_has_arson(30,red)).
neg(next_has_arson(300,blue)).
neg(next_has_arson(300,red)).
neg(next_has_arson(301,blue)).
neg(next_has_arson(301,red)).
neg(next_has_arson(302,blue)).
neg(next_has_arson(302,red)).
neg(next_has_arson(303,blue)).
neg(next_has_arson(303,red)).
neg(next_has_arson(304,blue)).
neg(next_has_arson(304,red)).
neg(next_has_arson(305,red)).
neg(next_has_arson(306,blue)).
neg(next_has_arson(306,red)).
neg(next_has_arson(307,blue)).
neg(next_has_arson(307,red)).
neg(next_has_arson(308,blue)).
neg(next_has_arson(308,red)).
neg(next_has_arson(309,blue)).
neg(next_has_arson(309,red)).
neg(next_has_arson(31,red)).
neg(next_has_arson(310,blue)).
neg(next_has_arson(310,red)).
neg(next_has_arson(311,blue)).
neg(next_has_arson(311,red)).
neg(next_has_arson(312,blue)).
neg(next_has_arson(312,red)).
neg(next_has_arson(314,blue)).
neg(next_has_arson(314,red)).
neg(next_has_arson(315,blue)).
neg(next_has_arson(315,red)).
neg(next_has_arson(316,blue)).
neg(next_has_arson(316,red)).
neg(next_has_arson(317,blue)).
neg(next_has_arson(317,red)).
neg(next_has_arson(318,red)).
neg(next_has_arson(319,blue)).
neg(next_has_arson(319,red)).
neg(next_has_arson(32,blue)).
neg(next_has_arson(32,red)).
neg(next_has_arson(320,blue)).
neg(next_has_arson(320,red)).
neg(next_has_arson(321,blue)).
neg(next_has_arson(321,red)).
neg(next_has_arson(322,blue)).
neg(next_has_arson(322,red)).
neg(next_has_arson(323,blue)).
neg(next_has_arson(323,red)).
neg(next_has_arson(325,blue)).
neg(next_has_arson(325,red)).
neg(next_has_arson(326,blue)).
neg(next_has_arson(326,red)).
neg(next_has_arson(328,blue)).
neg(next_has_arson(328,red)).
neg(next_has_arson(329,blue)).
neg(next_has_arson(329,red)).
neg(next_has_arson(33,blue)).
neg(next_has_arson(33,red)).
neg(next_has_arson(330,blue)).
neg(next_has_arson(330,red)).
neg(next_has_arson(331,blue)).
neg(next_has_arson(331,red)).
neg(next_has_arson(332,blue)).
neg(next_has_arson(332,red)).
neg(next_has_arson(333,blue)).
neg(next_has_arson(333,red)).
neg(next_has_arson(334,blue)).
neg(next_has_arson(334,red)).
neg(next_has_arson(335,blue)).
neg(next_has_arson(335,red)).
neg(next_has_arson(336,red)).
neg(next_has_arson(337,blue)).
neg(next_has_arson(337,red)).
neg(next_has_arson(338,blue)).
neg(next_has_arson(338,red)).
neg(next_has_arson(339,blue)).
neg(next_has_arson(339,red)).
neg(next_has_arson(34,blue)).
neg(next_has_arson(34,red)).
neg(next_has_arson(340,blue)).
neg(next_has_arson(340,red)).
neg(next_has_arson(341,blue)).
neg(next_has_arson(341,red)).
neg(next_has_arson(342,blue)).
neg(next_has_arson(342,red)).
neg(next_has_arson(343,blue)).
neg(next_has_arson(343,red)).
neg(next_has_arson(344,blue)).
neg(next_has_arson(344,red)).
neg(next_has_arson(345,blue)).
neg(next_has_arson(345,red)).
neg(next_has_arson(346,blue)).
neg(next_has_arson(346,red)).
neg(next_has_arson(347,blue)).
neg(next_has_arson(347,red)).
neg(next_has_arson(348,blue)).
neg(next_has_arson(348,red)).
neg(next_has_arson(349,blue)).
neg(next_has_arson(349,red)).
neg(next_has_arson(35,blue)).
neg(next_has_arson(35,red)).
neg(next_has_arson(350,blue)).
neg(next_has_arson(350,red)).
neg(next_has_arson(351,blue)).
neg(next_has_arson(351,red)).
neg(next_has_arson(352,blue)).
neg(next_has_arson(352,red)).
neg(next_has_arson(353,blue)).
neg(next_has_arson(353,red)).
neg(next_has_arson(354,blue)).
neg(next_has_arson(354,red)).
neg(next_has_arson(355,blue)).
neg(next_has_arson(355,red)).
neg(next_has_arson(356,blue)).
neg(next_has_arson(356,red)).
neg(next_has_arson(358,blue)).
neg(next_has_arson(358,red)).
neg(next_has_arson(36,blue)).
neg(next_has_arson(36,red)).
neg(next_has_arson(360,blue)).
neg(next_has_arson(360,red)).
neg(next_has_arson(361,blue)).
neg(next_has_arson(361,red)).
neg(next_has_arson(362,blue)).
neg(next_has_arson(362,red)).
neg(next_has_arson(363,blue)).
neg(next_has_arson(363,red)).
neg(next_has_arson(364,blue)).
neg(next_has_arson(364,red)).
neg(next_has_arson(365,red)).
neg(next_has_arson(366,red)).
neg(next_has_arson(367,blue)).
neg(next_has_arson(367,red)).
neg(next_has_arson(368,blue)).
neg(next_has_arson(368,red)).
neg(next_has_arson(369,blue)).
neg(next_has_arson(369,red)).
neg(next_has_arson(37,blue)).
neg(next_has_arson(37,red)).
neg(next_has_arson(370,blue)).
neg(next_has_arson(370,red)).
neg(next_has_arson(371,blue)).
neg(next_has_arson(371,red)).
neg(next_has_arson(373,blue)).
neg(next_has_arson(373,red)).
neg(next_has_arson(374,blue)).
neg(next_has_arson(374,red)).
neg(next_has_arson(375,blue)).
neg(next_has_arson(375,red)).
neg(next_has_arson(376,blue)).
neg(next_has_arson(376,red)).
neg(next_has_arson(377,blue)).
neg(next_has_arson(377,red)).
neg(next_has_arson(378,blue)).
neg(next_has_arson(378,red)).
neg(next_has_arson(379,blue)).
neg(next_has_arson(379,red)).
neg(next_has_arson(38,blue)).
neg(next_has_arson(38,red)).
neg(next_has_arson(380,blue)).
neg(next_has_arson(380,red)).
neg(next_has_arson(381,blue)).
neg(next_has_arson(381,red)).
neg(next_has_arson(382,blue)).
neg(next_has_arson(382,red)).
neg(next_has_arson(384,blue)).
neg(next_has_arson(384,red)).
neg(next_has_arson(385,blue)).
neg(next_has_arson(385,red)).
neg(next_has_arson(386,blue)).
neg(next_has_arson(386,red)).
neg(next_has_arson(387,blue)).
neg(next_has_arson(387,red)).
neg(next_has_arson(388,red)).
neg(next_has_arson(389,blue)).
neg(next_has_arson(389,red)).
neg(next_has_arson(39,blue)).
neg(next_has_arson(39,red)).
neg(next_has_arson(390,blue)).
neg(next_has_arson(390,red)).
neg(next_has_arson(391,blue)).
neg(next_has_arson(391,red)).
neg(next_has_arson(393,red)).
neg(next_has_arson(394,blue)).
neg(next_has_arson(394,red)).
neg(next_has_arson(395,blue)).
neg(next_has_arson(395,red)).
neg(next_has_arson(396,blue)).
neg(next_has_arson(396,red)).
neg(next_has_arson(397,blue)).
neg(next_has_arson(397,red)).
neg(next_has_arson(398,blue)).
neg(next_has_arson(398,red)).
neg(next_has_arson(399,blue)).
neg(next_has_arson(399,red)).
neg(next_has_arson(4,red)).
neg(next_has_arson(40,blue)).
neg(next_has_arson(40,red)).
neg(next_has_arson(400,red)).
neg(next_has_arson(401,blue)).
neg(next_has_arson(401,red)).
neg(next_has_arson(402,blue)).
neg(next_has_arson(402,red)).
neg(next_has_arson(403,blue)).
neg(next_has_arson(403,red)).
neg(next_has_arson(404,blue)).
neg(next_has_arson(404,red)).
neg(next_has_arson(405,blue)).
neg(next_has_arson(405,red)).
neg(next_has_arson(407,red)).
neg(next_has_arson(408,blue)).
neg(next_has_arson(408,red)).
neg(next_has_arson(409,blue)).
neg(next_has_arson(409,red)).
neg(next_has_arson(41,blue)).
neg(next_has_arson(41,red)).
neg(next_has_arson(410,red)).
neg(next_has_arson(411,blue)).
neg(next_has_arson(411,red)).
neg(next_has_arson(412,blue)).
neg(next_has_arson(412,red)).
neg(next_has_arson(413,blue)).
neg(next_has_arson(413,red)).
neg(next_has_arson(414,blue)).
neg(next_has_arson(414,red)).
neg(next_has_arson(415,blue)).
neg(next_has_arson(415,red)).
neg(next_has_arson(416,blue)).
neg(next_has_arson(416,red)).
neg(next_has_arson(417,blue)).
neg(next_has_arson(417,red)).
neg(next_has_arson(418,blue)).
neg(next_has_arson(418,red)).
neg(next_has_arson(419,blue)).
neg(next_has_arson(419,red)).
neg(next_has_arson(420,blue)).
neg(next_has_arson(420,red)).
neg(next_has_arson(421,blue)).
neg(next_has_arson(421,red)).
neg(next_has_arson(422,blue)).
neg(next_has_arson(422,red)).
neg(next_has_arson(423,red)).
neg(next_has_arson(424,blue)).
neg(next_has_arson(424,red)).
neg(next_has_arson(426,blue)).
neg(next_has_arson(426,red)).
neg(next_has_arson(427,blue)).
neg(next_has_arson(427,red)).
neg(next_has_arson(428,blue)).
neg(next_has_arson(428,red)).
neg(next_has_arson(429,blue)).
neg(next_has_arson(429,red)).
neg(next_has_arson(43,blue)).
neg(next_has_arson(43,red)).
neg(next_has_arson(430,blue)).
neg(next_has_arson(430,red)).
neg(next_has_arson(431,blue)).
neg(next_has_arson(431,red)).
neg(next_has_arson(432,blue)).
neg(next_has_arson(432,red)).
neg(next_has_arson(433,red)).
neg(next_has_arson(434,blue)).
neg(next_has_arson(434,red)).
neg(next_has_arson(435,blue)).
neg(next_has_arson(435,red)).
neg(next_has_arson(436,blue)).
neg(next_has_arson(436,red)).
neg(next_has_arson(437,blue)).
neg(next_has_arson(437,red)).
neg(next_has_arson(438,blue)).
neg(next_has_arson(438,red)).
neg(next_has_arson(439,blue)).
neg(next_has_arson(439,red)).
neg(next_has_arson(44,blue)).
neg(next_has_arson(44,red)).
neg(next_has_arson(440,blue)).
neg(next_has_arson(440,red)).
neg(next_has_arson(441,blue)).
neg(next_has_arson(441,red)).
neg(next_has_arson(442,blue)).
neg(next_has_arson(442,red)).
neg(next_has_arson(443,blue)).
neg(next_has_arson(443,red)).
neg(next_has_arson(444,blue)).
neg(next_has_arson(444,red)).
neg(next_has_arson(445,blue)).
neg(next_has_arson(445,red)).
neg(next_has_arson(446,blue)).
neg(next_has_arson(446,red)).
neg(next_has_arson(447,blue)).
neg(next_has_arson(447,red)).
neg(next_has_arson(449,blue)).
neg(next_has_arson(449,red)).
neg(next_has_arson(45,blue)).
neg(next_has_arson(45,red)).
neg(next_has_arson(450,blue)).
neg(next_has_arson(450,red)).
neg(next_has_arson(451,blue)).
neg(next_has_arson(451,red)).
neg(next_has_arson(453,blue)).
neg(next_has_arson(453,red)).
neg(next_has_arson(454,blue)).
neg(next_has_arson(454,red)).
neg(next_has_arson(455,blue)).
neg(next_has_arson(455,red)).
neg(next_has_arson(456,blue)).
neg(next_has_arson(456,red)).
neg(next_has_arson(457,blue)).
neg(next_has_arson(457,red)).
neg(next_has_arson(458,blue)).
neg(next_has_arson(458,red)).
neg(next_has_arson(459,red)).
neg(next_has_arson(46,blue)).
neg(next_has_arson(46,red)).
neg(next_has_arson(460,blue)).
neg(next_has_arson(460,red)).
neg(next_has_arson(461,blue)).
neg(next_has_arson(461,red)).
neg(next_has_arson(462,blue)).
neg(next_has_arson(462,red)).
neg(next_has_arson(463,blue)).
neg(next_has_arson(463,red)).
neg(next_has_arson(464,blue)).
neg(next_has_arson(464,red)).
neg(next_has_arson(465,blue)).
neg(next_has_arson(465,red)).
neg(next_has_arson(466,red)).
neg(next_has_arson(467,blue)).
neg(next_has_arson(467,red)).
neg(next_has_arson(468,red)).
neg(next_has_arson(469,blue)).
neg(next_has_arson(469,red)).
neg(next_has_arson(47,blue)).
neg(next_has_arson(47,red)).
neg(next_has_arson(470,red)).
neg(next_has_arson(471,red)).
neg(next_has_arson(474,blue)).
neg(next_has_arson(474,red)).
neg(next_has_arson(475,blue)).
neg(next_has_arson(475,red)).
neg(next_has_arson(476,blue)).
neg(next_has_arson(476,red)).
neg(next_has_arson(477,blue)).
neg(next_has_arson(477,red)).
neg(next_has_arson(478,blue)).
neg(next_has_arson(478,red)).
neg(next_has_arson(479,blue)).
neg(next_has_arson(479,red)).
neg(next_has_arson(48,blue)).
neg(next_has_arson(48,red)).
neg(next_has_arson(480,blue)).
neg(next_has_arson(480,red)).
neg(next_has_arson(482,blue)).
neg(next_has_arson(482,red)).
neg(next_has_arson(483,blue)).
neg(next_has_arson(483,red)).
neg(next_has_arson(484,blue)).
neg(next_has_arson(484,red)).
neg(next_has_arson(485,red)).
neg(next_has_arson(486,red)).
neg(next_has_arson(487,blue)).
neg(next_has_arson(487,red)).
neg(next_has_arson(488,blue)).
neg(next_has_arson(488,red)).
neg(next_has_arson(489,blue)).
neg(next_has_arson(489,red)).
neg(next_has_arson(491,blue)).
neg(next_has_arson(491,red)).
neg(next_has_arson(492,red)).
neg(next_has_arson(493,blue)).
neg(next_has_arson(493,red)).
neg(next_has_arson(494,blue)).
neg(next_has_arson(494,red)).
neg(next_has_arson(495,blue)).
neg(next_has_arson(495,red)).
neg(next_has_arson(496,blue)).
neg(next_has_arson(496,red)).
neg(next_has_arson(497,blue)).
neg(next_has_arson(497,red)).
neg(next_has_arson(498,blue)).
neg(next_has_arson(498,red)).
neg(next_has_arson(499,blue)).
neg(next_has_arson(499,red)).
neg(next_has_arson(5,blue)).
neg(next_has_arson(5,red)).
neg(next_has_arson(50,blue)).
neg(next_has_arson(50,red)).
neg(next_has_arson(500,blue)).
neg(next_has_arson(500,red)).
neg(next_has_arson(51,blue)).
neg(next_has_arson(51,red)).
neg(next_has_arson(52,blue)).
neg(next_has_arson(52,red)).
neg(next_has_arson(53,blue)).
neg(next_has_arson(53,red)).
neg(next_has_arson(55,red)).
neg(next_has_arson(56,blue)).
neg(next_has_arson(56,red)).
neg(next_has_arson(57,blue)).
neg(next_has_arson(57,red)).
neg(next_has_arson(58,blue)).
neg(next_has_arson(58,red)).
neg(next_has_arson(6,blue)).
neg(next_has_arson(6,red)).
neg(next_has_arson(61,blue)).
neg(next_has_arson(61,red)).
neg(next_has_arson(62,red)).
neg(next_has_arson(63,blue)).
neg(next_has_arson(63,red)).
neg(next_has_arson(64,blue)).
neg(next_has_arson(64,red)).
neg(next_has_arson(65,blue)).
neg(next_has_arson(65,red)).
neg(next_has_arson(66,blue)).
neg(next_has_arson(66,red)).
neg(next_has_arson(67,blue)).
neg(next_has_arson(67,red)).
neg(next_has_arson(68,blue)).
neg(next_has_arson(68,red)).
neg(next_has_arson(69,blue)).
neg(next_has_arson(69,red)).
neg(next_has_arson(7,blue)).
neg(next_has_arson(7,red)).
neg(next_has_arson(70,blue)).
neg(next_has_arson(70,red)).
neg(next_has_arson(71,blue)).
neg(next_has_arson(71,red)).
neg(next_has_arson(72,red)).
neg(next_has_arson(73,red)).
neg(next_has_arson(74,blue)).
neg(next_has_arson(74,red)).
neg(next_has_arson(75,blue)).
neg(next_has_arson(75,red)).
neg(next_has_arson(76,blue)).
neg(next_has_arson(76,red)).
neg(next_has_arson(77,blue)).
neg(next_has_arson(77,red)).
neg(next_has_arson(78,red)).
neg(next_has_arson(79,blue)).
neg(next_has_arson(79,red)).
neg(next_has_arson(8,blue)).
neg(next_has_arson(8,red)).
neg(next_has_arson(80,blue)).
neg(next_has_arson(80,red)).
neg(next_has_arson(81,blue)).
neg(next_has_arson(81,red)).
neg(next_has_arson(82,blue)).
neg(next_has_arson(82,red)).
neg(next_has_arson(83,blue)).
neg(next_has_arson(83,red)).
neg(next_has_arson(84,blue)).
neg(next_has_arson(84,red)).
neg(next_has_arson(85,blue)).
neg(next_has_arson(85,red)).
neg(next_has_arson(86,blue)).
neg(next_has_arson(86,red)).
neg(next_has_arson(87,red)).
neg(next_has_arson(88,red)).
neg(next_has_arson(89,blue)).
neg(next_has_arson(89,red)).
neg(next_has_arson(9,blue)).
neg(next_has_arson(9,red)).
neg(next_has_arson(90,blue)).
neg(next_has_arson(90,red)).
neg(next_has_arson(91,blue)).
neg(next_has_arson(91,red)).
neg(next_has_arson(92,blue)).
neg(next_has_arson(92,red)).
neg(next_has_arson(93,blue)).
neg(next_has_arson(93,red)).
neg(next_has_arson(94,red)).
neg(next_has_arson(95,blue)).
neg(next_has_arson(95,red)).
neg(next_has_arson(96,blue)).
neg(next_has_arson(96,red)).
neg(next_has_arson(97,red)).
neg(next_has_arson(98,blue)).
neg(next_has_arson(98,red)).
neg(next_has_arson(99,blue)).
neg(next_has_arson(99,red)).
pos(next_has_arson(10,blue)).
pos(next_has_arson(109,blue)).
pos(next_has_arson(109,red)).
pos(next_has_arson(11,blue)).
pos(next_has_arson(12,blue)).
pos(next_has_arson(121,blue)).
pos(next_has_arson(129,blue)).
pos(next_has_arson(129,red)).
pos(next_has_arson(136,blue)).
pos(next_has_arson(145,blue)).
pos(next_has_arson(145,red)).
pos(next_has_arson(146,blue)).
pos(next_has_arson(149,blue)).
pos(next_has_arson(152,blue)).
pos(next_has_arson(152,red)).
pos(next_has_arson(153,blue)).
pos(next_has_arson(16,blue)).
pos(next_has_arson(16,red)).
pos(next_has_arson(164,blue)).
pos(next_has_arson(166,blue)).
pos(next_has_arson(166,red)).
pos(next_has_arson(169,blue)).
pos(next_has_arson(184,blue)).
pos(next_has_arson(184,red)).
pos(next_has_arson(185,blue)).
pos(next_has_arson(194,blue)).
pos(next_has_arson(194,red)).
pos(next_has_arson(204,blue)).
pos(next_has_arson(210,blue)).
pos(next_has_arson(214,blue)).
pos(next_has_arson(221,blue)).
pos(next_has_arson(224,blue)).
pos(next_has_arson(224,red)).
pos(next_has_arson(226,blue)).
pos(next_has_arson(226,red)).
pos(next_has_arson(237,blue)).
pos(next_has_arson(237,red)).
pos(next_has_arson(258,blue)).
pos(next_has_arson(258,red)).
pos(next_has_arson(262,blue)).
pos(next_has_arson(267,blue)).
pos(next_has_arson(268,blue)).
pos(next_has_arson(273,red)).
pos(next_has_arson(279,blue)).
pos(next_has_arson(279,red)).
pos(next_has_arson(281,blue)).
pos(next_has_arson(281,red)).
pos(next_has_arson(286,blue)).
pos(next_has_arson(287,blue)).
pos(next_has_arson(287,red)).
pos(next_has_arson(289,blue)).
pos(next_has_arson(3,blue)).
pos(next_has_arson(305,blue)).
pos(next_has_arson(31,blue)).
pos(next_has_arson(313,blue)).
pos(next_has_arson(313,red)).
pos(next_has_arson(318,blue)).
pos(next_has_arson(324,blue)).
pos(next_has_arson(324,red)).
pos(next_has_arson(327,blue)).
pos(next_has_arson(327,red)).
pos(next_has_arson(336,blue)).
pos(next_has_arson(357,blue)).
pos(next_has_arson(357,red)).
pos(next_has_arson(359,blue)).
pos(next_has_arson(359,red)).
pos(next_has_arson(365,blue)).
pos(next_has_arson(366,blue)).
pos(next_has_arson(372,blue)).
pos(next_has_arson(372,red)).
pos(next_has_arson(383,blue)).
pos(next_has_arson(383,red)).
pos(next_has_arson(388,blue)).
pos(next_has_arson(392,blue)).
pos(next_has_arson(392,red)).
pos(next_has_arson(393,blue)).
pos(next_has_arson(4,blue)).
pos(next_has_arson(400,blue)).
pos(next_has_arson(406,blue)).
pos(next_has_arson(406,red)).
pos(next_has_arson(407,blue)).
pos(next_has_arson(410,blue)).
pos(next_has_arson(42,blue)).
pos(next_has_arson(42,red)).
pos(next_has_arson(423,blue)).
pos(next_has_arson(425,blue)).
pos(next_has_arson(425,red)).
pos(next_has_arson(433,blue)).
pos(next_has_arson(448,blue)).
pos(next_has_arson(448,red)).
pos(next_has_arson(452,blue)).
pos(next_has_arson(452,red)).
pos(next_has_arson(459,blue)).
pos(next_has_arson(466,blue)).
pos(next_has_arson(468,blue)).
pos(next_has_arson(470,blue)).
pos(next_has_arson(471,blue)).
pos(next_has_arson(472,blue)).
pos(next_has_arson(472,red)).
pos(next_has_arson(473,blue)).
pos(next_has_arson(473,red)).
pos(next_has_arson(481,blue)).
pos(next_has_arson(481,red)).
pos(next_has_arson(485,blue)).
pos(next_has_arson(486,blue)).
pos(next_has_arson(49,blue)).
pos(next_has_arson(49,red)).
pos(next_has_arson(490,blue)).
pos(next_has_arson(490,red)).
pos(next_has_arson(492,blue)).
pos(next_has_arson(54,blue)).
pos(next_has_arson(54,red)).
pos(next_has_arson(55,blue)).
pos(next_has_arson(59,blue)).
pos(next_has_arson(59,red)).
pos(next_has_arson(60,blue)).
pos(next_has_arson(60,red)).
pos(next_has_arson(62,blue)).
pos(next_has_arson(72,blue)).
pos(next_has_arson(73,blue)).
pos(next_has_arson(78,blue)).
pos(next_has_arson(87,blue)).
pos(next_has_arson(88,blue)).
pos(next_has_arson(94,blue)).
pos(next_has_arson(97,blue)).