neg(next_control(1,blue)).
neg(next_control(1,cyan)).
neg(next_control(1,red)).
neg(next_control(10,cyan)).
neg(next_control(10,orange)).
neg(next_control(10,red)).
neg(next_control(100,blue)).
neg(next_control(100,cyan)).
neg(next_control(100,orange)).
neg(next_control(101,blue)).
neg(next_control(101,orange)).
neg(next_control(101,red)).
neg(next_control(102,cyan)).
neg(next_control(102,orange)).
neg(next_control(102,red)).
neg(next_control(103,blue)).
neg(next_control(103,orange)).
neg(next_control(103,red)).
neg(next_control(104,cyan)).
neg(next_control(104,orange)).
neg(next_control(104,red)).
neg(next_control(105,blue)).
neg(next_control(105,cyan)).
neg(next_control(105,red)).
neg(next_control(106,cyan)).
neg(next_control(106,orange)).
neg(next_control(106,red)).
neg(next_control(107,cyan)).
neg(next_control(107,orange)).
neg(next_control(107,red)).
neg(next_control(108,cyan)).
neg(next_control(108,orange)).
neg(next_control(108,red)).
neg(next_control(109,blue)).
neg(next_control(109,orange)).
neg(next_control(109,red)).
neg(next_control(11,blue)).
neg(next_control(11,cyan)).
neg(next_control(11,orange)).
neg(next_control(110,cyan)).
neg(next_control(110,orange)).
neg(next_control(110,red)).
neg(next_control(111,blue)).
neg(next_control(111,cyan)).
neg(next_control(111,orange)).
neg(next_control(112,blue)).
neg(next_control(112,orange)).
neg(next_control(112,red)).
neg(next_control(113,cyan)).
neg(next_control(113,orange)).
neg(next_control(113,red)).
neg(next_control(114,blue)).
neg(next_control(114,cyan)).
neg(next_control(114,red)).
neg(next_control(115,blue)).
neg(next_control(115,cyan)).
neg(next_control(115,orange)).
neg(next_control(116,blue)).
neg(next_control(116,cyan)).
neg(next_control(116,red)).
neg(next_control(117,blue)).
neg(next_control(117,cyan)).
neg(next_control(117,orange)).
neg(next_control(118,blue)).
neg(next_control(118,cyan)).
neg(next_control(118,red)).
neg(next_control(119,blue)).
neg(next_control(119,orange)).
neg(next_control(119,red)).
neg(next_control(12,blue)).
neg(next_control(12,cyan)).
neg(next_control(12,orange)).
neg(next_control(120,blue)).
neg(next_control(120,cyan)).
neg(next_control(120,red)).
neg(next_control(121,cyan)).
neg(next_control(121,orange)).
neg(next_control(121,red)).
neg(next_control(122,cyan)).
neg(next_control(122,orange)).
neg(next_control(122,red)).
neg(next_control(123,blue)).
neg(next_control(123,orange)).
neg(next_control(123,red)).
neg(next_control(124,blue)).
neg(next_control(124,orange)).
neg(next_control(124,red)).
neg(next_control(125,blue)).
neg(next_control(125,orange)).
neg(next_control(125,red)).
neg(next_control(126,cyan)).
neg(next_control(126,orange)).
neg(next_control(126,red)).
neg(next_control(127,blue)).
neg(next_control(127,cyan)).
neg(next_control(127,red)).
neg(next_control(128,cyan)).
neg(next_control(128,orange)).
neg(next_control(128,red)).
neg(next_control(129,blue)).
neg(next_control(129,cyan)).
neg(next_control(129,orange)).
neg(next_control(13,blue)).
neg(next_control(13,cyan)).
neg(next_control(13,red)).
neg(next_control(130,blue)).
neg(next_control(130,cyan)).
neg(next_control(130,orange)).
neg(next_control(131,blue)).
neg(next_control(131,cyan)).
neg(next_control(131,orange)).
neg(next_control(132,blue)).
neg(next_control(132,cyan)).
neg(next_control(132,red)).
neg(next_control(133,blue)).
neg(next_control(133,cyan)).
neg(next_control(133,orange)).
neg(next_control(134,blue)).
neg(next_control(134,orange)).
neg(next_control(134,red)).
neg(next_control(135,cyan)).
neg(next_control(135,orange)).
neg(next_control(135,red)).
neg(next_control(136,blue)).
neg(next_control(136,cyan)).
neg(next_control(136,orange)).
neg(next_control(137,blue)).
neg(next_control(137,cyan)).
neg(next_control(137,red)).
neg(next_control(138,blue)).
neg(next_control(138,cyan)).
neg(next_control(138,orange)).
neg(next_control(139,blue)).
neg(next_control(139,cyan)).
neg(next_control(139,red)).
neg(next_control(14,cyan)).
neg(next_control(14,orange)).
neg(next_control(14,red)).
neg(next_control(140,blue)).
neg(next_control(140,cyan)).
neg(next_control(140,red)).
neg(next_control(141,blue)).
neg(next_control(141,cyan)).
neg(next_control(141,orange)).
neg(next_control(142,blue)).
neg(next_control(142,cyan)).
neg(next_control(142,orange)).
neg(next_control(143,blue)).
neg(next_control(143,orange)).
neg(next_control(143,red)).
neg(next_control(144,blue)).
neg(next_control(144,orange)).
neg(next_control(144,red)).
neg(next_control(145,blue)).
neg(next_control(145,cyan)).
neg(next_control(145,orange)).
neg(next_control(146,cyan)).
neg(next_control(146,orange)).
neg(next_control(146,red)).
neg(next_control(147,blue)).
neg(next_control(147,cyan)).
neg(next_control(147,red)).
neg(next_control(148,blue)).
neg(next_control(148,cyan)).
neg(next_control(148,orange)).
neg(next_control(149,blue)).
neg(next_control(149,cyan)).
neg(next_control(149,orange)).
neg(next_control(15,blue)).
neg(next_control(15,orange)).
neg(next_control(15,red)).
neg(next_control(150,blue)).
neg(next_control(150,cyan)).
neg(next_control(150,red)).
neg(next_control(151,blue)).
neg(next_control(151,cyan)).
neg(next_control(151,orange)).
neg(next_control(152,blue)).
neg(next_control(152,cyan)).
neg(next_control(152,red)).
neg(next_control(153,blue)).
neg(next_control(153,orange)).
neg(next_control(153,red)).
neg(next_control(154,blue)).
neg(next_control(154,cyan)).
neg(next_control(154,orange)).
neg(next_control(155,cyan)).
neg(next_control(155,orange)).
neg(next_control(155,red)).
neg(next_control(156,blue)).
neg(next_control(156,cyan)).
neg(next_control(156,red)).
neg(next_control(157,blue)).
neg(next_control(157,cyan)).
neg(next_control(157,orange)).
neg(next_control(158,blue)).
neg(next_control(158,cyan)).
neg(next_control(158,red)).
neg(next_control(159,blue)).
neg(next_control(159,orange)).
neg(next_control(159,red)).
neg(next_control(16,blue)).
neg(next_control(16,cyan)).
neg(next_control(16,orange)).
neg(next_control(160,blue)).
neg(next_control(160,cyan)).
neg(next_control(160,orange)).
neg(next_control(161,blue)).
neg(next_control(161,cyan)).
neg(next_control(161,orange)).
neg(next_control(162,cyan)).
neg(next_control(162,orange)).
neg(next_control(162,red)).
neg(next_control(163,cyan)).
neg(next_control(163,orange)).
neg(next_control(163,red)).
neg(next_control(164,blue)).
neg(next_control(164,cyan)).
neg(next_control(164,orange)).
neg(next_control(165,blue)).
neg(next_control(165,cyan)).
neg(next_control(165,orange)).
neg(next_control(166,blue)).
neg(next_control(166,cyan)).
neg(next_control(166,orange)).
neg(next_control(167,cyan)).
neg(next_control(167,orange)).
neg(next_control(167,red)).
neg(next_control(168,blue)).
neg(next_control(168,orange)).
neg(next_control(168,red)).
neg(next_control(169,cyan)).
neg(next_control(169,orange)).
neg(next_control(169,red)).
neg(next_control(17,blue)).
neg(next_control(17,orange)).
neg(next_control(17,red)).
neg(next_control(170,blue)).
neg(next_control(170,orange)).
neg(next_control(170,red)).
neg(next_control(171,blue)).
neg(next_control(171,cyan)).
neg(next_control(171,orange)).
neg(next_control(172,blue)).
neg(next_control(172,cyan)).
neg(next_control(172,red)).
neg(next_control(173,blue)).
neg(next_control(173,cyan)).
neg(next_control(173,orange)).
neg(next_control(174,blue)).
neg(next_control(174,cyan)).
neg(next_control(174,red)).
neg(next_control(175,cyan)).
neg(next_control(175,orange)).
neg(next_control(175,red)).
neg(next_control(176,blue)).
neg(next_control(176,cyan)).
neg(next_control(176,orange)).
neg(next_control(177,blue)).
neg(next_control(177,cyan)).
neg(next_control(177,orange)).
neg(next_control(178,blue)).
neg(next_control(178,cyan)).
neg(next_control(178,red)).
neg(next_control(179,cyan)).
neg(next_control(179,orange)).
neg(next_control(179,red)).
neg(next_control(18,blue)).
neg(next_control(18,cyan)).
neg(next_control(18,orange)).
neg(next_control(180,cyan)).
neg(next_control(180,orange)).
neg(next_control(180,red)).
neg(next_control(181,blue)).
neg(next_control(181,cyan)).
neg(next_control(181,orange)).
neg(next_control(182,blue)).
neg(next_control(182,cyan)).
neg(next_control(182,orange)).
neg(next_control(183,blue)).
neg(next_control(183,cyan)).
neg(next_control(183,red)).
neg(next_control(184,cyan)).
neg(next_control(184,orange)).
neg(next_control(184,red)).
neg(next_control(185,blue)).
neg(next_control(185,orange)).
neg(next_control(185,red)).
neg(next_control(186,cyan)).
neg(next_control(186,orange)).
neg(next_control(186,red)).
neg(next_control(187,blue)).
neg(next_control(187,cyan)).
neg(next_control(187,orange)).
neg(next_control(188,blue)).
neg(next_control(188,cyan)).
neg(next_control(188,red)).
neg(next_control(189,blue)).
neg(next_control(189,cyan)).
neg(next_control(189,red)).
neg(next_control(19,blue)).
neg(next_control(19,cyan)).
neg(next_control(19,orange)).
neg(next_control(190,blue)).
neg(next_control(190,cyan)).
neg(next_control(190,orange)).
neg(next_control(191,blue)).
neg(next_control(191,cyan)).
neg(next_control(191,red)).
neg(next_control(192,cyan)).
neg(next_control(192,orange)).
neg(next_control(192,red)).
neg(next_control(193,cyan)).
neg(next_control(193,orange)).
neg(next_control(193,red)).
neg(next_control(194,blue)).
neg(next_control(194,cyan)).
neg(next_control(194,orange)).
neg(next_control(195,blue)).
neg(next_control(195,cyan)).
neg(next_control(195,orange)).
neg(next_control(196,blue)).
neg(next_control(196,orange)).
neg(next_control(196,red)).
neg(next_control(197,blue)).
neg(next_control(197,cyan)).
neg(next_control(197,orange)).
neg(next_control(198,blue)).
neg(next_control(198,orange)).
neg(next_control(198,red)).
neg(next_control(199,cyan)).
neg(next_control(199,orange)).
neg(next_control(199,red)).
neg(next_control(2,blue)).
neg(next_control(2,cyan)).
neg(next_control(2,red)).
neg(next_control(20,blue)).
neg(next_control(20,orange)).
neg(next_control(20,red)).
neg(next_control(200,cyan)).
neg(next_control(200,orange)).
neg(next_control(200,red)).
neg(next_control(201,blue)).
neg(next_control(201,cyan)).
neg(next_control(201,orange)).
neg(next_control(202,blue)).
neg(next_control(202,orange)).
neg(next_control(202,red)).
neg(next_control(203,blue)).
neg(next_control(203,orange)).
neg(next_control(203,red)).
neg(next_control(204,blue)).
neg(next_control(204,cyan)).
neg(next_control(204,orange)).
neg(next_control(205,blue)).
neg(next_control(205,orange)).
neg(next_control(205,red)).
neg(next_control(206,cyan)).
neg(next_control(206,orange)).
neg(next_control(206,red)).
neg(next_control(207,cyan)).
neg(next_control(207,orange)).
neg(next_control(207,red)).
neg(next_control(208,blue)).
neg(next_control(208,cyan)).
neg(next_control(208,orange)).
neg(next_control(209,blue)).
neg(next_control(209,cyan)).
neg(next_control(209,red)).
neg(next_control(21,blue)).
neg(next_control(21,cyan)).
neg(next_control(21,red)).
neg(next_control(210,cyan)).
neg(next_control(210,orange)).
neg(next_control(210,red)).
neg(next_control(211,blue)).
neg(next_control(211,cyan)).
neg(next_control(211,red)).
neg(next_control(212,blue)).
neg(next_control(212,cyan)).
neg(next_control(212,red)).
neg(next_control(213,blue)).
neg(next_control(213,orange)).
neg(next_control(213,red)).
neg(next_control(214,blue)).
neg(next_control(214,orange)).
neg(next_control(214,red)).
neg(next_control(215,blue)).
neg(next_control(215,orange)).
neg(next_control(215,red)).
neg(next_control(216,blue)).
neg(next_control(216,cyan)).
neg(next_control(216,orange)).
neg(next_control(217,blue)).
neg(next_control(217,cyan)).
neg(next_control(217,orange)).
neg(next_control(218,blue)).
neg(next_control(218,orange)).
neg(next_control(218,red)).
neg(next_control(219,blue)).
neg(next_control(219,orange)).
neg(next_control(219,red)).
neg(next_control(22,blue)).
neg(next_control(22,cyan)).
neg(next_control(22,red)).
neg(next_control(220,blue)).
neg(next_control(220,cyan)).
neg(next_control(220,orange)).
neg(next_control(221,cyan)).
neg(next_control(221,orange)).
neg(next_control(221,red)).
neg(next_control(222,blue)).
neg(next_control(222,cyan)).
neg(next_control(222,red)).
neg(next_control(223,blue)).
neg(next_control(223,orange)).
neg(next_control(223,red)).
neg(next_control(224,blue)).
neg(next_control(224,cyan)).
neg(next_control(224,orange)).
neg(next_control(225,blue)).
neg(next_control(225,cyan)).
neg(next_control(225,red)).
neg(next_control(226,blue)).
neg(next_control(226,cyan)).
neg(next_control(226,orange)).
neg(next_control(227,blue)).
neg(next_control(227,cyan)).
neg(next_control(227,orange)).
neg(next_control(228,blue)).
neg(next_control(228,cyan)).
neg(next_control(228,red)).
neg(next_control(229,blue)).
neg(next_control(229,cyan)).
neg(next_control(229,orange)).
neg(next_control(23,blue)).
neg(next_control(23,orange)).
neg(next_control(23,red)).
neg(next_control(230,blue)).
neg(next_control(230,cyan)).
neg(next_control(230,red)).
neg(next_control(231,cyan)).
neg(next_control(231,orange)).
neg(next_control(231,red)).
neg(next_control(232,blue)).
neg(next_control(232,cyan)).
neg(next_control(232,orange)).
neg(next_control(233,cyan)).
neg(next_control(233,orange)).
neg(next_control(233,red)).
neg(next_control(234,blue)).
neg(next_control(234,orange)).
neg(next_control(234,red)).
neg(next_control(235,blue)).
neg(next_control(235,cyan)).
neg(next_control(235,red)).
neg(next_control(236,cyan)).
neg(next_control(236,orange)).
neg(next_control(236,red)).
neg(next_control(237,blue)).
neg(next_control(237,cyan)).
neg(next_control(237,orange)).
neg(next_control(238,blue)).
neg(next_control(238,cyan)).
neg(next_control(238,red)).
neg(next_control(239,blue)).
neg(next_control(239,cyan)).
neg(next_control(239,orange)).
neg(next_control(24,blue)).
neg(next_control(24,cyan)).
neg(next_control(24,orange)).
neg(next_control(240,cyan)).
neg(next_control(240,orange)).
neg(next_control(240,red)).
neg(next_control(241,cyan)).
neg(next_control(241,orange)).
neg(next_control(241,red)).
neg(next_control(242,blue)).
neg(next_control(242,cyan)).
neg(next_control(242,red)).
neg(next_control(243,blue)).
neg(next_control(243,cyan)).
neg(next_control(243,red)).
neg(next_control(244,cyan)).
neg(next_control(244,orange)).
neg(next_control(244,red)).
neg(next_control(245,blue)).
neg(next_control(245,cyan)).
neg(next_control(245,red)).
neg(next_control(246,blue)).
neg(next_control(246,cyan)).
neg(next_control(246,red)).
neg(next_control(247,blue)).
neg(next_control(247,orange)).
neg(next_control(247,red)).
neg(next_control(248,cyan)).
neg(next_control(248,orange)).
neg(next_control(248,red)).
neg(next_control(249,blue)).
neg(next_control(249,orange)).
neg(next_control(249,red)).
neg(next_control(25,blue)).
neg(next_control(25,cyan)).
neg(next_control(25,orange)).
neg(next_control(250,blue)).
neg(next_control(250,orange)).
neg(next_control(250,red)).
neg(next_control(251,cyan)).
neg(next_control(251,orange)).
neg(next_control(251,red)).
neg(next_control(252,blue)).
neg(next_control(252,cyan)).
neg(next_control(252,orange)).
neg(next_control(253,blue)).
neg(next_control(253,cyan)).
neg(next_control(253,orange)).
neg(next_control(254,blue)).
neg(next_control(254,cyan)).
neg(next_control(254,red)).
neg(next_control(255,cyan)).
neg(next_control(255,orange)).
neg(next_control(255,red)).
neg(next_control(256,cyan)).
neg(next_control(256,orange)).
neg(next_control(256,red)).
neg(next_control(257,cyan)).
neg(next_control(257,orange)).
neg(next_control(257,red)).
neg(next_control(258,blue)).
neg(next_control(258,orange)).
neg(next_control(258,red)).
neg(next_control(259,blue)).
neg(next_control(259,orange)).
neg(next_control(259,red)).
neg(next_control(26,blue)).
neg(next_control(26,orange)).
neg(next_control(26,red)).
neg(next_control(260,cyan)).
neg(next_control(260,orange)).
neg(next_control(260,red)).
neg(next_control(261,blue)).
neg(next_control(261,orange)).
neg(next_control(261,red)).
neg(next_control(262,cyan)).
neg(next_control(262,orange)).
neg(next_control(262,red)).
neg(next_control(263,blue)).
neg(next_control(263,cyan)).
neg(next_control(263,red)).
neg(next_control(264,blue)).
neg(next_control(264,cyan)).
neg(next_control(264,orange)).
neg(next_control(265,cyan)).
neg(next_control(265,orange)).
neg(next_control(265,red)).
neg(next_control(266,blue)).
neg(next_control(266,orange)).
neg(next_control(266,red)).
neg(next_control(267,blue)).
neg(next_control(267,cyan)).
neg(next_control(267,red)).
neg(next_control(268,blue)).
neg(next_control(268,cyan)).
neg(next_control(268,orange)).
neg(next_control(269,blue)).
neg(next_control(269,cyan)).
neg(next_control(269,red)).
neg(next_control(27,blue)).
neg(next_control(27,cyan)).
neg(next_control(27,orange)).
neg(next_control(270,cyan)).
neg(next_control(270,orange)).
neg(next_control(270,red)).
neg(next_control(271,blue)).
neg(next_control(271,orange)).
neg(next_control(271,red)).
neg(next_control(272,blue)).
neg(next_control(272,cyan)).
neg(next_control(272,orange)).
neg(next_control(273,cyan)).
neg(next_control(273,orange)).
neg(next_control(273,red)).
neg(next_control(274,blue)).
neg(next_control(274,cyan)).
neg(next_control(274,red)).
neg(next_control(275,blue)).
neg(next_control(275,cyan)).
neg(next_control(275,orange)).
neg(next_control(276,blue)).
neg(next_control(276,cyan)).
neg(next_control(276,orange)).
neg(next_control(277,blue)).
neg(next_control(277,orange)).
neg(next_control(277,red)).
neg(next_control(278,blue)).
neg(next_control(278,orange)).
neg(next_control(278,red)).
neg(next_control(279,blue)).
neg(next_control(279,orange)).
neg(next_control(279,red)).
neg(next_control(28,blue)).
neg(next_control(28,cyan)).
neg(next_control(28,orange)).
neg(next_control(280,cyan)).
neg(next_control(280,orange)).
neg(next_control(280,red)).
neg(next_control(281,blue)).
neg(next_control(281,cyan)).
neg(next_control(281,red)).
neg(next_control(282,blue)).
neg(next_control(282,orange)).
neg(next_control(282,red)).
neg(next_control(283,cyan)).
neg(next_control(283,orange)).
neg(next_control(283,red)).
neg(next_control(284,blue)).
neg(next_control(284,cyan)).
neg(next_control(284,red)).
neg(next_control(285,blue)).
neg(next_control(285,cyan)).
neg(next_control(285,red)).
neg(next_control(286,blue)).
neg(next_control(286,cyan)).
neg(next_control(286,red)).
neg(next_control(287,blue)).
neg(next_control(287,cyan)).
neg(next_control(287,red)).
neg(next_control(288,cyan)).
neg(next_control(288,orange)).
neg(next_control(288,red)).
neg(next_control(289,blue)).
neg(next_control(289,cyan)).
neg(next_control(289,red)).
neg(next_control(29,blue)).
neg(next_control(29,cyan)).
neg(next_control(29,orange)).
neg(next_control(290,blue)).
neg(next_control(290,cyan)).
neg(next_control(290,orange)).
neg(next_control(291,cyan)).
neg(next_control(291,orange)).
neg(next_control(291,red)).
neg(next_control(292,blue)).
neg(next_control(292,cyan)).
neg(next_control(292,red)).
neg(next_control(293,blue)).
neg(next_control(293,cyan)).
neg(next_control(293,red)).
neg(next_control(294,blue)).
neg(next_control(294,cyan)).
neg(next_control(294,orange)).
neg(next_control(295,blue)).
neg(next_control(295,cyan)).
neg(next_control(295,red)).
neg(next_control(296,cyan)).
neg(next_control(296,orange)).
neg(next_control(296,red)).
neg(next_control(297,blue)).
neg(next_control(297,orange)).
neg(next_control(297,red)).
neg(next_control(298,cyan)).
neg(next_control(298,orange)).
neg(next_control(298,red)).
neg(next_control(299,blue)).
neg(next_control(299,orange)).
neg(next_control(299,red)).
neg(next_control(3,blue)).
neg(next_control(3,orange)).
neg(next_control(3,red)).
neg(next_control(30,blue)).
neg(next_control(30,orange)).
neg(next_control(30,red)).
neg(next_control(300,cyan)).
neg(next_control(300,orange)).
neg(next_control(300,red)).
neg(next_control(301,blue)).
neg(next_control(301,orange)).
neg(next_control(301,red)).
neg(next_control(302,blue)).
neg(next_control(302,cyan)).
neg(next_control(302,red)).
neg(next_control(303,cyan)).
neg(next_control(303,orange)).
neg(next_control(303,red)).
neg(next_control(304,cyan)).
neg(next_control(304,orange)).
neg(next_control(304,red)).
neg(next_control(305,cyan)).
neg(next_control(305,orange)).
neg(next_control(305,red)).
neg(next_control(306,blue)).
neg(next_control(306,orange)).
neg(next_control(306,red)).
neg(next_control(307,blue)).
neg(next_control(307,orange)).
neg(next_control(307,red)).
neg(next_control(308,blue)).
neg(next_control(308,cyan)).
neg(next_control(308,orange)).
neg(next_control(309,blue)).
neg(next_control(309,cyan)).
neg(next_control(309,red)).
neg(next_control(31,blue)).
neg(next_control(31,cyan)).
neg(next_control(31,orange)).
neg(next_control(310,blue)).
neg(next_control(310,cyan)).
neg(next_control(310,red)).
neg(next_control(311,blue)).
neg(next_control(311,cyan)).
neg(next_control(311,orange)).
neg(next_control(312,cyan)).
neg(next_control(312,orange)).
neg(next_control(312,red)).
neg(next_control(313,blue)).
neg(next_control(313,cyan)).
neg(next_control(313,orange)).
neg(next_control(314,blue)).
neg(next_control(314,cyan)).
neg(next_control(314,red)).
neg(next_control(315,blue)).
neg(next_control(315,cyan)).
neg(next_control(315,orange)).
neg(next_control(316,blue)).
neg(next_control(316,orange)).
neg(next_control(316,red)).
neg(next_control(317,blue)).
neg(next_control(317,cyan)).
neg(next_control(317,orange)).
neg(next_control(318,blue)).
neg(next_control(318,cyan)).
neg(next_control(318,orange)).
neg(next_control(319,blue)).
neg(next_control(319,cyan)).
neg(next_control(319,red)).
neg(next_control(32,blue)).
neg(next_control(32,cyan)).
neg(next_control(32,orange)).
neg(next_control(320,blue)).
neg(next_control(320,cyan)).
neg(next_control(320,orange)).
neg(next_control(321,blue)).
neg(next_control(321,cyan)).
neg(next_control(321,orange)).
neg(next_control(322,blue)).
neg(next_control(322,cyan)).
neg(next_control(322,orange)).
neg(next_control(323,blue)).
neg(next_control(323,orange)).
neg(next_control(323,red)).
neg(next_control(324,blue)).
neg(next_control(324,cyan)).
neg(next_control(324,red)).
neg(next_control(325,cyan)).
neg(next_control(325,orange)).
neg(next_control(325,red)).
neg(next_control(326,cyan)).
neg(next_control(326,orange)).
neg(next_control(326,red)).
neg(next_control(327,blue)).
neg(next_control(327,cyan)).
neg(next_control(327,red)).
neg(next_control(328,blue)).
neg(next_control(328,cyan)).
neg(next_control(328,orange)).
neg(next_control(329,blue)).
neg(next_control(329,cyan)).
neg(next_control(329,red)).
neg(next_control(33,cyan)).
neg(next_control(33,orange)).
neg(next_control(33,red)).
neg(next_control(330,blue)).
neg(next_control(330,orange)).
neg(next_control(330,red)).
neg(next_control(331,cyan)).
neg(next_control(331,orange)).
neg(next_control(331,red)).
neg(next_control(332,blue)).
neg(next_control(332,orange)).
neg(next_control(332,red)).
neg(next_control(333,blue)).
neg(next_control(333,cyan)).
neg(next_control(333,red)).
neg(next_control(334,blue)).
neg(next_control(334,cyan)).
neg(next_control(334,orange)).
neg(next_control(335,blue)).
neg(next_control(335,orange)).
neg(next_control(335,red)).
neg(next_control(336,blue)).
neg(next_control(336,cyan)).
neg(next_control(336,red)).
neg(next_control(337,blue)).
neg(next_control(337,cyan)).
neg(next_control(337,orange)).
neg(next_control(338,cyan)).
neg(next_control(338,orange)).
neg(next_control(338,red)).
neg(next_control(339,blue)).
neg(next_control(339,cyan)).
neg(next_control(339,red)).
neg(next_control(34,cyan)).
neg(next_control(34,orange)).
neg(next_control(34,red)).
neg(next_control(340,blue)).
neg(next_control(340,cyan)).
neg(next_control(340,red)).
neg(next_control(341,blue)).
neg(next_control(341,cyan)).
neg(next_control(341,red)).
neg(next_control(342,cyan)).
neg(next_control(342,orange)).
neg(next_control(342,red)).
neg(next_control(343,cyan)).
neg(next_control(343,orange)).
neg(next_control(343,red)).
neg(next_control(344,cyan)).
neg(next_control(344,orange)).
neg(next_control(344,red)).
neg(next_control(345,blue)).
neg(next_control(345,cyan)).
neg(next_control(345,orange)).
neg(next_control(346,cyan)).
neg(next_control(346,orange)).
neg(next_control(346,red)).
neg(next_control(347,blue)).
neg(next_control(347,cyan)).
neg(next_control(347,orange)).
neg(next_control(348,blue)).
neg(next_control(348,cyan)).
neg(next_control(348,red)).
neg(next_control(349,blue)).
neg(next_control(349,cyan)).
neg(next_control(349,red)).
neg(next_control(35,cyan)).
neg(next_control(35,orange)).
neg(next_control(35,red)).
neg(next_control(350,blue)).
neg(next_control(350,orange)).
neg(next_control(350,red)).
neg(next_control(351,blue)).
neg(next_control(351,orange)).
neg(next_control(351,red)).
neg(next_control(352,cyan)).
neg(next_control(352,orange)).
neg(next_control(352,red)).
neg(next_control(353,cyan)).
neg(next_control(353,orange)).
neg(next_control(353,red)).
neg(next_control(354,blue)).
neg(next_control(354,cyan)).
neg(next_control(354,orange)).
neg(next_control(355,cyan)).
neg(next_control(355,orange)).
neg(next_control(355,red)).
neg(next_control(356,blue)).
neg(next_control(356,orange)).
neg(next_control(356,red)).
neg(next_control(357,blue)).
neg(next_control(357,cyan)).
neg(next_control(357,red)).
neg(next_control(358,blue)).
neg(next_control(358,cyan)).
neg(next_control(358,orange)).
neg(next_control(359,cyan)).
neg(next_control(359,orange)).
neg(next_control(359,red)).
neg(next_control(36,blue)).
neg(next_control(36,orange)).
neg(next_control(36,red)).
neg(next_control(360,cyan)).
neg(next_control(360,orange)).
neg(next_control(360,red)).
neg(next_control(361,blue)).
neg(next_control(361,cyan)).
neg(next_control(361,orange)).
neg(next_control(362,blue)).
neg(next_control(362,cyan)).
neg(next_control(362,orange)).
neg(next_control(363,blue)).
neg(next_control(363,cyan)).
neg(next_control(363,orange)).
neg(next_control(364,blue)).
neg(next_control(364,cyan)).
neg(next_control(364,red)).
neg(next_control(365,cyan)).
neg(next_control(365,orange)).
neg(next_control(365,red)).
neg(next_control(366,blue)).
neg(next_control(366,cyan)).
neg(next_control(366,orange)).
neg(next_control(367,cyan)).
neg(next_control(367,orange)).
neg(next_control(367,red)).
neg(next_control(368,blue)).
neg(next_control(368,cyan)).
neg(next_control(368,red)).
neg(next_control(369,cyan)).
neg(next_control(369,orange)).
neg(next_control(369,red)).
neg(next_control(37,blue)).
neg(next_control(37,cyan)).
neg(next_control(37,red)).
neg(next_control(370,blue)).
neg(next_control(370,cyan)).
neg(next_control(370,orange)).
neg(next_control(371,cyan)).
neg(next_control(371,orange)).
neg(next_control(371,red)).
neg(next_control(372,cyan)).
neg(next_control(372,orange)).
neg(next_control(372,red)).
neg(next_control(373,blue)).
neg(next_control(373,cyan)).
neg(next_control(373,orange)).
neg(next_control(374,blue)).
neg(next_control(374,cyan)).
neg(next_control(374,red)).
neg(next_control(375,blue)).
neg(next_control(375,orange)).
neg(next_control(375,red)).
neg(next_control(376,blue)).
neg(next_control(376,cyan)).
neg(next_control(376,red)).
neg(next_control(377,blue)).
neg(next_control(377,orange)).
neg(next_control(377,red)).
neg(next_control(378,cyan)).
neg(next_control(378,orange)).
neg(next_control(378,red)).
neg(next_control(379,blue)).
neg(next_control(379,cyan)).
neg(next_control(379,orange)).
neg(next_control(38,blue)).
neg(next_control(38,cyan)).
neg(next_control(38,red)).
neg(next_control(380,blue)).
neg(next_control(380,cyan)).
neg(next_control(380,orange)).
neg(next_control(381,blue)).
neg(next_control(381,orange)).
neg(next_control(381,red)).
neg(next_control(382,blue)).
neg(next_control(382,cyan)).
neg(next_control(382,red)).
neg(next_control(383,blue)).
neg(next_control(383,cyan)).
neg(next_control(383,red)).
neg(next_control(384,cyan)).
neg(next_control(384,orange)).
neg(next_control(384,red)).
neg(next_control(385,cyan)).
neg(next_control(385,orange)).
neg(next_control(385,red)).
neg(next_control(386,blue)).
neg(next_control(386,cyan)).
neg(next_control(386,red)).
neg(next_control(387,blue)).
neg(next_control(387,cyan)).
neg(next_control(387,orange)).
neg(next_control(388,blue)).
neg(next_control(388,orange)).
neg(next_control(388,red)).
neg(next_control(389,blue)).
neg(next_control(389,cyan)).
neg(next_control(389,red)).
neg(next_control(39,blue)).
neg(next_control(39,cyan)).
neg(next_control(39,orange)).
neg(next_control(390,cyan)).
neg(next_control(390,orange)).
neg(next_control(390,red)).
neg(next_control(391,blue)).
neg(next_control(391,orange)).
neg(next_control(391,red)).
neg(next_control(392,blue)).
neg(next_control(392,cyan)).
neg(next_control(392,orange)).
neg(next_control(393,blue)).
neg(next_control(393,orange)).
neg(next_control(393,red)).
neg(next_control(394,blue)).
neg(next_control(394,cyan)).
neg(next_control(394,orange)).
neg(next_control(395,cyan)).
neg(next_control(395,orange)).
neg(next_control(395,red)).
neg(next_control(396,blue)).
neg(next_control(396,cyan)).
neg(next_control(396,red)).
neg(next_control(397,blue)).
neg(next_control(397,cyan)).
neg(next_control(397,red)).
neg(next_control(398,cyan)).
neg(next_control(398,orange)).
neg(next_control(398,red)).
neg(next_control(399,cyan)).
neg(next_control(399,orange)).
neg(next_control(399,red)).
neg(next_control(4,blue)).
neg(next_control(4,cyan)).
neg(next_control(4,red)).
neg(next_control(40,blue)).
neg(next_control(40,orange)).
neg(next_control(40,red)).
neg(next_control(400,blue)).
neg(next_control(400,orange)).
neg(next_control(400,red)).
neg(next_control(401,cyan)).
neg(next_control(401,orange)).
neg(next_control(401,red)).
neg(next_control(402,blue)).
neg(next_control(402,orange)).
neg(next_control(402,red)).
neg(next_control(403,cyan)).
neg(next_control(403,orange)).
neg(next_control(403,red)).
neg(next_control(404,cyan)).
neg(next_control(404,orange)).
neg(next_control(404,red)).
neg(next_control(405,blue)).
neg(next_control(405,cyan)).
neg(next_control(405,red)).
neg(next_control(406,blue)).
neg(next_control(406,cyan)).
neg(next_control(406,orange)).
neg(next_control(407,blue)).
neg(next_control(407,cyan)).
neg(next_control(407,red)).
neg(next_control(408,cyan)).
neg(next_control(408,orange)).
neg(next_control(408,red)).
neg(next_control(409,cyan)).
neg(next_control(409,orange)).
neg(next_control(409,red)).
neg(next_control(41,blue)).
neg(next_control(41,orange)).
neg(next_control(41,red)).
neg(next_control(410,blue)).
neg(next_control(410,cyan)).
neg(next_control(410,orange)).
neg(next_control(411,blue)).
neg(next_control(411,cyan)).
neg(next_control(411,red)).
neg(next_control(412,blue)).
neg(next_control(412,cyan)).
neg(next_control(412,red)).
neg(next_control(413,blue)).
neg(next_control(413,cyan)).
neg(next_control(413,red)).
neg(next_control(414,blue)).
neg(next_control(414,orange)).
neg(next_control(414,red)).
neg(next_control(415,cyan)).
neg(next_control(415,orange)).
neg(next_control(415,red)).
neg(next_control(416,blue)).
neg(next_control(416,cyan)).
neg(next_control(416,orange)).
neg(next_control(417,cyan)).
neg(next_control(417,orange)).
neg(next_control(417,red)).
neg(next_control(418,blue)).
neg(next_control(418,cyan)).
neg(next_control(418,red)).
neg(next_control(419,blue)).
neg(next_control(419,cyan)).
neg(next_control(419,red)).
neg(next_control(42,blue)).
neg(next_control(42,cyan)).
neg(next_control(42,red)).
neg(next_control(420,blue)).
neg(next_control(420,cyan)).
neg(next_control(420,orange)).
neg(next_control(421,blue)).
neg(next_control(421,cyan)).
neg(next_control(421,red)).
neg(next_control(422,blue)).
neg(next_control(422,cyan)).
neg(next_control(422,red)).
neg(next_control(423,blue)).
neg(next_control(423,cyan)).
neg(next_control(423,orange)).
neg(next_control(424,blue)).
neg(next_control(424,cyan)).
neg(next_control(424,orange)).
neg(next_control(425,blue)).
neg(next_control(425,orange)).
neg(next_control(425,red)).
neg(next_control(426,blue)).
neg(next_control(426,cyan)).
neg(next_control(426,red)).
neg(next_control(427,cyan)).
neg(next_control(427,orange)).
neg(next_control(427,red)).
neg(next_control(428,blue)).
neg(next_control(428,cyan)).
neg(next_control(428,orange)).
neg(next_control(429,cyan)).
neg(next_control(429,orange)).
neg(next_control(429,red)).
neg(next_control(43,cyan)).
neg(next_control(43,orange)).
neg(next_control(43,red)).
neg(next_control(430,blue)).
neg(next_control(430,cyan)).
neg(next_control(430,red)).
neg(next_control(431,blue)).
neg(next_control(431,orange)).
neg(next_control(431,red)).
neg(next_control(432,blue)).
neg(next_control(432,orange)).
neg(next_control(432,red)).
neg(next_control(433,blue)).
neg(next_control(433,orange)).
neg(next_control(433,red)).
neg(next_control(434,blue)).
neg(next_control(434,cyan)).
neg(next_control(434,orange)).
neg(next_control(435,blue)).
neg(next_control(435,orange)).
neg(next_control(435,red)).
neg(next_control(436,cyan)).
neg(next_control(436,orange)).
neg(next_control(436,red)).
neg(next_control(437,blue)).
neg(next_control(437,cyan)).
neg(next_control(437,red)).
neg(next_control(438,blue)).
neg(next_control(438,cyan)).
neg(next_control(438,red)).
neg(next_control(439,blue)).
neg(next_control(439,cyan)).
neg(next_control(439,orange)).
neg(next_control(44,blue)).
neg(next_control(44,cyan)).
neg(next_control(44,red)).
neg(next_control(440,blue)).
neg(next_control(440,orange)).
neg(next_control(440,red)).
neg(next_control(441,blue)).
neg(next_control(441,orange)).
neg(next_control(441,red)).
neg(next_control(442,cyan)).
neg(next_control(442,orange)).
neg(next_control(442,red)).
neg(next_control(443,blue)).
neg(next_control(443,cyan)).
neg(next_control(443,red)).
neg(next_control(444,blue)).
neg(next_control(444,orange)).
neg(next_control(444,red)).
neg(next_control(445,blue)).
neg(next_control(445,cyan)).
neg(next_control(445,orange)).
neg(next_control(446,blue)).
neg(next_control(446,orange)).
neg(next_control(446,red)).
neg(next_control(447,cyan)).
neg(next_control(447,orange)).
neg(next_control(447,red)).
neg(next_control(448,blue)).
neg(next_control(448,cyan)).
neg(next_control(448,red)).
neg(next_control(449,blue)).
neg(next_control(449,cyan)).
neg(next_control(449,red)).
neg(next_control(45,blue)).
neg(next_control(45,cyan)).
neg(next_control(45,red)).
neg(next_control(450,cyan)).
neg(next_control(450,orange)).
neg(next_control(450,red)).
neg(next_control(451,cyan)).
neg(next_control(451,orange)).
neg(next_control(451,red)).
neg(next_control(452,blue)).
neg(next_control(452,orange)).
neg(next_control(452,red)).
neg(next_control(453,blue)).
neg(next_control(453,orange)).
neg(next_control(453,red)).
neg(next_control(454,blue)).
neg(next_control(454,orange)).
neg(next_control(454,red)).
neg(next_control(455,blue)).
neg(next_control(455,cyan)).
neg(next_control(455,red)).
neg(next_control(456,blue)).
neg(next_control(456,orange)).
neg(next_control(456,red)).
neg(next_control(457,cyan)).
neg(next_control(457,orange)).
neg(next_control(457,red)).
neg(next_control(458,cyan)).
neg(next_control(458,orange)).
neg(next_control(458,red)).
neg(next_control(459,cyan)).
neg(next_control(459,orange)).
neg(next_control(459,red)).
neg(next_control(46,blue)).
neg(next_control(46,orange)).
neg(next_control(46,red)).
neg(next_control(460,blue)).
neg(next_control(460,cyan)).
neg(next_control(460,red)).
neg(next_control(461,blue)).
neg(next_control(461,cyan)).
neg(next_control(461,red)).
neg(next_control(462,blue)).
neg(next_control(462,cyan)).
neg(next_control(462,red)).
neg(next_control(463,blue)).
neg(next_control(463,cyan)).
neg(next_control(463,orange)).
neg(next_control(464,blue)).
neg(next_control(464,cyan)).
neg(next_control(464,orange)).
neg(next_control(465,blue)).
neg(next_control(465,cyan)).
neg(next_control(465,red)).
neg(next_control(466,cyan)).
neg(next_control(466,orange)).
neg(next_control(466,red)).
neg(next_control(467,blue)).
neg(next_control(467,cyan)).
neg(next_control(467,red)).
neg(next_control(468,blue)).
neg(next_control(468,orange)).
neg(next_control(468,red)).
neg(next_control(469,blue)).
neg(next_control(469,orange)).
neg(next_control(469,red)).
neg(next_control(47,blue)).
neg(next_control(47,cyan)).
neg(next_control(47,orange)).
neg(next_control(470,cyan)).
neg(next_control(470,orange)).
neg(next_control(470,red)).
neg(next_control(471,blue)).
neg(next_control(471,cyan)).
neg(next_control(471,orange)).
neg(next_control(472,blue)).
neg(next_control(472,cyan)).
neg(next_control(472,orange)).
neg(next_control(473,blue)).
neg(next_control(473,cyan)).
neg(next_control(473,red)).
neg(next_control(474,blue)).
neg(next_control(474,cyan)).
neg(next_control(474,red)).
neg(next_control(475,blue)).
neg(next_control(475,cyan)).
neg(next_control(475,red)).
neg(next_control(476,cyan)).
neg(next_control(476,orange)).
neg(next_control(476,red)).
neg(next_control(477,blue)).
neg(next_control(477,cyan)).
neg(next_control(477,orange)).
neg(next_control(478,blue)).
neg(next_control(478,cyan)).
neg(next_control(478,orange)).
neg(next_control(479,blue)).
neg(next_control(479,cyan)).
neg(next_control(479,orange)).
neg(next_control(48,blue)).
neg(next_control(48,cyan)).
neg(next_control(48,orange)).
neg(next_control(480,cyan)).
neg(next_control(480,orange)).
neg(next_control(480,red)).
neg(next_control(481,cyan)).
neg(next_control(481,orange)).
neg(next_control(481,red)).
neg(next_control(482,blue)).
neg(next_control(482,orange)).
neg(next_control(482,red)).
neg(next_control(483,blue)).
neg(next_control(483,orange)).
neg(next_control(483,red)).
neg(next_control(484,cyan)).
neg(next_control(484,orange)).
neg(next_control(484,red)).
neg(next_control(485,cyan)).
neg(next_control(485,orange)).
neg(next_control(485,red)).
neg(next_control(486,blue)).
neg(next_control(486,cyan)).
neg(next_control(486,orange)).
neg(next_control(487,cyan)).
neg(next_control(487,orange)).
neg(next_control(487,red)).
neg(next_control(488,blue)).
neg(next_control(488,orange)).
neg(next_control(488,red)).
neg(next_control(489,blue)).
neg(next_control(489,cyan)).
neg(next_control(489,red)).
neg(next_control(49,cyan)).
neg(next_control(49,orange)).
neg(next_control(49,red)).
neg(next_control(490,blue)).
neg(next_control(490,cyan)).
neg(next_control(490,red)).
neg(next_control(491,blue)).
neg(next_control(491,cyan)).
neg(next_control(491,orange)).
neg(next_control(492,blue)).
neg(next_control(492,cyan)).
neg(next_control(492,red)).
neg(next_control(493,blue)).
neg(next_control(493,orange)).
neg(next_control(493,red)).
neg(next_control(494,blue)).
neg(next_control(494,orange)).
neg(next_control(494,red)).
neg(next_control(495,blue)).
neg(next_control(495,cyan)).
neg(next_control(495,orange)).
neg(next_control(496,cyan)).
neg(next_control(496,orange)).
neg(next_control(496,red)).
neg(next_control(497,blue)).
neg(next_control(497,orange)).
neg(next_control(497,red)).
neg(next_control(498,cyan)).
neg(next_control(498,orange)).
neg(next_control(498,red)).
neg(next_control(499,blue)).
neg(next_control(499,orange)).
neg(next_control(499,red)).
neg(next_control(5,cyan)).
neg(next_control(5,orange)).
neg(next_control(5,red)).
neg(next_control(50,cyan)).
neg(next_control(50,orange)).
neg(next_control(50,red)).
neg(next_control(500,blue)).
neg(next_control(500,orange)).
neg(next_control(500,red)).
neg(next_control(51,cyan)).
neg(next_control(51,orange)).
neg(next_control(51,red)).
neg(next_control(52,blue)).
neg(next_control(52,orange)).
neg(next_control(52,red)).
neg(next_control(53,cyan)).
neg(next_control(53,orange)).
neg(next_control(53,red)).
neg(next_control(54,blue)).
neg(next_control(54,orange)).
neg(next_control(54,red)).
neg(next_control(55,blue)).
neg(next_control(55,cyan)).
neg(next_control(55,red)).
neg(next_control(56,cyan)).
neg(next_control(56,orange)).
neg(next_control(56,red)).
neg(next_control(57,blue)).
neg(next_control(57,cyan)).
neg(next_control(57,red)).
neg(next_control(58,blue)).
neg(next_control(58,orange)).
neg(next_control(58,red)).
neg(next_control(59,blue)).
neg(next_control(59,orange)).
neg(next_control(59,red)).
neg(next_control(6,blue)).
neg(next_control(6,cyan)).
neg(next_control(6,orange)).
neg(next_control(60,blue)).
neg(next_control(60,cyan)).
neg(next_control(60,red)).
neg(next_control(61,blue)).
neg(next_control(61,orange)).
neg(next_control(61,red)).
neg(next_control(62,blue)).
neg(next_control(62,orange)).
neg(next_control(62,red)).
neg(next_control(63,blue)).
neg(next_control(63,cyan)).
neg(next_control(63,orange)).
neg(next_control(64,blue)).
neg(next_control(64,cyan)).
neg(next_control(64,red)).
neg(next_control(65,blue)).
neg(next_control(65,cyan)).
neg(next_control(65,red)).
neg(next_control(66,blue)).
neg(next_control(66,cyan)).
neg(next_control(66,orange)).
neg(next_control(67,blue)).
neg(next_control(67,cyan)).
neg(next_control(67,red)).
neg(next_control(68,blue)).
neg(next_control(68,cyan)).
neg(next_control(68,orange)).
neg(next_control(69,blue)).
neg(next_control(69,cyan)).
neg(next_control(69,orange)).
neg(next_control(7,blue)).
neg(next_control(7,orange)).
neg(next_control(7,red)).
neg(next_control(70,blue)).
neg(next_control(70,cyan)).
neg(next_control(70,orange)).
neg(next_control(71,cyan)).
neg(next_control(71,orange)).
neg(next_control(71,red)).
neg(next_control(72,blue)).
neg(next_control(72,orange)).
neg(next_control(72,red)).
neg(next_control(73,blue)).
neg(next_control(73,orange)).
neg(next_control(73,red)).
neg(next_control(74,cyan)).
neg(next_control(74,orange)).
neg(next_control(74,red)).
neg(next_control(75,blue)).
neg(next_control(75,cyan)).
neg(next_control(75,red)).
neg(next_control(76,cyan)).
neg(next_control(76,orange)).
neg(next_control(76,red)).
neg(next_control(77,blue)).
neg(next_control(77,orange)).
neg(next_control(77,red)).
neg(next_control(78,blue)).
neg(next_control(78,orange)).
neg(next_control(78,red)).
neg(next_control(79,blue)).
neg(next_control(79,orange)).
neg(next_control(79,red)).
neg(next_control(8,blue)).
neg(next_control(8,cyan)).
neg(next_control(8,orange)).
neg(next_control(80,blue)).
neg(next_control(80,orange)).
neg(next_control(80,red)).
neg(next_control(81,blue)).
neg(next_control(81,cyan)).
neg(next_control(81,red)).
neg(next_control(82,blue)).
neg(next_control(82,orange)).
neg(next_control(82,red)).
neg(next_control(83,blue)).
neg(next_control(83,cyan)).
neg(next_control(83,red)).
neg(next_control(84,blue)).
neg(next_control(84,cyan)).
neg(next_control(84,red)).
neg(next_control(85,blue)).
neg(next_control(85,orange)).
neg(next_control(85,red)).
neg(next_control(86,blue)).
neg(next_control(86,cyan)).
neg(next_control(86,red)).
neg(next_control(87,blue)).
neg(next_control(87,orange)).
neg(next_control(87,red)).
neg(next_control(88,blue)).
neg(next_control(88,cyan)).
neg(next_control(88,orange)).
neg(next_control(89,blue)).
neg(next_control(89,orange)).
neg(next_control(89,red)).
neg(next_control(9,blue)).
neg(next_control(9,orange)).
neg(next_control(9,red)).
neg(next_control(90,blue)).
neg(next_control(90,orange)).
neg(next_control(90,red)).
neg(next_control(91,cyan)).
neg(next_control(91,orange)).
neg(next_control(91,red)).
neg(next_control(92,blue)).
neg(next_control(92,cyan)).
neg(next_control(92,red)).
neg(next_control(93,blue)).
neg(next_control(93,cyan)).
neg(next_control(93,red)).
neg(next_control(94,cyan)).
neg(next_control(94,orange)).
neg(next_control(94,red)).
neg(next_control(95,blue)).
neg(next_control(95,cyan)).
neg(next_control(95,red)).
neg(next_control(96,blue)).
neg(next_control(96,cyan)).
neg(next_control(96,orange)).
neg(next_control(97,blue)).
neg(next_control(97,cyan)).
neg(next_control(97,red)).
neg(next_control(98,blue)).
neg(next_control(98,orange)).
neg(next_control(98,red)).
neg(next_control(99,cyan)).
neg(next_control(99,orange)).
neg(next_control(99,red)).
pos(next_control(1,orange)).
pos(next_control(10,blue)).
pos(next_control(100,red)).
pos(next_control(101,cyan)).
pos(next_control(102,blue)).
pos(next_control(103,cyan)).
pos(next_control(104,blue)).
pos(next_control(105,orange)).
pos(next_control(106,blue)).
pos(next_control(107,blue)).
pos(next_control(108,blue)).
pos(next_control(109,cyan)).
pos(next_control(11,red)).
pos(next_control(110,blue)).
pos(next_control(111,red)).
pos(next_control(112,cyan)).
pos(next_control(113,blue)).
pos(next_control(114,orange)).
pos(next_control(115,red)).
pos(next_control(116,orange)).
pos(next_control(117,red)).
pos(next_control(118,orange)).
pos(next_control(119,cyan)).
pos(next_control(12,red)).
pos(next_control(120,orange)).
pos(next_control(121,blue)).
pos(next_control(122,blue)).
pos(next_control(123,cyan)).
pos(next_control(124,cyan)).
pos(next_control(125,cyan)).
pos(next_control(126,blue)).
pos(next_control(127,orange)).
pos(next_control(128,blue)).
pos(next_control(129,red)).
pos(next_control(13,orange)).
pos(next_control(130,red)).
pos(next_control(131,red)).
pos(next_control(132,orange)).
pos(next_control(133,red)).
pos(next_control(134,cyan)).
pos(next_control(135,blue)).
pos(next_control(136,red)).
pos(next_control(137,orange)).
pos(next_control(138,red)).
pos(next_control(139,orange)).
pos(next_control(14,blue)).
pos(next_control(140,orange)).
pos(next_control(141,red)).
pos(next_control(142,red)).
pos(next_control(143,cyan)).
pos(next_control(144,cyan)).
pos(next_control(145,red)).
pos(next_control(146,blue)).
pos(next_control(147,orange)).
pos(next_control(148,red)).
pos(next_control(149,red)).
pos(next_control(15,cyan)).
pos(next_control(150,orange)).
pos(next_control(151,red)).
pos(next_control(152,orange)).
pos(next_control(153,cyan)).
pos(next_control(154,red)).
pos(next_control(155,blue)).
pos(next_control(156,orange)).
pos(next_control(157,red)).
pos(next_control(158,orange)).
pos(next_control(159,cyan)).
pos(next_control(16,red)).
pos(next_control(160,red)).
pos(next_control(161,red)).
pos(next_control(162,blue)).
pos(next_control(163,blue)).
pos(next_control(164,red)).
pos(next_control(165,red)).
pos(next_control(166,red)).
pos(next_control(167,blue)).
pos(next_control(168,cyan)).
pos(next_control(169,blue)).
pos(next_control(17,cyan)).
pos(next_control(170,cyan)).
pos(next_control(171,red)).
pos(next_control(172,orange)).
pos(next_control(173,red)).
pos(next_control(174,orange)).
pos(next_control(175,blue)).
pos(next_control(176,red)).
pos(next_control(177,red)).
pos(next_control(178,orange)).
pos(next_control(179,blue)).
pos(next_control(18,red)).
pos(next_control(180,blue)).
pos(next_control(181,red)).
pos(next_control(182,red)).
pos(next_control(183,orange)).
pos(next_control(184,blue)).
pos(next_control(185,cyan)).
pos(next_control(186,blue)).
pos(next_control(187,red)).
pos(next_control(188,orange)).
pos(next_control(189,orange)).
pos(next_control(19,red)).
pos(next_control(190,red)).
pos(next_control(191,orange)).
pos(next_control(192,blue)).
pos(next_control(193,blue)).
pos(next_control(194,red)).
pos(next_control(195,red)).
pos(next_control(196,cyan)).
pos(next_control(197,red)).
pos(next_control(198,cyan)).
pos(next_control(199,blue)).
pos(next_control(2,orange)).
pos(next_control(20,cyan)).
pos(next_control(200,blue)).
pos(next_control(201,red)).
pos(next_control(202,cyan)).
pos(next_control(203,cyan)).
pos(next_control(204,red)).
pos(next_control(205,cyan)).
pos(next_control(206,blue)).
pos(next_control(207,blue)).
pos(next_control(208,red)).
pos(next_control(209,orange)).
pos(next_control(21,orange)).
pos(next_control(210,blue)).
pos(next_control(211,orange)).
pos(next_control(212,orange)).
pos(next_control(213,cyan)).
pos(next_control(214,cyan)).
pos(next_control(215,cyan)).
pos(next_control(216,red)).
pos(next_control(217,red)).
pos(next_control(218,cyan)).
pos(next_control(219,cyan)).
pos(next_control(22,orange)).
pos(next_control(220,red)).
pos(next_control(221,blue)).
pos(next_control(222,orange)).
pos(next_control(223,cyan)).
pos(next_control(224,red)).
pos(next_control(225,orange)).
pos(next_control(226,red)).
pos(next_control(227,red)).
pos(next_control(228,orange)).
pos(next_control(229,red)).
pos(next_control(23,cyan)).
pos(next_control(230,orange)).
pos(next_control(231,blue)).
pos(next_control(232,red)).
pos(next_control(233,blue)).
pos(next_control(234,cyan)).
pos(next_control(235,orange)).
pos(next_control(236,blue)).
pos(next_control(237,red)).
pos(next_control(238,orange)).
pos(next_control(239,red)).
pos(next_control(24,red)).
pos(next_control(240,blue)).
pos(next_control(241,blue)).
pos(next_control(242,orange)).
pos(next_control(243,orange)).
pos(next_control(244,blue)).
pos(next_control(245,orange)).
pos(next_control(246,orange)).
pos(next_control(247,cyan)).
pos(next_control(248,blue)).
pos(next_control(249,cyan)).
pos(next_control(25,red)).
pos(next_control(250,cyan)).
pos(next_control(251,blue)).
pos(next_control(252,red)).
pos(next_control(253,red)).
pos(next_control(254,orange)).
pos(next_control(255,blue)).
pos(next_control(256,blue)).
pos(next_control(257,blue)).
pos(next_control(258,cyan)).
pos(next_control(259,cyan)).
pos(next_control(26,cyan)).
pos(next_control(260,blue)).
pos(next_control(261,cyan)).
pos(next_control(262,blue)).
pos(next_control(263,orange)).
pos(next_control(264,red)).
pos(next_control(265,blue)).
pos(next_control(266,cyan)).
pos(next_control(267,orange)).
pos(next_control(268,red)).
pos(next_control(269,orange)).
pos(next_control(27,red)).
pos(next_control(270,blue)).
pos(next_control(271,cyan)).
pos(next_control(272,red)).
pos(next_control(273,blue)).
pos(next_control(274,orange)).
pos(next_control(275,red)).
pos(next_control(276,red)).
pos(next_control(277,cyan)).
pos(next_control(278,cyan)).
pos(next_control(279,cyan)).
pos(next_control(28,red)).
pos(next_control(280,blue)).
pos(next_control(281,orange)).
pos(next_control(282,cyan)).
pos(next_control(283,blue)).
pos(next_control(284,orange)).
pos(next_control(285,orange)).
pos(next_control(286,orange)).
pos(next_control(287,orange)).
pos(next_control(288,blue)).
pos(next_control(289,orange)).
pos(next_control(29,red)).
pos(next_control(290,red)).
pos(next_control(291,blue)).
pos(next_control(292,orange)).
pos(next_control(293,orange)).
pos(next_control(294,red)).
pos(next_control(295,orange)).
pos(next_control(296,blue)).
pos(next_control(297,cyan)).
pos(next_control(298,blue)).
pos(next_control(299,cyan)).
pos(next_control(3,cyan)).
pos(next_control(30,cyan)).
pos(next_control(300,blue)).
pos(next_control(301,cyan)).
pos(next_control(302,orange)).
pos(next_control(303,blue)).
pos(next_control(304,blue)).
pos(next_control(305,blue)).
pos(next_control(306,cyan)).
pos(next_control(307,cyan)).
pos(next_control(308,red)).
pos(next_control(309,orange)).
pos(next_control(31,red)).
pos(next_control(310,orange)).
pos(next_control(311,red)).
pos(next_control(312,blue)).
pos(next_control(313,red)).
pos(next_control(314,orange)).
pos(next_control(315,red)).
pos(next_control(316,cyan)).
pos(next_control(317,red)).
pos(next_control(318,red)).
pos(next_control(319,orange)).
pos(next_control(32,red)).
pos(next_control(320,red)).
pos(next_control(321,red)).
pos(next_control(322,red)).
pos(next_control(323,cyan)).
pos(next_control(324,orange)).
pos(next_control(325,blue)).
pos(next_control(326,blue)).
pos(next_control(327,orange)).
pos(next_control(328,red)).
pos(next_control(329,orange)).
pos(next_control(33,blue)).
pos(next_control(330,cyan)).
pos(next_control(331,blue)).
pos(next_control(332,cyan)).
pos(next_control(333,orange)).
pos(next_control(334,red)).
pos(next_control(335,cyan)).
pos(next_control(336,orange)).
pos(next_control(337,red)).
pos(next_control(338,blue)).
pos(next_control(339,orange)).
pos(next_control(34,blue)).
pos(next_control(340,orange)).
pos(next_control(341,orange)).
pos(next_control(342,blue)).
pos(next_control(343,blue)).
pos(next_control(344,blue)).
pos(next_control(345,red)).
pos(next_control(346,blue)).
pos(next_control(347,red)).
pos(next_control(348,orange)).
pos(next_control(349,orange)).
pos(next_control(35,blue)).
pos(next_control(350,cyan)).
pos(next_control(351,cyan)).
pos(next_control(352,blue)).
pos(next_control(353,blue)).
pos(next_control(354,red)).
pos(next_control(355,blue)).
pos(next_control(356,cyan)).
pos(next_control(357,orange)).
pos(next_control(358,red)).
pos(next_control(359,blue)).
pos(next_control(36,cyan)).
pos(next_control(360,blue)).
pos(next_control(361,red)).
pos(next_control(362,red)).
pos(next_control(363,red)).
pos(next_control(364,orange)).
pos(next_control(365,blue)).
pos(next_control(366,red)).
pos(next_control(367,blue)).
pos(next_control(368,orange)).
pos(next_control(369,blue)).
pos(next_control(37,orange)).
pos(next_control(370,red)).
pos(next_control(371,blue)).
pos(next_control(372,blue)).
pos(next_control(373,red)).
pos(next_control(374,orange)).
pos(next_control(375,cyan)).
pos(next_control(376,orange)).
pos(next_control(377,cyan)).
pos(next_control(378,blue)).
pos(next_control(379,red)).
pos(next_control(38,orange)).
pos(next_control(380,red)).
pos(next_control(381,cyan)).
pos(next_control(382,orange)).
pos(next_control(383,orange)).
pos(next_control(384,blue)).
pos(next_control(385,blue)).
pos(next_control(386,orange)).
pos(next_control(387,red)).
pos(next_control(388,cyan)).
pos(next_control(389,orange)).
pos(next_control(39,red)).
pos(next_control(390,blue)).
pos(next_control(391,cyan)).
pos(next_control(392,red)).
pos(next_control(393,cyan)).
pos(next_control(394,red)).
pos(next_control(395,blue)).
pos(next_control(396,orange)).
pos(next_control(397,orange)).
pos(next_control(398,blue)).
pos(next_control(399,blue)).
pos(next_control(4,orange)).
pos(next_control(40,cyan)).
pos(next_control(400,cyan)).
pos(next_control(401,blue)).
pos(next_control(402,cyan)).
pos(next_control(403,blue)).
pos(next_control(404,blue)).
pos(next_control(405,orange)).
pos(next_control(406,red)).
pos(next_control(407,orange)).
pos(next_control(408,blue)).
pos(next_control(409,blue)).
pos(next_control(41,cyan)).
pos(next_control(410,red)).
pos(next_control(411,orange)).
pos(next_control(412,orange)).
pos(next_control(413,orange)).
pos(next_control(414,cyan)).
pos(next_control(415,blue)).
pos(next_control(416,red)).
pos(next_control(417,blue)).
pos(next_control(418,orange)).
pos(next_control(419,orange)).
pos(next_control(42,orange)).
pos(next_control(420,red)).
pos(next_control(421,orange)).
pos(next_control(422,orange)).
pos(next_control(423,red)).
pos(next_control(424,red)).
pos(next_control(425,cyan)).
pos(next_control(426,orange)).
pos(next_control(427,blue)).
pos(next_control(428,red)).
pos(next_control(429,blue)).
pos(next_control(43,blue)).
pos(next_control(430,orange)).
pos(next_control(431,cyan)).
pos(next_control(432,cyan)).
pos(next_control(433,cyan)).
pos(next_control(434,red)).
pos(next_control(435,cyan)).
pos(next_control(436,blue)).
pos(next_control(437,orange)).
pos(next_control(438,orange)).
pos(next_control(439,red)).
pos(next_control(44,orange)).
pos(next_control(440,cyan)).
pos(next_control(441,cyan)).
pos(next_control(442,blue)).
pos(next_control(443,orange)).
pos(next_control(444,cyan)).
pos(next_control(445,red)).
pos(next_control(446,cyan)).
pos(next_control(447,blue)).
pos(next_control(448,orange)).
pos(next_control(449,orange)).
pos(next_control(45,orange)).
pos(next_control(450,blue)).
pos(next_control(451,blue)).
pos(next_control(452,cyan)).
pos(next_control(453,cyan)).
pos(next_control(454,cyan)).
pos(next_control(455,orange)).
pos(next_control(456,cyan)).
pos(next_control(457,blue)).
pos(next_control(458,blue)).
pos(next_control(459,blue)).
pos(next_control(46,cyan)).
pos(next_control(460,orange)).
pos(next_control(461,orange)).
pos(next_control(462,orange)).
pos(next_control(463,red)).
pos(next_control(464,red)).
pos(next_control(465,orange)).
pos(next_control(466,blue)).
pos(next_control(467,orange)).
pos(next_control(468,cyan)).
pos(next_control(469,cyan)).
pos(next_control(47,red)).
pos(next_control(470,blue)).
pos(next_control(471,red)).
pos(next_control(472,red)).
pos(next_control(473,orange)).
pos(next_control(474,orange)).
pos(next_control(475,orange)).
pos(next_control(476,blue)).
pos(next_control(477,red)).
pos(next_control(478,red)).
pos(next_control(479,red)).
pos(next_control(48,red)).
pos(next_control(480,blue)).
pos(next_control(481,blue)).
pos(next_control(482,cyan)).
pos(next_control(483,cyan)).
pos(next_control(484,blue)).
pos(next_control(485,blue)).
pos(next_control(486,red)).
pos(next_control(487,blue)).
pos(next_control(488,cyan)).
pos(next_control(489,orange)).
pos(next_control(49,blue)).
pos(next_control(490,orange)).
pos(next_control(491,red)).
pos(next_control(492,orange)).
pos(next_control(493,cyan)).
pos(next_control(494,cyan)).
pos(next_control(495,red)).
pos(next_control(496,blue)).
pos(next_control(497,cyan)).
pos(next_control(498,blue)).
pos(next_control(499,cyan)).
pos(next_control(5,blue)).
pos(next_control(50,blue)).
pos(next_control(500,cyan)).
pos(next_control(51,blue)).
pos(next_control(52,cyan)).
pos(next_control(53,blue)).
pos(next_control(54,cyan)).
pos(next_control(55,orange)).
pos(next_control(56,blue)).
pos(next_control(57,orange)).
pos(next_control(58,cyan)).
pos(next_control(59,cyan)).
pos(next_control(6,red)).
pos(next_control(60,orange)).
pos(next_control(61,cyan)).
pos(next_control(62,cyan)).
pos(next_control(63,red)).
pos(next_control(64,orange)).
pos(next_control(65,orange)).
pos(next_control(66,red)).
pos(next_control(67,orange)).
pos(next_control(68,red)).
pos(next_control(69,red)).
pos(next_control(7,cyan)).
pos(next_control(70,red)).
pos(next_control(71,blue)).
pos(next_control(72,cyan)).
pos(next_control(73,cyan)).
pos(next_control(74,blue)).
pos(next_control(75,orange)).
pos(next_control(76,blue)).
pos(next_control(77,cyan)).
pos(next_control(78,cyan)).
pos(next_control(79,cyan)).
pos(next_control(8,red)).
pos(next_control(80,cyan)).
pos(next_control(81,orange)).
pos(next_control(82,cyan)).
pos(next_control(83,orange)).
pos(next_control(84,orange)).
pos(next_control(85,cyan)).
pos(next_control(86,orange)).
pos(next_control(87,cyan)).
pos(next_control(88,red)).
pos(next_control(89,cyan)).
pos(next_control(9,cyan)).
pos(next_control(90,cyan)).
pos(next_control(91,blue)).
pos(next_control(92,orange)).
pos(next_control(93,orange)).
pos(next_control(94,blue)).
pos(next_control(95,orange)).
pos(next_control(96,red)).
pos(next_control(97,orange)).
pos(next_control(98,cyan)).
pos(next_control(99,blue)).