% Positive examples
pos(move(rooma,roomb,13)).
pos(move(rooma,roomb,19)).
pos(move(rooma,roomb,2)).
pos(move(rooma,roomb,25)).
pos(move(rooma,roomb,30)).
pos(move(rooma,roomb,36)).
pos(move(rooma,roomb,42)).
pos(move(rooma,roomb,48)).
pos(move(rooma,roomb,8)).
pos(move(roomb,rooma,16)).
pos(move(roomb,rooma,22)).
pos(move(roomb,rooma,33)).
pos(move(roomb,rooma,39)).
pos(move(roomb,rooma,45)).
pos(move(roomb,rooma,5)).

% Negative examples
neg(move(rooma,roomb,0)).
neg(move(rooma,roomb,1)).
neg(move(rooma,roomb,10)).
neg(move(rooma,roomb,11)).
neg(move(rooma,roomb,14)).
neg(move(rooma,roomb,15)).
neg(move(rooma,roomb,16)).
neg(move(rooma,roomb,17)).
neg(move(rooma,roomb,18)).
neg(move(rooma,roomb,20)).
neg(move(rooma,roomb,21)).
neg(move(rooma,roomb,22)).
neg(move(rooma,roomb,23)).
neg(move(rooma,roomb,24)).
neg(move(rooma,roomb,26)).
neg(move(rooma,roomb,27)).
neg(move(rooma,roomb,28)).
neg(move(rooma,roomb,3)).
neg(move(rooma,roomb,31)).
neg(move(rooma,roomb,32)).
neg(move(rooma,roomb,33)).
neg(move(rooma,roomb,34)).
neg(move(rooma,roomb,37)).
neg(move(rooma,roomb,38)).
neg(move(rooma,roomb,39)).
neg(move(rooma,roomb,4)).
neg(move(rooma,roomb,40)).
neg(move(rooma,roomb,41)).
neg(move(rooma,roomb,43)).
neg(move(rooma,roomb,44)).
neg(move(rooma,roomb,45)).
neg(move(rooma,roomb,46)).
neg(move(rooma,roomb,47)).
neg(move(rooma,roomb,49)).
neg(move(rooma,roomb,5)).
neg(move(rooma,roomb,50)).
neg(move(rooma,roomb,6)).
neg(move(rooma,roomb,7)).
neg(move(rooma,roomb,9)).
neg(move(roomb,rooma,0)).
neg(move(roomb,rooma,1)).
neg(move(roomb,rooma,10)).
neg(move(roomb,rooma,11)).
neg(move(roomb,rooma,12)).
neg(move(roomb,rooma,13)).
neg(move(roomb,rooma,14)).
neg(move(roomb,rooma,15)).
neg(move(roomb,rooma,17)).
neg(move(roomb,rooma,18)).
neg(move(roomb,rooma,19)).
neg(move(roomb,rooma,2)).
neg(move(roomb,rooma,20)).
neg(move(roomb,rooma,21)).
neg(move(roomb,rooma,23)).
neg(move(roomb,rooma,24)).
neg(move(roomb,rooma,25)).
neg(move(roomb,rooma,26)).
neg(move(roomb,rooma,27)).
neg(move(roomb,rooma,28)).
neg(move(roomb,rooma,29)).
neg(move(roomb,rooma,3)).
neg(move(roomb,rooma,30)).
neg(move(roomb,rooma,31)).
neg(move(roomb,rooma,32)).
neg(move(roomb,rooma,34)).
neg(move(roomb,rooma,35)).
neg(move(roomb,rooma,36)).
neg(move(roomb,rooma,37)).
neg(move(roomb,rooma,38)).
neg(move(roomb,rooma,4)).
neg(move(roomb,rooma,40)).
neg(move(roomb,rooma,41)).
neg(move(roomb,rooma,42)).
neg(move(roomb,rooma,43)).
neg(move(roomb,rooma,44)).
neg(move(roomb,rooma,46)).
neg(move(roomb,rooma,47)).
neg(move(roomb,rooma,48)).
neg(move(roomb,rooma,49)).
neg(move(roomb,rooma,50)).
neg(move(roomb,rooma,6)).
neg(move(roomb,rooma,7)).
neg(move(roomb,rooma,8)).
neg(move(roomb,rooma,9)).
