% Positive examples
pos(move(rooma,roomb,13)).
pos(move(rooma,roomb,19)).
pos(move(rooma,roomb,2)).
pos(move(rooma,roomb,25)).
pos(move(rooma,roomb,8)).
pos(move(roomb,rooma,16)).
pos(move(roomb,rooma,22)).
pos(move(roomb,rooma,5)).

% Negative examples
neg(move(rooma,rooma,0)).
neg(move(rooma,rooma,1)).
neg(move(rooma,rooma,10)).
neg(move(rooma,rooma,11)).
neg(move(rooma,rooma,13)).
neg(move(rooma,rooma,14)).
neg(move(rooma,rooma,15)).
neg(move(rooma,rooma,16)).
neg(move(rooma,rooma,17)).
neg(move(rooma,rooma,18)).
neg(move(rooma,rooma,19)).
neg(move(rooma,rooma,2)).
neg(move(rooma,rooma,20)).
neg(move(rooma,rooma,21)).
neg(move(rooma,rooma,22)).
neg(move(rooma,rooma,23)).
neg(move(rooma,rooma,24)).
neg(move(rooma,rooma,25)).
neg(move(rooma,rooma,26)).
neg(move(rooma,rooma,27)).
neg(move(rooma,rooma,3)).
neg(move(rooma,rooma,4)).
neg(move(rooma,rooma,5)).
neg(move(rooma,rooma,6)).
neg(move(rooma,rooma,7)).
neg(move(rooma,rooma,8)).
neg(move(rooma,rooma,9)).
neg(move(rooma,roomb,0)).
neg(move(rooma,roomb,1)).
neg(move(rooma,roomb,10)).
neg(move(rooma,roomb,11)).
neg(move(rooma,roomb,14)).
neg(move(rooma,roomb,15)).
neg(move(rooma,roomb,16)).
neg(move(rooma,roomb,17)).
neg(move(rooma,roomb,18)).
neg(move(rooma,roomb,20)).
neg(move(rooma,roomb,21)).
neg(move(rooma,roomb,22)).
neg(move(rooma,roomb,23)).
neg(move(rooma,roomb,24)).
neg(move(rooma,roomb,26)).
neg(move(rooma,roomb,27)).
neg(move(rooma,roomb,3)).
neg(move(rooma,roomb,4)).
neg(move(rooma,roomb,5)).
neg(move(rooma,roomb,6)).
neg(move(rooma,roomb,7)).
neg(move(rooma,roomb,9)).
neg(move(roomb,rooma,0)).
neg(move(roomb,rooma,1)).
neg(move(roomb,rooma,10)).
neg(move(roomb,rooma,11)).
neg(move(roomb,rooma,12)).
neg(move(roomb,rooma,13)).
neg(move(roomb,rooma,14)).
neg(move(roomb,rooma,15)).
neg(move(roomb,rooma,17)).
neg(move(roomb,rooma,18)).
neg(move(roomb,rooma,19)).
neg(move(roomb,rooma,2)).
neg(move(roomb,rooma,20)).
neg(move(roomb,rooma,21)).
neg(move(roomb,rooma,23)).
neg(move(roomb,rooma,24)).
neg(move(roomb,rooma,25)).
neg(move(roomb,rooma,26)).
neg(move(roomb,rooma,27)).
neg(move(roomb,rooma,3)).
neg(move(roomb,rooma,4)).
neg(move(roomb,rooma,6)).
neg(move(roomb,rooma,7)).
neg(move(roomb,rooma,8)).
neg(move(roomb,rooma,9)).
neg(move(roomb,roomb,0)).
neg(move(roomb,roomb,1)).
neg(move(roomb,roomb,10)).
neg(move(roomb,roomb,11)).
neg(move(roomb,roomb,12)).
neg(move(roomb,roomb,13)).
neg(move(roomb,roomb,14)).
neg(move(roomb,roomb,15)).
neg(move(roomb,roomb,16)).
neg(move(roomb,roomb,17)).
neg(move(roomb,roomb,18)).
neg(move(roomb,roomb,19)).
neg(move(roomb,roomb,2)).
neg(move(roomb,roomb,20)).
neg(move(roomb,roomb,21)).
neg(move(roomb,roomb,22)).
neg(move(roomb,roomb,23)).
neg(move(roomb,roomb,24)).
neg(move(roomb,roomb,25)).
neg(move(roomb,roomb,26)).
neg(move(roomb,roomb,27)).
neg(move(roomb,roomb,3)).
neg(move(roomb,roomb,4)).
neg(move(roomb,roomb,5)).
neg(move(roomb,roomb,6)).
neg(move(roomb,roomb,7)).
neg(move(roomb,roomb,8)).
neg(move(roomb,roomb,9)).
