neg(next_control(1,xplayer)).
neg(next_control(10,oplayer)).
neg(next_control(100,xplayer)).
neg(next_control(101,xplayer)).
neg(next_control(102,xplayer)).
neg(next_control(103,oplayer)).
neg(next_control(104,oplayer)).
neg(next_control(105,xplayer)).
neg(next_control(106,xplayer)).
neg(next_control(107,oplayer)).
neg(next_control(108,xplayer)).
neg(next_control(109,oplayer)).
neg(next_control(11,xplayer)).
neg(next_control(110,oplayer)).
neg(next_control(111,oplayer)).
neg(next_control(112,xplayer)).
neg(next_control(113,oplayer)).
neg(next_control(114,oplayer)).
neg(next_control(115,oplayer)).
neg(next_control(116,xplayer)).
neg(next_control(117,oplayer)).
neg(next_control(118,xplayer)).
neg(next_control(119,xplayer)).
neg(next_control(12,oplayer)).
neg(next_control(120,oplayer)).
neg(next_control(121,oplayer)).
neg(next_control(122,oplayer)).
neg(next_control(123,xplayer)).
neg(next_control(124,xplayer)).
neg(next_control(125,oplayer)).
neg(next_control(126,oplayer)).
neg(next_control(127,oplayer)).
neg(next_control(128,xplayer)).
neg(next_control(129,oplayer)).
neg(next_control(13,oplayer)).
neg(next_control(130,oplayer)).
neg(next_control(131,oplayer)).
neg(next_control(132,oplayer)).
neg(next_control(133,oplayer)).
neg(next_control(134,oplayer)).
neg(next_control(135,xplayer)).
neg(next_control(136,xplayer)).
neg(next_control(137,xplayer)).
neg(next_control(138,xplayer)).
neg(next_control(139,xplayer)).
neg(next_control(14,xplayer)).
neg(next_control(140,oplayer)).
neg(next_control(141,oplayer)).
neg(next_control(142,oplayer)).
neg(next_control(143,oplayer)).
neg(next_control(144,oplayer)).
neg(next_control(145,xplayer)).
neg(next_control(146,oplayer)).
neg(next_control(147,xplayer)).
neg(next_control(148,oplayer)).
neg(next_control(149,xplayer)).
neg(next_control(15,oplayer)).
neg(next_control(150,xplayer)).
neg(next_control(151,oplayer)).
neg(next_control(152,xplayer)).
neg(next_control(153,xplayer)).
neg(next_control(154,xplayer)).
neg(next_control(155,oplayer)).
neg(next_control(156,xplayer)).
neg(next_control(157,oplayer)).
neg(next_control(158,xplayer)).
neg(next_control(159,xplayer)).
neg(next_control(16,xplayer)).
neg(next_control(160,oplayer)).
neg(next_control(161,xplayer)).
neg(next_control(162,xplayer)).
neg(next_control(163,oplayer)).
neg(next_control(164,xplayer)).
neg(next_control(165,xplayer)).
neg(next_control(166,xplayer)).
neg(next_control(167,oplayer)).
neg(next_control(168,oplayer)).
neg(next_control(169,xplayer)).
neg(next_control(17,oplayer)).
neg(next_control(170,oplayer)).
neg(next_control(171,oplayer)).
neg(next_control(172,oplayer)).
neg(next_control(173,oplayer)).
neg(next_control(174,xplayer)).
neg(next_control(175,xplayer)).
neg(next_control(176,oplayer)).
neg(next_control(177,oplayer)).
neg(next_control(178,xplayer)).
neg(next_control(179,xplayer)).
neg(next_control(18,oplayer)).
neg(next_control(180,oplayer)).
neg(next_control(181,oplayer)).
neg(next_control(182,oplayer)).
neg(next_control(183,xplayer)).
neg(next_control(184,oplayer)).
neg(next_control(185,xplayer)).
neg(next_control(186,oplayer)).
neg(next_control(187,oplayer)).
neg(next_control(188,oplayer)).
neg(next_control(189,xplayer)).
neg(next_control(19,oplayer)).
neg(next_control(190,oplayer)).
neg(next_control(191,xplayer)).
neg(next_control(192,xplayer)).
neg(next_control(193,oplayer)).
neg(next_control(194,oplayer)).
neg(next_control(195,oplayer)).
neg(next_control(196,oplayer)).
neg(next_control(197,oplayer)).
neg(next_control(198,xplayer)).
neg(next_control(199,oplayer)).
neg(next_control(2,xplayer)).
neg(next_control(20,xplayer)).
neg(next_control(200,oplayer)).
neg(next_control(201,oplayer)).
neg(next_control(202,xplayer)).
neg(next_control(203,xplayer)).
neg(next_control(204,xplayer)).
neg(next_control(205,oplayer)).
neg(next_control(206,oplayer)).
neg(next_control(207,oplayer)).
neg(next_control(208,xplayer)).
neg(next_control(209,oplayer)).
neg(next_control(21,xplayer)).
neg(next_control(210,xplayer)).
neg(next_control(211,xplayer)).
neg(next_control(212,xplayer)).
neg(next_control(213,oplayer)).
neg(next_control(214,oplayer)).
neg(next_control(215,oplayer)).
neg(next_control(216,xplayer)).
neg(next_control(217,xplayer)).
neg(next_control(218,xplayer)).
neg(next_control(219,xplayer)).
neg(next_control(22,xplayer)).
neg(next_control(220,oplayer)).
neg(next_control(221,oplayer)).
neg(next_control(222,xplayer)).
neg(next_control(223,xplayer)).
neg(next_control(224,xplayer)).
neg(next_control(225,oplayer)).
neg(next_control(226,oplayer)).
neg(next_control(227,xplayer)).
neg(next_control(228,oplayer)).
neg(next_control(229,oplayer)).
neg(next_control(23,xplayer)).
neg(next_control(230,xplayer)).
neg(next_control(231,xplayer)).
neg(next_control(232,oplayer)).
neg(next_control(233,xplayer)).
neg(next_control(234,xplayer)).
neg(next_control(235,xplayer)).
neg(next_control(236,oplayer)).
neg(next_control(237,xplayer)).
neg(next_control(238,xplayer)).
neg(next_control(239,oplayer)).
neg(next_control(24,oplayer)).
neg(next_control(240,xplayer)).
neg(next_control(241,oplayer)).
neg(next_control(242,oplayer)).
neg(next_control(243,xplayer)).
neg(next_control(244,oplayer)).
neg(next_control(245,oplayer)).
neg(next_control(246,oplayer)).
neg(next_control(247,xplayer)).
neg(next_control(248,xplayer)).
neg(next_control(249,oplayer)).
neg(next_control(25,oplayer)).
neg(next_control(250,oplayer)).
neg(next_control(251,xplayer)).
neg(next_control(252,xplayer)).
neg(next_control(253,xplayer)).
neg(next_control(254,xplayer)).
neg(next_control(255,xplayer)).
neg(next_control(256,xplayer)).
neg(next_control(257,oplayer)).
neg(next_control(258,xplayer)).
neg(next_control(259,xplayer)).
neg(next_control(26,oplayer)).
neg(next_control(260,oplayer)).
neg(next_control(261,oplayer)).
neg(next_control(262,xplayer)).
neg(next_control(263,xplayer)).
neg(next_control(264,xplayer)).
neg(next_control(265,xplayer)).
neg(next_control(266,xplayer)).
neg(next_control(267,oplayer)).
neg(next_control(268,xplayer)).
neg(next_control(269,xplayer)).
neg(next_control(27,xplayer)).
neg(next_control(270,xplayer)).
neg(next_control(271,xplayer)).
neg(next_control(272,xplayer)).
neg(next_control(273,oplayer)).
neg(next_control(274,xplayer)).
neg(next_control(275,xplayer)).
neg(next_control(276,xplayer)).
neg(next_control(277,xplayer)).
neg(next_control(278,oplayer)).
neg(next_control(279,xplayer)).
neg(next_control(28,xplayer)).
neg(next_control(280,oplayer)).
neg(next_control(281,xplayer)).
neg(next_control(282,oplayer)).
neg(next_control(283,oplayer)).
neg(next_control(284,xplayer)).
neg(next_control(285,xplayer)).
neg(next_control(286,xplayer)).
neg(next_control(287,oplayer)).
neg(next_control(288,oplayer)).
neg(next_control(289,xplayer)).
neg(next_control(29,oplayer)).
neg(next_control(290,oplayer)).
neg(next_control(291,xplayer)).
neg(next_control(292,xplayer)).
neg(next_control(293,oplayer)).
neg(next_control(294,oplayer)).
neg(next_control(295,oplayer)).
neg(next_control(296,oplayer)).
neg(next_control(297,oplayer)).
neg(next_control(298,oplayer)).
neg(next_control(299,oplayer)).
neg(next_control(3,xplayer)).
neg(next_control(30,oplayer)).
neg(next_control(300,xplayer)).
neg(next_control(301,oplayer)).
neg(next_control(302,oplayer)).
neg(next_control(303,xplayer)).
neg(next_control(304,oplayer)).
neg(next_control(305,xplayer)).
neg(next_control(306,oplayer)).
neg(next_control(307,oplayer)).
neg(next_control(308,xplayer)).
neg(next_control(309,oplayer)).
neg(next_control(31,xplayer)).
neg(next_control(310,oplayer)).
neg(next_control(311,oplayer)).
neg(next_control(312,oplayer)).
neg(next_control(313,oplayer)).
neg(next_control(314,oplayer)).
neg(next_control(315,oplayer)).
neg(next_control(316,oplayer)).
neg(next_control(317,oplayer)).
neg(next_control(318,xplayer)).
neg(next_control(319,xplayer)).
neg(next_control(32,xplayer)).
neg(next_control(320,xplayer)).
neg(next_control(321,oplayer)).
neg(next_control(322,oplayer)).
neg(next_control(323,oplayer)).
neg(next_control(324,oplayer)).
neg(next_control(325,xplayer)).
neg(next_control(326,oplayer)).
neg(next_control(327,xplayer)).
neg(next_control(328,oplayer)).
neg(next_control(329,oplayer)).
neg(next_control(33,xplayer)).
neg(next_control(330,oplayer)).
neg(next_control(331,xplayer)).
neg(next_control(332,oplayer)).
neg(next_control(333,xplayer)).
neg(next_control(334,xplayer)).
neg(next_control(335,oplayer)).
neg(next_control(336,oplayer)).
neg(next_control(337,oplayer)).
neg(next_control(338,oplayer)).
neg(next_control(339,xplayer)).
neg(next_control(34,xplayer)).
neg(next_control(340,xplayer)).
neg(next_control(341,oplayer)).
neg(next_control(342,xplayer)).
neg(next_control(343,xplayer)).
neg(next_control(344,xplayer)).
neg(next_control(345,oplayer)).
neg(next_control(346,xplayer)).
neg(next_control(347,xplayer)).
neg(next_control(348,xplayer)).
neg(next_control(349,oplayer)).
neg(next_control(35,oplayer)).
neg(next_control(350,oplayer)).
neg(next_control(351,oplayer)).
neg(next_control(352,oplayer)).
neg(next_control(353,oplayer)).
neg(next_control(354,xplayer)).
neg(next_control(355,oplayer)).
neg(next_control(356,oplayer)).
neg(next_control(357,oplayer)).
neg(next_control(358,xplayer)).
neg(next_control(359,oplayer)).
neg(next_control(36,oplayer)).
neg(next_control(360,xplayer)).
neg(next_control(361,xplayer)).
neg(next_control(362,oplayer)).
neg(next_control(363,xplayer)).
neg(next_control(364,oplayer)).
neg(next_control(365,xplayer)).
neg(next_control(366,oplayer)).
neg(next_control(367,oplayer)).
neg(next_control(368,oplayer)).
neg(next_control(369,xplayer)).
neg(next_control(37,xplayer)).
neg(next_control(370,oplayer)).
neg(next_control(371,oplayer)).
neg(next_control(372,xplayer)).
neg(next_control(373,oplayer)).
neg(next_control(374,oplayer)).
neg(next_control(375,oplayer)).
neg(next_control(376,xplayer)).
neg(next_control(377,xplayer)).
neg(next_control(378,xplayer)).
neg(next_control(379,xplayer)).
neg(next_control(38,xplayer)).
neg(next_control(380,xplayer)).
neg(next_control(381,oplayer)).
neg(next_control(382,xplayer)).
neg(next_control(383,oplayer)).
neg(next_control(384,xplayer)).
neg(next_control(385,oplayer)).
neg(next_control(386,oplayer)).
neg(next_control(387,xplayer)).
neg(next_control(388,oplayer)).
neg(next_control(389,xplayer)).
neg(next_control(39,xplayer)).
neg(next_control(390,xplayer)).
neg(next_control(391,oplayer)).
neg(next_control(392,xplayer)).
neg(next_control(393,xplayer)).
neg(next_control(394,oplayer)).
neg(next_control(395,xplayer)).
neg(next_control(396,xplayer)).
neg(next_control(397,xplayer)).
neg(next_control(398,oplayer)).
neg(next_control(399,oplayer)).
neg(next_control(4,oplayer)).
neg(next_control(40,oplayer)).
neg(next_control(400,oplayer)).
neg(next_control(401,xplayer)).
neg(next_control(402,xplayer)).
neg(next_control(403,oplayer)).
neg(next_control(404,xplayer)).
neg(next_control(405,xplayer)).
neg(next_control(406,xplayer)).
neg(next_control(407,xplayer)).
neg(next_control(408,oplayer)).
neg(next_control(409,oplayer)).
neg(next_control(41,xplayer)).
neg(next_control(410,xplayer)).
neg(next_control(411,xplayer)).
neg(next_control(412,oplayer)).
neg(next_control(413,xplayer)).
neg(next_control(414,xplayer)).
neg(next_control(415,xplayer)).
neg(next_control(416,xplayer)).
neg(next_control(417,xplayer)).
neg(next_control(418,xplayer)).
neg(next_control(419,xplayer)).
neg(next_control(42,xplayer)).
neg(next_control(420,oplayer)).
neg(next_control(421,oplayer)).
neg(next_control(422,oplayer)).
neg(next_control(423,oplayer)).
neg(next_control(424,oplayer)).
neg(next_control(425,oplayer)).
neg(next_control(426,oplayer)).
neg(next_control(427,xplayer)).
neg(next_control(428,oplayer)).
neg(next_control(429,xplayer)).
neg(next_control(43,xplayer)).
neg(next_control(430,oplayer)).
neg(next_control(431,oplayer)).
neg(next_control(432,xplayer)).
neg(next_control(433,xplayer)).
neg(next_control(434,oplayer)).
neg(next_control(435,oplayer)).
neg(next_control(436,xplayer)).
neg(next_control(437,xplayer)).
neg(next_control(438,xplayer)).
neg(next_control(439,xplayer)).
neg(next_control(44,xplayer)).
neg(next_control(440,oplayer)).
neg(next_control(441,xplayer)).
neg(next_control(442,xplayer)).
neg(next_control(443,xplayer)).
neg(next_control(444,xplayer)).
neg(next_control(445,oplayer)).
neg(next_control(446,xplayer)).
neg(next_control(447,oplayer)).
neg(next_control(448,oplayer)).
neg(next_control(449,xplayer)).
neg(next_control(45,oplayer)).
neg(next_control(450,oplayer)).
neg(next_control(451,oplayer)).
neg(next_control(452,xplayer)).
neg(next_control(453,xplayer)).
neg(next_control(454,xplayer)).
neg(next_control(455,xplayer)).
neg(next_control(456,xplayer)).
neg(next_control(457,oplayer)).
neg(next_control(458,oplayer)).
neg(next_control(459,xplayer)).
neg(next_control(46,xplayer)).
neg(next_control(460,oplayer)).
neg(next_control(461,xplayer)).
neg(next_control(462,oplayer)).
neg(next_control(463,xplayer)).
neg(next_control(464,xplayer)).
neg(next_control(465,oplayer)).
neg(next_control(466,xplayer)).
neg(next_control(467,xplayer)).
neg(next_control(468,oplayer)).
neg(next_control(469,oplayer)).
neg(next_control(47,oplayer)).
neg(next_control(470,xplayer)).
neg(next_control(471,xplayer)).
neg(next_control(472,oplayer)).
neg(next_control(473,xplayer)).
neg(next_control(474,xplayer)).
neg(next_control(475,xplayer)).
neg(next_control(476,oplayer)).
neg(next_control(477,oplayer)).
neg(next_control(478,oplayer)).
neg(next_control(479,oplayer)).
neg(next_control(48,xplayer)).
neg(next_control(480,xplayer)).
neg(next_control(481,xplayer)).
neg(next_control(482,xplayer)).
neg(next_control(483,xplayer)).
neg(next_control(484,oplayer)).
neg(next_control(485,oplayer)).
neg(next_control(486,xplayer)).
neg(next_control(487,xplayer)).
neg(next_control(488,oplayer)).
neg(next_control(489,xplayer)).
neg(next_control(49,xplayer)).
neg(next_control(490,oplayer)).
neg(next_control(491,xplayer)).
neg(next_control(492,xplayer)).
neg(next_control(493,oplayer)).
neg(next_control(494,xplayer)).
neg(next_control(495,xplayer)).
neg(next_control(496,oplayer)).
neg(next_control(497,oplayer)).
neg(next_control(498,xplayer)).
neg(next_control(499,xplayer)).
neg(next_control(5,xplayer)).
neg(next_control(50,oplayer)).
neg(next_control(500,oplayer)).
neg(next_control(51,xplayer)).
neg(next_control(52,xplayer)).
neg(next_control(53,xplayer)).
neg(next_control(54,xplayer)).
neg(next_control(55,xplayer)).
neg(next_control(56,oplayer)).
neg(next_control(57,xplayer)).
neg(next_control(58,oplayer)).
neg(next_control(59,xplayer)).
neg(next_control(6,oplayer)).
neg(next_control(60,xplayer)).
neg(next_control(61,oplayer)).
neg(next_control(62,xplayer)).
neg(next_control(63,xplayer)).
neg(next_control(64,oplayer)).
neg(next_control(65,oplayer)).
neg(next_control(66,xplayer)).
neg(next_control(67,xplayer)).
neg(next_control(68,xplayer)).
neg(next_control(69,oplayer)).
neg(next_control(7,xplayer)).
neg(next_control(70,oplayer)).
neg(next_control(71,xplayer)).
neg(next_control(72,xplayer)).
neg(next_control(73,oplayer)).
neg(next_control(74,xplayer)).
neg(next_control(75,oplayer)).
neg(next_control(76,xplayer)).
neg(next_control(77,xplayer)).
neg(next_control(78,oplayer)).
neg(next_control(79,oplayer)).
neg(next_control(8,oplayer)).
neg(next_control(80,xplayer)).
neg(next_control(81,oplayer)).
neg(next_control(82,xplayer)).
neg(next_control(83,xplayer)).
neg(next_control(84,xplayer)).
neg(next_control(85,xplayer)).
neg(next_control(86,oplayer)).
neg(next_control(87,xplayer)).
neg(next_control(88,oplayer)).
neg(next_control(89,xplayer)).
neg(next_control(9,xplayer)).
neg(next_control(90,xplayer)).
neg(next_control(91,oplayer)).
neg(next_control(92,xplayer)).
neg(next_control(93,oplayer)).
neg(next_control(94,oplayer)).
neg(next_control(95,xplayer)).
neg(next_control(96,oplayer)).
neg(next_control(97,xplayer)).
neg(next_control(98,oplayer)).
neg(next_control(99,oplayer)).
pos(next_control(1,oplayer)).
pos(next_control(10,xplayer)).
pos(next_control(100,oplayer)).
pos(next_control(101,oplayer)).
pos(next_control(102,oplayer)).
pos(next_control(103,xplayer)).
pos(next_control(104,xplayer)).
pos(next_control(105,oplayer)).
pos(next_control(106,oplayer)).
pos(next_control(107,xplayer)).
pos(next_control(108,oplayer)).
pos(next_control(109,xplayer)).
pos(next_control(11,oplayer)).
pos(next_control(110,xplayer)).
pos(next_control(111,xplayer)).
pos(next_control(112,oplayer)).
pos(next_control(113,xplayer)).
pos(next_control(114,xplayer)).
pos(next_control(115,xplayer)).
pos(next_control(116,oplayer)).
pos(next_control(117,xplayer)).
pos(next_control(118,oplayer)).
pos(next_control(119,oplayer)).
pos(next_control(12,xplayer)).
pos(next_control(120,xplayer)).
pos(next_control(121,xplayer)).
pos(next_control(122,xplayer)).
pos(next_control(123,oplayer)).
pos(next_control(124,oplayer)).
pos(next_control(125,xplayer)).
pos(next_control(126,xplayer)).
pos(next_control(127,xplayer)).
pos(next_control(128,oplayer)).
pos(next_control(129,xplayer)).
pos(next_control(13,xplayer)).
pos(next_control(130,xplayer)).
pos(next_control(131,xplayer)).
pos(next_control(132,xplayer)).
pos(next_control(133,xplayer)).
pos(next_control(134,xplayer)).
pos(next_control(135,oplayer)).
pos(next_control(136,oplayer)).
pos(next_control(137,oplayer)).
pos(next_control(138,oplayer)).
pos(next_control(139,oplayer)).
pos(next_control(14,oplayer)).
pos(next_control(140,xplayer)).
pos(next_control(141,xplayer)).
pos(next_control(142,xplayer)).
pos(next_control(143,xplayer)).
pos(next_control(144,xplayer)).
pos(next_control(145,oplayer)).
pos(next_control(146,xplayer)).
pos(next_control(147,oplayer)).
pos(next_control(148,xplayer)).
pos(next_control(149,oplayer)).
pos(next_control(15,xplayer)).
pos(next_control(150,oplayer)).
pos(next_control(151,xplayer)).
pos(next_control(152,oplayer)).
pos(next_control(153,oplayer)).
pos(next_control(154,oplayer)).
pos(next_control(155,xplayer)).
pos(next_control(156,oplayer)).
pos(next_control(157,xplayer)).
pos(next_control(158,oplayer)).
pos(next_control(159,oplayer)).
pos(next_control(16,oplayer)).
pos(next_control(160,xplayer)).
pos(next_control(161,oplayer)).
pos(next_control(162,oplayer)).
pos(next_control(163,xplayer)).
pos(next_control(164,oplayer)).
pos(next_control(165,oplayer)).
pos(next_control(166,oplayer)).
pos(next_control(167,xplayer)).
pos(next_control(168,xplayer)).
pos(next_control(169,oplayer)).
pos(next_control(17,xplayer)).
pos(next_control(170,xplayer)).
pos(next_control(171,xplayer)).
pos(next_control(172,xplayer)).
pos(next_control(173,xplayer)).
pos(next_control(174,oplayer)).
pos(next_control(175,oplayer)).
pos(next_control(176,xplayer)).
pos(next_control(177,xplayer)).
pos(next_control(178,oplayer)).
pos(next_control(179,oplayer)).
pos(next_control(18,xplayer)).
pos(next_control(180,xplayer)).
pos(next_control(181,xplayer)).
pos(next_control(182,xplayer)).
pos(next_control(183,oplayer)).
pos(next_control(184,xplayer)).
pos(next_control(185,oplayer)).
pos(next_control(186,xplayer)).
pos(next_control(187,xplayer)).
pos(next_control(188,xplayer)).
pos(next_control(189,oplayer)).
pos(next_control(19,xplayer)).
pos(next_control(190,xplayer)).
pos(next_control(191,oplayer)).
pos(next_control(192,oplayer)).
pos(next_control(193,xplayer)).
pos(next_control(194,xplayer)).
pos(next_control(195,xplayer)).
pos(next_control(196,xplayer)).
pos(next_control(197,xplayer)).
pos(next_control(198,oplayer)).
pos(next_control(199,xplayer)).
pos(next_control(2,oplayer)).
pos(next_control(20,oplayer)).
pos(next_control(200,xplayer)).
pos(next_control(201,xplayer)).
pos(next_control(202,oplayer)).
pos(next_control(203,oplayer)).
pos(next_control(204,oplayer)).
pos(next_control(205,xplayer)).
pos(next_control(206,xplayer)).
pos(next_control(207,xplayer)).
pos(next_control(208,oplayer)).
pos(next_control(209,xplayer)).
pos(next_control(21,oplayer)).
pos(next_control(210,oplayer)).
pos(next_control(211,oplayer)).
pos(next_control(212,oplayer)).
pos(next_control(213,xplayer)).
pos(next_control(214,xplayer)).
pos(next_control(215,xplayer)).
pos(next_control(216,oplayer)).
pos(next_control(217,oplayer)).
pos(next_control(218,oplayer)).
pos(next_control(219,oplayer)).
pos(next_control(22,oplayer)).
pos(next_control(220,xplayer)).
pos(next_control(221,xplayer)).
pos(next_control(222,oplayer)).
pos(next_control(223,oplayer)).
pos(next_control(224,oplayer)).
pos(next_control(225,xplayer)).
pos(next_control(226,xplayer)).
pos(next_control(227,oplayer)).
pos(next_control(228,xplayer)).
pos(next_control(229,xplayer)).
pos(next_control(23,oplayer)).
pos(next_control(230,oplayer)).
pos(next_control(231,oplayer)).
pos(next_control(232,xplayer)).
pos(next_control(233,oplayer)).
pos(next_control(234,oplayer)).
pos(next_control(235,oplayer)).
pos(next_control(236,xplayer)).
pos(next_control(237,oplayer)).
pos(next_control(238,oplayer)).
pos(next_control(239,xplayer)).
pos(next_control(24,xplayer)).
pos(next_control(240,oplayer)).
pos(next_control(241,xplayer)).
pos(next_control(242,xplayer)).
pos(next_control(243,oplayer)).
pos(next_control(244,xplayer)).
pos(next_control(245,xplayer)).
pos(next_control(246,xplayer)).
pos(next_control(247,oplayer)).
pos(next_control(248,oplayer)).
pos(next_control(249,xplayer)).
pos(next_control(25,xplayer)).
pos(next_control(250,xplayer)).
pos(next_control(251,oplayer)).
pos(next_control(252,oplayer)).
pos(next_control(253,oplayer)).
pos(next_control(254,oplayer)).
pos(next_control(255,oplayer)).
pos(next_control(256,oplayer)).
pos(next_control(257,xplayer)).
pos(next_control(258,oplayer)).
pos(next_control(259,oplayer)).
pos(next_control(26,xplayer)).
pos(next_control(260,xplayer)).
pos(next_control(261,xplayer)).
pos(next_control(262,oplayer)).
pos(next_control(263,oplayer)).
pos(next_control(264,oplayer)).
pos(next_control(265,oplayer)).
pos(next_control(266,oplayer)).
pos(next_control(267,xplayer)).
pos(next_control(268,oplayer)).
pos(next_control(269,oplayer)).
pos(next_control(27,oplayer)).
pos(next_control(270,oplayer)).
pos(next_control(271,oplayer)).
pos(next_control(272,oplayer)).
pos(next_control(273,xplayer)).
pos(next_control(274,oplayer)).
pos(next_control(275,oplayer)).
pos(next_control(276,oplayer)).
pos(next_control(277,oplayer)).
pos(next_control(278,xplayer)).
pos(next_control(279,oplayer)).
pos(next_control(28,oplayer)).
pos(next_control(280,xplayer)).
pos(next_control(281,oplayer)).
pos(next_control(282,xplayer)).
pos(next_control(283,xplayer)).
pos(next_control(284,oplayer)).
pos(next_control(285,oplayer)).
pos(next_control(286,oplayer)).
pos(next_control(287,xplayer)).
pos(next_control(288,xplayer)).
pos(next_control(289,oplayer)).
pos(next_control(29,xplayer)).
pos(next_control(290,xplayer)).
pos(next_control(291,oplayer)).
pos(next_control(292,oplayer)).
pos(next_control(293,xplayer)).
pos(next_control(294,xplayer)).
pos(next_control(295,xplayer)).
pos(next_control(296,xplayer)).
pos(next_control(297,xplayer)).
pos(next_control(298,xplayer)).
pos(next_control(299,xplayer)).
pos(next_control(3,oplayer)).
pos(next_control(30,xplayer)).
pos(next_control(300,oplayer)).
pos(next_control(301,xplayer)).
pos(next_control(302,xplayer)).
pos(next_control(303,oplayer)).
pos(next_control(304,xplayer)).
pos(next_control(305,oplayer)).
pos(next_control(306,xplayer)).
pos(next_control(307,xplayer)).
pos(next_control(308,oplayer)).
pos(next_control(309,xplayer)).
pos(next_control(31,oplayer)).
pos(next_control(310,xplayer)).
pos(next_control(311,xplayer)).
pos(next_control(312,xplayer)).
pos(next_control(313,xplayer)).
pos(next_control(314,xplayer)).
pos(next_control(315,xplayer)).
pos(next_control(316,xplayer)).
pos(next_control(317,xplayer)).
pos(next_control(318,oplayer)).
pos(next_control(319,oplayer)).
pos(next_control(32,oplayer)).
pos(next_control(320,oplayer)).
pos(next_control(321,xplayer)).
pos(next_control(322,xplayer)).
pos(next_control(323,xplayer)).
pos(next_control(324,xplayer)).
pos(next_control(325,oplayer)).
pos(next_control(326,xplayer)).
pos(next_control(327,oplayer)).
pos(next_control(328,xplayer)).
pos(next_control(329,xplayer)).
pos(next_control(33,oplayer)).
pos(next_control(330,xplayer)).
pos(next_control(331,oplayer)).
pos(next_control(332,xplayer)).
pos(next_control(333,oplayer)).
pos(next_control(334,oplayer)).
pos(next_control(335,xplayer)).
pos(next_control(336,xplayer)).
pos(next_control(337,xplayer)).
pos(next_control(338,xplayer)).
pos(next_control(339,oplayer)).
pos(next_control(34,oplayer)).
pos(next_control(340,oplayer)).
pos(next_control(341,xplayer)).
pos(next_control(342,oplayer)).
pos(next_control(343,oplayer)).
pos(next_control(344,oplayer)).
pos(next_control(345,xplayer)).
pos(next_control(346,oplayer)).
pos(next_control(347,oplayer)).
pos(next_control(348,oplayer)).
pos(next_control(349,xplayer)).
pos(next_control(35,xplayer)).
pos(next_control(350,xplayer)).
pos(next_control(351,xplayer)).
pos(next_control(352,xplayer)).
pos(next_control(353,xplayer)).
pos(next_control(354,oplayer)).
pos(next_control(355,xplayer)).
pos(next_control(356,xplayer)).
pos(next_control(357,xplayer)).
pos(next_control(358,oplayer)).
pos(next_control(359,xplayer)).
pos(next_control(36,xplayer)).
pos(next_control(360,oplayer)).
pos(next_control(361,oplayer)).
pos(next_control(362,xplayer)).
pos(next_control(363,oplayer)).
pos(next_control(364,xplayer)).
pos(next_control(365,oplayer)).
pos(next_control(366,xplayer)).
pos(next_control(367,xplayer)).
pos(next_control(368,xplayer)).
pos(next_control(369,oplayer)).
pos(next_control(37,oplayer)).
pos(next_control(370,xplayer)).
pos(next_control(371,xplayer)).
pos(next_control(372,oplayer)).
pos(next_control(373,xplayer)).
pos(next_control(374,xplayer)).
pos(next_control(375,xplayer)).
pos(next_control(376,oplayer)).
pos(next_control(377,oplayer)).
pos(next_control(378,oplayer)).
pos(next_control(379,oplayer)).
pos(next_control(38,oplayer)).
pos(next_control(380,oplayer)).
pos(next_control(381,xplayer)).
pos(next_control(382,oplayer)).
pos(next_control(383,xplayer)).
pos(next_control(384,oplayer)).
pos(next_control(385,xplayer)).
pos(next_control(386,xplayer)).
pos(next_control(387,oplayer)).
pos(next_control(388,xplayer)).
pos(next_control(389,oplayer)).
pos(next_control(39,oplayer)).
pos(next_control(390,oplayer)).
pos(next_control(391,xplayer)).
pos(next_control(392,oplayer)).
pos(next_control(393,oplayer)).
pos(next_control(394,xplayer)).
pos(next_control(395,oplayer)).
pos(next_control(396,oplayer)).
pos(next_control(397,oplayer)).
pos(next_control(398,xplayer)).
pos(next_control(399,xplayer)).
pos(next_control(4,xplayer)).
pos(next_control(40,xplayer)).
pos(next_control(400,xplayer)).
pos(next_control(401,oplayer)).
pos(next_control(402,oplayer)).
pos(next_control(403,xplayer)).
pos(next_control(404,oplayer)).
pos(next_control(405,oplayer)).
pos(next_control(406,oplayer)).
pos(next_control(407,oplayer)).
pos(next_control(408,xplayer)).
pos(next_control(409,xplayer)).
pos(next_control(41,oplayer)).
pos(next_control(410,oplayer)).
pos(next_control(411,oplayer)).
pos(next_control(412,xplayer)).
pos(next_control(413,oplayer)).
pos(next_control(414,oplayer)).
pos(next_control(415,oplayer)).
pos(next_control(416,oplayer)).
pos(next_control(417,oplayer)).
pos(next_control(418,oplayer)).
pos(next_control(419,oplayer)).
pos(next_control(42,oplayer)).
pos(next_control(420,xplayer)).
pos(next_control(421,xplayer)).
pos(next_control(422,xplayer)).
pos(next_control(423,xplayer)).
pos(next_control(424,xplayer)).
pos(next_control(425,xplayer)).
pos(next_control(426,xplayer)).
pos(next_control(427,oplayer)).
pos(next_control(428,xplayer)).
pos(next_control(429,oplayer)).
pos(next_control(43,oplayer)).
pos(next_control(430,xplayer)).
pos(next_control(431,xplayer)).
pos(next_control(432,oplayer)).
pos(next_control(433,oplayer)).
pos(next_control(434,xplayer)).
pos(next_control(435,xplayer)).
pos(next_control(436,oplayer)).
pos(next_control(437,oplayer)).
pos(next_control(438,oplayer)).
pos(next_control(439,oplayer)).
pos(next_control(44,oplayer)).
pos(next_control(440,xplayer)).
pos(next_control(441,oplayer)).
pos(next_control(442,oplayer)).
pos(next_control(443,oplayer)).
pos(next_control(444,oplayer)).
pos(next_control(445,xplayer)).
pos(next_control(446,oplayer)).
pos(next_control(447,xplayer)).
pos(next_control(448,xplayer)).
pos(next_control(449,oplayer)).
pos(next_control(45,xplayer)).
pos(next_control(450,xplayer)).
pos(next_control(451,xplayer)).
pos(next_control(452,oplayer)).
pos(next_control(453,oplayer)).
pos(next_control(454,oplayer)).
pos(next_control(455,oplayer)).
pos(next_control(456,oplayer)).
pos(next_control(457,xplayer)).
pos(next_control(458,xplayer)).
pos(next_control(459,oplayer)).
pos(next_control(46,oplayer)).
pos(next_control(460,xplayer)).
pos(next_control(461,oplayer)).
pos(next_control(462,xplayer)).
pos(next_control(463,oplayer)).
pos(next_control(464,oplayer)).
pos(next_control(465,xplayer)).
pos(next_control(466,oplayer)).
pos(next_control(467,oplayer)).
pos(next_control(468,xplayer)).
pos(next_control(469,xplayer)).
pos(next_control(47,xplayer)).
pos(next_control(470,oplayer)).
pos(next_control(471,oplayer)).
pos(next_control(472,xplayer)).
pos(next_control(473,oplayer)).
pos(next_control(474,oplayer)).
pos(next_control(475,oplayer)).
pos(next_control(476,xplayer)).
pos(next_control(477,xplayer)).
pos(next_control(478,xplayer)).
pos(next_control(479,xplayer)).
pos(next_control(48,oplayer)).
pos(next_control(480,oplayer)).
pos(next_control(481,oplayer)).
pos(next_control(482,oplayer)).
pos(next_control(483,oplayer)).
pos(next_control(484,xplayer)).
pos(next_control(485,xplayer)).
pos(next_control(486,oplayer)).
pos(next_control(487,oplayer)).
pos(next_control(488,xplayer)).
pos(next_control(489,oplayer)).
pos(next_control(49,oplayer)).
pos(next_control(490,xplayer)).
pos(next_control(491,oplayer)).
pos(next_control(492,oplayer)).
pos(next_control(493,xplayer)).
pos(next_control(494,oplayer)).
pos(next_control(495,oplayer)).
pos(next_control(496,xplayer)).
pos(next_control(497,xplayer)).
pos(next_control(498,oplayer)).
pos(next_control(499,oplayer)).
pos(next_control(5,oplayer)).
pos(next_control(50,xplayer)).
pos(next_control(500,xplayer)).
pos(next_control(51,oplayer)).
pos(next_control(52,oplayer)).
pos(next_control(53,oplayer)).
pos(next_control(54,oplayer)).
pos(next_control(55,oplayer)).
pos(next_control(56,xplayer)).
pos(next_control(57,oplayer)).
pos(next_control(58,xplayer)).
pos(next_control(59,oplayer)).
pos(next_control(6,xplayer)).
pos(next_control(60,oplayer)).
pos(next_control(61,xplayer)).
pos(next_control(62,oplayer)).
pos(next_control(63,oplayer)).
pos(next_control(64,xplayer)).
pos(next_control(65,xplayer)).
pos(next_control(66,oplayer)).
pos(next_control(67,oplayer)).
pos(next_control(68,oplayer)).
pos(next_control(69,xplayer)).
pos(next_control(7,oplayer)).
pos(next_control(70,xplayer)).
pos(next_control(71,oplayer)).
pos(next_control(72,oplayer)).
pos(next_control(73,xplayer)).
pos(next_control(74,oplayer)).
pos(next_control(75,xplayer)).
pos(next_control(76,oplayer)).
pos(next_control(77,oplayer)).
pos(next_control(78,xplayer)).
pos(next_control(79,xplayer)).
pos(next_control(8,xplayer)).
pos(next_control(80,oplayer)).
pos(next_control(81,xplayer)).
pos(next_control(82,oplayer)).
pos(next_control(83,oplayer)).
pos(next_control(84,oplayer)).
pos(next_control(85,oplayer)).
pos(next_control(86,xplayer)).
pos(next_control(87,oplayer)).
pos(next_control(88,xplayer)).
pos(next_control(89,oplayer)).
pos(next_control(9,oplayer)).
pos(next_control(90,oplayer)).
pos(next_control(91,xplayer)).
pos(next_control(92,oplayer)).
pos(next_control(93,xplayer)).
pos(next_control(94,xplayer)).
pos(next_control(95,oplayer)).
pos(next_control(96,xplayer)).
pos(next_control(97,oplayer)).
pos(next_control(98,xplayer)).
pos(next_control(99,xplayer)).