pos(ancestor(claudette,ann)).
pos(ancestor(jeannette,bill)).
pos(ancestor(mireille,john)).
pos(ancestor(john,ann)).
pos(ancestor(john,bill)).
pos(ancestor(jean-jacques,alphonse)).
pos(ancestor(alphonse,mireille)).
pos(ancestor(brad,john)).
pos(ancestor(mireille,ann)).
pos(ancestor(mireille,bill)).
pos(ancestor(jean-jacques,mireille)).
pos(ancestor(alphonse,john)).
pos(ancestor(brad,ann)).
pos(ancestor(brad,bill)).
pos(ancestor(jean-jacques,john)).
pos(ancestor(alphonse,ann)).
pos(ancestor(alphonse,bill)).
pos(ancestor(jean-jacques,ann)).
pos(ancestor(jean-jacques,bill)).
