neg(next_control(1,white)).
neg(next_control(10,black)).
neg(next_control(100,black)).
neg(next_control(101,black)).
neg(next_control(102,white)).
neg(next_control(103,black)).
neg(next_control(104,white)).
neg(next_control(105,white)).
neg(next_control(106,black)).
neg(next_control(107,black)).
neg(next_control(108,white)).
neg(next_control(109,white)).
neg(next_control(11,black)).
neg(next_control(110,white)).
neg(next_control(111,white)).
neg(next_control(112,black)).
neg(next_control(113,black)).
neg(next_control(114,white)).
neg(next_control(115,black)).
neg(next_control(116,black)).
neg(next_control(117,black)).
neg(next_control(118,black)).
neg(next_control(119,black)).
neg(next_control(12,black)).
neg(next_control(120,black)).
neg(next_control(121,white)).
neg(next_control(122,white)).
neg(next_control(123,black)).
neg(next_control(124,black)).
neg(next_control(125,black)).
neg(next_control(126,white)).
neg(next_control(127,white)).
neg(next_control(128,black)).
neg(next_control(129,white)).
neg(next_control(13,black)).
neg(next_control(130,black)).
neg(next_control(131,black)).
neg(next_control(132,black)).
neg(next_control(133,white)).
neg(next_control(134,white)).
neg(next_control(135,white)).
neg(next_control(136,black)).
neg(next_control(137,white)).
neg(next_control(138,black)).
neg(next_control(139,white)).
neg(next_control(14,white)).
neg(next_control(140,white)).
neg(next_control(141,black)).
neg(next_control(142,black)).
neg(next_control(143,black)).
neg(next_control(144,white)).
neg(next_control(145,white)).
neg(next_control(146,black)).
neg(next_control(147,white)).
neg(next_control(148,black)).
neg(next_control(149,white)).
neg(next_control(15,white)).
neg(next_control(150,white)).
neg(next_control(151,white)).
neg(next_control(152,black)).
neg(next_control(153,black)).
neg(next_control(154,black)).
neg(next_control(155,white)).
neg(next_control(156,white)).
neg(next_control(157,white)).
neg(next_control(158,black)).
neg(next_control(159,white)).
neg(next_control(16,black)).
neg(next_control(160,white)).
neg(next_control(161,white)).
neg(next_control(162,black)).
neg(next_control(163,white)).
neg(next_control(164,black)).
neg(next_control(165,black)).
neg(next_control(166,white)).
neg(next_control(167,white)).
neg(next_control(168,black)).
neg(next_control(169,white)).
neg(next_control(17,white)).
neg(next_control(170,black)).
neg(next_control(171,black)).
neg(next_control(172,white)).
neg(next_control(173,white)).
neg(next_control(174,black)).
neg(next_control(175,black)).
neg(next_control(176,white)).
neg(next_control(177,black)).
neg(next_control(178,white)).
neg(next_control(179,white)).
neg(next_control(18,white)).
neg(next_control(180,white)).
neg(next_control(181,white)).
neg(next_control(182,black)).
neg(next_control(183,white)).
neg(next_control(184,white)).
neg(next_control(185,black)).
neg(next_control(186,white)).
neg(next_control(187,white)).
neg(next_control(188,white)).
neg(next_control(189,black)).
neg(next_control(19,white)).
neg(next_control(190,black)).
neg(next_control(191,white)).
neg(next_control(192,black)).
neg(next_control(193,black)).
neg(next_control(194,white)).
neg(next_control(195,white)).
neg(next_control(196,black)).
neg(next_control(197,black)).
neg(next_control(198,white)).
neg(next_control(199,black)).
neg(next_control(2,white)).
neg(next_control(20,black)).
neg(next_control(200,white)).
neg(next_control(201,white)).
neg(next_control(202,white)).
neg(next_control(203,black)).
neg(next_control(204,black)).
neg(next_control(205,black)).
neg(next_control(206,black)).
neg(next_control(207,white)).
neg(next_control(208,black)).
neg(next_control(209,black)).
neg(next_control(21,black)).
neg(next_control(210,white)).
neg(next_control(211,white)).
neg(next_control(212,white)).
neg(next_control(213,black)).
neg(next_control(214,white)).
neg(next_control(215,black)).
neg(next_control(216,white)).
neg(next_control(217,white)).
neg(next_control(218,white)).
neg(next_control(219,black)).
neg(next_control(22,black)).
neg(next_control(220,white)).
neg(next_control(221,black)).
neg(next_control(222,black)).
neg(next_control(223,black)).
neg(next_control(224,white)).
neg(next_control(225,black)).
neg(next_control(226,white)).
neg(next_control(227,black)).
neg(next_control(228,black)).
neg(next_control(229,white)).
neg(next_control(23,white)).
neg(next_control(230,black)).
neg(next_control(231,white)).
neg(next_control(232,white)).
neg(next_control(233,black)).
neg(next_control(234,black)).
neg(next_control(235,black)).
neg(next_control(236,white)).
neg(next_control(237,black)).
neg(next_control(238,black)).
neg(next_control(239,black)).
neg(next_control(24,black)).
neg(next_control(240,white)).
neg(next_control(241,white)).
neg(next_control(242,white)).
neg(next_control(243,black)).
neg(next_control(244,white)).
neg(next_control(245,black)).
neg(next_control(246,white)).
neg(next_control(247,black)).
neg(next_control(248,white)).
neg(next_control(249,black)).
neg(next_control(25,white)).
neg(next_control(250,black)).
neg(next_control(251,black)).
neg(next_control(252,black)).
neg(next_control(253,black)).
neg(next_control(254,black)).
neg(next_control(255,white)).
neg(next_control(256,white)).
neg(next_control(257,white)).
neg(next_control(258,black)).
neg(next_control(259,black)).
neg(next_control(26,white)).
neg(next_control(260,black)).
neg(next_control(261,black)).
neg(next_control(262,white)).
neg(next_control(263,white)).
neg(next_control(264,black)).
neg(next_control(265,white)).
neg(next_control(266,black)).
neg(next_control(267,black)).
neg(next_control(268,white)).
neg(next_control(269,white)).
neg(next_control(27,black)).
neg(next_control(270,black)).
neg(next_control(271,black)).
neg(next_control(272,white)).
neg(next_control(273,black)).
neg(next_control(274,white)).
neg(next_control(275,black)).
neg(next_control(276,black)).
neg(next_control(277,black)).
neg(next_control(278,white)).
neg(next_control(279,black)).
neg(next_control(28,white)).
neg(next_control(280,white)).
neg(next_control(281,white)).
neg(next_control(282,black)).
neg(next_control(283,black)).
neg(next_control(284,white)).
neg(next_control(285,black)).
neg(next_control(286,white)).
neg(next_control(287,black)).
neg(next_control(288,white)).
neg(next_control(289,black)).
neg(next_control(29,black)).
neg(next_control(290,white)).
neg(next_control(291,black)).
neg(next_control(292,black)).
neg(next_control(293,black)).
neg(next_control(294,white)).
neg(next_control(295,black)).
neg(next_control(296,white)).
neg(next_control(297,black)).
neg(next_control(298,black)).
neg(next_control(299,white)).
neg(next_control(3,white)).
neg(next_control(30,black)).
neg(next_control(300,black)).
neg(next_control(301,black)).
neg(next_control(302,white)).
neg(next_control(303,black)).
neg(next_control(304,black)).
neg(next_control(305,white)).
neg(next_control(306,white)).
neg(next_control(307,black)).
neg(next_control(308,black)).
neg(next_control(309,white)).
neg(next_control(31,white)).
neg(next_control(310,white)).
neg(next_control(311,black)).
neg(next_control(312,white)).
neg(next_control(313,black)).
neg(next_control(314,white)).
neg(next_control(315,black)).
neg(next_control(316,white)).
neg(next_control(317,black)).
neg(next_control(318,white)).
neg(next_control(319,black)).
neg(next_control(32,black)).
neg(next_control(320,black)).
neg(next_control(321,black)).
neg(next_control(322,black)).
neg(next_control(323,white)).
neg(next_control(324,black)).
neg(next_control(325,white)).
neg(next_control(326,black)).
neg(next_control(327,black)).
neg(next_control(328,white)).
neg(next_control(329,black)).
neg(next_control(33,black)).
neg(next_control(330,black)).
neg(next_control(331,white)).
neg(next_control(332,black)).
neg(next_control(333,white)).
neg(next_control(334,black)).
neg(next_control(335,white)).
neg(next_control(336,black)).
neg(next_control(337,white)).
neg(next_control(338,black)).
neg(next_control(339,white)).
neg(next_control(34,black)).
neg(next_control(340,black)).
neg(next_control(341,black)).
neg(next_control(342,black)).
neg(next_control(343,black)).
neg(next_control(344,white)).
neg(next_control(345,black)).
neg(next_control(346,white)).
neg(next_control(347,white)).
neg(next_control(348,white)).
neg(next_control(349,black)).
neg(next_control(35,black)).
neg(next_control(350,black)).
neg(next_control(351,white)).
neg(next_control(352,black)).
neg(next_control(353,white)).
neg(next_control(354,black)).
neg(next_control(355,black)).
neg(next_control(356,white)).
neg(next_control(36,black)).
neg(next_control(37,black)).
neg(next_control(38,white)).
neg(next_control(39,black)).
neg(next_control(4,white)).
neg(next_control(40,white)).
neg(next_control(41,black)).
neg(next_control(42,white)).
neg(next_control(43,white)).
neg(next_control(44,black)).
neg(next_control(45,black)).
neg(next_control(46,black)).
neg(next_control(47,black)).
neg(next_control(48,white)).
neg(next_control(49,black)).
neg(next_control(5,black)).
neg(next_control(50,black)).
neg(next_control(51,white)).
neg(next_control(52,white)).
neg(next_control(53,black)).
neg(next_control(54,white)).
neg(next_control(55,black)).
neg(next_control(56,black)).
neg(next_control(57,black)).
neg(next_control(58,black)).
neg(next_control(59,black)).
neg(next_control(6,black)).
neg(next_control(60,black)).
neg(next_control(61,white)).
neg(next_control(62,black)).
neg(next_control(63,black)).
neg(next_control(64,white)).
neg(next_control(65,black)).
neg(next_control(66,black)).
neg(next_control(67,white)).
neg(next_control(68,white)).
neg(next_control(69,black)).
neg(next_control(7,black)).
neg(next_control(70,white)).
neg(next_control(71,black)).
neg(next_control(72,white)).
neg(next_control(73,white)).
neg(next_control(74,black)).
neg(next_control(75,black)).
neg(next_control(76,white)).
neg(next_control(77,white)).
neg(next_control(78,white)).
neg(next_control(79,white)).
neg(next_control(8,black)).
neg(next_control(80,black)).
neg(next_control(81,white)).
neg(next_control(82,white)).
neg(next_control(83,black)).
neg(next_control(84,white)).
neg(next_control(85,black)).
neg(next_control(86,white)).
neg(next_control(87,white)).
neg(next_control(88,black)).
neg(next_control(89,black)).
neg(next_control(9,black)).
neg(next_control(90,white)).
neg(next_control(91,white)).
neg(next_control(92,black)).
neg(next_control(93,black)).
neg(next_control(94,white)).
neg(next_control(95,white)).
neg(next_control(96,white)).
neg(next_control(97,white)).
neg(next_control(98,white)).
neg(next_control(99,black)).
pos(next_control(1,black)).
pos(next_control(10,white)).
pos(next_control(100,white)).
pos(next_control(101,white)).
pos(next_control(102,black)).
pos(next_control(103,white)).
pos(next_control(104,black)).
pos(next_control(105,black)).
pos(next_control(106,white)).
pos(next_control(107,white)).
pos(next_control(108,black)).
pos(next_control(109,black)).
pos(next_control(11,white)).
pos(next_control(110,black)).
pos(next_control(111,black)).
pos(next_control(112,white)).
pos(next_control(113,white)).
pos(next_control(114,black)).
pos(next_control(115,white)).
pos(next_control(116,white)).
pos(next_control(117,white)).
pos(next_control(118,white)).
pos(next_control(119,white)).
pos(next_control(12,white)).
pos(next_control(120,white)).
pos(next_control(121,black)).
pos(next_control(122,black)).
pos(next_control(123,white)).
pos(next_control(124,white)).
pos(next_control(125,white)).
pos(next_control(126,black)).
pos(next_control(127,black)).
pos(next_control(128,white)).
pos(next_control(129,black)).
pos(next_control(13,white)).
pos(next_control(130,white)).
pos(next_control(131,white)).
pos(next_control(132,white)).
pos(next_control(133,black)).
pos(next_control(134,black)).
pos(next_control(135,black)).
pos(next_control(136,white)).
pos(next_control(137,black)).
pos(next_control(138,white)).
pos(next_control(139,black)).
pos(next_control(14,black)).
pos(next_control(140,black)).
pos(next_control(141,white)).
pos(next_control(142,white)).
pos(next_control(143,white)).
pos(next_control(144,black)).
pos(next_control(145,black)).
pos(next_control(146,white)).
pos(next_control(147,black)).
pos(next_control(148,white)).
pos(next_control(149,black)).
pos(next_control(15,black)).
pos(next_control(150,black)).
pos(next_control(151,black)).
pos(next_control(152,white)).
pos(next_control(153,white)).
pos(next_control(154,white)).
pos(next_control(155,black)).
pos(next_control(156,black)).
pos(next_control(157,black)).
pos(next_control(158,white)).
pos(next_control(159,black)).
pos(next_control(16,white)).
pos(next_control(160,black)).
pos(next_control(161,black)).
pos(next_control(162,white)).
pos(next_control(163,black)).
pos(next_control(164,white)).
pos(next_control(165,white)).
pos(next_control(166,black)).
pos(next_control(167,black)).
pos(next_control(168,white)).
pos(next_control(169,black)).
pos(next_control(17,black)).
pos(next_control(170,white)).
pos(next_control(171,white)).
pos(next_control(172,black)).
pos(next_control(173,black)).
pos(next_control(174,white)).
pos(next_control(175,white)).
pos(next_control(176,black)).
pos(next_control(177,white)).
pos(next_control(178,black)).
pos(next_control(179,black)).
pos(next_control(18,black)).
pos(next_control(180,black)).
pos(next_control(181,black)).
pos(next_control(182,white)).
pos(next_control(183,black)).
pos(next_control(184,black)).
pos(next_control(185,white)).
pos(next_control(186,black)).
pos(next_control(187,black)).
pos(next_control(188,black)).
pos(next_control(189,white)).
pos(next_control(19,black)).
pos(next_control(190,white)).
pos(next_control(191,black)).
pos(next_control(192,white)).
pos(next_control(193,white)).
pos(next_control(194,black)).
pos(next_control(195,black)).
pos(next_control(196,white)).
pos(next_control(197,white)).
pos(next_control(198,black)).
pos(next_control(199,white)).
pos(next_control(2,black)).
pos(next_control(20,white)).
pos(next_control(200,black)).
pos(next_control(201,black)).
pos(next_control(202,black)).
pos(next_control(203,white)).
pos(next_control(204,white)).
pos(next_control(205,white)).
pos(next_control(206,white)).
pos(next_control(207,black)).
pos(next_control(208,white)).
pos(next_control(209,white)).
pos(next_control(21,white)).
pos(next_control(210,black)).
pos(next_control(211,black)).
pos(next_control(212,black)).
pos(next_control(213,white)).
pos(next_control(214,black)).
pos(next_control(215,white)).
pos(next_control(216,black)).
pos(next_control(217,black)).
pos(next_control(218,black)).
pos(next_control(219,white)).
pos(next_control(22,white)).
pos(next_control(220,black)).
pos(next_control(221,white)).
pos(next_control(222,white)).
pos(next_control(223,white)).
pos(next_control(224,black)).
pos(next_control(225,white)).
pos(next_control(226,black)).
pos(next_control(227,white)).
pos(next_control(228,white)).
pos(next_control(229,black)).
pos(next_control(23,black)).
pos(next_control(230,white)).
pos(next_control(231,black)).
pos(next_control(232,black)).
pos(next_control(233,white)).
pos(next_control(234,white)).
pos(next_control(235,white)).
pos(next_control(236,black)).
pos(next_control(237,white)).
pos(next_control(238,white)).
pos(next_control(239,white)).
pos(next_control(24,white)).
pos(next_control(240,black)).
pos(next_control(241,black)).
pos(next_control(242,black)).
pos(next_control(243,white)).
pos(next_control(244,black)).
pos(next_control(245,white)).
pos(next_control(246,black)).
pos(next_control(247,white)).
pos(next_control(248,black)).
pos(next_control(249,white)).
pos(next_control(25,black)).
pos(next_control(250,white)).
pos(next_control(251,white)).
pos(next_control(252,white)).
pos(next_control(253,white)).
pos(next_control(254,white)).
pos(next_control(255,black)).
pos(next_control(256,black)).
pos(next_control(257,black)).
pos(next_control(258,white)).
pos(next_control(259,white)).
pos(next_control(26,black)).
pos(next_control(260,white)).
pos(next_control(261,white)).
pos(next_control(262,black)).
pos(next_control(263,black)).
pos(next_control(264,white)).
pos(next_control(265,black)).
pos(next_control(266,white)).
pos(next_control(267,white)).
pos(next_control(268,black)).
pos(next_control(269,black)).
pos(next_control(27,white)).
pos(next_control(270,white)).
pos(next_control(271,white)).
pos(next_control(272,black)).
pos(next_control(273,white)).
pos(next_control(274,black)).
pos(next_control(275,white)).
pos(next_control(276,white)).
pos(next_control(277,white)).
pos(next_control(278,black)).
pos(next_control(279,white)).
pos(next_control(28,black)).
pos(next_control(280,black)).
pos(next_control(281,black)).
pos(next_control(282,white)).
pos(next_control(283,white)).
pos(next_control(284,black)).
pos(next_control(285,white)).
pos(next_control(286,black)).
pos(next_control(287,white)).
pos(next_control(288,black)).
pos(next_control(289,white)).
pos(next_control(29,white)).
pos(next_control(290,black)).
pos(next_control(291,white)).
pos(next_control(292,white)).
pos(next_control(293,white)).
pos(next_control(294,black)).
pos(next_control(295,white)).
pos(next_control(296,black)).
pos(next_control(297,white)).
pos(next_control(298,white)).
pos(next_control(299,black)).
pos(next_control(3,black)).
pos(next_control(30,white)).
pos(next_control(300,white)).
pos(next_control(301,white)).
pos(next_control(302,black)).
pos(next_control(303,white)).
pos(next_control(304,white)).
pos(next_control(305,black)).
pos(next_control(306,black)).
pos(next_control(307,white)).
pos(next_control(308,white)).
pos(next_control(309,black)).
pos(next_control(31,black)).
pos(next_control(310,black)).
pos(next_control(311,white)).
pos(next_control(312,black)).
pos(next_control(313,white)).
pos(next_control(314,black)).
pos(next_control(315,white)).
pos(next_control(316,black)).
pos(next_control(317,white)).
pos(next_control(318,black)).
pos(next_control(319,white)).
pos(next_control(32,white)).
pos(next_control(320,white)).
pos(next_control(321,white)).
pos(next_control(322,white)).
pos(next_control(323,black)).
pos(next_control(324,white)).
pos(next_control(325,black)).
pos(next_control(326,white)).
pos(next_control(327,white)).
pos(next_control(328,black)).
pos(next_control(329,white)).
pos(next_control(33,white)).
pos(next_control(330,white)).
pos(next_control(331,black)).
pos(next_control(332,white)).
pos(next_control(333,black)).
pos(next_control(334,white)).
pos(next_control(335,black)).
pos(next_control(336,white)).
pos(next_control(337,black)).
pos(next_control(338,white)).
pos(next_control(339,black)).
pos(next_control(34,white)).
pos(next_control(340,white)).
pos(next_control(341,white)).
pos(next_control(342,white)).
pos(next_control(343,white)).
pos(next_control(344,black)).
pos(next_control(345,white)).
pos(next_control(346,black)).
pos(next_control(347,black)).
pos(next_control(348,black)).
pos(next_control(349,white)).
pos(next_control(35,white)).
pos(next_control(350,white)).
pos(next_control(351,black)).
pos(next_control(352,white)).
pos(next_control(353,black)).
pos(next_control(354,white)).
pos(next_control(355,white)).
pos(next_control(356,black)).
pos(next_control(36,white)).
pos(next_control(37,white)).
pos(next_control(38,black)).
pos(next_control(39,white)).
pos(next_control(4,black)).
pos(next_control(40,black)).
pos(next_control(41,white)).
pos(next_control(42,black)).
pos(next_control(43,black)).
pos(next_control(44,white)).
pos(next_control(45,white)).
pos(next_control(46,white)).
pos(next_control(47,white)).
pos(next_control(48,black)).
pos(next_control(49,white)).
pos(next_control(5,white)).
pos(next_control(50,white)).
pos(next_control(51,black)).
pos(next_control(52,black)).
pos(next_control(53,white)).
pos(next_control(54,black)).
pos(next_control(55,white)).
pos(next_control(56,white)).
pos(next_control(57,white)).
pos(next_control(58,white)).
pos(next_control(59,white)).
pos(next_control(6,white)).
pos(next_control(60,white)).
pos(next_control(61,black)).
pos(next_control(62,white)).
pos(next_control(63,white)).
pos(next_control(64,black)).
pos(next_control(65,white)).
pos(next_control(66,white)).
pos(next_control(67,black)).
pos(next_control(68,black)).
pos(next_control(69,white)).
pos(next_control(7,white)).
pos(next_control(70,black)).
pos(next_control(71,white)).
pos(next_control(72,black)).
pos(next_control(73,black)).
pos(next_control(74,white)).
pos(next_control(75,white)).
pos(next_control(76,black)).
pos(next_control(77,black)).
pos(next_control(78,black)).
pos(next_control(79,black)).
pos(next_control(8,white)).
pos(next_control(80,white)).
pos(next_control(81,black)).
pos(next_control(82,black)).
pos(next_control(83,white)).
pos(next_control(84,black)).
pos(next_control(85,white)).
pos(next_control(86,black)).
pos(next_control(87,black)).
pos(next_control(88,white)).
pos(next_control(89,white)).
pos(next_control(9,white)).
pos(next_control(90,black)).
pos(next_control(91,black)).
pos(next_control(92,white)).
pos(next_control(93,white)).
pos(next_control(94,black)).
pos(next_control(95,black)).
pos(next_control(96,black)).
pos(next_control(97,black)).
pos(next_control(98,black)).
pos(next_control(99,white)).