neg(next_control(1,black)).
neg(next_control(10,black)).
neg(next_control(11,white)).
neg(next_control(12,white)).
neg(next_control(13,white)).
neg(next_control(2,white)).
neg(next_control(3,white)).
neg(next_control(4,white)).
neg(next_control(5,white)).
neg(next_control(6,white)).
neg(next_control(7,black)).
neg(next_control(8,white)).
neg(next_control(9,white)).
pos(next_control(1,white)).
pos(next_control(10,white)).
pos(next_control(11,black)).
pos(next_control(12,black)).
pos(next_control(13,black)).
pos(next_control(2,black)).
pos(next_control(3,black)).
pos(next_control(4,black)).
pos(next_control(5,black)).
pos(next_control(6,black)).
pos(next_control(7,white)).
pos(next_control(8,black)).
pos(next_control(9,black)).