enzyme(amine_oxidase__flavin_containing__a,phentermine).
enzyme(amine_oxidase__flavin_containing__a,sertraline).
enzyme(amine_oxidase__flavin_containing__b,phentermine).
enzyme(amine_oxidase__flavin_containing__b,sertraline).
enzyme(arylamine_n_acetyltransferase_2,acetaminophen).
enzyme(arylamine_n_acetyltransferase_2,clonazepam).
enzyme(bile_salt_sulfotransferase,acetaminophen).
enzyme(branched_chain_amino_acid_aminotransferase,gabapentin).
enzyme(c6_phosphogluconate_dehydrogenase,meloxicam).
enzyme(c_cytosolic,gabapentin).
enzyme(c_decarboxylating,meloxicam).
enzyme(c_mitochondrial,omeprazole).
enzyme(carboxylesterase,methylphenidate).
enzyme(cholesterol_side_chain_cleavage_enzyme,omeprazole).
enzyme(cyp2b_protein,fluoxetine).
enzyme(cyp2b_protein,sertraline).
enzyme(cytochrome_p450_19a1,methadone).
enzyme(cytochrome_p450_1a1,acetaminophen).
enzyme(cytochrome_p450_1a1,amlodipine).
enzyme(cytochrome_p450_1a1,clonidine).
enzyme(cytochrome_p450_1a1,diclofenac).
enzyme(cytochrome_p450_1a1,omeprazole).
enzyme(cytochrome_p450_1a1,propranolol).
enzyme(cytochrome_p450_1a1,sildenafil).
enzyme(cytochrome_p450_1a1,warfarin).
enzyme(cytochrome_p450_1a2,acetaminophen).
enzyme(cytochrome_p450_1a2,amitriptyline).
enzyme(cytochrome_p450_1a2,amlodipine).
enzyme(cytochrome_p450_1a2,azithromycin).
enzyme(cytochrome_p450_1a2,ciprofloxacin).
enzyme(cytochrome_p450_1a2,clonidine).
enzyme(cytochrome_p450_1a2,cyclobenzaprine).
enzyme(cytochrome_p450_1a2,diazepam).
enzyme(cytochrome_p450_1a2,diclofenac).
enzyme(cytochrome_p450_1a2,diphenhydramine).
enzyme(cytochrome_p450_1a2,duloxetine).
enzyme(cytochrome_p450_1a2,fluoxetine).
enzyme(cytochrome_p450_1a2,losartan).
enzyme(cytochrome_p450_1a2,methadone).
enzyme(cytochrome_p450_1a2,naproxen).
enzyme(cytochrome_p450_1a2,omeprazole).
enzyme(cytochrome_p450_1a2,ondansetron).
enzyme(cytochrome_p450_1a2,pantoprazole).
enzyme(cytochrome_p450_1a2,paroxetine).
enzyme(cytochrome_p450_1a2,phentermine).
enzyme(cytochrome_p450_1a2,propranolol).
enzyme(cytochrome_p450_1a2,sertraline).
enzyme(cytochrome_p450_1a2,warfarin).
enzyme(cytochrome_p450_1a2,zolpidem).
enzyme(cytochrome_p450_1b1,omeprazole).
enzyme(cytochrome_p450_2a6,acetaminophen).
enzyme(cytochrome_p450_2a6,amlodipine).
enzyme(cytochrome_p450_2a6,amphetamine).
enzyme(cytochrome_p450_2a6,azithromycin).
enzyme(cytochrome_p450_2b6,amitriptyline).
enzyme(cytochrome_p450_2b6,amlodipine).
enzyme(cytochrome_p450_2b6,atorvastatin).
enzyme(cytochrome_p450_2b6,diazepam).
enzyme(cytochrome_p450_2b6,diclofenac).
enzyme(cytochrome_p450_2b6,diphenhydramine).
enzyme(cytochrome_p450_2b6,fluoxetine).
enzyme(cytochrome_p450_2b6,methadone).
enzyme(cytochrome_p450_2b6,paroxetine).
enzyme(cytochrome_p450_2b6,sertraline).
enzyme(cytochrome_p450_2b6,simvastatin).
enzyme(cytochrome_p450_2b6,tramadol).
enzyme(cytochrome_p450_2b6,venlafaxine).
enzyme(cytochrome_p450_2c18,diazepam).
enzyme(cytochrome_p450_2c18,diclofenac).
enzyme(cytochrome_p450_2c18,diphenhydramine).
enzyme(cytochrome_p450_2c18,methadone).
enzyme(cytochrome_p450_2c18,omeprazole).
enzyme(cytochrome_p450_2c18,warfarin).
enzyme(cytochrome_p450_2c19,acetylsalicylic_acid).
enzyme(cytochrome_p450_2c19,amitriptyline).
enzyme(cytochrome_p450_2c19,amoxicillin).
enzyme(cytochrome_p450_2c19,atorvastatin).
enzyme(cytochrome_p450_2c19,diazepam).
enzyme(cytochrome_p450_2c19,diclofenac).
enzyme(cytochrome_p450_2c19,diphenhydramine).
enzyme(cytochrome_p450_2c19,esomeprazole).
enzyme(cytochrome_p450_2c19,fluoxetine).
enzyme(cytochrome_p450_2c19,ibuprofen).
enzyme(cytochrome_p450_2c19,loratadine).
enzyme(cytochrome_p450_2c19,losartan).
enzyme(cytochrome_p450_2c19,methadone).
enzyme(cytochrome_p450_2c19,metoprolol).
enzyme(cytochrome_p450_2c19,omeprazole).
enzyme(cytochrome_p450_2c19,pantoprazole).
enzyme(cytochrome_p450_2c19,prednisone).
enzyme(cytochrome_p450_2c19,propranolol).
enzyme(cytochrome_p450_2c19,quetiapine).
enzyme(cytochrome_p450_2c19,sertraline).
enzyme(cytochrome_p450_2c19,sildenafil).
enzyme(cytochrome_p450_2c19,simvastatin).
enzyme(cytochrome_p450_2c19,venlafaxine).
enzyme(cytochrome_p450_2c19,warfarin).
enzyme(cytochrome_p450_2c19,zolpidem).
enzyme(cytochrome_p450_2c8,acetaminophen).
enzyme(cytochrome_p450_2c8,acetylsalicylic_acid).
enzyme(cytochrome_p450_2c8,amitriptyline).
enzyme(cytochrome_p450_2c8,amlodipine).
enzyme(cytochrome_p450_2c8,atorvastatin).
enzyme(cytochrome_p450_2c8,celecoxib).
enzyme(cytochrome_p450_2c8,diazepam).
enzyme(cytochrome_p450_2c8,diclofenac).
enzyme(cytochrome_p450_2c8,fenofibrate).
enzyme(cytochrome_p450_2c8,ibuprofen).
enzyme(cytochrome_p450_2c8,levothyroxine).
enzyme(cytochrome_p450_2c8,loratadine).
enzyme(cytochrome_p450_2c8,losartan).
enzyme(cytochrome_p450_2c8,meloxicam).
enzyme(cytochrome_p450_2c8,methadone).
enzyme(cytochrome_p450_2c8,metronidazole).
enzyme(cytochrome_p450_2c8,morphine).
enzyme(cytochrome_p450_2c8,naloxone).
enzyme(cytochrome_p450_2c8,naproxen).
enzyme(cytochrome_p450_2c8,omeprazole).
enzyme(cytochrome_p450_2c8,paroxetine).
enzyme(cytochrome_p450_2c8,pravastatin).
enzyme(cytochrome_p450_2c8,salmeterol).
enzyme(cytochrome_p450_2c8,simvastatin).
enzyme(cytochrome_p450_2c8,sitagliptin).
enzyme(cytochrome_p450_2c8,warfarin).
enzyme(cytochrome_p450_2c9,acetaminophen).
enzyme(cytochrome_p450_2c9,acetylsalicylic_acid).
enzyme(cytochrome_p450_2c9,alprazolam).
enzyme(cytochrome_p450_2c9,amitriptyline).
enzyme(cytochrome_p450_2c9,amlodipine).
enzyme(cytochrome_p450_2c9,atorvastatin).
enzyme(cytochrome_p450_2c9,celecoxib).
enzyme(cytochrome_p450_2c9,diazepam).
enzyme(cytochrome_p450_2c9,diclofenac).
enzyme(cytochrome_p450_2c9,diphenhydramine).
enzyme(cytochrome_p450_2c9,fenofibrate).
enzyme(cytochrome_p450_2c9,fluoxetine).
enzyme(cytochrome_p450_2c9,hydromorphone).
enzyme(cytochrome_p450_2c9,ibuprofen).
enzyme(cytochrome_p450_2c9,loratadine).
enzyme(cytochrome_p450_2c9,losartan).
enzyme(cytochrome_p450_2c9,meloxicam).
enzyme(cytochrome_p450_2c9,methadone).
enzyme(cytochrome_p450_2c9,metronidazole).
enzyme(cytochrome_p450_2c9,naproxen).
enzyme(cytochrome_p450_2c9,omeprazole).
enzyme(cytochrome_p450_2c9,ondansetron).
enzyme(cytochrome_p450_2c9,pantoprazole).
enzyme(cytochrome_p450_2c9,paroxetine).
enzyme(cytochrome_p450_2c9,phentermine).
enzyme(cytochrome_p450_2c9,pravastatin).
enzyme(cytochrome_p450_2c9,sertraline).
enzyme(cytochrome_p450_2c9,sildenafil).
enzyme(cytochrome_p450_2c9,simvastatin).
enzyme(cytochrome_p450_2c9,venlafaxine).
enzyme(cytochrome_p450_2c9,warfarin).
enzyme(cytochrome_p450_2c9,zolpidem).
enzyme(cytochrome_p450_2d6,acetaminophen).
enzyme(cytochrome_p450_2d6,amitriptyline).
enzyme(cytochrome_p450_2d6,amlodipine).
enzyme(cytochrome_p450_2d6,amphetamine).
enzyme(cytochrome_p450_2d6,aripiprazole).
enzyme(cytochrome_p450_2d6,atorvastatin).
enzyme(cytochrome_p450_2d6,celecoxib).
enzyme(cytochrome_p450_2d6,cephalexin).
enzyme(cytochrome_p450_2d6,clonidine).
enzyme(cytochrome_p450_2d6,cyclobenzaprine).
enzyme(cytochrome_p450_2d6,diphenhydramine).
enzyme(cytochrome_p450_2d6,duloxetine).
enzyme(cytochrome_p450_2d6,fluoxetine).
enzyme(cytochrome_p450_2d6,hydrocodone).
enzyme(cytochrome_p450_2d6,hydromorphone).
enzyme(cytochrome_p450_2d6,hydroxyzine).
enzyme(cytochrome_p450_2d6,loratadine).
enzyme(cytochrome_p450_2d6,methadone).
enzyme(cytochrome_p450_2d6,methylphenidate).
enzyme(cytochrome_p450_2d6,metoprolol).
enzyme(cytochrome_p450_2d6,morphine).
enzyme(cytochrome_p450_2d6,omeprazole).
enzyme(cytochrome_p450_2d6,ondansetron).
enzyme(cytochrome_p450_2d6,oxycodone).
enzyme(cytochrome_p450_2d6,paroxetine).
enzyme(cytochrome_p450_2d6,phentermine).
enzyme(cytochrome_p450_2d6,pravastatin).
enzyme(cytochrome_p450_2d6,propranolol).
enzyme(cytochrome_p450_2d6,quetiapine).
enzyme(cytochrome_p450_2d6,risperidone).
enzyme(cytochrome_p450_2d6,sertraline).
enzyme(cytochrome_p450_2d6,sildenafil).
enzyme(cytochrome_p450_2d6,simvastatin).
enzyme(cytochrome_p450_2d6,tamsulosin).
enzyme(cytochrome_p450_2d6,tramadol).
enzyme(cytochrome_p450_2d6,trazodone).
enzyme(cytochrome_p450_2d6,venlafaxine).
enzyme(cytochrome_p450_2d6,zolpidem).
enzyme(cytochrome_p450_2e1,acetaminophen).
enzyme(cytochrome_p450_2e1,amitriptyline).
enzyme(cytochrome_p450_2e1,clonazepam).
enzyme(cytochrome_p450_2e1,diazepam).
enzyme(cytochrome_p450_2e1,diclofenac).
enzyme(cytochrome_p450_2e1,ondansetron).
enzyme(cytochrome_p450_2e1,sildenafil).
enzyme(cytochrome_p450_2j2,rivaroxaban).
enzyme(cytochrome_p450_3a4,acetaminophen).
enzyme(cytochrome_p450_3a4,alprazolam).
enzyme(cytochrome_p450_3a4,amitriptyline).
enzyme(cytochrome_p450_3a4,amlodipine).
enzyme(cytochrome_p450_3a4,aripiprazole).
enzyme(cytochrome_p450_3a4,atorvastatin).
enzyme(cytochrome_p450_3a4,azithromycin).
enzyme(cytochrome_p450_3a4,budesonide).
enzyme(cytochrome_p450_3a4,celecoxib).
enzyme(cytochrome_p450_3a4,cephalexin).
enzyme(cytochrome_p450_3a4,ciprofloxacin).
enzyme(cytochrome_p450_3a4,clindamycin).
enzyme(cytochrome_p450_3a4,clonazepam).
enzyme(cytochrome_p450_3a4,clonidine).
enzyme(cytochrome_p450_3a4,cyclobenzaprine).
enzyme(cytochrome_p450_3a4,diazepam).
enzyme(cytochrome_p450_3a4,diclofenac).
enzyme(cytochrome_p450_3a4,doxycycline).
enzyme(cytochrome_p450_3a4,esomeprazole).
enzyme(cytochrome_p450_3a4,fenofibrate).
enzyme(cytochrome_p450_3a4,fluoxetine).
enzyme(cytochrome_p450_3a4,hydrocodone).
enzyme(cytochrome_p450_3a4,hydromorphone).
enzyme(cytochrome_p450_3a4,levothyroxine).
enzyme(cytochrome_p450_3a4,loratadine).
enzyme(cytochrome_p450_3a4,losartan).
enzyme(cytochrome_p450_3a4,meloxicam).
enzyme(cytochrome_p450_3a4,methadone).
enzyme(cytochrome_p450_3a4,metronidazole).
enzyme(cytochrome_p450_3a4,morphine).
enzyme(cytochrome_p450_3a4,naloxone).
enzyme(cytochrome_p450_3a4,omeprazole).
enzyme(cytochrome_p450_3a4,ondansetron).
enzyme(cytochrome_p450_3a4,oxycodone).
enzyme(cytochrome_p450_3a4,pantoprazole).
enzyme(cytochrome_p450_3a4,pravastatin).
enzyme(cytochrome_p450_3a4,prednisone).
enzyme(cytochrome_p450_3a4,propranolol).
enzyme(cytochrome_p450_3a4,quetiapine).
enzyme(cytochrome_p450_3a4,risperidone).
enzyme(cytochrome_p450_3a4,rivaroxaban).
enzyme(cytochrome_p450_3a4,salbutamol).
enzyme(cytochrome_p450_3a4,salmeterol).
enzyme(cytochrome_p450_3a4,sertraline).
enzyme(cytochrome_p450_3a4,sildenafil).
enzyme(cytochrome_p450_3a4,simvastatin).
enzyme(cytochrome_p450_3a4,sitagliptin).
enzyme(cytochrome_p450_3a4,tadalafil).
enzyme(cytochrome_p450_3a4,tamsulosin).
enzyme(cytochrome_p450_3a4,tramadol).
enzyme(cytochrome_p450_3a4,trazodone).
enzyme(cytochrome_p450_3a4,venlafaxine).
enzyme(cytochrome_p450_3a4,warfarin).
enzyme(cytochrome_p450_3a4,zolpidem).
enzyme(cytochrome_p450_3a5,alprazolam).
enzyme(cytochrome_p450_3a5,amitriptyline).
enzyme(cytochrome_p450_3a5,amlodipine).
enzyme(cytochrome_p450_3a5,aripiprazole).
enzyme(cytochrome_p450_3a5,atorvastatin).
enzyme(cytochrome_p450_3a5,ciprofloxacin).
enzyme(cytochrome_p450_3a5,clonidine).
enzyme(cytochrome_p450_3a5,diazepam).
enzyme(cytochrome_p450_3a5,fluoxetine).
enzyme(cytochrome_p450_3a5,losartan).
enzyme(cytochrome_p450_3a5,methadone).
enzyme(cytochrome_p450_3a5,ondansetron).
enzyme(cytochrome_p450_3a5,oxycodone).
enzyme(cytochrome_p450_3a5,pravastatin).
enzyme(cytochrome_p450_3a5,propranolol).
enzyme(cytochrome_p450_3a5,quetiapine).
enzyme(cytochrome_p450_3a5,risperidone).
enzyme(cytochrome_p450_3a5,rivaroxaban).
enzyme(cytochrome_p450_3a5,salmeterol).
enzyme(cytochrome_p450_3a5,sildenafil).
enzyme(cytochrome_p450_3a5,simvastatin).
enzyme(cytochrome_p450_3a5,trazodone).
enzyme(cytochrome_p450_3a5,zolpidem).
enzyme(cytochrome_p450_3a7,alprazolam).
enzyme(cytochrome_p450_3a7,amlodipine).
enzyme(cytochrome_p450_3a7,aripiprazole).
enzyme(cytochrome_p450_3a7,atorvastatin).
enzyme(cytochrome_p450_3a7,ciprofloxacin).
enzyme(cytochrome_p450_3a7,diazepam).
enzyme(cytochrome_p450_3a7,methadone).
enzyme(cytochrome_p450_3a7,ondansetron).
enzyme(cytochrome_p450_3a7,oxycodone).
enzyme(cytochrome_p450_3a7,propranolol).
enzyme(cytochrome_p450_3a7,quetiapine).
enzyme(cytochrome_p450_3a7,risperidone).
enzyme(cytochrome_p450_3a7,salmeterol).
enzyme(cytochrome_p450_3a7,sildenafil).
enzyme(cytochrome_p450_3a7,simvastatin).
enzyme(cytochrome_p450_3a7,trazodone).
enzyme(cytochrome_p450_3a7,zolpidem).
enzyme(dihydrofolate_reductase,lamotrigine).
enzyme(estrogen_sulfotransferase,acetaminophen).
enzyme(prostaglandin_g_h_synthase_1,diazepam).
enzyme(prostaglandin_g_h_synthase_1,diclofenac).
enzyme(prostaglandin_g_h_synthase_1,diphenhydramine).
enzyme(prostaglandin_g_h_synthase_1,hydromorphone).
enzyme(prostaglandin_g_h_synthase_1,ibuprofen).
enzyme(prostaglandin_g_h_synthase_1,zolpidem).
enzyme(prostaglandin_g_h_synthase_2,ibuprofen).
enzyme(sulfotransferase_1a1,acetaminophen).
enzyme(sulfotransferase_1a3_1a4,acetaminophen).
enzyme(udp_glucuronosyltransferase_1_1,acetaminophen).
enzyme(udp_glucuronosyltransferase_1_1,atorvastatin).
enzyme(udp_glucuronosyltransferase_1_1,diclofenac).
enzyme(udp_glucuronosyltransferase_1_1,ibuprofen).
enzyme(udp_glucuronosyltransferase_1_1,losartan).
enzyme(udp_glucuronosyltransferase_1_1,morphine).
enzyme(udp_glucuronosyltransferase_1_1,naproxen).
enzyme(udp_glucuronosyltransferase_1_1,simvastatin).
enzyme(udp_glucuronosyltransferase_1_10,acetaminophen).
enzyme(udp_glucuronosyltransferase_1_10,losartan).
enzyme(udp_glucuronosyltransferase_1_3,atorvastatin).
enzyme(udp_glucuronosyltransferase_1_3,ibuprofen).
enzyme(udp_glucuronosyltransferase_1_3,lamotrigine).
enzyme(udp_glucuronosyltransferase_1_3,losartan).
enzyme(udp_glucuronosyltransferase_1_3,morphine).
enzyme(udp_glucuronosyltransferase_1_3,simvastatin).
enzyme(udp_glucuronosyltransferase_1_4,lamotrigine).
enzyme(udp_glucuronosyltransferase_1_6,acetaminophen).
enzyme(udp_glucuronosyltransferase_1_8,morphine).
enzyme(udp_glucuronosyltransferase_1_9,acetaminophen).
enzyme(udp_glucuronosyltransferase_1_9,hydromorphone).
enzyme(udp_glucuronosyltransferase_1_9,ibuprofen).
enzyme(udp_glucuronosyltransferase_2b15,acetaminophen).
enzyme(udp_glucuronosyltransferase_2b15,lorazepam).
enzyme(udp_glucuronosyltransferase_2b15,morphine).
enzyme(udp_glucuronosyltransferase_2b17,losartan).
enzyme(udp_glucuronosyltransferase_2b4,ibuprofen).
enzyme(udp_glucuronosyltransferase_2b4,morphine).
enzyme(udp_glucuronosyltransferase_2b7,atorvastatin).
enzyme(udp_glucuronosyltransferase_2b7,diclofenac).
enzyme(udp_glucuronosyltransferase_2b7,ibuprofen).
enzyme(udp_glucuronosyltransferase_2b7,losartan).
enzyme(udp_glucuronosyltransferase_2b7,morphine).
enzyme(udp_glucuronosyltransferase_2b7,naproxen).
enzyme(udp_glucuronosyltransferase_2b7,simvastatin).
enzymeinducer(acetaminophen,cytochrome_p450_3a4).
enzymeinducer(acetylsalicylic_acid,cytochrome_p450_2c19).
enzymeinducer(aripiprazole,cytochrome_p450_2d6).
enzymeinducer(atorvastatin,cytochrome_p450_2b6).
enzymeinducer(atorvastatin,cytochrome_p450_2c9).
enzymeinducer(atorvastatin,cytochrome_p450_3a4).
enzymeinducer(loratadine,cytochrome_p450_2c19).
enzymeinducer(loratadine,cytochrome_p450_2d6).
enzymeinducer(loratadine,cytochrome_p450_3a4).
enzymeinducer(methadone,cytochrome_p450_3a4).
enzymeinducer(omeprazole,cytochrome_p450_1a1).
enzymeinducer(omeprazole,cytochrome_p450_1a2).
enzymeinducer(omeprazole,cytochrome_p450_1b1).
enzymeinducer(omeprazole,cytochrome_p450_3a4).
enzymeinducer(pantoprazole,cytochrome_p450_1a2).
enzymeinducer(pantoprazole,cytochrome_p450_3a4).
enzymeinducer(phentermine,cytochrome_p450_2c9).
enzymeinducer(prednisone,cytochrome_p450_2c19).
enzymeinducer(prednisone,cytochrome_p450_3a4).
enzymeinducer(simvastatin,cytochrome_p450_2b6).
enzymeinducer(simvastatin,cytochrome_p450_2c9).
enzymeinducer(simvastatin,cytochrome_p450_3a4).
enzymeinhibitor(acetaminophen,arylamine_n_acetyltransferase_2).
enzymeinhibitor(acetaminophen,cytochrome_p450_3a4).
enzymeinhibitor(alprazolam,cytochrome_p450_3a4).
enzymeinhibitor(amitriptyline,cytochrome_p450_1a2).
enzymeinhibitor(amitriptyline,cytochrome_p450_2c19).
enzymeinhibitor(amitriptyline,cytochrome_p450_2c8).
enzymeinhibitor(amitriptyline,cytochrome_p450_2d6).
enzymeinhibitor(amitriptyline,cytochrome_p450_2e1).
enzymeinhibitor(amlodipine,cytochrome_p450_1a1).
enzymeinhibitor(amlodipine,cytochrome_p450_1a2).
enzymeinhibitor(amlodipine,cytochrome_p450_2a6).
enzymeinhibitor(amlodipine,cytochrome_p450_2b6).
enzymeinhibitor(amlodipine,cytochrome_p450_2c8).
enzymeinhibitor(amlodipine,cytochrome_p450_2c9).
enzymeinhibitor(amlodipine,cytochrome_p450_2d6).
enzymeinhibitor(amlodipine,cytochrome_p450_3a4).
enzymeinhibitor(amphetamine,cytochrome_p450_2a6).
enzymeinhibitor(amphetamine,cytochrome_p450_2d6).
enzymeinhibitor(aripiprazole,cytochrome_p450_2d6).
enzymeinhibitor(atorvastatin,cytochrome_p450_2c19).
enzymeinhibitor(atorvastatin,cytochrome_p450_2c8).
enzymeinhibitor(atorvastatin,cytochrome_p450_2c9).
enzymeinhibitor(atorvastatin,cytochrome_p450_2d6).
enzymeinhibitor(atorvastatin,cytochrome_p450_3a4).
enzymeinhibitor(azithromycin,cytochrome_p450_1a2).
enzymeinhibitor(azithromycin,cytochrome_p450_2a6).
enzymeinhibitor(azithromycin,cytochrome_p450_3a4).
enzymeinhibitor(celecoxib,cytochrome_p450_2c8).
enzymeinhibitor(celecoxib,cytochrome_p450_2d6).
enzymeinhibitor(ciprofloxacin,cytochrome_p450_1a2).
enzymeinhibitor(ciprofloxacin,cytochrome_p450_3a4).
enzymeinhibitor(ciprofloxacin,cytochrome_p450_3a5).
enzymeinhibitor(ciprofloxacin,cytochrome_p450_3a7).
enzymeinhibitor(clindamycin,cytochrome_p450_3a4).
enzymeinhibitor(clonazepam,cytochrome_p450_2e1).
enzymeinhibitor(diazepam,cytochrome_p450_1a2).
enzymeinhibitor(diazepam,cytochrome_p450_2c19).
enzymeinhibitor(diazepam,cytochrome_p450_2c9).
enzymeinhibitor(diazepam,cytochrome_p450_2e1).
enzymeinhibitor(diazepam,cytochrome_p450_3a4).
enzymeinhibitor(diclofenac,cytochrome_p450_1a2).
enzymeinhibitor(diclofenac,cytochrome_p450_2c9).
enzymeinhibitor(diclofenac,cytochrome_p450_2e1).
enzymeinhibitor(diphenhydramine,cytochrome_p450_2d6).
enzymeinhibitor(doxycycline,cytochrome_p450_3a4).
enzymeinhibitor(duloxetine,cytochrome_p450_2d6).
enzymeinhibitor(esomeprazole,cytochrome_p450_2c19).
enzymeinhibitor(fenofibrate,cytochrome_p450_2c8).
enzymeinhibitor(fenofibrate,cytochrome_p450_2c9).
enzymeinhibitor(fluoxetine,cyp2b_protein).
enzymeinhibitor(fluoxetine,cytochrome_p450_1a2).
enzymeinhibitor(fluoxetine,cytochrome_p450_2c19).
enzymeinhibitor(fluoxetine,cytochrome_p450_2c9).
enzymeinhibitor(fluoxetine,cytochrome_p450_2d6).
enzymeinhibitor(fluoxetine,cytochrome_p450_3a4).
enzymeinhibitor(gabapentin,branched_chain_amino_acid_aminotransferase).
enzymeinhibitor(gabapentin,cytosolic).
enzymeinhibitor(hydroxyzine,cytochrome_p450_2d6).
enzymeinhibitor(ibuprofen,cytochrome_p450_2c9).
enzymeinhibitor(ibuprofen,prostaglandin_g_h_synthase_1).
enzymeinhibitor(ibuprofen,prostaglandin_g_h_synthase_2).
enzymeinhibitor(lamotrigine,dihydrofolate_reductase).
enzymeinhibitor(levothyroxine,cytochrome_p450_2c8).
enzymeinhibitor(loratadine,cytochrome_p450_2c19).
enzymeinhibitor(loratadine,cytochrome_p450_2c8).
enzymeinhibitor(loratadine,cytochrome_p450_2c9).
enzymeinhibitor(loratadine,cytochrome_p450_2d6).
enzymeinhibitor(loratadine,cytochrome_p450_3a4).
enzymeinhibitor(losartan,cytochrome_p450_1a2).
enzymeinhibitor(losartan,cytochrome_p450_2c19).
enzymeinhibitor(losartan,cytochrome_p450_2c8).
enzymeinhibitor(losartan,cytochrome_p450_2c9).
enzymeinhibitor(losartan,cytochrome_p450_3a4).
enzymeinhibitor(meloxicam,c6_phosphogluconate_dehydrogenase).
enzymeinhibitor(meloxicam,cytochrome_p450_2c8).
enzymeinhibitor(meloxicam,cytochrome_p450_2c9).
enzymeinhibitor(meloxicam,decarboxylating).
enzymeinhibitor(methadone,cytochrome_p450_2d6).
enzymeinhibitor(methadone,cytochrome_p450_3a4).
enzymeinhibitor(methylphenidate,cytochrome_p450_2d6).
enzymeinhibitor(metoprolol,cytochrome_p450_2d6).
enzymeinhibitor(metronidazole,cytochrome_p450_2c8).
enzymeinhibitor(metronidazole,cytochrome_p450_2c9).
enzymeinhibitor(metronidazole,cytochrome_p450_3a4).
enzymeinhibitor(omeprazole,cholesterol_side_chain_cleavage_enzyme).
enzymeinhibitor(omeprazole,cytochrome_p450_1a2).
enzymeinhibitor(omeprazole,cytochrome_p450_2c19).
enzymeinhibitor(omeprazole,cytochrome_p450_2c9).
enzymeinhibitor(omeprazole,cytochrome_p450_2d6).
enzymeinhibitor(omeprazole,cytochrome_p450_3a4).
enzymeinhibitor(omeprazole,mitochondrial).
enzymeinhibitor(ondansetron,cytochrome_p450_1a2).
enzymeinhibitor(ondansetron,cytochrome_p450_2d6).
enzymeinhibitor(pantoprazole,cytochrome_p450_2c19).
enzymeinhibitor(pantoprazole,cytochrome_p450_2c9).
enzymeinhibitor(paroxetine,cytochrome_p450_1a2).
enzymeinhibitor(paroxetine,cytochrome_p450_2b6).
enzymeinhibitor(paroxetine,cytochrome_p450_2c8).
enzymeinhibitor(paroxetine,cytochrome_p450_2c9).
enzymeinhibitor(paroxetine,cytochrome_p450_2d6).
enzymeinhibitor(phentermine,amine_oxidase__flavin_containing__a).
enzymeinhibitor(phentermine,amine_oxidase__flavin_containing__b).
enzymeinhibitor(phentermine,cytochrome_p450_1a2).
enzymeinhibitor(phentermine,cytochrome_p450_2c9).
enzymeinhibitor(phentermine,cytochrome_p450_2d6).
enzymeinhibitor(pravastatin,cytochrome_p450_2c8).
enzymeinhibitor(pravastatin,cytochrome_p450_2c9).
enzymeinhibitor(pravastatin,cytochrome_p450_2d6).
enzymeinhibitor(pravastatin,cytochrome_p450_3a4).
enzymeinhibitor(prednisone,cytochrome_p450_3a4).
enzymeinhibitor(propranolol,cytochrome_p450_1a1).
enzymeinhibitor(propranolol,cytochrome_p450_1a2).
enzymeinhibitor(propranolol,cytochrome_p450_2d6).
enzymeinhibitor(quetiapine,cytochrome_p450_2d6).
enzymeinhibitor(risperidone,cytochrome_p450_2d6).
enzymeinhibitor(risperidone,cytochrome_p450_3a4).
enzymeinhibitor(salbutamol,cytochrome_p450_3a4).
enzymeinhibitor(salmeterol,cytochrome_p450_2c8).
enzymeinhibitor(sertraline,cyp2b_protein).
enzymeinhibitor(sertraline,cytochrome_p450_1a2).
enzymeinhibitor(sertraline,cytochrome_p450_2b6).
enzymeinhibitor(sertraline,cytochrome_p450_2c19).
enzymeinhibitor(sertraline,cytochrome_p450_2c9).
enzymeinhibitor(sertraline,cytochrome_p450_2d6).
enzymeinhibitor(sertraline,cytochrome_p450_3a4).
enzymeinhibitor(sildenafil,cytochrome_p450_1a1).
enzymeinhibitor(sildenafil,cytochrome_p450_2c19).
enzymeinhibitor(sildenafil,cytochrome_p450_2c9).
enzymeinhibitor(sildenafil,cytochrome_p450_2d6).
enzymeinhibitor(sildenafil,cytochrome_p450_2e1).
enzymeinhibitor(sildenafil,cytochrome_p450_3a4).
enzymeinhibitor(simvastatin,cytochrome_p450_2c19).
enzymeinhibitor(simvastatin,cytochrome_p450_2c8).
enzymeinhibitor(simvastatin,cytochrome_p450_2c9).
enzymeinhibitor(simvastatin,cytochrome_p450_2d6).
enzymeinhibitor(simvastatin,cytochrome_p450_3a4).
enzymeinhibitor(tadalafil,cytochrome_p450_3a4).
enzymeinhibitor(tramadol,cytochrome_p450_2d6).
enzymeinhibitor(tramadol,cytochrome_p450_3a4).
enzymeinhibitor(venlafaxine,cytochrome_p450_2b6).
enzymeinhibitor(venlafaxine,cytochrome_p450_2d6).
enzymeinhibitor(venlafaxine,cytochrome_p450_3a4).
enzymeinhibitor(warfarin,cytochrome_p450_2c19).
enzymeinhibitor(warfarin,cytochrome_p450_2c8).
enzymeinhibitor(warfarin,cytochrome_p450_2c9).
enzymesubstrate(acetaminophen,bile_salt_sulfotransferase).
enzymesubstrate(acetaminophen,cytochrome_p450_1a1).
enzymesubstrate(acetaminophen,cytochrome_p450_1a2).
enzymesubstrate(acetaminophen,cytochrome_p450_2a6).
enzymesubstrate(acetaminophen,cytochrome_p450_2c8).
enzymesubstrate(acetaminophen,cytochrome_p450_2c9).
enzymesubstrate(acetaminophen,cytochrome_p450_2d6).
enzymesubstrate(acetaminophen,cytochrome_p450_2e1).
enzymesubstrate(acetaminophen,cytochrome_p450_3a4).
enzymesubstrate(acetaminophen,estrogen_sulfotransferase).
enzymesubstrate(acetaminophen,sulfotransferase_1a1).
enzymesubstrate(acetaminophen,sulfotransferase_1a3_1a4).
enzymesubstrate(acetaminophen,udp_glucuronosyltransferase_1_1).
enzymesubstrate(acetaminophen,udp_glucuronosyltransferase_1_10).
enzymesubstrate(acetaminophen,udp_glucuronosyltransferase_1_6).
enzymesubstrate(acetaminophen,udp_glucuronosyltransferase_1_9).
enzymesubstrate(acetaminophen,udp_glucuronosyltransferase_2b15).
enzymesubstrate(acetylsalicylic_acid,cytochrome_p450_2c8).
enzymesubstrate(acetylsalicylic_acid,cytochrome_p450_2c9).
enzymesubstrate(alprazolam,cytochrome_p450_2c9).
enzymesubstrate(alprazolam,cytochrome_p450_3a4).
enzymesubstrate(alprazolam,cytochrome_p450_3a5).
enzymesubstrate(alprazolam,cytochrome_p450_3a7).
enzymesubstrate(amitriptyline,cytochrome_p450_1a2).
enzymesubstrate(amitriptyline,cytochrome_p450_2b6).
enzymesubstrate(amitriptyline,cytochrome_p450_2c19).
enzymesubstrate(amitriptyline,cytochrome_p450_2c8).
enzymesubstrate(amitriptyline,cytochrome_p450_2c9).
enzymesubstrate(amitriptyline,cytochrome_p450_2d6).
enzymesubstrate(amitriptyline,cytochrome_p450_2e1).
enzymesubstrate(amitriptyline,cytochrome_p450_3a4).
enzymesubstrate(amitriptyline,cytochrome_p450_3a5).
enzymesubstrate(amlodipine,cytochrome_p450_3a4).
enzymesubstrate(amlodipine,cytochrome_p450_3a5).
enzymesubstrate(amlodipine,cytochrome_p450_3a7).
enzymesubstrate(amoxicillin,cytochrome_p450_2c19).
enzymesubstrate(amphetamine,cytochrome_p450_2d6).
enzymesubstrate(aripiprazole,cytochrome_p450_2d6).
enzymesubstrate(aripiprazole,cytochrome_p450_3a4).
enzymesubstrate(aripiprazole,cytochrome_p450_3a5).
enzymesubstrate(aripiprazole,cytochrome_p450_3a7).
enzymesubstrate(atorvastatin,cytochrome_p450_2c8).
enzymesubstrate(atorvastatin,cytochrome_p450_3a4).
enzymesubstrate(atorvastatin,cytochrome_p450_3a5).
enzymesubstrate(atorvastatin,cytochrome_p450_3a7).
enzymesubstrate(atorvastatin,udp_glucuronosyltransferase_1_1).
enzymesubstrate(atorvastatin,udp_glucuronosyltransferase_1_3).
enzymesubstrate(atorvastatin,udp_glucuronosyltransferase_2b7).
enzymesubstrate(azithromycin,cytochrome_p450_3a4).
enzymesubstrate(budesonide,cytochrome_p450_3a4).
enzymesubstrate(celecoxib,cytochrome_p450_2c9).
enzymesubstrate(celecoxib,cytochrome_p450_3a4).
enzymesubstrate(cephalexin,cytochrome_p450_2d6).
enzymesubstrate(cephalexin,cytochrome_p450_3a4).
enzymesubstrate(clindamycin,cytochrome_p450_3a4).
enzymesubstrate(clonazepam,arylamine_n_acetyltransferase_2).
enzymesubstrate(clonazepam,cytochrome_p450_3a4).
enzymesubstrate(clonidine,cytochrome_p450_1a1).
enzymesubstrate(clonidine,cytochrome_p450_1a2).
enzymesubstrate(clonidine,cytochrome_p450_2d6).
enzymesubstrate(clonidine,cytochrome_p450_3a4).
enzymesubstrate(clonidine,cytochrome_p450_3a5).
enzymesubstrate(cyclobenzaprine,cytochrome_p450_1a2).
enzymesubstrate(cyclobenzaprine,cytochrome_p450_2d6).
enzymesubstrate(cyclobenzaprine,cytochrome_p450_3a4).
enzymesubstrate(diazepam,cytochrome_p450_1a2).
enzymesubstrate(diazepam,cytochrome_p450_2b6).
enzymesubstrate(diazepam,cytochrome_p450_2c18).
enzymesubstrate(diazepam,cytochrome_p450_2c19).
enzymesubstrate(diazepam,cytochrome_p450_2c8).
enzymesubstrate(diazepam,cytochrome_p450_2c9).
enzymesubstrate(diazepam,cytochrome_p450_3a4).
enzymesubstrate(diazepam,cytochrome_p450_3a5).
enzymesubstrate(diazepam,cytochrome_p450_3a7).
enzymesubstrate(diazepam,prostaglandin_g_h_synthase_1).
enzymesubstrate(diclofenac,cytochrome_p450_1a1).
enzymesubstrate(diclofenac,cytochrome_p450_1a2).
enzymesubstrate(diclofenac,cytochrome_p450_2b6).
enzymesubstrate(diclofenac,cytochrome_p450_2c18).
enzymesubstrate(diclofenac,cytochrome_p450_2c19).
enzymesubstrate(diclofenac,cytochrome_p450_2c8).
enzymesubstrate(diclofenac,cytochrome_p450_2c9).
enzymesubstrate(diclofenac,cytochrome_p450_3a4).
enzymesubstrate(diclofenac,prostaglandin_g_h_synthase_1).
enzymesubstrate(diclofenac,udp_glucuronosyltransferase_1_1).
enzymesubstrate(diclofenac,udp_glucuronosyltransferase_2b7).
enzymesubstrate(diphenhydramine,cytochrome_p450_1a2).
enzymesubstrate(diphenhydramine,cytochrome_p450_2b6).
enzymesubstrate(diphenhydramine,cytochrome_p450_2c18).
enzymesubstrate(diphenhydramine,cytochrome_p450_2c19).
enzymesubstrate(diphenhydramine,cytochrome_p450_2c9).
enzymesubstrate(diphenhydramine,cytochrome_p450_2d6).
enzymesubstrate(diphenhydramine,prostaglandin_g_h_synthase_1).
enzymesubstrate(duloxetine,cytochrome_p450_1a2).
enzymesubstrate(duloxetine,cytochrome_p450_2d6).
enzymesubstrate(esomeprazole,cytochrome_p450_2c19).
enzymesubstrate(esomeprazole,cytochrome_p450_3a4).
enzymesubstrate(fenofibrate,cytochrome_p450_3a4).
enzymesubstrate(fluoxetine,cytochrome_p450_1a2).
enzymesubstrate(fluoxetine,cytochrome_p450_2b6).
enzymesubstrate(fluoxetine,cytochrome_p450_2c19).
enzymesubstrate(fluoxetine,cytochrome_p450_2c9).
enzymesubstrate(fluoxetine,cytochrome_p450_2d6).
enzymesubstrate(fluoxetine,cytochrome_p450_3a4).
enzymesubstrate(fluoxetine,cytochrome_p450_3a5).
enzymesubstrate(hydrocodone,cytochrome_p450_2d6).
enzymesubstrate(hydrocodone,cytochrome_p450_3a4).
enzymesubstrate(hydromorphone,cytochrome_p450_2c9).
enzymesubstrate(hydromorphone,cytochrome_p450_2d6).
enzymesubstrate(hydromorphone,cytochrome_p450_3a4).
enzymesubstrate(hydromorphone,prostaglandin_g_h_synthase_1).
enzymesubstrate(hydromorphone,udp_glucuronosyltransferase_1_9).
enzymesubstrate(ibuprofen,cytochrome_p450_2c19).
enzymesubstrate(ibuprofen,cytochrome_p450_2c8).
enzymesubstrate(ibuprofen,cytochrome_p450_2c9).
enzymesubstrate(ibuprofen,udp_glucuronosyltransferase_1_1).
enzymesubstrate(ibuprofen,udp_glucuronosyltransferase_1_3).
enzymesubstrate(ibuprofen,udp_glucuronosyltransferase_1_9).
enzymesubstrate(ibuprofen,udp_glucuronosyltransferase_2b4).
enzymesubstrate(ibuprofen,udp_glucuronosyltransferase_2b7).
enzymesubstrate(lamotrigine,udp_glucuronosyltransferase_1_3).
enzymesubstrate(lamotrigine,udp_glucuronosyltransferase_1_4).
enzymesubstrate(levothyroxine,cytochrome_p450_3a4).
enzymesubstrate(loratadine,cytochrome_p450_2c8).
enzymesubstrate(loratadine,cytochrome_p450_2c9).
enzymesubstrate(loratadine,cytochrome_p450_2d6).
enzymesubstrate(loratadine,cytochrome_p450_3a4).
enzymesubstrate(lorazepam,udp_glucuronosyltransferase_2b15).
enzymesubstrate(losartan,cytochrome_p450_2c8).
enzymesubstrate(losartan,cytochrome_p450_2c9).
enzymesubstrate(losartan,cytochrome_p450_3a4).
enzymesubstrate(losartan,cytochrome_p450_3a5).
enzymesubstrate(losartan,udp_glucuronosyltransferase_1_1).
enzymesubstrate(losartan,udp_glucuronosyltransferase_1_10).
enzymesubstrate(losartan,udp_glucuronosyltransferase_1_3).
enzymesubstrate(losartan,udp_glucuronosyltransferase_2b17).
enzymesubstrate(losartan,udp_glucuronosyltransferase_2b7).
enzymesubstrate(meloxicam,cytochrome_p450_2c8).
enzymesubstrate(meloxicam,cytochrome_p450_2c9).
enzymesubstrate(meloxicam,cytochrome_p450_3a4).
enzymesubstrate(methadone,cytochrome_p450_19a1).
enzymesubstrate(methadone,cytochrome_p450_1a2).
enzymesubstrate(methadone,cytochrome_p450_2b6).
enzymesubstrate(methadone,cytochrome_p450_2c18).
enzymesubstrate(methadone,cytochrome_p450_2c19).
enzymesubstrate(methadone,cytochrome_p450_2c8).
enzymesubstrate(methadone,cytochrome_p450_2c9).
enzymesubstrate(methadone,cytochrome_p450_2d6).
enzymesubstrate(methadone,cytochrome_p450_3a4).
enzymesubstrate(methadone,cytochrome_p450_3a5).
enzymesubstrate(methadone,cytochrome_p450_3a7).
enzymesubstrate(methylphenidate,carboxylesterase).
enzymesubstrate(methylphenidate,cytochrome_p450_2d6).
enzymesubstrate(metoprolol,cytochrome_p450_2c19).
enzymesubstrate(metoprolol,cytochrome_p450_2d6).
enzymesubstrate(metronidazole,cytochrome_p450_2c9).
enzymesubstrate(metronidazole,cytochrome_p450_3a4).
enzymesubstrate(morphine,cytochrome_p450_2c8).
enzymesubstrate(morphine,cytochrome_p450_2d6).
enzymesubstrate(morphine,cytochrome_p450_3a4).
enzymesubstrate(morphine,udp_glucuronosyltransferase_1_1).
enzymesubstrate(morphine,udp_glucuronosyltransferase_1_3).
enzymesubstrate(morphine,udp_glucuronosyltransferase_1_8).
enzymesubstrate(morphine,udp_glucuronosyltransferase_2b15).
enzymesubstrate(morphine,udp_glucuronosyltransferase_2b4).
enzymesubstrate(morphine,udp_glucuronosyltransferase_2b7).
enzymesubstrate(naloxone,cytochrome_p450_2c8).
enzymesubstrate(naloxone,cytochrome_p450_3a4).
enzymesubstrate(naproxen,cytochrome_p450_1a2).
enzymesubstrate(naproxen,cytochrome_p450_2c8).
enzymesubstrate(naproxen,cytochrome_p450_2c9).
enzymesubstrate(naproxen,udp_glucuronosyltransferase_1_1).
enzymesubstrate(naproxen,udp_glucuronosyltransferase_2b7).
enzymesubstrate(omeprazole,cytochrome_p450_1a2).
enzymesubstrate(omeprazole,cytochrome_p450_2c18).
enzymesubstrate(omeprazole,cytochrome_p450_2c19).
enzymesubstrate(omeprazole,cytochrome_p450_2c8).
enzymesubstrate(omeprazole,cytochrome_p450_2c9).
enzymesubstrate(omeprazole,cytochrome_p450_3a4).
enzymesubstrate(ondansetron,cytochrome_p450_1a2).
enzymesubstrate(ondansetron,cytochrome_p450_2c9).
enzymesubstrate(ondansetron,cytochrome_p450_2d6).
enzymesubstrate(ondansetron,cytochrome_p450_2e1).
enzymesubstrate(ondansetron,cytochrome_p450_3a4).
enzymesubstrate(ondansetron,cytochrome_p450_3a5).
enzymesubstrate(ondansetron,cytochrome_p450_3a7).
enzymesubstrate(oxycodone,cytochrome_p450_2d6).
enzymesubstrate(oxycodone,cytochrome_p450_3a4).
enzymesubstrate(oxycodone,cytochrome_p450_3a5).
enzymesubstrate(oxycodone,cytochrome_p450_3a7).
enzymesubstrate(pantoprazole,cytochrome_p450_1a2).
enzymesubstrate(pantoprazole,cytochrome_p450_2c19).
enzymesubstrate(pantoprazole,cytochrome_p450_3a4).
enzymesubstrate(paroxetine,cytochrome_p450_2d6).
enzymesubstrate(pravastatin,cytochrome_p450_2c9).
enzymesubstrate(pravastatin,cytochrome_p450_3a4).
enzymesubstrate(pravastatin,cytochrome_p450_3a5).
enzymesubstrate(prednisone,cytochrome_p450_3a4).
enzymesubstrate(propranolol,cytochrome_p450_1a2).
enzymesubstrate(propranolol,cytochrome_p450_2c19).
enzymesubstrate(propranolol,cytochrome_p450_2d6).
enzymesubstrate(propranolol,cytochrome_p450_3a4).
enzymesubstrate(propranolol,cytochrome_p450_3a5).
enzymesubstrate(propranolol,cytochrome_p450_3a7).
enzymesubstrate(quetiapine,cytochrome_p450_2c19).
enzymesubstrate(quetiapine,cytochrome_p450_2d6).
enzymesubstrate(quetiapine,cytochrome_p450_3a4).
enzymesubstrate(quetiapine,cytochrome_p450_3a5).
enzymesubstrate(quetiapine,cytochrome_p450_3a7).
enzymesubstrate(risperidone,cytochrome_p450_2d6).
enzymesubstrate(risperidone,cytochrome_p450_3a4).
enzymesubstrate(risperidone,cytochrome_p450_3a5).
enzymesubstrate(risperidone,cytochrome_p450_3a7).
enzymesubstrate(rivaroxaban,cytochrome_p450_2j2).
enzymesubstrate(rivaroxaban,cytochrome_p450_3a4).
enzymesubstrate(rivaroxaban,cytochrome_p450_3a5).
enzymesubstrate(salmeterol,cytochrome_p450_3a4).
enzymesubstrate(salmeterol,cytochrome_p450_3a5).
enzymesubstrate(salmeterol,cytochrome_p450_3a7).
enzymesubstrate(sertraline,amine_oxidase__flavin_containing__a).
enzymesubstrate(sertraline,amine_oxidase__flavin_containing__b).
enzymesubstrate(sertraline,cytochrome_p450_1a2).
enzymesubstrate(sertraline,cytochrome_p450_2b6).
enzymesubstrate(sertraline,cytochrome_p450_2c19).
enzymesubstrate(sertraline,cytochrome_p450_2c9).
enzymesubstrate(sertraline,cytochrome_p450_2d6).
enzymesubstrate(sertraline,cytochrome_p450_3a4).
enzymesubstrate(sildenafil,cytochrome_p450_2c19).
enzymesubstrate(sildenafil,cytochrome_p450_2c9).
enzymesubstrate(sildenafil,cytochrome_p450_2d6).
enzymesubstrate(sildenafil,cytochrome_p450_2e1).
enzymesubstrate(sildenafil,cytochrome_p450_3a4).
enzymesubstrate(sildenafil,cytochrome_p450_3a5).
enzymesubstrate(sildenafil,cytochrome_p450_3a7).
enzymesubstrate(simvastatin,cytochrome_p450_2c8).
enzymesubstrate(simvastatin,cytochrome_p450_2d6).
enzymesubstrate(simvastatin,cytochrome_p450_3a4).
enzymesubstrate(simvastatin,cytochrome_p450_3a5).
enzymesubstrate(simvastatin,cytochrome_p450_3a7).
enzymesubstrate(simvastatin,udp_glucuronosyltransferase_1_1).
enzymesubstrate(simvastatin,udp_glucuronosyltransferase_1_3).
enzymesubstrate(simvastatin,udp_glucuronosyltransferase_2b7).
enzymesubstrate(sitagliptin,cytochrome_p450_2c8).
enzymesubstrate(sitagliptin,cytochrome_p450_3a4).
enzymesubstrate(tadalafil,cytochrome_p450_3a4).
enzymesubstrate(tamsulosin,cytochrome_p450_2d6).
enzymesubstrate(tamsulosin,cytochrome_p450_3a4).
enzymesubstrate(tramadol,cytochrome_p450_2b6).
enzymesubstrate(tramadol,cytochrome_p450_2d6).
enzymesubstrate(tramadol,cytochrome_p450_3a4).
enzymesubstrate(trazodone,cytochrome_p450_2d6).
enzymesubstrate(trazodone,cytochrome_p450_3a4).
enzymesubstrate(trazodone,cytochrome_p450_3a5).
enzymesubstrate(trazodone,cytochrome_p450_3a7).
enzymesubstrate(venlafaxine,cytochrome_p450_2c19).
enzymesubstrate(venlafaxine,cytochrome_p450_2c9).
enzymesubstrate(venlafaxine,cytochrome_p450_2d6).
enzymesubstrate(venlafaxine,cytochrome_p450_3a4).
enzymesubstrate(warfarin,cytochrome_p450_1a1).
enzymesubstrate(warfarin,cytochrome_p450_1a2).
enzymesubstrate(warfarin,cytochrome_p450_2c18).
enzymesubstrate(warfarin,cytochrome_p450_2c19).
enzymesubstrate(warfarin,cytochrome_p450_2c8).
enzymesubstrate(warfarin,cytochrome_p450_2c9).
enzymesubstrate(warfarin,cytochrome_p450_3a4).
enzymesubstrate(zolpidem,cytochrome_p450_1a2).
enzymesubstrate(zolpidem,cytochrome_p450_2c19).
enzymesubstrate(zolpidem,cytochrome_p450_2c9).
enzymesubstrate(zolpidem,cytochrome_p450_2d6).
enzymesubstrate(zolpidem,cytochrome_p450_3a4).
enzymesubstrate(zolpidem,cytochrome_p450_3a5).
enzymesubstrate(zolpidem,cytochrome_p450_3a7).
enzymesubstrate(zolpidem,prostaglandin_g_h_synthase_1).
target(acid_sensing_ion_channel_1,diclofenac).
target(adenosine_receptor_a1,gabapentin).
target(adenosine_receptor_a1,lamotrigine).
target(adenosine_receptor_a2a,lamotrigine).
target(aldo_keto_reductase_family_1_member_c1,acetylsalicylic_acid).
target(alpha1_acid_glycoprotein,oxycodone).
target(alpha_1_acid_glycoprotein_2,methadone).
target(alpha_1a_adrenergic_receptor,amitriptyline).
target(alpha_1a_adrenergic_receptor,aripiprazole).
target(alpha_1a_adrenergic_receptor,clonidine).
target(alpha_1a_adrenergic_receptor,lamotrigine).
target(alpha_1a_adrenergic_receptor,oxymetazoline).
target(alpha_1a_adrenergic_receptor,quetiapine).
target(alpha_1a_adrenergic_receptor,risperidone).
target(alpha_1a_adrenergic_receptor,tamsulosin).
target(alpha_1a_adrenergic_receptor,trazodone).
target(alpha_1b_adrenergic_receptor,amitriptyline).
target(alpha_1b_adrenergic_receptor,aripiprazole).
target(alpha_1b_adrenergic_receptor,clonidine).
target(alpha_1b_adrenergic_receptor,lisdexamfetamine).
target(alpha_1b_adrenergic_receptor,oxymetazoline).
target(alpha_1b_adrenergic_receptor,quetiapine).
target(alpha_1b_adrenergic_receptor,risperidone).
target(alpha_1b_adrenergic_receptor,tamsulosin).
target(alpha_1d_adrenergic_receptor,amitriptyline).
target(alpha_1d_adrenergic_receptor,clonidine).
target(alpha_1d_adrenergic_receptor,oxymetazoline).
target(alpha_1d_adrenergic_receptor,quetiapine).
target(alpha_1d_adrenergic_receptor,tamsulosin).
target(alpha_2a_adrenergic_receptor,amitriptyline).
target(alpha_2a_adrenergic_receptor,aripiprazole).
target(alpha_2a_adrenergic_receptor,clonidine).
target(alpha_2a_adrenergic_receptor,lamotrigine).
target(alpha_2a_adrenergic_receptor,oxymetazoline).
target(alpha_2a_adrenergic_receptor,quetiapine).
target(alpha_2a_adrenergic_receptor,risperidone).
target(alpha_2a_adrenergic_receptor,trazodone).
target(alpha_2b_adrenergic_receptor,aripiprazole).
target(alpha_2b_adrenergic_receptor,clonidine).
target(alpha_2b_adrenergic_receptor,oxymetazoline).
target(alpha_2b_adrenergic_receptor,quetiapine).
target(alpha_2b_adrenergic_receptor,risperidone).
target(alpha_2c_adrenergic_receptor,aripiprazole).
target(alpha_2c_adrenergic_receptor,clonidine).
target(alpha_2c_adrenergic_receptor,oxymetazoline).
target(alpha_2c_adrenergic_receptor,quetiapine).
target(alpha_2c_adrenergic_receptor,risperidone).
target(alpha_7_nicotinic_cholinergic_receptor_subunit,tramadol).
target(alpha_adrenergic_receptor,amphetamine).
target(amine_oxidase__flavin_containing__a,phentermine).
target(amine_oxidase__flavin_containing__b,amphetamine).
target(amine_oxidase__flavin_containing__b,phentermine).
target(angiotensin_converting_enzyme,lisinopril).
target(apoptosis_regulator_bcl_2,ibuprofen).
target(arachidonate_5_lipoxygenase,diclofenac).
target(aryl_hydrocarbon_receptor,atorvastatin).
target(aryl_hydrocarbon_receptor,omeprazole).
target(bdnf_nt_3_growth_factors_receptor,amitriptyline).
target(beta_1_adrenergic_receptor,lamotrigine).
target(beta_1_adrenergic_receptor,metoprolol).
target(beta_1_adrenergic_receptor,propranolol).
target(beta_1_adrenergic_receptor,salbutamol).
target(beta_1_adrenergic_receptor,salmeterol).
target(beta_2_adrenergic_receptor,metoprolol).
target(beta_2_adrenergic_receptor,propranolol).
target(beta_2_adrenergic_receptor,salbutamol).
target(beta_2_adrenergic_receptor,salmeterol).
target(beta_2_microglobulin,doxycycline).
target(beta_3_adrenergic_receptor,propranolol).
target(beta_3_adrenergic_receptor,salbutamol).
target(beta_3_adrenergic_receptor,salmeterol).
target(beta_adrenergic_receptor,amitriptyline).
target(beta_adrenergic_receptor,amphetamine).
target(beta_lactamase,clavulanate).
target(c16s_rrna,doxycycline).
target(c23s_rrna,azithromycin).
target(c23s_rrna,clindamycin).
target(c30s_ribosomal_protein_s4,doxycycline).
target(c30s_ribosomal_protein_s9,doxycycline).
target(c3_hydroxy_3_methylglutaryl_coenzyme_a_reductase,atorvastatin).
target(c3_hydroxy_3_methylglutaryl_coenzyme_a_reductase,pravastatin).
target(c3_hydroxy_3_methylglutaryl_coenzyme_a_reductase,simvastatin).
target(c3_phosphoinositide_dependent_protein_kinase_1,celecoxib).
target(c50s_ribosomal_protein_l10,clindamycin).
target(c50s_ribosomal_protein_l22,azithromycin).
target(c50s_ribosomal_protein_l4,azithromycin).
target(c5_amp_activated_protein_kinase,acetylsalicylic_acid).
target(c5_amp_activated_protein_kinase_subunit_beta_1,metformin).
target(c5_cyclic_amp_and__gmp_phosphodiesterase_11a,tadalafil).
target(c5_cyclic_phosphodiesterase,sildenafil).
target(c5_cyclic_phosphodiesterase,tadalafil).
target(c5_cyclic_phosphodiesterase_subunit_gamma,sildenafil).
target(c5_cyclic_phosphodiesterase_subunit_gamma,sildenafil).
target(c5_hydroxytryptamine_receptor_1a,amitriptyline).
target(c5_hydroxytryptamine_receptor_1a,aripiprazole).
target(c5_hydroxytryptamine_receptor_1a,ondansetron).
target(c5_hydroxytryptamine_receptor_1a,propranolol).
target(c5_hydroxytryptamine_receptor_1a,quetiapine).
target(c5_hydroxytryptamine_receptor_1a,risperidone).
target(c5_hydroxytryptamine_receptor_1a,trazodone).
target(c5_hydroxytryptamine_receptor_1b,amitriptyline).
target(c5_hydroxytryptamine_receptor_1b,aripiprazole).
target(c5_hydroxytryptamine_receptor_1b,ondansetron).
target(c5_hydroxytryptamine_receptor_1b,propranolol).
target(c5_hydroxytryptamine_receptor_1b,quetiapine).
target(c5_hydroxytryptamine_receptor_1d,amitriptyline).
target(c5_hydroxytryptamine_receptor_1d,aripiprazole).
target(c5_hydroxytryptamine_receptor_1d,quetiapine).
target(c5_hydroxytryptamine_receptor_1d,risperidone).
target(c5_hydroxytryptamine_receptor_1e,aripiprazole).
target(c5_hydroxytryptamine_receptor_1e,quetiapine).
target(c5_hydroxytryptamine_receptor_2a,amitriptyline).
target(c5_hydroxytryptamine_receptor_2a,aripiprazole).
target(c5_hydroxytryptamine_receptor_2a,cyclobenzaprine).
target(c5_hydroxytryptamine_receptor_2a,lamotrigine).
target(c5_hydroxytryptamine_receptor_2a,paroxetine).
target(c5_hydroxytryptamine_receptor_2a,quetiapine).
target(c5_hydroxytryptamine_receptor_2a,risperidone).
target(c5_hydroxytryptamine_receptor_2a,trazodone).
target(c5_hydroxytryptamine_receptor_2c,amitriptyline).
target(c5_hydroxytryptamine_receptor_2c,aripiprazole).
target(c5_hydroxytryptamine_receptor_2c,fluoxetine).
target(c5_hydroxytryptamine_receptor_2c,quetiapine).
target(c5_hydroxytryptamine_receptor_2c,risperidone).
target(c5_hydroxytryptamine_receptor_2c,tramadol).
target(c5_hydroxytryptamine_receptor_2c,trazodone).
target(c5_hydroxytryptamine_receptor_3a,aripiprazole).
target(c5_hydroxytryptamine_receptor_3a,lamotrigine).
target(c5_hydroxytryptamine_receptor_3a,methadone).
target(c5_hydroxytryptamine_receptor_3a,ondansetron).
target(c5_hydroxytryptamine_receptor_3a,quetiapine).
target(c5_hydroxytryptamine_receptor_4,ondansetron).
target(c5_hydroxytryptamine_receptor_6,amitriptyline).
target(c5_hydroxytryptamine_receptor_6,aripiprazole).
target(c5_hydroxytryptamine_receptor_6,quetiapine).
target(c5_hydroxytryptamine_receptor_7,amitriptyline).
target(c5_hydroxytryptamine_receptor_7,aripiprazole).
target(c5_hydroxytryptamine_receptor_7,quetiapine).
target(c5_hydroxytryptamine_receptor_7,risperidone).
target(c78_kda_glucose_regulated_protein,acetylsalicylic_acid).
target(c_intestinal,ibuprofen).
target(c_membrane_associated,diclofenac).
target(c_nmda_3a,methadone).
target(c_nmda_3a,tramadol).
target(carbonic_anhydrase_1,amlodipine).
target(carbonic_anhydrase_2,celecoxib).
target(carbonic_anhydrase_3,celecoxib).
target(cellular_tumor_antigen_p53,acetylsalicylic_acid).
target(cgmp_specific_3,sildenafil).
target(cgmp_specific_3,tadalafil).
target(coagulation_factor_x,rivaroxaban).
target(cocaine__and_amphetamine_regulated_transcript_protein,amphetamine).
target(corticosteroid_11_beta_dehydrogenase_isozyme_1,prednisone).
target(cyclic_amp_responsive_element_binding_protein_1,naloxone).
target(cyclin_dependent_kinases_regulatory_subunit_1,fluoxetine).
target(cystic_fibrosis_transmembrane_conductance_regulator,ibuprofen).
target(d1_dopamine_receptor,lamotrigine).
target(d1a_dopamine_receptor,aripiprazole).
target(d1a_dopamine_receptor,quetiapine).
target(d1a_dopamine_receptor,risperidone).
target(d1b_dopamine_receptor,aripiprazole).
target(d1b_dopamine_receptor,quetiapine).
target(d2_dopamine_receptor,amphetamine).
target(d2_dopamine_receptor,aripiprazole).
target(d2_dopamine_receptor,lamotrigine).
target(d2_dopamine_receptor,quetiapine).
target(d2_dopamine_receptor,risperidone).
target(d3_dopamine_receptor,aripiprazole).
target(d3_dopamine_receptor,quetiapine).
target(d3_dopamine_receptor,risperidone).
target(d4_dopamine_receptor,aripiprazole).
target(d4_dopamine_receptor,quetiapine).
target(d4_dopamine_receptor,risperidone).
target(delta_type_opioid_receptor,amitriptyline).
target(delta_type_opioid_receptor,hydrocodone).
target(delta_type_opioid_receptor,hydromorphone).
target(delta_type_opioid_receptor,methadone).
target(delta_type_opioid_receptor,morphine).
target(delta_type_opioid_receptor,naloxone).
target(delta_type_opioid_receptor,oxycodone).
target(delta_type_opioid_receptor,tramadol).
target(dipeptidyl_peptidase_4,atorvastatin).
target(dipeptidyl_peptidase_4,sitagliptin).
target(dna,metronidazole).
target(dna_gyrase_subunit_a,ciprofloxacin).
target(dna_gyrase_subunit_a,ciprofloxacin).
target(dna_gyrase_subunit_a,ciprofloxacin).
target(dna_gyrase_subunit_a,ciprofloxacin).
target(dna_topoisomerase_2_alpha,ciprofloxacin).
target(dna_topoisomerase_4_subunit_a,ciprofloxacin).
target(dna_topoisomerase_4_subunit_a,ciprofloxacin).
target(dna_topoisomerase_4_subunit_b,ciprofloxacin).
target(dual_3,tadalafil).
target(endothelin_1_receptor,acetylsalicylic_acid).
target(estrogen_receptor_alpha,naloxone).
target(fatty_acid_amide_hydrolase_1,acetaminophen).
target(fatty_acid_binding_protein,ibuprofen).
target(gaba_a_receptor_anion_channel,alprazolam).
target(gaba_a_receptor_anion_channel,clonazepam).
target(gaba_a_receptor_anion_channel,diazepam).
target(gaba_a_receptor_anion_channel,lamotrigine).
target(gaba_a_receptor_anion_channel,lorazepam).
target(gaba_a_receptor_benzodiazepine_site,lamotrigine).
target(gamma_aminobutyric_acid_receptor_subunit_alpha_1,diazepam).
target(gamma_aminobutyric_acid_receptor_subunit_alpha_1,zolpidem).
target(gamma_aminobutyric_acid_receptor_subunit_alpha_2,diazepam).
target(gamma_aminobutyric_acid_receptor_subunit_alpha_2,zolpidem).
target(gamma_aminobutyric_acid_receptor_subunit_alpha_3,diazepam).
target(gamma_aminobutyric_acid_receptor_subunit_alpha_3,zolpidem).
target(gamma_aminobutyric_acid_receptor_subunit_alpha_5,diazepam).
target(gamma_aminobutyric_acid_receptor_subunit_beta_1,diazepam).
target(gamma_aminobutyric_acid_receptor_subunit_beta_2,diazepam).
target(gamma_aminobutyric_acid_receptor_subunit_beta_3,diazepam).
target(gamma_aminobutyric_acid_receptor_subunit_beta_3,zolpidem).
target(gamma_aminobutyric_acid_receptor_subunit_delta,diazepam).
target(gamma_aminobutyric_acid_receptor_subunit_epsilon,diazepam).
target(gamma_aminobutyric_acid_receptor_subunit_gamma_1,diazepam).
target(gamma_aminobutyric_acid_receptor_subunit_gamma_2,diazepam).
target(gamma_aminobutyric_acid_receptor_subunit_gamma_2,zolpidem).
target(gamma_aminobutyric_acid_receptor_subunit_gamma_3,diazepam).
target(gamma_aminobutyric_acid_receptor_subunit_pi,diazepam).
target(gamma_aminobutyric_acid_receptor_subunit_rho_1,diazepam).
target(gamma_aminobutyric_acid_receptor_subunit_rho_2,diazepam).
target(gamma_aminobutyric_acid_receptor_subunit_rho_3,diazepam).
target(gamma_aminobutyric_acid_receptor_subunit_theta,diazepam).
target(gamma_aminobutyric_acid_type_b_receptor_subunit_1,baclofen).
target(gamma_aminobutyric_acid_type_b_receptor_subunit_1,gabapentin).
target(gamma_aminobutyric_acid_type_b_receptor_subunit_2,baclofen).
target(gamma_aminobutyric_acid_type_b_receptor_subunit_2,gabapentin).
target(glucocorticoid_receptor,budesonide).
target(glucocorticoid_receptor,prednisone).
target(glutamate_receptor_ionotropic,methadone).
target(glutamate_receptor_ionotropic,tramadol).
target(glutathione_s_transferase_p,acetaminophen).
target(gyrase_a,ciprofloxacin).
target(high_affinity_nerve_growth_factor_receptor,amitriptyline).
target(histamine_h1_receptor,amitriptyline).
target(histamine_h1_receptor,aripiprazole).
target(histamine_h1_receptor,cetirizine).
target(histamine_h1_receptor,diphenhydramine).
target(histamine_h1_receptor,hydroxyzine).
target(histamine_h1_receptor,lamotrigine).
target(histamine_h1_receptor,loratadine).
target(histamine_h1_receptor,quetiapine).
target(histamine_h1_receptor,risperidone).
target(histamine_h1_receptor,trazodone).
target(histamine_h2_receptor,amitriptyline).
target(histamine_h4_receptor,amitriptyline).
target(inhibitor_of_nuclear_factor_kappa_b_kinase_subunit_beta,acetylsalicylic_acid).
target(integrin_alpha_l,simvastatin).
target(integrin_beta_2,simvastatin).
target(iron_hydrogenase_1,metronidazole).
target(kappa_type_opioid_receptor,amitriptyline).
target(kappa_type_opioid_receptor,hydromorphone).
target(kappa_type_opioid_receptor,lamotrigine).
target(kappa_type_opioid_receptor,morphine).
target(kappa_type_opioid_receptor,naloxone).
target(kappa_type_opioid_receptor,oxycodone).
target(kappa_type_opioid_receptor,tramadol).
target(kappa_type_opioid_receptor_2b,oxycodone).
target(lanosterol_14_alpha_demethylase,metronidazole).
target(liver_carboxylesterase_1,naloxone).
target(lymphocyte_antigen_96,methadone).
target(lymphocyte_antigen_96,morphine).
target(metalloproteinase,fenofibrate).
target(monoamine_oxidase,amphetamine).
target(mu_type_opioid_receptor,amitriptyline).
target(mu_type_opioid_receptor,hydrocodone).
target(mu_type_opioid_receptor,hydromorphone).
target(mu_type_opioid_receptor,methadone).
target(mu_type_opioid_receptor,morphine).
target(mu_type_opioid_receptor,naloxone).
target(mu_type_opioid_receptor,ondansetron).
target(mu_type_opioid_receptor,oxycodone).
target(mu_type_opioid_receptor,tramadol).
target(multidrug_resistance_protein_mdtk,ciprofloxacin).
target(muscarinic_acetylcholine_receptor,lamotrigine).
target(muscarinic_acetylcholine_receptor_m1,amitriptyline).
target(muscarinic_acetylcholine_receptor_m1,aripiprazole).
target(muscarinic_acetylcholine_receptor_m1,paroxetine).
target(muscarinic_acetylcholine_receptor_m1,quetiapine).
target(muscarinic_acetylcholine_receptor_m2,amitriptyline).
target(muscarinic_acetylcholine_receptor_m2,aripiprazole).
target(muscarinic_acetylcholine_receptor_m2,diphenhydramine).
target(muscarinic_acetylcholine_receptor_m2,paroxetine).
target(muscarinic_acetylcholine_receptor_m2,quetiapine).
target(muscarinic_acetylcholine_receptor_m3,amitriptyline).
target(muscarinic_acetylcholine_receptor_m3,aripiprazole).
target(muscarinic_acetylcholine_receptor_m3,paroxetine).
target(muscarinic_acetylcholine_receptor_m3,quetiapine).
target(muscarinic_acetylcholine_receptor_m3,tramadol).
target(muscarinic_acetylcholine_receptor_m4,amitriptyline).
target(muscarinic_acetylcholine_receptor_m4,aripiprazole).
target(muscarinic_acetylcholine_receptor_m4,paroxetine).
target(muscarinic_acetylcholine_receptor_m4,quetiapine).
target(muscarinic_acetylcholine_receptor_m5,amitriptyline).
target(muscarinic_acetylcholine_receptor_m5,aripiprazole).
target(muscarinic_acetylcholine_receptor_m5,paroxetine).
target(muscarinic_acetylcholine_receptor_m5,quetiapine).
target(neuronal_acetylcholine_receptor_subunit_alpha_10,methadone).
target(nf_kappa_b_inhibitor_alpha,acetylsalicylic_acid).
target(nmda_receptor,gabapentin).
target(nuclear_factor_nf_kappa_b,acetylsalicylic_acid).
target(nuclear_receptor_subfamily_1_group_i_member_2,clonazepam).
target(nuclear_receptor_subfamily_1_group_i_member_2,fenofibrate).
target(nuclear_receptor_subfamily_1_group_i_member_2,warfarin).
target(oxygen_insensitive_nadph_nitroreductase,metronidazole).
target(penicillin_binding_protein_1a,amdinocillin).
target(penicillin_binding_protein_1a,amoxicillin).
target(penicillin_binding_protein_1a,cephalexin).
target(penicillin_binding_protein_1b,amdinocillin).
target(penicillin_binding_protein_1b,cephalexin).
target(penicillin_binding_protein_2,amdinocillin).
target(penicillin_binding_protein_2a,amdinocillin).
target(penicillin_binding_protein_2a,cephalexin).
target(penicillin_binding_protein_2b,amdinocillin).
target(penicillin_binding_protein_2b,cephalexin).
target(penicillin_binding_protein_3,amdinocillin).
target(penicillin_binding_protein_3,cephalexin).
target(peptostreptococcal_albumin_binding_protein,naproxen).
target(peroxisome_proliferator_activated_receptor_alpha,fenofibrate).
target(peroxisome_proliferator_activated_receptor_alpha,ibuprofen).
target(peroxisome_proliferator_activated_receptor_delta,fenofibrate).
target(peroxisome_proliferator_activated_receptor_gamma,fenofibrate).
target(peroxisome_proliferator_activated_receptor_gamma,ibuprofen).
target(phospholipase_a2,diclofenac).
target(potassium_transporting_atpase_alpha_chain_1,esomeprazole).
target(potassium_transporting_atpase_alpha_chain_1,omeprazole).
target(potassium_transporting_atpase_alpha_chain_1,pantoprazole).
target(potassium_voltage_gated_channel_subfamily_a_member_1,amitriptyline).
target(potassium_voltage_gated_channel_subfamily_d_member_2,amitriptyline).
target(potassium_voltage_gated_channel_subfamily_d_member_3,amitriptyline).
target(potassium_voltage_gated_channel_subfamily_h_member_2,ciprofloxacin).
target(potassium_voltage_gated_channel_subfamily_h_member_2,fluoxetine).
target(potassium_voltage_gated_channel_subfamily_h_member_2,loratadine).
target(potassium_voltage_gated_channel_subfamily_kqt_member_2,amitriptyline).
target(potassium_voltage_gated_channel_subfamily_kqt_member_2,diclofenac).
target(potassium_voltage_gated_channel_subfamily_kqt_member_3,amitriptyline).
target(potassium_voltage_gated_channel_subfamily_kqt_member_3,diclofenac).
target(prostaglandin_g_h_synthase_1,acetaminophen).
target(prostaglandin_g_h_synthase_1,acetylsalicylic_acid).
target(prostaglandin_g_h_synthase_1,diclofenac).
target(prostaglandin_g_h_synthase_1,ibuprofen).
target(prostaglandin_g_h_synthase_1,meloxicam).
target(prostaglandin_g_h_synthase_1,naproxen).
target(prostaglandin_g_h_synthase_2,acetaminophen).
target(prostaglandin_g_h_synthase_2,acetylsalicylic_acid).
target(prostaglandin_g_h_synthase_2,celecoxib).
target(prostaglandin_g_h_synthase_2,diclofenac).
target(prostaglandin_g_h_synthase_2,ibuprofen).
target(prostaglandin_g_h_synthase_2,meloxicam).
target(prostaglandin_g_h_synthase_2,naproxen).
target(prostaglandin_g_h_synthase_3,acetaminophen).
target(protein_arginine_deiminase_type_4,azithromycin).
target(protein_arginine_deiminase_type_4,doxycycline).
target(retinal_cone_rhodopsin_sensitive_cgmp_3,sildenafil).
target(retinal_rod_rhodopsin_sensitive_cgmp_3,sildenafil).
target(ribosomal_protein_s6_kinase_alpha_3,acetylsalicylic_acid).
target(sigma_non_opioid_intracellular_receptor_1,amitriptyline).
target(sigma_receptor,sertraline).
target(sodium_channel_protein_type_2_subunit_alpha,lamotrigine).
target(sodium_channel_protein_type_4_subunit_alpha,diclofenac).
target(sodium_dependent_dopamine_transporter,amphetamine).
target(sodium_dependent_dopamine_transporter,duloxetine).
target(sodium_dependent_dopamine_transporter,lisdexamfetamine).
target(sodium_dependent_dopamine_transporter,methylphenidate).
target(sodium_dependent_dopamine_transporter,phentermine).
target(sodium_dependent_dopamine_transporter,sertraline).
target(sodium_dependent_dopamine_transporter,venlafaxine).
target(sodium_dependent_noradrenaline_transporter,amitriptyline).
target(sodium_dependent_noradrenaline_transporter,amphetamine).
target(sodium_dependent_noradrenaline_transporter,duloxetine).
target(sodium_dependent_noradrenaline_transporter,methylphenidate).
target(sodium_dependent_noradrenaline_transporter,paroxetine).
target(sodium_dependent_noradrenaline_transporter,phentermine).
target(sodium_dependent_noradrenaline_transporter,tramadol).
target(sodium_dependent_noradrenaline_transporter,venlafaxine).
target(sodium_dependent_serotonin_transporter,amitriptyline).
target(sodium_dependent_serotonin_transporter,amphetamine).
target(sodium_dependent_serotonin_transporter,duloxetine).
target(sodium_dependent_serotonin_transporter,fluoxetine).
target(sodium_dependent_serotonin_transporter,methylphenidate).
target(sodium_dependent_serotonin_transporter,paroxetine).
target(sodium_dependent_serotonin_transporter,phentermine).
target(sodium_dependent_serotonin_transporter,sertraline).
target(sodium_dependent_serotonin_transporter,tramadol).
target(sodium_dependent_serotonin_transporter,trazodone).
target(sodium_dependent_serotonin_transporter,venlafaxine).
target(solute_carrier_family_15_member_1,ibuprofen).
target(sphingomyelin_phosphodiesterase,amlodipine).
target(synaptic_vesicular_amine_transporter,amphetamine).
target(thrombomodulin,ibuprofen).
target(thyroid_hormone_receptor_alpha,levothyroxine).
target(thyroid_hormone_receptor_beta,levothyroxine).
target(tissue_type_plasminogen_activator,ibuprofen).
target(toll_like_receptor_4,naloxone).
target(trace_amine_associated_receptor_1,amphetamine).
target(transient_receptor_potential_cation_channel_subfamily_v_member_1,acetaminophen).
target(translocator_protein,clonazepam).
target(translocator_protein,diazepam).
target(translocator_protein,lorazepam).
target(type_1_angiotensin_ii_receptor,losartan).
target(vesicular_monoamine_transporter_2_vmat2,amphetamine).
target(vitamin_k_epoxide_reductase_complex_subunit_1,warfarin).
target(voltage_dependent_calcium_channel_subunit_alpha_2_delta_1,amlodipine).
target(voltage_dependent_calcium_channel_subunit_alpha_2_delta_1,gabapentin).
target(voltage_dependent_calcium_channel_subunit_alpha_2_delta_2,gabapentin).
target(voltage_dependent_calcium_channel_subunit_alpha_2_delta_3,amlodipine).
target(voltage_dependent_l_type_calcium_channel_subunit_alpha_1c,amlodipine).
target(voltage_dependent_l_type_calcium_channel_subunit_alpha_1d,amlodipine).
target(voltage_dependent_l_type_calcium_channel_subunit_alpha_1s,amlodipine).
target(voltage_dependent_l_type_calcium_channel_subunit_beta_2,amlodipine).
target(voltage_dependent_n_type_calcium_channel_subunit_alpha_1b,amlodipine).
target(voltage_dependent_n_type_calcium_channel_subunit_alpha_1b,gabapentin).
target(voltage_dependent_p_q_type_calcium_channel_subunit_alpha_1a,pregabalin).
target(voltage_dependent_r_type_calcium_channel_subunit_alpha_1e,lamotrigine).
target(voltage_gated_calcium_channel_beta_1_subunit_splice_variant_cavb1d,amlodipine).
targetagonist(amitriptyline,bdnf_nt_3_growth_factors_receptor).
targetagonist(amitriptyline,delta_type_opioid_receptor).
targetagonist(amitriptyline,high_affinity_nerve_growth_factor_receptor).
targetagonist(amitriptyline,kappa_type_opioid_receptor).
targetagonist(amitriptyline,sigma_non_opioid_intracellular_receptor_1).
targetagonist(amphetamine,alpha_adrenergic_receptor).
targetagonist(amphetamine,beta_adrenergic_receptor).
targetagonist(amphetamine,cocaine__and_amphetamine_regulated_transcript_protein).
targetagonist(amphetamine,trace_amine_associated_receptor_1).
targetagonist(atorvastatin,aryl_hydrocarbon_receptor).
targetagonist(baclofen,gamma_aminobutyric_acid_type_b_receptor_subunit_1).
targetagonist(baclofen,gamma_aminobutyric_acid_type_b_receptor_subunit_2).
targetagonist(clonidine,alpha_1a_adrenergic_receptor).
targetagonist(clonidine,alpha_1b_adrenergic_receptor).
targetagonist(clonidine,alpha_1d_adrenergic_receptor).
targetagonist(clonidine,alpha_2a_adrenergic_receptor).
targetagonist(clonidine,alpha_2b_adrenergic_receptor).
targetagonist(clonidine,alpha_2c_adrenergic_receptor).
targetagonist(fenofibrate,peroxisome_proliferator_activated_receptor_alpha).
targetagonist(gabapentin,adenosine_receptor_a1).
targetagonist(hydrocodone,delta_type_opioid_receptor).
targetagonist(hydrocodone,mu_type_opioid_receptor).
targetagonist(hydromorphone,kappa_type_opioid_receptor).
targetagonist(hydromorphone,mu_type_opioid_receptor).
targetagonist(levothyroxine,thyroid_hormone_receptor_alpha).
targetagonist(levothyroxine,thyroid_hormone_receptor_beta).
targetagonist(methadone,delta_type_opioid_receptor).
targetagonist(methadone,mu_type_opioid_receptor).
targetagonist(morphine,delta_type_opioid_receptor).
targetagonist(morphine,kappa_type_opioid_receptor).
targetagonist(morphine,mu_type_opioid_receptor).
targetagonist(omeprazole,aryl_hydrocarbon_receptor).
targetagonist(ondansetron,c5_hydroxytryptamine_receptor_4).
targetagonist(oxycodone,delta_type_opioid_receptor).
targetagonist(oxycodone,kappa_type_opioid_receptor).
targetagonist(oxycodone,kappa_type_opioid_receptor_2b).
targetagonist(oxycodone,mu_type_opioid_receptor).
targetagonist(oxymetazoline,alpha_1a_adrenergic_receptor).
targetagonist(oxymetazoline,alpha_1b_adrenergic_receptor).
targetagonist(oxymetazoline,alpha_1d_adrenergic_receptor).
targetagonist(oxymetazoline,alpha_2a_adrenergic_receptor).
targetagonist(oxymetazoline,alpha_2c_adrenergic_receptor).
targetagonist(prednisone,glucocorticoid_receptor).
targetagonist(risperidone,alpha_2c_adrenergic_receptor).
targetagonist(salbutamol,beta_1_adrenergic_receptor).
targetagonist(salbutamol,beta_2_adrenergic_receptor).
targetagonist(salmeterol,beta_1_adrenergic_receptor).
targetagonist(salmeterol,beta_2_adrenergic_receptor).
targetagonist(salmeterol,beta_3_adrenergic_receptor).
targetagonist(tramadol,delta_type_opioid_receptor).
targetagonist(tramadol,kappa_type_opioid_receptor).
targetagonist(tramadol,mu_type_opioid_receptor).
targetagonist(trazodone,c5_hydroxytryptamine_receptor_2c).
targetagonist(zolpidem,gamma_aminobutyric_acid_receptor_subunit_alpha_2).
targetagonist(zolpidem,gamma_aminobutyric_acid_receptor_subunit_alpha_3).
targetagonist(zolpidem,gamma_aminobutyric_acid_receptor_subunit_beta_3).
targetagonist(zolpidem,gamma_aminobutyric_acid_receptor_subunit_gamma_2).
targetantagonist(acetylsalicylic_acid,nuclear_factor_nf_kappa_b).
targetantagonist(amitriptyline,alpha_1a_adrenergic_receptor).
targetantagonist(amitriptyline,alpha_1b_adrenergic_receptor).
targetantagonist(amitriptyline,alpha_1d_adrenergic_receptor).
targetantagonist(amitriptyline,alpha_2a_adrenergic_receptor).
targetantagonist(amitriptyline,c5_hydroxytryptamine_receptor_2a).
targetantagonist(amitriptyline,c5_hydroxytryptamine_receptor_6).
targetantagonist(amitriptyline,c5_hydroxytryptamine_receptor_7).
targetantagonist(amitriptyline,histamine_h1_receptor).
targetantagonist(amitriptyline,muscarinic_acetylcholine_receptor_m1).
targetantagonist(amitriptyline,muscarinic_acetylcholine_receptor_m2).
targetantagonist(amitriptyline,muscarinic_acetylcholine_receptor_m3).
targetantagonist(amitriptyline,muscarinic_acetylcholine_receptor_m4).
targetantagonist(amitriptyline,muscarinic_acetylcholine_receptor_m5).
targetantagonist(aripiprazole,alpha_1a_adrenergic_receptor).
targetantagonist(aripiprazole,alpha_1b_adrenergic_receptor).
targetantagonist(aripiprazole,alpha_2a_adrenergic_receptor).
targetantagonist(aripiprazole,alpha_2b_adrenergic_receptor).
targetantagonist(aripiprazole,alpha_2c_adrenergic_receptor).
targetantagonist(aripiprazole,c5_hydroxytryptamine_receptor_1a).
targetantagonist(aripiprazole,c5_hydroxytryptamine_receptor_1b).
targetantagonist(aripiprazole,c5_hydroxytryptamine_receptor_1d).
targetantagonist(aripiprazole,c5_hydroxytryptamine_receptor_1e).
targetantagonist(aripiprazole,c5_hydroxytryptamine_receptor_2a).
targetantagonist(aripiprazole,c5_hydroxytryptamine_receptor_2c).
targetantagonist(aripiprazole,c5_hydroxytryptamine_receptor_3a).
targetantagonist(aripiprazole,c5_hydroxytryptamine_receptor_6).
targetantagonist(aripiprazole,c5_hydroxytryptamine_receptor_7).
targetantagonist(aripiprazole,d1a_dopamine_receptor).
targetantagonist(aripiprazole,d1b_dopamine_receptor).
targetantagonist(aripiprazole,d2_dopamine_receptor).
targetantagonist(aripiprazole,d3_dopamine_receptor).
targetantagonist(aripiprazole,d4_dopamine_receptor).
targetantagonist(aripiprazole,histamine_h1_receptor).
targetantagonist(aripiprazole,muscarinic_acetylcholine_receptor_m1).
targetantagonist(aripiprazole,muscarinic_acetylcholine_receptor_m2).
targetantagonist(aripiprazole,muscarinic_acetylcholine_receptor_m3).
targetantagonist(aripiprazole,muscarinic_acetylcholine_receptor_m4).
targetantagonist(aripiprazole,muscarinic_acetylcholine_receptor_m5).
targetantagonist(budesonide,glucocorticoid_receptor).
targetantagonist(cetirizine,histamine_h1_receptor).
targetantagonist(cyclobenzaprine,c5_hydroxytryptamine_receptor_2a).
targetantagonist(diphenhydramine,histamine_h1_receptor).
targetantagonist(diphenhydramine,muscarinic_acetylcholine_receptor_m2).
targetantagonist(fluoxetine,c5_hydroxytryptamine_receptor_2c).
targetantagonist(hydroxyzine,histamine_h1_receptor).
targetantagonist(lisdexamfetamine,alpha_1b_adrenergic_receptor).
targetantagonist(loratadine,histamine_h1_receptor).
targetantagonist(losartan,type_1_angiotensin_ii_receptor).
targetantagonist(methadone,c5_hydroxytryptamine_receptor_3a).
targetantagonist(methadone,glutamate_receptor_ionotropic).
targetantagonist(methadone,neuronal_acetylcholine_receptor_subunit_alpha_10).
targetantagonist(methadone,nmda_3a).
targetantagonist(metoprolol,beta_1_adrenergic_receptor).
targetantagonist(metoprolol,beta_2_adrenergic_receptor).
targetantagonist(naloxone,delta_type_opioid_receptor).
targetantagonist(naloxone,estrogen_receptor_alpha).
targetantagonist(naloxone,kappa_type_opioid_receptor).
targetantagonist(naloxone,mu_type_opioid_receptor).
targetantagonist(ondansetron,c5_hydroxytryptamine_receptor_3a).
targetantagonist(paroxetine,muscarinic_acetylcholine_receptor_m1).
targetantagonist(paroxetine,muscarinic_acetylcholine_receptor_m2).
targetantagonist(paroxetine,muscarinic_acetylcholine_receptor_m3).
targetantagonist(paroxetine,muscarinic_acetylcholine_receptor_m4).
targetantagonist(paroxetine,muscarinic_acetylcholine_receptor_m5).
targetantagonist(phentermine,amine_oxidase__flavin_containing__a).
targetantagonist(phentermine,amine_oxidase__flavin_containing__b).
targetantagonist(propranolol,beta_1_adrenergic_receptor).
targetantagonist(propranolol,beta_2_adrenergic_receptor).
targetantagonist(propranolol,beta_3_adrenergic_receptor).
targetantagonist(quetiapine,alpha_1a_adrenergic_receptor).
targetantagonist(quetiapine,alpha_1b_adrenergic_receptor).
targetantagonist(quetiapine,alpha_1d_adrenergic_receptor).
targetantagonist(quetiapine,alpha_2a_adrenergic_receptor).
targetantagonist(quetiapine,alpha_2b_adrenergic_receptor).
targetantagonist(quetiapine,alpha_2c_adrenergic_receptor).
targetantagonist(quetiapine,c5_hydroxytryptamine_receptor_1a).
targetantagonist(quetiapine,c5_hydroxytryptamine_receptor_2a).
targetantagonist(quetiapine,c5_hydroxytryptamine_receptor_2c).
targetantagonist(quetiapine,c5_hydroxytryptamine_receptor_7).
targetantagonist(quetiapine,d1a_dopamine_receptor).
targetantagonist(quetiapine,d1b_dopamine_receptor).
targetantagonist(quetiapine,d2_dopamine_receptor).
targetantagonist(quetiapine,d3_dopamine_receptor).
targetantagonist(quetiapine,d4_dopamine_receptor).
targetantagonist(quetiapine,histamine_h1_receptor).
targetantagonist(quetiapine,muscarinic_acetylcholine_receptor_m1).
targetantagonist(quetiapine,muscarinic_acetylcholine_receptor_m2).
targetantagonist(quetiapine,muscarinic_acetylcholine_receptor_m3).
targetantagonist(quetiapine,muscarinic_acetylcholine_receptor_m4).
targetantagonist(quetiapine,muscarinic_acetylcholine_receptor_m5).
targetantagonist(risperidone,alpha_1a_adrenergic_receptor).
targetantagonist(risperidone,alpha_1b_adrenergic_receptor).
targetantagonist(risperidone,alpha_2a_adrenergic_receptor).
targetantagonist(risperidone,alpha_2b_adrenergic_receptor).
targetantagonist(risperidone,c5_hydroxytryptamine_receptor_1a).
targetantagonist(risperidone,c5_hydroxytryptamine_receptor_1d).
targetantagonist(risperidone,c5_hydroxytryptamine_receptor_2a).
targetantagonist(risperidone,c5_hydroxytryptamine_receptor_2c).
targetantagonist(risperidone,d1a_dopamine_receptor).
targetantagonist(risperidone,d2_dopamine_receptor).
targetantagonist(risperidone,d3_dopamine_receptor).
targetantagonist(risperidone,d4_dopamine_receptor).
targetantagonist(risperidone,histamine_h1_receptor).
targetantagonist(rivaroxaban,coagulation_factor_x).
targetantagonist(sertraline,sigma_receptor).
targetantagonist(tamsulosin,alpha_1a_adrenergic_receptor).
targetantagonist(tamsulosin,alpha_1b_adrenergic_receptor).
targetantagonist(tamsulosin,alpha_1d_adrenergic_receptor).
targetantagonist(tramadol,alpha_7_nicotinic_cholinergic_receptor_subunit).
targetantagonist(tramadol,c5_hydroxytryptamine_receptor_2c).
targetantagonist(tramadol,glutamate_receptor_ionotropic).
targetantagonist(tramadol,muscarinic_acetylcholine_receptor_m3).
targetantagonist(tramadol,nmda_3a).
targetantagonist(trazodone,alpha_1a_adrenergic_receptor).
targetantagonist(trazodone,alpha_2a_adrenergic_receptor).
targetantagonist(trazodone,c5_hydroxytryptamine_receptor_2a).
targetantagonist(trazodone,histamine_h1_receptor).
targetinducer(metformin,c5_amp_activated_protein_kinase_subunit_beta_1).
targetinhibitor(acetaminophen,fatty_acid_amide_hydrolase_1).
targetinhibitor(acetaminophen,prostaglandin_g_h_synthase_1).
targetinhibitor(acetaminophen,prostaglandin_g_h_synthase_2).
targetinhibitor(acetaminophen,prostaglandin_g_h_synthase_3).
targetinhibitor(acetylsalicylic_acid,aldo_keto_reductase_family_1_member_c1).
targetinhibitor(acetylsalicylic_acid,prostaglandin_g_h_synthase_1).
targetinhibitor(acetylsalicylic_acid,prostaglandin_g_h_synthase_2).
targetinhibitor(amdinocillin,penicillin_binding_protein_1a).
targetinhibitor(amdinocillin,penicillin_binding_protein_1b).
targetinhibitor(amdinocillin,penicillin_binding_protein_2).
targetinhibitor(amdinocillin,penicillin_binding_protein_2a).
targetinhibitor(amdinocillin,penicillin_binding_protein_2b).
targetinhibitor(amdinocillin,penicillin_binding_protein_3).
targetinhibitor(amitriptyline,c5_hydroxytryptamine_receptor_1a).
targetinhibitor(amitriptyline,potassium_voltage_gated_channel_subfamily_a_member_1).
targetinhibitor(amitriptyline,potassium_voltage_gated_channel_subfamily_d_member_2).
targetinhibitor(amitriptyline,potassium_voltage_gated_channel_subfamily_d_member_3).
targetinhibitor(amitriptyline,potassium_voltage_gated_channel_subfamily_kqt_member_2).
targetinhibitor(amitriptyline,sodium_dependent_noradrenaline_transporter).
targetinhibitor(amitriptyline,sodium_dependent_serotonin_transporter).
targetinhibitor(amlodipine,carbonic_anhydrase_1).
targetinhibitor(amlodipine,voltage_dependent_calcium_channel_subunit_alpha_2_delta_1).
targetinhibitor(amlodipine,voltage_dependent_calcium_channel_subunit_alpha_2_delta_3).
targetinhibitor(amlodipine,voltage_dependent_l_type_calcium_channel_subunit_alpha_1c).
targetinhibitor(amlodipine,voltage_dependent_l_type_calcium_channel_subunit_alpha_1d).
targetinhibitor(amlodipine,voltage_dependent_l_type_calcium_channel_subunit_alpha_1s).
targetinhibitor(amlodipine,voltage_dependent_l_type_calcium_channel_subunit_beta_2).
targetinhibitor(amlodipine,voltage_dependent_n_type_calcium_channel_subunit_alpha_1b).
targetinhibitor(amlodipine,voltage_gated_calcium_channel_beta_1_subunit_splice_variant_cavb1d).
targetinhibitor(amoxicillin,penicillin_binding_protein_1a).
targetinhibitor(amphetamine,monoamine_oxidase).
targetinhibitor(amphetamine,synaptic_vesicular_amine_transporter).
targetinhibitor(atorvastatin,c3_hydroxy_3_methylglutaryl_coenzyme_a_reductase).
targetinhibitor(atorvastatin,dipeptidyl_peptidase_4).
targetinhibitor(azithromycin,c23s_rrna).
targetinhibitor(azithromycin,c50s_ribosomal_protein_l22).
targetinhibitor(azithromycin,c50s_ribosomal_protein_l4).
targetinhibitor(celecoxib,c3_phosphoinositide_dependent_protein_kinase_1).
targetinhibitor(celecoxib,carbonic_anhydrase_2).
targetinhibitor(celecoxib,carbonic_anhydrase_3).
targetinhibitor(celecoxib,prostaglandin_g_h_synthase_2).
targetinhibitor(cephalexin,penicillin_binding_protein_1a).
targetinhibitor(cephalexin,penicillin_binding_protein_1b).
targetinhibitor(cephalexin,penicillin_binding_protein_2a).
targetinhibitor(cephalexin,penicillin_binding_protein_2b).
targetinhibitor(cephalexin,penicillin_binding_protein_3).
targetinhibitor(ciprofloxacin,dna_gyrase_subunit_a).
targetinhibitor(ciprofloxacin,dna_topoisomerase_2_alpha).
targetinhibitor(ciprofloxacin,dna_topoisomerase_4_subunit_a).
targetinhibitor(clavulanate,beta_lactamase).
targetinhibitor(clindamycin,c23s_rrna).
targetinhibitor(clindamycin,c50s_ribosomal_protein_l10).
targetinhibitor(diclofenac,acid_sensing_ion_channel_1).
targetinhibitor(diclofenac,membrane_associated).
targetinhibitor(diclofenac,phospholipase_a2).
targetinhibitor(diclofenac,prostaglandin_g_h_synthase_1).
targetinhibitor(diclofenac,prostaglandin_g_h_synthase_2).
targetinhibitor(diclofenac,sodium_channel_protein_type_4_subunit_alpha).
targetinhibitor(doxycycline,c16s_rrna).
targetinhibitor(doxycycline,c30s_ribosomal_protein_s4).
targetinhibitor(doxycycline,c30s_ribosomal_protein_s9).
targetinhibitor(duloxetine,sodium_dependent_dopamine_transporter).
targetinhibitor(duloxetine,sodium_dependent_noradrenaline_transporter).
targetinhibitor(duloxetine,sodium_dependent_serotonin_transporter).
targetinhibitor(esomeprazole,potassium_transporting_atpase_alpha_chain_1).
targetinhibitor(fenofibrate,metalloproteinase).
targetinhibitor(fluoxetine,potassium_voltage_gated_channel_subfamily_h_member_2).
targetinhibitor(fluoxetine,sodium_dependent_serotonin_transporter).
targetinhibitor(gabapentin,voltage_dependent_calcium_channel_subunit_alpha_2_delta_1).
targetinhibitor(gabapentin,voltage_dependent_calcium_channel_subunit_alpha_2_delta_2).
targetinhibitor(gabapentin,voltage_dependent_n_type_calcium_channel_subunit_alpha_1b).
targetinhibitor(ibuprofen,cystic_fibrosis_transmembrane_conductance_regulator).
targetinhibitor(ibuprofen,prostaglandin_g_h_synthase_2).
targetinhibitor(lamotrigine,adenosine_receptor_a1).
targetinhibitor(lamotrigine,adenosine_receptor_a2a).
targetinhibitor(lamotrigine,alpha_1a_adrenergic_receptor).
targetinhibitor(lamotrigine,alpha_2a_adrenergic_receptor).
targetinhibitor(lamotrigine,beta_1_adrenergic_receptor).
targetinhibitor(lamotrigine,c5_hydroxytryptamine_receptor_2a).
targetinhibitor(lamotrigine,c5_hydroxytryptamine_receptor_3a).
targetinhibitor(lamotrigine,d1_dopamine_receptor).
targetinhibitor(lamotrigine,d2_dopamine_receptor).
targetinhibitor(lamotrigine,gaba_a_receptor_anion_channel).
targetinhibitor(lamotrigine,gaba_a_receptor_benzodiazepine_site).
targetinhibitor(lamotrigine,histamine_h1_receptor).
targetinhibitor(lamotrigine,kappa_type_opioid_receptor).
targetinhibitor(lamotrigine,muscarinic_acetylcholine_receptor).
targetinhibitor(lamotrigine,sodium_channel_protein_type_2_subunit_alpha).
targetinhibitor(lamotrigine,voltage_dependent_r_type_calcium_channel_subunit_alpha_1e).
targetinhibitor(lisdexamfetamine,sodium_dependent_dopamine_transporter).
targetinhibitor(lisinopril,angiotensin_converting_enzyme).
targetinhibitor(meloxicam,prostaglandin_g_h_synthase_1).
targetinhibitor(meloxicam,prostaglandin_g_h_synthase_2).
targetinhibitor(methylphenidate,sodium_dependent_dopamine_transporter).
targetinhibitor(methylphenidate,sodium_dependent_noradrenaline_transporter).
targetinhibitor(methylphenidate,sodium_dependent_serotonin_transporter).
targetinhibitor(metronidazole,iron_hydrogenase_1).
targetinhibitor(naloxone,toll_like_receptor_4).
targetinhibitor(naproxen,prostaglandin_g_h_synthase_1).
targetinhibitor(naproxen,prostaglandin_g_h_synthase_2).
targetinhibitor(omeprazole,potassium_transporting_atpase_alpha_chain_1).
targetinhibitor(pantoprazole,potassium_transporting_atpase_alpha_chain_1).
targetinhibitor(paroxetine,sodium_dependent_noradrenaline_transporter).
targetinhibitor(paroxetine,sodium_dependent_serotonin_transporter).
targetinhibitor(phentermine,sodium_dependent_dopamine_transporter).
targetinhibitor(phentermine,sodium_dependent_noradrenaline_transporter).
targetinhibitor(phentermine,sodium_dependent_serotonin_transporter).
targetinhibitor(pravastatin,c3_hydroxy_3_methylglutaryl_coenzyme_a_reductase).
targetinhibitor(pregabalin,voltage_dependent_p_q_type_calcium_channel_subunit_alpha_1a).
targetinhibitor(sertraline,sodium_dependent_dopamine_transporter).
targetinhibitor(sertraline,sodium_dependent_serotonin_transporter).
targetinhibitor(sildenafil,c5_cyclic_phosphodiesterase).
targetinhibitor(sildenafil,c5_cyclic_phosphodiesterase_subunit_gamma).
targetinhibitor(sildenafil,c5_cyclic_phosphodiesterase_subunit_gamma).
targetinhibitor(sildenafil,cgmp_specific_3).
targetinhibitor(sildenafil,retinal_cone_rhodopsin_sensitive_cgmp_3).
targetinhibitor(sildenafil,retinal_rod_rhodopsin_sensitive_cgmp_3).
targetinhibitor(simvastatin,c3_hydroxy_3_methylglutaryl_coenzyme_a_reductase).
targetinhibitor(simvastatin,integrin_alpha_l).
targetinhibitor(sitagliptin,dipeptidyl_peptidase_4).
targetinhibitor(tadalafil,c5_cyclic_amp_and__gmp_phosphodiesterase_11a).
targetinhibitor(tadalafil,c5_cyclic_phosphodiesterase).
targetinhibitor(tadalafil,cgmp_specific_3).
targetinhibitor(tadalafil,dual_3).
targetinhibitor(tramadol,sodium_dependent_noradrenaline_transporter).
targetinhibitor(tramadol,sodium_dependent_serotonin_transporter).
targetinhibitor(trazodone,sodium_dependent_serotonin_transporter).
targetinhibitor(venlafaxine,sodium_dependent_dopamine_transporter).
targetinhibitor(venlafaxine,sodium_dependent_noradrenaline_transporter).
targetinhibitor(venlafaxine,sodium_dependent_serotonin_transporter).
targetinhibitor(warfarin,vitamin_k_epoxide_reductase_complex_subunit_1).
transporter(atp_binding_cassette_sub_family_g_member_2,omeprazole).
transporter(atp_binding_cassette_sub_family_g_member_2,pantoprazole).
transporter(atp_binding_cassette_sub_family_g_member_2,pravastatin).
transporter(atp_binding_cassette_sub_family_g_member_2,venlafaxine).
transporter(bile_salt_export_pump,pravastatin).
transporter(c_facilitated_glucose_transporter_member_9,losartan).
transporter(canalicular_multispecific_organic_anion_transporter_1,atorvastatin).
transporter(canalicular_multispecific_organic_anion_transporter_1,pravastatin).
transporter(canalicular_multispecific_organic_anion_transporter_1,simvastatin).
transporter(canalicular_multispecific_organic_anion_transporter_2,omeprazole).
transporter(equilibrative_nucleoside_transporter_4,metformin).
transporter(excitatory_amino_acid_transporter_3,pregabalin).
transporter(large_neutral_amino_acids_transporter_small_subunit_1,levothyroxine).
transporter(monocarboxylate_transporter_1,pravastatin).
transporter(monocarboxylate_transporter_8,levothyroxine).
transporter(multidrug_and_toxin_extrusion_protein_1,cephalexin).
transporter(multidrug_and_toxin_extrusion_protein_1,metformin).
transporter(multidrug_resistance_associated_protein_1,atorvastatin).
transporter(multidrug_resistance_associated_protein_1,diclofenac).
transporter(multidrug_resistance_associated_protein_1,ibuprofen).
transporter(multidrug_resistance_associated_protein_4,atorvastatin).
transporter(multidrug_resistance_associated_protein_4,celecoxib).
transporter(multidrug_resistance_associated_protein_4,diclofenac).
transporter(multidrug_resistance_associated_protein_4,ibuprofen).
transporter(multidrug_resistance_associated_protein_4,meloxicam).
transporter(multidrug_resistance_associated_protein_4,sildenafil).
transporter(multidrug_resistance_associated_protein_5,atorvastatin).
transporter(multidrug_resistance_associated_protein_5,sildenafil).
transporter(multidrug_resistance_associated_protein_7,sildenafil).
transporter(multidrug_resistance_protein_1,acetaminophen).
transporter(multidrug_resistance_protein_1,acetylsalicylic_acid).
transporter(multidrug_resistance_protein_1,amitriptyline).
transporter(multidrug_resistance_protein_1,amlodipine).
transporter(multidrug_resistance_protein_1,atorvastatin).
transporter(multidrug_resistance_protein_1,azithromycin).
transporter(multidrug_resistance_protein_1,ciprofloxacin).
transporter(multidrug_resistance_protein_1,clonidine).
transporter(multidrug_resistance_protein_1,diazepam).
transporter(multidrug_resistance_protein_1,diclofenac).
transporter(multidrug_resistance_protein_1,fluoxetine).
transporter(multidrug_resistance_protein_1,ibuprofen).
transporter(multidrug_resistance_protein_1,lamotrigine).
transporter(multidrug_resistance_protein_1,levothyroxine).
transporter(multidrug_resistance_protein_1,loratadine).
transporter(multidrug_resistance_protein_1,losartan).
transporter(multidrug_resistance_protein_1,methadone).
transporter(multidrug_resistance_protein_1,metoprolol).
transporter(multidrug_resistance_protein_1,morphine).
transporter(multidrug_resistance_protein_1,naloxone).
transporter(multidrug_resistance_protein_1,omeprazole).
transporter(multidrug_resistance_protein_1,pantoprazole).
transporter(multidrug_resistance_protein_1,paroxetine).
transporter(multidrug_resistance_protein_1,pravastatin).
transporter(multidrug_resistance_protein_1,prednisone).
transporter(multidrug_resistance_protein_1,propranolol).
transporter(multidrug_resistance_protein_1,quetiapine).
transporter(multidrug_resistance_protein_1,rivaroxaban).
transporter(multidrug_resistance_protein_1,sertraline).
transporter(multidrug_resistance_protein_1,simvastatin).
transporter(multidrug_resistance_protein_1,sitagliptin).
transporter(multidrug_resistance_protein_1,trazodone).
transporter(multidrug_resistance_protein_1,venlafaxine).
transporter(solute_carrier_family_15_member_1,amoxicillin).
transporter(solute_carrier_family_15_member_1,cephalexin).
transporter(solute_carrier_family_15_member_2,amoxicillin).
transporter(solute_carrier_family_15_member_2,cephalexin).
transporter(solute_carrier_family_2,losartan).
transporter(solute_carrier_family_22_member_1,clonidine).
transporter(solute_carrier_family_22_member_1,diphenhydramine).
transporter(solute_carrier_family_22_member_1,metformin).
transporter(solute_carrier_family_22_member_11,diclofenac).
transporter(solute_carrier_family_22_member_11,doxycycline).
transporter(solute_carrier_family_22_member_11,ibuprofen).
transporter(solute_carrier_family_22_member_11,pravastatin).
transporter(solute_carrier_family_22_member_12,losartan).
transporter(solute_carrier_family_22_member_2,diphenhydramine).
transporter(solute_carrier_family_22_member_2,metformin).
transporter(solute_carrier_family_22_member_2,metoprolol).
transporter(solute_carrier_family_22_member_2,propranolol).
transporter(solute_carrier_family_22_member_3,amphetamine).
transporter(solute_carrier_family_22_member_3,clonidine).
transporter(solute_carrier_family_22_member_3,metformin).
transporter(solute_carrier_family_22_member_4,clonidine).
transporter(solute_carrier_family_22_member_5,amphetamine).
transporter(solute_carrier_family_22_member_5,cephalexin).
transporter(solute_carrier_family_22_member_5,clonidine).
transporter(solute_carrier_family_22_member_5,diphenhydramine).
transporter(solute_carrier_family_22_member_6,acetaminophen).
transporter(solute_carrier_family_22_member_6,acetylsalicylic_acid).
transporter(solute_carrier_family_22_member_6,amoxicillin).
transporter(solute_carrier_family_22_member_6,cephalexin).
transporter(solute_carrier_family_22_member_6,diclofenac).
transporter(solute_carrier_family_22_member_6,doxycycline).
transporter(solute_carrier_family_22_member_6,ibuprofen).
transporter(solute_carrier_family_22_member_6,losartan).
transporter(solute_carrier_family_22_member_6,naproxen).
transporter(solute_carrier_family_22_member_6,pravastatin).
transporter(solute_carrier_family_22_member_7,acetylsalicylic_acid).
transporter(solute_carrier_family_22_member_7,pravastatin).
transporter(solute_carrier_family_22_member_8,baclofen).
transporter(solute_carrier_family_22_member_8,cephalexin).
transporter(solute_carrier_family_22_member_8,diclofenac).
transporter(solute_carrier_family_22_member_8,doxycycline).
transporter(solute_carrier_family_22_member_8,ibuprofen).
transporter(solute_carrier_family_22_member_8,pravastatin).
transporter(solute_carrier_organic_anion_transporter_family_member_1a2,atorvastatin).
transporter(solute_carrier_organic_anion_transporter_family_member_1a2,ibuprofen).
transporter(solute_carrier_organic_anion_transporter_family_member_1a2,levothyroxine).
transporter(solute_carrier_organic_anion_transporter_family_member_1a2,naloxone).
transporter(solute_carrier_organic_anion_transporter_family_member_1a2,naproxen).
transporter(solute_carrier_organic_anion_transporter_family_member_1a2,pravastatin).
transporter(solute_carrier_organic_anion_transporter_family_member_1a2,prednisone).
transporter(solute_carrier_organic_anion_transporter_family_member_1a2,simvastatin).
transporter(solute_carrier_organic_anion_transporter_family_member_1b1,atorvastatin).
transporter(solute_carrier_organic_anion_transporter_family_member_1b1,levothyroxine).
transporter(solute_carrier_organic_anion_transporter_family_member_1b1,pantoprazole).
transporter(solute_carrier_organic_anion_transporter_family_member_1b1,pravastatin).
transporter(solute_carrier_organic_anion_transporter_family_member_1b1,simvastatin).
transporter(solute_carrier_organic_anion_transporter_family_member_1b3,atorvastatin).
transporter(solute_carrier_organic_anion_transporter_family_member_1b3,levothyroxine).
transporter(solute_carrier_organic_anion_transporter_family_member_1b3,pravastatin).
transporter(solute_carrier_organic_anion_transporter_family_member_1c1,diclofenac).
transporter(solute_carrier_organic_anion_transporter_family_member_1c1,levothyroxine).
transporter(solute_carrier_organic_anion_transporter_family_member_2b1,atorvastatin).
transporter(solute_carrier_organic_anion_transporter_family_member_2b1,ibuprofen).
transporter(solute_carrier_organic_anion_transporter_family_member_2b1,pravastatin).
transporter(solute_carrier_organic_anion_transporter_family_member_4a1,levothyroxine).
transporter(solute_carrier_organic_anion_transporter_family_member_4c1,levothyroxine).
transporterinducer(levothyroxine,multidrug_resistance_protein_1).
transporterinducer(omeprazole,canalicular_multispecific_organic_anion_transporter_2).
transporterinducer(trazodone,multidrug_resistance_protein_1).
transporterinducer(venlafaxine,atp_binding_cassette_sub_family_g_member_2).
transporterinhibitor(acetaminophen,multidrug_resistance_protein_1).
transporterinhibitor(acetaminophen,solute_carrier_family_22_member_6).
transporterinhibitor(acetylsalicylic_acid,solute_carrier_family_22_member_6).
transporterinhibitor(amitriptyline,multidrug_resistance_protein_1).
transporterinhibitor(amlodipine,multidrug_resistance_protein_1).
transporterinhibitor(amoxicillin,solute_carrier_family_15_member_1).
transporterinhibitor(amoxicillin,solute_carrier_family_15_member_2).
transporterinhibitor(amoxicillin,solute_carrier_family_22_member_6).
transporterinhibitor(amphetamine,solute_carrier_family_22_member_3).
transporterinhibitor(amphetamine,solute_carrier_family_22_member_5).
transporterinhibitor(atorvastatin,multidrug_resistance_protein_1).
transporterinhibitor(atorvastatin,solute_carrier_organic_anion_transporter_family_member_1a2).
transporterinhibitor(atorvastatin,solute_carrier_organic_anion_transporter_family_member_1b1).
transporterinhibitor(azithromycin,multidrug_resistance_protein_1).
transporterinhibitor(baclofen,solute_carrier_family_22_member_8).
transporterinhibitor(celecoxib,multidrug_resistance_associated_protein_4).
transporterinhibitor(cephalexin,solute_carrier_family_15_member_1).
transporterinhibitor(cephalexin,solute_carrier_family_15_member_2).
transporterinhibitor(cephalexin,solute_carrier_family_22_member_5).
transporterinhibitor(cephalexin,solute_carrier_family_22_member_6).
transporterinhibitor(cephalexin,solute_carrier_family_22_member_8).
transporterinhibitor(ciprofloxacin,multidrug_resistance_protein_1).
transporterinhibitor(clonidine,solute_carrier_family_22_member_1).
transporterinhibitor(clonidine,solute_carrier_family_22_member_3).
transporterinhibitor(clonidine,solute_carrier_family_22_member_4).
transporterinhibitor(clonidine,solute_carrier_family_22_member_5).
transporterinhibitor(diclofenac,multidrug_resistance_associated_protein_1).
transporterinhibitor(diclofenac,multidrug_resistance_associated_protein_4).
transporterinhibitor(diclofenac,multidrug_resistance_protein_1).
transporterinhibitor(diclofenac,solute_carrier_family_22_member_11).
transporterinhibitor(diclofenac,solute_carrier_family_22_member_6).
transporterinhibitor(diclofenac,solute_carrier_family_22_member_8).
transporterinhibitor(diclofenac,solute_carrier_organic_anion_transporter_family_member_1c1).
transporterinhibitor(diphenhydramine,solute_carrier_family_22_member_1).
transporterinhibitor(diphenhydramine,solute_carrier_family_22_member_2).
transporterinhibitor(diphenhydramine,solute_carrier_family_22_member_5).
transporterinhibitor(doxycycline,solute_carrier_family_22_member_11).
transporterinhibitor(doxycycline,solute_carrier_family_22_member_6).
transporterinhibitor(doxycycline,solute_carrier_family_22_member_8).
transporterinhibitor(fluoxetine,multidrug_resistance_protein_1).
transporterinhibitor(ibuprofen,multidrug_resistance_associated_protein_1).
transporterinhibitor(ibuprofen,multidrug_resistance_associated_protein_4).
transporterinhibitor(ibuprofen,solute_carrier_family_22_member_11).
transporterinhibitor(ibuprofen,solute_carrier_family_22_member_6).
transporterinhibitor(ibuprofen,solute_carrier_family_22_member_8).
transporterinhibitor(ibuprofen,solute_carrier_organic_anion_transporter_family_member_1a2).
transporterinhibitor(levothyroxine,monocarboxylate_transporter_8).
transporterinhibitor(loratadine,multidrug_resistance_protein_1).
transporterinhibitor(losartan,facilitated_glucose_transporter_member_9).
transporterinhibitor(losartan,multidrug_resistance_protein_1).
transporterinhibitor(losartan,solute_carrier_family_2).
transporterinhibitor(losartan,solute_carrier_family_22_member_12).
transporterinhibitor(losartan,solute_carrier_family_22_member_6).
transporterinhibitor(metformin,multidrug_and_toxin_extrusion_protein_1).
transporterinhibitor(metformin,solute_carrier_family_22_member_1).
transporterinhibitor(metformin,solute_carrier_family_22_member_2).
transporterinhibitor(methadone,multidrug_resistance_protein_1).
transporterinhibitor(metoprolol,multidrug_resistance_protein_1).
transporterinhibitor(metoprolol,solute_carrier_family_22_member_2).
transporterinhibitor(morphine,multidrug_resistance_protein_1).
transporterinhibitor(naloxone,solute_carrier_organic_anion_transporter_family_member_1a2).
transporterinhibitor(naproxen,solute_carrier_family_22_member_6).
transporterinhibitor(naproxen,solute_carrier_organic_anion_transporter_family_member_1a2).
transporterinhibitor(omeprazole,atp_binding_cassette_sub_family_g_member_2).
transporterinhibitor(omeprazole,multidrug_resistance_protein_1).
transporterinhibitor(pantoprazole,atp_binding_cassette_sub_family_g_member_2).
transporterinhibitor(pantoprazole,multidrug_resistance_protein_1).
transporterinhibitor(pantoprazole,solute_carrier_organic_anion_transporter_family_member_1b1).
transporterinhibitor(paroxetine,multidrug_resistance_protein_1).
transporterinhibitor(pravastatin,atp_binding_cassette_sub_family_g_member_2).
transporterinhibitor(pravastatin,canalicular_multispecific_organic_anion_transporter_1).
transporterinhibitor(pravastatin,multidrug_resistance_protein_1).
transporterinhibitor(pravastatin,solute_carrier_family_22_member_11).
transporterinhibitor(pravastatin,solute_carrier_family_22_member_6).
transporterinhibitor(pravastatin,solute_carrier_family_22_member_7).
transporterinhibitor(pravastatin,solute_carrier_family_22_member_8).
transporterinhibitor(pravastatin,solute_carrier_organic_anion_transporter_family_member_1a2).
transporterinhibitor(pravastatin,solute_carrier_organic_anion_transporter_family_member_1b1).
transporterinhibitor(pravastatin,solute_carrier_organic_anion_transporter_family_member_2b1).
transporterinhibitor(prednisone,multidrug_resistance_protein_1).
transporterinhibitor(prednisone,solute_carrier_organic_anion_transporter_family_member_1a2).
transporterinhibitor(propranolol,multidrug_resistance_protein_1).
transporterinhibitor(propranolol,solute_carrier_family_22_member_2).
transporterinhibitor(sertraline,multidrug_resistance_protein_1).
transporterinhibitor(sildenafil,multidrug_resistance_associated_protein_4).
transporterinhibitor(sildenafil,multidrug_resistance_associated_protein_5).
transporterinhibitor(sildenafil,multidrug_resistance_associated_protein_7).
transporterinhibitor(simvastatin,multidrug_resistance_protein_1).
transporterinhibitor(simvastatin,solute_carrier_organic_anion_transporter_family_member_1a2).
transporterinhibitor(simvastatin,solute_carrier_organic_anion_transporter_family_member_1b1).
transporterinhibitor(venlafaxine,multidrug_resistance_protein_1).
transportersubstrate(acetaminophen,multidrug_resistance_protein_1).
transportersubstrate(acetylsalicylic_acid,multidrug_resistance_protein_1).
transportersubstrate(acetylsalicylic_acid,solute_carrier_family_22_member_7).
transportersubstrate(amitriptyline,multidrug_resistance_protein_1).
transportersubstrate(atorvastatin,canalicular_multispecific_organic_anion_transporter_1).
transportersubstrate(atorvastatin,multidrug_resistance_associated_protein_1).
transportersubstrate(atorvastatin,multidrug_resistance_associated_protein_4).
transportersubstrate(atorvastatin,multidrug_resistance_associated_protein_5).
transportersubstrate(atorvastatin,solute_carrier_organic_anion_transporter_family_member_1b1).
transportersubstrate(atorvastatin,solute_carrier_organic_anion_transporter_family_member_1b3).
transportersubstrate(cephalexin,multidrug_and_toxin_extrusion_protein_1).
transportersubstrate(cephalexin,solute_carrier_family_15_member_1).
transportersubstrate(cephalexin,solute_carrier_family_22_member_6).
transportersubstrate(ciprofloxacin,multidrug_resistance_protein_1).
transportersubstrate(clonidine,multidrug_resistance_protein_1).
transportersubstrate(diazepam,multidrug_resistance_protein_1).
transportersubstrate(ibuprofen,multidrug_resistance_protein_1).
transportersubstrate(ibuprofen,solute_carrier_organic_anion_transporter_family_member_2b1).
transportersubstrate(lamotrigine,multidrug_resistance_protein_1).
transportersubstrate(levothyroxine,solute_carrier_organic_anion_transporter_family_member_1c1).
transportersubstrate(losartan,multidrug_resistance_protein_1).
transportersubstrate(meloxicam,multidrug_resistance_associated_protein_4).
transportersubstrate(metformin,equilibrative_nucleoside_transporter_4).
transportersubstrate(metformin,solute_carrier_family_22_member_1).
transportersubstrate(metformin,solute_carrier_family_22_member_2).
transportersubstrate(metformin,solute_carrier_family_22_member_3).
transportersubstrate(metoprolol,multidrug_resistance_protein_1).
transportersubstrate(morphine,multidrug_resistance_protein_1).
transportersubstrate(naloxone,multidrug_resistance_protein_1).
transportersubstrate(pravastatin,atp_binding_cassette_sub_family_g_member_2).
transportersubstrate(pravastatin,bile_salt_export_pump).
transportersubstrate(pravastatin,canalicular_multispecific_organic_anion_transporter_1).
transportersubstrate(pravastatin,multidrug_resistance_protein_1).
transportersubstrate(pravastatin,solute_carrier_family_22_member_8).
transportersubstrate(pravastatin,solute_carrier_organic_anion_transporter_family_member_1b1).
transportersubstrate(pravastatin,solute_carrier_organic_anion_transporter_family_member_1b3).
transportersubstrate(pravastatin,solute_carrier_organic_anion_transporter_family_member_2b1).
transportersubstrate(prednisone,multidrug_resistance_protein_1).
transportersubstrate(propranolol,multidrug_resistance_protein_1).
transportersubstrate(quetiapine,multidrug_resistance_protein_1).
transportersubstrate(rivaroxaban,multidrug_resistance_protein_1).
transportersubstrate(simvastatin,canalicular_multispecific_organic_anion_transporter_1).
transportersubstrate(simvastatin,solute_carrier_organic_anion_transporter_family_member_1b1).
transportersubstrate(sitagliptin,multidrug_resistance_protein_1).
transportersubstrate(venlafaxine,multidrug_resistance_protein_1).