goal_inbox(obj3,receptacle_box,0).
goal_inbox(obj3,receptacle_box,1).
goal_inbox(obj3,receptacle_box,10).
goal_inbox(obj3,receptacle_box,11).
goal_inbox(obj3,receptacle_box,12).
goal_inbox(obj3,receptacle_box,13).
goal_inbox(obj3,receptacle_box,14).
goal_inbox(obj3,receptacle_box,15).
goal_inbox(obj3,receptacle_box,16).
goal_inbox(obj3,receptacle_box,2).
goal_inbox(obj3,receptacle_box,3).
goal_inbox(obj3,receptacle_box,4).
goal_inbox(obj3,receptacle_box,5).
goal_inbox(obj3,receptacle_box,6).
goal_inbox(obj3,receptacle_box,7).
goal_inbox(obj3,receptacle_box,8).
goal_inbox(obj3,receptacle_box,9).
goal_inshelf(obj0,receptacle_shelf,0).
goal_inshelf(obj0,receptacle_shelf,1).
goal_inshelf(obj0,receptacle_shelf,10).
goal_inshelf(obj0,receptacle_shelf,11).
goal_inshelf(obj0,receptacle_shelf,12).
goal_inshelf(obj0,receptacle_shelf,13).
goal_inshelf(obj0,receptacle_shelf,14).
goal_inshelf(obj0,receptacle_shelf,15).
goal_inshelf(obj0,receptacle_shelf,16).
goal_inshelf(obj0,receptacle_shelf,2).
goal_inshelf(obj0,receptacle_shelf,3).
goal_inshelf(obj0,receptacle_shelf,4).
goal_inshelf(obj0,receptacle_shelf,5).
goal_inshelf(obj0,receptacle_shelf,6).
goal_inshelf(obj0,receptacle_shelf,7).
goal_inshelf(obj0,receptacle_shelf,8).
goal_inshelf(obj0,receptacle_shelf,9).
goal_inshelf(obj1,receptacle_shelf,0).
goal_inshelf(obj1,receptacle_shelf,1).
goal_inshelf(obj1,receptacle_shelf,10).
goal_inshelf(obj1,receptacle_shelf,11).
goal_inshelf(obj1,receptacle_shelf,12).
goal_inshelf(obj1,receptacle_shelf,13).
goal_inshelf(obj1,receptacle_shelf,14).
goal_inshelf(obj1,receptacle_shelf,15).
goal_inshelf(obj1,receptacle_shelf,16).
goal_inshelf(obj1,receptacle_shelf,2).
goal_inshelf(obj1,receptacle_shelf,3).
goal_inshelf(obj1,receptacle_shelf,4).
goal_inshelf(obj1,receptacle_shelf,5).
goal_inshelf(obj1,receptacle_shelf,6).
goal_inshelf(obj1,receptacle_shelf,7).
goal_inshelf(obj1,receptacle_shelf,8).
goal_inshelf(obj1,receptacle_shelf,9).
goal_inshelf(obj2,receptacle_shelf,0).
goal_inshelf(obj2,receptacle_shelf,1).
goal_inshelf(obj2,receptacle_shelf,10).
goal_inshelf(obj2,receptacle_shelf,11).
goal_inshelf(obj2,receptacle_shelf,12).
goal_inshelf(obj2,receptacle_shelf,13).
goal_inshelf(obj2,receptacle_shelf,14).
goal_inshelf(obj2,receptacle_shelf,15).
goal_inshelf(obj2,receptacle_shelf,16).
goal_inshelf(obj2,receptacle_shelf,2).
goal_inshelf(obj2,receptacle_shelf,3).
goal_inshelf(obj2,receptacle_shelf,4).
goal_inshelf(obj2,receptacle_shelf,5).
goal_inshelf(obj2,receptacle_shelf,6).
goal_inshelf(obj2,receptacle_shelf,7).
goal_inshelf(obj2,receptacle_shelf,8).
goal_inshelf(obj2,receptacle_shelf,9).
goal_isboxcolor(obj3,receptacle_box,0).
goal_isboxcolor(obj3,receptacle_box,1).
goal_isboxcolor(obj3,receptacle_box,10).
goal_isboxcolor(obj3,receptacle_box,11).
goal_isboxcolor(obj3,receptacle_box,12).
goal_isboxcolor(obj3,receptacle_box,13).
goal_isboxcolor(obj3,receptacle_box,14).
goal_isboxcolor(obj3,receptacle_box,15).
goal_isboxcolor(obj3,receptacle_box,16).
goal_isboxcolor(obj3,receptacle_box,2).
goal_isboxcolor(obj3,receptacle_box,3).
goal_isboxcolor(obj3,receptacle_box,4).
goal_isboxcolor(obj3,receptacle_box,5).
goal_isboxcolor(obj3,receptacle_box,6).
goal_isboxcolor(obj3,receptacle_box,7).
goal_isboxcolor(obj3,receptacle_box,8).
goal_isboxcolor(obj3,receptacle_box,9).
goal_isshelfcolor(obj0,receptacle_shelf,0).
goal_isshelfcolor(obj0,receptacle_shelf,1).
goal_isshelfcolor(obj0,receptacle_shelf,10).
goal_isshelfcolor(obj0,receptacle_shelf,11).
goal_isshelfcolor(obj0,receptacle_shelf,12).
goal_isshelfcolor(obj0,receptacle_shelf,13).
goal_isshelfcolor(obj0,receptacle_shelf,14).
goal_isshelfcolor(obj0,receptacle_shelf,15).
goal_isshelfcolor(obj0,receptacle_shelf,16).
goal_isshelfcolor(obj0,receptacle_shelf,2).
goal_isshelfcolor(obj0,receptacle_shelf,3).
goal_isshelfcolor(obj0,receptacle_shelf,4).
goal_isshelfcolor(obj0,receptacle_shelf,5).
goal_isshelfcolor(obj0,receptacle_shelf,6).
goal_isshelfcolor(obj0,receptacle_shelf,7).
goal_isshelfcolor(obj0,receptacle_shelf,8).
goal_isshelfcolor(obj0,receptacle_shelf,9).
goal_isshelfcolor(obj1,receptacle_shelf,0).
goal_isshelfcolor(obj1,receptacle_shelf,1).
goal_isshelfcolor(obj1,receptacle_shelf,10).
goal_isshelfcolor(obj1,receptacle_shelf,11).
goal_isshelfcolor(obj1,receptacle_shelf,12).
goal_isshelfcolor(obj1,receptacle_shelf,13).
goal_isshelfcolor(obj1,receptacle_shelf,14).
goal_isshelfcolor(obj1,receptacle_shelf,15).
goal_isshelfcolor(obj1,receptacle_shelf,16).
goal_isshelfcolor(obj1,receptacle_shelf,2).
goal_isshelfcolor(obj1,receptacle_shelf,3).
goal_isshelfcolor(obj1,receptacle_shelf,4).
goal_isshelfcolor(obj1,receptacle_shelf,5).
goal_isshelfcolor(obj1,receptacle_shelf,6).
goal_isshelfcolor(obj1,receptacle_shelf,7).
goal_isshelfcolor(obj1,receptacle_shelf,8).
goal_isshelfcolor(obj1,receptacle_shelf,9).
goal_isshelfcolor(obj2,receptacle_shelf,0).
goal_isshelfcolor(obj2,receptacle_shelf,1).
goal_isshelfcolor(obj2,receptacle_shelf,10).
goal_isshelfcolor(obj2,receptacle_shelf,11).
goal_isshelfcolor(obj2,receptacle_shelf,12).
goal_isshelfcolor(obj2,receptacle_shelf,13).
goal_isshelfcolor(obj2,receptacle_shelf,14).
goal_isshelfcolor(obj2,receptacle_shelf,15).
goal_isshelfcolor(obj2,receptacle_shelf,16).
goal_isshelfcolor(obj2,receptacle_shelf,2).
goal_isshelfcolor(obj2,receptacle_shelf,3).
goal_isshelfcolor(obj2,receptacle_shelf,4).
goal_isshelfcolor(obj2,receptacle_shelf,5).
goal_isshelfcolor(obj2,receptacle_shelf,6).
goal_isshelfcolor(obj2,receptacle_shelf,7).
goal_isshelfcolor(obj2,receptacle_shelf,8).
goal_isshelfcolor(obj2,receptacle_shelf,9).
gripperopen(robby,0).
gripperopen(robby,12).
gripperopen(robby,4).
gripperopen(robby,8).
holding(obj0,13).
holding(obj0,14).
holding(obj0,15).
holding(obj0,16).
holding(obj1,10).
holding(obj1,11).
holding(obj1,9).
holding(obj2,5).
holding(obj2,6).
holding(obj2,7).
holding(obj3,1).
holding(obj3,2).
holding(obj3,3).
holdingside(obj0,13).
holdingside(obj0,14).
holdingside(obj0,15).
holdingside(obj0,16).
holdingside(obj1,10).
holdingside(obj1,11).
holdingside(obj1,9).
holdingside(obj2,5).
holdingside(obj2,6).
holdingside(obj2,7).
holdingtop(obj3,1).
holdingtop(obj3,2).
holdingtop(obj3,3).
inbox(obj3,receptacle_box,10).
inbox(obj3,receptacle_box,11).
inbox(obj3,receptacle_box,12).
inbox(obj3,receptacle_box,13).
inbox(obj3,receptacle_box,14).
inbox(obj3,receptacle_box,15).
inbox(obj3,receptacle_box,16).
inbox(obj3,receptacle_box,4).
inbox(obj3,receptacle_box,5).
inbox(obj3,receptacle_box,6).
inbox(obj3,receptacle_box,7).
inbox(obj3,receptacle_box,8).
inbox(obj3,receptacle_box,9).
inshelf(obj1,receptacle_shelf,12).
inshelf(obj1,receptacle_shelf,13).
inshelf(obj1,receptacle_shelf,14).
inshelf(obj1,receptacle_shelf,15).
inshelf(obj1,receptacle_shelf,16).
inshelf(obj2,receptacle_shelf,10).
inshelf(obj2,receptacle_shelf,11).
inshelf(obj2,receptacle_shelf,12).
inshelf(obj2,receptacle_shelf,13).
inshelf(obj2,receptacle_shelf,14).
inshelf(obj2,receptacle_shelf,15).
inshelf(obj2,receptacle_shelf,16).
inshelf(obj2,receptacle_shelf,8).
inshelf(obj2,receptacle_shelf,9).
isboxcolor(obj3,receptacle_box,10).
isboxcolor(obj3,receptacle_box,11).
isboxcolor(obj3,receptacle_box,12).
isboxcolor(obj3,receptacle_box,13).
isboxcolor(obj3,receptacle_box,14).
isboxcolor(obj3,receptacle_box,15).
isboxcolor(obj3,receptacle_box,16).
isboxcolor(obj3,receptacle_box,3).
isboxcolor(obj3,receptacle_box,4).
isboxcolor(obj3,receptacle_box,5).
isboxcolor(obj3,receptacle_box,6).
isboxcolor(obj3,receptacle_box,7).
isboxcolor(obj3,receptacle_box,8).
isboxcolor(obj3,receptacle_box,9).
isclean(obj0,14).
isclean(obj0,15).
isclean(obj0,16).
isclean(obj1,0).
isclean(obj1,1).
isclean(obj1,10).
isclean(obj1,11).
isclean(obj1,12).
isclean(obj1,13).
isclean(obj1,14).
isclean(obj1,15).
isclean(obj1,16).
isclean(obj1,2).
isclean(obj1,3).
isclean(obj1,4).
isclean(obj1,5).
isclean(obj1,6).
isclean(obj1,7).
isclean(obj1,8).
isclean(obj1,9).
isclean(obj2,0).
isclean(obj2,1).
isclean(obj2,10).
isclean(obj2,11).
isclean(obj2,12).
isclean(obj2,13).
isclean(obj2,14).
isclean(obj2,15).
isclean(obj2,16).
isclean(obj2,2).
isclean(obj2,3).
isclean(obj2,4).
isclean(obj2,5).
isclean(obj2,6).
isclean(obj2,7).
isclean(obj2,8).
isclean(obj2,9).
isclean(obj3,0).
isclean(obj3,1).
isclean(obj3,10).
isclean(obj3,11).
isclean(obj3,12).
isclean(obj3,13).
isclean(obj3,14).
isclean(obj3,15).
isclean(obj3,16).
isclean(obj3,2).
isclean(obj3,3).
isclean(obj3,4).
isclean(obj3,5).
isclean(obj3,6).
isclean(obj3,7).
isclean(obj3,8).
isclean(obj3,9).
isdirty(obj0,0).
isdirty(obj0,1).
isdirty(obj0,10).
isdirty(obj0,11).
isdirty(obj0,12).
isdirty(obj0,13).
isdirty(obj0,2).
isdirty(obj0,3).
isdirty(obj0,4).
isdirty(obj0,5).
isdirty(obj0,6).
isdirty(obj0,7).
isdirty(obj0,8).
isdirty(obj0,9).
isdry(obj0,0).
isdry(obj0,1).
isdry(obj0,10).
isdry(obj0,11).
isdry(obj0,12).
isdry(obj0,13).
isdry(obj0,15).
isdry(obj0,16).
isdry(obj0,2).
isdry(obj0,3).
isdry(obj0,4).
isdry(obj0,5).
isdry(obj0,6).
isdry(obj0,7).
isdry(obj0,8).
isdry(obj0,9).
isdry(obj1,10).
isdry(obj1,11).
isdry(obj1,12).
isdry(obj1,13).
isdry(obj1,14).
isdry(obj1,15).
isdry(obj1,16).
isdry(obj2,10).
isdry(obj2,11).
isdry(obj2,12).
isdry(obj2,13).
isdry(obj2,14).
isdry(obj2,15).
isdry(obj2,16).
isdry(obj2,6).
isdry(obj2,7).
isdry(obj2,8).
isdry(obj2,9).
isdry(obj3,10).
isdry(obj3,11).
isdry(obj3,12).
isdry(obj3,13).
isdry(obj3,14).
isdry(obj3,15).
isdry(obj3,16).
isdry(obj3,2).
isdry(obj3,3).
isdry(obj3,4).
isdry(obj3,5).
isdry(obj3,6).
isdry(obj3,7).
isdry(obj3,8).
isdry(obj3,9).
isshelfcolor(obj0,receptacle_shelf,16).
isshelfcolor(obj1,receptacle_shelf,11).
isshelfcolor(obj1,receptacle_shelf,12).
isshelfcolor(obj1,receptacle_shelf,13).
isshelfcolor(obj1,receptacle_shelf,14).
isshelfcolor(obj1,receptacle_shelf,15).
isshelfcolor(obj1,receptacle_shelf,16).
isshelfcolor(obj2,receptacle_shelf,10).
isshelfcolor(obj2,receptacle_shelf,11).
isshelfcolor(obj2,receptacle_shelf,12).
isshelfcolor(obj2,receptacle_shelf,13).
isshelfcolor(obj2,receptacle_shelf,14).
isshelfcolor(obj2,receptacle_shelf,15).
isshelfcolor(obj2,receptacle_shelf,16).
isshelfcolor(obj2,receptacle_shelf,7).
isshelfcolor(obj2,receptacle_shelf,8).
isshelfcolor(obj2,receptacle_shelf,9).
iswet(obj0,14).
iswet(obj1,0).
iswet(obj1,1).
iswet(obj1,2).
iswet(obj1,3).
iswet(obj1,4).
iswet(obj1,5).
iswet(obj1,6).
iswet(obj1,7).
iswet(obj1,8).
iswet(obj1,9).
iswet(obj2,0).
iswet(obj2,1).
iswet(obj2,2).
iswet(obj2,3).
iswet(obj2,4).
iswet(obj2,5).
iswet(obj3,0).
iswet(obj3,1).
negated_gripperopen(robby,1).
negated_gripperopen(robby,10).
negated_gripperopen(robby,11).
negated_gripperopen(robby,13).
negated_gripperopen(robby,14).
negated_gripperopen(robby,15).
negated_gripperopen(robby,16).
negated_gripperopen(robby,2).
negated_gripperopen(robby,3).
negated_gripperopen(robby,5).
negated_gripperopen(robby,6).
negated_gripperopen(robby,7).
negated_gripperopen(robby,9).
negated_holding(obj0,0).
negated_holding(obj0,1).
negated_holding(obj0,10).
negated_holding(obj0,11).
negated_holding(obj0,12).
negated_holding(obj0,2).
negated_holding(obj0,3).
negated_holding(obj0,4).
negated_holding(obj0,5).
negated_holding(obj0,6).
negated_holding(obj0,7).
negated_holding(obj0,8).
negated_holding(obj0,9).
negated_holding(obj1,0).
negated_holding(obj1,1).
negated_holding(obj1,12).
negated_holding(obj1,13).
negated_holding(obj1,14).
negated_holding(obj1,15).
negated_holding(obj1,16).
negated_holding(obj1,2).
negated_holding(obj1,3).
negated_holding(obj1,4).
negated_holding(obj1,5).
negated_holding(obj1,6).
negated_holding(obj1,7).
negated_holding(obj1,8).
negated_holding(obj2,0).
negated_holding(obj2,1).
negated_holding(obj2,10).
negated_holding(obj2,11).
negated_holding(obj2,12).
negated_holding(obj2,13).
negated_holding(obj2,14).
negated_holding(obj2,15).
negated_holding(obj2,16).
negated_holding(obj2,2).
negated_holding(obj2,3).
negated_holding(obj2,4).
negated_holding(obj2,8).
negated_holding(obj2,9).
negated_holding(obj3,0).
negated_holding(obj3,10).
negated_holding(obj3,11).
negated_holding(obj3,12).
negated_holding(obj3,13).
negated_holding(obj3,14).
negated_holding(obj3,15).
negated_holding(obj3,16).
negated_holding(obj3,4).
negated_holding(obj3,5).
negated_holding(obj3,6).
negated_holding(obj3,7).
negated_holding(obj3,8).
negated_holding(obj3,9).
negated_holdingside(obj0,0).
negated_holdingside(obj0,1).
negated_holdingside(obj0,10).
negated_holdingside(obj0,11).
negated_holdingside(obj0,12).
negated_holdingside(obj0,2).
negated_holdingside(obj0,3).
negated_holdingside(obj0,4).
negated_holdingside(obj0,5).
negated_holdingside(obj0,6).
negated_holdingside(obj0,7).
negated_holdingside(obj0,8).
negated_holdingside(obj0,9).
negated_holdingside(obj1,0).
negated_holdingside(obj1,1).
negated_holdingside(obj1,12).
negated_holdingside(obj1,13).
negated_holdingside(obj1,14).
negated_holdingside(obj1,15).
negated_holdingside(obj1,16).
negated_holdingside(obj1,2).
negated_holdingside(obj1,3).
negated_holdingside(obj1,4).
negated_holdingside(obj1,5).
negated_holdingside(obj1,6).
negated_holdingside(obj1,7).
negated_holdingside(obj1,8).
negated_holdingside(obj2,0).
negated_holdingside(obj2,1).
negated_holdingside(obj2,10).
negated_holdingside(obj2,11).
negated_holdingside(obj2,12).
negated_holdingside(obj2,13).
negated_holdingside(obj2,14).
negated_holdingside(obj2,15).
negated_holdingside(obj2,16).
negated_holdingside(obj2,2).
negated_holdingside(obj2,3).
negated_holdingside(obj2,4).
negated_holdingside(obj2,8).
negated_holdingside(obj2,9).
negated_holdingside(obj3,0).
negated_holdingside(obj3,1).
negated_holdingside(obj3,10).
negated_holdingside(obj3,11).
negated_holdingside(obj3,12).
negated_holdingside(obj3,13).
negated_holdingside(obj3,14).
negated_holdingside(obj3,15).
negated_holdingside(obj3,16).
negated_holdingside(obj3,2).
negated_holdingside(obj3,3).
negated_holdingside(obj3,4).
negated_holdingside(obj3,5).
negated_holdingside(obj3,6).
negated_holdingside(obj3,7).
negated_holdingside(obj3,8).
negated_holdingside(obj3,9).
negated_holdingtop(obj0,0).
negated_holdingtop(obj0,1).
negated_holdingtop(obj0,10).
negated_holdingtop(obj0,11).
negated_holdingtop(obj0,12).
negated_holdingtop(obj0,13).
negated_holdingtop(obj0,14).
negated_holdingtop(obj0,15).
negated_holdingtop(obj0,16).
negated_holdingtop(obj0,2).
negated_holdingtop(obj0,3).
negated_holdingtop(obj0,4).
negated_holdingtop(obj0,5).
negated_holdingtop(obj0,6).
negated_holdingtop(obj0,7).
negated_holdingtop(obj0,8).
negated_holdingtop(obj0,9).
negated_holdingtop(obj1,0).
negated_holdingtop(obj1,1).
negated_holdingtop(obj1,10).
negated_holdingtop(obj1,11).
negated_holdingtop(obj1,12).
negated_holdingtop(obj1,13).
negated_holdingtop(obj1,14).
negated_holdingtop(obj1,15).
negated_holdingtop(obj1,16).
negated_holdingtop(obj1,2).
negated_holdingtop(obj1,3).
negated_holdingtop(obj1,4).
negated_holdingtop(obj1,5).
negated_holdingtop(obj1,6).
negated_holdingtop(obj1,7).
negated_holdingtop(obj1,8).
negated_holdingtop(obj1,9).
negated_holdingtop(obj2,0).
negated_holdingtop(obj2,1).
negated_holdingtop(obj2,10).
negated_holdingtop(obj2,11).
negated_holdingtop(obj2,12).
negated_holdingtop(obj2,13).
negated_holdingtop(obj2,14).
negated_holdingtop(obj2,15).
negated_holdingtop(obj2,16).
negated_holdingtop(obj2,2).
negated_holdingtop(obj2,3).
negated_holdingtop(obj2,4).
negated_holdingtop(obj2,5).
negated_holdingtop(obj2,6).
negated_holdingtop(obj2,7).
negated_holdingtop(obj2,8).
negated_holdingtop(obj2,9).
negated_holdingtop(obj3,0).
negated_holdingtop(obj3,10).
negated_holdingtop(obj3,11).
negated_holdingtop(obj3,12).
negated_holdingtop(obj3,13).
negated_holdingtop(obj3,14).
negated_holdingtop(obj3,15).
negated_holdingtop(obj3,16).
negated_holdingtop(obj3,4).
negated_holdingtop(obj3,5).
negated_holdingtop(obj3,6).
negated_holdingtop(obj3,7).
negated_holdingtop(obj3,8).
negated_holdingtop(obj3,9).
negated_inbox(obj0,receptacle_box,0).
negated_inbox(obj0,receptacle_box,1).
negated_inbox(obj0,receptacle_box,10).
negated_inbox(obj0,receptacle_box,11).
negated_inbox(obj0,receptacle_box,12).
negated_inbox(obj0,receptacle_box,13).
negated_inbox(obj0,receptacle_box,14).
negated_inbox(obj0,receptacle_box,15).
negated_inbox(obj0,receptacle_box,16).
negated_inbox(obj0,receptacle_box,2).
negated_inbox(obj0,receptacle_box,3).
negated_inbox(obj0,receptacle_box,4).
negated_inbox(obj0,receptacle_box,5).
negated_inbox(obj0,receptacle_box,6).
negated_inbox(obj0,receptacle_box,7).
negated_inbox(obj0,receptacle_box,8).
negated_inbox(obj0,receptacle_box,9).
negated_inbox(obj1,receptacle_box,0).
negated_inbox(obj1,receptacle_box,1).
negated_inbox(obj1,receptacle_box,10).
negated_inbox(obj1,receptacle_box,11).
negated_inbox(obj1,receptacle_box,12).
negated_inbox(obj1,receptacle_box,13).
negated_inbox(obj1,receptacle_box,14).
negated_inbox(obj1,receptacle_box,15).
negated_inbox(obj1,receptacle_box,16).
negated_inbox(obj1,receptacle_box,2).
negated_inbox(obj1,receptacle_box,3).
negated_inbox(obj1,receptacle_box,4).
negated_inbox(obj1,receptacle_box,5).
negated_inbox(obj1,receptacle_box,6).
negated_inbox(obj1,receptacle_box,7).
negated_inbox(obj1,receptacle_box,8).
negated_inbox(obj1,receptacle_box,9).
negated_inbox(obj2,receptacle_box,0).
negated_inbox(obj2,receptacle_box,1).
negated_inbox(obj2,receptacle_box,10).
negated_inbox(obj2,receptacle_box,11).
negated_inbox(obj2,receptacle_box,12).
negated_inbox(obj2,receptacle_box,13).
negated_inbox(obj2,receptacle_box,14).
negated_inbox(obj2,receptacle_box,15).
negated_inbox(obj2,receptacle_box,16).
negated_inbox(obj2,receptacle_box,2).
negated_inbox(obj2,receptacle_box,3).
negated_inbox(obj2,receptacle_box,4).
negated_inbox(obj2,receptacle_box,5).
negated_inbox(obj2,receptacle_box,6).
negated_inbox(obj2,receptacle_box,7).
negated_inbox(obj2,receptacle_box,8).
negated_inbox(obj2,receptacle_box,9).
negated_inbox(obj3,receptacle_box,0).
negated_inbox(obj3,receptacle_box,1).
negated_inbox(obj3,receptacle_box,2).
negated_inbox(obj3,receptacle_box,3).
negated_inshelf(obj0,receptacle_shelf,0).
negated_inshelf(obj0,receptacle_shelf,1).
negated_inshelf(obj0,receptacle_shelf,10).
negated_inshelf(obj0,receptacle_shelf,11).
negated_inshelf(obj0,receptacle_shelf,12).
negated_inshelf(obj0,receptacle_shelf,13).
negated_inshelf(obj0,receptacle_shelf,14).
negated_inshelf(obj0,receptacle_shelf,15).
negated_inshelf(obj0,receptacle_shelf,16).
negated_inshelf(obj0,receptacle_shelf,2).
negated_inshelf(obj0,receptacle_shelf,3).
negated_inshelf(obj0,receptacle_shelf,4).
negated_inshelf(obj0,receptacle_shelf,5).
negated_inshelf(obj0,receptacle_shelf,6).
negated_inshelf(obj0,receptacle_shelf,7).
negated_inshelf(obj0,receptacle_shelf,8).
negated_inshelf(obj0,receptacle_shelf,9).
negated_inshelf(obj1,receptacle_shelf,0).
negated_inshelf(obj1,receptacle_shelf,1).
negated_inshelf(obj1,receptacle_shelf,10).
negated_inshelf(obj1,receptacle_shelf,11).
negated_inshelf(obj1,receptacle_shelf,2).
negated_inshelf(obj1,receptacle_shelf,3).
negated_inshelf(obj1,receptacle_shelf,4).
negated_inshelf(obj1,receptacle_shelf,5).
negated_inshelf(obj1,receptacle_shelf,6).
negated_inshelf(obj1,receptacle_shelf,7).
negated_inshelf(obj1,receptacle_shelf,8).
negated_inshelf(obj1,receptacle_shelf,9).
negated_inshelf(obj2,receptacle_shelf,0).
negated_inshelf(obj2,receptacle_shelf,1).
negated_inshelf(obj2,receptacle_shelf,2).
negated_inshelf(obj2,receptacle_shelf,3).
negated_inshelf(obj2,receptacle_shelf,4).
negated_inshelf(obj2,receptacle_shelf,5).
negated_inshelf(obj2,receptacle_shelf,6).
negated_inshelf(obj2,receptacle_shelf,7).
negated_inshelf(obj3,receptacle_shelf,0).
negated_inshelf(obj3,receptacle_shelf,1).
negated_inshelf(obj3,receptacle_shelf,10).
negated_inshelf(obj3,receptacle_shelf,11).
negated_inshelf(obj3,receptacle_shelf,12).
negated_inshelf(obj3,receptacle_shelf,13).
negated_inshelf(obj3,receptacle_shelf,14).
negated_inshelf(obj3,receptacle_shelf,15).
negated_inshelf(obj3,receptacle_shelf,16).
negated_inshelf(obj3,receptacle_shelf,2).
negated_inshelf(obj3,receptacle_shelf,3).
negated_inshelf(obj3,receptacle_shelf,4).
negated_inshelf(obj3,receptacle_shelf,5).
negated_inshelf(obj3,receptacle_shelf,6).
negated_inshelf(obj3,receptacle_shelf,7).
negated_inshelf(obj3,receptacle_shelf,8).
negated_inshelf(obj3,receptacle_shelf,9).
negated_isboxcolor(obj0,receptacle_box,0).
negated_isboxcolor(obj0,receptacle_box,1).
negated_isboxcolor(obj0,receptacle_box,10).
negated_isboxcolor(obj0,receptacle_box,11).
negated_isboxcolor(obj0,receptacle_box,12).
negated_isboxcolor(obj0,receptacle_box,13).
negated_isboxcolor(obj0,receptacle_box,14).
negated_isboxcolor(obj0,receptacle_box,15).
negated_isboxcolor(obj0,receptacle_box,16).
negated_isboxcolor(obj0,receptacle_box,2).
negated_isboxcolor(obj0,receptacle_box,3).
negated_isboxcolor(obj0,receptacle_box,4).
negated_isboxcolor(obj0,receptacle_box,5).
negated_isboxcolor(obj0,receptacle_box,6).
negated_isboxcolor(obj0,receptacle_box,7).
negated_isboxcolor(obj0,receptacle_box,8).
negated_isboxcolor(obj0,receptacle_box,9).
negated_isboxcolor(obj1,receptacle_box,0).
negated_isboxcolor(obj1,receptacle_box,1).
negated_isboxcolor(obj1,receptacle_box,10).
negated_isboxcolor(obj1,receptacle_box,11).
negated_isboxcolor(obj1,receptacle_box,12).
negated_isboxcolor(obj1,receptacle_box,13).
negated_isboxcolor(obj1,receptacle_box,14).
negated_isboxcolor(obj1,receptacle_box,15).
negated_isboxcolor(obj1,receptacle_box,16).
negated_isboxcolor(obj1,receptacle_box,2).
negated_isboxcolor(obj1,receptacle_box,3).
negated_isboxcolor(obj1,receptacle_box,4).
negated_isboxcolor(obj1,receptacle_box,5).
negated_isboxcolor(obj1,receptacle_box,6).
negated_isboxcolor(obj1,receptacle_box,7).
negated_isboxcolor(obj1,receptacle_box,8).
negated_isboxcolor(obj1,receptacle_box,9).
negated_isboxcolor(obj2,receptacle_box,0).
negated_isboxcolor(obj2,receptacle_box,1).
negated_isboxcolor(obj2,receptacle_box,10).
negated_isboxcolor(obj2,receptacle_box,11).
negated_isboxcolor(obj2,receptacle_box,12).
negated_isboxcolor(obj2,receptacle_box,13).
negated_isboxcolor(obj2,receptacle_box,14).
negated_isboxcolor(obj2,receptacle_box,15).
negated_isboxcolor(obj2,receptacle_box,16).
negated_isboxcolor(obj2,receptacle_box,2).
negated_isboxcolor(obj2,receptacle_box,3).
negated_isboxcolor(obj2,receptacle_box,4).
negated_isboxcolor(obj2,receptacle_box,5).
negated_isboxcolor(obj2,receptacle_box,6).
negated_isboxcolor(obj2,receptacle_box,7).
negated_isboxcolor(obj2,receptacle_box,8).
negated_isboxcolor(obj2,receptacle_box,9).
negated_isboxcolor(obj3,receptacle_box,0).
negated_isboxcolor(obj3,receptacle_box,1).
negated_isboxcolor(obj3,receptacle_box,2).
negated_isclean(obj0,0).
negated_isclean(obj0,1).
negated_isclean(obj0,10).
negated_isclean(obj0,11).
negated_isclean(obj0,12).
negated_isclean(obj0,13).
negated_isclean(obj0,2).
negated_isclean(obj0,3).
negated_isclean(obj0,4).
negated_isclean(obj0,5).
negated_isclean(obj0,6).
negated_isclean(obj0,7).
negated_isclean(obj0,8).
negated_isclean(obj0,9).
negated_isdirty(obj0,14).
negated_isdirty(obj0,15).
negated_isdirty(obj0,16).
negated_isdirty(obj1,0).
negated_isdirty(obj1,1).
negated_isdirty(obj1,10).
negated_isdirty(obj1,11).
negated_isdirty(obj1,12).
negated_isdirty(obj1,13).
negated_isdirty(obj1,14).
negated_isdirty(obj1,15).
negated_isdirty(obj1,16).
negated_isdirty(obj1,2).
negated_isdirty(obj1,3).
negated_isdirty(obj1,4).
negated_isdirty(obj1,5).
negated_isdirty(obj1,6).
negated_isdirty(obj1,7).
negated_isdirty(obj1,8).
negated_isdirty(obj1,9).
negated_isdirty(obj2,0).
negated_isdirty(obj2,1).
negated_isdirty(obj2,10).
negated_isdirty(obj2,11).
negated_isdirty(obj2,12).
negated_isdirty(obj2,13).
negated_isdirty(obj2,14).
negated_isdirty(obj2,15).
negated_isdirty(obj2,16).
negated_isdirty(obj2,2).
negated_isdirty(obj2,3).
negated_isdirty(obj2,4).
negated_isdirty(obj2,5).
negated_isdirty(obj2,6).
negated_isdirty(obj2,7).
negated_isdirty(obj2,8).
negated_isdirty(obj2,9).
negated_isdirty(obj3,0).
negated_isdirty(obj3,1).
negated_isdirty(obj3,10).
negated_isdirty(obj3,11).
negated_isdirty(obj3,12).
negated_isdirty(obj3,13).
negated_isdirty(obj3,14).
negated_isdirty(obj3,15).
negated_isdirty(obj3,16).
negated_isdirty(obj3,2).
negated_isdirty(obj3,3).
negated_isdirty(obj3,4).
negated_isdirty(obj3,5).
negated_isdirty(obj3,6).
negated_isdirty(obj3,7).
negated_isdirty(obj3,8).
negated_isdirty(obj3,9).
negated_isdry(obj0,14).
negated_isdry(obj1,0).
negated_isdry(obj1,1).
negated_isdry(obj1,2).
negated_isdry(obj1,3).
negated_isdry(obj1,4).
negated_isdry(obj1,5).
negated_isdry(obj1,6).
negated_isdry(obj1,7).
negated_isdry(obj1,8).
negated_isdry(obj1,9).
negated_isdry(obj2,0).
negated_isdry(obj2,1).
negated_isdry(obj2,2).
negated_isdry(obj2,3).
negated_isdry(obj2,4).
negated_isdry(obj2,5).
negated_isdry(obj3,0).
negated_isdry(obj3,1).
negated_isshelfcolor(obj0,receptacle_shelf,0).
negated_isshelfcolor(obj0,receptacle_shelf,1).
negated_isshelfcolor(obj0,receptacle_shelf,10).
negated_isshelfcolor(obj0,receptacle_shelf,11).
negated_isshelfcolor(obj0,receptacle_shelf,12).
negated_isshelfcolor(obj0,receptacle_shelf,13).
negated_isshelfcolor(obj0,receptacle_shelf,14).
negated_isshelfcolor(obj0,receptacle_shelf,15).
negated_isshelfcolor(obj0,receptacle_shelf,2).
negated_isshelfcolor(obj0,receptacle_shelf,3).
negated_isshelfcolor(obj0,receptacle_shelf,4).
negated_isshelfcolor(obj0,receptacle_shelf,5).
negated_isshelfcolor(obj0,receptacle_shelf,6).
negated_isshelfcolor(obj0,receptacle_shelf,7).
negated_isshelfcolor(obj0,receptacle_shelf,8).
negated_isshelfcolor(obj0,receptacle_shelf,9).
negated_isshelfcolor(obj1,receptacle_shelf,0).
negated_isshelfcolor(obj1,receptacle_shelf,1).
negated_isshelfcolor(obj1,receptacle_shelf,10).
negated_isshelfcolor(obj1,receptacle_shelf,2).
negated_isshelfcolor(obj1,receptacle_shelf,3).
negated_isshelfcolor(obj1,receptacle_shelf,4).
negated_isshelfcolor(obj1,receptacle_shelf,5).
negated_isshelfcolor(obj1,receptacle_shelf,6).
negated_isshelfcolor(obj1,receptacle_shelf,7).
negated_isshelfcolor(obj1,receptacle_shelf,8).
negated_isshelfcolor(obj1,receptacle_shelf,9).
negated_isshelfcolor(obj2,receptacle_shelf,0).
negated_isshelfcolor(obj2,receptacle_shelf,1).
negated_isshelfcolor(obj2,receptacle_shelf,2).
negated_isshelfcolor(obj2,receptacle_shelf,3).
negated_isshelfcolor(obj2,receptacle_shelf,4).
negated_isshelfcolor(obj2,receptacle_shelf,5).
negated_isshelfcolor(obj2,receptacle_shelf,6).
negated_isshelfcolor(obj3,receptacle_shelf,0).
negated_isshelfcolor(obj3,receptacle_shelf,1).
negated_isshelfcolor(obj3,receptacle_shelf,10).
negated_isshelfcolor(obj3,receptacle_shelf,11).
negated_isshelfcolor(obj3,receptacle_shelf,12).
negated_isshelfcolor(obj3,receptacle_shelf,13).
negated_isshelfcolor(obj3,receptacle_shelf,14).
negated_isshelfcolor(obj3,receptacle_shelf,15).
negated_isshelfcolor(obj3,receptacle_shelf,16).
negated_isshelfcolor(obj3,receptacle_shelf,2).
negated_isshelfcolor(obj3,receptacle_shelf,3).
negated_isshelfcolor(obj3,receptacle_shelf,4).
negated_isshelfcolor(obj3,receptacle_shelf,5).
negated_isshelfcolor(obj3,receptacle_shelf,6).
negated_isshelfcolor(obj3,receptacle_shelf,7).
negated_isshelfcolor(obj3,receptacle_shelf,8).
negated_isshelfcolor(obj3,receptacle_shelf,9).
negated_iswet(obj0,0).
negated_iswet(obj0,1).
negated_iswet(obj0,10).
negated_iswet(obj0,11).
negated_iswet(obj0,12).
negated_iswet(obj0,13).
negated_iswet(obj0,15).
negated_iswet(obj0,16).
negated_iswet(obj0,2).
negated_iswet(obj0,3).
negated_iswet(obj0,4).
negated_iswet(obj0,5).
negated_iswet(obj0,6).
negated_iswet(obj0,7).
negated_iswet(obj0,8).
negated_iswet(obj0,9).
negated_iswet(obj1,10).
negated_iswet(obj1,11).
negated_iswet(obj1,12).
negated_iswet(obj1,13).
negated_iswet(obj1,14).
negated_iswet(obj1,15).
negated_iswet(obj1,16).
negated_iswet(obj2,10).
negated_iswet(obj2,11).
negated_iswet(obj2,12).
negated_iswet(obj2,13).
negated_iswet(obj2,14).
negated_iswet(obj2,15).
negated_iswet(obj2,16).
negated_iswet(obj2,6).
negated_iswet(obj2,7).
negated_iswet(obj2,8).
negated_iswet(obj2,9).
negated_iswet(obj3,10).
negated_iswet(obj3,11).
negated_iswet(obj3,12).
negated_iswet(obj3,13).
negated_iswet(obj3,14).
negated_iswet(obj3,15).
negated_iswet(obj3,16).
negated_iswet(obj3,2).
negated_iswet(obj3,3).
negated_iswet(obj3,4).
negated_iswet(obj3,5).
negated_iswet(obj3,6).
negated_iswet(obj3,7).
negated_iswet(obj3,8).
negated_iswet(obj3,9).
negated_notontable(obj0,0).
negated_notontable(obj0,1).
negated_notontable(obj0,10).
negated_notontable(obj0,11).
negated_notontable(obj0,12).
negated_notontable(obj0,13).
negated_notontable(obj0,14).
negated_notontable(obj0,15).
negated_notontable(obj0,16).
negated_notontable(obj0,2).
negated_notontable(obj0,3).
negated_notontable(obj0,4).
negated_notontable(obj0,5).
negated_notontable(obj0,6).
negated_notontable(obj0,7).
negated_notontable(obj0,8).
negated_notontable(obj0,9).
negated_notontable(obj1,0).
negated_notontable(obj1,1).
negated_notontable(obj1,10).
negated_notontable(obj1,11).
negated_notontable(obj1,2).
negated_notontable(obj1,3).
negated_notontable(obj1,4).
negated_notontable(obj1,5).
negated_notontable(obj1,6).
negated_notontable(obj1,7).
negated_notontable(obj1,8).
negated_notontable(obj1,9).
negated_notontable(obj2,0).
negated_notontable(obj2,1).
negated_notontable(obj2,2).
negated_notontable(obj2,3).
negated_notontable(obj2,4).
negated_notontable(obj2,5).
negated_notontable(obj2,6).
negated_notontable(obj2,7).
negated_notontable(obj3,0).
negated_notontable(obj3,1).
negated_notontable(obj3,2).
negated_notontable(obj3,3).
negated_ontable(obj1,12).
negated_ontable(obj1,13).
negated_ontable(obj1,14).
negated_ontable(obj1,15).
negated_ontable(obj1,16).
negated_ontable(obj2,10).
negated_ontable(obj2,11).
negated_ontable(obj2,12).
negated_ontable(obj2,13).
negated_ontable(obj2,14).
negated_ontable(obj2,15).
negated_ontable(obj2,16).
negated_ontable(obj2,8).
negated_ontable(obj2,9).
negated_ontable(obj3,10).
negated_ontable(obj3,11).
negated_ontable(obj3,12).
negated_ontable(obj3,13).
negated_ontable(obj3,14).
negated_ontable(obj3,15).
negated_ontable(obj3,16).
negated_ontable(obj3,4).
negated_ontable(obj3,5).
negated_ontable(obj3,6).
negated_ontable(obj3,7).
negated_ontable(obj3,8).
negated_ontable(obj3,9).
notontable(obj1,12).
notontable(obj1,13).
notontable(obj1,14).
notontable(obj1,15).
notontable(obj1,16).
notontable(obj2,10).
notontable(obj2,11).
notontable(obj2,12).
notontable(obj2,13).
notontable(obj2,14).
notontable(obj2,15).
notontable(obj2,16).
notontable(obj2,8).
notontable(obj2,9).
notontable(obj3,10).
notontable(obj3,11).
notontable(obj3,12).
notontable(obj3,13).
notontable(obj3,14).
notontable(obj3,15).
notontable(obj3,16).
notontable(obj3,4).
notontable(obj3,5).
notontable(obj3,6).
notontable(obj3,7).
notontable(obj3,8).
notontable(obj3,9).
ontable(obj0,0).
ontable(obj0,1).
ontable(obj0,10).
ontable(obj0,11).
ontable(obj0,12).
ontable(obj0,13).
ontable(obj0,14).
ontable(obj0,15).
ontable(obj0,16).
ontable(obj0,2).
ontable(obj0,3).
ontable(obj0,4).
ontable(obj0,5).
ontable(obj0,6).
ontable(obj0,7).
ontable(obj0,8).
ontable(obj0,9).
ontable(obj1,0).
ontable(obj1,1).
ontable(obj1,10).
ontable(obj1,11).
ontable(obj1,2).
ontable(obj1,3).
ontable(obj1,4).
ontable(obj1,5).
ontable(obj1,6).
ontable(obj1,7).
ontable(obj1,8).
ontable(obj1,9).
ontable(obj2,0).
ontable(obj2,1).
ontable(obj2,2).
ontable(obj2,3).
ontable(obj2,4).
ontable(obj2,5).
ontable(obj2,6).
ontable(obj2,7).
ontable(obj3,0).
ontable(obj3,1).
ontable(obj3,2).
ontable(obj3,3).
