% Positive examples
pos(placeinshelf(obj0,receptacle_shelf,robby,16)).
pos(placeinshelf(obj1,receptacle_shelf,robby,11)).
pos(placeinshelf(obj2,receptacle_shelf,robby,7)).

% Negative examples
neg(placeinshelf(obj0,receptacle_shelf,robby,0)).
neg(placeinshelf(obj0,receptacle_shelf,robby,1)).
neg(placeinshelf(obj0,receptacle_shelf,robby,10)).
neg(placeinshelf(obj0,receptacle_shelf,robby,11)).
neg(placeinshelf(obj0,receptacle_shelf,robby,12)).
neg(placeinshelf(obj0,receptacle_shelf,robby,13)).
neg(placeinshelf(obj0,receptacle_shelf,robby,14)).
neg(placeinshelf(obj0,receptacle_shelf,robby,15)).
neg(placeinshelf(obj0,receptacle_shelf,robby,2)).
neg(placeinshelf(obj0,receptacle_shelf,robby,3)).
neg(placeinshelf(obj0,receptacle_shelf,robby,4)).
neg(placeinshelf(obj0,receptacle_shelf,robby,5)).
neg(placeinshelf(obj0,receptacle_shelf,robby,6)).
neg(placeinshelf(obj0,receptacle_shelf,robby,7)).
neg(placeinshelf(obj0,receptacle_shelf,robby,8)).
neg(placeinshelf(obj0,receptacle_shelf,robby,9)).
neg(placeinshelf(obj1,receptacle_shelf,robby,0)).
neg(placeinshelf(obj1,receptacle_shelf,robby,1)).
neg(placeinshelf(obj1,receptacle_shelf,robby,10)).
neg(placeinshelf(obj1,receptacle_shelf,robby,12)).
neg(placeinshelf(obj1,receptacle_shelf,robby,13)).
neg(placeinshelf(obj1,receptacle_shelf,robby,14)).
neg(placeinshelf(obj1,receptacle_shelf,robby,15)).
neg(placeinshelf(obj1,receptacle_shelf,robby,16)).
neg(placeinshelf(obj1,receptacle_shelf,robby,2)).
neg(placeinshelf(obj1,receptacle_shelf,robby,3)).
neg(placeinshelf(obj1,receptacle_shelf,robby,4)).
neg(placeinshelf(obj1,receptacle_shelf,robby,5)).
neg(placeinshelf(obj1,receptacle_shelf,robby,6)).
neg(placeinshelf(obj1,receptacle_shelf,robby,7)).
neg(placeinshelf(obj1,receptacle_shelf,robby,8)).
neg(placeinshelf(obj1,receptacle_shelf,robby,9)).
neg(placeinshelf(obj2,receptacle_shelf,robby,0)).
neg(placeinshelf(obj2,receptacle_shelf,robby,1)).
neg(placeinshelf(obj2,receptacle_shelf,robby,10)).
neg(placeinshelf(obj2,receptacle_shelf,robby,11)).
neg(placeinshelf(obj2,receptacle_shelf,robby,12)).
neg(placeinshelf(obj2,receptacle_shelf,robby,13)).
neg(placeinshelf(obj2,receptacle_shelf,robby,14)).
neg(placeinshelf(obj2,receptacle_shelf,robby,15)).
neg(placeinshelf(obj2,receptacle_shelf,robby,16)).
neg(placeinshelf(obj2,receptacle_shelf,robby,2)).
neg(placeinshelf(obj2,receptacle_shelf,robby,3)).
neg(placeinshelf(obj2,receptacle_shelf,robby,4)).
neg(placeinshelf(obj2,receptacle_shelf,robby,5)).
neg(placeinshelf(obj2,receptacle_shelf,robby,6)).
neg(placeinshelf(obj2,receptacle_shelf,robby,8)).
neg(placeinshelf(obj2,receptacle_shelf,robby,9)).
neg(placeinshelf(obj3,receptacle_shelf,robby,0)).
neg(placeinshelf(obj3,receptacle_shelf,robby,1)).
neg(placeinshelf(obj3,receptacle_shelf,robby,10)).
neg(placeinshelf(obj3,receptacle_shelf,robby,11)).
neg(placeinshelf(obj3,receptacle_shelf,robby,12)).
neg(placeinshelf(obj3,receptacle_shelf,robby,13)).
neg(placeinshelf(obj3,receptacle_shelf,robby,14)).
neg(placeinshelf(obj3,receptacle_shelf,robby,15)).
neg(placeinshelf(obj3,receptacle_shelf,robby,16)).
neg(placeinshelf(obj3,receptacle_shelf,robby,2)).
neg(placeinshelf(obj3,receptacle_shelf,robby,3)).
neg(placeinshelf(obj3,receptacle_shelf,robby,4)).
neg(placeinshelf(obj3,receptacle_shelf,robby,5)).
neg(placeinshelf(obj3,receptacle_shelf,robby,6)).
neg(placeinshelf(obj3,receptacle_shelf,robby,7)).
neg(placeinshelf(obj3,receptacle_shelf,robby,8)).
neg(placeinshelf(obj3,receptacle_shelf,robby,9)).
