head_pred(modinstfield, 3).
body_pred(mgetinstfldinst, 4).
body_pred(mputinstfldinst, 4).
body_pred(mgetstatfldinst, 3).
body_pred(mputstatfldinst, 3).
body_pred(vh, 2).
body_pred(mi, 2).
body_pred(im, 2).
body_pred(rmm, 2).
body_pred(refstatfield, 2).
body_pred(modstatfield, 2).
body_pred(refinstfield, 3).
