pos(rmm(m0,m1)).
pos(rmm(m0,m2)).
pos(rmm(m0,m3)).
pos(rmm(m0,m4)).
pos(rmm(m1,m2)).
pos(rmm(m1,m3)).
pos(rmm(m1,m4)).
pos(rmm(m2,m3)).
pos(rmm(m2,m4)).
pos(rmm(m3,m4)).
pos(refstatfield(m0,f0)).
pos(refstatfield(m1,f0)).
pos(refstatfield(m2,f0)).
pos(refstatfield(m3,f0)).
pos(refstatfield(m4,f0)).
pos(refstatfield(m8,f8)).
pos(refstatfield(m10,f10)).
pos(modstatfield(m0,f1)).
pos(modstatfield(m1,f1)).
pos(modstatfield(m2,f1)).
pos(modstatfield(m3,f1)).
pos(modstatfield(m4,f1)).
pos(modstatfield(m9,f9)).
pos(modstatfield(m10,f10)).
pos(refinstfield(m0,h2,f2)).
pos(refinstfield(m1,h2,f2)).
pos(refinstfield(m2,h2,f2)).
pos(refinstfield(m3,h2,f2)).
pos(refinstfield(m4,h2,f2)).
pos(modinstfield(m0,h4,f4)).
pos(modinstfield(m1,h4,f4)).
pos(modinstfield(m2,h4,f4)).
pos(modinstfield(m3,h4,f4)).
pos(modinstfield(m4,h4,f4)).
