at(ball1,rooma,0).
at(ball1,rooma,1).
at(ball1,rooma,2).
at(ball1,rooma,3).
at(ball1,rooma,4).
at(ball2,rooma,0).
at(ball2,roomb,3).
at(ball2,roomb,4).
at(ball2,roomb,5).
at(ball2,roomb,6).
at_robby(rooma,0).
at_robby(rooma,1).
at_robby(rooma,4).
at_robby(rooma,5).
at_robby(roomb,2).
at_robby(roomb,3).
at_robby(roomb,6).
ball(ball1,0).
ball(ball1,1).
ball(ball1,2).
ball(ball1,3).
ball(ball1,4).
ball(ball1,5).
ball(ball1,6).
ball(ball2,0).
ball(ball2,1).
ball(ball2,2).
ball(ball2,3).
ball(ball2,4).
ball(ball2,5).
ball(ball2,6).
carry(ball1,left,5).
carry(ball1,left,6).
carry(ball2,left,1).
carry(ball2,left,2).
free(left,0).
free(left,3).
free(left,4).
goal_at(ball1,roomb,0).
goal_at(ball1,roomb,1).
goal_at(ball1,roomb,2).
goal_at(ball1,roomb,3).
goal_at(ball1,roomb,4).
goal_at(ball1,roomb,5).
goal_at(ball1,roomb,6).
goal_at(ball2,roomb,0).
goal_at(ball2,roomb,1).
goal_at(ball2,roomb,2).
goal_at(ball2,roomb,3).
goal_at(ball2,roomb,4).
goal_at(ball2,roomb,5).
goal_at(ball2,roomb,6).
gripper(left,0).
gripper(left,1).
gripper(left,2).
gripper(left,3).
gripper(left,4).
gripper(left,5).
gripper(left,6).
negated_at(ball1,rooma,5).
negated_at(ball1,rooma,6).
negated_at(ball1,roomb,0).
negated_at(ball1,roomb,1).
negated_at(ball1,roomb,2).
negated_at(ball1,roomb,3).
negated_at(ball1,roomb,4).
negated_at(ball1,roomb,5).
negated_at(ball1,roomb,6).
negated_at(ball2,rooma,1).
negated_at(ball2,rooma,2).
negated_at(ball2,rooma,3).
negated_at(ball2,rooma,4).
negated_at(ball2,rooma,5).
negated_at(ball2,rooma,6).
negated_at(ball2,roomb,0).
negated_at(ball2,roomb,1).
negated_at(ball2,roomb,2).
negated_at_robby(rooma,2).
negated_at_robby(rooma,3).
negated_at_robby(rooma,6).
negated_at_robby(roomb,0).
negated_at_robby(roomb,1).
negated_at_robby(roomb,4).
negated_at_robby(roomb,5).
negated_carry(ball1,left,0).
negated_carry(ball1,left,1).
negated_carry(ball1,left,2).
negated_carry(ball1,left,3).
negated_carry(ball1,left,4).
negated_carry(ball2,left,0).
negated_carry(ball2,left,3).
negated_carry(ball2,left,4).
negated_carry(ball2,left,5).
negated_carry(ball2,left,6).
negated_free(left,1).
negated_free(left,2).
negated_free(left,5).
negated_free(left,6).
room(rooma,0).
room(rooma,1).
room(rooma,2).
room(rooma,3).
room(rooma,4).
room(rooma,5).
room(rooma,6).
room(roomb,0).
room(roomb,1).
room(roomb,2).
room(roomb,3).
room(roomb,4).
room(roomb,5).
room(roomb,6).