neg(legal(1,black, continue)).
neg(legal(1,black, finish)).
neg(legal(1,white, noop)).
neg(legal(10,black, continue)).
neg(legal(10,black, finish)).
neg(legal(10,white, noop)).
neg(legal(2,black, noop)).
neg(legal(2,white, continue)).
neg(legal(2,white, finish)).
neg(legal(3,black, continue)).
neg(legal(3,black, finish)).
neg(legal(3,white, noop)).
neg(legal(4,black, noop)).
neg(legal(4,white, continue)).
neg(legal(4,white, finish)).
neg(legal(5,black, continue)).
neg(legal(5,black, finish)).
neg(legal(5,white, noop)).
neg(legal(6,black, continue)).
neg(legal(6,black, finish)).
neg(legal(6,white, noop)).
neg(legal(7,black, noop)).
neg(legal(7,white, continue)).
neg(legal(7,white, finish)).
neg(legal(8,black, noop)).
neg(legal(8,white, continue)).
neg(legal(8,white, finish)).
neg(legal(9,black, noop)).
neg(legal(9,white, continue)).
neg(legal(9,white, finish)).
pos(legal(1,black, noop)).
pos(legal(1,white, continue)).
pos(legal(1,white, finish)).
pos(legal(10,black, noop)).
pos(legal(10,white, continue)).
pos(legal(10,white, finish)).
pos(legal(2,black, continue)).
pos(legal(2,black, finish)).
pos(legal(2,white, noop)).
pos(legal(3,black, noop)).
pos(legal(3,white, continue)).
pos(legal(3,white, finish)).
pos(legal(4,black, continue)).
pos(legal(4,black, finish)).
pos(legal(4,white, noop)).
pos(legal(5,black, noop)).
pos(legal(5,white, continue)).
pos(legal(5,white, finish)).
pos(legal(6,black, noop)).
pos(legal(6,white, continue)).
pos(legal(6,white, finish)).
pos(legal(7,black, continue)).
pos(legal(7,black, finish)).
pos(legal(7,white, noop)).
pos(legal(8,black, continue)).
pos(legal(8,black, finish)).
pos(legal(8,white, noop)).
pos(legal(9,black, continue)).
pos(legal(9,black, finish)).
pos(legal(9,white, noop)).