% Positive examples
pos(painttobox(obj3,receptacle_box,robby,2)).

% Negative examples
neg(painttobox(obj0,receptacle_box,robby,0)).
neg(painttobox(obj0,receptacle_box,robby,1)).
neg(painttobox(obj0,receptacle_box,robby,10)).
neg(painttobox(obj0,receptacle_box,robby,11)).
neg(painttobox(obj0,receptacle_box,robby,12)).
neg(painttobox(obj0,receptacle_box,robby,13)).
neg(painttobox(obj0,receptacle_box,robby,14)).
neg(painttobox(obj0,receptacle_box,robby,15)).
neg(painttobox(obj0,receptacle_box,robby,16)).
neg(painttobox(obj0,receptacle_box,robby,2)).
neg(painttobox(obj0,receptacle_box,robby,3)).
neg(painttobox(obj0,receptacle_box,robby,4)).
neg(painttobox(obj0,receptacle_box,robby,5)).
neg(painttobox(obj0,receptacle_box,robby,6)).
neg(painttobox(obj0,receptacle_box,robby,7)).
neg(painttobox(obj0,receptacle_box,robby,8)).
neg(painttobox(obj0,receptacle_box,robby,9)).
neg(painttobox(obj1,receptacle_box,robby,0)).
neg(painttobox(obj1,receptacle_box,robby,1)).
neg(painttobox(obj1,receptacle_box,robby,10)).
neg(painttobox(obj1,receptacle_box,robby,11)).
neg(painttobox(obj1,receptacle_box,robby,12)).
neg(painttobox(obj1,receptacle_box,robby,13)).
neg(painttobox(obj1,receptacle_box,robby,14)).
neg(painttobox(obj1,receptacle_box,robby,15)).
neg(painttobox(obj1,receptacle_box,robby,16)).
neg(painttobox(obj1,receptacle_box,robby,2)).
neg(painttobox(obj1,receptacle_box,robby,3)).
neg(painttobox(obj1,receptacle_box,robby,4)).
neg(painttobox(obj1,receptacle_box,robby,5)).
neg(painttobox(obj1,receptacle_box,robby,6)).
neg(painttobox(obj1,receptacle_box,robby,7)).
neg(painttobox(obj1,receptacle_box,robby,8)).
neg(painttobox(obj1,receptacle_box,robby,9)).
neg(painttobox(obj2,receptacle_box,robby,0)).
neg(painttobox(obj2,receptacle_box,robby,1)).
neg(painttobox(obj2,receptacle_box,robby,10)).
neg(painttobox(obj2,receptacle_box,robby,11)).
neg(painttobox(obj2,receptacle_box,robby,12)).
neg(painttobox(obj2,receptacle_box,robby,13)).
neg(painttobox(obj2,receptacle_box,robby,14)).
neg(painttobox(obj2,receptacle_box,robby,15)).
neg(painttobox(obj2,receptacle_box,robby,16)).
neg(painttobox(obj2,receptacle_box,robby,2)).
neg(painttobox(obj2,receptacle_box,robby,3)).
neg(painttobox(obj2,receptacle_box,robby,4)).
neg(painttobox(obj2,receptacle_box,robby,5)).
neg(painttobox(obj2,receptacle_box,robby,6)).
neg(painttobox(obj2,receptacle_box,robby,7)).
neg(painttobox(obj2,receptacle_box,robby,8)).
neg(painttobox(obj2,receptacle_box,robby,9)).
neg(painttobox(obj3,receptacle_box,robby,0)).
neg(painttobox(obj3,receptacle_box,robby,1)).
neg(painttobox(obj3,receptacle_box,robby,10)).
neg(painttobox(obj3,receptacle_box,robby,11)).
neg(painttobox(obj3,receptacle_box,robby,12)).
neg(painttobox(obj3,receptacle_box,robby,13)).
neg(painttobox(obj3,receptacle_box,robby,14)).
neg(painttobox(obj3,receptacle_box,robby,15)).
neg(painttobox(obj3,receptacle_box,robby,16)).
neg(painttobox(obj3,receptacle_box,robby,3)).
neg(painttobox(obj3,receptacle_box,robby,4)).
neg(painttobox(obj3,receptacle_box,robby,5)).
neg(painttobox(obj3,receptacle_box,robby,6)).
neg(painttobox(obj3,receptacle_box,robby,7)).
neg(painttobox(obj3,receptacle_box,robby,8)).
neg(painttobox(obj3,receptacle_box,robby,9)).
