junior(jr).
focus(faculty1).
class(class1,f1).
class(class2,f2).
class(class3,f1).
class(class4,f3).
class(class5,f4).
enroll(s1,class1).
enroll(s2,class1).
enroll(s3,class2).
enroll(s3,class5).
enroll(s4,class2).
enroll(s4,class4).
enroll(s5,class3).
enroll(s6,class3).
enroll(s6,class2).
enroll(s7,class5).
enroll(s8,class4).
faculty(f1,faculty1).
faculty(f2,faculty2).
faculty(f3,faculty3).
faculty(f4,faculty4).
student(s1,stu1,jr).
student(s2,stu2,sr).
student(s3,stu3,jr).
student(s4,stu4,sr).
student(s5,stu5,jr).
student(s6,stu6,sr).
student(s7,stu7,jr).
student(s8,stu8,jr).