customercity(1,london).
customercity(2,paris).
customercity(3,san_francisco).
customercity(4,munich).
customercity(5,seoul).
hasordered(1,1).
hasordered(2,2).
hasordered(3,3).
hasordered(4,4).
hasordered(5,5).
productname(1,tea).
productname(2,bread).
productname(3,flowers).
productname(4,sausage).
productname(5,horse).