neg(next_control(1,blue)).
neg(next_control(1,green)).
neg(next_control(10,green)).
neg(next_control(10,red)).
neg(next_control(100,blue)).
neg(next_control(100,green)).
neg(next_control(101,blue)).
neg(next_control(101,green)).
neg(next_control(102,green)).
neg(next_control(102,red)).
neg(next_control(103,green)).
neg(next_control(103,red)).
neg(next_control(104,green)).
neg(next_control(104,red)).
neg(next_control(105,blue)).
neg(next_control(105,red)).
neg(next_control(106,blue)).
neg(next_control(106,red)).
neg(next_control(107,blue)).
neg(next_control(107,red)).
neg(next_control(108,green)).
neg(next_control(108,red)).
neg(next_control(109,green)).
neg(next_control(109,red)).
neg(next_control(11,blue)).
neg(next_control(11,red)).
neg(next_control(110,blue)).
neg(next_control(110,green)).
neg(next_control(111,blue)).
neg(next_control(111,red)).
neg(next_control(112,blue)).
neg(next_control(112,green)).
neg(next_control(113,green)).
neg(next_control(113,red)).
neg(next_control(114,blue)).
neg(next_control(114,red)).
neg(next_control(115,blue)).
neg(next_control(115,red)).
neg(next_control(116,blue)).
neg(next_control(116,red)).
neg(next_control(117,blue)).
neg(next_control(117,green)).
neg(next_control(118,blue)).
neg(next_control(118,green)).
neg(next_control(119,green)).
neg(next_control(119,red)).
neg(next_control(12,blue)).
neg(next_control(12,green)).
neg(next_control(120,green)).
neg(next_control(120,red)).
neg(next_control(121,blue)).
neg(next_control(121,red)).
neg(next_control(122,green)).
neg(next_control(122,red)).
neg(next_control(123,blue)).
neg(next_control(123,green)).
neg(next_control(124,blue)).
neg(next_control(124,red)).
neg(next_control(125,blue)).
neg(next_control(125,green)).
neg(next_control(126,green)).
neg(next_control(126,red)).
neg(next_control(127,blue)).
neg(next_control(127,red)).
neg(next_control(128,green)).
neg(next_control(128,red)).
neg(next_control(129,blue)).
neg(next_control(129,red)).
neg(next_control(13,blue)).
neg(next_control(13,green)).
neg(next_control(130,green)).
neg(next_control(130,red)).
neg(next_control(131,blue)).
neg(next_control(131,green)).
neg(next_control(132,blue)).
neg(next_control(132,green)).
neg(next_control(133,blue)).
neg(next_control(133,green)).
neg(next_control(134,blue)).
neg(next_control(134,red)).
neg(next_control(135,blue)).
neg(next_control(135,green)).
neg(next_control(136,blue)).
neg(next_control(136,green)).
neg(next_control(137,green)).
neg(next_control(137,red)).
neg(next_control(138,blue)).
neg(next_control(138,red)).
neg(next_control(139,green)).
neg(next_control(139,red)).
neg(next_control(14,blue)).
neg(next_control(14,red)).
neg(next_control(140,blue)).
neg(next_control(140,red)).
neg(next_control(141,blue)).
neg(next_control(141,green)).
neg(next_control(142,blue)).
neg(next_control(142,red)).
neg(next_control(143,blue)).
neg(next_control(143,green)).
neg(next_control(144,blue)).
neg(next_control(144,green)).
neg(next_control(145,blue)).
neg(next_control(145,green)).
neg(next_control(146,green)).
neg(next_control(146,red)).
neg(next_control(147,blue)).
neg(next_control(147,green)).
neg(next_control(148,blue)).
neg(next_control(148,green)).
neg(next_control(149,blue)).
neg(next_control(149,red)).
neg(next_control(15,blue)).
neg(next_control(15,green)).
neg(next_control(150,green)).
neg(next_control(150,red)).
neg(next_control(151,blue)).
neg(next_control(151,green)).
neg(next_control(152,blue)).
neg(next_control(152,red)).
neg(next_control(153,green)).
neg(next_control(153,red)).
neg(next_control(154,blue)).
neg(next_control(154,red)).
neg(next_control(155,green)).
neg(next_control(155,red)).
neg(next_control(156,blue)).
neg(next_control(156,red)).
neg(next_control(157,blue)).
neg(next_control(157,red)).
neg(next_control(158,blue)).
neg(next_control(158,green)).
neg(next_control(159,green)).
neg(next_control(159,red)).
neg(next_control(16,blue)).
neg(next_control(16,green)).
neg(next_control(160,green)).
neg(next_control(160,red)).
neg(next_control(161,blue)).
neg(next_control(161,green)).
neg(next_control(162,blue)).
neg(next_control(162,green)).
neg(next_control(163,green)).
neg(next_control(163,red)).
neg(next_control(164,green)).
neg(next_control(164,red)).
neg(next_control(165,blue)).
neg(next_control(165,green)).
neg(next_control(166,blue)).
neg(next_control(166,green)).
neg(next_control(167,blue)).
neg(next_control(167,green)).
neg(next_control(168,green)).
neg(next_control(168,red)).
neg(next_control(169,green)).
neg(next_control(169,red)).
neg(next_control(17,blue)).
neg(next_control(17,green)).
neg(next_control(170,blue)).
neg(next_control(170,green)).
neg(next_control(171,blue)).
neg(next_control(171,red)).
neg(next_control(172,blue)).
neg(next_control(172,green)).
neg(next_control(173,blue)).
neg(next_control(173,green)).
neg(next_control(174,blue)).
neg(next_control(174,red)).
neg(next_control(175,green)).
neg(next_control(175,red)).
neg(next_control(176,blue)).
neg(next_control(176,green)).
neg(next_control(177,blue)).
neg(next_control(177,green)).
neg(next_control(178,blue)).
neg(next_control(178,red)).
neg(next_control(179,blue)).
neg(next_control(179,red)).
neg(next_control(18,green)).
neg(next_control(18,red)).
neg(next_control(180,green)).
neg(next_control(180,red)).
neg(next_control(181,blue)).
neg(next_control(181,red)).
neg(next_control(182,blue)).
neg(next_control(182,red)).
neg(next_control(183,green)).
neg(next_control(183,red)).
neg(next_control(184,blue)).
neg(next_control(184,green)).
neg(next_control(185,green)).
neg(next_control(185,red)).
neg(next_control(186,blue)).
neg(next_control(186,green)).
neg(next_control(187,blue)).
neg(next_control(187,red)).
neg(next_control(188,blue)).
neg(next_control(188,red)).
neg(next_control(189,green)).
neg(next_control(189,red)).
neg(next_control(19,green)).
neg(next_control(19,red)).
neg(next_control(190,blue)).
neg(next_control(190,red)).
neg(next_control(191,green)).
neg(next_control(191,red)).
neg(next_control(192,blue)).
neg(next_control(192,red)).
neg(next_control(193,green)).
neg(next_control(193,red)).
neg(next_control(194,blue)).
neg(next_control(194,green)).
neg(next_control(195,blue)).
neg(next_control(195,red)).
neg(next_control(196,blue)).
neg(next_control(196,red)).
neg(next_control(197,blue)).
neg(next_control(197,green)).
neg(next_control(198,green)).
neg(next_control(198,red)).
neg(next_control(199,blue)).
neg(next_control(199,red)).
neg(next_control(2,blue)).
neg(next_control(2,red)).
neg(next_control(20,blue)).
neg(next_control(20,green)).
neg(next_control(200,blue)).
neg(next_control(200,green)).
neg(next_control(201,green)).
neg(next_control(201,red)).
neg(next_control(202,blue)).
neg(next_control(202,green)).
neg(next_control(203,blue)).
neg(next_control(203,green)).
neg(next_control(204,blue)).
neg(next_control(204,red)).
neg(next_control(205,blue)).
neg(next_control(205,red)).
neg(next_control(206,green)).
neg(next_control(206,red)).
neg(next_control(207,blue)).
neg(next_control(207,red)).
neg(next_control(208,blue)).
neg(next_control(208,green)).
neg(next_control(209,blue)).
neg(next_control(209,green)).
neg(next_control(21,blue)).
neg(next_control(21,green)).
neg(next_control(210,green)).
neg(next_control(210,red)).
neg(next_control(211,blue)).
neg(next_control(211,red)).
neg(next_control(212,blue)).
neg(next_control(212,red)).
neg(next_control(213,blue)).
neg(next_control(213,red)).
neg(next_control(214,blue)).
neg(next_control(214,red)).
neg(next_control(215,blue)).
neg(next_control(215,red)).
neg(next_control(216,blue)).
neg(next_control(216,green)).
neg(next_control(217,blue)).
neg(next_control(217,red)).
neg(next_control(218,green)).
neg(next_control(218,red)).
neg(next_control(219,green)).
neg(next_control(219,red)).
neg(next_control(22,blue)).
neg(next_control(22,green)).
neg(next_control(220,blue)).
neg(next_control(220,red)).
neg(next_control(221,blue)).
neg(next_control(221,green)).
neg(next_control(222,blue)).
neg(next_control(222,red)).
neg(next_control(223,blue)).
neg(next_control(223,red)).
neg(next_control(224,green)).
neg(next_control(224,red)).
neg(next_control(225,blue)).
neg(next_control(225,green)).
neg(next_control(226,blue)).
neg(next_control(226,green)).
neg(next_control(227,blue)).
neg(next_control(227,green)).
neg(next_control(228,blue)).
neg(next_control(228,red)).
neg(next_control(229,green)).
neg(next_control(229,red)).
neg(next_control(23,blue)).
neg(next_control(23,red)).
neg(next_control(230,blue)).
neg(next_control(230,red)).
neg(next_control(231,blue)).
neg(next_control(231,green)).
neg(next_control(232,blue)).
neg(next_control(232,green)).
neg(next_control(233,green)).
neg(next_control(233,red)).
neg(next_control(234,blue)).
neg(next_control(234,red)).
neg(next_control(235,blue)).
neg(next_control(235,red)).
neg(next_control(236,green)).
neg(next_control(236,red)).
neg(next_control(237,blue)).
neg(next_control(237,red)).
neg(next_control(238,blue)).
neg(next_control(238,red)).
neg(next_control(239,blue)).
neg(next_control(239,red)).
neg(next_control(24,green)).
neg(next_control(24,red)).
neg(next_control(240,green)).
neg(next_control(240,red)).
neg(next_control(241,green)).
neg(next_control(241,red)).
neg(next_control(242,green)).
neg(next_control(242,red)).
neg(next_control(243,green)).
neg(next_control(243,red)).
neg(next_control(244,blue)).
neg(next_control(244,green)).
neg(next_control(245,blue)).
neg(next_control(245,red)).
neg(next_control(246,blue)).
neg(next_control(246,red)).
neg(next_control(247,blue)).
neg(next_control(247,red)).
neg(next_control(248,blue)).
neg(next_control(248,green)).
neg(next_control(249,green)).
neg(next_control(249,red)).
neg(next_control(25,blue)).
neg(next_control(25,green)).
neg(next_control(250,blue)).
neg(next_control(250,red)).
neg(next_control(251,green)).
neg(next_control(251,red)).
neg(next_control(252,blue)).
neg(next_control(252,green)).
neg(next_control(253,blue)).
neg(next_control(253,green)).
neg(next_control(254,blue)).
neg(next_control(254,red)).
neg(next_control(255,blue)).
neg(next_control(255,green)).
neg(next_control(256,blue)).
neg(next_control(256,green)).
neg(next_control(257,blue)).
neg(next_control(257,red)).
neg(next_control(258,green)).
neg(next_control(258,red)).
neg(next_control(259,green)).
neg(next_control(259,red)).
neg(next_control(26,blue)).
neg(next_control(26,green)).
neg(next_control(260,green)).
neg(next_control(260,red)).
neg(next_control(261,blue)).
neg(next_control(261,red)).
neg(next_control(262,blue)).
neg(next_control(262,green)).
neg(next_control(263,green)).
neg(next_control(263,red)).
neg(next_control(264,blue)).
neg(next_control(264,green)).
neg(next_control(265,blue)).
neg(next_control(265,red)).
neg(next_control(266,green)).
neg(next_control(266,red)).
neg(next_control(267,green)).
neg(next_control(267,red)).
neg(next_control(268,blue)).
neg(next_control(268,green)).
neg(next_control(269,blue)).
neg(next_control(269,green)).
neg(next_control(27,blue)).
neg(next_control(27,red)).
neg(next_control(270,blue)).
neg(next_control(270,green)).
neg(next_control(271,blue)).
neg(next_control(271,green)).
neg(next_control(272,blue)).
neg(next_control(272,red)).
neg(next_control(273,blue)).
neg(next_control(273,green)).
neg(next_control(274,green)).
neg(next_control(274,red)).
neg(next_control(275,blue)).
neg(next_control(275,red)).
neg(next_control(276,blue)).
neg(next_control(276,red)).
neg(next_control(277,green)).
neg(next_control(277,red)).
neg(next_control(278,green)).
neg(next_control(278,red)).
neg(next_control(279,green)).
neg(next_control(279,red)).
neg(next_control(28,green)).
neg(next_control(28,red)).
neg(next_control(280,green)).
neg(next_control(280,red)).
neg(next_control(281,blue)).
neg(next_control(281,green)).
neg(next_control(282,blue)).
neg(next_control(282,green)).
neg(next_control(283,green)).
neg(next_control(283,red)).
neg(next_control(284,blue)).
neg(next_control(284,green)).
neg(next_control(285,blue)).
neg(next_control(285,red)).
neg(next_control(286,blue)).
neg(next_control(286,red)).
neg(next_control(287,blue)).
neg(next_control(287,red)).
neg(next_control(288,green)).
neg(next_control(288,red)).
neg(next_control(289,blue)).
neg(next_control(289,green)).
neg(next_control(29,blue)).
neg(next_control(29,green)).
neg(next_control(290,green)).
neg(next_control(290,red)).
neg(next_control(291,blue)).
neg(next_control(291,green)).
neg(next_control(292,blue)).
neg(next_control(292,green)).
neg(next_control(293,blue)).
neg(next_control(293,green)).
neg(next_control(294,blue)).
neg(next_control(294,green)).
neg(next_control(295,blue)).
neg(next_control(295,green)).
neg(next_control(296,blue)).
neg(next_control(296,green)).
neg(next_control(297,blue)).
neg(next_control(297,green)).
neg(next_control(298,green)).
neg(next_control(298,red)).
neg(next_control(299,blue)).
neg(next_control(299,red)).
neg(next_control(3,blue)).
neg(next_control(3,red)).
neg(next_control(30,blue)).
neg(next_control(30,red)).
neg(next_control(300,blue)).
neg(next_control(300,green)).
neg(next_control(301,blue)).
neg(next_control(301,green)).
neg(next_control(302,blue)).
neg(next_control(302,green)).
neg(next_control(303,blue)).
neg(next_control(303,red)).
neg(next_control(304,blue)).
neg(next_control(304,green)).
neg(next_control(305,blue)).
neg(next_control(305,red)).
neg(next_control(306,blue)).
neg(next_control(306,red)).
neg(next_control(307,blue)).
neg(next_control(307,red)).
neg(next_control(308,blue)).
neg(next_control(308,red)).
neg(next_control(309,blue)).
neg(next_control(309,red)).
neg(next_control(31,blue)).
neg(next_control(31,red)).
neg(next_control(310,green)).
neg(next_control(310,red)).
neg(next_control(311,blue)).
neg(next_control(311,green)).
neg(next_control(312,blue)).
neg(next_control(312,green)).
neg(next_control(313,green)).
neg(next_control(313,red)).
neg(next_control(314,blue)).
neg(next_control(314,green)).
neg(next_control(315,green)).
neg(next_control(315,red)).
neg(next_control(316,blue)).
neg(next_control(316,green)).
neg(next_control(317,blue)).
neg(next_control(317,red)).
neg(next_control(318,blue)).
neg(next_control(318,green)).
neg(next_control(319,green)).
neg(next_control(319,red)).
neg(next_control(32,blue)).
neg(next_control(32,green)).
neg(next_control(320,blue)).
neg(next_control(320,red)).
neg(next_control(321,blue)).
neg(next_control(321,green)).
neg(next_control(322,green)).
neg(next_control(322,red)).
neg(next_control(323,blue)).
neg(next_control(323,green)).
neg(next_control(324,blue)).
neg(next_control(324,green)).
neg(next_control(325,green)).
neg(next_control(325,red)).
neg(next_control(326,green)).
neg(next_control(326,red)).
neg(next_control(327,blue)).
neg(next_control(327,green)).
neg(next_control(328,green)).
neg(next_control(328,red)).
neg(next_control(329,blue)).
neg(next_control(329,red)).
neg(next_control(33,blue)).
neg(next_control(33,red)).
neg(next_control(330,blue)).
neg(next_control(330,green)).
neg(next_control(331,blue)).
neg(next_control(331,green)).
neg(next_control(332,green)).
neg(next_control(332,red)).
neg(next_control(333,blue)).
neg(next_control(333,red)).
neg(next_control(334,blue)).
neg(next_control(334,red)).
neg(next_control(335,blue)).
neg(next_control(335,red)).
neg(next_control(336,green)).
neg(next_control(336,red)).
neg(next_control(337,green)).
neg(next_control(337,red)).
neg(next_control(338,blue)).
neg(next_control(338,green)).
neg(next_control(339,blue)).
neg(next_control(339,green)).
neg(next_control(34,green)).
neg(next_control(34,red)).
neg(next_control(340,green)).
neg(next_control(340,red)).
neg(next_control(341,blue)).
neg(next_control(341,green)).
neg(next_control(342,green)).
neg(next_control(342,red)).
neg(next_control(343,blue)).
neg(next_control(343,green)).
neg(next_control(344,blue)).
neg(next_control(344,red)).
neg(next_control(345,blue)).
neg(next_control(345,red)).
neg(next_control(346,green)).
neg(next_control(346,red)).
neg(next_control(347,green)).
neg(next_control(347,red)).
neg(next_control(348,green)).
neg(next_control(348,red)).
neg(next_control(349,blue)).
neg(next_control(349,red)).
neg(next_control(35,blue)).
neg(next_control(35,green)).
neg(next_control(350,blue)).
neg(next_control(350,red)).
neg(next_control(351,blue)).
neg(next_control(351,red)).
neg(next_control(352,blue)).
neg(next_control(352,red)).
neg(next_control(353,blue)).
neg(next_control(353,green)).
neg(next_control(354,blue)).
neg(next_control(354,red)).
neg(next_control(355,green)).
neg(next_control(355,red)).
neg(next_control(356,blue)).
neg(next_control(356,red)).
neg(next_control(357,blue)).
neg(next_control(357,red)).
neg(next_control(358,green)).
neg(next_control(358,red)).
neg(next_control(359,green)).
neg(next_control(359,red)).
neg(next_control(36,blue)).
neg(next_control(36,red)).
neg(next_control(360,blue)).
neg(next_control(360,red)).
neg(next_control(361,blue)).
neg(next_control(361,green)).
neg(next_control(362,blue)).
neg(next_control(362,red)).
neg(next_control(363,blue)).
neg(next_control(363,green)).
neg(next_control(364,blue)).
neg(next_control(364,green)).
neg(next_control(365,blue)).
neg(next_control(365,green)).
neg(next_control(366,blue)).
neg(next_control(366,red)).
neg(next_control(367,blue)).
neg(next_control(367,red)).
neg(next_control(368,green)).
neg(next_control(368,red)).
neg(next_control(369,blue)).
neg(next_control(369,red)).
neg(next_control(37,blue)).
neg(next_control(37,red)).
neg(next_control(370,blue)).
neg(next_control(370,red)).
neg(next_control(371,blue)).
neg(next_control(371,red)).
neg(next_control(372,green)).
neg(next_control(372,red)).
neg(next_control(373,blue)).
neg(next_control(373,green)).
neg(next_control(374,blue)).
neg(next_control(374,red)).
neg(next_control(375,blue)).
neg(next_control(375,green)).
neg(next_control(376,blue)).
neg(next_control(376,green)).
neg(next_control(377,green)).
neg(next_control(377,red)).
neg(next_control(378,green)).
neg(next_control(378,red)).
neg(next_control(379,blue)).
neg(next_control(379,green)).
neg(next_control(38,blue)).
neg(next_control(38,red)).
neg(next_control(380,blue)).
neg(next_control(380,green)).
neg(next_control(381,blue)).
neg(next_control(381,green)).
neg(next_control(382,blue)).
neg(next_control(382,green)).
neg(next_control(383,green)).
neg(next_control(383,red)).
neg(next_control(384,blue)).
neg(next_control(384,red)).
neg(next_control(385,blue)).
neg(next_control(385,green)).
neg(next_control(386,blue)).
neg(next_control(386,green)).
neg(next_control(387,blue)).
neg(next_control(387,green)).
neg(next_control(388,green)).
neg(next_control(388,red)).
neg(next_control(389,green)).
neg(next_control(389,red)).
neg(next_control(39,blue)).
neg(next_control(39,red)).
neg(next_control(390,blue)).
neg(next_control(390,red)).
neg(next_control(391,blue)).
neg(next_control(391,green)).
neg(next_control(392,blue)).
neg(next_control(392,red)).
neg(next_control(393,green)).
neg(next_control(393,red)).
neg(next_control(394,blue)).
neg(next_control(394,green)).
neg(next_control(395,green)).
neg(next_control(395,red)).
neg(next_control(396,blue)).
neg(next_control(396,red)).
neg(next_control(397,green)).
neg(next_control(397,red)).
neg(next_control(398,blue)).
neg(next_control(398,green)).
neg(next_control(399,green)).
neg(next_control(399,red)).
neg(next_control(4,green)).
neg(next_control(4,red)).
neg(next_control(40,blue)).
neg(next_control(40,red)).
neg(next_control(400,blue)).
neg(next_control(400,red)).
neg(next_control(401,green)).
neg(next_control(401,red)).
neg(next_control(402,blue)).
neg(next_control(402,green)).
neg(next_control(403,blue)).
neg(next_control(403,red)).
neg(next_control(404,green)).
neg(next_control(404,red)).
neg(next_control(405,blue)).
neg(next_control(405,green)).
neg(next_control(406,blue)).
neg(next_control(406,green)).
neg(next_control(407,green)).
neg(next_control(407,red)).
neg(next_control(408,green)).
neg(next_control(408,red)).
neg(next_control(409,green)).
neg(next_control(409,red)).
neg(next_control(41,blue)).
neg(next_control(41,green)).
neg(next_control(410,green)).
neg(next_control(410,red)).
neg(next_control(411,blue)).
neg(next_control(411,red)).
neg(next_control(412,blue)).
neg(next_control(412,red)).
neg(next_control(413,blue)).
neg(next_control(413,red)).
neg(next_control(414,green)).
neg(next_control(414,red)).
neg(next_control(415,green)).
neg(next_control(415,red)).
neg(next_control(416,blue)).
neg(next_control(416,green)).
neg(next_control(417,green)).
neg(next_control(417,red)).
neg(next_control(418,green)).
neg(next_control(418,red)).
neg(next_control(419,green)).
neg(next_control(419,red)).
neg(next_control(42,blue)).
neg(next_control(42,green)).
neg(next_control(420,blue)).
neg(next_control(420,red)).
neg(next_control(421,blue)).
neg(next_control(421,red)).
neg(next_control(422,green)).
neg(next_control(422,red)).
neg(next_control(423,blue)).
neg(next_control(423,green)).
neg(next_control(424,blue)).
neg(next_control(424,green)).
neg(next_control(425,blue)).
neg(next_control(425,green)).
neg(next_control(426,green)).
neg(next_control(426,red)).
neg(next_control(427,blue)).
neg(next_control(427,green)).
neg(next_control(428,blue)).
neg(next_control(428,green)).
neg(next_control(429,blue)).
neg(next_control(429,green)).
neg(next_control(43,blue)).
neg(next_control(43,red)).
neg(next_control(430,green)).
neg(next_control(430,red)).
neg(next_control(431,blue)).
neg(next_control(431,green)).
neg(next_control(432,blue)).
neg(next_control(432,green)).
neg(next_control(433,green)).
neg(next_control(433,red)).
neg(next_control(434,blue)).
neg(next_control(434,green)).
neg(next_control(435,blue)).
neg(next_control(435,green)).
neg(next_control(436,blue)).
neg(next_control(436,green)).
neg(next_control(437,blue)).
neg(next_control(437,red)).
neg(next_control(438,green)).
neg(next_control(438,red)).
neg(next_control(439,blue)).
neg(next_control(439,red)).
neg(next_control(44,green)).
neg(next_control(44,red)).
neg(next_control(440,blue)).
neg(next_control(440,red)).
neg(next_control(441,blue)).
neg(next_control(441,red)).
neg(next_control(442,blue)).
neg(next_control(442,green)).
neg(next_control(443,green)).
neg(next_control(443,red)).
neg(next_control(444,blue)).
neg(next_control(444,red)).
neg(next_control(445,blue)).
neg(next_control(445,green)).
neg(next_control(446,green)).
neg(next_control(446,red)).
neg(next_control(447,blue)).
neg(next_control(447,green)).
neg(next_control(448,green)).
neg(next_control(448,red)).
neg(next_control(449,green)).
neg(next_control(449,red)).
neg(next_control(45,blue)).
neg(next_control(45,red)).
neg(next_control(450,blue)).
neg(next_control(450,green)).
neg(next_control(451,blue)).
neg(next_control(451,green)).
neg(next_control(452,green)).
neg(next_control(452,red)).
neg(next_control(453,blue)).
neg(next_control(453,green)).
neg(next_control(454,blue)).
neg(next_control(454,red)).
neg(next_control(455,blue)).
neg(next_control(455,green)).
neg(next_control(456,blue)).
neg(next_control(456,green)).
neg(next_control(457,blue)).
neg(next_control(457,red)).
neg(next_control(458,green)).
neg(next_control(458,red)).
neg(next_control(459,blue)).
neg(next_control(459,green)).
neg(next_control(46,blue)).
neg(next_control(46,red)).
neg(next_control(460,blue)).
neg(next_control(460,green)).
neg(next_control(461,blue)).
neg(next_control(461,green)).
neg(next_control(462,blue)).
neg(next_control(462,green)).
neg(next_control(463,blue)).
neg(next_control(463,green)).
neg(next_control(464,green)).
neg(next_control(464,red)).
neg(next_control(465,blue)).
neg(next_control(465,red)).
neg(next_control(466,blue)).
neg(next_control(466,green)).
neg(next_control(467,blue)).
neg(next_control(467,red)).
neg(next_control(468,green)).
neg(next_control(468,red)).
neg(next_control(469,blue)).
neg(next_control(469,green)).
neg(next_control(47,green)).
neg(next_control(47,red)).
neg(next_control(470,blue)).
neg(next_control(470,green)).
neg(next_control(471,blue)).
neg(next_control(471,green)).
neg(next_control(472,blue)).
neg(next_control(472,red)).
neg(next_control(473,blue)).
neg(next_control(473,red)).
neg(next_control(474,blue)).
neg(next_control(474,red)).
neg(next_control(475,blue)).
neg(next_control(475,green)).
neg(next_control(476,green)).
neg(next_control(476,red)).
neg(next_control(477,blue)).
neg(next_control(477,green)).
neg(next_control(478,blue)).
neg(next_control(478,green)).
neg(next_control(479,green)).
neg(next_control(479,red)).
neg(next_control(48,blue)).
neg(next_control(48,green)).
neg(next_control(480,blue)).
neg(next_control(480,red)).
neg(next_control(481,green)).
neg(next_control(481,red)).
neg(next_control(482,blue)).
neg(next_control(482,green)).
neg(next_control(483,green)).
neg(next_control(483,red)).
neg(next_control(484,blue)).
neg(next_control(484,green)).
neg(next_control(485,blue)).
neg(next_control(485,red)).
neg(next_control(486,green)).
neg(next_control(486,red)).
neg(next_control(487,blue)).
neg(next_control(487,red)).
neg(next_control(488,green)).
neg(next_control(488,red)).
neg(next_control(489,blue)).
neg(next_control(489,green)).
neg(next_control(49,green)).
neg(next_control(49,red)).
neg(next_control(490,blue)).
neg(next_control(490,green)).
neg(next_control(491,blue)).
neg(next_control(491,red)).
neg(next_control(492,green)).
neg(next_control(492,red)).
neg(next_control(493,blue)).
neg(next_control(493,green)).
neg(next_control(494,green)).
neg(next_control(494,red)).
neg(next_control(495,green)).
neg(next_control(495,red)).
neg(next_control(496,blue)).
neg(next_control(496,green)).
neg(next_control(497,blue)).
neg(next_control(497,green)).
neg(next_control(498,green)).
neg(next_control(498,red)).
neg(next_control(499,blue)).
neg(next_control(499,green)).
neg(next_control(5,green)).
neg(next_control(5,red)).
neg(next_control(50,blue)).
neg(next_control(50,red)).
neg(next_control(500,blue)).
neg(next_control(500,red)).
neg(next_control(51,blue)).
neg(next_control(51,red)).
neg(next_control(52,blue)).
neg(next_control(52,green)).
neg(next_control(53,green)).
neg(next_control(53,red)).
neg(next_control(54,blue)).
neg(next_control(54,red)).
neg(next_control(55,blue)).
neg(next_control(55,red)).
neg(next_control(56,blue)).
neg(next_control(56,green)).
neg(next_control(57,blue)).
neg(next_control(57,green)).
neg(next_control(58,green)).
neg(next_control(58,red)).
neg(next_control(59,blue)).
neg(next_control(59,red)).
neg(next_control(6,blue)).
neg(next_control(6,red)).
neg(next_control(60,blue)).
neg(next_control(60,red)).
neg(next_control(61,blue)).
neg(next_control(61,green)).
neg(next_control(62,blue)).
neg(next_control(62,red)).
neg(next_control(63,green)).
neg(next_control(63,red)).
neg(next_control(64,green)).
neg(next_control(64,red)).
neg(next_control(65,blue)).
neg(next_control(65,red)).
neg(next_control(66,blue)).
neg(next_control(66,green)).
neg(next_control(67,blue)).
neg(next_control(67,red)).
neg(next_control(68,green)).
neg(next_control(68,red)).
neg(next_control(69,blue)).
neg(next_control(69,green)).
neg(next_control(7,blue)).
neg(next_control(7,green)).
neg(next_control(70,blue)).
neg(next_control(70,red)).
neg(next_control(71,blue)).
neg(next_control(71,red)).
neg(next_control(72,green)).
neg(next_control(72,red)).
neg(next_control(73,green)).
neg(next_control(73,red)).
neg(next_control(74,blue)).
neg(next_control(74,red)).
neg(next_control(75,green)).
neg(next_control(75,red)).
neg(next_control(76,green)).
neg(next_control(76,red)).
neg(next_control(77,green)).
neg(next_control(77,red)).
neg(next_control(78,blue)).
neg(next_control(78,green)).
neg(next_control(79,green)).
neg(next_control(79,red)).
neg(next_control(8,green)).
neg(next_control(8,red)).
neg(next_control(80,green)).
neg(next_control(80,red)).
neg(next_control(81,blue)).
neg(next_control(81,red)).
neg(next_control(82,blue)).
neg(next_control(82,red)).
neg(next_control(83,green)).
neg(next_control(83,red)).
neg(next_control(84,green)).
neg(next_control(84,red)).
neg(next_control(85,blue)).
neg(next_control(85,green)).
neg(next_control(86,blue)).
neg(next_control(86,red)).
neg(next_control(87,green)).
neg(next_control(87,red)).
neg(next_control(88,blue)).
neg(next_control(88,green)).
neg(next_control(89,green)).
neg(next_control(89,red)).
neg(next_control(9,blue)).
neg(next_control(9,green)).
neg(next_control(90,green)).
neg(next_control(90,red)).
neg(next_control(91,green)).
neg(next_control(91,red)).
neg(next_control(92,blue)).
neg(next_control(92,green)).
neg(next_control(93,blue)).
neg(next_control(93,green)).
neg(next_control(94,blue)).
neg(next_control(94,red)).
neg(next_control(95,blue)).
neg(next_control(95,green)).
neg(next_control(96,green)).
neg(next_control(96,red)).
neg(next_control(97,blue)).
neg(next_control(97,green)).
neg(next_control(98,blue)).
neg(next_control(98,red)).
neg(next_control(99,green)).
neg(next_control(99,red)).
pos(next_control(1,red)).
pos(next_control(10,blue)).
pos(next_control(100,red)).
pos(next_control(101,red)).
pos(next_control(102,blue)).
pos(next_control(103,blue)).
pos(next_control(104,blue)).
pos(next_control(105,green)).
pos(next_control(106,green)).
pos(next_control(107,green)).
pos(next_control(108,blue)).
pos(next_control(109,blue)).
pos(next_control(11,green)).
pos(next_control(110,red)).
pos(next_control(111,green)).
pos(next_control(112,red)).
pos(next_control(113,blue)).
pos(next_control(114,green)).
pos(next_control(115,green)).
pos(next_control(116,green)).
pos(next_control(117,red)).
pos(next_control(118,red)).
pos(next_control(119,blue)).
pos(next_control(12,red)).
pos(next_control(120,blue)).
pos(next_control(121,green)).
pos(next_control(122,blue)).
pos(next_control(123,red)).
pos(next_control(124,green)).
pos(next_control(125,red)).
pos(next_control(126,blue)).
pos(next_control(127,green)).
pos(next_control(128,blue)).
pos(next_control(129,green)).
pos(next_control(13,red)).
pos(next_control(130,blue)).
pos(next_control(131,red)).
pos(next_control(132,red)).
pos(next_control(133,red)).
pos(next_control(134,green)).
pos(next_control(135,red)).
pos(next_control(136,red)).
pos(next_control(137,blue)).
pos(next_control(138,green)).
pos(next_control(139,blue)).
pos(next_control(14,green)).
pos(next_control(140,green)).
pos(next_control(141,red)).
pos(next_control(142,green)).
pos(next_control(143,red)).
pos(next_control(144,red)).
pos(next_control(145,red)).
pos(next_control(146,blue)).
pos(next_control(147,red)).
pos(next_control(148,red)).
pos(next_control(149,green)).
pos(next_control(15,red)).
pos(next_control(150,blue)).
pos(next_control(151,red)).
pos(next_control(152,green)).
pos(next_control(153,blue)).
pos(next_control(154,green)).
pos(next_control(155,blue)).
pos(next_control(156,green)).
pos(next_control(157,green)).
pos(next_control(158,red)).
pos(next_control(159,blue)).
pos(next_control(16,red)).
pos(next_control(160,blue)).
pos(next_control(161,red)).
pos(next_control(162,red)).
pos(next_control(163,blue)).
pos(next_control(164,blue)).
pos(next_control(165,red)).
pos(next_control(166,red)).
pos(next_control(167,red)).
pos(next_control(168,blue)).
pos(next_control(169,blue)).
pos(next_control(17,red)).
pos(next_control(170,red)).
pos(next_control(171,green)).
pos(next_control(172,red)).
pos(next_control(173,red)).
pos(next_control(174,green)).
pos(next_control(175,blue)).
pos(next_control(176,red)).
pos(next_control(177,red)).
pos(next_control(178,green)).
pos(next_control(179,green)).
pos(next_control(18,blue)).
pos(next_control(180,blue)).
pos(next_control(181,green)).
pos(next_control(182,green)).
pos(next_control(183,blue)).
pos(next_control(184,red)).
pos(next_control(185,blue)).
pos(next_control(186,red)).
pos(next_control(187,green)).
pos(next_control(188,green)).
pos(next_control(189,blue)).
pos(next_control(19,blue)).
pos(next_control(190,green)).
pos(next_control(191,blue)).
pos(next_control(192,green)).
pos(next_control(193,blue)).
pos(next_control(194,red)).
pos(next_control(195,green)).
pos(next_control(196,green)).
pos(next_control(197,red)).
pos(next_control(198,blue)).
pos(next_control(199,green)).
pos(next_control(2,green)).
pos(next_control(20,red)).
pos(next_control(200,red)).
pos(next_control(201,blue)).
pos(next_control(202,red)).
pos(next_control(203,red)).
pos(next_control(204,green)).
pos(next_control(205,green)).
pos(next_control(206,blue)).
pos(next_control(207,green)).
pos(next_control(208,red)).
pos(next_control(209,red)).
pos(next_control(21,red)).
pos(next_control(210,blue)).
pos(next_control(211,green)).
pos(next_control(212,green)).
pos(next_control(213,green)).
pos(next_control(214,green)).
pos(next_control(215,green)).
pos(next_control(216,red)).
pos(next_control(217,green)).
pos(next_control(218,blue)).
pos(next_control(219,blue)).
pos(next_control(22,red)).
pos(next_control(220,green)).
pos(next_control(221,red)).
pos(next_control(222,green)).
pos(next_control(223,green)).
pos(next_control(224,blue)).
pos(next_control(225,red)).
pos(next_control(226,red)).
pos(next_control(227,red)).
pos(next_control(228,green)).
pos(next_control(229,blue)).
pos(next_control(23,green)).
pos(next_control(230,green)).
pos(next_control(231,red)).
pos(next_control(232,red)).
pos(next_control(233,blue)).
pos(next_control(234,green)).
pos(next_control(235,green)).
pos(next_control(236,blue)).
pos(next_control(237,green)).
pos(next_control(238,green)).
pos(next_control(239,green)).
pos(next_control(24,blue)).
pos(next_control(240,blue)).
pos(next_control(241,blue)).
pos(next_control(242,blue)).
pos(next_control(243,blue)).
pos(next_control(244,red)).
pos(next_control(245,green)).
pos(next_control(246,green)).
pos(next_control(247,green)).
pos(next_control(248,red)).
pos(next_control(249,blue)).
pos(next_control(25,red)).
pos(next_control(250,green)).
pos(next_control(251,blue)).
pos(next_control(252,red)).
pos(next_control(253,red)).
pos(next_control(254,green)).
pos(next_control(255,red)).
pos(next_control(256,red)).
pos(next_control(257,green)).
pos(next_control(258,blue)).
pos(next_control(259,blue)).
pos(next_control(26,red)).
pos(next_control(260,blue)).
pos(next_control(261,green)).
pos(next_control(262,red)).
pos(next_control(263,blue)).
pos(next_control(264,red)).
pos(next_control(265,green)).
pos(next_control(266,blue)).
pos(next_control(267,blue)).
pos(next_control(268,red)).
pos(next_control(269,red)).
pos(next_control(27,green)).
pos(next_control(270,red)).
pos(next_control(271,red)).
pos(next_control(272,green)).
pos(next_control(273,red)).
pos(next_control(274,blue)).
pos(next_control(275,green)).
pos(next_control(276,green)).
pos(next_control(277,blue)).
pos(next_control(278,blue)).
pos(next_control(279,blue)).
pos(next_control(28,blue)).
pos(next_control(280,blue)).
pos(next_control(281,red)).
pos(next_control(282,red)).
pos(next_control(283,blue)).
pos(next_control(284,red)).
pos(next_control(285,green)).
pos(next_control(286,green)).
pos(next_control(287,green)).
pos(next_control(288,blue)).
pos(next_control(289,red)).
pos(next_control(29,red)).
pos(next_control(290,blue)).
pos(next_control(291,red)).
pos(next_control(292,red)).
pos(next_control(293,red)).
pos(next_control(294,red)).
pos(next_control(295,red)).
pos(next_control(296,red)).
pos(next_control(297,red)).
pos(next_control(298,blue)).
pos(next_control(299,green)).
pos(next_control(3,green)).
pos(next_control(30,green)).
pos(next_control(300,red)).
pos(next_control(301,red)).
pos(next_control(302,red)).
pos(next_control(303,green)).
pos(next_control(304,red)).
pos(next_control(305,green)).
pos(next_control(306,green)).
pos(next_control(307,green)).
pos(next_control(308,green)).
pos(next_control(309,green)).
pos(next_control(31,green)).
pos(next_control(310,blue)).
pos(next_control(311,red)).
pos(next_control(312,red)).
pos(next_control(313,blue)).
pos(next_control(314,red)).
pos(next_control(315,blue)).
pos(next_control(316,red)).
pos(next_control(317,green)).
pos(next_control(318,red)).
pos(next_control(319,blue)).
pos(next_control(32,red)).
pos(next_control(320,green)).
pos(next_control(321,red)).
pos(next_control(322,blue)).
pos(next_control(323,red)).
pos(next_control(324,red)).
pos(next_control(325,blue)).
pos(next_control(326,blue)).
pos(next_control(327,red)).
pos(next_control(328,blue)).
pos(next_control(329,green)).
pos(next_control(33,green)).
pos(next_control(330,red)).
pos(next_control(331,red)).
pos(next_control(332,blue)).
pos(next_control(333,green)).
pos(next_control(334,green)).
pos(next_control(335,green)).
pos(next_control(336,blue)).
pos(next_control(337,blue)).
pos(next_control(338,red)).
pos(next_control(339,red)).
pos(next_control(34,blue)).
pos(next_control(340,blue)).
pos(next_control(341,red)).
pos(next_control(342,blue)).
pos(next_control(343,red)).
pos(next_control(344,green)).
pos(next_control(345,green)).
pos(next_control(346,blue)).
pos(next_control(347,blue)).
pos(next_control(348,blue)).
pos(next_control(349,green)).
pos(next_control(35,red)).
pos(next_control(350,green)).
pos(next_control(351,green)).
pos(next_control(352,green)).
pos(next_control(353,red)).
pos(next_control(354,green)).
pos(next_control(355,blue)).
pos(next_control(356,green)).
pos(next_control(357,green)).
pos(next_control(358,blue)).
pos(next_control(359,blue)).
pos(next_control(36,green)).
pos(next_control(360,green)).
pos(next_control(361,red)).
pos(next_control(362,green)).
pos(next_control(363,red)).
pos(next_control(364,red)).
pos(next_control(365,red)).
pos(next_control(366,green)).
pos(next_control(367,green)).
pos(next_control(368,blue)).
pos(next_control(369,green)).
pos(next_control(37,green)).
pos(next_control(370,green)).
pos(next_control(371,green)).
pos(next_control(372,blue)).
pos(next_control(373,red)).
pos(next_control(374,green)).
pos(next_control(375,red)).
pos(next_control(376,red)).
pos(next_control(377,blue)).
pos(next_control(378,blue)).
pos(next_control(379,red)).
pos(next_control(38,green)).
pos(next_control(380,red)).
pos(next_control(381,red)).
pos(next_control(382,red)).
pos(next_control(383,blue)).
pos(next_control(384,green)).
pos(next_control(385,red)).
pos(next_control(386,red)).
pos(next_control(387,red)).
pos(next_control(388,blue)).
pos(next_control(389,blue)).
pos(next_control(39,green)).
pos(next_control(390,green)).
pos(next_control(391,red)).
pos(next_control(392,green)).
pos(next_control(393,blue)).
pos(next_control(394,red)).
pos(next_control(395,blue)).
pos(next_control(396,green)).
pos(next_control(397,blue)).
pos(next_control(398,red)).
pos(next_control(399,blue)).
pos(next_control(4,blue)).
pos(next_control(40,green)).
pos(next_control(400,green)).
pos(next_control(401,blue)).
pos(next_control(402,red)).
pos(next_control(403,green)).
pos(next_control(404,blue)).
pos(next_control(405,red)).
pos(next_control(406,red)).
pos(next_control(407,blue)).
pos(next_control(408,blue)).
pos(next_control(409,blue)).
pos(next_control(41,red)).
pos(next_control(410,blue)).
pos(next_control(411,green)).
pos(next_control(412,green)).
pos(next_control(413,green)).
pos(next_control(414,blue)).
pos(next_control(415,blue)).
pos(next_control(416,red)).
pos(next_control(417,blue)).
pos(next_control(418,blue)).
pos(next_control(419,blue)).
pos(next_control(42,red)).
pos(next_control(420,green)).
pos(next_control(421,green)).
pos(next_control(422,blue)).
pos(next_control(423,red)).
pos(next_control(424,red)).
pos(next_control(425,red)).
pos(next_control(426,blue)).
pos(next_control(427,red)).
pos(next_control(428,red)).
pos(next_control(429,red)).
pos(next_control(43,green)).
pos(next_control(430,blue)).
pos(next_control(431,red)).
pos(next_control(432,red)).
pos(next_control(433,blue)).
pos(next_control(434,red)).
pos(next_control(435,red)).
pos(next_control(436,red)).
pos(next_control(437,green)).
pos(next_control(438,blue)).
pos(next_control(439,green)).
pos(next_control(44,blue)).
pos(next_control(440,green)).
pos(next_control(441,green)).
pos(next_control(442,red)).
pos(next_control(443,blue)).
pos(next_control(444,green)).
pos(next_control(445,red)).
pos(next_control(446,blue)).
pos(next_control(447,red)).
pos(next_control(448,blue)).
pos(next_control(449,blue)).
pos(next_control(45,green)).
pos(next_control(450,red)).
pos(next_control(451,red)).
pos(next_control(452,blue)).
pos(next_control(453,red)).
pos(next_control(454,green)).
pos(next_control(455,red)).
pos(next_control(456,red)).
pos(next_control(457,green)).
pos(next_control(458,blue)).
pos(next_control(459,red)).
pos(next_control(46,green)).
pos(next_control(460,red)).
pos(next_control(461,red)).
pos(next_control(462,red)).
pos(next_control(463,red)).
pos(next_control(464,blue)).
pos(next_control(465,green)).
pos(next_control(466,red)).
pos(next_control(467,green)).
pos(next_control(468,blue)).
pos(next_control(469,red)).
pos(next_control(47,blue)).
pos(next_control(470,red)).
pos(next_control(471,red)).
pos(next_control(472,green)).
pos(next_control(473,green)).
pos(next_control(474,green)).
pos(next_control(475,red)).
pos(next_control(476,blue)).
pos(next_control(477,red)).
pos(next_control(478,red)).
pos(next_control(479,blue)).
pos(next_control(48,red)).
pos(next_control(480,green)).
pos(next_control(481,blue)).
pos(next_control(482,red)).
pos(next_control(483,blue)).
pos(next_control(484,red)).
pos(next_control(485,green)).
pos(next_control(486,blue)).
pos(next_control(487,green)).
pos(next_control(488,blue)).
pos(next_control(489,red)).
pos(next_control(49,blue)).
pos(next_control(490,red)).
pos(next_control(491,green)).
pos(next_control(492,blue)).
pos(next_control(493,red)).
pos(next_control(494,blue)).
pos(next_control(495,blue)).
pos(next_control(496,red)).
pos(next_control(497,red)).
pos(next_control(498,blue)).
pos(next_control(499,red)).
pos(next_control(5,blue)).
pos(next_control(50,green)).
pos(next_control(500,green)).
pos(next_control(51,green)).
pos(next_control(52,red)).
pos(next_control(53,blue)).
pos(next_control(54,green)).
pos(next_control(55,green)).
pos(next_control(56,red)).
pos(next_control(57,red)).
pos(next_control(58,blue)).
pos(next_control(59,green)).
pos(next_control(6,green)).
pos(next_control(60,green)).
pos(next_control(61,red)).
pos(next_control(62,green)).
pos(next_control(63,blue)).
pos(next_control(64,blue)).
pos(next_control(65,green)).
pos(next_control(66,red)).
pos(next_control(67,green)).
pos(next_control(68,blue)).
pos(next_control(69,red)).
pos(next_control(7,red)).
pos(next_control(70,green)).
pos(next_control(71,green)).
pos(next_control(72,blue)).
pos(next_control(73,blue)).
pos(next_control(74,green)).
pos(next_control(75,blue)).
pos(next_control(76,blue)).
pos(next_control(77,blue)).
pos(next_control(78,red)).
pos(next_control(79,blue)).
pos(next_control(8,blue)).
pos(next_control(80,blue)).
pos(next_control(81,green)).
pos(next_control(82,green)).
pos(next_control(83,blue)).
pos(next_control(84,blue)).
pos(next_control(85,red)).
pos(next_control(86,green)).
pos(next_control(87,blue)).
pos(next_control(88,red)).
pos(next_control(89,blue)).
pos(next_control(9,red)).
pos(next_control(90,blue)).
pos(next_control(91,blue)).
pos(next_control(92,red)).
pos(next_control(93,red)).
pos(next_control(94,green)).
pos(next_control(95,red)).
pos(next_control(96,blue)).
pos(next_control(97,red)).
pos(next_control(98,green)).
pos(next_control(99,blue)).