head_pred(verbgroup,2).
body_pred(synsetdomaintopicof,2).
body_pred(alsosee,2).
body_pred(instancehypernym,2).
body_pred(hypernym,2).
body_pred(haspart,2).
body_pred(similarto,2).
body_pred(membermeronym,2).
body_pred(memberofdomainusage,2).
body_pred(derivationallyrelatedform,2).
body_pred(memberofdomainregion,2).
