pos(grandparent(ddbob,bob)).
pos(grandparent(mdbob,bob)).
pos(grandparent(dmbob,bob)).
pos(grandparent(mmbob,bob)).
pos(grandparent(ddjoe,joe)).
pos(grandparent(mdjoe,joe)).
pos(grandparent(dmjoe,joe)).
pos(grandparent(mmjoe,joe)).
neg(grandparent(bob,joe)).
neg(grandparent(joe,bob)).
neg(grandparent(bob,ddbob)).
neg(grandparent(dbob,bob)).
neg(grandparent(mbob,bob)).
neg(grandparent(ddbob,dbob)).
neg(grandparent(mdbob,dbob)).
neg(grandparent(dmbob,mbob)).
neg(grandparent(mmbob,mbob)).
neg(grandparent(djoe,bob)).
