greensignal(abercrombie_st).
greensignal(cleveland_st).
greensignal(shepard_st).
greensignal(elizabeth_st).
greensignal(goulburn_st).
hastraffic(abercrombie_st).
hastraffic(lawson_st).
hastraffic(elizabeth_st).
hastraffic(goulburn_st).
intersect(abercrombie_st,lawson_st).
intersect(cleveland_st,shepard_st).
intersect(elizabeth_st,goulburn_st).