head_pred(inflamation, 1).
body_pred(gte38, 1).
body_pred(temparature, 2).
body_pred(nausea, 1).
body_pred(not_nausea, 1).
body_pred(lumbar_pain, 1).
body_pred(not_lumbar_pain, 1).
body_pred(urine_pushing, 1).
body_pred(not_urine_pushing, 1).
body_pred(micturition_pain, 1).
body_pred(not_micturition_pain, 1).
body_pred(burning_urethra, 1).
body_pred(not_burning_urethra, 1).
