pos(inflamation(1)).
pos(inflamation(3)).
pos(inflamation(6)).
pos(inflamation(8)).
pos(inflamation(9)).
pos(inflamation(10)).
pos(inflamation(17)).
pos(inflamation(18)).
pos(inflamation(20)).
pos(inflamation(21)).
pos(inflamation(23)).
pos(inflamation(24)).
pos(inflamation(25)).
pos(inflamation(26)).
pos(inflamation(27)).
pos(inflamation(29)).
pos(inflamation(30)).
pos(inflamation(31)).
pos(inflamation(35)).
pos(inflamation(36)).
pos(inflamation(38)).
pos(inflamation(39)).
pos(inflamation(42)).
pos(inflamation(43)).
pos(inflamation(44)).
pos(inflamation(46)).
pos(inflamation(48)).
pos(inflamation(53)).
pos(inflamation(55)).
pos(inflamation(58)).
pos(inflamation(59)).
pos(inflamation(70)).
pos(inflamation(71)).
pos(inflamation(72)).
pos(inflamation(78)).
pos(inflamation(79)).
pos(inflamation(83)).
pos(inflamation(84)).
pos(inflamation(85)).
pos(inflamation(88)).
pos(inflamation(89)).
pos(inflamation(92)).
pos(inflamation(98)).
pos(inflamation(99)).
pos(inflamation(101)).
pos(inflamation(105)).
pos(inflamation(106)).
pos(inflamation(110)).
pos(inflamation(114)).
