% Positive examples
pos(wash(obj0,robby,13)).

% Negative examples
neg(wash(obj0,robby,0)).
neg(wash(obj0,robby,1)).
neg(wash(obj0,robby,10)).
neg(wash(obj0,robby,11)).
neg(wash(obj0,robby,12)).
neg(wash(obj0,robby,14)).
neg(wash(obj0,robby,15)).
neg(wash(obj0,robby,16)).
neg(wash(obj0,robby,2)).
neg(wash(obj0,robby,3)).
neg(wash(obj0,robby,4)).
neg(wash(obj0,robby,5)).
neg(wash(obj0,robby,6)).
neg(wash(obj0,robby,7)).
neg(wash(obj0,robby,8)).
neg(wash(obj0,robby,9)).
neg(wash(obj1,robby,0)).
neg(wash(obj1,robby,1)).
neg(wash(obj1,robby,10)).
neg(wash(obj1,robby,11)).
neg(wash(obj1,robby,12)).
neg(wash(obj1,robby,13)).
neg(wash(obj1,robby,14)).
neg(wash(obj1,robby,15)).
neg(wash(obj1,robby,16)).
neg(wash(obj1,robby,2)).
neg(wash(obj1,robby,3)).
neg(wash(obj1,robby,4)).
neg(wash(obj1,robby,5)).
neg(wash(obj1,robby,6)).
neg(wash(obj1,robby,7)).
neg(wash(obj1,robby,8)).
neg(wash(obj1,robby,9)).
neg(wash(obj2,robby,0)).
neg(wash(obj2,robby,1)).
neg(wash(obj2,robby,10)).
neg(wash(obj2,robby,11)).
neg(wash(obj2,robby,12)).
neg(wash(obj2,robby,13)).
neg(wash(obj2,robby,14)).
neg(wash(obj2,robby,15)).
neg(wash(obj2,robby,16)).
neg(wash(obj2,robby,2)).
neg(wash(obj2,robby,3)).
neg(wash(obj2,robby,4)).
neg(wash(obj2,robby,5)).
neg(wash(obj2,robby,6)).
neg(wash(obj2,robby,7)).
neg(wash(obj2,robby,8)).
neg(wash(obj2,robby,9)).
neg(wash(obj3,robby,0)).
neg(wash(obj3,robby,1)).
neg(wash(obj3,robby,10)).
neg(wash(obj3,robby,11)).
neg(wash(obj3,robby,12)).
neg(wash(obj3,robby,13)).
neg(wash(obj3,robby,14)).
neg(wash(obj3,robby,15)).
neg(wash(obj3,robby,16)).
neg(wash(obj3,robby,2)).
neg(wash(obj3,robby,3)).
neg(wash(obj3,robby,4)).
neg(wash(obj3,robby,5)).
neg(wash(obj3,robby,6)).
neg(wash(obj3,robby,7)).
neg(wash(obj3,robby,8)).
neg(wash(obj3,robby,9)).
