body_pred(collidingclose,2).
body_pred(higherpri,2).
body_pred(isambulance,1).
body_pred(isatinter,1).
body_pred(isbus,1).
body_pred(iscar,1).
body_pred(isclose,2).
body_pred(isininter,1).
body_pred(isold,1).
body_pred(ispedestrian,1).
body_pred(ispolice,1).
body_pred(isreckless,1).
body_pred(istiro,1).
body_pred(isyoung,1).
body_pred(leftof,2).
body_pred(nextto,2).
body_pred(not_collidingclose,2).
body_pred(not_higherpri,2).
body_pred(not_isambulance,1).
body_pred(not_isatinter,1).
body_pred(not_isbus,1).
body_pred(not_iscar,1).
body_pred(not_isclose,2).
body_pred(not_isininter,1).
body_pred(not_isold,1).
body_pred(not_ispedestrian,1).
body_pred(not_ispolice,1).
body_pred(not_isreckless,1).
body_pred(not_istiro,1).
body_pred(not_isyoung,1).
body_pred(not_leftof,2).
body_pred(not_nextto,2).
body_pred(not_rightof,2).
body_pred(rightof,2).
body_pred(see,2).
head_pred(stop,1).
