% Positive examples
pos(pickfromside(obj0,robby,12)).
pos(pickfromside(obj1,robby,8)).
pos(pickfromside(obj2,robby,4)).

% Negative examples
neg(pickfromside(obj0,robby,1)).
neg(pickfromside(obj0,robby,10)).
neg(pickfromside(obj0,robby,11)).
neg(pickfromside(obj0,robby,13)).
neg(pickfromside(obj0,robby,14)).
neg(pickfromside(obj0,robby,15)).
neg(pickfromside(obj0,robby,16)).
neg(pickfromside(obj0,robby,2)).
neg(pickfromside(obj0,robby,3)).
neg(pickfromside(obj0,robby,5)).
neg(pickfromside(obj0,robby,6)).
neg(pickfromside(obj0,robby,7)).
neg(pickfromside(obj0,robby,9)).
neg(pickfromside(obj1,robby,1)).
neg(pickfromside(obj1,robby,10)).
neg(pickfromside(obj1,robby,11)).
neg(pickfromside(obj1,robby,12)).
neg(pickfromside(obj1,robby,13)).
neg(pickfromside(obj1,robby,14)).
neg(pickfromside(obj1,robby,15)).
neg(pickfromside(obj1,robby,16)).
neg(pickfromside(obj1,robby,2)).
neg(pickfromside(obj1,robby,3)).
neg(pickfromside(obj1,robby,5)).
neg(pickfromside(obj1,robby,6)).
neg(pickfromside(obj1,robby,7)).
neg(pickfromside(obj1,robby,9)).
neg(pickfromside(obj2,robby,1)).
neg(pickfromside(obj2,robby,10)).
neg(pickfromside(obj2,robby,11)).
neg(pickfromside(obj2,robby,12)).
neg(pickfromside(obj2,robby,13)).
neg(pickfromside(obj2,robby,14)).
neg(pickfromside(obj2,robby,15)).
neg(pickfromside(obj2,robby,16)).
neg(pickfromside(obj2,robby,2)).
neg(pickfromside(obj2,robby,3)).
neg(pickfromside(obj2,robby,5)).
neg(pickfromside(obj2,robby,6)).
neg(pickfromside(obj2,robby,7)).
neg(pickfromside(obj2,robby,8)).
neg(pickfromside(obj2,robby,9)).
neg(pickfromside(obj3,robby,0)).
neg(pickfromside(obj3,robby,1)).
neg(pickfromside(obj3,robby,10)).
neg(pickfromside(obj3,robby,11)).
neg(pickfromside(obj3,robby,12)).
neg(pickfromside(obj3,robby,13)).
neg(pickfromside(obj3,robby,14)).
neg(pickfromside(obj3,robby,15)).
neg(pickfromside(obj3,robby,16)).
neg(pickfromside(obj3,robby,2)).
neg(pickfromside(obj3,robby,3)).
neg(pickfromside(obj3,robby,4)).
neg(pickfromside(obj3,robby,5)).
neg(pickfromside(obj3,robby,6)).
neg(pickfromside(obj3,robby,7)).
neg(pickfromside(obj3,robby,8)).
neg(pickfromside(obj3,robby,9)).
