% Positive examples
pos(drop(ball1,roomb,left,13)).
pos(drop(ball1,roomb,left,2)).
pos(drop(ball2,roomb,left,17)).
pos(drop(ball2,roomb,left,6)).
pos(drop(ball3,roomb,left,10)).
pos(drop(ball3,roomb,left,21)).
pos(drop(ball4,roomb,left,25)).

% Negative examples
neg(drop(ball1,rooma,left,0)).
neg(drop(ball1,rooma,left,1)).
neg(drop(ball1,rooma,left,10)).
neg(drop(ball1,rooma,left,11)).
neg(drop(ball1,rooma,left,12)).
neg(drop(ball1,rooma,left,13)).
neg(drop(ball1,rooma,left,14)).
neg(drop(ball1,rooma,left,15)).
neg(drop(ball1,rooma,left,16)).
neg(drop(ball1,rooma,left,17)).
neg(drop(ball1,rooma,left,18)).
neg(drop(ball1,rooma,left,19)).
neg(drop(ball1,rooma,left,2)).
neg(drop(ball1,rooma,left,20)).
neg(drop(ball1,rooma,left,21)).
neg(drop(ball1,rooma,left,22)).
neg(drop(ball1,rooma,left,23)).
neg(drop(ball1,rooma,left,24)).
neg(drop(ball1,rooma,left,25)).
neg(drop(ball1,rooma,left,3)).
neg(drop(ball1,rooma,left,4)).
neg(drop(ball1,rooma,left,5)).
neg(drop(ball1,rooma,left,6)).
neg(drop(ball1,rooma,left,7)).
neg(drop(ball1,rooma,left,8)).
neg(drop(ball1,rooma,left,9)).
neg(drop(ball1,roomb,left,0)).
neg(drop(ball1,roomb,left,1)).
neg(drop(ball1,roomb,left,10)).
neg(drop(ball1,roomb,left,11)).
neg(drop(ball1,roomb,left,12)).
neg(drop(ball1,roomb,left,14)).
neg(drop(ball1,roomb,left,15)).
neg(drop(ball1,roomb,left,16)).
neg(drop(ball1,roomb,left,17)).
neg(drop(ball1,roomb,left,18)).
neg(drop(ball1,roomb,left,19)).
neg(drop(ball1,roomb,left,20)).
neg(drop(ball1,roomb,left,21)).
neg(drop(ball1,roomb,left,22)).
neg(drop(ball1,roomb,left,23)).
neg(drop(ball1,roomb,left,24)).
neg(drop(ball1,roomb,left,25)).
neg(drop(ball1,roomb,left,3)).
neg(drop(ball1,roomb,left,4)).
neg(drop(ball1,roomb,left,5)).
neg(drop(ball1,roomb,left,6)).
neg(drop(ball1,roomb,left,7)).
neg(drop(ball1,roomb,left,8)).
neg(drop(ball1,roomb,left,9)).
neg(drop(ball2,rooma,left,0)).
neg(drop(ball2,rooma,left,1)).
neg(drop(ball2,rooma,left,10)).
neg(drop(ball2,rooma,left,11)).
neg(drop(ball2,rooma,left,12)).
neg(drop(ball2,rooma,left,13)).
neg(drop(ball2,rooma,left,14)).
neg(drop(ball2,rooma,left,15)).
neg(drop(ball2,rooma,left,16)).
neg(drop(ball2,rooma,left,17)).
neg(drop(ball2,rooma,left,18)).
neg(drop(ball2,rooma,left,19)).
neg(drop(ball2,rooma,left,2)).
neg(drop(ball2,rooma,left,20)).
neg(drop(ball2,rooma,left,21)).
neg(drop(ball2,rooma,left,22)).
neg(drop(ball2,rooma,left,23)).
neg(drop(ball2,rooma,left,24)).
neg(drop(ball2,rooma,left,25)).
neg(drop(ball2,rooma,left,3)).
neg(drop(ball2,rooma,left,4)).
neg(drop(ball2,rooma,left,5)).
neg(drop(ball2,rooma,left,6)).
neg(drop(ball2,rooma,left,7)).
neg(drop(ball2,rooma,left,8)).
neg(drop(ball2,rooma,left,9)).
neg(drop(ball2,roomb,left,0)).
neg(drop(ball2,roomb,left,1)).
neg(drop(ball2,roomb,left,10)).
neg(drop(ball2,roomb,left,11)).
neg(drop(ball2,roomb,left,12)).
neg(drop(ball2,roomb,left,13)).
neg(drop(ball2,roomb,left,14)).
neg(drop(ball2,roomb,left,15)).
neg(drop(ball2,roomb,left,16)).
neg(drop(ball2,roomb,left,18)).
neg(drop(ball2,roomb,left,19)).
neg(drop(ball2,roomb,left,2)).
neg(drop(ball2,roomb,left,20)).
neg(drop(ball2,roomb,left,21)).
neg(drop(ball2,roomb,left,22)).
neg(drop(ball2,roomb,left,23)).
neg(drop(ball2,roomb,left,24)).
neg(drop(ball2,roomb,left,25)).
neg(drop(ball2,roomb,left,3)).
neg(drop(ball2,roomb,left,4)).
neg(drop(ball2,roomb,left,5)).
neg(drop(ball2,roomb,left,7)).
neg(drop(ball2,roomb,left,8)).
neg(drop(ball2,roomb,left,9)).
neg(drop(ball3,rooma,left,0)).
neg(drop(ball3,rooma,left,1)).
neg(drop(ball3,rooma,left,10)).
neg(drop(ball3,rooma,left,11)).
neg(drop(ball3,rooma,left,12)).
neg(drop(ball3,rooma,left,13)).
neg(drop(ball3,rooma,left,14)).
neg(drop(ball3,rooma,left,15)).
neg(drop(ball3,rooma,left,16)).
neg(drop(ball3,rooma,left,17)).
neg(drop(ball3,rooma,left,18)).
neg(drop(ball3,rooma,left,19)).
neg(drop(ball3,rooma,left,2)).
neg(drop(ball3,rooma,left,20)).
neg(drop(ball3,rooma,left,21)).
neg(drop(ball3,rooma,left,22)).
neg(drop(ball3,rooma,left,23)).
neg(drop(ball3,rooma,left,24)).
neg(drop(ball3,rooma,left,25)).
neg(drop(ball3,rooma,left,3)).
neg(drop(ball3,rooma,left,4)).
neg(drop(ball3,rooma,left,5)).
neg(drop(ball3,rooma,left,6)).
neg(drop(ball3,rooma,left,7)).
neg(drop(ball3,rooma,left,8)).
neg(drop(ball3,rooma,left,9)).
neg(drop(ball3,roomb,left,0)).
neg(drop(ball3,roomb,left,1)).
neg(drop(ball3,roomb,left,11)).
neg(drop(ball3,roomb,left,12)).
neg(drop(ball3,roomb,left,13)).
neg(drop(ball3,roomb,left,14)).
neg(drop(ball3,roomb,left,15)).
neg(drop(ball3,roomb,left,16)).
neg(drop(ball3,roomb,left,17)).
neg(drop(ball3,roomb,left,18)).
neg(drop(ball3,roomb,left,19)).
neg(drop(ball3,roomb,left,2)).
neg(drop(ball3,roomb,left,20)).
neg(drop(ball3,roomb,left,22)).
neg(drop(ball3,roomb,left,23)).
neg(drop(ball3,roomb,left,24)).
neg(drop(ball3,roomb,left,25)).
neg(drop(ball3,roomb,left,3)).
neg(drop(ball3,roomb,left,4)).
neg(drop(ball3,roomb,left,5)).
neg(drop(ball3,roomb,left,6)).
neg(drop(ball3,roomb,left,7)).
neg(drop(ball3,roomb,left,8)).
neg(drop(ball3,roomb,left,9)).
neg(drop(ball4,rooma,left,0)).
neg(drop(ball4,rooma,left,1)).
neg(drop(ball4,rooma,left,10)).
neg(drop(ball4,rooma,left,11)).
neg(drop(ball4,rooma,left,12)).
neg(drop(ball4,rooma,left,13)).
neg(drop(ball4,rooma,left,14)).
neg(drop(ball4,rooma,left,15)).
neg(drop(ball4,rooma,left,16)).
neg(drop(ball4,rooma,left,17)).
neg(drop(ball4,rooma,left,18)).
neg(drop(ball4,rooma,left,19)).
neg(drop(ball4,rooma,left,2)).
neg(drop(ball4,rooma,left,20)).
neg(drop(ball4,rooma,left,21)).
neg(drop(ball4,rooma,left,22)).
neg(drop(ball4,rooma,left,23)).
neg(drop(ball4,rooma,left,24)).
neg(drop(ball4,rooma,left,25)).
neg(drop(ball4,rooma,left,3)).
neg(drop(ball4,rooma,left,4)).
neg(drop(ball4,rooma,left,5)).
neg(drop(ball4,rooma,left,6)).
neg(drop(ball4,rooma,left,7)).
neg(drop(ball4,rooma,left,8)).
neg(drop(ball4,rooma,left,9)).
neg(drop(ball4,roomb,left,0)).
neg(drop(ball4,roomb,left,1)).
neg(drop(ball4,roomb,left,10)).
neg(drop(ball4,roomb,left,11)).
neg(drop(ball4,roomb,left,12)).
neg(drop(ball4,roomb,left,13)).
neg(drop(ball4,roomb,left,14)).
neg(drop(ball4,roomb,left,15)).
neg(drop(ball4,roomb,left,16)).
neg(drop(ball4,roomb,left,17)).
neg(drop(ball4,roomb,left,18)).
neg(drop(ball4,roomb,left,19)).
neg(drop(ball4,roomb,left,2)).
neg(drop(ball4,roomb,left,20)).
neg(drop(ball4,roomb,left,21)).
neg(drop(ball4,roomb,left,22)).
neg(drop(ball4,roomb,left,23)).
neg(drop(ball4,roomb,left,24)).
neg(drop(ball4,roomb,left,3)).
neg(drop(ball4,roomb,left,4)).
neg(drop(ball4,roomb,left,5)).
neg(drop(ball4,roomb,left,6)).
neg(drop(ball4,roomb,left,7)).
neg(drop(ball4,roomb,left,8)).
neg(drop(ball4,roomb,left,9)).
