pos(great_ne(z1,t1)).
pos(great_ne(t1,hh1)).
pos(great_ne(jj1,kk1)).
pos(great_ne(hh1,k1)).
pos(great_ne(hh1,dd1)).
pos(great_ne(m1,a1)).
pos(great_ne(cc1,jj1)).
pos(great_ne(x1,f1)).
pos(great_ne(v1,f1)).
pos(great_ne(u1,y1)).
pos(great_ne(t1,m1)).
pos(great_ne(bb1,w1)).
pos(great_ne(k1,a1)).
pos(great_ne(kk1,b1)).
pos(great_ne(bb1,v1)).
pos(great_ne(z1,a1)).
pos(great_ne(b1,c1)).
pos(great_ne(aa1,hh1)).
pos(great_ne(kk1,a1)).
pos(great_ne(bb1,y1)).
pos(great_ne(q1,w1)).
pos(great_ne(bb1,i1)).
pos(great_ne(kk1,w1)).
pos(great_ne(ee1,c1)).
pos(great_ne(q1,cc1)).
pos(great_ne(cc1,y1)).
pos(great_ne(ee1,m1)).
pos(great_ne(kk1,m1)).
pos(great_ne(dd1,bb1)).
pos(great_ne(q1,y1)).
pos(great_ne(m1,f1)).
pos(great_ne(ee1,x1)).
pos(great_ne(kk1,v1)).
pos(great_ne(t1,c1)).
pos(great_ne(dd1,m1)).
pos(great_ne(z1,cc1)).
pos(great_ne(hh1,ff1)).
pos(great_ne(ee1,y1)).
pos(great_ne(x1,v1)).
pos(great_ne(y1,f1)).
pos(great_ne(cc1,kk1)).
pos(great_ne(u1,ii1)).
pos(great_ne(cc1,ff1)).
pos(great_ne(x1,w1)).
pos(great_ne(u1,bb1)).
pos(great_ne(m1,i1)).
pos(great_ne(k1,x1)).
pos(great_ne(dd1,ii1)).
pos(great_ne(hh1,w1)).
pos(great_ne(hh1,h1)).
pos(great_ne(t1,y1)).
pos(great_ne(f1,c1)).
pos(great_ne(z1,y1)).
pos(great_ne(m1,c1)).
pos(great_ne(z1,b1)).
pos(great_ne(dd1,h1)).
pos(great_ne(aa1,f1)).
pos(great_ne(aa1,ee1)).
pos(great_ne(jj1,k1)).
pos(great_ne(k1,w1)).
pos(great_ne(v1,b1)).
pos(great_ne(b1,a1)).
pos(great_ne(ee1,bb1)).
pos(great_ne(jj1,a1)).
pos(great_ne(y1,h1)).
pos(great_ne(dd1,f1)).
pos(great_ne(ee1,ff1)).
pos(great_ne(aa1,a1)).
pos(great_ne(jj1,c1)).
pos(great_ne(ff1,c1)).
pos(great_ne(q1,ff1)).
pos(great_ne(ee1,w1)).
pos(great_ne(ii1,a1)).
pos(great_ne(aa1,ii1)).
pos(great_ne(q1,i1)).
pos(great_ne(cc1,aa1)).
pos(great_ne(z1,jj1)).
pos(great_ne(p1,v1)).
pos(great_ne(p1,ee1)).
pos(great_ne(ee1,b1)).
pos(great_ne(q1,h1)).
pos(great_ne(ee1,f1)).
pos(great_ne(p1,f1)).
pos(great_ne(hh1,ii1)).
pos(great_ne(jj1,w1)).
pos(great_ne(cc1,f1)).
pos(great_ne(q1,k1)).
pos(great_ne(z1,dd1)).
pos(great_ne(cc1,v1)).
pos(great_ne(q1,b1)).
pos(great_ne(p1,aa1)).
pos(great_ne(kk1,h1)).
pos(great_ne(v1,c1)).
pos(great_ne(q1,c1)).
pos(great_ne(t1,b1)).
pos(great_ne(jj1,b1)).
pos(great_ne(p1,hh1)).
pos(great_ne(p1,k1)).
pos(great_ne(aa1,ff1)).
pos(great_ne(v1,w1)).
pos(great_ne(q1,z1)).
pos(great_ne(t1,f1)).
pos(great_ne(aa1,b1)).
pos(great_ne(kk1,k1)).
pos(great_ne(kk1,hh1)).
pos(great_ne(hh1,a1)).
pos(great_ne(w1,ff1)).
pos(great_ne(z1,x1)).
pos(great_ne(t1,ee1)).
pos(great_ne(w1,h1)).
pos(great_ne(ff1,a1)).
pos(great_ne(m1,ii1)).
pos(great_ne(z1,u1)).
pos(great_ne(cc1,hh1)).
pos(great_ne(t1,ii1)).
pos(great_ne(u1,jj1)).
pos(great_ne(m1,h1)).
pos(great_ne(z1,hh1)).
pos(great_ne(aa1,m1)).
pos(great_ne(q1,t1)).
pos(great_ne(z1,ff1)).
pos(great_ne(q1,x1)).
pos(great_ne(bb1,ii1)).
pos(great_ne(t1,kk1)).
pos(great_ne(z1,p1)).
pos(great_ne(w1,a1)).
pos(great_ne(dd1,k1)).
pos(great_ne(m1,v1)).
pos(great_ne(ff1,h1)).
pos(great_ne(w1,b1)).
pos(great_ne(k1,ii1)).
pos(great_ne(bb1,a1)).
pos(great_ne(t1,jj1)).
pos(great_ne(bb1,x1)).
pos(great_ne(k1,c1)).
pos(great_ne(b1,ff1)).
pos(great_ne(u1,v1)).
pos(great_ne(hh1,x1)).
pos(great_ne(dd1,w1)).
pos(great_ne(y1,a1)).
pos(great_ne(m1,y1)).
pos(great_ne(u1,aa1)).
pos(great_ne(f1,a1)).
pos(great_ne(jj1,m1)).
pos(great_ne(q1,p1)).
pos(great_ne(bb1,b1)).
pos(great_ne(y1,b1)).
pos(great_ne(cc1,w1)).
pos(great_ne(p1,u1)).
pos(great_ne(z1,w1)).
pos(great_ne(y1,w1)).
pos(great_ne(ee1,v1)).
pos(great_ne(ee1,hh1)).
pos(great_ne(ii1,c1)).
pos(great_ne(cc1,b1)).
pos(great_ne(jj1,v1)).
pos(great_ne(t1,u1)).
pos(great_ne(x1,i1)).
pos(great_ne(x1,c1)).
pos(great_ne(t1,v1)).
pos(great_ne(ii1,i1)).
pos(great_ne(hh1,m1)).
pos(great_ne(q1,ee1)).
pos(great_ne(y1,ff1)).
pos(great_ne(ii1,w1)).
pos(great_ne(p1,bb1)).
pos(great_ne(t1,a1)).
pos(great_ne(k1,i1)).
pos(great_ne(m1,ff1)).
pos(great_ne(bb1,k1)).
pos(great_ne(q1,ii1)).
pos(great_ne(aa1,x1)).
pos(great_ne(dd1,i1)).
pos(great_ne(u1,m1)).
pos(great_ne(q1,hh1)).
pos(great_ne(q1,a1)).
pos(great_ne(q1,aa1)).
pos(great_ne(q1,u1)).
pos(great_ne(v1,ff1)).
pos(great_ne(q1,kk1)).
pos(great_ne(t1,k1)).
pos(great_ne(aa1,kk1)).
pos(great_ne(q1,v1)).
pos(great_ne(u1,ee1)).
pos(great_ne(ee1,ii1)).
pos(great_ne(k1,ff1)).
pos(great_ne(z1,aa1)).
pos(great_ne(f1,h1)).
pos(great_ne(p1,y1)).
pos(great_ne(dd1,y1)).
pos(great_ne(k1,y1)).
pos(great_ne(aa1,k1)).
pos(great_ne(jj1,dd1)).
pos(great_ne(dd1,b1)).
pos(great_ne(f1,ff1)).
pos(great_ne(z1,c1)).
pos(great_ne(bb1,m1)).
pos(great_ne(x1,b1)).
pos(great_ne(ii1,f1)).
pos(great_ne(x1,h1)).
pos(great_ne(k1,f1)).
pos(great_ne(hh1,bb1)).
pos(great_ne(z1,h1)).
pos(great_ne(z1,bb1)).
pos(great_ne(w1,i1)).
pos(great_ne(u1,dd1)).
pos(great_ne(ee1,kk1)).
pos(great_ne(aa1,dd1)).
pos(great_ne(aa1,w1)).
pos(great_ne(kk1,f1)).
pos(great_ne(q1,dd1)).
pos(great_ne(t1,x1)).
pos(great_ne(dd1,a1)).
pos(great_ne(cc1,t1)).
pos(great_ne(x1,ff1)).
pos(great_ne(cc1,c1)).
pos(great_ne(hh1,c1)).
pos(great_ne(z1,ee1)).
pos(great_ne(jj1,i1)).
pos(great_ne(p1,b1)).
pos(great_ne(u1,h1)).
pos(great_ne(hh1,b1)).
pos(great_ne(k1,m1)).
pos(great_ne(t1,h1)).
pos(great_ne(t1,bb1)).
pos(great_ne(t1,dd1)).
pos(great_ne(p1,c1)).
pos(great_ne(m1,w1)).
pos(great_ne(ii1,b1)).
pos(great_ne(cc1,ii1)).
pos(great_ne(u1,c1)).
pos(great_ne(b1,i1)).
pos(great_ne(jj1,bb1)).
pos(great_ne(jj1,ee1)).
pos(great_ne(jj1,aa1)).
pos(great_ne(ee1,h1)).
pos(great_ne(ii1,y1)).
pos(great_ne(jj1,h1)).
pos(great_ne(aa1,i1)).
pos(great_ne(dd1,c1)).
pos(great_ne(p1,w1)).
pos(great_ne(b1,h1)).
pos(great_ne(kk1,c1)).
pos(great_ne(q1,jj1)).
pos(great_ne(hh1,i1)).
pos(great_ne(cc1,u1)).
pos(great_ne(ee1,a1)).
pos(great_ne(ee1,k1)).
pos(great_ne(z1,kk1)).
pos(great_ne(bb1,c1)).
pos(great_ne(cc1,bb1)).
pos(great_ne(p1,jj1)).
pos(great_ne(t1,aa1)).
pos(great_ne(cc1,dd1)).
pos(great_ne(u1,w1)).
pos(great_ne(y1,i1)).
pos(great_ne(cc1,k1)).
pos(great_ne(p1,i1)).
pos(great_ne(kk1,ff1)).
pos(great_ne(cc1,m1)).
pos(great_ne(kk1,x1)).
pos(great_ne(w1,f1)).
pos(great_ne(m1,b1)).
pos(great_ne(q1,f1)).
pos(great_ne(aa1,c1)).
pos(great_ne(cc1,ee1)).
pos(great_ne(f1,i1)).
pos(great_ne(p1,cc1)).
pos(great_ne(t1,w1)).
pos(great_ne(q1,bb1)).
pos(great_ne(z1,k1)).
pos(great_ne(aa1,v1)).
pos(great_ne(jj1,hh1)).
pos(great_ne(p1,t1)).
neg(great_ne(b1,p1)).
neg(great_ne(ee1,cc1)).
neg(great_ne(bb1,dd1)).
neg(great_ne(f1,dd1)).
neg(great_ne(ff1,bb1)).
neg(great_ne(x1,cc1)).
neg(great_ne(b1,t1)).
neg(great_ne(w1,y1)).
neg(great_ne(ff1,dd1)).
neg(great_ne(c1,w1)).
neg(great_ne(u1,q1)).
neg(great_ne(k1,t1)).
neg(great_ne(b1,m1)).
neg(great_ne(t1,cc1)).
neg(great_ne(dd1,t1)).
neg(great_ne(ii1,p1)).
neg(great_ne(v1,x1)).
neg(great_ne(kk1,q1)).
neg(great_ne(a1,ee1)).
neg(great_ne(ii1,aa1)).
neg(great_ne(bb1,t1)).
neg(great_ne(i1,y1)).
neg(great_ne(f1,ee1)).
neg(great_ne(p1,q1)).
neg(great_ne(kk1,jj1)).
neg(great_ne(hh1,q1)).
neg(great_ne(i1,w1)).
neg(great_ne(p1,z1)).
neg(great_ne(hh1,z1)).
neg(great_ne(bb1,cc1)).
neg(great_ne(c1,v1)).
neg(great_ne(cc1,p1)).
neg(great_ne(f1,w1)).
neg(great_ne(x1,kk1)).
neg(great_ne(c1,p1)).
neg(great_ne(b1,ii1)).
neg(great_ne(y1,hh1)).
neg(great_ne(u1,z1)).
neg(great_ne(ff1,f1)).
neg(great_ne(y1,ee1)).
neg(great_ne(c1,ff1)).
neg(great_ne(aa1,z1)).
neg(great_ne(dd1,hh1)).
neg(great_ne(w1,v1)).
neg(great_ne(ee1,aa1)).
neg(great_ne(t1,p1)).
neg(great_ne(ff1,aa1)).
neg(great_ne(w1,ee1)).
neg(great_ne(k1,kk1)).
neg(great_ne(dd1,cc1)).
neg(great_ne(h1,kk1)).
neg(great_ne(i1,z1)).
neg(great_ne(b1,ee1)).
neg(great_ne(a1,k1)).
neg(great_ne(u1,p1)).
neg(great_ne(h1,u1)).
neg(great_ne(f1,bb1)).
neg(great_ne(b1,cc1)).
neg(great_ne(bb1,kk1)).
neg(great_ne(a1,aa1)).
neg(great_ne(c1,jj1)).
neg(great_ne(h1,hh1)).
neg(great_ne(m1,jj1)).
neg(great_ne(m1,k1)).
neg(great_ne(b1,hh1)).
neg(great_ne(bb1,p1)).
neg(great_ne(m1,aa1)).
neg(great_ne(ff1,kk1)).
neg(great_ne(h1,cc1)).
neg(great_ne(y1,jj1)).
neg(great_ne(k1,z1)).
neg(great_ne(a1,p1)).
neg(great_ne(b1,q1)).
neg(great_ne(a1,w1)).
neg(great_ne(m1,q1)).
neg(great_ne(h1,p1)).
neg(great_ne(i1,jj1)).
neg(great_ne(w1,x1)).
neg(great_ne(u1,t1)).
neg(great_ne(k1,p1)).
neg(great_ne(ii1,cc1)).
neg(great_ne(c1,kk1)).
neg(great_ne(a1,m1)).
neg(great_ne(v1,u1)).
neg(great_ne(w1,bb1)).
neg(great_ne(y1,z1)).
neg(great_ne(a1,f1)).
neg(great_ne(f1,hh1)).
neg(great_ne(w1,jj1)).
neg(great_ne(i1,bb1)).
neg(great_ne(ff1,ee1)).
neg(great_ne(v1,m1)).
neg(great_ne(i1,aa1)).
neg(great_ne(w1,aa1)).
neg(great_ne(bb1,u1)).
neg(great_ne(b1,x1)).
neg(great_ne(ii1,m1)).
neg(great_ne(x1,u1)).
neg(great_ne(ii1,t1)).
neg(great_ne(y1,u1)).
neg(great_ne(i1,p1)).
neg(great_ne(y1,v1)).
neg(great_ne(dd1,q1)).
neg(great_ne(w1,q1)).
neg(great_ne(hh1,cc1)).
neg(great_ne(h1,t1)).
neg(great_ne(a1,jj1)).
neg(great_ne(ee1,z1)).
neg(great_ne(ii1,x1)).
neg(great_ne(f1,q1)).
neg(great_ne(c1,k1)).
neg(great_ne(h1,dd1)).
neg(great_ne(aa1,cc1)).
neg(great_ne(m1,dd1)).
neg(great_ne(kk1,cc1)).
neg(great_ne(hh1,ee1)).
neg(great_ne(m1,bb1)).
neg(great_ne(ff1,hh1)).
neg(great_ne(x1,t1)).
neg(great_ne(h1,q1)).
neg(great_ne(v1,z1)).
neg(great_ne(i1,hh1)).
neg(great_ne(v1,aa1)).
neg(great_ne(a1,dd1)).
neg(great_ne(bb1,jj1)).
neg(great_ne(k1,bb1)).
neg(great_ne(a1,q1)).
neg(great_ne(ee1,jj1)).
neg(great_ne(x1,hh1)).
neg(great_ne(i1,k1)).
neg(great_ne(b1,dd1)).
neg(great_ne(f1,m1)).
neg(great_ne(h1,k1)).
neg(great_ne(ff1,k1)).
neg(great_ne(k1,jj1)).
neg(great_ne(ii1,kk1)).
neg(great_ne(f1,cc1)).
neg(great_ne(hh1,p1)).
neg(great_ne(a1,t1)).
neg(great_ne(c1,ee1)).
neg(great_ne(v1,q1)).
neg(great_ne(ii1,v1)).
neg(great_ne(jj1,p1)).
neg(great_ne(ff1,u1)).
neg(great_ne(ii1,hh1)).
neg(great_ne(ff1,x1)).
neg(great_ne(aa1,q1)).
neg(great_ne(v1,jj1)).
neg(great_ne(v1,bb1)).
neg(great_ne(c1,dd1)).
neg(great_ne(b1,y1)).
neg(great_ne(c1,x1)).
neg(great_ne(h1,y1)).
neg(great_ne(i1,b1)).
neg(great_ne(i1,t1)).
neg(great_ne(a1,kk1)).
neg(great_ne(dd1,u1)).
neg(great_ne(dd1,ee1)).
neg(great_ne(x1,ee1)).
neg(great_ne(b1,w1)).
neg(great_ne(k1,dd1)).
neg(great_ne(z1,q1)).
neg(great_ne(a1,ff1)).
neg(great_ne(i1,kk1)).
neg(great_ne(i1,cc1)).
neg(great_ne(m1,hh1)).
neg(great_ne(y1,x1)).
neg(great_ne(f1,x1)).
neg(great_ne(a1,u1)).
neg(great_ne(i1,x1)).
neg(great_ne(i1,ee1)).
neg(great_ne(kk1,ee1)).
neg(great_ne(h1,b1)).
neg(great_ne(ff1,m1)).
neg(great_ne(kk1,z1)).
neg(great_ne(a1,cc1)).
neg(great_ne(dd1,kk1)).
neg(great_ne(h1,ee1)).
neg(great_ne(w1,dd1)).
neg(great_ne(h1,x1)).
neg(great_ne(w1,m1)).
neg(great_ne(h1,w1)).
neg(great_ne(ff1,ii1)).
neg(great_ne(bb1,hh1)).
neg(great_ne(f1,u1)).
neg(great_ne(f1,p1)).
neg(great_ne(a1,b1)).
neg(great_ne(m1,cc1)).
neg(great_ne(h1,f1)).
neg(great_ne(kk1,aa1)).
neg(great_ne(w1,p1)).
neg(great_ne(h1,aa1)).
neg(great_ne(b1,jj1)).
neg(great_ne(dd1,aa1)).
neg(great_ne(jj1,q1)).
neg(great_ne(jj1,t1)).
neg(great_ne(v1,p1)).
neg(great_ne(k1,aa1)).
neg(great_ne(m1,p1)).
neg(great_ne(k1,u1)).
neg(great_ne(v1,k1)).
neg(great_ne(hh1,t1)).
neg(great_ne(m1,ee1)).
neg(great_ne(i1,v1)).
neg(great_ne(b1,bb1)).
neg(great_ne(y1,dd1)).
neg(great_ne(i1,m1)).
neg(great_ne(y1,aa1)).
neg(great_ne(f1,aa1)).
neg(great_ne(c1,aa1)).
neg(great_ne(ff1,jj1)).
neg(great_ne(ii1,z1)).
neg(great_ne(c1,y1)).
neg(great_ne(ff1,z1)).
neg(great_ne(a1,bb1)).
neg(great_ne(k1,hh1)).
neg(great_ne(ee1,t1)).
neg(great_ne(a1,z1)).
neg(great_ne(h1,bb1)).
neg(great_ne(ee1,u1)).
neg(great_ne(x1,q1)).
neg(great_ne(ff1,cc1)).
neg(great_ne(ff1,p1)).
neg(great_ne(hh1,jj1)).
neg(great_ne(v1,kk1)).
neg(great_ne(jj1,cc1)).
neg(great_ne(f1,k1)).
neg(great_ne(h1,jj1)).
neg(great_ne(y1,q1)).
neg(great_ne(ii1,bb1)).
neg(great_ne(cc1,z1)).
neg(great_ne(f1,ii1)).
neg(great_ne(y1,k1)).
neg(great_ne(v1,ee1)).
neg(great_ne(w1,t1)).
neg(great_ne(b1,aa1)).
neg(great_ne(c1,bb1)).
neg(great_ne(ee1,p1)).
neg(great_ne(aa1,t1)).
neg(great_ne(y1,t1)).
neg(great_ne(ff1,w1)).
neg(great_ne(c1,hh1)).
neg(great_ne(f1,t1)).
neg(great_ne(w1,hh1)).
neg(great_ne(h1,m1)).
neg(great_ne(m1,t1)).
neg(great_ne(b1,k1)).
neg(great_ne(c1,f1)).
neg(great_ne(w1,k1)).
neg(great_ne(i1,u1)).
neg(great_ne(a1,x1)).
neg(great_ne(w1,kk1)).
neg(great_ne(y1,ii1)).
neg(great_ne(x1,k1)).
neg(great_ne(ii1,dd1)).
neg(great_ne(aa1,u1)).
neg(great_ne(y1,p1)).
neg(great_ne(hh1,u1)).
neg(great_ne(f1,y1)).
neg(great_ne(f1,kk1)).
neg(great_ne(m1,kk1)).
neg(great_ne(ff1,v1)).
neg(great_ne(c1,u1)).
neg(great_ne(cc1,q1)).
neg(great_ne(k1,cc1)).
neg(great_ne(i1,dd1)).
neg(great_ne(a1,ii1)).
neg(great_ne(dd1,p1)).
neg(great_ne(w1,u1)).
neg(great_ne(aa1,p1)).
neg(great_ne(bb1,ee1)).
neg(great_ne(y1,m1)).
neg(great_ne(k1,ee1)).
neg(great_ne(kk1,p1)).
