neg(next_cell(1,a, blank)).
neg(next_cell(1,a, red)).
neg(next_cell(1,b, black)).
neg(next_cell(1,b, blank)).
neg(next_cell(1,c, black)).
neg(next_cell(1,c, red)).
neg(next_cell(1,d, black)).
neg(next_cell(1,d, blank)).
neg(next_cell(1,e, blank)).
neg(next_cell(1,e, red)).
neg(next_cell(10,a, blank)).
neg(next_cell(10,a, red)).
neg(next_cell(10,b, black)).
neg(next_cell(10,b, blank)).
neg(next_cell(10,c, blank)).
neg(next_cell(10,c, red)).
neg(next_cell(10,d, black)).
neg(next_cell(10,d, red)).
neg(next_cell(10,e, black)).
neg(next_cell(10,e, blank)).
neg(next_cell(100,a, blank)).
neg(next_cell(100,a, red)).
neg(next_cell(100,b, blank)).
neg(next_cell(100,b, red)).
neg(next_cell(100,c, black)).
neg(next_cell(100,c, blank)).
neg(next_cell(100,d, black)).
neg(next_cell(100,d, red)).
neg(next_cell(100,e, black)).
neg(next_cell(100,e, blank)).
neg(next_cell(101,a, blank)).
neg(next_cell(101,a, red)).
neg(next_cell(101,b, black)).
neg(next_cell(101,b, red)).
neg(next_cell(101,c, blank)).
neg(next_cell(101,c, red)).
neg(next_cell(101,d, black)).
neg(next_cell(101,d, blank)).
neg(next_cell(101,e, black)).
neg(next_cell(101,e, blank)).
neg(next_cell(102,a, blank)).
neg(next_cell(102,a, red)).
neg(next_cell(102,b, black)).
neg(next_cell(102,b, blank)).
neg(next_cell(102,c, blank)).
neg(next_cell(102,c, red)).
neg(next_cell(102,d, black)).
neg(next_cell(102,d, blank)).
neg(next_cell(102,e, black)).
neg(next_cell(102,e, red)).
neg(next_cell(103,a, black)).
neg(next_cell(103,a, blank)).
neg(next_cell(103,a, red)).
neg(next_cell(103,b, black)).
neg(next_cell(103,b, blank)).
neg(next_cell(103,b, red)).
neg(next_cell(103,c, black)).
neg(next_cell(103,c, blank)).
neg(next_cell(103,c, red)).
neg(next_cell(103,d, black)).
neg(next_cell(103,d, blank)).
neg(next_cell(103,d, red)).
neg(next_cell(103,e, black)).
neg(next_cell(103,e, blank)).
neg(next_cell(103,e, red)).
neg(next_cell(104,a, black)).
neg(next_cell(104,a, red)).
neg(next_cell(104,b, black)).
neg(next_cell(104,b, blank)).
neg(next_cell(104,c, black)).
neg(next_cell(104,c, blank)).
neg(next_cell(104,d, blank)).
neg(next_cell(104,d, red)).
neg(next_cell(104,e, blank)).
neg(next_cell(104,e, red)).
neg(next_cell(105,a, black)).
neg(next_cell(105,a, red)).
neg(next_cell(105,b, blank)).
neg(next_cell(105,b, red)).
neg(next_cell(105,c, blank)).
neg(next_cell(105,c, red)).
neg(next_cell(105,d, black)).
neg(next_cell(105,d, blank)).
neg(next_cell(105,e, black)).
neg(next_cell(105,e, blank)).
neg(next_cell(106,a, black)).
neg(next_cell(106,a, red)).
neg(next_cell(106,b, black)).
neg(next_cell(106,b, blank)).
neg(next_cell(106,c, blank)).
neg(next_cell(106,c, red)).
neg(next_cell(106,d, black)).
neg(next_cell(106,d, blank)).
neg(next_cell(106,e, blank)).
neg(next_cell(106,e, red)).
neg(next_cell(107,a, black)).
neg(next_cell(107,a, blank)).
neg(next_cell(107,a, red)).
neg(next_cell(107,b, black)).
neg(next_cell(107,b, blank)).
neg(next_cell(107,b, red)).
neg(next_cell(107,c, black)).
neg(next_cell(107,c, blank)).
neg(next_cell(107,c, red)).
neg(next_cell(107,d, black)).
neg(next_cell(107,d, blank)).
neg(next_cell(107,d, red)).
neg(next_cell(107,e, black)).
neg(next_cell(107,e, blank)).
neg(next_cell(107,e, red)).
neg(next_cell(108,a, black)).
neg(next_cell(108,a, blank)).
neg(next_cell(108,b, black)).
neg(next_cell(108,b, red)).
neg(next_cell(108,c, blank)).
neg(next_cell(108,c, red)).
neg(next_cell(108,d, black)).
neg(next_cell(108,d, blank)).
neg(next_cell(108,e, blank)).
neg(next_cell(108,e, red)).
neg(next_cell(109,a, blank)).
neg(next_cell(109,a, red)).
neg(next_cell(109,b, black)).
neg(next_cell(109,b, blank)).
neg(next_cell(109,c, black)).
neg(next_cell(109,c, blank)).
neg(next_cell(109,d, blank)).
neg(next_cell(109,d, red)).
neg(next_cell(109,e, black)).
neg(next_cell(109,e, red)).
neg(next_cell(11,a, blank)).
neg(next_cell(11,a, red)).
neg(next_cell(11,b, black)).
neg(next_cell(11,b, blank)).
neg(next_cell(11,c, blank)).
neg(next_cell(11,c, red)).
neg(next_cell(11,d, black)).
neg(next_cell(11,d, red)).
neg(next_cell(11,e, black)).
neg(next_cell(11,e, blank)).
neg(next_cell(110,a, black)).
neg(next_cell(110,a, blank)).
neg(next_cell(110,a, red)).
neg(next_cell(110,b, black)).
neg(next_cell(110,b, blank)).
neg(next_cell(110,b, red)).
neg(next_cell(110,c, black)).
neg(next_cell(110,c, blank)).
neg(next_cell(110,c, red)).
neg(next_cell(110,d, black)).
neg(next_cell(110,d, blank)).
neg(next_cell(110,d, red)).
neg(next_cell(110,e, black)).
neg(next_cell(110,e, blank)).
neg(next_cell(110,e, red)).
neg(next_cell(111,a, black)).
neg(next_cell(111,a, blank)).
neg(next_cell(111,b, blank)).
neg(next_cell(111,b, red)).
neg(next_cell(111,c, blank)).
neg(next_cell(111,c, red)).
neg(next_cell(111,d, black)).
neg(next_cell(111,d, blank)).
neg(next_cell(111,e, black)).
neg(next_cell(111,e, red)).
neg(next_cell(112,a, blank)).
neg(next_cell(112,a, red)).
neg(next_cell(112,b, black)).
neg(next_cell(112,b, blank)).
neg(next_cell(112,c, black)).
neg(next_cell(112,c, red)).
neg(next_cell(112,d, blank)).
neg(next_cell(112,d, red)).
neg(next_cell(112,e, black)).
neg(next_cell(112,e, blank)).
neg(next_cell(113,a, blank)).
neg(next_cell(113,a, red)).
neg(next_cell(113,b, black)).
neg(next_cell(113,b, blank)).
neg(next_cell(113,c, blank)).
neg(next_cell(113,c, red)).
neg(next_cell(113,d, black)).
neg(next_cell(113,d, red)).
neg(next_cell(113,e, black)).
neg(next_cell(113,e, blank)).
neg(next_cell(114,a, blank)).
neg(next_cell(114,a, red)).
neg(next_cell(114,b, black)).
neg(next_cell(114,b, red)).
neg(next_cell(114,c, black)).
neg(next_cell(114,c, blank)).
neg(next_cell(114,d, black)).
neg(next_cell(114,d, blank)).
neg(next_cell(114,e, blank)).
neg(next_cell(114,e, red)).
neg(next_cell(115,a, black)).
neg(next_cell(115,a, red)).
neg(next_cell(115,b, blank)).
neg(next_cell(115,b, red)).
neg(next_cell(115,c, black)).
neg(next_cell(115,c, blank)).
neg(next_cell(115,d, blank)).
neg(next_cell(115,d, red)).
neg(next_cell(115,e, black)).
neg(next_cell(115,e, blank)).
neg(next_cell(116,a, black)).
neg(next_cell(116,a, red)).
neg(next_cell(116,b, blank)).
neg(next_cell(116,b, red)).
neg(next_cell(116,c, black)).
neg(next_cell(116,c, blank)).
neg(next_cell(116,d, blank)).
neg(next_cell(116,d, red)).
neg(next_cell(116,e, black)).
neg(next_cell(116,e, blank)).
neg(next_cell(117,a, black)).
neg(next_cell(117,a, blank)).
neg(next_cell(117,b, blank)).
neg(next_cell(117,b, red)).
neg(next_cell(117,c, black)).
neg(next_cell(117,c, red)).
neg(next_cell(117,d, black)).
neg(next_cell(117,d, blank)).
neg(next_cell(117,e, blank)).
neg(next_cell(117,e, red)).
neg(next_cell(118,a, black)).
neg(next_cell(118,a, blank)).
neg(next_cell(118,b, blank)).
neg(next_cell(118,b, red)).
neg(next_cell(118,c, black)).
neg(next_cell(118,c, red)).
neg(next_cell(118,d, blank)).
neg(next_cell(118,d, red)).
neg(next_cell(118,e, black)).
neg(next_cell(118,e, blank)).
neg(next_cell(119,a, blank)).
neg(next_cell(119,a, red)).
neg(next_cell(119,b, black)).
neg(next_cell(119,b, blank)).
neg(next_cell(119,c, black)).
neg(next_cell(119,c, red)).
neg(next_cell(119,d, black)).
neg(next_cell(119,d, blank)).
neg(next_cell(119,e, blank)).
neg(next_cell(119,e, red)).
neg(next_cell(12,a, black)).
neg(next_cell(12,a, blank)).
neg(next_cell(12,a, red)).
neg(next_cell(12,b, black)).
neg(next_cell(12,b, blank)).
neg(next_cell(12,b, red)).
neg(next_cell(12,c, black)).
neg(next_cell(12,c, blank)).
neg(next_cell(12,c, red)).
neg(next_cell(12,d, black)).
neg(next_cell(12,d, blank)).
neg(next_cell(12,d, red)).
neg(next_cell(12,e, black)).
neg(next_cell(12,e, blank)).
neg(next_cell(12,e, red)).
neg(next_cell(120,a, blank)).
neg(next_cell(120,a, red)).
neg(next_cell(120,b, black)).
neg(next_cell(120,b, red)).
neg(next_cell(120,c, blank)).
neg(next_cell(120,c, red)).
neg(next_cell(120,d, black)).
neg(next_cell(120,d, blank)).
neg(next_cell(120,e, black)).
neg(next_cell(120,e, blank)).
neg(next_cell(121,a, blank)).
neg(next_cell(121,a, red)).
neg(next_cell(121,b, black)).
neg(next_cell(121,b, blank)).
neg(next_cell(121,c, black)).
neg(next_cell(121,c, red)).
neg(next_cell(121,d, black)).
neg(next_cell(121,d, blank)).
neg(next_cell(121,e, blank)).
neg(next_cell(121,e, red)).
neg(next_cell(122,a, black)).
neg(next_cell(122,a, red)).
neg(next_cell(122,b, blank)).
neg(next_cell(122,b, red)).
neg(next_cell(122,c, black)).
neg(next_cell(122,c, blank)).
neg(next_cell(122,d, black)).
neg(next_cell(122,d, blank)).
neg(next_cell(122,e, blank)).
neg(next_cell(122,e, red)).
neg(next_cell(123,a, black)).
neg(next_cell(123,a, blank)).
neg(next_cell(123,a, red)).
neg(next_cell(123,b, black)).
neg(next_cell(123,b, blank)).
neg(next_cell(123,b, red)).
neg(next_cell(123,c, black)).
neg(next_cell(123,c, blank)).
neg(next_cell(123,c, red)).
neg(next_cell(123,d, black)).
neg(next_cell(123,d, blank)).
neg(next_cell(123,d, red)).
neg(next_cell(123,e, black)).
neg(next_cell(123,e, blank)).
neg(next_cell(123,e, red)).
neg(next_cell(124,a, black)).
neg(next_cell(124,a, red)).
neg(next_cell(124,b, blank)).
neg(next_cell(124,b, red)).
neg(next_cell(124,c, black)).
neg(next_cell(124,c, blank)).
neg(next_cell(124,d, black)).
neg(next_cell(124,d, blank)).
neg(next_cell(124,e, blank)).
neg(next_cell(124,e, red)).
neg(next_cell(125,a, black)).
neg(next_cell(125,a, blank)).
neg(next_cell(125,a, red)).
neg(next_cell(125,b, black)).
neg(next_cell(125,b, blank)).
neg(next_cell(125,b, red)).
neg(next_cell(125,c, black)).
neg(next_cell(125,c, blank)).
neg(next_cell(125,c, red)).
neg(next_cell(125,d, black)).
neg(next_cell(125,d, blank)).
neg(next_cell(125,d, red)).
neg(next_cell(125,e, black)).
neg(next_cell(125,e, blank)).
neg(next_cell(125,e, red)).
neg(next_cell(126,a, blank)).
neg(next_cell(126,a, red)).
neg(next_cell(126,b, black)).
neg(next_cell(126,b, blank)).
neg(next_cell(126,c, black)).
neg(next_cell(126,c, blank)).
neg(next_cell(126,d, black)).
neg(next_cell(126,d, red)).
neg(next_cell(126,e, blank)).
neg(next_cell(126,e, red)).
neg(next_cell(127,a, black)).
neg(next_cell(127,a, blank)).
neg(next_cell(127,a, red)).
neg(next_cell(127,b, black)).
neg(next_cell(127,b, blank)).
neg(next_cell(127,b, red)).
neg(next_cell(127,c, black)).
neg(next_cell(127,c, blank)).
neg(next_cell(127,c, red)).
neg(next_cell(127,d, black)).
neg(next_cell(127,d, blank)).
neg(next_cell(127,d, red)).
neg(next_cell(127,e, black)).
neg(next_cell(127,e, blank)).
neg(next_cell(127,e, red)).
neg(next_cell(128,a, blank)).
neg(next_cell(128,a, red)).
neg(next_cell(128,b, black)).
neg(next_cell(128,b, blank)).
neg(next_cell(128,c, black)).
neg(next_cell(128,c, red)).
neg(next_cell(128,d, black)).
neg(next_cell(128,d, blank)).
neg(next_cell(128,e, blank)).
neg(next_cell(128,e, red)).
neg(next_cell(129,a, black)).
neg(next_cell(129,a, blank)).
neg(next_cell(129,b, blank)).
neg(next_cell(129,b, red)).
neg(next_cell(129,c, black)).
neg(next_cell(129,c, blank)).
neg(next_cell(129,d, black)).
neg(next_cell(129,d, red)).
neg(next_cell(129,e, blank)).
neg(next_cell(129,e, red)).
neg(next_cell(13,a, black)).
neg(next_cell(13,a, blank)).
neg(next_cell(13,b, black)).
neg(next_cell(13,b, blank)).
neg(next_cell(13,c, black)).
neg(next_cell(13,c, red)).
neg(next_cell(13,d, blank)).
neg(next_cell(13,d, red)).
neg(next_cell(13,e, blank)).
neg(next_cell(13,e, red)).
neg(next_cell(130,a, blank)).
neg(next_cell(130,a, red)).
neg(next_cell(130,b, black)).
neg(next_cell(130,b, blank)).
neg(next_cell(130,c, black)).
neg(next_cell(130,c, red)).
neg(next_cell(130,d, blank)).
neg(next_cell(130,d, red)).
neg(next_cell(130,e, black)).
neg(next_cell(130,e, blank)).
neg(next_cell(131,a, black)).
neg(next_cell(131,a, red)).
neg(next_cell(131,b, blank)).
neg(next_cell(131,b, red)).
neg(next_cell(131,c, black)).
neg(next_cell(131,c, blank)).
neg(next_cell(131,d, black)).
neg(next_cell(131,d, blank)).
neg(next_cell(131,e, blank)).
neg(next_cell(131,e, red)).
neg(next_cell(132,a, black)).
neg(next_cell(132,a, blank)).
neg(next_cell(132,b, black)).
neg(next_cell(132,b, blank)).
neg(next_cell(132,c, blank)).
neg(next_cell(132,c, red)).
neg(next_cell(132,d, blank)).
neg(next_cell(132,d, red)).
neg(next_cell(132,e, black)).
neg(next_cell(132,e, red)).
neg(next_cell(133,a, blank)).
neg(next_cell(133,a, red)).
neg(next_cell(133,b, black)).
neg(next_cell(133,b, blank)).
neg(next_cell(133,c, black)).
neg(next_cell(133,c, red)).
neg(next_cell(133,d, blank)).
neg(next_cell(133,d, red)).
neg(next_cell(133,e, black)).
neg(next_cell(133,e, blank)).
neg(next_cell(134,a, black)).
neg(next_cell(134,a, blank)).
neg(next_cell(134,b, blank)).
neg(next_cell(134,b, red)).
neg(next_cell(134,c, black)).
neg(next_cell(134,c, red)).
neg(next_cell(134,d, black)).
neg(next_cell(134,d, blank)).
neg(next_cell(134,e, blank)).
neg(next_cell(134,e, red)).
neg(next_cell(135,a, black)).
neg(next_cell(135,a, red)).
neg(next_cell(135,b, blank)).
neg(next_cell(135,b, red)).
neg(next_cell(135,c, black)).
neg(next_cell(135,c, blank)).
neg(next_cell(135,d, blank)).
neg(next_cell(135,d, red)).
neg(next_cell(135,e, black)).
neg(next_cell(135,e, blank)).
neg(next_cell(136,a, black)).
neg(next_cell(136,a, blank)).
neg(next_cell(136,b, black)).
neg(next_cell(136,b, red)).
neg(next_cell(136,c, blank)).
neg(next_cell(136,c, red)).
neg(next_cell(136,d, black)).
neg(next_cell(136,d, blank)).
neg(next_cell(136,e, blank)).
neg(next_cell(136,e, red)).
neg(next_cell(137,a, blank)).
neg(next_cell(137,a, red)).
neg(next_cell(137,b, blank)).
neg(next_cell(137,b, red)).
neg(next_cell(137,c, black)).
neg(next_cell(137,c, blank)).
neg(next_cell(137,d, black)).
neg(next_cell(137,d, red)).
neg(next_cell(137,e, black)).
neg(next_cell(137,e, blank)).
neg(next_cell(138,a, black)).
neg(next_cell(138,a, red)).
neg(next_cell(138,b, black)).
neg(next_cell(138,b, blank)).
neg(next_cell(138,c, black)).
neg(next_cell(138,c, blank)).
neg(next_cell(138,d, blank)).
neg(next_cell(138,d, red)).
neg(next_cell(138,e, blank)).
neg(next_cell(138,e, red)).
neg(next_cell(139,a, blank)).
neg(next_cell(139,a, red)).
neg(next_cell(139,b, black)).
neg(next_cell(139,b, red)).
neg(next_cell(139,c, black)).
neg(next_cell(139,c, blank)).
neg(next_cell(139,d, black)).
neg(next_cell(139,d, blank)).
neg(next_cell(139,e, blank)).
neg(next_cell(139,e, red)).
neg(next_cell(14,a, black)).
neg(next_cell(14,a, red)).
neg(next_cell(14,b, blank)).
neg(next_cell(14,b, red)).
neg(next_cell(14,c, black)).
neg(next_cell(14,c, blank)).
neg(next_cell(14,d, black)).
neg(next_cell(14,d, blank)).
neg(next_cell(14,e, blank)).
neg(next_cell(14,e, red)).
neg(next_cell(140,a, blank)).
neg(next_cell(140,a, red)).
neg(next_cell(140,b, blank)).
neg(next_cell(140,b, red)).
neg(next_cell(140,c, black)).
neg(next_cell(140,c, red)).
neg(next_cell(140,d, black)).
neg(next_cell(140,d, blank)).
neg(next_cell(140,e, black)).
neg(next_cell(140,e, blank)).
neg(next_cell(141,a, blank)).
neg(next_cell(141,a, red)).
neg(next_cell(141,b, black)).
neg(next_cell(141,b, red)).
neg(next_cell(141,c, black)).
neg(next_cell(141,c, blank)).
neg(next_cell(141,d, blank)).
neg(next_cell(141,d, red)).
neg(next_cell(141,e, black)).
neg(next_cell(141,e, blank)).
neg(next_cell(142,a, blank)).
neg(next_cell(142,a, red)).
neg(next_cell(142,b, black)).
neg(next_cell(142,b, red)).
neg(next_cell(142,c, black)).
neg(next_cell(142,c, blank)).
neg(next_cell(142,d, black)).
neg(next_cell(142,d, blank)).
neg(next_cell(142,e, blank)).
neg(next_cell(142,e, red)).
neg(next_cell(143,a, blank)).
neg(next_cell(143,a, red)).
neg(next_cell(143,b, black)).
neg(next_cell(143,b, blank)).
neg(next_cell(143,c, black)).
neg(next_cell(143,c, red)).
neg(next_cell(143,d, black)).
neg(next_cell(143,d, blank)).
neg(next_cell(143,e, blank)).
neg(next_cell(143,e, red)).
neg(next_cell(144,a, blank)).
neg(next_cell(144,a, red)).
neg(next_cell(144,b, black)).
neg(next_cell(144,b, blank)).
neg(next_cell(144,c, black)).
neg(next_cell(144,c, red)).
neg(next_cell(144,d, black)).
neg(next_cell(144,d, blank)).
neg(next_cell(144,e, blank)).
neg(next_cell(144,e, red)).
neg(next_cell(145,a, black)).
neg(next_cell(145,a, red)).
neg(next_cell(145,b, black)).
neg(next_cell(145,b, blank)).
neg(next_cell(145,c, blank)).
neg(next_cell(145,c, red)).
neg(next_cell(145,d, black)).
neg(next_cell(145,d, blank)).
neg(next_cell(145,e, blank)).
neg(next_cell(145,e, red)).
neg(next_cell(146,a, blank)).
neg(next_cell(146,a, red)).
neg(next_cell(146,b, black)).
neg(next_cell(146,b, blank)).
neg(next_cell(146,c, black)).
neg(next_cell(146,c, blank)).
neg(next_cell(146,d, black)).
neg(next_cell(146,d, red)).
neg(next_cell(146,e, blank)).
neg(next_cell(146,e, red)).
neg(next_cell(147,a, blank)).
neg(next_cell(147,a, red)).
neg(next_cell(147,b, black)).
neg(next_cell(147,b, red)).
neg(next_cell(147,c, black)).
neg(next_cell(147,c, blank)).
neg(next_cell(147,d, black)).
neg(next_cell(147,d, blank)).
neg(next_cell(147,e, blank)).
neg(next_cell(147,e, red)).
neg(next_cell(148,a, black)).
neg(next_cell(148,a, blank)).
neg(next_cell(148,b, blank)).
neg(next_cell(148,b, red)).
neg(next_cell(148,c, blank)).
neg(next_cell(148,c, red)).
neg(next_cell(148,d, black)).
neg(next_cell(148,d, blank)).
neg(next_cell(148,e, black)).
neg(next_cell(148,e, red)).
neg(next_cell(149,a, blank)).
neg(next_cell(149,a, red)).
neg(next_cell(149,b, black)).
neg(next_cell(149,b, blank)).
neg(next_cell(149,c, black)).
neg(next_cell(149,c, red)).
neg(next_cell(149,d, black)).
neg(next_cell(149,d, blank)).
neg(next_cell(149,e, blank)).
neg(next_cell(149,e, red)).
neg(next_cell(15,a, black)).
neg(next_cell(15,a, blank)).
neg(next_cell(15,a, red)).
neg(next_cell(15,b, black)).
neg(next_cell(15,b, blank)).
neg(next_cell(15,b, red)).
neg(next_cell(15,c, black)).
neg(next_cell(15,c, blank)).
neg(next_cell(15,c, red)).
neg(next_cell(15,d, black)).
neg(next_cell(15,d, blank)).
neg(next_cell(15,d, red)).
neg(next_cell(15,e, black)).
neg(next_cell(15,e, blank)).
neg(next_cell(15,e, red)).
neg(next_cell(150,a, black)).
neg(next_cell(150,a, red)).
neg(next_cell(150,b, blank)).
neg(next_cell(150,b, red)).
neg(next_cell(150,c, black)).
neg(next_cell(150,c, blank)).
neg(next_cell(150,d, black)).
neg(next_cell(150,d, blank)).
neg(next_cell(150,e, blank)).
neg(next_cell(150,e, red)).
neg(next_cell(151,a, blank)).
neg(next_cell(151,a, red)).
neg(next_cell(151,b, black)).
neg(next_cell(151,b, blank)).
neg(next_cell(151,c, blank)).
neg(next_cell(151,c, red)).
neg(next_cell(151,d, black)).
neg(next_cell(151,d, red)).
neg(next_cell(151,e, black)).
neg(next_cell(151,e, blank)).
neg(next_cell(152,a, black)).
neg(next_cell(152,a, blank)).
neg(next_cell(152,b, blank)).
neg(next_cell(152,b, red)).
neg(next_cell(152,c, blank)).
neg(next_cell(152,c, red)).
neg(next_cell(152,d, black)).
neg(next_cell(152,d, red)).
neg(next_cell(152,e, black)).
neg(next_cell(152,e, blank)).
neg(next_cell(16,a, black)).
neg(next_cell(16,a, blank)).
neg(next_cell(16,b, blank)).
neg(next_cell(16,b, red)).
neg(next_cell(16,c, black)).
neg(next_cell(16,c, blank)).
neg(next_cell(16,d, blank)).
neg(next_cell(16,d, red)).
neg(next_cell(16,e, black)).
neg(next_cell(16,e, red)).
neg(next_cell(17,a, black)).
neg(next_cell(17,a, blank)).
neg(next_cell(17,a, red)).
neg(next_cell(17,b, black)).
neg(next_cell(17,b, blank)).
neg(next_cell(17,b, red)).
neg(next_cell(17,c, black)).
neg(next_cell(17,c, blank)).
neg(next_cell(17,c, red)).
neg(next_cell(17,d, black)).
neg(next_cell(17,d, blank)).
neg(next_cell(17,d, red)).
neg(next_cell(17,e, black)).
neg(next_cell(17,e, blank)).
neg(next_cell(17,e, red)).
neg(next_cell(18,a, black)).
neg(next_cell(18,a, blank)).
neg(next_cell(18,b, blank)).
neg(next_cell(18,b, red)).
neg(next_cell(18,c, blank)).
neg(next_cell(18,c, red)).
neg(next_cell(18,d, black)).
neg(next_cell(18,d, blank)).
neg(next_cell(18,e, black)).
neg(next_cell(18,e, red)).
neg(next_cell(19,a, blank)).
neg(next_cell(19,a, red)).
neg(next_cell(19,b, blank)).
neg(next_cell(19,b, red)).
neg(next_cell(19,c, black)).
neg(next_cell(19,c, red)).
neg(next_cell(19,d, black)).
neg(next_cell(19,d, blank)).
neg(next_cell(19,e, black)).
neg(next_cell(19,e, blank)).
neg(next_cell(2,a, black)).
neg(next_cell(2,a, blank)).
neg(next_cell(2,b, blank)).
neg(next_cell(2,b, red)).
neg(next_cell(2,c, black)).
neg(next_cell(2,c, blank)).
neg(next_cell(2,d, blank)).
neg(next_cell(2,d, red)).
neg(next_cell(2,e, black)).
neg(next_cell(2,e, red)).
neg(next_cell(20,a, black)).
neg(next_cell(20,a, blank)).
neg(next_cell(20,b, blank)).
neg(next_cell(20,b, red)).
neg(next_cell(20,c, blank)).
neg(next_cell(20,c, red)).
neg(next_cell(20,d, black)).
neg(next_cell(20,d, blank)).
neg(next_cell(20,e, black)).
neg(next_cell(20,e, red)).
neg(next_cell(21,a, blank)).
neg(next_cell(21,a, red)).
neg(next_cell(21,b, blank)).
neg(next_cell(21,b, red)).
neg(next_cell(21,c, black)).
neg(next_cell(21,c, red)).
neg(next_cell(21,d, black)).
neg(next_cell(21,d, blank)).
neg(next_cell(21,e, black)).
neg(next_cell(21,e, blank)).
neg(next_cell(22,a, black)).
neg(next_cell(22,a, blank)).
neg(next_cell(22,b, blank)).
neg(next_cell(22,b, red)).
neg(next_cell(22,c, black)).
neg(next_cell(22,c, blank)).
neg(next_cell(22,d, black)).
neg(next_cell(22,d, red)).
neg(next_cell(22,e, blank)).
neg(next_cell(22,e, red)).
neg(next_cell(23,a, blank)).
neg(next_cell(23,a, red)).
neg(next_cell(23,b, black)).
neg(next_cell(23,b, blank)).
neg(next_cell(23,c, blank)).
neg(next_cell(23,c, red)).
neg(next_cell(23,d, black)).
neg(next_cell(23,d, blank)).
neg(next_cell(23,e, black)).
neg(next_cell(23,e, red)).
neg(next_cell(24,a, black)).
neg(next_cell(24,a, blank)).
neg(next_cell(24,b, black)).
neg(next_cell(24,b, red)).
neg(next_cell(24,c, black)).
neg(next_cell(24,c, blank)).
neg(next_cell(24,d, blank)).
neg(next_cell(24,d, red)).
neg(next_cell(24,e, blank)).
neg(next_cell(24,e, red)).
neg(next_cell(25,a, black)).
neg(next_cell(25,a, red)).
neg(next_cell(25,b, black)).
neg(next_cell(25,b, blank)).
neg(next_cell(25,c, blank)).
neg(next_cell(25,c, red)).
neg(next_cell(25,d, black)).
neg(next_cell(25,d, blank)).
neg(next_cell(25,e, blank)).
neg(next_cell(25,e, red)).
neg(next_cell(26,a, blank)).
neg(next_cell(26,a, red)).
neg(next_cell(26,b, black)).
neg(next_cell(26,b, blank)).
neg(next_cell(26,c, black)).
neg(next_cell(26,c, blank)).
neg(next_cell(26,d, blank)).
neg(next_cell(26,d, red)).
neg(next_cell(26,e, black)).
neg(next_cell(26,e, red)).
neg(next_cell(27,a, blank)).
neg(next_cell(27,a, red)).
neg(next_cell(27,b, black)).
neg(next_cell(27,b, blank)).
neg(next_cell(27,c, black)).
neg(next_cell(27,c, red)).
neg(next_cell(27,d, blank)).
neg(next_cell(27,d, red)).
neg(next_cell(27,e, black)).
neg(next_cell(27,e, blank)).
neg(next_cell(28,a, black)).
neg(next_cell(28,a, blank)).
neg(next_cell(28,a, red)).
neg(next_cell(28,b, black)).
neg(next_cell(28,b, blank)).
neg(next_cell(28,b, red)).
neg(next_cell(28,c, black)).
neg(next_cell(28,c, blank)).
neg(next_cell(28,c, red)).
neg(next_cell(28,d, black)).
neg(next_cell(28,d, blank)).
neg(next_cell(28,d, red)).
neg(next_cell(28,e, black)).
neg(next_cell(28,e, blank)).
neg(next_cell(28,e, red)).
neg(next_cell(29,a, black)).
neg(next_cell(29,a, blank)).
neg(next_cell(29,a, red)).
neg(next_cell(29,b, black)).
neg(next_cell(29,b, blank)).
neg(next_cell(29,b, red)).
neg(next_cell(29,c, black)).
neg(next_cell(29,c, blank)).
neg(next_cell(29,c, red)).
neg(next_cell(29,d, black)).
neg(next_cell(29,d, blank)).
neg(next_cell(29,d, red)).
neg(next_cell(29,e, black)).
neg(next_cell(29,e, blank)).
neg(next_cell(29,e, red)).
neg(next_cell(3,a, black)).
neg(next_cell(3,a, blank)).
neg(next_cell(3,b, blank)).
neg(next_cell(3,b, red)).
neg(next_cell(3,c, black)).
neg(next_cell(3,c, blank)).
neg(next_cell(3,d, black)).
neg(next_cell(3,d, red)).
neg(next_cell(3,e, blank)).
neg(next_cell(3,e, red)).
neg(next_cell(30,a, black)).
neg(next_cell(30,a, blank)).
neg(next_cell(30,b, blank)).
neg(next_cell(30,b, red)).
neg(next_cell(30,c, black)).
neg(next_cell(30,c, red)).
neg(next_cell(30,d, black)).
neg(next_cell(30,d, blank)).
neg(next_cell(30,e, blank)).
neg(next_cell(30,e, red)).
neg(next_cell(31,a, black)).
neg(next_cell(31,a, red)).
neg(next_cell(31,b, blank)).
neg(next_cell(31,b, red)).
neg(next_cell(31,c, black)).
neg(next_cell(31,c, blank)).
neg(next_cell(31,d, blank)).
neg(next_cell(31,d, red)).
neg(next_cell(31,e, black)).
neg(next_cell(31,e, blank)).
neg(next_cell(32,a, blank)).
neg(next_cell(32,a, red)).
neg(next_cell(32,b, black)).
neg(next_cell(32,b, blank)).
neg(next_cell(32,c, black)).
neg(next_cell(32,c, red)).
neg(next_cell(32,d, blank)).
neg(next_cell(32,d, red)).
neg(next_cell(32,e, black)).
neg(next_cell(32,e, blank)).
neg(next_cell(33,a, blank)).
neg(next_cell(33,a, red)).
neg(next_cell(33,b, black)).
neg(next_cell(33,b, red)).
neg(next_cell(33,c, black)).
neg(next_cell(33,c, blank)).
neg(next_cell(33,d, blank)).
neg(next_cell(33,d, red)).
neg(next_cell(33,e, black)).
neg(next_cell(33,e, blank)).
neg(next_cell(34,a, black)).
neg(next_cell(34,a, red)).
neg(next_cell(34,b, black)).
neg(next_cell(34,b, blank)).
neg(next_cell(34,c, blank)).
neg(next_cell(34,c, red)).
neg(next_cell(34,d, blank)).
neg(next_cell(34,d, red)).
neg(next_cell(34,e, black)).
neg(next_cell(34,e, blank)).
neg(next_cell(35,a, black)).
neg(next_cell(35,a, blank)).
neg(next_cell(35,b, black)).
neg(next_cell(35,b, blank)).
neg(next_cell(35,c, blank)).
neg(next_cell(35,c, red)).
neg(next_cell(35,d, blank)).
neg(next_cell(35,d, red)).
neg(next_cell(35,e, black)).
neg(next_cell(35,e, red)).
neg(next_cell(36,a, blank)).
neg(next_cell(36,a, red)).
neg(next_cell(36,b, black)).
neg(next_cell(36,b, blank)).
neg(next_cell(36,c, blank)).
neg(next_cell(36,c, red)).
neg(next_cell(36,d, black)).
neg(next_cell(36,d, blank)).
neg(next_cell(36,e, black)).
neg(next_cell(36,e, red)).
neg(next_cell(37,a, black)).
neg(next_cell(37,a, blank)).
neg(next_cell(37,a, red)).
neg(next_cell(37,b, black)).
neg(next_cell(37,b, blank)).
neg(next_cell(37,b, red)).
neg(next_cell(37,c, black)).
neg(next_cell(37,c, blank)).
neg(next_cell(37,c, red)).
neg(next_cell(37,d, black)).
neg(next_cell(37,d, blank)).
neg(next_cell(37,d, red)).
neg(next_cell(37,e, black)).
neg(next_cell(37,e, blank)).
neg(next_cell(37,e, red)).
neg(next_cell(38,a, blank)).
neg(next_cell(38,a, red)).
neg(next_cell(38,b, black)).
neg(next_cell(38,b, blank)).
neg(next_cell(38,c, black)).
neg(next_cell(38,c, red)).
neg(next_cell(38,d, blank)).
neg(next_cell(38,d, red)).
neg(next_cell(38,e, black)).
neg(next_cell(38,e, blank)).
neg(next_cell(39,a, blank)).
neg(next_cell(39,a, red)).
neg(next_cell(39,b, black)).
neg(next_cell(39,b, red)).
neg(next_cell(39,c, blank)).
neg(next_cell(39,c, red)).
neg(next_cell(39,d, black)).
neg(next_cell(39,d, blank)).
neg(next_cell(39,e, black)).
neg(next_cell(39,e, blank)).
neg(next_cell(4,a, blank)).
neg(next_cell(4,a, red)).
neg(next_cell(4,b, black)).
neg(next_cell(4,b, blank)).
neg(next_cell(4,c, black)).
neg(next_cell(4,c, blank)).
neg(next_cell(4,d, black)).
neg(next_cell(4,d, red)).
neg(next_cell(4,e, blank)).
neg(next_cell(4,e, red)).
neg(next_cell(40,a, black)).
neg(next_cell(40,a, blank)).
neg(next_cell(40,b, blank)).
neg(next_cell(40,b, red)).
neg(next_cell(40,c, black)).
neg(next_cell(40,c, red)).
neg(next_cell(40,d, blank)).
neg(next_cell(40,d, red)).
neg(next_cell(40,e, black)).
neg(next_cell(40,e, blank)).
neg(next_cell(41,a, black)).
neg(next_cell(41,a, red)).
neg(next_cell(41,b, black)).
neg(next_cell(41,b, blank)).
neg(next_cell(41,c, blank)).
neg(next_cell(41,c, red)).
neg(next_cell(41,d, black)).
neg(next_cell(41,d, blank)).
neg(next_cell(41,e, blank)).
neg(next_cell(41,e, red)).
neg(next_cell(42,a, black)).
neg(next_cell(42,a, red)).
neg(next_cell(42,b, black)).
neg(next_cell(42,b, blank)).
neg(next_cell(42,c, blank)).
neg(next_cell(42,c, red)).
neg(next_cell(42,d, black)).
neg(next_cell(42,d, blank)).
neg(next_cell(42,e, blank)).
neg(next_cell(42,e, red)).
neg(next_cell(43,a, blank)).
neg(next_cell(43,a, red)).
neg(next_cell(43,b, blank)).
neg(next_cell(43,b, red)).
neg(next_cell(43,c, black)).
neg(next_cell(43,c, red)).
neg(next_cell(43,d, black)).
neg(next_cell(43,d, blank)).
neg(next_cell(43,e, black)).
neg(next_cell(43,e, blank)).
neg(next_cell(44,a, black)).
neg(next_cell(44,a, blank)).
neg(next_cell(44,b, blank)).
neg(next_cell(44,b, red)).
neg(next_cell(44,c, black)).
neg(next_cell(44,c, red)).
neg(next_cell(44,d, black)).
neg(next_cell(44,d, blank)).
neg(next_cell(44,e, blank)).
neg(next_cell(44,e, red)).
neg(next_cell(45,a, blank)).
neg(next_cell(45,a, red)).
neg(next_cell(45,b, black)).
neg(next_cell(45,b, blank)).
neg(next_cell(45,c, blank)).
neg(next_cell(45,c, red)).
neg(next_cell(45,d, black)).
neg(next_cell(45,d, red)).
neg(next_cell(45,e, black)).
neg(next_cell(45,e, blank)).
neg(next_cell(46,a, black)).
neg(next_cell(46,a, red)).
neg(next_cell(46,b, black)).
neg(next_cell(46,b, blank)).
neg(next_cell(46,c, blank)).
neg(next_cell(46,c, red)).
neg(next_cell(46,d, black)).
neg(next_cell(46,d, blank)).
neg(next_cell(46,e, blank)).
neg(next_cell(46,e, red)).
neg(next_cell(47,a, black)).
neg(next_cell(47,a, blank)).
neg(next_cell(47,b, blank)).
neg(next_cell(47,b, red)).
neg(next_cell(47,c, black)).
neg(next_cell(47,c, blank)).
neg(next_cell(47,d, blank)).
neg(next_cell(47,d, red)).
neg(next_cell(47,e, black)).
neg(next_cell(47,e, red)).
neg(next_cell(48,a, black)).
neg(next_cell(48,a, blank)).
neg(next_cell(48,b, black)).
neg(next_cell(48,b, red)).
neg(next_cell(48,c, black)).
neg(next_cell(48,c, blank)).
neg(next_cell(48,d, blank)).
neg(next_cell(48,d, red)).
neg(next_cell(48,e, blank)).
neg(next_cell(48,e, red)).
neg(next_cell(49,a, black)).
neg(next_cell(49,a, blank)).
neg(next_cell(49,a, red)).
neg(next_cell(49,b, black)).
neg(next_cell(49,b, blank)).
neg(next_cell(49,b, red)).
neg(next_cell(49,c, black)).
neg(next_cell(49,c, blank)).
neg(next_cell(49,c, red)).
neg(next_cell(49,d, black)).
neg(next_cell(49,d, blank)).
neg(next_cell(49,d, red)).
neg(next_cell(49,e, black)).
neg(next_cell(49,e, blank)).
neg(next_cell(49,e, red)).
neg(next_cell(5,a, black)).
neg(next_cell(5,a, blank)).
neg(next_cell(5,b, blank)).
neg(next_cell(5,b, red)).
neg(next_cell(5,c, black)).
neg(next_cell(5,c, red)).
neg(next_cell(5,d, blank)).
neg(next_cell(5,d, red)).
neg(next_cell(5,e, black)).
neg(next_cell(5,e, blank)).
neg(next_cell(50,a, blank)).
neg(next_cell(50,a, red)).
neg(next_cell(50,b, blank)).
neg(next_cell(50,b, red)).
neg(next_cell(50,c, black)).
neg(next_cell(50,c, red)).
neg(next_cell(50,d, black)).
neg(next_cell(50,d, blank)).
neg(next_cell(50,e, black)).
neg(next_cell(50,e, blank)).
neg(next_cell(51,a, black)).
neg(next_cell(51,a, blank)).
neg(next_cell(51,b, blank)).
neg(next_cell(51,b, red)).
neg(next_cell(51,c, black)).
neg(next_cell(51,c, red)).
neg(next_cell(51,d, black)).
neg(next_cell(51,d, blank)).
neg(next_cell(51,e, blank)).
neg(next_cell(51,e, red)).
neg(next_cell(52,a, blank)).
neg(next_cell(52,a, red)).
neg(next_cell(52,b, black)).
neg(next_cell(52,b, blank)).
neg(next_cell(52,c, blank)).
neg(next_cell(52,c, red)).
neg(next_cell(52,d, black)).
neg(next_cell(52,d, blank)).
neg(next_cell(52,e, black)).
neg(next_cell(52,e, red)).
neg(next_cell(53,a, black)).
neg(next_cell(53,a, blank)).
neg(next_cell(53,b, blank)).
neg(next_cell(53,b, red)).
neg(next_cell(53,c, blank)).
neg(next_cell(53,c, red)).
neg(next_cell(53,d, black)).
neg(next_cell(53,d, blank)).
neg(next_cell(53,e, black)).
neg(next_cell(53,e, red)).
neg(next_cell(54,a, black)).
neg(next_cell(54,a, red)).
neg(next_cell(54,b, blank)).
neg(next_cell(54,b, red)).
neg(next_cell(54,c, blank)).
neg(next_cell(54,c, red)).
neg(next_cell(54,d, black)).
neg(next_cell(54,d, blank)).
neg(next_cell(54,e, black)).
neg(next_cell(54,e, blank)).
neg(next_cell(55,a, black)).
neg(next_cell(55,a, blank)).
neg(next_cell(55,b, blank)).
neg(next_cell(55,b, red)).
neg(next_cell(55,c, black)).
neg(next_cell(55,c, blank)).
neg(next_cell(55,d, blank)).
neg(next_cell(55,d, red)).
neg(next_cell(55,e, black)).
neg(next_cell(55,e, red)).
neg(next_cell(56,a, black)).
neg(next_cell(56,a, blank)).
neg(next_cell(56,b, black)).
neg(next_cell(56,b, red)).
neg(next_cell(56,c, blank)).
neg(next_cell(56,c, red)).
neg(next_cell(56,d, black)).
neg(next_cell(56,d, blank)).
neg(next_cell(56,e, blank)).
neg(next_cell(56,e, red)).
neg(next_cell(57,a, black)).
neg(next_cell(57,a, blank)).
neg(next_cell(57,b, black)).
neg(next_cell(57,b, red)).
neg(next_cell(57,c, blank)).
neg(next_cell(57,c, red)).
neg(next_cell(57,d, blank)).
neg(next_cell(57,d, red)).
neg(next_cell(57,e, black)).
neg(next_cell(57,e, blank)).
neg(next_cell(58,a, black)).
neg(next_cell(58,a, blank)).
neg(next_cell(58,b, blank)).
neg(next_cell(58,b, red)).
neg(next_cell(58,c, black)).
neg(next_cell(58,c, red)).
neg(next_cell(58,d, blank)).
neg(next_cell(58,d, red)).
neg(next_cell(58,e, black)).
neg(next_cell(58,e, blank)).
neg(next_cell(59,a, blank)).
neg(next_cell(59,a, red)).
neg(next_cell(59,b, black)).
neg(next_cell(59,b, blank)).
neg(next_cell(59,c, black)).
neg(next_cell(59,c, red)).
neg(next_cell(59,d, black)).
neg(next_cell(59,d, blank)).
neg(next_cell(59,e, blank)).
neg(next_cell(59,e, red)).
neg(next_cell(6,a, blank)).
neg(next_cell(6,a, red)).
neg(next_cell(6,b, black)).
neg(next_cell(6,b, blank)).
neg(next_cell(6,c, black)).
neg(next_cell(6,c, blank)).
neg(next_cell(6,d, blank)).
neg(next_cell(6,d, red)).
neg(next_cell(6,e, black)).
neg(next_cell(6,e, red)).
neg(next_cell(60,a, black)).
neg(next_cell(60,a, red)).
neg(next_cell(60,b, black)).
neg(next_cell(60,b, blank)).
neg(next_cell(60,c, blank)).
neg(next_cell(60,c, red)).
neg(next_cell(60,d, blank)).
neg(next_cell(60,d, red)).
neg(next_cell(60,e, black)).
neg(next_cell(60,e, blank)).
neg(next_cell(61,a, blank)).
neg(next_cell(61,a, red)).
neg(next_cell(61,b, black)).
neg(next_cell(61,b, red)).
neg(next_cell(61,c, black)).
neg(next_cell(61,c, blank)).
neg(next_cell(61,d, blank)).
neg(next_cell(61,d, red)).
neg(next_cell(61,e, black)).
neg(next_cell(61,e, blank)).
neg(next_cell(62,a, blank)).
neg(next_cell(62,a, red)).
neg(next_cell(62,b, black)).
neg(next_cell(62,b, blank)).
neg(next_cell(62,c, black)).
neg(next_cell(62,c, red)).
neg(next_cell(62,d, black)).
neg(next_cell(62,d, blank)).
neg(next_cell(62,e, blank)).
neg(next_cell(62,e, red)).
neg(next_cell(63,a, black)).
neg(next_cell(63,a, blank)).
neg(next_cell(63,a, red)).
neg(next_cell(63,b, black)).
neg(next_cell(63,b, blank)).
neg(next_cell(63,b, red)).
neg(next_cell(63,c, black)).
neg(next_cell(63,c, blank)).
neg(next_cell(63,c, red)).
neg(next_cell(63,d, black)).
neg(next_cell(63,d, blank)).
neg(next_cell(63,d, red)).
neg(next_cell(63,e, black)).
neg(next_cell(63,e, blank)).
neg(next_cell(63,e, red)).
neg(next_cell(64,a, black)).
neg(next_cell(64,a, blank)).
neg(next_cell(64,b, blank)).
neg(next_cell(64,b, red)).
neg(next_cell(64,c, black)).
neg(next_cell(64,c, red)).
neg(next_cell(64,d, blank)).
neg(next_cell(64,d, red)).
neg(next_cell(64,e, black)).
neg(next_cell(64,e, blank)).
neg(next_cell(65,a, black)).
neg(next_cell(65,a, red)).
neg(next_cell(65,b, black)).
neg(next_cell(65,b, blank)).
neg(next_cell(65,c, black)).
neg(next_cell(65,c, blank)).
neg(next_cell(65,d, blank)).
neg(next_cell(65,d, red)).
neg(next_cell(65,e, blank)).
neg(next_cell(65,e, red)).
neg(next_cell(66,a, blank)).
neg(next_cell(66,a, red)).
neg(next_cell(66,b, black)).
neg(next_cell(66,b, blank)).
neg(next_cell(66,c, black)).
neg(next_cell(66,c, blank)).
neg(next_cell(66,d, blank)).
neg(next_cell(66,d, red)).
neg(next_cell(66,e, black)).
neg(next_cell(66,e, red)).
neg(next_cell(67,a, blank)).
neg(next_cell(67,a, red)).
neg(next_cell(67,b, black)).
neg(next_cell(67,b, blank)).
neg(next_cell(67,c, black)).
neg(next_cell(67,c, red)).
neg(next_cell(67,d, blank)).
neg(next_cell(67,d, red)).
neg(next_cell(67,e, black)).
neg(next_cell(67,e, blank)).
neg(next_cell(68,a, black)).
neg(next_cell(68,a, blank)).
neg(next_cell(68,a, red)).
neg(next_cell(68,b, black)).
neg(next_cell(68,b, blank)).
neg(next_cell(68,b, red)).
neg(next_cell(68,c, black)).
neg(next_cell(68,c, blank)).
neg(next_cell(68,c, red)).
neg(next_cell(68,d, black)).
neg(next_cell(68,d, blank)).
neg(next_cell(68,d, red)).
neg(next_cell(68,e, black)).
neg(next_cell(68,e, blank)).
neg(next_cell(68,e, red)).
neg(next_cell(69,a, black)).
neg(next_cell(69,a, blank)).
neg(next_cell(69,a, red)).
neg(next_cell(69,b, black)).
neg(next_cell(69,b, blank)).
neg(next_cell(69,b, red)).
neg(next_cell(69,c, black)).
neg(next_cell(69,c, blank)).
neg(next_cell(69,c, red)).
neg(next_cell(69,d, black)).
neg(next_cell(69,d, blank)).
neg(next_cell(69,d, red)).
neg(next_cell(69,e, black)).
neg(next_cell(69,e, blank)).
neg(next_cell(69,e, red)).
neg(next_cell(7,a, black)).
neg(next_cell(7,a, blank)).
neg(next_cell(7,a, red)).
neg(next_cell(7,b, black)).
neg(next_cell(7,b, blank)).
neg(next_cell(7,b, red)).
neg(next_cell(7,c, black)).
neg(next_cell(7,c, blank)).
neg(next_cell(7,c, red)).
neg(next_cell(7,d, black)).
neg(next_cell(7,d, blank)).
neg(next_cell(7,d, red)).
neg(next_cell(7,e, black)).
neg(next_cell(7,e, blank)).
neg(next_cell(7,e, red)).
neg(next_cell(70,a, black)).
neg(next_cell(70,a, blank)).
neg(next_cell(70,b, blank)).
neg(next_cell(70,b, red)).
neg(next_cell(70,c, black)).
neg(next_cell(70,c, red)).
neg(next_cell(70,d, black)).
neg(next_cell(70,d, blank)).
neg(next_cell(70,e, blank)).
neg(next_cell(70,e, red)).
neg(next_cell(71,a, black)).
neg(next_cell(71,a, blank)).
neg(next_cell(71,a, red)).
neg(next_cell(71,b, black)).
neg(next_cell(71,b, blank)).
neg(next_cell(71,b, red)).
neg(next_cell(71,c, black)).
neg(next_cell(71,c, blank)).
neg(next_cell(71,c, red)).
neg(next_cell(71,d, black)).
neg(next_cell(71,d, blank)).
neg(next_cell(71,d, red)).
neg(next_cell(71,e, black)).
neg(next_cell(71,e, blank)).
neg(next_cell(71,e, red)).
neg(next_cell(72,a, black)).
neg(next_cell(72,a, blank)).
neg(next_cell(72,b, black)).
neg(next_cell(72,b, red)).
neg(next_cell(72,c, blank)).
neg(next_cell(72,c, red)).
neg(next_cell(72,d, black)).
neg(next_cell(72,d, blank)).
neg(next_cell(72,e, blank)).
neg(next_cell(72,e, red)).
neg(next_cell(73,a, black)).
neg(next_cell(73,a, red)).
neg(next_cell(73,b, blank)).
neg(next_cell(73,b, red)).
neg(next_cell(73,c, black)).
neg(next_cell(73,c, blank)).
neg(next_cell(73,d, blank)).
neg(next_cell(73,d, red)).
neg(next_cell(73,e, black)).
neg(next_cell(73,e, blank)).
neg(next_cell(74,a, black)).
neg(next_cell(74,a, blank)).
neg(next_cell(74,b, black)).
neg(next_cell(74,b, red)).
neg(next_cell(74,c, blank)).
neg(next_cell(74,c, red)).
neg(next_cell(74,d, blank)).
neg(next_cell(74,d, red)).
neg(next_cell(74,e, black)).
neg(next_cell(74,e, blank)).
neg(next_cell(75,a, black)).
neg(next_cell(75,a, blank)).
neg(next_cell(75,b, black)).
neg(next_cell(75,b, red)).
neg(next_cell(75,c, blank)).
neg(next_cell(75,c, red)).
neg(next_cell(75,d, black)).
neg(next_cell(75,d, blank)).
neg(next_cell(75,e, blank)).
neg(next_cell(75,e, red)).
neg(next_cell(76,a, black)).
neg(next_cell(76,a, red)).
neg(next_cell(76,b, blank)).
neg(next_cell(76,b, red)).
neg(next_cell(76,c, black)).
neg(next_cell(76,c, blank)).
neg(next_cell(76,d, blank)).
neg(next_cell(76,d, red)).
neg(next_cell(76,e, black)).
neg(next_cell(76,e, blank)).
neg(next_cell(77,a, black)).
neg(next_cell(77,a, blank)).
neg(next_cell(77,b, blank)).
neg(next_cell(77,b, red)).
neg(next_cell(77,c, blank)).
neg(next_cell(77,c, red)).
neg(next_cell(77,d, black)).
neg(next_cell(77,d, red)).
neg(next_cell(77,e, black)).
neg(next_cell(77,e, blank)).
neg(next_cell(78,a, black)).
neg(next_cell(78,a, blank)).
neg(next_cell(78,b, blank)).
neg(next_cell(78,b, red)).
neg(next_cell(78,c, blank)).
neg(next_cell(78,c, red)).
neg(next_cell(78,d, black)).
neg(next_cell(78,d, red)).
neg(next_cell(78,e, black)).
neg(next_cell(78,e, blank)).
neg(next_cell(79,a, black)).
neg(next_cell(79,a, blank)).
neg(next_cell(79,b, blank)).
neg(next_cell(79,b, red)).
neg(next_cell(79,c, black)).
neg(next_cell(79,c, blank)).
neg(next_cell(79,d, blank)).
neg(next_cell(79,d, red)).
neg(next_cell(79,e, black)).
neg(next_cell(79,e, red)).
neg(next_cell(8,a, black)).
neg(next_cell(8,a, red)).
neg(next_cell(8,b, blank)).
neg(next_cell(8,b, red)).
neg(next_cell(8,c, blank)).
neg(next_cell(8,c, red)).
neg(next_cell(8,d, black)).
neg(next_cell(8,d, blank)).
neg(next_cell(8,e, black)).
neg(next_cell(8,e, blank)).
neg(next_cell(80,a, blank)).
neg(next_cell(80,a, red)).
neg(next_cell(80,b, black)).
neg(next_cell(80,b, red)).
neg(next_cell(80,c, black)).
neg(next_cell(80,c, blank)).
neg(next_cell(80,d, black)).
neg(next_cell(80,d, blank)).
neg(next_cell(80,e, blank)).
neg(next_cell(80,e, red)).
neg(next_cell(81,a, blank)).
neg(next_cell(81,a, red)).
neg(next_cell(81,b, black)).
neg(next_cell(81,b, blank)).
neg(next_cell(81,c, black)).
neg(next_cell(81,c, red)).
neg(next_cell(81,d, blank)).
neg(next_cell(81,d, red)).
neg(next_cell(81,e, black)).
neg(next_cell(81,e, blank)).
neg(next_cell(82,a, black)).
neg(next_cell(82,a, blank)).
neg(next_cell(82,a, red)).
neg(next_cell(82,b, black)).
neg(next_cell(82,b, blank)).
neg(next_cell(82,b, red)).
neg(next_cell(82,c, black)).
neg(next_cell(82,c, blank)).
neg(next_cell(82,c, red)).
neg(next_cell(82,d, black)).
neg(next_cell(82,d, blank)).
neg(next_cell(82,d, red)).
neg(next_cell(82,e, black)).
neg(next_cell(82,e, blank)).
neg(next_cell(82,e, red)).
neg(next_cell(83,a, black)).
neg(next_cell(83,a, blank)).
neg(next_cell(83,b, blank)).
neg(next_cell(83,b, red)).
neg(next_cell(83,c, black)).
neg(next_cell(83,c, red)).
neg(next_cell(83,d, black)).
neg(next_cell(83,d, blank)).
neg(next_cell(83,e, blank)).
neg(next_cell(83,e, red)).
neg(next_cell(84,a, black)).
neg(next_cell(84,a, red)).
neg(next_cell(84,b, black)).
neg(next_cell(84,b, blank)).
neg(next_cell(84,c, blank)).
neg(next_cell(84,c, red)).
neg(next_cell(84,d, blank)).
neg(next_cell(84,d, red)).
neg(next_cell(84,e, black)).
neg(next_cell(84,e, blank)).
neg(next_cell(85,a, black)).
neg(next_cell(85,a, blank)).
neg(next_cell(85,b, black)).
neg(next_cell(85,b, red)).
neg(next_cell(85,c, blank)).
neg(next_cell(85,c, red)).
neg(next_cell(85,d, black)).
neg(next_cell(85,d, blank)).
neg(next_cell(85,e, blank)).
neg(next_cell(85,e, red)).
neg(next_cell(86,a, black)).
neg(next_cell(86,a, blank)).
neg(next_cell(86,b, black)).
neg(next_cell(86,b, red)).
neg(next_cell(86,c, black)).
neg(next_cell(86,c, blank)).
neg(next_cell(86,d, blank)).
neg(next_cell(86,d, red)).
neg(next_cell(86,e, blank)).
neg(next_cell(86,e, red)).
neg(next_cell(87,a, black)).
neg(next_cell(87,a, blank)).
neg(next_cell(87,b, blank)).
neg(next_cell(87,b, red)).
neg(next_cell(87,c, black)).
neg(next_cell(87,c, red)).
neg(next_cell(87,d, black)).
neg(next_cell(87,d, blank)).
neg(next_cell(87,e, blank)).
neg(next_cell(87,e, red)).
neg(next_cell(88,a, black)).
neg(next_cell(88,a, red)).
neg(next_cell(88,b, blank)).
neg(next_cell(88,b, red)).
neg(next_cell(88,c, blank)).
neg(next_cell(88,c, red)).
neg(next_cell(88,d, black)).
neg(next_cell(88,d, blank)).
neg(next_cell(88,e, black)).
neg(next_cell(88,e, blank)).
neg(next_cell(89,a, black)).
neg(next_cell(89,a, blank)).
neg(next_cell(89,b, black)).
neg(next_cell(89,b, red)).
neg(next_cell(89,c, blank)).
neg(next_cell(89,c, red)).
neg(next_cell(89,d, black)).
neg(next_cell(89,d, blank)).
neg(next_cell(89,e, blank)).
neg(next_cell(89,e, red)).
neg(next_cell(9,a, blank)).
neg(next_cell(9,a, red)).
neg(next_cell(9,b, black)).
neg(next_cell(9,b, blank)).
neg(next_cell(9,c, blank)).
neg(next_cell(9,c, red)).
neg(next_cell(9,d, black)).
neg(next_cell(9,d, blank)).
neg(next_cell(9,e, black)).
neg(next_cell(9,e, red)).
neg(next_cell(90,a, blank)).
neg(next_cell(90,a, red)).
neg(next_cell(90,b, black)).
neg(next_cell(90,b, blank)).
neg(next_cell(90,c, black)).
neg(next_cell(90,c, red)).
neg(next_cell(90,d, black)).
neg(next_cell(90,d, blank)).
neg(next_cell(90,e, blank)).
neg(next_cell(90,e, red)).
neg(next_cell(91,a, blank)).
neg(next_cell(91,a, red)).
neg(next_cell(91,b, black)).
neg(next_cell(91,b, blank)).
neg(next_cell(91,c, blank)).
neg(next_cell(91,c, red)).
neg(next_cell(91,d, black)).
neg(next_cell(91,d, blank)).
neg(next_cell(91,e, black)).
neg(next_cell(91,e, red)).
neg(next_cell(92,a, black)).
neg(next_cell(92,a, blank)).
neg(next_cell(92,a, red)).
neg(next_cell(92,b, black)).
neg(next_cell(92,b, blank)).
neg(next_cell(92,b, red)).
neg(next_cell(92,c, black)).
neg(next_cell(92,c, blank)).
neg(next_cell(92,c, red)).
neg(next_cell(92,d, black)).
neg(next_cell(92,d, blank)).
neg(next_cell(92,d, red)).
neg(next_cell(92,e, black)).
neg(next_cell(92,e, blank)).
neg(next_cell(92,e, red)).
neg(next_cell(93,a, black)).
neg(next_cell(93,a, blank)).
neg(next_cell(93,b, blank)).
neg(next_cell(93,b, red)).
neg(next_cell(93,c, black)).
neg(next_cell(93,c, red)).
neg(next_cell(93,d, blank)).
neg(next_cell(93,d, red)).
neg(next_cell(93,e, black)).
neg(next_cell(93,e, blank)).
neg(next_cell(94,a, black)).
neg(next_cell(94,a, blank)).
neg(next_cell(94,b, black)).
neg(next_cell(94,b, red)).
neg(next_cell(94,c, blank)).
neg(next_cell(94,c, red)).
neg(next_cell(94,d, blank)).
neg(next_cell(94,d, red)).
neg(next_cell(94,e, black)).
neg(next_cell(94,e, blank)).
neg(next_cell(95,a, black)).
neg(next_cell(95,a, blank)).
neg(next_cell(95,b, blank)).
neg(next_cell(95,b, red)).
neg(next_cell(95,c, black)).
neg(next_cell(95,c, red)).
neg(next_cell(95,d, black)).
neg(next_cell(95,d, blank)).
neg(next_cell(95,e, blank)).
neg(next_cell(95,e, red)).
neg(next_cell(96,a, blank)).
neg(next_cell(96,a, red)).
neg(next_cell(96,b, black)).
neg(next_cell(96,b, red)).
neg(next_cell(96,c, black)).
neg(next_cell(96,c, blank)).
neg(next_cell(96,d, blank)).
neg(next_cell(96,d, red)).
neg(next_cell(96,e, black)).
neg(next_cell(96,e, blank)).
neg(next_cell(97,a, blank)).
neg(next_cell(97,a, red)).
neg(next_cell(97,b, blank)).
neg(next_cell(97,b, red)).
neg(next_cell(97,c, black)).
neg(next_cell(97,c, blank)).
neg(next_cell(97,d, black)).
neg(next_cell(97,d, red)).
neg(next_cell(97,e, black)).
neg(next_cell(97,e, blank)).
neg(next_cell(98,a, blank)).
neg(next_cell(98,a, red)).
neg(next_cell(98,b, black)).
neg(next_cell(98,b, red)).
neg(next_cell(98,c, black)).
neg(next_cell(98,c, blank)).
neg(next_cell(98,d, black)).
neg(next_cell(98,d, blank)).
neg(next_cell(98,e, blank)).
neg(next_cell(98,e, red)).
neg(next_cell(99,a, black)).
neg(next_cell(99,a, blank)).
neg(next_cell(99,b, blank)).
neg(next_cell(99,b, red)).
neg(next_cell(99,c, black)).
neg(next_cell(99,c, blank)).
neg(next_cell(99,d, black)).
neg(next_cell(99,d, red)).
neg(next_cell(99,e, blank)).
neg(next_cell(99,e, red)).
pos(next_cell(1,a, black)).
pos(next_cell(1,b, red)).
pos(next_cell(1,c, blank)).
pos(next_cell(1,d, red)).
pos(next_cell(1,e, black)).
pos(next_cell(10,a, black)).
pos(next_cell(10,b, red)).
pos(next_cell(10,c, black)).
pos(next_cell(10,d, blank)).
pos(next_cell(10,e, red)).
pos(next_cell(100,a, black)).
pos(next_cell(100,b, black)).
pos(next_cell(100,c, red)).
pos(next_cell(100,d, blank)).
pos(next_cell(100,e, red)).
pos(next_cell(101,a, black)).
pos(next_cell(101,b, blank)).
pos(next_cell(101,c, black)).
pos(next_cell(101,d, red)).
pos(next_cell(101,e, red)).
pos(next_cell(102,a, black)).
pos(next_cell(102,b, red)).
pos(next_cell(102,c, black)).
pos(next_cell(102,d, red)).
pos(next_cell(102,e, blank)).
pos(next_cell(104,a, blank)).
pos(next_cell(104,b, red)).
pos(next_cell(104,c, red)).
pos(next_cell(104,d, black)).
pos(next_cell(104,e, black)).
pos(next_cell(105,a, blank)).
pos(next_cell(105,b, black)).
pos(next_cell(105,c, black)).
pos(next_cell(105,d, red)).
pos(next_cell(105,e, red)).
pos(next_cell(106,a, blank)).
pos(next_cell(106,b, red)).
pos(next_cell(106,c, black)).
pos(next_cell(106,d, red)).
pos(next_cell(106,e, black)).
pos(next_cell(108,a, red)).
pos(next_cell(108,b, blank)).
pos(next_cell(108,c, black)).
pos(next_cell(108,d, red)).
pos(next_cell(108,e, black)).
pos(next_cell(109,a, black)).
pos(next_cell(109,b, red)).
pos(next_cell(109,c, red)).
pos(next_cell(109,d, black)).
pos(next_cell(109,e, blank)).
pos(next_cell(11,a, black)).
pos(next_cell(11,b, red)).
pos(next_cell(11,c, black)).
pos(next_cell(11,d, blank)).
pos(next_cell(11,e, red)).
pos(next_cell(111,a, red)).
pos(next_cell(111,b, black)).
pos(next_cell(111,c, black)).
pos(next_cell(111,d, red)).
pos(next_cell(111,e, blank)).
pos(next_cell(112,a, black)).
pos(next_cell(112,b, red)).
pos(next_cell(112,c, blank)).
pos(next_cell(112,d, black)).
pos(next_cell(112,e, red)).
pos(next_cell(113,a, black)).
pos(next_cell(113,b, red)).
pos(next_cell(113,c, black)).
pos(next_cell(113,d, blank)).
pos(next_cell(113,e, red)).
pos(next_cell(114,a, black)).
pos(next_cell(114,b, blank)).
pos(next_cell(114,c, red)).
pos(next_cell(114,d, red)).
pos(next_cell(114,e, black)).
pos(next_cell(115,a, blank)).
pos(next_cell(115,b, black)).
pos(next_cell(115,c, red)).
pos(next_cell(115,d, black)).
pos(next_cell(115,e, red)).
pos(next_cell(116,a, blank)).
pos(next_cell(116,b, black)).
pos(next_cell(116,c, red)).
pos(next_cell(116,d, black)).
pos(next_cell(116,e, red)).
pos(next_cell(117,a, red)).
pos(next_cell(117,b, black)).
pos(next_cell(117,c, blank)).
pos(next_cell(117,d, red)).
pos(next_cell(117,e, black)).
pos(next_cell(118,a, red)).
pos(next_cell(118,b, black)).
pos(next_cell(118,c, blank)).
pos(next_cell(118,d, black)).
pos(next_cell(118,e, red)).
pos(next_cell(119,a, black)).
pos(next_cell(119,b, red)).
pos(next_cell(119,c, blank)).
pos(next_cell(119,d, red)).
pos(next_cell(119,e, black)).
pos(next_cell(120,a, black)).
pos(next_cell(120,b, blank)).
pos(next_cell(120,c, black)).
pos(next_cell(120,d, red)).
pos(next_cell(120,e, red)).
pos(next_cell(121,a, black)).
pos(next_cell(121,b, red)).
pos(next_cell(121,c, blank)).
pos(next_cell(121,d, red)).
pos(next_cell(121,e, black)).
pos(next_cell(122,a, blank)).
pos(next_cell(122,b, black)).
pos(next_cell(122,c, red)).
pos(next_cell(122,d, red)).
pos(next_cell(122,e, black)).
pos(next_cell(124,a, blank)).
pos(next_cell(124,b, black)).
pos(next_cell(124,c, red)).
pos(next_cell(124,d, red)).
pos(next_cell(124,e, black)).
pos(next_cell(126,a, black)).
pos(next_cell(126,b, red)).
pos(next_cell(126,c, red)).
pos(next_cell(126,d, blank)).
pos(next_cell(126,e, black)).
pos(next_cell(128,a, black)).
pos(next_cell(128,b, red)).
pos(next_cell(128,c, blank)).
pos(next_cell(128,d, red)).
pos(next_cell(128,e, black)).
pos(next_cell(129,a, red)).
pos(next_cell(129,b, black)).
pos(next_cell(129,c, red)).
pos(next_cell(129,d, blank)).
pos(next_cell(129,e, black)).
pos(next_cell(13,a, red)).
pos(next_cell(13,b, red)).
pos(next_cell(13,c, blank)).
pos(next_cell(13,d, black)).
pos(next_cell(13,e, black)).
pos(next_cell(130,a, black)).
pos(next_cell(130,b, red)).
pos(next_cell(130,c, blank)).
pos(next_cell(130,d, black)).
pos(next_cell(130,e, red)).
pos(next_cell(131,a, blank)).
pos(next_cell(131,b, black)).
pos(next_cell(131,c, red)).
pos(next_cell(131,d, red)).
pos(next_cell(131,e, black)).
pos(next_cell(132,a, red)).
pos(next_cell(132,b, red)).
pos(next_cell(132,c, black)).
pos(next_cell(132,d, black)).
pos(next_cell(132,e, blank)).
pos(next_cell(133,a, black)).
pos(next_cell(133,b, red)).
pos(next_cell(133,c, blank)).
pos(next_cell(133,d, black)).
pos(next_cell(133,e, red)).
pos(next_cell(134,a, red)).
pos(next_cell(134,b, black)).
pos(next_cell(134,c, blank)).
pos(next_cell(134,d, red)).
pos(next_cell(134,e, black)).
pos(next_cell(135,a, blank)).
pos(next_cell(135,b, black)).
pos(next_cell(135,c, red)).
pos(next_cell(135,d, black)).
pos(next_cell(135,e, red)).
pos(next_cell(136,a, red)).
pos(next_cell(136,b, blank)).
pos(next_cell(136,c, black)).
pos(next_cell(136,d, red)).
pos(next_cell(136,e, black)).
pos(next_cell(137,a, black)).
pos(next_cell(137,b, black)).
pos(next_cell(137,c, red)).
pos(next_cell(137,d, blank)).
pos(next_cell(137,e, red)).
pos(next_cell(138,a, blank)).
pos(next_cell(138,b, red)).
pos(next_cell(138,c, red)).
pos(next_cell(138,d, black)).
pos(next_cell(138,e, black)).
pos(next_cell(139,a, black)).
pos(next_cell(139,b, blank)).
pos(next_cell(139,c, red)).
pos(next_cell(139,d, red)).
pos(next_cell(139,e, black)).
pos(next_cell(14,a, blank)).
pos(next_cell(14,b, black)).
pos(next_cell(14,c, red)).
pos(next_cell(14,d, red)).
pos(next_cell(14,e, black)).
pos(next_cell(140,a, black)).
pos(next_cell(140,b, black)).
pos(next_cell(140,c, blank)).
pos(next_cell(140,d, red)).
pos(next_cell(140,e, red)).
pos(next_cell(141,a, black)).
pos(next_cell(141,b, blank)).
pos(next_cell(141,c, red)).
pos(next_cell(141,d, black)).
pos(next_cell(141,e, red)).
pos(next_cell(142,a, black)).
pos(next_cell(142,b, blank)).
pos(next_cell(142,c, red)).
pos(next_cell(142,d, red)).
pos(next_cell(142,e, black)).
pos(next_cell(143,a, black)).
pos(next_cell(143,b, red)).
pos(next_cell(143,c, blank)).
pos(next_cell(143,d, red)).
pos(next_cell(143,e, black)).
pos(next_cell(144,a, black)).
pos(next_cell(144,b, red)).
pos(next_cell(144,c, blank)).
pos(next_cell(144,d, red)).
pos(next_cell(144,e, black)).
pos(next_cell(145,a, blank)).
pos(next_cell(145,b, red)).
pos(next_cell(145,c, black)).
pos(next_cell(145,d, red)).
pos(next_cell(145,e, black)).
pos(next_cell(146,a, black)).
pos(next_cell(146,b, red)).
pos(next_cell(146,c, red)).
pos(next_cell(146,d, blank)).
pos(next_cell(146,e, black)).
pos(next_cell(147,a, black)).
pos(next_cell(147,b, blank)).
pos(next_cell(147,c, red)).
pos(next_cell(147,d, red)).
pos(next_cell(147,e, black)).
pos(next_cell(148,a, red)).
pos(next_cell(148,b, black)).
pos(next_cell(148,c, black)).
pos(next_cell(148,d, red)).
pos(next_cell(148,e, blank)).
pos(next_cell(149,a, black)).
pos(next_cell(149,b, red)).
pos(next_cell(149,c, blank)).
pos(next_cell(149,d, red)).
pos(next_cell(149,e, black)).
pos(next_cell(150,a, blank)).
pos(next_cell(150,b, black)).
pos(next_cell(150,c, red)).
pos(next_cell(150,d, red)).
pos(next_cell(150,e, black)).
pos(next_cell(151,a, black)).
pos(next_cell(151,b, red)).
pos(next_cell(151,c, black)).
pos(next_cell(151,d, blank)).
pos(next_cell(151,e, red)).
pos(next_cell(152,a, red)).
pos(next_cell(152,b, black)).
pos(next_cell(152,c, black)).
pos(next_cell(152,d, blank)).
pos(next_cell(152,e, red)).
pos(next_cell(16,a, red)).
pos(next_cell(16,b, black)).
pos(next_cell(16,c, red)).
pos(next_cell(16,d, black)).
pos(next_cell(16,e, blank)).
pos(next_cell(18,a, red)).
pos(next_cell(18,b, black)).
pos(next_cell(18,c, black)).
pos(next_cell(18,d, red)).
pos(next_cell(18,e, blank)).
pos(next_cell(19,a, black)).
pos(next_cell(19,b, black)).
pos(next_cell(19,c, blank)).
pos(next_cell(19,d, red)).
pos(next_cell(19,e, red)).
pos(next_cell(2,a, red)).
pos(next_cell(2,b, black)).
pos(next_cell(2,c, red)).
pos(next_cell(2,d, black)).
pos(next_cell(2,e, blank)).
pos(next_cell(20,a, red)).
pos(next_cell(20,b, black)).
pos(next_cell(20,c, black)).
pos(next_cell(20,d, red)).
pos(next_cell(20,e, blank)).
pos(next_cell(21,a, black)).
pos(next_cell(21,b, black)).
pos(next_cell(21,c, blank)).
pos(next_cell(21,d, red)).
pos(next_cell(21,e, red)).
pos(next_cell(22,a, red)).
pos(next_cell(22,b, black)).
pos(next_cell(22,c, red)).
pos(next_cell(22,d, blank)).
pos(next_cell(22,e, black)).
pos(next_cell(23,a, black)).
pos(next_cell(23,b, red)).
pos(next_cell(23,c, black)).
pos(next_cell(23,d, red)).
pos(next_cell(23,e, blank)).
pos(next_cell(24,a, red)).
pos(next_cell(24,b, blank)).
pos(next_cell(24,c, red)).
pos(next_cell(24,d, black)).
pos(next_cell(24,e, black)).
pos(next_cell(25,a, blank)).
pos(next_cell(25,b, red)).
pos(next_cell(25,c, black)).
pos(next_cell(25,d, red)).
pos(next_cell(25,e, black)).
pos(next_cell(26,a, black)).
pos(next_cell(26,b, red)).
pos(next_cell(26,c, red)).
pos(next_cell(26,d, black)).
pos(next_cell(26,e, blank)).
pos(next_cell(27,a, black)).
pos(next_cell(27,b, red)).
pos(next_cell(27,c, blank)).
pos(next_cell(27,d, black)).
pos(next_cell(27,e, red)).
pos(next_cell(3,a, red)).
pos(next_cell(3,b, black)).
pos(next_cell(3,c, red)).
pos(next_cell(3,d, blank)).
pos(next_cell(3,e, black)).
pos(next_cell(30,a, red)).
pos(next_cell(30,b, black)).
pos(next_cell(30,c, blank)).
pos(next_cell(30,d, red)).
pos(next_cell(30,e, black)).
pos(next_cell(31,a, blank)).
pos(next_cell(31,b, black)).
pos(next_cell(31,c, red)).
pos(next_cell(31,d, black)).
pos(next_cell(31,e, red)).
pos(next_cell(32,a, black)).
pos(next_cell(32,b, red)).
pos(next_cell(32,c, blank)).
pos(next_cell(32,d, black)).
pos(next_cell(32,e, red)).
pos(next_cell(33,a, black)).
pos(next_cell(33,b, blank)).
pos(next_cell(33,c, red)).
pos(next_cell(33,d, black)).
pos(next_cell(33,e, red)).
pos(next_cell(34,a, blank)).
pos(next_cell(34,b, red)).
pos(next_cell(34,c, black)).
pos(next_cell(34,d, black)).
pos(next_cell(34,e, red)).
pos(next_cell(35,a, red)).
pos(next_cell(35,b, red)).
pos(next_cell(35,c, black)).
pos(next_cell(35,d, black)).
pos(next_cell(35,e, blank)).
pos(next_cell(36,a, black)).
pos(next_cell(36,b, red)).
pos(next_cell(36,c, black)).
pos(next_cell(36,d, red)).
pos(next_cell(36,e, blank)).
pos(next_cell(38,a, black)).
pos(next_cell(38,b, red)).
pos(next_cell(38,c, blank)).
pos(next_cell(38,d, black)).
pos(next_cell(38,e, red)).
pos(next_cell(39,a, black)).
pos(next_cell(39,b, blank)).
pos(next_cell(39,c, black)).
pos(next_cell(39,d, red)).
pos(next_cell(39,e, red)).
pos(next_cell(4,a, black)).
pos(next_cell(4,b, red)).
pos(next_cell(4,c, red)).
pos(next_cell(4,d, blank)).
pos(next_cell(4,e, black)).
pos(next_cell(40,a, red)).
pos(next_cell(40,b, black)).
pos(next_cell(40,c, blank)).
pos(next_cell(40,d, black)).
pos(next_cell(40,e, red)).
pos(next_cell(41,a, blank)).
pos(next_cell(41,b, red)).
pos(next_cell(41,c, black)).
pos(next_cell(41,d, red)).
pos(next_cell(41,e, black)).
pos(next_cell(42,a, blank)).
pos(next_cell(42,b, red)).
pos(next_cell(42,c, black)).
pos(next_cell(42,d, red)).
pos(next_cell(42,e, black)).
pos(next_cell(43,a, black)).
pos(next_cell(43,b, black)).
pos(next_cell(43,c, blank)).
pos(next_cell(43,d, red)).
pos(next_cell(43,e, red)).
pos(next_cell(44,a, red)).
pos(next_cell(44,b, black)).
pos(next_cell(44,c, blank)).
pos(next_cell(44,d, red)).
pos(next_cell(44,e, black)).
pos(next_cell(45,a, black)).
pos(next_cell(45,b, red)).
pos(next_cell(45,c, black)).
pos(next_cell(45,d, blank)).
pos(next_cell(45,e, red)).
pos(next_cell(46,a, blank)).
pos(next_cell(46,b, red)).
pos(next_cell(46,c, black)).
pos(next_cell(46,d, red)).
pos(next_cell(46,e, black)).
pos(next_cell(47,a, red)).
pos(next_cell(47,b, black)).
pos(next_cell(47,c, red)).
pos(next_cell(47,d, black)).
pos(next_cell(47,e, blank)).
pos(next_cell(48,a, red)).
pos(next_cell(48,b, blank)).
pos(next_cell(48,c, red)).
pos(next_cell(48,d, black)).
pos(next_cell(48,e, black)).
pos(next_cell(5,a, red)).
pos(next_cell(5,b, black)).
pos(next_cell(5,c, blank)).
pos(next_cell(5,d, black)).
pos(next_cell(5,e, red)).
pos(next_cell(50,a, black)).
pos(next_cell(50,b, black)).
pos(next_cell(50,c, blank)).
pos(next_cell(50,d, red)).
pos(next_cell(50,e, red)).
pos(next_cell(51,a, red)).
pos(next_cell(51,b, black)).
pos(next_cell(51,c, blank)).
pos(next_cell(51,d, red)).
pos(next_cell(51,e, black)).
pos(next_cell(52,a, black)).
pos(next_cell(52,b, red)).
pos(next_cell(52,c, black)).
pos(next_cell(52,d, red)).
pos(next_cell(52,e, blank)).
pos(next_cell(53,a, red)).
pos(next_cell(53,b, black)).
pos(next_cell(53,c, black)).
pos(next_cell(53,d, red)).
pos(next_cell(53,e, blank)).
pos(next_cell(54,a, blank)).
pos(next_cell(54,b, black)).
pos(next_cell(54,c, black)).
pos(next_cell(54,d, red)).
pos(next_cell(54,e, red)).
pos(next_cell(55,a, red)).
pos(next_cell(55,b, black)).
pos(next_cell(55,c, red)).
pos(next_cell(55,d, black)).
pos(next_cell(55,e, blank)).
pos(next_cell(56,a, red)).
pos(next_cell(56,b, blank)).
pos(next_cell(56,c, black)).
pos(next_cell(56,d, red)).
pos(next_cell(56,e, black)).
pos(next_cell(57,a, red)).
pos(next_cell(57,b, blank)).
pos(next_cell(57,c, black)).
pos(next_cell(57,d, black)).
pos(next_cell(57,e, red)).
pos(next_cell(58,a, red)).
pos(next_cell(58,b, black)).
pos(next_cell(58,c, blank)).
pos(next_cell(58,d, black)).
pos(next_cell(58,e, red)).
pos(next_cell(59,a, black)).
pos(next_cell(59,b, red)).
pos(next_cell(59,c, blank)).
pos(next_cell(59,d, red)).
pos(next_cell(59,e, black)).
pos(next_cell(6,a, black)).
pos(next_cell(6,b, red)).
pos(next_cell(6,c, red)).
pos(next_cell(6,d, black)).
pos(next_cell(6,e, blank)).
pos(next_cell(60,a, blank)).
pos(next_cell(60,b, red)).
pos(next_cell(60,c, black)).
pos(next_cell(60,d, black)).
pos(next_cell(60,e, red)).
pos(next_cell(61,a, black)).
pos(next_cell(61,b, blank)).
pos(next_cell(61,c, red)).
pos(next_cell(61,d, black)).
pos(next_cell(61,e, red)).
pos(next_cell(62,a, black)).
pos(next_cell(62,b, red)).
pos(next_cell(62,c, blank)).
pos(next_cell(62,d, red)).
pos(next_cell(62,e, black)).
pos(next_cell(64,a, red)).
pos(next_cell(64,b, black)).
pos(next_cell(64,c, blank)).
pos(next_cell(64,d, black)).
pos(next_cell(64,e, red)).
pos(next_cell(65,a, blank)).
pos(next_cell(65,b, red)).
pos(next_cell(65,c, red)).
pos(next_cell(65,d, black)).
pos(next_cell(65,e, black)).
pos(next_cell(66,a, black)).
pos(next_cell(66,b, red)).
pos(next_cell(66,c, red)).
pos(next_cell(66,d, black)).
pos(next_cell(66,e, blank)).
pos(next_cell(67,a, black)).
pos(next_cell(67,b, red)).
pos(next_cell(67,c, blank)).
pos(next_cell(67,d, black)).
pos(next_cell(67,e, red)).
pos(next_cell(70,a, red)).
pos(next_cell(70,b, black)).
pos(next_cell(70,c, blank)).
pos(next_cell(70,d, red)).
pos(next_cell(70,e, black)).
pos(next_cell(72,a, red)).
pos(next_cell(72,b, blank)).
pos(next_cell(72,c, black)).
pos(next_cell(72,d, red)).
pos(next_cell(72,e, black)).
pos(next_cell(73,a, blank)).
pos(next_cell(73,b, black)).
pos(next_cell(73,c, red)).
pos(next_cell(73,d, black)).
pos(next_cell(73,e, red)).
pos(next_cell(74,a, red)).
pos(next_cell(74,b, blank)).
pos(next_cell(74,c, black)).
pos(next_cell(74,d, black)).
pos(next_cell(74,e, red)).
pos(next_cell(75,a, red)).
pos(next_cell(75,b, blank)).
pos(next_cell(75,c, black)).
pos(next_cell(75,d, red)).
pos(next_cell(75,e, black)).
pos(next_cell(76,a, blank)).
pos(next_cell(76,b, black)).
pos(next_cell(76,c, red)).
pos(next_cell(76,d, black)).
pos(next_cell(76,e, red)).
pos(next_cell(77,a, red)).
pos(next_cell(77,b, black)).
pos(next_cell(77,c, black)).
pos(next_cell(77,d, blank)).
pos(next_cell(77,e, red)).
pos(next_cell(78,a, red)).
pos(next_cell(78,b, black)).
pos(next_cell(78,c, black)).
pos(next_cell(78,d, blank)).
pos(next_cell(78,e, red)).
pos(next_cell(79,a, red)).
pos(next_cell(79,b, black)).
pos(next_cell(79,c, red)).
pos(next_cell(79,d, black)).
pos(next_cell(79,e, blank)).
pos(next_cell(8,a, blank)).
pos(next_cell(8,b, black)).
pos(next_cell(8,c, black)).
pos(next_cell(8,d, red)).
pos(next_cell(8,e, red)).
pos(next_cell(80,a, black)).
pos(next_cell(80,b, blank)).
pos(next_cell(80,c, red)).
pos(next_cell(80,d, red)).
pos(next_cell(80,e, black)).
pos(next_cell(81,a, black)).
pos(next_cell(81,b, red)).
pos(next_cell(81,c, blank)).
pos(next_cell(81,d, black)).
pos(next_cell(81,e, red)).
pos(next_cell(83,a, red)).
pos(next_cell(83,b, black)).
pos(next_cell(83,c, blank)).
pos(next_cell(83,d, red)).
pos(next_cell(83,e, black)).
pos(next_cell(84,a, blank)).
pos(next_cell(84,b, red)).
pos(next_cell(84,c, black)).
pos(next_cell(84,d, black)).
pos(next_cell(84,e, red)).
pos(next_cell(85,a, red)).
pos(next_cell(85,b, blank)).
pos(next_cell(85,c, black)).
pos(next_cell(85,d, red)).
pos(next_cell(85,e, black)).
pos(next_cell(86,a, red)).
pos(next_cell(86,b, blank)).
pos(next_cell(86,c, red)).
pos(next_cell(86,d, black)).
pos(next_cell(86,e, black)).
pos(next_cell(87,a, red)).
pos(next_cell(87,b, black)).
pos(next_cell(87,c, blank)).
pos(next_cell(87,d, red)).
pos(next_cell(87,e, black)).
pos(next_cell(88,a, blank)).
pos(next_cell(88,b, black)).
pos(next_cell(88,c, black)).
pos(next_cell(88,d, red)).
pos(next_cell(88,e, red)).
pos(next_cell(89,a, red)).
pos(next_cell(89,b, blank)).
pos(next_cell(89,c, black)).
pos(next_cell(89,d, red)).
pos(next_cell(89,e, black)).
pos(next_cell(9,a, black)).
pos(next_cell(9,b, red)).
pos(next_cell(9,c, black)).
pos(next_cell(9,d, red)).
pos(next_cell(9,e, blank)).
pos(next_cell(90,a, black)).
pos(next_cell(90,b, red)).
pos(next_cell(90,c, blank)).
pos(next_cell(90,d, red)).
pos(next_cell(90,e, black)).
pos(next_cell(91,a, black)).
pos(next_cell(91,b, red)).
pos(next_cell(91,c, black)).
pos(next_cell(91,d, red)).
pos(next_cell(91,e, blank)).
pos(next_cell(93,a, red)).
pos(next_cell(93,b, black)).
pos(next_cell(93,c, blank)).
pos(next_cell(93,d, black)).
pos(next_cell(93,e, red)).
pos(next_cell(94,a, red)).
pos(next_cell(94,b, blank)).
pos(next_cell(94,c, black)).
pos(next_cell(94,d, black)).
pos(next_cell(94,e, red)).
pos(next_cell(95,a, red)).
pos(next_cell(95,b, black)).
pos(next_cell(95,c, blank)).
pos(next_cell(95,d, red)).
pos(next_cell(95,e, black)).
pos(next_cell(96,a, black)).
pos(next_cell(96,b, blank)).
pos(next_cell(96,c, red)).
pos(next_cell(96,d, black)).
pos(next_cell(96,e, red)).
pos(next_cell(97,a, black)).
pos(next_cell(97,b, black)).
pos(next_cell(97,c, red)).
pos(next_cell(97,d, blank)).
pos(next_cell(97,e, red)).
pos(next_cell(98,a, black)).
pos(next_cell(98,b, blank)).
pos(next_cell(98,c, red)).
pos(next_cell(98,d, red)).
pos(next_cell(98,e, black)).
pos(next_cell(99,a, red)).
pos(next_cell(99,b, black)).
pos(next_cell(99,c, red)).
pos(next_cell(99,d, blank)).
pos(next_cell(99,e, black)).