different(A,B):- my_pos(A), my_pos(B), A != B.
c_zerocoins(zerocoins).
c_onecoin(onecoin).
c_twocoins(twocoins).
role(you).
my_pos(1).
my_pos(2).
my_pos(3).
my_pos(4).
my_pos(5).
my_pos(6).
my_pos(7).
my_pos(8).
my_succ(1,2).
my_succ(2,3).
my_succ(3,4).
my_succ(4,5).
my_succ(5,6).
my_succ(6,7).
my_succ(7,8).