#T10
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
does_jump(you,5,2).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
my_true_cell(3,onecoin).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
my_true_step(1).

#T101
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
my_true_cell(3,onecoin).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
does_jump(you,7,4).
my_true_step(1).

#T103
my_true_cell(6,onecoin).
my_true_cell(1,twocoins).
my_true_cell(8,onecoin).
my_true_cell(3,zerocoins).
my_true_cell(5,zerocoins).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
does_jump(you,4,8).
my_true_step(3).
my_true_cell(2,twocoins).

#T105
my_true_cell(6,onecoin).
my_true_cell(1,twocoins).
my_true_cell(8,onecoin).
my_true_cell(3,zerocoins).
does_jump(you,8,4).
my_true_cell(5,zerocoins).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
my_true_step(3).
my_true_cell(2,twocoins).

#T106
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
does_jump(you,6,8).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_step(2).
my_true_cell(7,twocoins).

#T11
my_true_cell(6,onecoin).
my_true_cell(2,onecoin).
does_jump(you,6,8).
my_true_cell(1,twocoins).
my_true_cell(8,onecoin).
my_true_cell(5,zerocoins).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_cell(7,twocoins).
my_true_step(3).

#T13
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(8,onecoin).
does_jump(you,4,1).
my_true_cell(3,zerocoins).
my_true_cell(5,zerocoins).
my_true_cell(4,onecoin).
my_true_cell(7,twocoins).
my_true_step(3).
my_true_cell(2,twocoins).

#T14
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(8,onecoin).
does_jump(you,1,3).
my_true_cell(5,zerocoins).
my_true_cell(3,onecoin).
my_true_step(2).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
my_true_cell(2,twocoins).

#T15
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
my_true_cell(3,onecoin).
does_jump(you,6,3).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
my_true_step(1).

#T17
my_true_cell(6,onecoin).
my_true_cell(2,onecoin).
my_true_cell(4,twocoins).
my_true_cell(1,zerocoins).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
does_jump(you,3,5).
my_true_cell(3,onecoin).
my_true_step(2).
my_true_cell(7,onecoin).

#T19
my_true_cell(6,onecoin).
my_true_cell(8,onecoin).
my_true_cell(1,zerocoins).
my_true_cell(3,twocoins).
my_true_cell(5,zerocoins).
does_jump(you,8,4).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
my_true_step(3).
my_true_cell(2,twocoins).

#T2
my_true_step(3).
my_true_cell(1,onecoin).
my_true_cell(6,twocoins).
my_true_cell(5,zerocoins).
my_true_cell(3,onecoin).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
does_jump(you,7,4).
my_true_cell(2,zerocoins).
my_true_cell(8,twocoins).

#T20
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
does_jump(you,4,1).
my_true_cell(5,zerocoins).
my_true_cell(3,onecoin).
my_true_step(2).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
my_true_cell(8,twocoins).

#T21
my_true_cell(6,zerocoins).
does_jump(you,8,3).
my_true_cell(1,twocoins).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_cell(7,onecoin).
my_true_step(3).
my_true_cell(2,twocoins).

#T22
my_true_step(3).
my_true_cell(1,onecoin).
does_jump(you,4,7).
my_true_cell(5,zerocoins).
my_true_cell(3,onecoin).
my_true_cell(6,twocoins).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
my_true_cell(2,zerocoins).
my_true_cell(8,twocoins).

#T23
my_true_cell(6,onecoin).
my_true_cell(2,onecoin).
my_true_cell(1,twocoins).
my_true_cell(8,onecoin).
does_jump(you,8,5).
my_true_cell(5,onecoin).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_step(2).
my_true_cell(7,onecoin).

#T24
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(5,zerocoins).
my_true_cell(3,onecoin).
my_true_step(2).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
does_jump(you,3,7).
my_true_cell(8,twocoins).

#T26
my_true_cell(6,zerocoins).
my_true_cell(8,onecoin).
my_true_cell(1,zerocoins).
my_true_cell(5,onecoin).
my_true_cell(3,twocoins).
does_jump(you,5,8).
my_true_step(4).
my_true_cell(4,zerocoins).
my_true_cell(7,twocoins).
my_true_cell(2,twocoins).

#T27
my_true_cell(2,onecoin).
my_true_cell(1,twocoins).
my_true_cell(8,onecoin).
does_jump(you,4,7).
my_true_cell(3,zerocoins).
my_true_cell(5,zerocoins).
my_true_cell(6,twocoins).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
my_true_step(3).

#T28
my_true_step(3).
my_true_cell(1,onecoin).
my_true_cell(6,zerocoins).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_cell(7,twocoins).
does_jump(you,3,1).
my_true_cell(2,twocoins).

#T30
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
does_jump(you,2,6).
my_true_cell(2,onecoin).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_step(2).
my_true_cell(7,twocoins).

#T31
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
my_true_cell(6,twocoins).
my_true_cell(3,zerocoins).
my_true_step(2).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
does_jump(you,5,1).

#T32
my_true_cell(6,onecoin).
my_true_cell(2,onecoin).
my_true_cell(1,twocoins).
does_jump(you,2,5).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
my_true_cell(3,twocoins).
my_true_cell(4,zerocoins).
my_true_cell(7,zerocoins).
my_true_step(3).

#T33
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(5,zerocoins).
my_true_cell(3,onecoin).
my_true_step(2).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
does_jump(you,7,3).
my_true_cell(8,twocoins).

#T35
my_true_step(3).
my_true_cell(1,onecoin).
my_true_cell(6,zerocoins).
my_true_cell(5,zerocoins).
my_true_cell(3,onecoin).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
does_jump(you,3,1).
my_true_cell(8,twocoins).
my_true_cell(2,twocoins).

#T36
my_true_cell(6,onecoin).
my_true_cell(2,onecoin).
my_true_cell(4,twocoins).
my_true_cell(1,zerocoins).
my_true_cell(5,zerocoins).
my_true_cell(3,onecoin).
does_jump(you,3,6).
my_true_cell(7,onecoin).
my_true_step(3).
my_true_cell(8,twocoins).

#T38
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(6,zerocoins).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
my_true_cell(3,twocoins).
does_jump(you,8,4).
my_true_step(2).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).

#T39
my_true_cell(6,onecoin).
my_true_step(3).
my_true_cell(1,onecoin).
my_true_cell(4,twocoins).
my_true_cell(8,zerocoins).
my_true_cell(5,zerocoins).
my_true_cell(3,onecoin).
my_true_cell(7,onecoin).
does_jump(you,3,1).
my_true_cell(2,twocoins).

#T4
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
does_jump(you,2,6).
my_true_cell(2,onecoin).
my_true_cell(5,zerocoins).
my_true_cell(3,onecoin).
my_true_step(2).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
my_true_cell(8,twocoins).

#T40
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(8,onecoin).
does_jump(you,7,5).
my_true_cell(5,onecoin).
my_true_cell(6,twocoins).
my_true_cell(3,zerocoins).
my_true_step(2).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).

#T41
my_true_cell(6,onecoin).
my_true_cell(2,onecoin).
my_true_cell(4,twocoins).
my_true_cell(1,zerocoins).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
does_jump(you,5,8).
my_true_cell(3,onecoin).
my_true_step(2).
my_true_cell(7,onecoin).

#T42
my_true_cell(1,onecoin).
my_true_cell(6,zerocoins).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
does_jump(you,5,8).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_cell(7,twocoins).
my_true_step(3).
my_true_cell(2,twocoins).

#T43
my_true_cell(6,onecoin).
my_true_cell(2,onecoin).
my_true_cell(1,twocoins).
my_true_cell(8,zerocoins).
my_true_cell(3,onecoin).
does_jump(you,3,6).
my_true_cell(4,zerocoins).
my_true_cell(7,onecoin).
my_true_cell(5,twocoins).
my_true_step(3).

#T44
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(4,twocoins).
my_true_cell(8,zerocoins).
my_true_cell(5,zerocoins).
my_true_cell(3,onecoin).
does_jump(you,3,6).
my_true_cell(7,onecoin).
my_true_step(3).
my_true_cell(2,twocoins).

#T45
does_jump(you,5,7).
my_true_step(3).
my_true_cell(1,twocoins).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
my_true_cell(6,twocoins).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_cell(7,onecoin).
my_true_cell(2,zerocoins).

#T46
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
does_jump(you,4,7).
my_true_cell(3,onecoin).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
my_true_step(1).

#T47
my_true_cell(6,onecoin).
my_true_step(3).
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(3,twocoins).
my_true_cell(5,zerocoins).
my_true_cell(4,onecoin).
my_true_cell(7,zerocoins).
does_jump(you,2,4).
my_true_cell(8,twocoins).

#T49
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(6,zerocoins).
my_true_cell(5,onecoin).
does_jump(you,1,5).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_cell(7,twocoins).
my_true_step(3).
my_true_cell(8,twocoins).

#T51
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
does_jump(you,6,1).
my_true_cell(3,zerocoins).
my_true_cell(5,zerocoins).
my_true_cell(4,onecoin).
my_true_cell(7,twocoins).
my_true_step(3).
my_true_cell(8,twocoins).

#T53
does_jump(you,6,2).
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_step(2).
my_true_cell(7,twocoins).

#T54
my_true_cell(6,onecoin).
my_true_step(3).
my_true_cell(1,onecoin).
my_true_cell(5,zerocoins).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_cell(7,onecoin).
does_jump(you,3,1).
my_true_cell(8,twocoins).
my_true_cell(2,twocoins).

#T55
my_true_cell(6,onecoin).
my_true_cell(2,onecoin).
does_jump(you,6,8).
my_true_cell(8,onecoin).
my_true_cell(1,zerocoins).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_cell(5,twocoins).
my_true_cell(7,twocoins).
my_true_step(3).

#T56
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(8,zerocoins).
does_jump(you,4,1).
my_true_cell(3,onecoin).
my_true_step(2).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
my_true_cell(5,twocoins).

#T61
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
my_true_cell(3,onecoin).
does_jump(you,3,6).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
my_true_step(1).

#T62
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(6,zerocoins).
my_true_cell(5,onecoin).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
does_jump(you,5,1).
my_true_cell(7,twocoins).
my_true_step(3).
my_true_cell(8,twocoins).

#T63
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(8,zerocoins).
my_true_cell(5,onecoin).
my_true_cell(6,twocoins).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
does_jump(you,5,1).
my_true_cell(7,twocoins).
my_true_step(3).

#T64
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
does_jump(you,4,1).
my_true_cell(3,onecoin).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
my_true_step(1).

#T65
my_true_cell(6,onecoin).
my_true_cell(2,onecoin).
does_jump(you,6,8).
my_true_cell(1,twocoins).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
my_true_cell(3,zerocoins).
my_true_cell(4,zerocoins).
my_true_cell(7,twocoins).
my_true_step(3).

#T66
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(8,onecoin).
my_true_cell(3,onecoin).
my_true_step(2).
does_jump(you,6,4).
my_true_cell(4,onecoin).
my_true_cell(5,twocoins).
my_true_cell(7,onecoin).
my_true_cell(2,zerocoins).

#T68
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
does_jump(you,5,8).
my_true_cell(3,onecoin).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
my_true_step(1).

#T7
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(6,zerocoins).
does_jump(you,5,2).
my_true_cell(5,onecoin).
my_true_cell(3,twocoins).
my_true_cell(4,zerocoins).
my_true_cell(7,onecoin).
my_true_step(3).
my_true_cell(8,twocoins).

#T71
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(6,zerocoins).
does_jump(you,2,5).
my_true_cell(5,onecoin).
my_true_cell(3,twocoins).
my_true_cell(4,zerocoins).
my_true_cell(7,onecoin).
my_true_step(3).
my_true_cell(8,twocoins).

#T72
my_true_cell(1,onecoin).
my_true_cell(6,zerocoins).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
does_jump(you,1,3).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_cell(7,twocoins).
my_true_step(3).
my_true_cell(2,twocoins).

#T73
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(8,onecoin).
my_true_cell(5,zerocoins).
my_true_cell(3,onecoin).
my_true_step(2).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
does_jump(you,7,3).
my_true_cell(2,twocoins).

#T75
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(4,twocoins).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
does_jump(you,3,5).
my_true_cell(3,onecoin).
my_true_step(2).
my_true_cell(7,zerocoins).

#T76
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
does_jump(you,1,4).
my_true_cell(2,onecoin).
my_true_cell(5,zerocoins).
my_true_cell(3,onecoin).
my_true_step(2).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
my_true_cell(8,twocoins).

#T77
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
does_jump(you,1,4).
my_true_cell(2,onecoin).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
my_true_cell(3,onecoin).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
my_true_step(1).

#T78
my_true_cell(6,onecoin).
does_jump(you,6,8).
my_true_cell(1,twocoins).
my_true_cell(8,onecoin).
my_true_step(4).
my_true_cell(3,zerocoins).
my_true_cell(5,zerocoins).
my_true_cell(4,zerocoins).
my_true_cell(7,twocoins).
my_true_cell(2,twocoins).

#T79
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(6,zerocoins).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
my_true_cell(3,twocoins).
my_true_step(2).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
does_jump(you,4,8).

#T8
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
does_jump(you,5,3).
my_true_cell(2,onecoin).
my_true_cell(4,twocoins).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
my_true_cell(3,onecoin).
my_true_step(2).
my_true_cell(7,zerocoins).

#T81
my_true_cell(6,onecoin).
does_jump(you,2,7).
my_true_cell(2,onecoin).
my_true_cell(1,twocoins).
my_true_cell(5,zerocoins).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_cell(7,onecoin).
my_true_step(3).
my_true_cell(8,twocoins).

#T83
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(8,onecoin).
does_jump(you,8,5).
my_true_cell(5,onecoin).
my_true_cell(3,onecoin).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
my_true_step(1).

#T84
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_step(2).
does_jump(you,5,1).
my_true_cell(7,twocoins).

#T86
my_true_cell(6,onecoin).
my_true_cell(2,onecoin).
my_true_cell(1,twocoins).
does_jump(you,5,2).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
my_true_cell(3,twocoins).
my_true_cell(4,zerocoins).
my_true_cell(7,zerocoins).
my_true_step(3).

#T87
does_jump(you,6,2).
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(5,zerocoins).
my_true_cell(3,onecoin).
my_true_step(2).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
my_true_cell(8,twocoins).

#T89
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(8,onecoin).
my_true_cell(5,zerocoins).
does_jump(you,8,4).
my_true_cell(3,onecoin).
my_true_step(2).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
my_true_cell(2,twocoins).

#T9
my_true_cell(6,onecoin).
my_true_cell(2,onecoin).
my_true_cell(8,onecoin).
my_true_cell(1,zerocoins).
my_true_cell(3,onecoin).
does_jump(you,3,6).
my_true_cell(4,zerocoins).
my_true_cell(5,twocoins).
my_true_cell(7,twocoins).
my_true_step(3).

#T90
my_true_cell(6,onecoin).
my_true_cell(2,onecoin).
my_true_cell(1,twocoins).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_step(2).
my_true_cell(7,onecoin).
does_jump(you,3,7).

#T91
my_true_cell(1,onecoin).
does_jump(you,4,2).
my_true_cell(2,onecoin).
my_true_cell(6,zerocoins).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
my_true_cell(3,twocoins).
my_true_step(2).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).

#T93
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
does_jump(you,1,3).
my_true_cell(5,zerocoins).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_cell(7,onecoin).
my_true_step(3).
my_true_cell(8,twocoins).
my_true_cell(2,twocoins).

#T96
does_jump(you,6,2).
my_true_cell(6,onecoin).
my_true_cell(2,onecoin).
my_true_cell(1,twocoins).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_step(2).
my_true_cell(7,onecoin).

#T99
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(8,zerocoins).
my_true_cell(3,onecoin).
my_true_step(2).
does_jump(you,6,4).
my_true_cell(4,onecoin).
my_true_cell(5,twocoins).
my_true_cell(7,onecoin).

#T1
my_true_step(3).
my_true_cell(1,onecoin).
my_true_cell(8,onecoin).
my_true_cell(6,twocoins).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_cell(7,onecoin).
my_true_cell(5,twocoins).
my_true_cell(2,zerocoins).

#T100
my_true_cell(1,onecoin).
my_true_cell(6,zerocoins).
my_true_cell(4,twocoins).
my_true_cell(8,zerocoins).
my_true_cell(3,twocoins).
my_true_step(4).
my_true_cell(5,zerocoins).
my_true_cell(7,onecoin).
my_true_cell(2,twocoins).

#T102
my_true_cell(6,onecoin).
my_true_cell(1,zerocoins).
my_true_cell(3,twocoins).
my_true_step(4).
my_true_cell(5,zerocoins).
my_true_cell(4,zerocoins).
my_true_cell(7,onecoin).
my_true_cell(8,twocoins).
my_true_cell(2,twocoins).

#T104
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(3,twocoins).
my_true_step(4).
my_true_cell(5,zerocoins).
my_true_cell(4,zerocoins).
my_true_cell(7,zerocoins).
my_true_cell(8,twocoins).
my_true_cell(2,twocoins).

#T12
my_true_step(3).
my_true_cell(1,onecoin).
my_true_cell(6,zerocoins).
my_true_cell(4,twocoins).
my_true_cell(8,onecoin).
my_true_cell(3,onecoin).
my_true_cell(7,onecoin).
my_true_cell(5,twocoins).
my_true_cell(2,zerocoins).

#T16
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(6,zerocoins).
my_true_cell(4,twocoins).
my_true_cell(8,zerocoins).
my_true_cell(5,onecoin).
my_true_cell(3,twocoins).
my_true_cell(7,onecoin).
my_true_step(3).

#T18
my_true_cell(1,twocoins).
my_true_cell(8,onecoin).
my_true_step(4).
my_true_cell(6,twocoins).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_cell(5,twocoins).
my_true_cell(7,zerocoins).
my_true_cell(2,zerocoins).

#T25
my_true_cell(2,onecoin).
my_true_cell(8,zerocoins).
my_true_cell(1,zerocoins).
my_true_step(4).
my_true_cell(6,twocoins).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_cell(5,twocoins).
my_true_cell(7,twocoins).

#T29
my_true_cell(6,onecoin).
my_true_cell(1,twocoins).
my_true_cell(8,onecoin).
my_true_cell(3,twocoins).
my_true_step(4).
my_true_cell(5,zerocoins).
my_true_cell(4,zerocoins).
my_true_cell(7,zerocoins).
my_true_cell(2,twocoins).

#T3
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(8,onecoin).
my_true_cell(6,twocoins).
my_true_cell(3,zerocoins).
my_true_cell(4,onecoin).
my_true_cell(5,twocoins).
my_true_cell(7,zerocoins).
my_true_step(3).

#T34
my_true_cell(6,onecoin).
my_true_cell(1,onecoin).
my_true_cell(8,onecoin).
my_true_cell(3,twocoins).
my_true_cell(5,zerocoins).
my_true_cell(4,onecoin).
my_true_cell(7,zerocoins).
my_true_step(3).
my_true_cell(2,twocoins).

#T37
my_true_cell(2,onecoin).
my_true_cell(1,twocoins).
my_true_cell(8,zerocoins).
my_true_step(4).
my_true_cell(6,twocoins).
my_true_cell(3,zerocoins).
my_true_cell(4,zerocoins).
my_true_cell(7,onecoin).
my_true_cell(5,twocoins).

#T48
my_true_cell(6,onecoin).
my_true_cell(1,twocoins).
my_true_cell(8,onecoin).
my_true_cell(3,twocoins).
my_true_step(4).
my_true_cell(4,zerocoins).
my_true_cell(5,twocoins).
my_true_cell(7,zerocoins).
my_true_cell(2,zerocoins).

#T5
my_true_cell(6,zerocoins).
my_true_cell(2,onecoin).
my_true_cell(1,zerocoins).
my_true_step(4).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_cell(5,twocoins).
my_true_cell(7,twocoins).
my_true_cell(8,twocoins).

#T50
my_true_cell(2,onecoin).
my_true_cell(8,onecoin).
my_true_cell(1,zerocoins).
my_true_step(4).
my_true_cell(6,twocoins).
my_true_cell(3,zerocoins).
my_true_cell(4,zerocoins).
my_true_cell(5,twocoins).
my_true_cell(7,twocoins).

#T52
my_true_cell(1,onecoin).
my_true_cell(4,twocoins).
my_true_step(4).
my_true_cell(6,twocoins).
my_true_cell(5,zerocoins).
my_true_cell(3,onecoin).
my_true_cell(7,zerocoins).
my_true_cell(2,zerocoins).
my_true_cell(8,twocoins).

#T57
my_true_cell(6,onecoin).
my_true_cell(1,twocoins).
my_true_step(4).
my_true_cell(5,zerocoins).
my_true_cell(3,zerocoins).
my_true_cell(4,zerocoins).
my_true_cell(7,onecoin).
my_true_cell(8,twocoins).
my_true_cell(2,twocoins).

#T58
my_true_cell(6,onecoin).
my_true_cell(1,twocoins).
my_true_step(4).
my_true_cell(5,zerocoins).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_cell(7,twocoins).
my_true_cell(2,zerocoins).
my_true_cell(8,twocoins).

#T59
my_true_cell(2,onecoin).
my_true_cell(4,twocoins).
my_true_cell(1,zerocoins).
my_true_step(4).
my_true_cell(6,twocoins).
my_true_cell(5,zerocoins).
my_true_cell(3,zerocoins).
my_true_cell(7,onecoin).
my_true_cell(8,twocoins).

#T6
my_true_step(3).
my_true_cell(1,onecoin).
my_true_cell(6,zerocoins).
my_true_cell(4,twocoins).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
my_true_cell(3,twocoins).
my_true_cell(7,onecoin).
my_true_cell(2,zerocoins).

#T60
my_true_cell(6,zerocoins).
my_true_step(5).
my_true_cell(1,zerocoins).
my_true_cell(3,twocoins).
my_true_cell(5,zerocoins).
my_true_cell(4,zerocoins).
my_true_cell(7,twocoins).
my_true_cell(8,twocoins).
my_true_cell(2,twocoins).

#T67
my_true_cell(6,zerocoins).
my_true_cell(2,onecoin).
my_true_cell(4,twocoins).
my_true_cell(1,zerocoins).
my_true_cell(3,twocoins).
my_true_step(4).
my_true_cell(5,zerocoins).
my_true_cell(7,onecoin).
my_true_cell(8,twocoins).

#T69
my_true_cell(1,onecoin).
my_true_cell(6,zerocoins).
my_true_cell(3,twocoins).
my_true_step(4).
my_true_cell(4,zerocoins).
my_true_cell(7,onecoin).
my_true_cell(5,twocoins).
my_true_cell(2,zerocoins).
my_true_cell(8,twocoins).

#T70
my_true_cell(1,onecoin).
my_true_step(4).
my_true_cell(6,twocoins).
my_true_cell(5,zerocoins).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_cell(7,twocoins).
my_true_cell(2,zerocoins).
my_true_cell(8,twocoins).

#T74
my_true_cell(6,zerocoins).
my_true_cell(2,onecoin).
my_true_cell(1,twocoins).
my_true_step(4).
my_true_cell(5,zerocoins).
my_true_cell(3,zerocoins).
my_true_cell(4,onecoin).
my_true_cell(7,twocoins).
my_true_cell(8,twocoins).

#T80
my_true_cell(2,onecoin).
my_true_cell(8,onecoin).
my_true_cell(1,zerocoins).
my_true_cell(6,twocoins).
my_true_cell(3,zerocoins).
my_true_cell(7,onecoin).
my_true_cell(4,onecoin).
my_true_cell(5,twocoins).
my_true_step(3).

#T82
my_true_step(3).
my_true_cell(1,onecoin).
my_true_cell(8,onecoin).
my_true_cell(5,onecoin).
my_true_cell(6,twocoins).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_cell(7,twocoins).
my_true_cell(2,zerocoins).

#T85
my_true_cell(6,zerocoins).
my_true_cell(1,twocoins).
my_true_cell(8,zerocoins).
my_true_cell(5,onecoin).
my_true_cell(3,twocoins).
my_true_step(4).
my_true_cell(4,zerocoins).
my_true_cell(7,onecoin).
my_true_cell(2,twocoins).

#T88
my_true_cell(6,onecoin).
my_true_cell(2,onecoin).
my_true_cell(4,twocoins).
my_true_cell(1,zerocoins).
my_true_cell(8,onecoin).
my_true_cell(3,twocoins).
my_true_cell(5,zerocoins).
my_true_cell(7,onecoin).
my_true_step(3).

#T92
my_true_cell(6,onecoin).
my_true_cell(4,twocoins).
my_true_cell(1,twocoins).
my_true_cell(8,zerocoins).
my_true_step(4).
my_true_cell(5,zerocoins).
my_true_cell(3,zerocoins).
my_true_cell(7,onecoin).
my_true_cell(2,twocoins).

#T94
my_true_cell(6,onecoin).
my_true_cell(1,twocoins).
my_true_step(4).
my_true_cell(5,zerocoins).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_cell(7,zerocoins).
my_true_cell(8,twocoins).
my_true_cell(2,twocoins).

#T95
my_true_cell(6,zerocoins).
my_true_cell(2,onecoin).
my_true_cell(1,twocoins).
my_true_step(4).
my_true_cell(5,zerocoins).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_cell(7,twocoins).
my_true_cell(8,twocoins).

#T97
my_true_cell(1,onecoin).
my_true_cell(2,onecoin).
my_true_cell(8,zerocoins).
my_true_cell(6,twocoins).
my_true_cell(3,onecoin).
my_true_cell(4,zerocoins).
my_true_cell(7,onecoin).
my_true_cell(5,twocoins).
my_true_step(3).

#T98
my_true_cell(6,onecoin).
my_true_cell(2,onecoin).
my_true_cell(4,twocoins).
my_true_cell(1,zerocoins).
my_true_cell(8,zerocoins).
my_true_cell(3,onecoin).
my_true_cell(7,onecoin).
my_true_cell(5,twocoins).
my_true_step(3).

