#T1
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T10
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
pos(next_cell(4,onecoin)).
pos(next_cell(8,onecoin)).
pos(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
pos(next_cell(2,twocoins)).
neg(next_cell(1,zerocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(5,zerocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
neg(next_cell(2,onecoin)).
neg(next_cell(6,twocoins)).

#T100
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T101
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
pos(next_cell(5,onecoin)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(3,zerocoins)).
neg(next_cell(1,twocoins)).
pos(next_cell(2,onecoin)).
pos(next_cell(8,onecoin)).
pos(next_cell(4,twocoins)).
pos(next_cell(1,onecoin)).
pos(next_cell(7,zerocoins)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,zerocoins)).
neg(next_cell(7,onecoin)).

#T102
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T103
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(5,onecoin)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
pos(next_cell(2,twocoins)).
neg(next_cell(1,zerocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
pos(next_cell(4,zerocoins)).
pos(next_cell(1,twocoins)).
neg(next_cell(2,onecoin)).
pos(next_cell(8,twocoins)).
neg(next_cell(3,onecoin)).
neg(next_cell(6,twocoins)).

#T104
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T105
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(5,onecoin)).
pos(next_cell(8,zerocoins)).
neg(next_cell(8,onecoin)).
pos(next_cell(4,twocoins)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
pos(next_cell(2,twocoins)).
neg(next_cell(1,zerocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
pos(next_cell(5,zerocoins)).
pos(next_cell(3,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
pos(next_cell(1,twocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(6,twocoins)).

#T106
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
pos(next_cell(5,onecoin)).
neg(next_cell(5,zerocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(1,twocoins)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(7,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
pos(next_cell(1,onecoin)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(6,zerocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,zerocoins)).
pos(next_cell(4,zerocoins)).
pos(next_cell(8,twocoins)).
neg(next_cell(7,onecoin)).

#T11
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(7,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(6,zerocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,zerocoins)).
pos(next_cell(4,zerocoins)).
pos(next_cell(1,twocoins)).
pos(next_cell(8,twocoins)).
neg(next_cell(7,onecoin)).

#T12
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T13
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(8,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(5,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(7,twocoins)).
pos(next_cell(8,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
pos(next_cell(2,twocoins)).
neg(next_cell(1,zerocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(4,zerocoins)).
pos(next_cell(1,twocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T14
neg(next_cell(7,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
pos(next_cell(4,onecoin)).
pos(next_cell(8,onecoin)).
neg(next_cell(1,onecoin)).
pos(next_cell(1,zerocoins)).
neg(next_cell(6,zerocoins)).
pos(next_cell(2,twocoins)).
pos(next_cell(3,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(6,twocoins)).

#T15
neg(next_cell(7,zerocoins)).
pos(next_cell(5,onecoin)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(1,twocoins)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
neg(next_cell(6,onecoin)).
pos(next_cell(4,onecoin)).
pos(next_cell(8,onecoin)).
pos(next_cell(1,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,twocoins)).
pos(next_cell(6,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(6,twocoins)).

#T16
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T17
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,zerocoins)).
pos(next_cell(5,twocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
pos(next_cell(2,onecoin)).
pos(next_cell(8,onecoin)).
pos(next_cell(4,twocoins)).
neg(next_cell(1,onecoin)).
pos(next_cell(1,zerocoins)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(6,twocoins)).

#T18
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T19
neg(next_cell(7,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
pos(next_cell(8,zerocoins)).
neg(next_cell(8,onecoin)).
pos(next_cell(4,twocoins)).
neg(next_cell(1,onecoin)).
pos(next_cell(1,zerocoins)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
pos(next_cell(2,twocoins)).
pos(next_cell(3,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(6,twocoins)).

#T2
neg(next_cell(3,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(8,onecoin)).
pos(next_cell(6,twocoins)).
neg(next_cell(6,onecoin)).
pos(next_cell(4,twocoins)).
pos(next_cell(1,onecoin)).
pos(next_cell(7,zerocoins)).
pos(next_cell(2,zerocoins)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(5,zerocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,onecoin)).
pos(next_cell(8,twocoins)).
neg(next_cell(7,onecoin)).

#T20
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
pos(next_cell(4,zerocoins)).
pos(next_cell(1,twocoins)).
pos(next_cell(8,twocoins)).
neg(next_cell(6,twocoins)).

#T21
neg(next_cell(7,zerocoins)).
pos(next_cell(5,onecoin)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
pos(next_cell(8,zerocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(4,onecoin)).
pos(next_cell(2,twocoins)).
neg(next_cell(1,zerocoins)).
pos(next_cell(3,twocoins)).
neg(next_cell(5,twocoins)).
pos(next_cell(6,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
pos(next_cell(4,zerocoins)).
pos(next_cell(1,twocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(6,twocoins)).

#T22
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
pos(next_cell(7,twocoins)).
neg(next_cell(8,onecoin)).
pos(next_cell(6,twocoins)).
neg(next_cell(6,onecoin)).
pos(next_cell(1,onecoin)).
pos(next_cell(2,zerocoins)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,onecoin)).
pos(next_cell(4,zerocoins)).
neg(next_cell(2,onecoin)).
pos(next_cell(8,twocoins)).
neg(next_cell(7,onecoin)).

#T23
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,zerocoins)).
pos(next_cell(5,twocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(8,zerocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
pos(next_cell(4,zerocoins)).
pos(next_cell(1,twocoins)).
neg(next_cell(6,twocoins)).

#T24
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(7,twocoins)).
neg(next_cell(8,onecoin)).
pos(next_cell(4,onecoin)).
pos(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,zerocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(8,twocoins)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T25
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T26
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
pos(next_cell(7,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
pos(next_cell(1,zerocoins)).
neg(next_cell(4,onecoin)).
pos(next_cell(2,twocoins)).
pos(next_cell(3,twocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(6,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(4,zerocoins)).
neg(next_cell(2,onecoin)).
pos(next_cell(8,twocoins)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T27
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,onecoin)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(7,twocoins)).
pos(next_cell(6,twocoins)).
neg(next_cell(6,onecoin)).
pos(next_cell(8,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(4,zerocoins)).
pos(next_cell(1,twocoins)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T28
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
pos(next_cell(5,onecoin)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(4,twocoins)).
pos(next_cell(7,twocoins)).
neg(next_cell(6,onecoin)).
pos(next_cell(8,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(4,onecoin)).
pos(next_cell(2,twocoins)).
neg(next_cell(1,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,zerocoins)).
pos(next_cell(6,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(4,zerocoins)).
pos(next_cell(1,twocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T29
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T3
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T30
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
pos(next_cell(5,onecoin)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
pos(next_cell(7,twocoins)).
pos(next_cell(6,twocoins)).
neg(next_cell(6,onecoin)).
pos(next_cell(8,onecoin)).
pos(next_cell(1,onecoin)).
pos(next_cell(2,zerocoins)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,onecoin)).
pos(next_cell(4,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(7,onecoin)).

#T31
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(5,onecoin)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(6,twocoins)).
neg(next_cell(6,onecoin)).
pos(next_cell(4,onecoin)).
pos(next_cell(8,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,zerocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(1,twocoins)).
neg(next_cell(3,onecoin)).
pos(next_cell(7,onecoin)).

#T32
neg(next_cell(6,twocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,zerocoins)).
pos(next_cell(5,twocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(8,onecoin)).
neg(next_cell(1,onecoin)).
pos(next_cell(7,zerocoins)).
pos(next_cell(2,zerocoins)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
pos(next_cell(3,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(4,zerocoins)).
pos(next_cell(1,twocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T33
neg(next_cell(6,twocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
pos(next_cell(4,onecoin)).
pos(next_cell(1,onecoin)).
pos(next_cell(7,zerocoins)).
neg(next_cell(6,zerocoins)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,twocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(8,twocoins)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T34
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T35
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
pos(next_cell(4,onecoin)).
neg(next_cell(1,onecoin)).
pos(next_cell(2,twocoins)).
neg(next_cell(1,zerocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,zerocoins)).
pos(next_cell(5,zerocoins)).
pos(next_cell(6,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
pos(next_cell(1,twocoins)).
neg(next_cell(2,onecoin)).
pos(next_cell(8,twocoins)).
neg(next_cell(3,onecoin)).
neg(next_cell(6,twocoins)).

#T36
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
pos(next_cell(2,onecoin)).
neg(next_cell(8,onecoin)).
pos(next_cell(6,twocoins)).
neg(next_cell(6,onecoin)).
pos(next_cell(4,twocoins)).
neg(next_cell(1,onecoin)).
pos(next_cell(1,zerocoins)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,zerocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(8,twocoins)).
neg(next_cell(3,onecoin)).
pos(next_cell(7,onecoin)).

#T37
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T38
neg(next_cell(7,zerocoins)).
pos(next_cell(5,onecoin)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(1,twocoins)).
pos(next_cell(2,onecoin)).
pos(next_cell(8,zerocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
pos(next_cell(4,twocoins)).
pos(next_cell(1,onecoin)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
pos(next_cell(3,twocoins)).
pos(next_cell(6,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(6,twocoins)).

#T39
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(5,onecoin)).
pos(next_cell(8,zerocoins)).
neg(next_cell(8,onecoin)).
pos(next_cell(4,twocoins)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
pos(next_cell(2,twocoins)).
neg(next_cell(1,zerocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
pos(next_cell(5,zerocoins)).
pos(next_cell(3,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
pos(next_cell(1,twocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(6,twocoins)).

#T4
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
pos(next_cell(6,twocoins)).
neg(next_cell(6,onecoin)).
pos(next_cell(4,onecoin)).
pos(next_cell(1,onecoin)).
pos(next_cell(2,zerocoins)).
neg(next_cell(6,zerocoins)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(5,zerocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,onecoin)).
pos(next_cell(8,twocoins)).
pos(next_cell(7,onecoin)).

#T40
neg(next_cell(3,twocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,zerocoins)).
pos(next_cell(5,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(6,twocoins)).
neg(next_cell(6,onecoin)).
pos(next_cell(4,onecoin)).
pos(next_cell(8,onecoin)).
pos(next_cell(1,onecoin)).
pos(next_cell(7,zerocoins)).
neg(next_cell(6,zerocoins)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T41
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
pos(next_cell(2,onecoin)).
neg(next_cell(8,onecoin)).
pos(next_cell(4,twocoins)).
neg(next_cell(1,onecoin)).
pos(next_cell(1,zerocoins)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(5,zerocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
pos(next_cell(8,twocoins)).
neg(next_cell(6,twocoins)).

#T42
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
pos(next_cell(7,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
pos(next_cell(1,onecoin)).
neg(next_cell(4,onecoin)).
pos(next_cell(2,twocoins)).
neg(next_cell(1,zerocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(6,zerocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,zerocoins)).
pos(next_cell(4,zerocoins)).
neg(next_cell(2,onecoin)).
pos(next_cell(8,twocoins)).
neg(next_cell(7,onecoin)).

#T43
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,zerocoins)).
pos(next_cell(5,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(5,onecoin)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(8,zerocoins)).
neg(next_cell(8,onecoin)).
pos(next_cell(6,twocoins)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
pos(next_cell(3,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(4,zerocoins)).
pos(next_cell(1,twocoins)).
neg(next_cell(3,onecoin)).
pos(next_cell(7,onecoin)).

#T44
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
pos(next_cell(8,zerocoins)).
neg(next_cell(8,onecoin)).
pos(next_cell(6,twocoins)).
neg(next_cell(6,onecoin)).
pos(next_cell(4,twocoins)).
pos(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
pos(next_cell(2,twocoins)).
neg(next_cell(1,zerocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
pos(next_cell(5,zerocoins)).
pos(next_cell(3,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
pos(next_cell(7,onecoin)).

#T45
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(7,twocoins)).
pos(next_cell(6,twocoins)).
neg(next_cell(6,onecoin)).
pos(next_cell(8,onecoin)).
neg(next_cell(1,onecoin)).
pos(next_cell(2,zerocoins)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,onecoin)).
pos(next_cell(4,zerocoins)).
pos(next_cell(1,twocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(7,onecoin)).

#T46
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
pos(next_cell(5,onecoin)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,zerocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(3,zerocoins)).
neg(next_cell(1,twocoins)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(7,twocoins)).
pos(next_cell(8,onecoin)).
pos(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,zerocoins)).
pos(next_cell(4,zerocoins)).
neg(next_cell(7,onecoin)).

#T47
neg(next_cell(6,twocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(8,onecoin)).
pos(next_cell(4,twocoins)).
pos(next_cell(1,onecoin)).
pos(next_cell(7,zerocoins)).
pos(next_cell(2,zerocoins)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,twocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(2,onecoin)).
pos(next_cell(8,twocoins)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T48
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T49
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
pos(next_cell(5,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(7,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
pos(next_cell(1,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(2,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(6,zerocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,zerocoins)).
pos(next_cell(4,zerocoins)).
pos(next_cell(8,twocoins)).
neg(next_cell(7,onecoin)).

#T5
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T50
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T51
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,onecoin)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(7,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
pos(next_cell(4,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,zerocoins)).
pos(next_cell(5,zerocoins)).
pos(next_cell(6,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(1,twocoins)).
pos(next_cell(8,twocoins)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T52
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T53
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
pos(next_cell(5,onecoin)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
pos(next_cell(7,twocoins)).
neg(next_cell(6,onecoin)).
pos(next_cell(8,onecoin)).
pos(next_cell(1,onecoin)).
neg(next_cell(4,onecoin)).
pos(next_cell(2,twocoins)).
neg(next_cell(1,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(6,zerocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,zerocoins)).
pos(next_cell(4,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(7,onecoin)).

#T54
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(5,onecoin)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
pos(next_cell(2,twocoins)).
neg(next_cell(1,zerocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
pos(next_cell(4,zerocoins)).
pos(next_cell(1,twocoins)).
neg(next_cell(2,onecoin)).
pos(next_cell(8,twocoins)).
neg(next_cell(3,onecoin)).
neg(next_cell(6,twocoins)).

#T55
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
pos(next_cell(5,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(7,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
pos(next_cell(1,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(2,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(6,zerocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,zerocoins)).
pos(next_cell(4,zerocoins)).
pos(next_cell(8,twocoins)).
neg(next_cell(7,onecoin)).

#T56
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,zerocoins)).
pos(next_cell(5,twocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(8,zerocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
pos(next_cell(4,zerocoins)).
pos(next_cell(1,twocoins)).
neg(next_cell(6,twocoins)).

#T57
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T58
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T59
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T6
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T60
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T61
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
pos(next_cell(5,onecoin)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(1,twocoins)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(6,twocoins)).
neg(next_cell(6,onecoin)).
pos(next_cell(4,onecoin)).
pos(next_cell(8,onecoin)).
pos(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(3,onecoin)).
pos(next_cell(7,onecoin)).

#T62
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(7,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(6,zerocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,zerocoins)).
pos(next_cell(4,zerocoins)).
pos(next_cell(1,twocoins)).
pos(next_cell(8,twocoins)).
neg(next_cell(7,onecoin)).

#T63
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(8,zerocoins)).
pos(next_cell(7,twocoins)).
neg(next_cell(8,onecoin)).
pos(next_cell(6,twocoins)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(5,twocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,zerocoins)).
pos(next_cell(4,zerocoins)).
pos(next_cell(1,twocoins)).
neg(next_cell(7,onecoin)).

#T64
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
pos(next_cell(5,onecoin)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(3,zerocoins)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(8,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
pos(next_cell(4,zerocoins)).
pos(next_cell(1,twocoins)).
neg(next_cell(6,twocoins)).

#T65
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
pos(next_cell(5,onecoin)).
neg(next_cell(5,zerocoins)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(7,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,zerocoins)).
pos(next_cell(6,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(4,zerocoins)).
pos(next_cell(1,twocoins)).
pos(next_cell(8,twocoins)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T66
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,zerocoins)).
pos(next_cell(5,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(6,onecoin)).
pos(next_cell(8,onecoin)).
pos(next_cell(4,twocoins)).
pos(next_cell(1,onecoin)).
pos(next_cell(2,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(6,zerocoins)).
pos(next_cell(3,onecoin)).
pos(next_cell(7,onecoin)).
neg(next_cell(2,onecoin)).
neg(next_cell(6,twocoins)).

#T67
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T68
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
pos(next_cell(4,onecoin)).
pos(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(5,zerocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
pos(next_cell(8,twocoins)).
neg(next_cell(6,twocoins)).

#T69
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T7
neg(next_cell(7,zerocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
pos(next_cell(1,onecoin)).
neg(next_cell(4,onecoin)).
pos(next_cell(2,twocoins)).
neg(next_cell(1,zerocoins)).
pos(next_cell(3,twocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(6,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
pos(next_cell(4,zerocoins)).
neg(next_cell(2,onecoin)).
pos(next_cell(8,twocoins)).
neg(next_cell(3,onecoin)).
neg(next_cell(6,twocoins)).

#T70
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T71
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
pos(next_cell(5,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
pos(next_cell(1,onecoin)).
pos(next_cell(2,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
pos(next_cell(3,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(6,zerocoins)).
pos(next_cell(7,onecoin)).
pos(next_cell(4,zerocoins)).
neg(next_cell(2,onecoin)).
pos(next_cell(8,twocoins)).
neg(next_cell(3,onecoin)).
neg(next_cell(6,twocoins)).

#T72
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
pos(next_cell(5,onecoin)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
pos(next_cell(7,twocoins)).
neg(next_cell(6,onecoin)).
pos(next_cell(8,onecoin)).
neg(next_cell(1,onecoin)).
pos(next_cell(1,zerocoins)).
neg(next_cell(4,onecoin)).
pos(next_cell(2,twocoins)).
pos(next_cell(3,twocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(6,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(4,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T73
neg(next_cell(6,twocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
pos(next_cell(4,onecoin)).
pos(next_cell(8,onecoin)).
pos(next_cell(1,onecoin)).
pos(next_cell(7,zerocoins)).
neg(next_cell(6,zerocoins)).
pos(next_cell(2,twocoins)).
neg(next_cell(1,zerocoins)).
pos(next_cell(3,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T74
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T75
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,zerocoins)).
pos(next_cell(5,twocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
pos(next_cell(2,onecoin)).
pos(next_cell(8,onecoin)).
pos(next_cell(4,twocoins)).
pos(next_cell(1,onecoin)).
pos(next_cell(7,zerocoins)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T76
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
pos(next_cell(2,onecoin)).
neg(next_cell(8,onecoin)).
pos(next_cell(4,twocoins)).
neg(next_cell(1,onecoin)).
pos(next_cell(1,zerocoins)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(5,zerocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
pos(next_cell(8,twocoins)).
neg(next_cell(6,twocoins)).

#T77
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
pos(next_cell(5,onecoin)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(3,zerocoins)).
neg(next_cell(1,twocoins)).
pos(next_cell(2,onecoin)).
pos(next_cell(8,onecoin)).
pos(next_cell(4,twocoins)).
neg(next_cell(1,onecoin)).
pos(next_cell(1,zerocoins)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
neg(next_cell(6,twocoins)).

#T78
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(7,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(4,onecoin)).
pos(next_cell(2,twocoins)).
neg(next_cell(1,zerocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,zerocoins)).
pos(next_cell(6,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(4,zerocoins)).
pos(next_cell(1,twocoins)).
neg(next_cell(2,onecoin)).
pos(next_cell(8,twocoins)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T79
neg(next_cell(7,zerocoins)).
pos(next_cell(5,onecoin)).
neg(next_cell(5,zerocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(1,twocoins)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
pos(next_cell(1,onecoin)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
pos(next_cell(3,twocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(6,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
pos(next_cell(4,zerocoins)).
pos(next_cell(8,twocoins)).
neg(next_cell(3,onecoin)).
neg(next_cell(6,twocoins)).

#T8
neg(next_cell(6,twocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
pos(next_cell(2,onecoin)).
pos(next_cell(8,onecoin)).
pos(next_cell(4,twocoins)).
pos(next_cell(1,onecoin)).
pos(next_cell(7,zerocoins)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,twocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T80
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T81
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(7,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(1,onecoin)).
pos(next_cell(2,zerocoins)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,onecoin)).
pos(next_cell(4,zerocoins)).
pos(next_cell(1,twocoins)).
neg(next_cell(2,onecoin)).
pos(next_cell(8,twocoins)).
neg(next_cell(7,onecoin)).

#T82
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T83
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,zerocoins)).
pos(next_cell(5,twocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(8,zerocoins)).
neg(next_cell(8,onecoin)).
pos(next_cell(4,onecoin)).
pos(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
neg(next_cell(6,twocoins)).

#T84
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(8,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(7,twocoins)).
pos(next_cell(8,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,zerocoins)).
pos(next_cell(4,zerocoins)).
pos(next_cell(1,twocoins)).
neg(next_cell(7,onecoin)).

#T85
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T86
neg(next_cell(6,twocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(8,onecoin)).
neg(next_cell(1,onecoin)).
pos(next_cell(7,zerocoins)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
pos(next_cell(2,twocoins)).
neg(next_cell(1,zerocoins)).
pos(next_cell(3,twocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(4,zerocoins)).
pos(next_cell(1,twocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T87
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
pos(next_cell(4,onecoin)).
pos(next_cell(1,onecoin)).
pos(next_cell(2,twocoins)).
neg(next_cell(1,zerocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(5,zerocoins)).
pos(next_cell(6,zerocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
neg(next_cell(2,onecoin)).
pos(next_cell(8,twocoins)).
neg(next_cell(6,twocoins)).

#T88
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T89
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
pos(next_cell(8,zerocoins)).
neg(next_cell(8,onecoin)).
pos(next_cell(4,twocoins)).
pos(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
pos(next_cell(2,twocoins)).
neg(next_cell(1,zerocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
pos(next_cell(5,zerocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
neg(next_cell(2,onecoin)).
neg(next_cell(6,twocoins)).

#T9
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,zerocoins)).
pos(next_cell(5,twocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(7,twocoins)).
pos(next_cell(6,twocoins)).
neg(next_cell(6,onecoin)).
pos(next_cell(8,onecoin)).
neg(next_cell(1,onecoin)).
pos(next_cell(1,zerocoins)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(2,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(4,zerocoins)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T90
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
pos(next_cell(5,onecoin)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,zerocoins)).
pos(next_cell(6,onecoin)).
pos(next_cell(2,onecoin)).
neg(next_cell(4,twocoins)).
pos(next_cell(7,twocoins)).
pos(next_cell(8,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(3,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(4,zerocoins)).
pos(next_cell(1,twocoins)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T91
neg(next_cell(7,zerocoins)).
pos(next_cell(5,onecoin)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(6,onecoin)).
pos(next_cell(8,onecoin)).
pos(next_cell(1,onecoin)).
neg(next_cell(4,onecoin)).
pos(next_cell(2,twocoins)).
neg(next_cell(1,zerocoins)).
pos(next_cell(3,twocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(6,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
pos(next_cell(4,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(6,twocoins)).

#T92
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T93
neg(next_cell(7,zerocoins)).
neg(next_cell(7,twocoins)).
pos(next_cell(6,onecoin)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(1,onecoin)).
pos(next_cell(1,zerocoins)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
pos(next_cell(2,twocoins)).
pos(next_cell(3,twocoins)).
pos(next_cell(5,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
pos(next_cell(4,zerocoins)).
neg(next_cell(2,onecoin)).
pos(next_cell(8,twocoins)).
neg(next_cell(3,onecoin)).
neg(next_cell(6,twocoins)).

#T94
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T95
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T96
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
pos(next_cell(5,onecoin)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(6,onecoin)).
pos(next_cell(8,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(4,onecoin)).
pos(next_cell(2,twocoins)).
neg(next_cell(1,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
pos(next_cell(6,zerocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
pos(next_cell(4,zerocoins)).
pos(next_cell(1,twocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(6,twocoins)).

#T97
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T98
neg(next_cell(3,twocoins)).
neg(next_cell(6,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(5,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
neg(next_cell(4,twocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
neg(next_cell(1,onecoin)).
neg(next_cell(6,zerocoins)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
neg(next_cell(5,twocoins)).
neg(next_cell(8,zerocoins)).
neg(next_cell(2,zerocoins)).
neg(next_cell(2,onecoin)).
neg(next_cell(3,onecoin)).
neg(next_cell(7,onecoin)).

#T99
neg(next_cell(3,twocoins)).
neg(next_cell(7,zerocoins)).
neg(next_cell(8,twocoins)).
neg(next_cell(5,zerocoins)).
pos(next_cell(5,twocoins)).
neg(next_cell(7,twocoins)).
neg(next_cell(3,zerocoins)).
neg(next_cell(5,onecoin)).
neg(next_cell(1,twocoins)).
pos(next_cell(2,onecoin)).
pos(next_cell(8,zerocoins)).
neg(next_cell(8,onecoin)).
neg(next_cell(6,onecoin)).
pos(next_cell(4,twocoins)).
pos(next_cell(1,onecoin)).
neg(next_cell(4,onecoin)).
neg(next_cell(1,zerocoins)).
neg(next_cell(2,twocoins)).
neg(next_cell(4,zerocoins)).
pos(next_cell(6,zerocoins)).
pos(next_cell(3,onecoin)).
neg(next_cell(2,zerocoins)).
pos(next_cell(7,onecoin)).
neg(next_cell(6,twocoins)).

