does(1,player,pressButton).
does(2,player,noop).
does(3,player,pressButton).
does(4,player,pressButton).
does(5,player,pressButton).
does(6,player,noop).
does(7,player,noop).
does(8,player,pressButton).
does(9,player,pressButton).
my_succ(0,1).
my_succ(1,2).
my_succ(2,3).
my_succ(3,4).
my_succ(4,5).
my_true_value(1,0).
my_true_value(2,3).
my_true_value(3,3).
my_true_value(4,4).
my_true_value(5,5).
my_true_value(6,2).
my_true_value(8,2).


c_pressButton(c_pressButton).
c_noop(c_noop).
c1(c1).
c2(c2).
c3(c3).
c4(c4).
c5(c5).
c6(c6).
c7(c7).
c8(c8).
c9(c9).
c10(c10).
