neg(next_value(1,0)).
neg(next_value(1,1)).
neg(next_value(1,2)).
neg(next_value(1,4)).
neg(next_value(1,5)).
neg(next_value(2,0)).
neg(next_value(2,1)).
neg(next_value(2,2)).
neg(next_value(2,3)).
neg(next_value(2,4)).
neg(next_value(2,5)).
neg(next_value(3,0)).
neg(next_value(3,1)).
neg(next_value(3,2)).
neg(next_value(3,3)).
neg(next_value(3,4)).
pos(next_value(1,3)).
pos(next_value(3,5)).
