pos(less_toxic(cc1,dd1)).
pos(less_toxic(m1,w1)).
pos(less_toxic(s1,dd1)).
pos(less_toxic(o1,cc1)).
pos(less_toxic(ee1,c1)).
pos(less_toxic(k1,a1)).
pos(less_toxic(g1,i1)).
pos(less_toxic(g1,t1)).
pos(less_toxic(y1,u1)).
pos(less_toxic(ii1,v1)).
pos(less_toxic(z1,p1)).
pos(less_toxic(k1,c1)).
pos(less_toxic(ll1,l1)).
pos(less_toxic(ll1,dd1)).
pos(less_toxic(ll1,h1)).
pos(less_toxic(ll1,jj1)).
pos(less_toxic(y1,f1)).
pos(less_toxic(q1,t1)).
pos(less_toxic(hh1,z1)).
pos(less_toxic(ee1,z1)).
pos(less_toxic(y1,dd1)).
pos(less_toxic(o1,e1)).
pos(less_toxic(r1,a1)).
pos(less_toxic(m1,dd1)).
pos(less_toxic(ff1,p1)).
pos(less_toxic(r1,aa1)).
pos(less_toxic(s1,v1)).
pos(less_toxic(h1,d1)).
pos(less_toxic(n1,d1)).
pos(less_toxic(m1,v1)).
pos(less_toxic(s1,t1)).
pos(less_toxic(s1,i1)).
pos(less_toxic(ee1,a1)).
pos(less_toxic(k1,p1)).
pos(less_toxic(hh1,h1)).
pos(less_toxic(u1,f1)).
pos(less_toxic(y1,i1)).
pos(less_toxic(s1,b1)).
pos(less_toxic(o1,c1)).
pos(less_toxic(i1,c1)).
pos(less_toxic(j1,cc1)).
pos(less_toxic(kk1,cc1)).
pos(less_toxic(x1,cc1)).
pos(less_toxic(kk1,h1)).
pos(less_toxic(r1,f1)).
pos(less_toxic(bb1,a1)).
pos(less_toxic(k1,l1)).
pos(less_toxic(r1,e1)).
pos(less_toxic(q1,e1)).
pos(less_toxic(bb1,h1)).
pos(less_toxic(y1,e1)).
pos(less_toxic(r1,t1)).
pos(less_toxic(hh1,d1)).
pos(less_toxic(s1,e1)).
pos(less_toxic(w1,a1)).
pos(less_toxic(ff1,dd1)).
pos(less_toxic(w1,u1)).
pos(less_toxic(l1,f1)).
pos(less_toxic(jj1,d1)).
pos(less_toxic(n1,b1)).
pos(less_toxic(j1,p1)).
pos(less_toxic(x1,a1)).
pos(less_toxic(hh1,f1)).
pos(less_toxic(cc1,c1)).
pos(less_toxic(b1,p1)).
pos(less_toxic(y1,c1)).
pos(less_toxic(hh1,e1)).
pos(less_toxic(b1,i1)).
pos(less_toxic(ee1,aa1)).
pos(less_toxic(x1,u1)).
pos(less_toxic(aa1,d1)).
pos(less_toxic(ff1,u1)).
pos(less_toxic(hh1,u1)).
pos(less_toxic(aa1,p1)).
pos(less_toxic(ee1,i1)).
pos(less_toxic(cc1,h1)).
pos(less_toxic(b1,d1)).
pos(less_toxic(ll1,e1)).
pos(less_toxic(n1,h1)).
pos(less_toxic(ee1,l1)).
pos(less_toxic(x1,b1)).
pos(less_toxic(f1,d1)).
pos(less_toxic(bb1,w1)).
pos(less_toxic(dd1,p1)).
pos(less_toxic(w1,t1)).
pos(less_toxic(cc1,z1)).
pos(less_toxic(ll1,p1)).
pos(less_toxic(n1,f1)).
pos(less_toxic(o1,u1)).
pos(less_toxic(y1,v1)).
pos(less_toxic(ii1,aa1)).
pos(less_toxic(kk1,p1)).
pos(less_toxic(g1,h1)).
pos(less_toxic(o1,b1)).
pos(less_toxic(ff1,w1)).
pos(less_toxic(ll1,f1)).
pos(less_toxic(z1,c1)).
pos(less_toxic(n1,cc1)).
pos(less_toxic(w1,p1)).
pos(less_toxic(jj1,p1)).
pos(less_toxic(s1,aa1)).
pos(less_toxic(j1,h1)).
pos(less_toxic(hh1,cc1)).
pos(less_toxic(k1,b1)).
pos(less_toxic(bb1,u1)).
pos(less_toxic(m1,l1)).
pos(less_toxic(o1,dd1)).
pos(less_toxic(kk1,c1)).
pos(less_toxic(n1,l1)).
pos(less_toxic(j1,f1)).
pos(less_toxic(bb1,jj1)).
pos(less_toxic(ii1,w1)).
pos(less_toxic(v1,c1)).
pos(less_toxic(n1,u1)).
pos(less_toxic(kk1,i1)).
pos(less_toxic(ii1,t1)).
pos(less_toxic(r1,jj1)).
pos(less_toxic(ii1,u1)).
pos(less_toxic(g1,z1)).
pos(less_toxic(q1,h1)).
pos(less_toxic(p1,d1)).
pos(less_toxic(r1,d1)).
pos(less_toxic(f1,c1)).
pos(less_toxic(m1,c1)).
pos(less_toxic(n1,z1)).
pos(less_toxic(w1,jj1)).
pos(less_toxic(x1,w1)).
pos(less_toxic(s1,z1)).
pos(less_toxic(ff1,l1)).
pos(less_toxic(cc1,aa1)).
pos(less_toxic(bb1,cc1)).
pos(less_toxic(b1,dd1)).
pos(less_toxic(g1,dd1)).
pos(less_toxic(r1,w1)).
pos(less_toxic(jj1,c1)).
pos(less_toxic(k1,z1)).
pos(less_toxic(s1,cc1)).
pos(less_toxic(o1,i1)).
pos(less_toxic(y1,l1)).
pos(less_toxic(q1,i1)).
pos(less_toxic(s1,l1)).
pos(less_toxic(q1,w1)).
pos(less_toxic(a1,p1)).
pos(less_toxic(w1,z1)).
pos(less_toxic(b1,u1)).
pos(less_toxic(u1,c1)).
pos(less_toxic(hh1,c1)).
pos(less_toxic(k1,u1)).
pos(less_toxic(ii1,a1)).
pos(less_toxic(ff1,t1)).
pos(less_toxic(x1,jj1)).
pos(less_toxic(b1,aa1)).
pos(less_toxic(ff1,d1)).
pos(less_toxic(bb1,c1)).
pos(less_toxic(t1,f1)).
pos(less_toxic(hh1,dd1)).
pos(less_toxic(r1,u1)).
pos(less_toxic(aa1,c1)).
pos(less_toxic(w1,e1)).
pos(less_toxic(w1,c1)).
pos(less_toxic(e1,d1)).
pos(less_toxic(i1,f1)).
pos(less_toxic(g1,b1)).
pos(less_toxic(m1,e1)).
pos(less_toxic(g1,w1)).
pos(less_toxic(y1,jj1)).
pos(less_toxic(dd1,c1)).
pos(less_toxic(n1,dd1)).
pos(less_toxic(ii1,f1)).
pos(less_toxic(hh1,jj1)).
pos(less_toxic(ll1,d1)).
pos(less_toxic(ee1,b1)).
pos(less_toxic(z1,f1)).
pos(less_toxic(x1,i1)).
pos(less_toxic(n1,c1)).
pos(less_toxic(hh1,p1)).
pos(less_toxic(z1,d1)).
pos(less_toxic(j1,dd1)).
pos(less_toxic(x1,f1)).
pos(less_toxic(b1,t1)).
pos(less_toxic(x1,v1)).
pos(less_toxic(j1,t1)).
pos(less_toxic(y1,z1)).
pos(less_toxic(ee1,t1)).
pos(less_toxic(cc1,i1)).
pos(less_toxic(b1,e1)).
pos(less_toxic(bb1,v1)).
pos(less_toxic(v1,p1)).
pos(less_toxic(q1,cc1)).
pos(less_toxic(g1,l1)).
pos(less_toxic(b1,v1)).
pos(less_toxic(j1,v1)).
pos(less_toxic(kk1,aa1)).
pos(less_toxic(ff1,e1)).
pos(less_toxic(y1,cc1)).
pos(less_toxic(ii1,dd1)).
pos(less_toxic(ll1,v1)).
pos(less_toxic(v1,d1)).
pos(less_toxic(ll1,u1)).
pos(less_toxic(a1,d1)).
pos(less_toxic(ff1,aa1)).
pos(less_toxic(t1,p1)).
pos(less_toxic(q1,u1)).
pos(less_toxic(k1,aa1)).
pos(less_toxic(q1,p1)).
pos(less_toxic(s1,h1)).
pos(less_toxic(ee1,jj1)).
pos(less_toxic(q1,z1)).
pos(less_toxic(hh1,t1)).
pos(less_toxic(w1,v1)).
pos(less_toxic(o1,f1)).
pos(less_toxic(w1,h1)).
pos(less_toxic(q1,l1)).
pos(less_toxic(g1,v1)).
pos(less_toxic(o1,l1)).
pos(less_toxic(i1,p1)).
pos(less_toxic(n1,e1)).
pos(less_toxic(q1,f1)).
pos(less_toxic(o1,h1)).
pos(less_toxic(j1,u1)).
pos(less_toxic(k1,h1)).
pos(less_toxic(ii1,l1)).
pos(less_toxic(ll1,a1)).
pos(less_toxic(w1,i1)).
pos(less_toxic(ii1,d1)).
pos(less_toxic(ii1,cc1)).
pos(less_toxic(ii1,c1)).
pos(less_toxic(hh1,i1)).
pos(less_toxic(o1,jj1)).
pos(less_toxic(a1,f1)).
pos(less_toxic(j1,i1)).
pos(less_toxic(m1,t1)).
pos(less_toxic(m1,a1)).
pos(less_toxic(b1,l1)).
pos(less_toxic(dd1,d1)).
pos(less_toxic(ff1,v1)).
pos(less_toxic(y1,d1)).
pos(less_toxic(ii1,p1)).
pos(less_toxic(q1,b1)).
pos(less_toxic(j1,l1)).
pos(less_toxic(w1,f1)).
pos(less_toxic(x1,p1)).
pos(less_toxic(g1,a1)).
pos(less_toxic(w1,aa1)).
pos(less_toxic(o1,p1)).
pos(less_toxic(w1,l1)).
pos(less_toxic(ii1,h1)).
pos(less_toxic(j1,b1)).
pos(less_toxic(p1,c1)).
pos(less_toxic(h1,p1)).
pos(less_toxic(r1,l1)).
pos(less_toxic(ff1,cc1)).
pos(less_toxic(k1,dd1)).
pos(less_toxic(l1,d1)).
pos(less_toxic(kk1,l1)).
pos(less_toxic(j1,d1)).
pos(less_toxic(w1,d1)).
pos(less_toxic(bb1,p1)).
pos(less_toxic(x1,aa1)).
pos(less_toxic(g1,c1)).
pos(less_toxic(t1,d1)).
pos(less_toxic(j1,c1)).
pos(less_toxic(v1,f1)).
pos(less_toxic(ee1,h1)).
pos(less_toxic(cc1,u1)).
pos(less_toxic(ll1,z1)).
pos(less_toxic(bb1,l1)).
pos(less_toxic(jj1,f1)).
pos(less_toxic(y1,aa1)).
pos(less_toxic(ff1,i1)).
pos(less_toxic(q1,aa1)).
pos(less_toxic(j1,z1)).
pos(less_toxic(q1,dd1)).
pos(less_toxic(kk1,jj1)).
pos(less_toxic(cc1,d1)).
pos(less_toxic(m1,jj1)).
pos(less_toxic(b1,h1)).
pos(less_toxic(q1,a1)).
pos(less_toxic(ff1,h1)).
pos(less_toxic(r1,c1)).
pos(less_toxic(hh1,b1)).
pos(less_toxic(k1,f1)).
pos(less_toxic(m1,cc1)).
pos(less_toxic(j1,a1)).
pos(less_toxic(cc1,p1)).
pos(less_toxic(ll1,t1)).
pos(less_toxic(x1,z1)).
pos(less_toxic(bb1,d1)).
pos(less_toxic(m1,p1)).
pos(less_toxic(ff1,a1)).
pos(less_toxic(bb1,b1)).
pos(less_toxic(cc1,f1)).
pos(less_toxic(kk1,b1)).
pos(less_toxic(m1,b1)).
pos(less_toxic(o1,z1)).
pos(less_toxic(r1,cc1)).
pos(less_toxic(g1,aa1)).
pos(less_toxic(o1,a1)).
pos(less_toxic(hh1,a1)).
pos(less_toxic(y1,b1)).
pos(less_toxic(ll1,w1)).
pos(less_toxic(k1,i1)).
pos(less_toxic(t1,c1)).
pos(less_toxic(e1,f1)).
pos(less_toxic(l1,p1)).
pos(less_toxic(n1,w1)).
pos(less_toxic(g1,cc1)).
pos(less_toxic(hh1,aa1)).
pos(less_toxic(ll1,i1)).
pos(less_toxic(o1,d1)).
pos(less_toxic(n1,i1)).
pos(less_toxic(b1,z1)).
pos(less_toxic(s1,d1)).
pos(less_toxic(g1,d1)).
pos(less_toxic(g1,e1)).
pos(less_toxic(g1,jj1)).
pos(less_toxic(n1,aa1)).
pos(less_toxic(a1,c1)).
pos(less_toxic(q1,v1)).
pos(less_toxic(bb1,f1)).
pos(less_toxic(ii1,i1)).
pos(less_toxic(ee1,p1)).
pos(less_toxic(ii1,b1)).
pos(less_toxic(k1,e1)).
pos(less_toxic(y1,w1)).
pos(less_toxic(e1,p1)).
pos(less_toxic(kk1,e1)).
pos(less_toxic(m1,d1)).
pos(less_toxic(x1,c1)).
pos(less_toxic(ff1,z1)).
pos(less_toxic(n1,t1)).
pos(less_toxic(i1,d1)).
pos(less_toxic(ee1,e1)).
pos(less_toxic(y1,h1)).
pos(less_toxic(j1,e1)).
pos(less_toxic(ee1,d1)).
pos(less_toxic(ff1,c1)).
pos(less_toxic(x1,d1)).
pos(less_toxic(j1,aa1)).
pos(less_toxic(kk1,u1)).
pos(less_toxic(p1,f1)).
pos(less_toxic(ii1,e1)).
pos(less_toxic(u1,p1)).
pos(less_toxic(y1,p1)).
pos(less_toxic(cc1,e1)).
pos(less_toxic(o1,w1)).
pos(less_toxic(o1,v1)).
pos(less_toxic(aa1,f1)).
pos(less_toxic(cc1,v1)).
pos(less_toxic(g1,f1)).
pos(less_toxic(m1,u1)).
pos(less_toxic(q1,d1)).
pos(less_toxic(ll1,b1)).
pos(less_toxic(o1,t1)).
neg(less_toxic(c1,f1)).
neg(less_toxic(w1,hh1)).
neg(less_toxic(a1,n1)).
neg(less_toxic(a1,j1)).
neg(less_toxic(t1,o1)).
neg(less_toxic(i1,m1)).
neg(less_toxic(cc1,q1)).
neg(less_toxic(d1,dd1)).
neg(less_toxic(v1,kk1)).
neg(less_toxic(cc1,ll1)).
neg(less_toxic(a1,s1)).
neg(less_toxic(h1,q1)).
neg(less_toxic(cc1,n1)).
neg(less_toxic(u1,s1)).
neg(less_toxic(p1,w1)).
neg(less_toxic(v1,x1)).
neg(less_toxic(l1,ff1)).
neg(less_toxic(i1,g1)).
neg(less_toxic(t1,m1)).
neg(less_toxic(jj1,g1)).
neg(less_toxic(f1,z1)).
neg(less_toxic(i1,ll1)).
neg(less_toxic(e1,hh1)).
neg(less_toxic(e1,cc1)).
neg(less_toxic(t1,cc1)).
neg(less_toxic(h1,s1)).
neg(less_toxic(u1,ee1)).
neg(less_toxic(a1,kk1)).
neg(less_toxic(a1,ff1)).
neg(less_toxic(f1,t1)).
neg(less_toxic(z1,o1)).
neg(less_toxic(f1,n1)).
neg(less_toxic(b1,y1)).
neg(less_toxic(d1,f1)).
neg(less_toxic(l1,hh1)).
neg(less_toxic(w1,g1)).
neg(less_toxic(u1,ii1)).
neg(less_toxic(cc1,m1)).
neg(less_toxic(a1,hh1)).
neg(less_toxic(p1,m1)).
neg(less_toxic(d1,u1)).
neg(less_toxic(c1,x1)).
neg(less_toxic(v1,j1)).
neg(less_toxic(aa1,b1)).
neg(less_toxic(c1,ff1)).
neg(less_toxic(c1,m1)).
neg(less_toxic(b1,n1)).
neg(less_toxic(c1,p1)).
neg(less_toxic(c1,w1)).
neg(less_toxic(p1,n1)).
neg(less_toxic(f1,l1)).
neg(less_toxic(t1,hh1)).
neg(less_toxic(h1,ii1)).
neg(less_toxic(f1,g1)).
neg(less_toxic(t1,ff1)).
neg(less_toxic(v1,w1)).
neg(less_toxic(h1,hh1)).
neg(less_toxic(d1,q1)).
neg(less_toxic(h1,k1)).
neg(less_toxic(aa1,g1)).
neg(less_toxic(i1,hh1)).
neg(less_toxic(z1,w1)).
neg(less_toxic(jj1,n1)).
neg(less_toxic(d1,ee1)).
neg(less_toxic(h1,o1)).
neg(less_toxic(b1,m1)).
neg(less_toxic(jj1,w1)).
neg(less_toxic(h1,n1)).
neg(less_toxic(z1,ee1)).
neg(less_toxic(dd1,m1)).
neg(less_toxic(l1,ii1)).
neg(less_toxic(z1,n1)).
neg(less_toxic(aa1,o1)).
neg(less_toxic(z1,kk1)).
neg(less_toxic(f1,s1)).
neg(less_toxic(p1,a1)).
neg(less_toxic(e1,w1)).
neg(less_toxic(v1,n1)).
neg(less_toxic(dd1,n1)).
neg(less_toxic(c1,t1)).
neg(less_toxic(b1,g1)).
neg(less_toxic(f1,y1)).
neg(less_toxic(l1,n1)).
neg(less_toxic(f1,aa1)).
neg(less_toxic(dd1,y1)).
neg(less_toxic(l1,s1)).
neg(less_toxic(p1,x1)).
neg(less_toxic(w1,j1)).
neg(less_toxic(c1,o1)).
neg(less_toxic(cc1,r1)).
neg(less_toxic(jj1,s1)).
neg(less_toxic(t1,ll1)).
neg(less_toxic(a1,ee1)).
neg(less_toxic(jj1,k1)).
neg(less_toxic(f1,ii1)).
neg(less_toxic(d1,o1)).
neg(less_toxic(c1,g1)).
neg(less_toxic(c1,l1)).
neg(less_toxic(c1,z1)).
neg(less_toxic(cc1,g1)).
neg(less_toxic(i1,r1)).
neg(less_toxic(h1,j1)).
neg(less_toxic(u1,b1)).
neg(less_toxic(jj1,bb1)).
neg(less_toxic(p1,u1)).
neg(less_toxic(jj1,y1)).
neg(less_toxic(e1,j1)).
neg(less_toxic(u1,w1)).
neg(less_toxic(p1,g1)).
neg(less_toxic(dd1,g1)).
neg(less_toxic(aa1,x1)).
neg(less_toxic(f1,q1)).
neg(less_toxic(p1,hh1)).
neg(less_toxic(d1,i1)).
neg(less_toxic(b1,ff1)).
neg(less_toxic(t1,x1)).
neg(less_toxic(b1,ll1)).
neg(less_toxic(a1,m1)).
neg(less_toxic(i1,cc1)).
neg(less_toxic(d1,cc1)).
neg(less_toxic(d1,ll1)).
neg(less_toxic(d1,ff1)).
neg(less_toxic(cc1,x1)).
neg(less_toxic(d1,v1)).
neg(less_toxic(cc1,hh1)).
neg(less_toxic(h1,y1)).
neg(less_toxic(h1,w1)).
neg(less_toxic(cc1,s1)).
neg(less_toxic(dd1,k1)).
neg(less_toxic(i1,n1)).
neg(less_toxic(l1,bb1)).
neg(less_toxic(c1,kk1)).
neg(less_toxic(c1,b1)).
neg(less_toxic(w1,k1)).
neg(less_toxic(z1,k1)).
neg(less_toxic(aa1,hh1)).
neg(less_toxic(u1,cc1)).
neg(less_toxic(z1,g1)).
neg(less_toxic(f1,hh1)).
neg(less_toxic(b1,r1)).
neg(less_toxic(jj1,m1)).
neg(less_toxic(p1,q1)).
neg(less_toxic(i1,ff1)).
neg(less_toxic(d1,bb1)).
neg(less_toxic(dd1,ee1)).
neg(less_toxic(l1,q1)).
neg(less_toxic(t1,s1)).
neg(less_toxic(a1,ll1)).
neg(less_toxic(dd1,o1)).
neg(less_toxic(l1,y1)).
neg(less_toxic(cc1,ff1)).
neg(less_toxic(l1,x1)).
neg(less_toxic(u1,k1)).
neg(less_toxic(w1,y1)).
neg(less_toxic(a1,q1)).
neg(less_toxic(f1,r1)).
neg(less_toxic(p1,r1)).
neg(less_toxic(c1,n1)).
neg(less_toxic(f1,kk1)).
neg(less_toxic(p1,kk1)).
neg(less_toxic(h1,cc1)).
neg(less_toxic(d1,z1)).
neg(less_toxic(i1,b1)).
neg(less_toxic(dd1,ll1)).
neg(less_toxic(z1,ll1)).
neg(less_toxic(c1,cc1)).
neg(less_toxic(t1,b1)).
neg(less_toxic(cc1,ii1)).
neg(less_toxic(aa1,j1)).
neg(less_toxic(u1,r1)).
neg(less_toxic(c1,bb1)).
neg(less_toxic(p1,i1)).
neg(less_toxic(a1,cc1)).
neg(less_toxic(u1,bb1)).
neg(less_toxic(f1,ll1)).
neg(less_toxic(z1,bb1)).
neg(less_toxic(c1,hh1)).
neg(less_toxic(w1,ff1)).
neg(less_toxic(c1,e1)).
neg(less_toxic(t1,n1)).
neg(less_toxic(d1,jj1)).
neg(less_toxic(p1,dd1)).
neg(less_toxic(p1,cc1)).
neg(less_toxic(h1,bb1)).
neg(less_toxic(w1,ll1)).
neg(less_toxic(f1,v1)).
neg(less_toxic(v1,bb1)).
neg(less_toxic(c1,ii1)).
neg(less_toxic(w1,ee1)).
neg(less_toxic(u1,y1)).
neg(less_toxic(t1,q1)).
neg(less_toxic(jj1,kk1)).
neg(less_toxic(v1,q1)).
neg(less_toxic(f1,o1)).
neg(less_toxic(z1,cc1)).
neg(less_toxic(f1,ee1)).
neg(less_toxic(p1,k1)).
neg(less_toxic(dd1,hh1)).
neg(less_toxic(u1,n1)).
neg(less_toxic(d1,ii1)).
neg(less_toxic(c1,i1)).
neg(less_toxic(v1,ff1)).
neg(less_toxic(d1,kk1)).
neg(less_toxic(w1,o1)).
neg(less_toxic(w1,x1)).
neg(less_toxic(p1,ee1)).
neg(less_toxic(a1,g1)).
neg(less_toxic(f1,m1)).
neg(less_toxic(l1,b1)).
neg(less_toxic(c1,ee1)).
neg(less_toxic(v1,g1)).
neg(less_toxic(v1,b1)).
neg(less_toxic(c1,j1)).
neg(less_toxic(a1,x1)).
neg(less_toxic(d1,e1)).
neg(less_toxic(jj1,b1)).
neg(less_toxic(p1,aa1)).
neg(less_toxic(v1,k1)).
neg(less_toxic(f1,bb1)).
neg(less_toxic(i1,s1)).
neg(less_toxic(f1,h1)).
neg(less_toxic(aa1,ii1)).
neg(less_toxic(w1,bb1)).
neg(less_toxic(b1,x1)).
neg(less_toxic(a1,bb1)).
neg(less_toxic(i1,bb1)).
neg(less_toxic(a1,ii1)).
neg(less_toxic(i1,ee1)).
neg(less_toxic(e1,kk1)).
neg(less_toxic(aa1,ll1)).
neg(less_toxic(p1,bb1)).
neg(less_toxic(cc1,j1)).
neg(less_toxic(cc1,o1)).
neg(less_toxic(cc1,ee1)).
neg(less_toxic(p1,t1)).
neg(less_toxic(h1,b1)).
neg(less_toxic(aa1,kk1)).
neg(less_toxic(c1,u1)).
neg(less_toxic(i1,w1)).
neg(less_toxic(jj1,x1)).
neg(less_toxic(t1,g1)).
neg(less_toxic(i1,y1)).
neg(less_toxic(e1,o1)).
neg(less_toxic(z1,j1)).
neg(less_toxic(t1,ee1)).
neg(less_toxic(f1,cc1)).
neg(less_toxic(jj1,ll1)).
neg(less_toxic(u1,kk1)).
neg(less_toxic(p1,o1)).
neg(less_toxic(d1,h1)).
neg(less_toxic(e1,m1)).
neg(less_toxic(v1,o1)).
neg(less_toxic(w1,q1)).
neg(less_toxic(c1,k1)).
neg(less_toxic(v1,ii1)).
neg(less_toxic(e1,s1)).
neg(less_toxic(d1,m1)).
neg(less_toxic(cc1,kk1)).
neg(less_toxic(b1,q1)).
neg(less_toxic(v1,s1)).
neg(less_toxic(d1,k1)).
neg(less_toxic(b1,ii1)).
neg(less_toxic(b1,o1)).
neg(less_toxic(dd1,j1)).
neg(less_toxic(p1,h1)).
neg(less_toxic(c1,q1)).
neg(less_toxic(c1,r1)).
neg(less_toxic(dd1,q1)).
neg(less_toxic(u1,o1)).
neg(less_toxic(d1,n1)).
neg(less_toxic(l1,kk1)).
neg(less_toxic(u1,g1)).
neg(less_toxic(v1,y1)).
neg(less_toxic(d1,r1)).
neg(less_toxic(w1,n1)).
neg(less_toxic(h1,ll1)).
neg(less_toxic(d1,w1)).
neg(less_toxic(a1,r1)).
neg(less_toxic(z1,ff1)).
neg(less_toxic(aa1,k1)).
neg(less_toxic(v1,ll1)).
neg(less_toxic(l1,w1)).
neg(less_toxic(b1,s1)).
neg(less_toxic(f1,a1)).
neg(less_toxic(dd1,ii1)).
neg(less_toxic(d1,p1)).
neg(less_toxic(t1,ii1)).
neg(less_toxic(aa1,s1)).
neg(less_toxic(w1,r1)).
neg(less_toxic(aa1,r1)).
neg(less_toxic(b1,ee1)).
neg(less_toxic(e1,x1)).
neg(less_toxic(u1,x1)).
neg(less_toxic(e1,g1)).
neg(less_toxic(l1,o1)).
neg(less_toxic(t1,k1)).
neg(less_toxic(z1,r1)).
neg(less_toxic(aa1,cc1)).
neg(less_toxic(f1,e1)).
neg(less_toxic(p1,l1)).
neg(less_toxic(aa1,q1)).
neg(less_toxic(b1,k1)).
neg(less_toxic(a1,b1)).
neg(less_toxic(v1,m1)).
neg(less_toxic(f1,u1)).
neg(less_toxic(e1,r1)).
neg(less_toxic(p1,s1)).
neg(less_toxic(c1,jj1)).
neg(less_toxic(w1,m1)).
neg(less_toxic(aa1,n1)).
neg(less_toxic(p1,b1)).
neg(less_toxic(jj1,q1)).
neg(less_toxic(d1,aa1)).
neg(less_toxic(dd1,b1)).
neg(less_toxic(a1,k1)).
neg(less_toxic(dd1,cc1)).
neg(less_toxic(i1,j1)).
neg(less_toxic(v1,r1)).
neg(less_toxic(d1,x1)).
neg(less_toxic(w1,kk1)).
neg(less_toxic(i1,k1)).
neg(less_toxic(b1,hh1)).
neg(less_toxic(t1,w1)).
neg(less_toxic(e1,y1)).
neg(less_toxic(c1,ll1)).
neg(less_toxic(c1,v1)).
neg(less_toxic(u1,m1)).
neg(less_toxic(h1,m1)).
neg(less_toxic(c1,h1)).
neg(less_toxic(d1,a1)).
neg(less_toxic(a1,y1)).
neg(less_toxic(u1,j1)).
neg(less_toxic(jj1,hh1)).
neg(less_toxic(l1,k1)).
neg(less_toxic(l1,r1)).
neg(less_toxic(u1,hh1)).
neg(less_toxic(t1,r1)).
neg(less_toxic(z1,hh1)).
neg(less_toxic(z1,s1)).
neg(less_toxic(dd1,ff1)).
neg(less_toxic(aa1,m1)).
neg(less_toxic(aa1,bb1)).
neg(less_toxic(d1,y1)).
neg(less_toxic(d1,g1)).
neg(less_toxic(p1,jj1)).
neg(less_toxic(i1,ii1)).
neg(less_toxic(jj1,ff1)).
neg(less_toxic(e1,ii1)).
neg(less_toxic(c1,dd1)).
neg(less_toxic(e1,k1)).
neg(less_toxic(e1,ee1)).
neg(less_toxic(d1,hh1)).
neg(less_toxic(h1,x1)).
neg(less_toxic(c1,aa1)).
