pos(leg(a,c)).
pos(leg(b,d)).
pos(leg(c,a)).
pos(leg(d,b)).
pos(sameclique(a,a)).
pos(sameclique(a,b)).
pos(sameclique(a,c)).
pos(sameclique(a,d)).
pos(sameclique(b,a)).
pos(sameclique(b,b)).
pos(sameclique(b,c)).
pos(sameclique(b,d)).
pos(sameclique(c,a)).
pos(sameclique(c,b)).
pos(sameclique(c,c)).
pos(sameclique(c,d)).
pos(sameclique(d,a)).
pos(sameclique(d,b)).
pos(sameclique(d,c)).
pos(sameclique(d,d)).
