%% next_score(A,B):-does(C,D),opponent(A,C),my_true_score(A,B),lay_claim(D).
%% next_score(A,B):-my_true_score(A,B),opponent(C,A),c80(B),my_true_control(C).
%% next_score(A,B):-my_succ(B,D),my_true_score(A,D),does(A,C),lay_claim(C).
%% next_score(A,B):-my_true_score(A,B),does(A,C),end_game(C).
%% next_score(A,B):-my_true_score(A,C),does(E,D),opponent(A,E),c65(C),c90(B),end_game(D).
%% next_score(A,B):-c55(C),my_true_score(A,C),c80(B).
%% next_score(A,B):-my_true_score(A,C),c95(B),does(E,D),opponent(E,A),c70(C),end_game(D).

%% :- #count{P,Vars : body_literal(P,_,Vars)} != 1.

max_clauses(1).
max_vars(6).
max_body(6).

head_pred(next_score,2).
body_pred(does,2).
body_pred(my_true_claim_made_by,1).
body_pred(my_true_control,1).
body_pred(my_succ,2).
body_pred(my_true_gameOver,1).
body_pred(my_true_score,2).
body_pred(opponent,2).

type(next_score,(agent,int)).
type(does,(agent,action)).
type(my_true_claim_made_by,(agent,)).
type(my_true_control,(agent,)).
type(my_succ,(int,int)).
type(my_true_gameOver,(agent,)).
type(my_true_score,(agent,int)).
type(opponent,(agent,agent)).

body_pred(P,1):-
    constant(P,_).
type(P,(T,)):-
    constant(P,T).

constant(lay_claim,action).
constant(end_game,action).
constant(noop,action).
constant(white,agent).
constant(black,agent).
constant(c5,int).
constant(c10,int).
constant(c15,int).
constant(c20,int).
constant(c25,int).
constant(c30,int).
constant(c35,int).
constant(c40,int).
constant(c45,int).
constant(c50,int).
constant(c55,int).
constant(c60,int).
constant(c65,int).
constant(c70,int).
constant(c75,int).
constant(c80,int).
constant(c85,int).
constant(c90,int).
constant(c95,int).
constant(c100,int).

prop(antitransitive,my_succ).
prop(antitransitive,opponent).
prop(antitriangular,my_succ).
prop(antitriangular,opponent).
prop(asymmetric_ab_ba,my_succ).
prop(postcon,(my_true_score,c10)).
prop(postcon,(my_true_score,c15)).
prop(postcon,(my_true_score,c20)).
prop(postcon,(my_true_score,c25)).
prop(postcon,(my_true_score,c30)).
prop(postcon,(my_true_score,c35)).
prop(postcon,(my_true_score,c40)).
prop(postcon,(my_true_score,c45)).
prop(postcon,(my_true_score,c5)).
prop(postcon,(my_true_score,c50)).
prop(postcon,(my_true_score,c85)).
prop(pre_postcon,(black,my_true_score,c10)).
prop(pre_postcon,(black,my_true_score,c15)).
prop(pre_postcon,(black,my_true_score,c20)).
prop(pre_postcon,(black,my_true_score,c25)).
prop(pre_postcon,(black,my_true_score,c30)).
prop(pre_postcon,(black,my_true_score,c35)).
prop(pre_postcon,(black,my_true_score,c40)).
prop(pre_postcon,(black,my_true_score,c45)).
prop(pre_postcon,(black,my_true_score,c5)).
prop(pre_postcon,(black,my_true_score,c50)).
prop(pre_postcon,(black,my_true_score,c55)).
prop(pre_postcon,(black,my_true_score,c85)).
prop(pre_postcon,(black,my_true_score,c95)).
prop(pre_postcon,(black,next_score,c10)).
prop(pre_postcon,(black,next_score,c100)).
prop(pre_postcon,(black,next_score,c15)).
prop(pre_postcon,(black,next_score,c20)).
prop(pre_postcon,(black,next_score,c25)).
prop(pre_postcon,(black,next_score,c30)).
prop(pre_postcon,(black,next_score,c35)).
prop(pre_postcon,(black,next_score,c40)).
prop(pre_postcon,(black,next_score,c45)).
prop(pre_postcon,(black,next_score,c5)).
prop(pre_postcon,(black,next_score,c50)).
prop(pre_postcon,(black,next_score,c55)).
prop(pre_postcon,(black,next_score,c60)).
prop(pre_postcon,(black,next_score,c65)).
prop(pre_postcon,(black,next_score,c70)).
prop(pre_postcon,(black,next_score,c75)).
prop(pre_postcon,(black,next_score,c80)).
prop(pre_postcon,(black,next_score,c85)).
prop(pre_postcon,(black,next_score,c90)).
prop(pre_postcon,(black,next_score,c95)).
prop(pre_postcon,(black,opponent,black)).
prop(pre_postcon,(c10,my_succ,c10)).
prop(pre_postcon,(c10,my_succ,c100)).
prop(pre_postcon,(c10,my_succ,c20)).
prop(pre_postcon,(c10,my_succ,c25)).
prop(pre_postcon,(c10,my_succ,c30)).
prop(pre_postcon,(c10,my_succ,c35)).
prop(pre_postcon,(c10,my_succ,c40)).
prop(pre_postcon,(c10,my_succ,c45)).
prop(pre_postcon,(c10,my_succ,c5)).
prop(pre_postcon,(c10,my_succ,c50)).
prop(pre_postcon,(c10,my_succ,c55)).
prop(pre_postcon,(c10,my_succ,c60)).
prop(pre_postcon,(c10,my_succ,c65)).
prop(pre_postcon,(c10,my_succ,c70)).
prop(pre_postcon,(c10,my_succ,c75)).
prop(pre_postcon,(c10,my_succ,c80)).
prop(pre_postcon,(c10,my_succ,c85)).
prop(pre_postcon,(c10,my_succ,c90)).
prop(pre_postcon,(c10,my_succ,c95)).
prop(pre_postcon,(c100,my_succ,c10)).
prop(pre_postcon,(c100,my_succ,c100)).
prop(pre_postcon,(c100,my_succ,c15)).
prop(pre_postcon,(c100,my_succ,c20)).
prop(pre_postcon,(c100,my_succ,c25)).
prop(pre_postcon,(c100,my_succ,c30)).
prop(pre_postcon,(c100,my_succ,c35)).
prop(pre_postcon,(c100,my_succ,c40)).
prop(pre_postcon,(c100,my_succ,c45)).
prop(pre_postcon,(c100,my_succ,c5)).
prop(pre_postcon,(c100,my_succ,c50)).
prop(pre_postcon,(c100,my_succ,c55)).
prop(pre_postcon,(c100,my_succ,c60)).
prop(pre_postcon,(c100,my_succ,c65)).
prop(pre_postcon,(c100,my_succ,c70)).
prop(pre_postcon,(c100,my_succ,c75)).
prop(pre_postcon,(c100,my_succ,c80)).
prop(pre_postcon,(c100,my_succ,c85)).
prop(pre_postcon,(c100,my_succ,c90)).
prop(pre_postcon,(c100,my_succ,c95)).
prop(pre_postcon,(c15,my_succ,c10)).
prop(pre_postcon,(c15,my_succ,c100)).
prop(pre_postcon,(c15,my_succ,c15)).
prop(pre_postcon,(c15,my_succ,c25)).
prop(pre_postcon,(c15,my_succ,c30)).
prop(pre_postcon,(c15,my_succ,c35)).
prop(pre_postcon,(c15,my_succ,c40)).
prop(pre_postcon,(c15,my_succ,c45)).
prop(pre_postcon,(c15,my_succ,c5)).
prop(pre_postcon,(c15,my_succ,c50)).
prop(pre_postcon,(c15,my_succ,c55)).
prop(pre_postcon,(c15,my_succ,c60)).
prop(pre_postcon,(c15,my_succ,c65)).
prop(pre_postcon,(c15,my_succ,c70)).
prop(pre_postcon,(c15,my_succ,c75)).
prop(pre_postcon,(c15,my_succ,c80)).
prop(pre_postcon,(c15,my_succ,c85)).
prop(pre_postcon,(c15,my_succ,c90)).
prop(pre_postcon,(c15,my_succ,c95)).
prop(pre_postcon,(c20,my_succ,c10)).
prop(pre_postcon,(c20,my_succ,c100)).
prop(pre_postcon,(c20,my_succ,c15)).
prop(pre_postcon,(c20,my_succ,c20)).
prop(pre_postcon,(c20,my_succ,c30)).
prop(pre_postcon,(c20,my_succ,c35)).
prop(pre_postcon,(c20,my_succ,c40)).
prop(pre_postcon,(c20,my_succ,c45)).
prop(pre_postcon,(c20,my_succ,c5)).
prop(pre_postcon,(c20,my_succ,c50)).
prop(pre_postcon,(c20,my_succ,c55)).
prop(pre_postcon,(c20,my_succ,c60)).
prop(pre_postcon,(c20,my_succ,c65)).
prop(pre_postcon,(c20,my_succ,c70)).
prop(pre_postcon,(c20,my_succ,c75)).
prop(pre_postcon,(c20,my_succ,c80)).
prop(pre_postcon,(c20,my_succ,c85)).
prop(pre_postcon,(c20,my_succ,c90)).
prop(pre_postcon,(c20,my_succ,c95)).
prop(pre_postcon,(c25,my_succ,c10)).
prop(pre_postcon,(c25,my_succ,c100)).
prop(pre_postcon,(c25,my_succ,c15)).
prop(pre_postcon,(c25,my_succ,c20)).
prop(pre_postcon,(c25,my_succ,c25)).
prop(pre_postcon,(c25,my_succ,c35)).
prop(pre_postcon,(c25,my_succ,c40)).
prop(pre_postcon,(c25,my_succ,c45)).
prop(pre_postcon,(c25,my_succ,c5)).
prop(pre_postcon,(c25,my_succ,c50)).
prop(pre_postcon,(c25,my_succ,c55)).
prop(pre_postcon,(c25,my_succ,c60)).
prop(pre_postcon,(c25,my_succ,c65)).
prop(pre_postcon,(c25,my_succ,c70)).
prop(pre_postcon,(c25,my_succ,c75)).
prop(pre_postcon,(c25,my_succ,c80)).
prop(pre_postcon,(c25,my_succ,c85)).
prop(pre_postcon,(c25,my_succ,c90)).
prop(pre_postcon,(c25,my_succ,c95)).
prop(pre_postcon,(c30,my_succ,c10)).
prop(pre_postcon,(c30,my_succ,c100)).
prop(pre_postcon,(c30,my_succ,c15)).
prop(pre_postcon,(c30,my_succ,c20)).
prop(pre_postcon,(c30,my_succ,c25)).
prop(pre_postcon,(c30,my_succ,c30)).
prop(pre_postcon,(c30,my_succ,c40)).
prop(pre_postcon,(c30,my_succ,c45)).
prop(pre_postcon,(c30,my_succ,c5)).
prop(pre_postcon,(c30,my_succ,c50)).
prop(pre_postcon,(c30,my_succ,c55)).
prop(pre_postcon,(c30,my_succ,c60)).
prop(pre_postcon,(c30,my_succ,c65)).
prop(pre_postcon,(c30,my_succ,c70)).
prop(pre_postcon,(c30,my_succ,c75)).
prop(pre_postcon,(c30,my_succ,c80)).
prop(pre_postcon,(c30,my_succ,c85)).
prop(pre_postcon,(c30,my_succ,c90)).
prop(pre_postcon,(c30,my_succ,c95)).
prop(pre_postcon,(c35,my_succ,c10)).
prop(pre_postcon,(c35,my_succ,c100)).
prop(pre_postcon,(c35,my_succ,c15)).
prop(pre_postcon,(c35,my_succ,c20)).
prop(pre_postcon,(c35,my_succ,c25)).
prop(pre_postcon,(c35,my_succ,c30)).
prop(pre_postcon,(c35,my_succ,c35)).
prop(pre_postcon,(c35,my_succ,c45)).
prop(pre_postcon,(c35,my_succ,c5)).
prop(pre_postcon,(c35,my_succ,c50)).
prop(pre_postcon,(c35,my_succ,c55)).
prop(pre_postcon,(c35,my_succ,c60)).
prop(pre_postcon,(c35,my_succ,c65)).
prop(pre_postcon,(c35,my_succ,c70)).
prop(pre_postcon,(c35,my_succ,c75)).
prop(pre_postcon,(c35,my_succ,c80)).
prop(pre_postcon,(c35,my_succ,c85)).
prop(pre_postcon,(c35,my_succ,c90)).
prop(pre_postcon,(c35,my_succ,c95)).
prop(pre_postcon,(c40,my_succ,c10)).
prop(pre_postcon,(c40,my_succ,c100)).
prop(pre_postcon,(c40,my_succ,c15)).
prop(pre_postcon,(c40,my_succ,c20)).
prop(pre_postcon,(c40,my_succ,c25)).
prop(pre_postcon,(c40,my_succ,c30)).
prop(pre_postcon,(c40,my_succ,c35)).
prop(pre_postcon,(c40,my_succ,c40)).
prop(pre_postcon,(c40,my_succ,c5)).
prop(pre_postcon,(c40,my_succ,c50)).
prop(pre_postcon,(c40,my_succ,c55)).
prop(pre_postcon,(c40,my_succ,c60)).
prop(pre_postcon,(c40,my_succ,c65)).
prop(pre_postcon,(c40,my_succ,c70)).
prop(pre_postcon,(c40,my_succ,c75)).
prop(pre_postcon,(c40,my_succ,c80)).
prop(pre_postcon,(c40,my_succ,c85)).
prop(pre_postcon,(c40,my_succ,c90)).
prop(pre_postcon,(c40,my_succ,c95)).
prop(pre_postcon,(c45,my_succ,c10)).
prop(pre_postcon,(c45,my_succ,c100)).
prop(pre_postcon,(c45,my_succ,c15)).
prop(pre_postcon,(c45,my_succ,c20)).
prop(pre_postcon,(c45,my_succ,c25)).
prop(pre_postcon,(c45,my_succ,c30)).
prop(pre_postcon,(c45,my_succ,c35)).
prop(pre_postcon,(c45,my_succ,c40)).
prop(pre_postcon,(c45,my_succ,c45)).
prop(pre_postcon,(c45,my_succ,c5)).
prop(pre_postcon,(c45,my_succ,c55)).
prop(pre_postcon,(c45,my_succ,c60)).
prop(pre_postcon,(c45,my_succ,c65)).
prop(pre_postcon,(c45,my_succ,c70)).
prop(pre_postcon,(c45,my_succ,c75)).
prop(pre_postcon,(c45,my_succ,c80)).
prop(pre_postcon,(c45,my_succ,c85)).
prop(pre_postcon,(c45,my_succ,c90)).
prop(pre_postcon,(c45,my_succ,c95)).
prop(pre_postcon,(c5,my_succ,c100)).
prop(pre_postcon,(c5,my_succ,c15)).
prop(pre_postcon,(c5,my_succ,c20)).
prop(pre_postcon,(c5,my_succ,c25)).
prop(pre_postcon,(c5,my_succ,c30)).
prop(pre_postcon,(c5,my_succ,c35)).
prop(pre_postcon,(c5,my_succ,c40)).
prop(pre_postcon,(c5,my_succ,c45)).
prop(pre_postcon,(c5,my_succ,c5)).
prop(pre_postcon,(c5,my_succ,c50)).
prop(pre_postcon,(c5,my_succ,c55)).
prop(pre_postcon,(c5,my_succ,c60)).
prop(pre_postcon,(c5,my_succ,c65)).
prop(pre_postcon,(c5,my_succ,c70)).
prop(pre_postcon,(c5,my_succ,c75)).
prop(pre_postcon,(c5,my_succ,c80)).
prop(pre_postcon,(c5,my_succ,c85)).
prop(pre_postcon,(c5,my_succ,c90)).
prop(pre_postcon,(c5,my_succ,c95)).
prop(pre_postcon,(c50,my_succ,c10)).
prop(pre_postcon,(c50,my_succ,c100)).
prop(pre_postcon,(c50,my_succ,c15)).
prop(pre_postcon,(c50,my_succ,c20)).
prop(pre_postcon,(c50,my_succ,c25)).
prop(pre_postcon,(c50,my_succ,c30)).
prop(pre_postcon,(c50,my_succ,c35)).
prop(pre_postcon,(c50,my_succ,c40)).
prop(pre_postcon,(c50,my_succ,c45)).
prop(pre_postcon,(c50,my_succ,c5)).
prop(pre_postcon,(c50,my_succ,c50)).
prop(pre_postcon,(c50,my_succ,c60)).
prop(pre_postcon,(c50,my_succ,c65)).
prop(pre_postcon,(c50,my_succ,c70)).
prop(pre_postcon,(c50,my_succ,c75)).
prop(pre_postcon,(c50,my_succ,c80)).
prop(pre_postcon,(c50,my_succ,c85)).
prop(pre_postcon,(c50,my_succ,c90)).
prop(pre_postcon,(c50,my_succ,c95)).
prop(pre_postcon,(c55,my_succ,c10)).
prop(pre_postcon,(c55,my_succ,c100)).
prop(pre_postcon,(c55,my_succ,c15)).
prop(pre_postcon,(c55,my_succ,c20)).
prop(pre_postcon,(c55,my_succ,c25)).
prop(pre_postcon,(c55,my_succ,c30)).
prop(pre_postcon,(c55,my_succ,c35)).
prop(pre_postcon,(c55,my_succ,c40)).
prop(pre_postcon,(c55,my_succ,c45)).
prop(pre_postcon,(c55,my_succ,c5)).
prop(pre_postcon,(c55,my_succ,c50)).
prop(pre_postcon,(c55,my_succ,c55)).
prop(pre_postcon,(c55,my_succ,c65)).
prop(pre_postcon,(c55,my_succ,c70)).
prop(pre_postcon,(c55,my_succ,c75)).
prop(pre_postcon,(c55,my_succ,c80)).
prop(pre_postcon,(c55,my_succ,c85)).
prop(pre_postcon,(c55,my_succ,c90)).
prop(pre_postcon,(c55,my_succ,c95)).
prop(pre_postcon,(c60,my_succ,c10)).
prop(pre_postcon,(c60,my_succ,c100)).
prop(pre_postcon,(c60,my_succ,c15)).
prop(pre_postcon,(c60,my_succ,c20)).
prop(pre_postcon,(c60,my_succ,c25)).
prop(pre_postcon,(c60,my_succ,c30)).
prop(pre_postcon,(c60,my_succ,c35)).
prop(pre_postcon,(c60,my_succ,c40)).
prop(pre_postcon,(c60,my_succ,c45)).
prop(pre_postcon,(c60,my_succ,c5)).
prop(pre_postcon,(c60,my_succ,c50)).
prop(pre_postcon,(c60,my_succ,c55)).
prop(pre_postcon,(c60,my_succ,c60)).
prop(pre_postcon,(c60,my_succ,c70)).
prop(pre_postcon,(c60,my_succ,c75)).
prop(pre_postcon,(c60,my_succ,c80)).
prop(pre_postcon,(c60,my_succ,c85)).
prop(pre_postcon,(c60,my_succ,c90)).
prop(pre_postcon,(c60,my_succ,c95)).
prop(pre_postcon,(c65,my_succ,c10)).
prop(pre_postcon,(c65,my_succ,c100)).
prop(pre_postcon,(c65,my_succ,c15)).
prop(pre_postcon,(c65,my_succ,c20)).
prop(pre_postcon,(c65,my_succ,c25)).
prop(pre_postcon,(c65,my_succ,c30)).
prop(pre_postcon,(c65,my_succ,c35)).
prop(pre_postcon,(c65,my_succ,c40)).
prop(pre_postcon,(c65,my_succ,c45)).
prop(pre_postcon,(c65,my_succ,c5)).
prop(pre_postcon,(c65,my_succ,c50)).
prop(pre_postcon,(c65,my_succ,c55)).
prop(pre_postcon,(c65,my_succ,c60)).
prop(pre_postcon,(c65,my_succ,c65)).
prop(pre_postcon,(c65,my_succ,c75)).
prop(pre_postcon,(c65,my_succ,c80)).
prop(pre_postcon,(c65,my_succ,c85)).
prop(pre_postcon,(c65,my_succ,c90)).
prop(pre_postcon,(c65,my_succ,c95)).
prop(pre_postcon,(c70,my_succ,c10)).
prop(pre_postcon,(c70,my_succ,c100)).
prop(pre_postcon,(c70,my_succ,c15)).
prop(pre_postcon,(c70,my_succ,c20)).
prop(pre_postcon,(c70,my_succ,c25)).
prop(pre_postcon,(c70,my_succ,c30)).
prop(pre_postcon,(c70,my_succ,c35)).
prop(pre_postcon,(c70,my_succ,c40)).
prop(pre_postcon,(c70,my_succ,c45)).
prop(pre_postcon,(c70,my_succ,c5)).
prop(pre_postcon,(c70,my_succ,c50)).
prop(pre_postcon,(c70,my_succ,c55)).
prop(pre_postcon,(c70,my_succ,c60)).
prop(pre_postcon,(c70,my_succ,c65)).
prop(pre_postcon,(c70,my_succ,c70)).
prop(pre_postcon,(c70,my_succ,c80)).
prop(pre_postcon,(c70,my_succ,c85)).
prop(pre_postcon,(c70,my_succ,c90)).
prop(pre_postcon,(c70,my_succ,c95)).
prop(pre_postcon,(c75,my_succ,c10)).
prop(pre_postcon,(c75,my_succ,c100)).
prop(pre_postcon,(c75,my_succ,c15)).
prop(pre_postcon,(c75,my_succ,c20)).
prop(pre_postcon,(c75,my_succ,c25)).
prop(pre_postcon,(c75,my_succ,c30)).
prop(pre_postcon,(c75,my_succ,c35)).
prop(pre_postcon,(c75,my_succ,c40)).
prop(pre_postcon,(c75,my_succ,c45)).
prop(pre_postcon,(c75,my_succ,c5)).
prop(pre_postcon,(c75,my_succ,c50)).
prop(pre_postcon,(c75,my_succ,c55)).
prop(pre_postcon,(c75,my_succ,c60)).
prop(pre_postcon,(c75,my_succ,c65)).
prop(pre_postcon,(c75,my_succ,c70)).
prop(pre_postcon,(c75,my_succ,c75)).
prop(pre_postcon,(c75,my_succ,c85)).
prop(pre_postcon,(c75,my_succ,c90)).
prop(pre_postcon,(c75,my_succ,c95)).
prop(pre_postcon,(c80,my_succ,c10)).
prop(pre_postcon,(c80,my_succ,c100)).
prop(pre_postcon,(c80,my_succ,c15)).
prop(pre_postcon,(c80,my_succ,c20)).
prop(pre_postcon,(c80,my_succ,c25)).
prop(pre_postcon,(c80,my_succ,c30)).
prop(pre_postcon,(c80,my_succ,c35)).
prop(pre_postcon,(c80,my_succ,c40)).
prop(pre_postcon,(c80,my_succ,c45)).
prop(pre_postcon,(c80,my_succ,c5)).
prop(pre_postcon,(c80,my_succ,c50)).
prop(pre_postcon,(c80,my_succ,c55)).
prop(pre_postcon,(c80,my_succ,c60)).
prop(pre_postcon,(c80,my_succ,c65)).
prop(pre_postcon,(c80,my_succ,c70)).
prop(pre_postcon,(c80,my_succ,c75)).
prop(pre_postcon,(c80,my_succ,c80)).
prop(pre_postcon,(c80,my_succ,c90)).
prop(pre_postcon,(c80,my_succ,c95)).
prop(pre_postcon,(c85,my_succ,c10)).
prop(pre_postcon,(c85,my_succ,c100)).
prop(pre_postcon,(c85,my_succ,c15)).
prop(pre_postcon,(c85,my_succ,c20)).
prop(pre_postcon,(c85,my_succ,c25)).
prop(pre_postcon,(c85,my_succ,c30)).
prop(pre_postcon,(c85,my_succ,c35)).
prop(pre_postcon,(c85,my_succ,c40)).
prop(pre_postcon,(c85,my_succ,c45)).
prop(pre_postcon,(c85,my_succ,c5)).
prop(pre_postcon,(c85,my_succ,c50)).
prop(pre_postcon,(c85,my_succ,c55)).
prop(pre_postcon,(c85,my_succ,c60)).
prop(pre_postcon,(c85,my_succ,c65)).
prop(pre_postcon,(c85,my_succ,c70)).
prop(pre_postcon,(c85,my_succ,c75)).
prop(pre_postcon,(c85,my_succ,c80)).
prop(pre_postcon,(c85,my_succ,c85)).
prop(pre_postcon,(c85,my_succ,c95)).
prop(pre_postcon,(c90,my_succ,c10)).
prop(pre_postcon,(c90,my_succ,c100)).
prop(pre_postcon,(c90,my_succ,c15)).
prop(pre_postcon,(c90,my_succ,c20)).
prop(pre_postcon,(c90,my_succ,c25)).
prop(pre_postcon,(c90,my_succ,c30)).
prop(pre_postcon,(c90,my_succ,c35)).
prop(pre_postcon,(c90,my_succ,c40)).
prop(pre_postcon,(c90,my_succ,c45)).
prop(pre_postcon,(c90,my_succ,c5)).
prop(pre_postcon,(c90,my_succ,c50)).
prop(pre_postcon,(c90,my_succ,c55)).
prop(pre_postcon,(c90,my_succ,c60)).
prop(pre_postcon,(c90,my_succ,c65)).
prop(pre_postcon,(c90,my_succ,c70)).
prop(pre_postcon,(c90,my_succ,c75)).
prop(pre_postcon,(c90,my_succ,c80)).
prop(pre_postcon,(c90,my_succ,c85)).
prop(pre_postcon,(c90,my_succ,c90)).
prop(pre_postcon,(c95,my_succ,c10)).
prop(pre_postcon,(c95,my_succ,c15)).
prop(pre_postcon,(c95,my_succ,c20)).
prop(pre_postcon,(c95,my_succ,c25)).
prop(pre_postcon,(c95,my_succ,c30)).
prop(pre_postcon,(c95,my_succ,c35)).
prop(pre_postcon,(c95,my_succ,c40)).
prop(pre_postcon,(c95,my_succ,c45)).
prop(pre_postcon,(c95,my_succ,c5)).
prop(pre_postcon,(c95,my_succ,c50)).
prop(pre_postcon,(c95,my_succ,c55)).
prop(pre_postcon,(c95,my_succ,c60)).
prop(pre_postcon,(c95,my_succ,c65)).
prop(pre_postcon,(c95,my_succ,c70)).
prop(pre_postcon,(c95,my_succ,c75)).
prop(pre_postcon,(c95,my_succ,c80)).
prop(pre_postcon,(c95,my_succ,c85)).
prop(pre_postcon,(c95,my_succ,c90)).
prop(pre_postcon,(c95,my_succ,c95)).
prop(pre_postcon,(my_true_claim_made_by,does,end_game)).
prop(pre_postcon,(my_true_claim_made_by,does,lay_claim)).
prop(pre_postcon,(my_true_claim_made_by,my_true_score,c10)).
prop(pre_postcon,(my_true_claim_made_by,my_true_score,c100)).
prop(pre_postcon,(my_true_claim_made_by,my_true_score,c15)).
prop(pre_postcon,(my_true_claim_made_by,my_true_score,c20)).
prop(pre_postcon,(my_true_claim_made_by,my_true_score,c25)).
prop(pre_postcon,(my_true_claim_made_by,my_true_score,c30)).
prop(pre_postcon,(my_true_claim_made_by,my_true_score,c35)).
prop(pre_postcon,(my_true_claim_made_by,my_true_score,c40)).
prop(pre_postcon,(my_true_claim_made_by,my_true_score,c45)).
prop(pre_postcon,(my_true_claim_made_by,my_true_score,c5)).
prop(pre_postcon,(my_true_claim_made_by,my_true_score,c50)).
prop(pre_postcon,(my_true_claim_made_by,my_true_score,c80)).
prop(pre_postcon,(my_true_claim_made_by,my_true_score,c85)).
prop(pre_postcon,(my_true_claim_made_by,my_true_score,c90)).
prop(pre_postcon,(my_true_claim_made_by,my_true_score,c95)).
prop(pre_postcon,(my_true_claim_made_by,next_score,c10)).
prop(pre_postcon,(my_true_claim_made_by,next_score,c100)).
prop(pre_postcon,(my_true_claim_made_by,next_score,c15)).
prop(pre_postcon,(my_true_claim_made_by,next_score,c20)).
prop(pre_postcon,(my_true_claim_made_by,next_score,c25)).
prop(pre_postcon,(my_true_claim_made_by,next_score,c30)).
prop(pre_postcon,(my_true_claim_made_by,next_score,c35)).
prop(pre_postcon,(my_true_claim_made_by,next_score,c40)).
prop(pre_postcon,(my_true_claim_made_by,next_score,c45)).
prop(pre_postcon,(my_true_claim_made_by,next_score,c5)).
prop(pre_postcon,(my_true_claim_made_by,next_score,c50)).
prop(pre_postcon,(my_true_claim_made_by,next_score,c55)).
prop(pre_postcon,(my_true_claim_made_by,next_score,c60)).
prop(pre_postcon,(my_true_claim_made_by,next_score,c65)).
prop(pre_postcon,(my_true_claim_made_by,next_score,c70)).
prop(pre_postcon,(my_true_claim_made_by,next_score,c75)).
prop(pre_postcon,(my_true_claim_made_by,next_score,c80)).
prop(pre_postcon,(my_true_claim_made_by,next_score,c85)).
prop(pre_postcon,(my_true_claim_made_by,next_score,c90)).
prop(pre_postcon,(my_true_claim_made_by,next_score,c95)).
prop(pre_postcon,(my_true_claim_made_by,opponent,my_true_claim_made_by)).
prop(pre_postcon,(my_true_claim_made_by,opponent,my_true_gameOver)).
prop(pre_postcon,(my_true_control,does,noop)).
prop(pre_postcon,(my_true_control,my_true_score,c10)).
prop(pre_postcon,(my_true_control,my_true_score,c15)).
prop(pre_postcon,(my_true_control,my_true_score,c20)).
prop(pre_postcon,(my_true_control,my_true_score,c25)).
prop(pre_postcon,(my_true_control,my_true_score,c30)).
prop(pre_postcon,(my_true_control,my_true_score,c35)).
prop(pre_postcon,(my_true_control,my_true_score,c40)).
prop(pre_postcon,(my_true_control,my_true_score,c45)).
prop(pre_postcon,(my_true_control,my_true_score,c5)).
prop(pre_postcon,(my_true_control,my_true_score,c50)).
prop(pre_postcon,(my_true_control,my_true_score,c55)).
prop(pre_postcon,(my_true_control,my_true_score,c85)).
prop(pre_postcon,(my_true_control,next_score,c10)).
prop(pre_postcon,(my_true_control,next_score,c100)).
prop(pre_postcon,(my_true_control,next_score,c15)).
prop(pre_postcon,(my_true_control,next_score,c20)).
prop(pre_postcon,(my_true_control,next_score,c25)).
prop(pre_postcon,(my_true_control,next_score,c30)).
prop(pre_postcon,(my_true_control,next_score,c35)).
prop(pre_postcon,(my_true_control,next_score,c40)).
prop(pre_postcon,(my_true_control,next_score,c45)).
prop(pre_postcon,(my_true_control,next_score,c5)).
prop(pre_postcon,(my_true_control,next_score,c50)).
prop(pre_postcon,(my_true_control,next_score,c55)).
prop(pre_postcon,(my_true_control,next_score,c60)).
prop(pre_postcon,(my_true_control,next_score,c65)).
prop(pre_postcon,(my_true_control,next_score,c70)).
prop(pre_postcon,(my_true_control,next_score,c75)).
prop(pre_postcon,(my_true_control,next_score,c80)).
prop(pre_postcon,(my_true_control,next_score,c85)).
prop(pre_postcon,(my_true_control,next_score,c90)).
prop(pre_postcon,(my_true_control,next_score,c95)).
prop(pre_postcon,(my_true_control,opponent,my_true_control)).
prop(pre_postcon,(my_true_gameOver,does,end_game)).
prop(pre_postcon,(my_true_gameOver,does,lay_claim)).
prop(pre_postcon,(my_true_gameOver,does,noop)).
prop(pre_postcon,(my_true_gameOver,my_true_score,c10)).
prop(pre_postcon,(my_true_gameOver,my_true_score,c15)).
prop(pre_postcon,(my_true_gameOver,my_true_score,c20)).
prop(pre_postcon,(my_true_gameOver,my_true_score,c25)).
prop(pre_postcon,(my_true_gameOver,my_true_score,c30)).
prop(pre_postcon,(my_true_gameOver,my_true_score,c35)).
prop(pre_postcon,(my_true_gameOver,my_true_score,c40)).
prop(pre_postcon,(my_true_gameOver,my_true_score,c45)).
prop(pre_postcon,(my_true_gameOver,my_true_score,c5)).
prop(pre_postcon,(my_true_gameOver,my_true_score,c50)).
prop(pre_postcon,(my_true_gameOver,my_true_score,c55)).
prop(pre_postcon,(my_true_gameOver,my_true_score,c85)).
prop(pre_postcon,(my_true_gameOver,next_score,c10)).
prop(pre_postcon,(my_true_gameOver,next_score,c100)).
prop(pre_postcon,(my_true_gameOver,next_score,c15)).
prop(pre_postcon,(my_true_gameOver,next_score,c20)).
prop(pre_postcon,(my_true_gameOver,next_score,c25)).
prop(pre_postcon,(my_true_gameOver,next_score,c30)).
prop(pre_postcon,(my_true_gameOver,next_score,c35)).
prop(pre_postcon,(my_true_gameOver,next_score,c40)).
prop(pre_postcon,(my_true_gameOver,next_score,c45)).
prop(pre_postcon,(my_true_gameOver,next_score,c5)).
prop(pre_postcon,(my_true_gameOver,next_score,c50)).
prop(pre_postcon,(my_true_gameOver,next_score,c55)).
prop(pre_postcon,(my_true_gameOver,next_score,c60)).
prop(pre_postcon,(my_true_gameOver,next_score,c65)).
prop(pre_postcon,(my_true_gameOver,next_score,c70)).
prop(pre_postcon,(my_true_gameOver,next_score,c75)).
prop(pre_postcon,(my_true_gameOver,next_score,c80)).
prop(pre_postcon,(my_true_gameOver,next_score,c85)).
prop(pre_postcon,(my_true_gameOver,next_score,c90)).
prop(pre_postcon,(my_true_gameOver,next_score,c95)).
prop(pre_postcon,(my_true_gameOver,opponent,my_true_claim_made_by)).
prop(pre_postcon,(white,my_true_score,c10)).
prop(pre_postcon,(white,my_true_score,c100)).
prop(pre_postcon,(white,my_true_score,c15)).
prop(pre_postcon,(white,my_true_score,c20)).
prop(pre_postcon,(white,my_true_score,c25)).
prop(pre_postcon,(white,my_true_score,c30)).
prop(pre_postcon,(white,my_true_score,c35)).
prop(pre_postcon,(white,my_true_score,c40)).
prop(pre_postcon,(white,my_true_score,c45)).
prop(pre_postcon,(white,my_true_score,c5)).
prop(pre_postcon,(white,my_true_score,c50)).
prop(pre_postcon,(white,my_true_score,c85)).
prop(pre_postcon,(white,next_score,c10)).
prop(pre_postcon,(white,next_score,c100)).
prop(pre_postcon,(white,next_score,c15)).
prop(pre_postcon,(white,next_score,c20)).
prop(pre_postcon,(white,next_score,c25)).
prop(pre_postcon,(white,next_score,c30)).
prop(pre_postcon,(white,next_score,c35)).
prop(pre_postcon,(white,next_score,c40)).
prop(pre_postcon,(white,next_score,c45)).
prop(pre_postcon,(white,next_score,c5)).
prop(pre_postcon,(white,next_score,c50)).
prop(pre_postcon,(white,next_score,c55)).
prop(pre_postcon,(white,next_score,c60)).
prop(pre_postcon,(white,next_score,c65)).
prop(pre_postcon,(white,next_score,c70)).
prop(pre_postcon,(white,next_score,c75)).
prop(pre_postcon,(white,next_score,c80)).
prop(pre_postcon,(white,next_score,c85)).
prop(pre_postcon,(white,next_score,c90)).
prop(pre_postcon,(white,next_score,c95)).
prop(pre_postcon,(white,opponent,white)).
prop(precon,(c100,my_succ)).
prop(precon,(my_true_gameOver,does)).
prop(singleton,black).
prop(singleton,c10).
prop(singleton,c100).
prop(singleton,c15).
prop(singleton,c20).
prop(singleton,c25).
prop(singleton,c30).
prop(singleton,c35).
prop(singleton,c40).
prop(singleton,c45).
prop(singleton,c5).
prop(singleton,c50).
prop(singleton,c55).
prop(singleton,c60).
prop(singleton,c65).
prop(singleton,c70).
prop(singleton,c75).
prop(singleton,c80).
prop(singleton,c85).
prop(singleton,c90).
prop(singleton,c95).
prop(singleton,end_game).
prop(singleton,lay_claim).
prop(singleton,my_true_control).
prop(singleton,noop).
prop(singleton,white).
prop(symmetric_ab,opponent).
prop(unique_a_b,does).
prop(unique_a_b,my_succ).
prop(unique_a_b,my_true_score).
prop(unique_a_b,opponent).
prop(unique_b_a,does).
prop(unique_b_a,my_succ).
prop(unique_b_a,opponent).
prop(countk,black,1).
prop(countk,c10,1).
prop(countk,c100,1).
prop(countk,c15,1).
prop(countk,c20,1).
prop(countk,c25,1).
prop(countk,c30,1).
prop(countk,c35,1).
prop(countk,c40,1).
prop(countk,c45,1).
prop(countk,c5,1).
prop(countk,c50,1).
prop(countk,c55,1).
prop(countk,c60,1).
prop(countk,c65,1).
prop(countk,c70,1).
prop(countk,c75,1).
prop(countk,c80,1).
prop(countk,c85,1).
prop(countk,c90,1).
prop(countk,c95,1).
prop(countk,end_game,1).
prop(countk,lay_claim,1).
prop(countk,my_true_control,1).
prop(countk,my_true_score,2).
prop(countk,noop,1).
prop(countk,opponent,2).
prop(countk,white,1).
prop(unsat_pair,c100,c10).
prop(unsat_pair,c15,c10).
prop(unsat_pair,c15,c100).
prop(unsat_pair,c20,c10).
prop(unsat_pair,c20,c100).
prop(unsat_pair,c20,c15).
prop(unsat_pair,c25,c10).
prop(unsat_pair,c25,c100).
prop(unsat_pair,c25,c15).
prop(unsat_pair,c25,c20).
prop(unsat_pair,c30,c10).
prop(unsat_pair,c30,c100).
prop(unsat_pair,c30,c15).
prop(unsat_pair,c30,c20).
prop(unsat_pair,c30,c25).
prop(unsat_pair,c35,c10).
prop(unsat_pair,c35,c100).
prop(unsat_pair,c35,c15).
prop(unsat_pair,c35,c20).
prop(unsat_pair,c35,c25).
prop(unsat_pair,c35,c30).
prop(unsat_pair,c40,c10).
prop(unsat_pair,c40,c100).
prop(unsat_pair,c40,c15).
prop(unsat_pair,c40,c20).
prop(unsat_pair,c40,c25).
prop(unsat_pair,c40,c30).
prop(unsat_pair,c40,c35).
prop(unsat_pair,c45,c10).
prop(unsat_pair,c45,c100).
prop(unsat_pair,c45,c15).
prop(unsat_pair,c45,c20).
prop(unsat_pair,c45,c25).
prop(unsat_pair,c45,c30).
prop(unsat_pair,c45,c35).
prop(unsat_pair,c45,c40).
prop(unsat_pair,c5,c10).
prop(unsat_pair,c5,c100).
prop(unsat_pair,c5,c15).
prop(unsat_pair,c5,c20).
prop(unsat_pair,c5,c25).
prop(unsat_pair,c5,c30).
prop(unsat_pair,c5,c35).
prop(unsat_pair,c5,c40).
prop(unsat_pair,c5,c45).
prop(unsat_pair,c50,c10).
prop(unsat_pair,c50,c100).
prop(unsat_pair,c50,c15).
prop(unsat_pair,c50,c20).
prop(unsat_pair,c50,c25).
prop(unsat_pair,c50,c30).
prop(unsat_pair,c50,c35).
prop(unsat_pair,c50,c40).
prop(unsat_pair,c50,c45).
prop(unsat_pair,c50,c5).
prop(unsat_pair,c55,c10).
prop(unsat_pair,c55,c100).
prop(unsat_pair,c55,c15).
prop(unsat_pair,c55,c20).
prop(unsat_pair,c55,c25).
prop(unsat_pair,c55,c30).
prop(unsat_pair,c55,c35).
prop(unsat_pair,c55,c40).
prop(unsat_pair,c55,c45).
prop(unsat_pair,c55,c5).
prop(unsat_pair,c55,c50).
prop(unsat_pair,c60,c10).
prop(unsat_pair,c60,c100).
prop(unsat_pair,c60,c15).
prop(unsat_pair,c60,c20).
prop(unsat_pair,c60,c25).
prop(unsat_pair,c60,c30).
prop(unsat_pair,c60,c35).
prop(unsat_pair,c60,c40).
prop(unsat_pair,c60,c45).
prop(unsat_pair,c60,c5).
prop(unsat_pair,c60,c50).
prop(unsat_pair,c60,c55).
prop(unsat_pair,c65,c10).
prop(unsat_pair,c65,c100).
prop(unsat_pair,c65,c15).
prop(unsat_pair,c65,c20).
prop(unsat_pair,c65,c25).
prop(unsat_pair,c65,c30).
prop(unsat_pair,c65,c35).
prop(unsat_pair,c65,c40).
prop(unsat_pair,c65,c45).
prop(unsat_pair,c65,c5).
prop(unsat_pair,c65,c50).
prop(unsat_pair,c65,c55).
prop(unsat_pair,c65,c60).
prop(unsat_pair,c70,c10).
prop(unsat_pair,c70,c100).
prop(unsat_pair,c70,c15).
prop(unsat_pair,c70,c20).
prop(unsat_pair,c70,c25).
prop(unsat_pair,c70,c30).
prop(unsat_pair,c70,c35).
prop(unsat_pair,c70,c40).
prop(unsat_pair,c70,c45).
prop(unsat_pair,c70,c5).
prop(unsat_pair,c70,c50).
prop(unsat_pair,c70,c55).
prop(unsat_pair,c70,c60).
prop(unsat_pair,c70,c65).
prop(unsat_pair,c75,c10).
prop(unsat_pair,c75,c100).
prop(unsat_pair,c75,c15).
prop(unsat_pair,c75,c20).
prop(unsat_pair,c75,c25).
prop(unsat_pair,c75,c30).
prop(unsat_pair,c75,c35).
prop(unsat_pair,c75,c40).
prop(unsat_pair,c75,c45).
prop(unsat_pair,c75,c5).
prop(unsat_pair,c75,c50).
prop(unsat_pair,c75,c55).
prop(unsat_pair,c75,c60).
prop(unsat_pair,c75,c65).
prop(unsat_pair,c75,c70).
prop(unsat_pair,c80,c10).
prop(unsat_pair,c80,c100).
prop(unsat_pair,c80,c15).
prop(unsat_pair,c80,c20).
prop(unsat_pair,c80,c25).
prop(unsat_pair,c80,c30).
prop(unsat_pair,c80,c35).
prop(unsat_pair,c80,c40).
prop(unsat_pair,c80,c45).
prop(unsat_pair,c80,c5).
prop(unsat_pair,c80,c50).
prop(unsat_pair,c80,c55).
prop(unsat_pair,c80,c60).
prop(unsat_pair,c80,c65).
prop(unsat_pair,c80,c70).
prop(unsat_pair,c80,c75).
prop(unsat_pair,c85,c10).
prop(unsat_pair,c85,c100).
prop(unsat_pair,c85,c15).
prop(unsat_pair,c85,c20).
prop(unsat_pair,c85,c25).
prop(unsat_pair,c85,c30).
prop(unsat_pair,c85,c35).
prop(unsat_pair,c85,c40).
prop(unsat_pair,c85,c45).
prop(unsat_pair,c85,c5).
prop(unsat_pair,c85,c50).
prop(unsat_pair,c85,c55).
prop(unsat_pair,c85,c60).
prop(unsat_pair,c85,c65).
prop(unsat_pair,c85,c70).
prop(unsat_pair,c85,c75).
prop(unsat_pair,c85,c80).
prop(unsat_pair,c90,c10).
prop(unsat_pair,c90,c100).
prop(unsat_pair,c90,c15).
prop(unsat_pair,c90,c20).
prop(unsat_pair,c90,c25).
prop(unsat_pair,c90,c30).
prop(unsat_pair,c90,c35).
prop(unsat_pair,c90,c40).
prop(unsat_pair,c90,c45).
prop(unsat_pair,c90,c5).
prop(unsat_pair,c90,c50).
prop(unsat_pair,c90,c55).
prop(unsat_pair,c90,c60).
prop(unsat_pair,c90,c65).
prop(unsat_pair,c90,c70).
prop(unsat_pair,c90,c75).
prop(unsat_pair,c90,c80).
prop(unsat_pair,c90,c85).
prop(unsat_pair,c95,c10).
prop(unsat_pair,c95,c100).
prop(unsat_pair,c95,c15).
prop(unsat_pair,c95,c20).
prop(unsat_pair,c95,c25).
prop(unsat_pair,c95,c30).
prop(unsat_pair,c95,c35).
prop(unsat_pair,c95,c40).
prop(unsat_pair,c95,c45).
prop(unsat_pair,c95,c5).
prop(unsat_pair,c95,c50).
prop(unsat_pair,c95,c55).
prop(unsat_pair,c95,c60).
prop(unsat_pair,c95,c65).
prop(unsat_pair,c95,c70).
prop(unsat_pair,c95,c75).
prop(unsat_pair,c95,c80).
prop(unsat_pair,c95,c85).
prop(unsat_pair,c95,c90).
prop(unsat_pair,lay_claim,end_game).
prop(unsat_pair,my_true_control,my_true_claim_made_by).
prop(unsat_pair,my_true_gameOver,my_true_claim_made_by).
prop(unsat_pair,noop,end_game).
prop(unsat_pair,noop,lay_claim).
prop(unsat_pair,white,black).
prop(countk,my_true_gameOver,2).
