does(1,black,noop).
does(1,white,lay_claim).
does(10,black,noop).
does(10,white,lay_claim).
does(11,black,noop).
does(11,white,end_game).
does(12,black,lay_claim).
does(12,white,noop).
does(13,black,end_game).
does(13,white,noop).
does(2,black,noop).
does(2,white,lay_claim).
does(4,black,end_game).
does(4,white,noop).
does(5,black,lay_claim).
does(5,white,noop).
does(6,black,noop).
does(6,white,end_game).
does(8,black,noop).
does(8,white,end_game).
does(9,black,noop).
does(9,white,lay_claim).
my_true_claim_made_by(1,black).
my_true_claim_made_by(10,black).
my_true_claim_made_by(11,black).
my_true_claim_made_by(12,white).
my_true_claim_made_by(13,white).
my_true_claim_made_by(2,black).
my_true_claim_made_by(4,white).
my_true_claim_made_by(5,white).
my_true_claim_made_by(6,black).
my_true_claim_made_by(9,black).
my_true_control(1,white).
my_true_control(10,white).
my_true_control(11,white).
my_true_control(12,black).
my_true_control(13,black).
my_true_control(14,white).
my_true_control(15,black).
my_true_control(16,white).
my_true_control(2,white).
my_true_control(3,white).
my_true_control(4,black).
my_true_control(5,black).
my_true_control(6,white).
my_true_control(7,black).
my_true_control(8,white).
my_true_control(9,white).
my_true_score(1,black,60).
my_true_score(1,white,60).
my_true_score(10,black,65).
my_true_score(10,white,65).
my_true_score(11,black,70).
my_true_score(11,white,70).
my_true_score(12,black,75).
my_true_score(12,white,70).
my_true_score(13,black,70).
my_true_score(13,white,65).
my_true_score(14,black,75).
my_true_score(14,white,95).
my_true_score(15,black,90).
my_true_score(15,white,65).
my_true_score(16,black,60).
my_true_score(16,white,80).
my_true_score(2,black,70).
my_true_score(2,white,70).
my_true_score(3,black,70).
my_true_score(3,white,90).
my_true_score(4,black,60).
my_true_score(4,white,55).
my_true_score(5,black,80).
my_true_score(5,white,75).
my_true_score(6,black,65).
my_true_score(6,white,65).
my_true_score(7,black,100).
my_true_score(7,white,75).
my_true_score(8,black,80).
my_true_score(8,white,80).
my_true_score(9,black,75).
my_true_score(9,white,75).
