#T1
neg(next_score(black,10)).
neg(next_score(white,15)).
neg(next_score(white,65)).
neg(next_score(white,75)).
neg(next_score(black,35)).
neg(next_score(black,30)).
neg(next_score(black,20)).
neg(next_score(white,25)).
neg(next_score(black,0)).
neg(next_score(black,95)).
neg(next_score(white,90)).
neg(next_score(white,95)).
neg(next_score(white,40)).
neg(next_score(white,100)).
neg(next_score(white,70)).
neg(next_score(black,80)).
neg(next_score(white,20)).
neg(next_score(white,45)).
neg(next_score(white,60)).
neg(next_score(black,50)).
neg(next_score(black,45)).
neg(next_score(black,15)).
neg(next_score(black,25)).
neg(next_score(white,35)).
neg(next_score(white,30)).
neg(next_score(white,0)).
neg(next_score(black,5)).
neg(next_score(black,65)).
neg(next_score(white,50)).
neg(next_score(white,5)).
neg(next_score(black,40)).
neg(next_score(white,10)).
neg(next_score(white,85)).
neg(next_score(white,80)).
pos(next_score(black,60)).
neg(next_score(black,70)).
neg(next_score(black,55)).
neg(next_score(black,75)).
neg(next_score(black,85)).
neg(next_score(black,100)).
neg(next_score(black,90)).
pos(next_score(white,55)).

#T10
neg(next_score(black,10)).
neg(next_score(white,15)).
neg(next_score(white,65)).
pos(next_score(white,60)).
neg(next_score(white,75)).
neg(next_score(black,35)).
neg(next_score(black,30)).
neg(next_score(black,20)).
neg(next_score(white,25)).
neg(next_score(black,0)).
neg(next_score(black,95)).
neg(next_score(white,90)).
neg(next_score(white,95)).
neg(next_score(white,40)).
neg(next_score(white,100)).
neg(next_score(white,70)).
neg(next_score(black,80)).
neg(next_score(white,20)).
neg(next_score(white,45)).
pos(next_score(black,65)).
neg(next_score(black,60)).
neg(next_score(black,50)).
neg(next_score(black,45)).
neg(next_score(black,15)).
neg(next_score(black,25)).
neg(next_score(white,35)).
neg(next_score(white,30)).
neg(next_score(white,0)).
neg(next_score(black,5)).
neg(next_score(white,50)).
neg(next_score(white,5)).
neg(next_score(black,40)).
neg(next_score(white,10)).
neg(next_score(white,85)).
neg(next_score(white,80)).
neg(next_score(black,70)).
neg(next_score(black,55)).
neg(next_score(black,75)).
neg(next_score(black,85)).
neg(next_score(black,100)).
neg(next_score(black,90)).
neg(next_score(white,55)).

#T11
neg(next_score(black,10)).
neg(next_score(white,15)).
neg(next_score(white,65)).
pos(next_score(white,70)).
neg(next_score(white,75)).
neg(next_score(black,35)).
neg(next_score(black,30)).
neg(next_score(black,20)).
neg(next_score(white,25)).
neg(next_score(black,0)).
neg(next_score(white,90)).
neg(next_score(white,95)).
neg(next_score(white,40)).
neg(next_score(white,100)).
neg(next_score(black,80)).
neg(next_score(white,20)).
neg(next_score(white,45)).
neg(next_score(white,60)).
neg(next_score(black,60)).
neg(next_score(black,50)).
neg(next_score(black,45)).
neg(next_score(black,15)).
neg(next_score(black,25)).
neg(next_score(white,35)).
neg(next_score(white,30)).
neg(next_score(white,0)).
neg(next_score(black,5)).
neg(next_score(black,65)).
pos(next_score(black,95)).
neg(next_score(white,50)).
neg(next_score(white,5)).
neg(next_score(black,40)).
neg(next_score(white,10)).
neg(next_score(white,85)).
neg(next_score(white,80)).
neg(next_score(black,70)).
neg(next_score(black,55)).
neg(next_score(black,75)).
neg(next_score(black,85)).
neg(next_score(black,100)).
neg(next_score(black,90)).
neg(next_score(white,55)).

#T12
neg(next_score(black,10)).
neg(next_score(white,15)).
neg(next_score(white,65)).
pos(next_score(white,70)).
neg(next_score(white,75)).
neg(next_score(black,35)).
neg(next_score(black,30)).
neg(next_score(black,20)).
neg(next_score(white,25)).
neg(next_score(black,0)).
pos(next_score(black,70)).
neg(next_score(black,95)).
neg(next_score(white,90)).
neg(next_score(white,95)).
neg(next_score(white,40)).
neg(next_score(white,100)).
neg(next_score(black,80)).
neg(next_score(white,20)).
neg(next_score(white,45)).
neg(next_score(white,60)).
neg(next_score(black,60)).
neg(next_score(black,50)).
neg(next_score(black,45)).
neg(next_score(black,15)).
neg(next_score(black,25)).
neg(next_score(white,35)).
neg(next_score(white,30)).
neg(next_score(white,0)).
neg(next_score(black,5)).
neg(next_score(black,65)).
neg(next_score(white,50)).
neg(next_score(white,5)).
neg(next_score(black,40)).
neg(next_score(white,10)).
neg(next_score(white,85)).
neg(next_score(white,80)).
neg(next_score(black,55)).
neg(next_score(black,75)).
neg(next_score(black,85)).
neg(next_score(black,100)).
neg(next_score(black,90)).
neg(next_score(white,55)).

#T13
neg(next_score(black,10)).
neg(next_score(white,15)).
neg(next_score(white,65)).
neg(next_score(white,75)).
neg(next_score(black,35)).
neg(next_score(black,30)).
neg(next_score(black,20)).
neg(next_score(white,25)).
neg(next_score(black,0)).
pos(next_score(black,70)).
neg(next_score(black,95)).
neg(next_score(white,95)).
neg(next_score(white,40)).
neg(next_score(white,100)).
neg(next_score(white,70)).
neg(next_score(black,80)).
neg(next_score(white,20)).
neg(next_score(white,45)).
neg(next_score(white,60)).
neg(next_score(black,60)).
pos(next_score(white,90)).
neg(next_score(black,50)).
neg(next_score(black,45)).
neg(next_score(black,15)).
neg(next_score(black,25)).
neg(next_score(white,35)).
neg(next_score(white,30)).
neg(next_score(white,0)).
neg(next_score(black,5)).
neg(next_score(black,65)).
neg(next_score(white,50)).
neg(next_score(white,5)).
neg(next_score(black,40)).
neg(next_score(white,10)).
neg(next_score(white,85)).
neg(next_score(white,80)).
neg(next_score(black,55)).
neg(next_score(black,75)).
neg(next_score(black,85)).
neg(next_score(black,100)).
neg(next_score(black,90)).
neg(next_score(white,55)).

#T2
neg(next_score(black,10)).
neg(next_score(white,15)).
neg(next_score(white,75)).
neg(next_score(black,35)).
neg(next_score(black,30)).
neg(next_score(black,20)).
neg(next_score(white,25)).
neg(next_score(black,0)).
pos(next_score(black,70)).
neg(next_score(black,95)).
neg(next_score(white,90)).
neg(next_score(white,95)).
neg(next_score(white,40)).
neg(next_score(white,100)).
neg(next_score(white,70)).
neg(next_score(black,80)).
neg(next_score(white,20)).
neg(next_score(white,45)).
neg(next_score(white,60)).
neg(next_score(black,60)).
neg(next_score(black,50)).
neg(next_score(black,45)).
neg(next_score(black,15)).
neg(next_score(black,25)).
neg(next_score(white,35)).
neg(next_score(white,30)).
neg(next_score(white,0)).
neg(next_score(black,5)).
neg(next_score(black,65)).
neg(next_score(white,50)).
neg(next_score(white,5)).
neg(next_score(black,40)).
neg(next_score(white,10)).
neg(next_score(white,85)).
neg(next_score(white,80)).
neg(next_score(black,55)).
neg(next_score(black,75)).
neg(next_score(black,85)).
neg(next_score(black,100)).
neg(next_score(black,90)).
pos(next_score(white,65)).
neg(next_score(white,55)).

#T4
neg(next_score(black,10)).
neg(next_score(white,15)).
pos(next_score(white,80)).
neg(next_score(white,65)).
neg(next_score(white,75)).
neg(next_score(black,35)).
neg(next_score(black,30)).
neg(next_score(black,20)).
neg(next_score(white,25)).
neg(next_score(black,0)).
neg(next_score(black,95)).
neg(next_score(white,90)).
neg(next_score(white,95)).
neg(next_score(white,40)).
neg(next_score(white,100)).
neg(next_score(white,70)).
neg(next_score(black,80)).
neg(next_score(white,20)).
neg(next_score(white,45)).
neg(next_score(white,60)).
neg(next_score(black,50)).
neg(next_score(black,45)).
neg(next_score(black,15)).
neg(next_score(black,25)).
neg(next_score(white,35)).
neg(next_score(white,30)).
neg(next_score(white,0)).
neg(next_score(black,5)).
neg(next_score(black,65)).
neg(next_score(white,50)).
neg(next_score(white,5)).
neg(next_score(black,40)).
neg(next_score(white,10)).
neg(next_score(white,85)).
pos(next_score(black,60)).
neg(next_score(black,70)).
neg(next_score(black,55)).
neg(next_score(black,75)).
neg(next_score(black,85)).
neg(next_score(black,100)).
neg(next_score(black,90)).
neg(next_score(white,55)).

#T5
pos(next_score(black,75)).
neg(next_score(black,10)).
neg(next_score(white,15)).
neg(next_score(white,65)).
neg(next_score(black,35)).
pos(next_score(white,75)).
neg(next_score(black,30)).
neg(next_score(black,20)).
neg(next_score(white,25)).
neg(next_score(black,0)).
neg(next_score(black,95)).
neg(next_score(white,90)).
neg(next_score(white,95)).
neg(next_score(white,40)).
neg(next_score(white,100)).
neg(next_score(white,70)).
neg(next_score(black,80)).
neg(next_score(white,20)).
neg(next_score(white,45)).
neg(next_score(white,60)).
neg(next_score(black,60)).
neg(next_score(black,50)).
neg(next_score(black,45)).
neg(next_score(black,15)).
neg(next_score(black,25)).
neg(next_score(white,35)).
neg(next_score(white,30)).
neg(next_score(white,0)).
neg(next_score(black,5)).
neg(next_score(black,65)).
neg(next_score(white,50)).
neg(next_score(white,5)).
neg(next_score(black,40)).
neg(next_score(white,10)).
neg(next_score(white,85)).
neg(next_score(white,80)).
neg(next_score(black,70)).
neg(next_score(black,55)).
neg(next_score(black,85)).
neg(next_score(black,100)).
neg(next_score(black,90)).
neg(next_score(white,55)).

#T6
neg(next_score(black,10)).
neg(next_score(white,15)).
neg(next_score(white,75)).
neg(next_score(black,35)).
neg(next_score(black,30)).
neg(next_score(black,20)).
neg(next_score(white,25)).
neg(next_score(black,0)).
neg(next_score(black,95)).
neg(next_score(white,90)).
neg(next_score(white,95)).
neg(next_score(white,40)).
neg(next_score(white,100)).
neg(next_score(white,70)).
neg(next_score(black,80)).
neg(next_score(white,20)).
neg(next_score(white,45)).
neg(next_score(white,60)).
neg(next_score(black,60)).
neg(next_score(black,50)).
neg(next_score(black,45)).
neg(next_score(black,15)).
neg(next_score(black,25)).
neg(next_score(white,35)).
neg(next_score(white,30)).
neg(next_score(white,0)).
neg(next_score(black,5)).
neg(next_score(black,65)).
neg(next_score(white,50)).
neg(next_score(white,5)).
neg(next_score(black,40)).
neg(next_score(white,10)).
neg(next_score(white,85)).
neg(next_score(white,80)).
pos(next_score(black,90)).
neg(next_score(black,70)).
neg(next_score(black,55)).
neg(next_score(black,75)).
neg(next_score(black,85)).
neg(next_score(black,100)).
pos(next_score(white,65)).
neg(next_score(white,55)).

#T8
neg(next_score(black,10)).
neg(next_score(white,15)).
pos(next_score(white,80)).
neg(next_score(white,65)).
neg(next_score(white,75)).
neg(next_score(black,35)).
neg(next_score(black,30)).
neg(next_score(black,20)).
neg(next_score(white,25)).
neg(next_score(black,0)).
neg(next_score(black,95)).
neg(next_score(white,90)).
neg(next_score(white,95)).
neg(next_score(white,40)).
neg(next_score(white,100)).
neg(next_score(white,70)).
neg(next_score(white,20)).
neg(next_score(white,45)).
neg(next_score(white,60)).
neg(next_score(black,60)).
neg(next_score(black,50)).
neg(next_score(black,45)).
pos(next_score(black,80)).
neg(next_score(black,15)).
neg(next_score(black,25)).
neg(next_score(white,35)).
neg(next_score(white,30)).
neg(next_score(white,0)).
neg(next_score(black,5)).
neg(next_score(black,65)).
neg(next_score(white,50)).
neg(next_score(white,5)).
neg(next_score(black,40)).
neg(next_score(white,10)).
neg(next_score(white,85)).
neg(next_score(black,70)).
neg(next_score(black,55)).
neg(next_score(black,75)).
neg(next_score(black,85)).
neg(next_score(black,100)).
neg(next_score(black,90)).
neg(next_score(white,55)).

#T9
pos(next_score(black,75)).
neg(next_score(black,10)).
neg(next_score(white,15)).
pos(next_score(white,70)).
neg(next_score(white,65)).
neg(next_score(white,75)).
neg(next_score(black,35)).
neg(next_score(black,30)).
neg(next_score(black,20)).
neg(next_score(white,25)).
neg(next_score(black,0)).
neg(next_score(black,95)).
neg(next_score(white,90)).
neg(next_score(white,95)).
neg(next_score(white,40)).
neg(next_score(white,100)).
neg(next_score(black,80)).
neg(next_score(white,20)).
neg(next_score(white,45)).
neg(next_score(white,60)).
neg(next_score(black,60)).
neg(next_score(black,50)).
neg(next_score(black,45)).
neg(next_score(black,15)).
neg(next_score(black,25)).
neg(next_score(white,35)).
neg(next_score(white,30)).
neg(next_score(white,0)).
neg(next_score(black,5)).
neg(next_score(black,65)).
neg(next_score(white,50)).
neg(next_score(white,5)).
neg(next_score(black,40)).
neg(next_score(white,10)).
neg(next_score(white,85)).
neg(next_score(white,80)).
neg(next_score(black,70)).
neg(next_score(black,55)).
neg(next_score(black,85)).
neg(next_score(black,100)).
neg(next_score(black,90)).
neg(next_score(white,55)).

#T14
neg(next_score(black,10)).
neg(next_score(white,15)).
neg(next_score(white,65)).
neg(next_score(white,75)).
neg(next_score(black,35)).
neg(next_score(black,30)).
neg(next_score(black,20)).
neg(next_score(white,25)).
neg(next_score(black,0)).
neg(next_score(black,95)).
neg(next_score(white,90)).
neg(next_score(white,95)).
neg(next_score(white,40)).
neg(next_score(white,100)).
neg(next_score(white,70)).
neg(next_score(black,80)).
neg(next_score(white,20)).
neg(next_score(white,45)).
neg(next_score(white,60)).
neg(next_score(black,60)).
neg(next_score(black,50)).
neg(next_score(black,45)).
neg(next_score(black,15)).
neg(next_score(black,25)).
neg(next_score(white,35)).
neg(next_score(white,30)).
neg(next_score(white,0)).
neg(next_score(black,5)).
neg(next_score(black,65)).
neg(next_score(white,50)).
neg(next_score(white,5)).
neg(next_score(black,40)).
neg(next_score(white,10)).
neg(next_score(white,85)).
neg(next_score(white,80)).
neg(next_score(black,70)).
neg(next_score(black,55)).
neg(next_score(black,75)).
neg(next_score(black,85)).
neg(next_score(black,100)).
neg(next_score(black,90)).
neg(next_score(white,55)).

#T15
neg(next_score(black,10)).
neg(next_score(white,15)).
neg(next_score(white,65)).
neg(next_score(white,75)).
neg(next_score(black,35)).
neg(next_score(black,30)).
neg(next_score(black,20)).
neg(next_score(white,25)).
neg(next_score(black,0)).
neg(next_score(black,95)).
neg(next_score(white,90)).
neg(next_score(white,95)).
neg(next_score(white,40)).
neg(next_score(white,100)).
neg(next_score(white,70)).
neg(next_score(black,80)).
neg(next_score(white,20)).
neg(next_score(white,45)).
neg(next_score(white,60)).
neg(next_score(black,60)).
neg(next_score(black,50)).
neg(next_score(black,45)).
neg(next_score(black,15)).
neg(next_score(black,25)).
neg(next_score(white,35)).
neg(next_score(white,30)).
neg(next_score(white,0)).
neg(next_score(black,5)).
neg(next_score(black,65)).
neg(next_score(white,50)).
neg(next_score(white,5)).
neg(next_score(black,40)).
neg(next_score(white,10)).
neg(next_score(white,85)).
neg(next_score(white,80)).
neg(next_score(black,70)).
neg(next_score(black,55)).
neg(next_score(black,75)).
neg(next_score(black,85)).
neg(next_score(black,100)).
neg(next_score(black,90)).
neg(next_score(white,55)).

#T16
neg(next_score(black,10)).
neg(next_score(white,15)).
neg(next_score(white,65)).
neg(next_score(white,75)).
neg(next_score(black,35)).
neg(next_score(black,30)).
neg(next_score(black,20)).
neg(next_score(white,25)).
neg(next_score(black,0)).
neg(next_score(black,95)).
neg(next_score(white,90)).
neg(next_score(white,95)).
neg(next_score(white,40)).
neg(next_score(white,100)).
neg(next_score(white,70)).
neg(next_score(black,80)).
neg(next_score(white,20)).
neg(next_score(white,45)).
neg(next_score(white,60)).
neg(next_score(black,60)).
neg(next_score(black,50)).
neg(next_score(black,45)).
neg(next_score(black,15)).
neg(next_score(black,25)).
neg(next_score(white,35)).
neg(next_score(white,30)).
neg(next_score(white,0)).
neg(next_score(black,5)).
neg(next_score(black,65)).
neg(next_score(white,50)).
neg(next_score(white,5)).
neg(next_score(black,40)).
neg(next_score(white,10)).
neg(next_score(white,85)).
neg(next_score(white,80)).
neg(next_score(black,70)).
neg(next_score(black,55)).
neg(next_score(black,75)).
neg(next_score(black,85)).
neg(next_score(black,100)).
neg(next_score(black,90)).
neg(next_score(white,55)).

#T3
neg(next_score(black,10)).
neg(next_score(white,15)).
neg(next_score(white,65)).
neg(next_score(white,75)).
neg(next_score(black,35)).
neg(next_score(black,30)).
neg(next_score(black,20)).
neg(next_score(white,25)).
neg(next_score(black,0)).
neg(next_score(black,95)).
neg(next_score(white,90)).
neg(next_score(white,95)).
neg(next_score(white,40)).
neg(next_score(white,100)).
neg(next_score(white,70)).
neg(next_score(black,80)).
neg(next_score(white,20)).
neg(next_score(white,45)).
neg(next_score(white,60)).
neg(next_score(black,60)).
neg(next_score(black,50)).
neg(next_score(black,45)).
neg(next_score(black,15)).
neg(next_score(black,25)).
neg(next_score(white,35)).
neg(next_score(white,30)).
neg(next_score(white,0)).
neg(next_score(black,5)).
neg(next_score(black,65)).
neg(next_score(white,50)).
neg(next_score(white,5)).
neg(next_score(black,40)).
neg(next_score(white,10)).
neg(next_score(white,85)).
neg(next_score(white,80)).
neg(next_score(black,70)).
neg(next_score(black,55)).
neg(next_score(black,75)).
neg(next_score(black,85)).
neg(next_score(black,100)).
neg(next_score(black,90)).
neg(next_score(white,55)).

#T7
neg(next_score(black,10)).
neg(next_score(white,15)).
neg(next_score(white,65)).
neg(next_score(white,75)).
neg(next_score(black,35)).
neg(next_score(black,30)).
neg(next_score(black,20)).
neg(next_score(white,25)).
neg(next_score(black,0)).
neg(next_score(black,95)).
neg(next_score(white,90)).
neg(next_score(white,95)).
neg(next_score(white,40)).
neg(next_score(white,100)).
neg(next_score(white,70)).
neg(next_score(black,80)).
neg(next_score(white,20)).
neg(next_score(white,45)).
neg(next_score(white,60)).
neg(next_score(black,60)).
neg(next_score(black,50)).
neg(next_score(black,45)).
neg(next_score(black,15)).
neg(next_score(black,25)).
neg(next_score(white,35)).
neg(next_score(white,30)).
neg(next_score(white,0)).
neg(next_score(black,5)).
neg(next_score(black,65)).
neg(next_score(white,50)).
neg(next_score(white,5)).
neg(next_score(black,40)).
neg(next_score(white,10)).
neg(next_score(white,85)).
neg(next_score(white,80)).
neg(next_score(black,70)).
neg(next_score(black,55)).
neg(next_score(black,75)).
neg(next_score(black,85)).
neg(next_score(black,100)).
neg(next_score(black,90)).
neg(next_score(white,55)).

