% Positive examples
pos(pick(ball1,rooma,left,0)).
pos(pick(ball1,rooma,left,11)).
pos(pick(ball2,rooma,right,1)).
pos(pick(ball2,rooma,right,12)).
pos(pick(ball3,rooma,left,17)).
pos(pick(ball3,rooma,left,6)).
pos(pick(ball4,rooma,right,18)).
pos(pick(ball4,rooma,right,7)).
pos(pick(ball5,rooma,left,23)).
pos(pick(ball6,rooma,right,24)).

% Negative examples
neg(pick(ball1,rooma,left,1)).
neg(pick(ball1,rooma,left,10)).
neg(pick(ball1,rooma,left,12)).
neg(pick(ball1,rooma,left,13)).
neg(pick(ball1,rooma,left,14)).
neg(pick(ball1,rooma,left,15)).
neg(pick(ball1,rooma,left,16)).
neg(pick(ball1,rooma,left,17)).
neg(pick(ball1,rooma,left,18)).
neg(pick(ball1,rooma,left,19)).
neg(pick(ball1,rooma,left,2)).
neg(pick(ball1,rooma,left,20)).
neg(pick(ball1,rooma,left,21)).
neg(pick(ball1,rooma,left,22)).
neg(pick(ball1,rooma,left,23)).
neg(pick(ball1,rooma,left,24)).
neg(pick(ball1,rooma,left,25)).
neg(pick(ball1,rooma,left,26)).
neg(pick(ball1,rooma,left,27)).
neg(pick(ball1,rooma,left,3)).
neg(pick(ball1,rooma,left,4)).
neg(pick(ball1,rooma,left,5)).
neg(pick(ball1,rooma,left,6)).
neg(pick(ball1,rooma,left,7)).
neg(pick(ball1,rooma,left,8)).
neg(pick(ball1,rooma,left,9)).
neg(pick(ball1,rooma,right,1)).
neg(pick(ball1,rooma,right,10)).
neg(pick(ball1,rooma,right,12)).
neg(pick(ball1,rooma,right,13)).
neg(pick(ball1,rooma,right,14)).
neg(pick(ball1,rooma,right,15)).
neg(pick(ball1,rooma,right,16)).
neg(pick(ball1,rooma,right,17)).
neg(pick(ball1,rooma,right,18)).
neg(pick(ball1,rooma,right,19)).
neg(pick(ball1,rooma,right,2)).
neg(pick(ball1,rooma,right,20)).
neg(pick(ball1,rooma,right,21)).
neg(pick(ball1,rooma,right,22)).
neg(pick(ball1,rooma,right,23)).
neg(pick(ball1,rooma,right,24)).
neg(pick(ball1,rooma,right,25)).
neg(pick(ball1,rooma,right,26)).
neg(pick(ball1,rooma,right,27)).
neg(pick(ball1,rooma,right,3)).
neg(pick(ball1,rooma,right,4)).
neg(pick(ball1,rooma,right,5)).
neg(pick(ball1,rooma,right,6)).
neg(pick(ball1,rooma,right,7)).
neg(pick(ball1,rooma,right,8)).
neg(pick(ball1,rooma,right,9)).
neg(pick(ball1,roomb,left,0)).
neg(pick(ball1,roomb,left,1)).
neg(pick(ball1,roomb,left,10)).
neg(pick(ball1,roomb,left,11)).
neg(pick(ball1,roomb,left,12)).
neg(pick(ball1,roomb,left,13)).
neg(pick(ball1,roomb,left,14)).
neg(pick(ball1,roomb,left,15)).
neg(pick(ball1,roomb,left,16)).
neg(pick(ball1,roomb,left,17)).
neg(pick(ball1,roomb,left,18)).
neg(pick(ball1,roomb,left,19)).
neg(pick(ball1,roomb,left,2)).
neg(pick(ball1,roomb,left,20)).
neg(pick(ball1,roomb,left,21)).
neg(pick(ball1,roomb,left,22)).
neg(pick(ball1,roomb,left,23)).
neg(pick(ball1,roomb,left,24)).
neg(pick(ball1,roomb,left,25)).
neg(pick(ball1,roomb,left,26)).
neg(pick(ball1,roomb,left,27)).
neg(pick(ball1,roomb,left,3)).
neg(pick(ball1,roomb,left,4)).
neg(pick(ball1,roomb,left,5)).
neg(pick(ball1,roomb,left,6)).
neg(pick(ball1,roomb,left,7)).
neg(pick(ball1,roomb,left,8)).
neg(pick(ball1,roomb,left,9)).
neg(pick(ball1,roomb,right,0)).
neg(pick(ball1,roomb,right,1)).
neg(pick(ball1,roomb,right,10)).
neg(pick(ball1,roomb,right,11)).
neg(pick(ball1,roomb,right,12)).
neg(pick(ball1,roomb,right,13)).
neg(pick(ball1,roomb,right,14)).
neg(pick(ball1,roomb,right,15)).
neg(pick(ball1,roomb,right,16)).
neg(pick(ball1,roomb,right,17)).
neg(pick(ball1,roomb,right,18)).
neg(pick(ball1,roomb,right,19)).
neg(pick(ball1,roomb,right,2)).
neg(pick(ball1,roomb,right,20)).
neg(pick(ball1,roomb,right,21)).
neg(pick(ball1,roomb,right,22)).
neg(pick(ball1,roomb,right,23)).
neg(pick(ball1,roomb,right,24)).
neg(pick(ball1,roomb,right,25)).
neg(pick(ball1,roomb,right,26)).
neg(pick(ball1,roomb,right,27)).
neg(pick(ball1,roomb,right,3)).
neg(pick(ball1,roomb,right,4)).
neg(pick(ball1,roomb,right,5)).
neg(pick(ball1,roomb,right,6)).
neg(pick(ball1,roomb,right,7)).
neg(pick(ball1,roomb,right,8)).
neg(pick(ball1,roomb,right,9)).
neg(pick(ball2,rooma,left,1)).
neg(pick(ball2,rooma,left,10)).
neg(pick(ball2,rooma,left,12)).
neg(pick(ball2,rooma,left,13)).
neg(pick(ball2,rooma,left,14)).
neg(pick(ball2,rooma,left,15)).
neg(pick(ball2,rooma,left,16)).
neg(pick(ball2,rooma,left,17)).
neg(pick(ball2,rooma,left,18)).
neg(pick(ball2,rooma,left,19)).
neg(pick(ball2,rooma,left,2)).
neg(pick(ball2,rooma,left,20)).
neg(pick(ball2,rooma,left,21)).
neg(pick(ball2,rooma,left,22)).
neg(pick(ball2,rooma,left,23)).
neg(pick(ball2,rooma,left,24)).
neg(pick(ball2,rooma,left,25)).
neg(pick(ball2,rooma,left,26)).
neg(pick(ball2,rooma,left,27)).
neg(pick(ball2,rooma,left,3)).
neg(pick(ball2,rooma,left,4)).
neg(pick(ball2,rooma,left,5)).
neg(pick(ball2,rooma,left,6)).
neg(pick(ball2,rooma,left,7)).
neg(pick(ball2,rooma,left,8)).
neg(pick(ball2,rooma,left,9)).
neg(pick(ball2,rooma,right,10)).
neg(pick(ball2,rooma,right,13)).
neg(pick(ball2,rooma,right,14)).
neg(pick(ball2,rooma,right,15)).
neg(pick(ball2,rooma,right,16)).
neg(pick(ball2,rooma,right,17)).
neg(pick(ball2,rooma,right,18)).
neg(pick(ball2,rooma,right,19)).
neg(pick(ball2,rooma,right,2)).
neg(pick(ball2,rooma,right,20)).
neg(pick(ball2,rooma,right,21)).
neg(pick(ball2,rooma,right,22)).
neg(pick(ball2,rooma,right,23)).
neg(pick(ball2,rooma,right,24)).
neg(pick(ball2,rooma,right,25)).
neg(pick(ball2,rooma,right,26)).
neg(pick(ball2,rooma,right,27)).
neg(pick(ball2,rooma,right,3)).
neg(pick(ball2,rooma,right,4)).
neg(pick(ball2,rooma,right,5)).
neg(pick(ball2,rooma,right,6)).
neg(pick(ball2,rooma,right,7)).
neg(pick(ball2,rooma,right,8)).
neg(pick(ball2,rooma,right,9)).
neg(pick(ball2,roomb,left,0)).
neg(pick(ball2,roomb,left,1)).
neg(pick(ball2,roomb,left,10)).
neg(pick(ball2,roomb,left,11)).
neg(pick(ball2,roomb,left,12)).
neg(pick(ball2,roomb,left,13)).
neg(pick(ball2,roomb,left,14)).
neg(pick(ball2,roomb,left,15)).
neg(pick(ball2,roomb,left,16)).
neg(pick(ball2,roomb,left,17)).
neg(pick(ball2,roomb,left,18)).
neg(pick(ball2,roomb,left,19)).
neg(pick(ball2,roomb,left,2)).
neg(pick(ball2,roomb,left,20)).
neg(pick(ball2,roomb,left,21)).
neg(pick(ball2,roomb,left,22)).
neg(pick(ball2,roomb,left,23)).
neg(pick(ball2,roomb,left,24)).
neg(pick(ball2,roomb,left,25)).
neg(pick(ball2,roomb,left,26)).
neg(pick(ball2,roomb,left,27)).
neg(pick(ball2,roomb,left,3)).
neg(pick(ball2,roomb,left,4)).
neg(pick(ball2,roomb,left,5)).
neg(pick(ball2,roomb,left,6)).
neg(pick(ball2,roomb,left,7)).
neg(pick(ball2,roomb,left,8)).
neg(pick(ball2,roomb,left,9)).
neg(pick(ball2,roomb,right,0)).
neg(pick(ball2,roomb,right,1)).
neg(pick(ball2,roomb,right,10)).
neg(pick(ball2,roomb,right,11)).
neg(pick(ball2,roomb,right,12)).
neg(pick(ball2,roomb,right,13)).
neg(pick(ball2,roomb,right,14)).
neg(pick(ball2,roomb,right,15)).
neg(pick(ball2,roomb,right,16)).
neg(pick(ball2,roomb,right,17)).
neg(pick(ball2,roomb,right,18)).
neg(pick(ball2,roomb,right,19)).
neg(pick(ball2,roomb,right,2)).
neg(pick(ball2,roomb,right,20)).
neg(pick(ball2,roomb,right,21)).
neg(pick(ball2,roomb,right,22)).
neg(pick(ball2,roomb,right,23)).
neg(pick(ball2,roomb,right,24)).
neg(pick(ball2,roomb,right,25)).
neg(pick(ball2,roomb,right,26)).
neg(pick(ball2,roomb,right,27)).
neg(pick(ball2,roomb,right,3)).
neg(pick(ball2,roomb,right,4)).
neg(pick(ball2,roomb,right,5)).
neg(pick(ball2,roomb,right,6)).
neg(pick(ball2,roomb,right,7)).
neg(pick(ball2,roomb,right,8)).
neg(pick(ball2,roomb,right,9)).
neg(pick(ball3,rooma,left,1)).
neg(pick(ball3,rooma,left,10)).
neg(pick(ball3,rooma,left,12)).
neg(pick(ball3,rooma,left,13)).
neg(pick(ball3,rooma,left,14)).
neg(pick(ball3,rooma,left,15)).
neg(pick(ball3,rooma,left,16)).
neg(pick(ball3,rooma,left,18)).
neg(pick(ball3,rooma,left,19)).
neg(pick(ball3,rooma,left,2)).
neg(pick(ball3,rooma,left,20)).
neg(pick(ball3,rooma,left,21)).
neg(pick(ball3,rooma,left,22)).
neg(pick(ball3,rooma,left,23)).
neg(pick(ball3,rooma,left,24)).
neg(pick(ball3,rooma,left,25)).
neg(pick(ball3,rooma,left,26)).
neg(pick(ball3,rooma,left,27)).
neg(pick(ball3,rooma,left,3)).
neg(pick(ball3,rooma,left,4)).
neg(pick(ball3,rooma,left,5)).
neg(pick(ball3,rooma,left,7)).
neg(pick(ball3,rooma,left,8)).
neg(pick(ball3,rooma,left,9)).
neg(pick(ball3,rooma,right,10)).
neg(pick(ball3,rooma,right,13)).
neg(pick(ball3,rooma,right,14)).
neg(pick(ball3,rooma,right,15)).
neg(pick(ball3,rooma,right,16)).
neg(pick(ball3,rooma,right,18)).
neg(pick(ball3,rooma,right,19)).
neg(pick(ball3,rooma,right,2)).
neg(pick(ball3,rooma,right,20)).
neg(pick(ball3,rooma,right,21)).
neg(pick(ball3,rooma,right,22)).
neg(pick(ball3,rooma,right,23)).
neg(pick(ball3,rooma,right,24)).
neg(pick(ball3,rooma,right,25)).
neg(pick(ball3,rooma,right,26)).
neg(pick(ball3,rooma,right,27)).
neg(pick(ball3,rooma,right,3)).
neg(pick(ball3,rooma,right,4)).
neg(pick(ball3,rooma,right,5)).
neg(pick(ball3,rooma,right,7)).
neg(pick(ball3,rooma,right,8)).
neg(pick(ball3,rooma,right,9)).
neg(pick(ball3,roomb,left,0)).
neg(pick(ball3,roomb,left,1)).
neg(pick(ball3,roomb,left,10)).
neg(pick(ball3,roomb,left,11)).
neg(pick(ball3,roomb,left,12)).
neg(pick(ball3,roomb,left,13)).
neg(pick(ball3,roomb,left,14)).
neg(pick(ball3,roomb,left,15)).
neg(pick(ball3,roomb,left,16)).
neg(pick(ball3,roomb,left,17)).
neg(pick(ball3,roomb,left,18)).
neg(pick(ball3,roomb,left,19)).
neg(pick(ball3,roomb,left,2)).
neg(pick(ball3,roomb,left,20)).
neg(pick(ball3,roomb,left,21)).
neg(pick(ball3,roomb,left,22)).
neg(pick(ball3,roomb,left,23)).
neg(pick(ball3,roomb,left,24)).
neg(pick(ball3,roomb,left,25)).
neg(pick(ball3,roomb,left,26)).
neg(pick(ball3,roomb,left,27)).
neg(pick(ball3,roomb,left,3)).
neg(pick(ball3,roomb,left,4)).
neg(pick(ball3,roomb,left,5)).
neg(pick(ball3,roomb,left,6)).
neg(pick(ball3,roomb,left,7)).
neg(pick(ball3,roomb,left,8)).
neg(pick(ball3,roomb,left,9)).
neg(pick(ball3,roomb,right,0)).
neg(pick(ball3,roomb,right,1)).
neg(pick(ball3,roomb,right,10)).
neg(pick(ball3,roomb,right,11)).
neg(pick(ball3,roomb,right,12)).
neg(pick(ball3,roomb,right,13)).
neg(pick(ball3,roomb,right,14)).
neg(pick(ball3,roomb,right,15)).
neg(pick(ball3,roomb,right,16)).
neg(pick(ball3,roomb,right,17)).
neg(pick(ball3,roomb,right,18)).
neg(pick(ball3,roomb,right,19)).
neg(pick(ball3,roomb,right,2)).
neg(pick(ball3,roomb,right,20)).
neg(pick(ball3,roomb,right,21)).
neg(pick(ball3,roomb,right,22)).
neg(pick(ball3,roomb,right,23)).
neg(pick(ball3,roomb,right,24)).
neg(pick(ball3,roomb,right,25)).
neg(pick(ball3,roomb,right,26)).
neg(pick(ball3,roomb,right,27)).
neg(pick(ball3,roomb,right,3)).
neg(pick(ball3,roomb,right,4)).
neg(pick(ball3,roomb,right,5)).
neg(pick(ball3,roomb,right,6)).
neg(pick(ball3,roomb,right,7)).
neg(pick(ball3,roomb,right,8)).
neg(pick(ball3,roomb,right,9)).
neg(pick(ball4,rooma,left,1)).
neg(pick(ball4,rooma,left,10)).
neg(pick(ball4,rooma,left,12)).
neg(pick(ball4,rooma,left,13)).
neg(pick(ball4,rooma,left,14)).
neg(pick(ball4,rooma,left,15)).
neg(pick(ball4,rooma,left,16)).
neg(pick(ball4,rooma,left,18)).
neg(pick(ball4,rooma,left,19)).
neg(pick(ball4,rooma,left,2)).
neg(pick(ball4,rooma,left,20)).
neg(pick(ball4,rooma,left,21)).
neg(pick(ball4,rooma,left,22)).
neg(pick(ball4,rooma,left,23)).
neg(pick(ball4,rooma,left,24)).
neg(pick(ball4,rooma,left,25)).
neg(pick(ball4,rooma,left,26)).
neg(pick(ball4,rooma,left,27)).
neg(pick(ball4,rooma,left,3)).
neg(pick(ball4,rooma,left,4)).
neg(pick(ball4,rooma,left,5)).
neg(pick(ball4,rooma,left,7)).
neg(pick(ball4,rooma,left,8)).
neg(pick(ball4,rooma,left,9)).
neg(pick(ball4,rooma,right,10)).
neg(pick(ball4,rooma,right,13)).
neg(pick(ball4,rooma,right,14)).
neg(pick(ball4,rooma,right,15)).
neg(pick(ball4,rooma,right,16)).
neg(pick(ball4,rooma,right,19)).
neg(pick(ball4,rooma,right,2)).
neg(pick(ball4,rooma,right,20)).
neg(pick(ball4,rooma,right,21)).
neg(pick(ball4,rooma,right,22)).
neg(pick(ball4,rooma,right,23)).
neg(pick(ball4,rooma,right,24)).
neg(pick(ball4,rooma,right,25)).
neg(pick(ball4,rooma,right,26)).
neg(pick(ball4,rooma,right,27)).
neg(pick(ball4,rooma,right,3)).
neg(pick(ball4,rooma,right,4)).
neg(pick(ball4,rooma,right,5)).
neg(pick(ball4,rooma,right,8)).
neg(pick(ball4,rooma,right,9)).
neg(pick(ball4,roomb,left,0)).
neg(pick(ball4,roomb,left,1)).
neg(pick(ball4,roomb,left,10)).
neg(pick(ball4,roomb,left,11)).
neg(pick(ball4,roomb,left,12)).
neg(pick(ball4,roomb,left,13)).
neg(pick(ball4,roomb,left,14)).
neg(pick(ball4,roomb,left,15)).
neg(pick(ball4,roomb,left,16)).
neg(pick(ball4,roomb,left,17)).
neg(pick(ball4,roomb,left,18)).
neg(pick(ball4,roomb,left,19)).
neg(pick(ball4,roomb,left,2)).
neg(pick(ball4,roomb,left,20)).
neg(pick(ball4,roomb,left,21)).
neg(pick(ball4,roomb,left,22)).
neg(pick(ball4,roomb,left,23)).
neg(pick(ball4,roomb,left,24)).
neg(pick(ball4,roomb,left,25)).
neg(pick(ball4,roomb,left,26)).
neg(pick(ball4,roomb,left,27)).
neg(pick(ball4,roomb,left,3)).
neg(pick(ball4,roomb,left,4)).
neg(pick(ball4,roomb,left,5)).
neg(pick(ball4,roomb,left,6)).
neg(pick(ball4,roomb,left,7)).
neg(pick(ball4,roomb,left,8)).
neg(pick(ball4,roomb,left,9)).
neg(pick(ball4,roomb,right,0)).
neg(pick(ball4,roomb,right,1)).
neg(pick(ball4,roomb,right,10)).
neg(pick(ball4,roomb,right,11)).
neg(pick(ball4,roomb,right,12)).
neg(pick(ball4,roomb,right,13)).
neg(pick(ball4,roomb,right,14)).
neg(pick(ball4,roomb,right,15)).
neg(pick(ball4,roomb,right,16)).
neg(pick(ball4,roomb,right,17)).
neg(pick(ball4,roomb,right,18)).
neg(pick(ball4,roomb,right,19)).
neg(pick(ball4,roomb,right,2)).
neg(pick(ball4,roomb,right,20)).
neg(pick(ball4,roomb,right,21)).
neg(pick(ball4,roomb,right,22)).
neg(pick(ball4,roomb,right,23)).
neg(pick(ball4,roomb,right,24)).
neg(pick(ball4,roomb,right,25)).
neg(pick(ball4,roomb,right,26)).
neg(pick(ball4,roomb,right,27)).
neg(pick(ball4,roomb,right,3)).
neg(pick(ball4,roomb,right,4)).
neg(pick(ball4,roomb,right,5)).
neg(pick(ball4,roomb,right,6)).
neg(pick(ball4,roomb,right,7)).
neg(pick(ball4,roomb,right,8)).
neg(pick(ball4,roomb,right,9)).
neg(pick(ball5,rooma,left,0)).
neg(pick(ball5,rooma,left,1)).
neg(pick(ball5,rooma,left,10)).
neg(pick(ball5,rooma,left,12)).
neg(pick(ball5,rooma,left,13)).
neg(pick(ball5,rooma,left,14)).
neg(pick(ball5,rooma,left,15)).
neg(pick(ball5,rooma,left,16)).
neg(pick(ball5,rooma,left,18)).
neg(pick(ball5,rooma,left,19)).
neg(pick(ball5,rooma,left,2)).
neg(pick(ball5,rooma,left,20)).
neg(pick(ball5,rooma,left,21)).
neg(pick(ball5,rooma,left,22)).
neg(pick(ball5,rooma,left,24)).
neg(pick(ball5,rooma,left,25)).
neg(pick(ball5,rooma,left,26)).
neg(pick(ball5,rooma,left,27)).
neg(pick(ball5,rooma,left,3)).
neg(pick(ball5,rooma,left,4)).
neg(pick(ball5,rooma,left,5)).
neg(pick(ball5,rooma,left,6)).
neg(pick(ball5,rooma,left,7)).
neg(pick(ball5,rooma,left,8)).
neg(pick(ball5,rooma,left,9)).
neg(pick(ball5,rooma,right,0)).
neg(pick(ball5,rooma,right,1)).
neg(pick(ball5,rooma,right,10)).
neg(pick(ball5,rooma,right,13)).
neg(pick(ball5,rooma,right,14)).
neg(pick(ball5,rooma,right,15)).
neg(pick(ball5,rooma,right,16)).
neg(pick(ball5,rooma,right,19)).
neg(pick(ball5,rooma,right,2)).
neg(pick(ball5,rooma,right,20)).
neg(pick(ball5,rooma,right,21)).
neg(pick(ball5,rooma,right,22)).
neg(pick(ball5,rooma,right,24)).
neg(pick(ball5,rooma,right,25)).
neg(pick(ball5,rooma,right,26)).
neg(pick(ball5,rooma,right,27)).
neg(pick(ball5,rooma,right,3)).
neg(pick(ball5,rooma,right,4)).
neg(pick(ball5,rooma,right,5)).
neg(pick(ball5,rooma,right,6)).
neg(pick(ball5,rooma,right,7)).
neg(pick(ball5,rooma,right,8)).
neg(pick(ball5,rooma,right,9)).
neg(pick(ball5,roomb,left,0)).
neg(pick(ball5,roomb,left,1)).
neg(pick(ball5,roomb,left,10)).
neg(pick(ball5,roomb,left,11)).
neg(pick(ball5,roomb,left,12)).
neg(pick(ball5,roomb,left,13)).
neg(pick(ball5,roomb,left,14)).
neg(pick(ball5,roomb,left,15)).
neg(pick(ball5,roomb,left,16)).
neg(pick(ball5,roomb,left,17)).
neg(pick(ball5,roomb,left,18)).
neg(pick(ball5,roomb,left,19)).
neg(pick(ball5,roomb,left,2)).
neg(pick(ball5,roomb,left,20)).
neg(pick(ball5,roomb,left,21)).
neg(pick(ball5,roomb,left,22)).
neg(pick(ball5,roomb,left,23)).
neg(pick(ball5,roomb,left,24)).
neg(pick(ball5,roomb,left,25)).
neg(pick(ball5,roomb,left,26)).
neg(pick(ball5,roomb,left,27)).
neg(pick(ball5,roomb,left,3)).
neg(pick(ball5,roomb,left,4)).
neg(pick(ball5,roomb,left,5)).
neg(pick(ball5,roomb,left,6)).
neg(pick(ball5,roomb,left,7)).
neg(pick(ball5,roomb,left,8)).
neg(pick(ball5,roomb,left,9)).
neg(pick(ball5,roomb,right,0)).
neg(pick(ball5,roomb,right,1)).
neg(pick(ball5,roomb,right,10)).
neg(pick(ball5,roomb,right,11)).
neg(pick(ball5,roomb,right,12)).
neg(pick(ball5,roomb,right,13)).
neg(pick(ball5,roomb,right,14)).
neg(pick(ball5,roomb,right,15)).
neg(pick(ball5,roomb,right,16)).
neg(pick(ball5,roomb,right,17)).
neg(pick(ball5,roomb,right,18)).
neg(pick(ball5,roomb,right,19)).
neg(pick(ball5,roomb,right,2)).
neg(pick(ball5,roomb,right,20)).
neg(pick(ball5,roomb,right,21)).
neg(pick(ball5,roomb,right,22)).
neg(pick(ball5,roomb,right,23)).
neg(pick(ball5,roomb,right,24)).
neg(pick(ball5,roomb,right,25)).
neg(pick(ball5,roomb,right,26)).
neg(pick(ball5,roomb,right,27)).
neg(pick(ball5,roomb,right,3)).
neg(pick(ball5,roomb,right,4)).
neg(pick(ball5,roomb,right,5)).
neg(pick(ball5,roomb,right,6)).
neg(pick(ball5,roomb,right,7)).
neg(pick(ball5,roomb,right,8)).
neg(pick(ball5,roomb,right,9)).
neg(pick(ball6,rooma,left,0)).
neg(pick(ball6,rooma,left,1)).
neg(pick(ball6,rooma,left,10)).
neg(pick(ball6,rooma,left,12)).
neg(pick(ball6,rooma,left,13)).
neg(pick(ball6,rooma,left,14)).
neg(pick(ball6,rooma,left,15)).
neg(pick(ball6,rooma,left,16)).
neg(pick(ball6,rooma,left,18)).
neg(pick(ball6,rooma,left,19)).
neg(pick(ball6,rooma,left,2)).
neg(pick(ball6,rooma,left,20)).
neg(pick(ball6,rooma,left,21)).
neg(pick(ball6,rooma,left,22)).
neg(pick(ball6,rooma,left,24)).
neg(pick(ball6,rooma,left,25)).
neg(pick(ball6,rooma,left,26)).
neg(pick(ball6,rooma,left,27)).
neg(pick(ball6,rooma,left,3)).
neg(pick(ball6,rooma,left,4)).
neg(pick(ball6,rooma,left,5)).
neg(pick(ball6,rooma,left,6)).
neg(pick(ball6,rooma,left,7)).
neg(pick(ball6,rooma,left,8)).
neg(pick(ball6,rooma,left,9)).
neg(pick(ball6,rooma,right,0)).
neg(pick(ball6,rooma,right,1)).
neg(pick(ball6,rooma,right,10)).
neg(pick(ball6,rooma,right,13)).
neg(pick(ball6,rooma,right,14)).
neg(pick(ball6,rooma,right,15)).
neg(pick(ball6,rooma,right,16)).
neg(pick(ball6,rooma,right,19)).
neg(pick(ball6,rooma,right,2)).
neg(pick(ball6,rooma,right,20)).
neg(pick(ball6,rooma,right,21)).
neg(pick(ball6,rooma,right,22)).
neg(pick(ball6,rooma,right,25)).
neg(pick(ball6,rooma,right,26)).
neg(pick(ball6,rooma,right,27)).
neg(pick(ball6,rooma,right,3)).
neg(pick(ball6,rooma,right,4)).
neg(pick(ball6,rooma,right,5)).
neg(pick(ball6,rooma,right,6)).
neg(pick(ball6,rooma,right,7)).
neg(pick(ball6,rooma,right,8)).
neg(pick(ball6,rooma,right,9)).
neg(pick(ball6,roomb,left,0)).
neg(pick(ball6,roomb,left,1)).
neg(pick(ball6,roomb,left,10)).
neg(pick(ball6,roomb,left,11)).
neg(pick(ball6,roomb,left,12)).
neg(pick(ball6,roomb,left,13)).
neg(pick(ball6,roomb,left,14)).
neg(pick(ball6,roomb,left,15)).
neg(pick(ball6,roomb,left,16)).
neg(pick(ball6,roomb,left,17)).
neg(pick(ball6,roomb,left,18)).
neg(pick(ball6,roomb,left,19)).
neg(pick(ball6,roomb,left,2)).
neg(pick(ball6,roomb,left,20)).
neg(pick(ball6,roomb,left,21)).
neg(pick(ball6,roomb,left,22)).
neg(pick(ball6,roomb,left,23)).
neg(pick(ball6,roomb,left,24)).
neg(pick(ball6,roomb,left,25)).
neg(pick(ball6,roomb,left,26)).
neg(pick(ball6,roomb,left,27)).
neg(pick(ball6,roomb,left,3)).
neg(pick(ball6,roomb,left,4)).
neg(pick(ball6,roomb,left,5)).
neg(pick(ball6,roomb,left,6)).
neg(pick(ball6,roomb,left,7)).
neg(pick(ball6,roomb,left,8)).
neg(pick(ball6,roomb,left,9)).
neg(pick(ball6,roomb,right,0)).
neg(pick(ball6,roomb,right,1)).
neg(pick(ball6,roomb,right,10)).
neg(pick(ball6,roomb,right,11)).
neg(pick(ball6,roomb,right,12)).
neg(pick(ball6,roomb,right,13)).
neg(pick(ball6,roomb,right,14)).
neg(pick(ball6,roomb,right,15)).
neg(pick(ball6,roomb,right,16)).
neg(pick(ball6,roomb,right,17)).
neg(pick(ball6,roomb,right,18)).
neg(pick(ball6,roomb,right,19)).
neg(pick(ball6,roomb,right,2)).
neg(pick(ball6,roomb,right,20)).
neg(pick(ball6,roomb,right,21)).
neg(pick(ball6,roomb,right,22)).
neg(pick(ball6,roomb,right,23)).
neg(pick(ball6,roomb,right,24)).
neg(pick(ball6,roomb,right,25)).
neg(pick(ball6,roomb,right,26)).
neg(pick(ball6,roomb,right,27)).
neg(pick(ball6,roomb,right,3)).
neg(pick(ball6,roomb,right,4)).
neg(pick(ball6,roomb,right,5)).
neg(pick(ball6,roomb,right,6)).
neg(pick(ball6,roomb,right,7)).
neg(pick(ball6,roomb,right,8)).
neg(pick(ball6,roomb,right,9)).
