pos(great_rsd(a1,v1)).
pos(great_rsd(w1,l1)).
pos(great_rsd(u1,kk1)).
pos(great_rsd(kk1,z1)).
pos(great_rsd(f1,q1)).
pos(great_rsd(m1,z1)).
pos(great_rsd(w1,hh1)).
pos(great_rsd(aa1,hh1)).
pos(great_rsd(ee1,k1)).
pos(great_rsd(k1,jj1)).
pos(great_rsd(g1,hh1)).
pos(great_rsd(c1,l1)).
pos(great_rsd(ff1,g1)).
pos(great_rsd(cc1,ff1)).
pos(great_rsd(f1,k1)).
pos(great_rsd(m1,dd1)).
pos(great_rsd(f1,x1)).
pos(great_rsd(e1,ee1)).
pos(great_rsd(e1,x1)).
pos(great_rsd(z1,jj1)).
pos(great_rsd(v1,h1)).
pos(great_rsd(f1,a1)).
pos(great_rsd(v1,z1)).
pos(great_rsd(v1,g1)).
pos(great_rsd(hh1,h1)).
pos(great_rsd(p1,k1)).
pos(great_rsd(e1,t1)).
pos(great_rsd(f1,u1)).
pos(great_rsd(ee1,kk1)).
pos(great_rsd(cc1,l1)).
pos(great_rsd(c1,h1)).
pos(great_rsd(a1,ff1)).
pos(great_rsd(ee1,ff1)).
pos(great_rsd(t1,ii1)).
pos(great_rsd(p1,u1)).
pos(great_rsd(p1,h1)).
pos(great_rsd(aa1,jj1)).
pos(great_rsd(cc1,m1)).
pos(great_rsd(g1,jj1)).
pos(great_rsd(p1,hh1)).
pos(great_rsd(u1,ii1)).
pos(great_rsd(t1,k1)).
pos(great_rsd(a1,jj1)).
pos(great_rsd(ee1,m1)).
pos(great_rsd(p1,a1)).
pos(great_rsd(aa1,g1)).
pos(great_rsd(g1,dd1)).
pos(great_rsd(e1,a1)).
pos(great_rsd(aa1,l1)).
pos(great_rsd(g1,l1)).
pos(great_rsd(h1,dd1)).
pos(great_rsd(w1,t1)).
pos(great_rsd(k1,c1)).
pos(great_rsd(v1,t1)).
pos(great_rsd(a1,g1)).
pos(great_rsd(ee1,ii1)).
pos(great_rsd(u1,jj1)).
pos(great_rsd(ii1,l1)).
pos(great_rsd(t1,g1)).
pos(great_rsd(f1,jj1)).
pos(great_rsd(c1,jj1)).
pos(great_rsd(f1,aa1)).
pos(great_rsd(f1,t1)).
pos(great_rsd(a1,h1)).
pos(great_rsd(cc1,ii1)).
pos(great_rsd(ee1,c1)).
pos(great_rsd(u1,l1)).
pos(great_rsd(g1,h1)).
pos(great_rsd(k1,g1)).
pos(great_rsd(cc1,v1)).
pos(great_rsd(e1,c1)).
pos(great_rsd(a1,t1)).
pos(great_rsd(cc1,dd1)).
pos(great_rsd(t1,ff1)).
pos(great_rsd(f1,ee1)).
pos(great_rsd(k1,l1)).
pos(great_rsd(q1,k1)).
pos(great_rsd(aa1,c1)).
pos(great_rsd(q1,h1)).
pos(great_rsd(ee1,z1)).
pos(great_rsd(jj1,dd1)).
pos(great_rsd(t1,q1)).
pos(great_rsd(ff1,k1)).
pos(great_rsd(e1,z1)).
pos(great_rsd(jj1,x1)).
pos(great_rsd(hh1,x1)).
pos(great_rsd(cc1,w1)).
pos(great_rsd(f1,p1)).
pos(great_rsd(a1,c1)).
pos(great_rsd(m1,hh1)).
pos(great_rsd(q1,ee1)).
pos(great_rsd(w1,z1)).
pos(great_rsd(u1,t1)).
pos(great_rsd(cc1,q1)).
pos(great_rsd(aa1,kk1)).
pos(great_rsd(a1,l1)).
pos(great_rsd(cc1,kk1)).
pos(great_rsd(p1,ii1)).
pos(great_rsd(w1,ee1)).
pos(great_rsd(t1,l1)).
pos(great_rsd(e1,hh1)).
pos(great_rsd(q1,hh1)).
pos(great_rsd(k1,z1)).
pos(great_rsd(ff1,z1)).
pos(great_rsd(w1,c1)).
pos(great_rsd(t1,hh1)).
pos(great_rsd(p1,cc1)).
pos(great_rsd(f1,g1)).
pos(great_rsd(aa1,ee1)).
pos(great_rsd(kk1,ii1)).
pos(great_rsd(f1,hh1)).
pos(great_rsd(a1,kk1)).
pos(great_rsd(q1,ff1)).
pos(great_rsd(p1,kk1)).
pos(great_rsd(h1,l1)).
pos(great_rsd(t1,x1)).
pos(great_rsd(m1,kk1)).
pos(great_rsd(a1,cc1)).
pos(great_rsd(cc1,z1)).
pos(great_rsd(w1,ff1)).
pos(great_rsd(c1,hh1)).
pos(great_rsd(l1,dd1)).
pos(great_rsd(e1,l1)).
pos(great_rsd(a1,w1)).
pos(great_rsd(a1,u1)).
pos(great_rsd(q1,jj1)).
pos(great_rsd(q1,kk1)).
pos(great_rsd(w1,g1)).
pos(great_rsd(m1,jj1)).
pos(great_rsd(ee1,h1)).
pos(great_rsd(t1,z1)).
pos(great_rsd(w1,k1)).
pos(great_rsd(h1,jj1)).
pos(great_rsd(u1,m1)).
pos(great_rsd(v1,ee1)).
pos(great_rsd(v1,m1)).
pos(great_rsd(a1,aa1)).
pos(great_rsd(e1,q1)).
pos(great_rsd(aa1,z1)).
pos(great_rsd(t1,aa1)).
pos(great_rsd(e1,u1)).
pos(great_rsd(q1,dd1)).
pos(great_rsd(c1,ii1)).
pos(great_rsd(ff1,m1)).
pos(great_rsd(q1,g1)).
pos(great_rsd(t1,kk1)).
pos(great_rsd(k1,ii1)).
pos(great_rsd(f1,m1)).
pos(great_rsd(f1,w1)).
pos(great_rsd(g1,z1)).
pos(great_rsd(u1,q1)).
pos(great_rsd(kk1,x1)).
pos(great_rsd(p1,ff1)).
pos(great_rsd(e1,v1)).
pos(great_rsd(w1,aa1)).
pos(great_rsd(ff1,jj1)).
pos(great_rsd(ff1,x1)).
pos(great_rsd(w1,jj1)).
pos(great_rsd(m1,l1)).
pos(great_rsd(z1,l1)).
pos(great_rsd(kk1,l1)).
pos(great_rsd(q1,l1)).
pos(great_rsd(f1,z1)).
pos(great_rsd(v1,q1)).
pos(great_rsd(t1,ee1)).
pos(great_rsd(k1,x1)).
pos(great_rsd(cc1,jj1)).
pos(great_rsd(aa1,m1)).
pos(great_rsd(p1,z1)).
pos(great_rsd(q1,z1)).
pos(great_rsd(w1,m1)).
pos(great_rsd(ee1,x1)).
pos(great_rsd(v1,w1)).
pos(great_rsd(ee1,g1)).
pos(great_rsd(t1,c1)).
pos(great_rsd(p1,l1)).
pos(great_rsd(e1,dd1)).
pos(great_rsd(m1,k1)).
pos(great_rsd(u1,k1)).
pos(great_rsd(a1,dd1)).
pos(great_rsd(ee1,jj1)).
pos(great_rsd(p1,m1)).
pos(great_rsd(c1,dd1)).
pos(great_rsd(kk1,hh1)).
pos(great_rsd(p1,jj1)).
pos(great_rsd(m1,ii1)).
pos(great_rsd(m1,h1)).
pos(great_rsd(e1,cc1)).
pos(great_rsd(g1,x1)).
pos(great_rsd(cc1,u1)).
pos(great_rsd(aa1,h1)).
pos(great_rsd(v1,ff1)).
pos(great_rsd(g1,c1)).
pos(great_rsd(a1,k1)).
pos(great_rsd(a1,ii1)).
pos(great_rsd(u1,ff1)).
pos(great_rsd(cc1,g1)).
pos(great_rsd(hh1,jj1)).
pos(great_rsd(e1,jj1)).
pos(great_rsd(f1,h1)).
pos(great_rsd(p1,aa1)).
pos(great_rsd(u1,aa1)).
pos(great_rsd(v1,kk1)).
pos(great_rsd(aa1,ff1)).
pos(great_rsd(u1,dd1)).
pos(great_rsd(t1,jj1)).
pos(great_rsd(a1,x1)).
pos(great_rsd(ff1,kk1)).
pos(great_rsd(kk1,dd1)).
pos(great_rsd(kk1,c1)).
pos(great_rsd(ii1,x1)).
pos(great_rsd(t1,h1)).
pos(great_rsd(q1,c1)).
pos(great_rsd(e1,k1)).
pos(great_rsd(p1,c1)).
pos(great_rsd(ii1,dd1)).
pos(great_rsd(cc1,x1)).
pos(great_rsd(p1,q1)).
pos(great_rsd(w1,kk1)).
pos(great_rsd(cc1,h1)).
pos(great_rsd(f1,kk1)).
pos(great_rsd(w1,ii1)).
pos(great_rsd(cc1,k1)).
pos(great_rsd(q1,ii1)).
pos(great_rsd(p1,x1)).
pos(great_rsd(ff1,l1)).
pos(great_rsd(f1,v1)).
pos(great_rsd(f1,dd1)).
pos(great_rsd(cc1,ee1)).
pos(great_rsd(k1,kk1)).
pos(great_rsd(m1,c1)).
pos(great_rsd(v1,dd1)).
pos(great_rsd(l1,jj1)).
pos(great_rsd(z1,h1)).
pos(great_rsd(kk1,jj1)).
pos(great_rsd(a1,m1)).
pos(great_rsd(aa1,ii1)).
pos(great_rsd(w1,dd1)).
pos(great_rsd(p1,dd1)).
pos(great_rsd(f1,ff1)).
pos(great_rsd(aa1,q1)).
pos(great_rsd(e1,f1)).
pos(great_rsd(v1,k1)).
pos(great_rsd(aa1,x1)).
pos(great_rsd(k1,h1)).
pos(great_rsd(k1,hh1)).
pos(great_rsd(e1,w1)).
pos(great_rsd(c1,z1)).
pos(great_rsd(t1,m1)).
pos(great_rsd(e1,m1)).
pos(great_rsd(aa1,dd1)).
pos(great_rsd(e1,ii1)).
pos(great_rsd(ff1,dd1)).
pos(great_rsd(ff1,hh1)).
pos(great_rsd(v1,l1)).
pos(great_rsd(t1,dd1)).
neg(great_rsd(k1,v1)).
neg(great_rsd(t1,f1)).
neg(great_rsd(t1,u1)).
neg(great_rsd(dd1,hh1)).
neg(great_rsd(x1,a1)).
neg(great_rsd(q1,t1)).
neg(great_rsd(aa1,f1)).
neg(great_rsd(x1,h1)).
neg(great_rsd(cc1,p1)).
neg(great_rsd(z1,t1)).
neg(great_rsd(h1,ii1)).
neg(great_rsd(c1,v1)).
neg(great_rsd(t1,w1)).
neg(great_rsd(hh1,u1)).
neg(great_rsd(x1,l1)).
neg(great_rsd(l1,f1)).
neg(great_rsd(g1,q1)).
neg(great_rsd(w1,f1)).
neg(great_rsd(dd1,f1)).
neg(great_rsd(l1,a1)).
neg(great_rsd(h1,v1)).
neg(great_rsd(g1,a1)).
neg(great_rsd(ff1,aa1)).
neg(great_rsd(k1,m1)).
neg(great_rsd(hh1,k1)).
neg(great_rsd(g1,f1)).
neg(great_rsd(u1,p1)).
neg(great_rsd(ff1,cc1)).
neg(great_rsd(k1,t1)).
neg(great_rsd(kk1,w1)).
neg(great_rsd(x1,c1)).
neg(great_rsd(a1,f1)).
neg(great_rsd(x1,ff1)).
neg(great_rsd(h1,aa1)).
neg(great_rsd(t1,v1)).
neg(great_rsd(z1,u1)).
neg(great_rsd(ii1,c1)).
neg(great_rsd(x1,k1)).
neg(great_rsd(c1,g1)).
neg(great_rsd(q1,a1)).
neg(great_rsd(g1,p1)).
neg(great_rsd(h1,kk1)).
neg(great_rsd(jj1,z1)).
neg(great_rsd(z1,cc1)).
neg(great_rsd(x1,q1)).
neg(great_rsd(z1,aa1)).
neg(great_rsd(ii1,kk1)).
neg(great_rsd(ee1,a1)).
neg(great_rsd(dd1,aa1)).
neg(great_rsd(c1,t1)).
neg(great_rsd(x1,aa1)).
neg(great_rsd(kk1,u1)).
neg(great_rsd(q1,cc1)).
neg(great_rsd(q1,e1)).
neg(great_rsd(jj1,g1)).
neg(great_rsd(ee1,p1)).
neg(great_rsd(h1,w1)).
neg(great_rsd(q1,p1)).
neg(great_rsd(g1,v1)).
neg(great_rsd(m1,e1)).
neg(great_rsd(dd1,c1)).
neg(great_rsd(x1,f1)).
neg(great_rsd(hh1,cc1)).
neg(great_rsd(u1,w1)).
neg(great_rsd(z1,c1)).
neg(great_rsd(q1,f1)).
neg(great_rsd(c1,q1)).
neg(great_rsd(g1,t1)).
neg(great_rsd(ii1,w1)).
neg(great_rsd(g1,e1)).
neg(great_rsd(c1,cc1)).
neg(great_rsd(cc1,e1)).
neg(great_rsd(t1,p1)).
neg(great_rsd(ee1,f1)).
neg(great_rsd(g1,ee1)).
neg(great_rsd(h1,ee1)).
neg(great_rsd(w1,p1)).
neg(great_rsd(kk1,q1)).
neg(great_rsd(h1,q1)).
neg(great_rsd(dd1,cc1)).
neg(great_rsd(ii1,k1)).
neg(great_rsd(g1,w1)).
neg(great_rsd(dd1,m1)).
neg(great_rsd(l1,t1)).
neg(great_rsd(t1,e1)).
neg(great_rsd(l1,ee1)).
neg(great_rsd(ee1,t1)).
neg(great_rsd(x1,g1)).
neg(great_rsd(kk1,k1)).
neg(great_rsd(g1,u1)).
neg(great_rsd(l1,c1)).
neg(great_rsd(z1,ff1)).
neg(great_rsd(dd1,ii1)).
neg(great_rsd(dd1,g1)).
neg(great_rsd(aa1,e1)).
neg(great_rsd(c1,ee1)).
neg(great_rsd(hh1,aa1)).
neg(great_rsd(jj1,m1)).
neg(great_rsd(jj1,k1)).
neg(great_rsd(w1,e1)).
neg(great_rsd(h1,k1)).
neg(great_rsd(cc1,a1)).
neg(great_rsd(aa1,p1)).
neg(great_rsd(x1,t1)).
neg(great_rsd(h1,cc1)).
neg(great_rsd(l1,u1)).
neg(great_rsd(c1,a1)).
neg(great_rsd(jj1,t1)).
neg(great_rsd(k1,aa1)).
neg(great_rsd(kk1,ee1)).
neg(great_rsd(jj1,a1)).
neg(great_rsd(u1,e1)).
neg(great_rsd(w1,cc1)).
neg(great_rsd(m1,w1)).
neg(great_rsd(l1,ff1)).
neg(great_rsd(ii1,ee1)).
neg(great_rsd(f1,e1)).
neg(great_rsd(h1,m1)).
neg(great_rsd(k1,ff1)).
neg(great_rsd(k1,a1)).
neg(great_rsd(l1,aa1)).
neg(great_rsd(kk1,ff1)).
neg(great_rsd(h1,f1)).
neg(great_rsd(ff1,q1)).
neg(great_rsd(m1,q1)).
neg(great_rsd(k1,q1)).
neg(great_rsd(x1,cc1)).
neg(great_rsd(jj1,cc1)).
neg(great_rsd(dd1,a1)).
neg(great_rsd(hh1,a1)).
neg(great_rsd(v1,a1)).
neg(great_rsd(x1,z1)).
neg(great_rsd(jj1,w1)).
neg(great_rsd(v1,e1)).
neg(great_rsd(dd1,ee1)).
neg(great_rsd(x1,dd1)).
neg(great_rsd(dd1,v1)).
neg(great_rsd(dd1,p1)).
neg(great_rsd(l1,z1)).
neg(great_rsd(aa1,t1)).
neg(great_rsd(t1,a1)).
neg(great_rsd(z1,w1)).
neg(great_rsd(ee1,cc1)).
neg(great_rsd(c1,f1)).
neg(great_rsd(l1,m1)).
neg(great_rsd(h1,c1)).
neg(great_rsd(kk1,cc1)).
neg(great_rsd(hh1,p1)).
neg(great_rsd(ee1,w1)).
neg(great_rsd(ff1,v1)).
neg(great_rsd(v1,cc1)).
neg(great_rsd(k1,f1)).
neg(great_rsd(m1,cc1)).
neg(great_rsd(cc1,f1)).
neg(great_rsd(c1,k1)).
neg(great_rsd(l1,g1)).
neg(great_rsd(m1,aa1)).
neg(great_rsd(ii1,g1)).
neg(great_rsd(ff1,a1)).
neg(great_rsd(u1,f1)).
neg(great_rsd(hh1,m1)).
neg(great_rsd(x1,jj1)).
neg(great_rsd(z1,e1)).
neg(great_rsd(jj1,ii1)).
neg(great_rsd(k1,u1)).
neg(great_rsd(aa1,a1)).
neg(great_rsd(ii1,m1)).
neg(great_rsd(t1,cc1)).
neg(great_rsd(ff1,p1)).
neg(great_rsd(h1,u1)).
neg(great_rsd(m1,a1)).
neg(great_rsd(aa1,v1)).
neg(great_rsd(kk1,m1)).
neg(great_rsd(p1,f1)).
neg(great_rsd(dd1,w1)).
neg(great_rsd(c1,ff1)).
neg(great_rsd(ff1,e1)).
neg(great_rsd(ff1,u1)).
neg(great_rsd(m1,ee1)).
neg(great_rsd(l1,v1)).
neg(great_rsd(kk1,v1)).
neg(great_rsd(hh1,v1)).
neg(great_rsd(kk1,f1)).
neg(great_rsd(z1,v1)).
neg(great_rsd(c1,w1)).
neg(great_rsd(c1,p1)).
neg(great_rsd(h1,p1)).
neg(great_rsd(m1,ff1)).
neg(great_rsd(ff1,f1)).
neg(great_rsd(l1,w1)).
neg(great_rsd(c1,u1)).
neg(great_rsd(x1,v1)).
neg(great_rsd(c1,e1)).
neg(great_rsd(l1,k1)).
neg(great_rsd(h1,hh1)).
neg(great_rsd(k1,ee1)).
neg(great_rsd(aa1,cc1)).
neg(great_rsd(x1,u1)).
neg(great_rsd(dd1,l1)).
neg(great_rsd(hh1,f1)).
neg(great_rsd(jj1,f1)).
neg(great_rsd(l1,cc1)).
neg(great_rsd(u1,v1)).
neg(great_rsd(x1,ii1)).
neg(great_rsd(w1,v1)).
neg(great_rsd(x1,e1)).
neg(great_rsd(kk1,e1)).
neg(great_rsd(ii1,p1)).
neg(great_rsd(kk1,p1)).
neg(great_rsd(ii1,aa1)).
neg(great_rsd(l1,h1)).
neg(great_rsd(v1,f1)).
neg(great_rsd(hh1,c1)).
neg(great_rsd(c1,kk1)).
neg(great_rsd(ii1,e1)).
neg(great_rsd(q1,aa1)).
neg(great_rsd(kk1,t1)).
neg(great_rsd(ff1,w1)).
neg(great_rsd(dd1,jj1)).
neg(great_rsd(dd1,q1)).
neg(great_rsd(hh1,kk1)).
neg(great_rsd(c1,aa1)).
neg(great_rsd(m1,p1)).
neg(great_rsd(w1,a1)).
neg(great_rsd(h1,e1)).
neg(great_rsd(g1,ff1)).
neg(great_rsd(ii1,ff1)).
neg(great_rsd(z1,m1)).
neg(great_rsd(hh1,t1)).
neg(great_rsd(p1,e1)).
neg(great_rsd(z1,f1)).
neg(great_rsd(ee1,q1)).
neg(great_rsd(x1,ee1)).
neg(great_rsd(k1,p1)).
neg(great_rsd(h1,a1)).
neg(great_rsd(h1,t1)).
neg(great_rsd(jj1,l1)).
neg(great_rsd(m1,u1)).
neg(great_rsd(jj1,ee1)).
neg(great_rsd(hh1,q1)).
neg(great_rsd(jj1,v1)).
neg(great_rsd(ii1,f1)).
neg(great_rsd(h1,z1)).
neg(great_rsd(x1,w1)).
neg(great_rsd(dd1,kk1)).
neg(great_rsd(jj1,e1)).
neg(great_rsd(q1,u1)).
neg(great_rsd(z1,p1)).
neg(great_rsd(x1,kk1)).
neg(great_rsd(ee1,aa1)).
neg(great_rsd(m1,v1)).
neg(great_rsd(jj1,p1)).
neg(great_rsd(ii1,q1)).
neg(great_rsd(jj1,q1)).
neg(great_rsd(ii1,v1)).
neg(great_rsd(hh1,e1)).
