% Positive examples
pos(painttoshelf(obj0,receptacle_shelf,robby,15)).
pos(painttoshelf(obj1,receptacle_shelf,robby,10)).
pos(painttoshelf(obj2,receptacle_shelf,robby,6)).

% Negative examples
neg(painttoshelf(obj0,receptacle_shelf,robby,0)).
neg(painttoshelf(obj0,receptacle_shelf,robby,1)).
neg(painttoshelf(obj0,receptacle_shelf,robby,10)).
neg(painttoshelf(obj0,receptacle_shelf,robby,11)).
neg(painttoshelf(obj0,receptacle_shelf,robby,12)).
neg(painttoshelf(obj0,receptacle_shelf,robby,13)).
neg(painttoshelf(obj0,receptacle_shelf,robby,14)).
neg(painttoshelf(obj0,receptacle_shelf,robby,16)).
neg(painttoshelf(obj0,receptacle_shelf,robby,2)).
neg(painttoshelf(obj0,receptacle_shelf,robby,3)).
neg(painttoshelf(obj0,receptacle_shelf,robby,4)).
neg(painttoshelf(obj0,receptacle_shelf,robby,5)).
neg(painttoshelf(obj0,receptacle_shelf,robby,6)).
neg(painttoshelf(obj0,receptacle_shelf,robby,7)).
neg(painttoshelf(obj0,receptacle_shelf,robby,8)).
neg(painttoshelf(obj0,receptacle_shelf,robby,9)).
neg(painttoshelf(obj1,receptacle_shelf,robby,0)).
neg(painttoshelf(obj1,receptacle_shelf,robby,1)).
neg(painttoshelf(obj1,receptacle_shelf,robby,11)).
neg(painttoshelf(obj1,receptacle_shelf,robby,12)).
neg(painttoshelf(obj1,receptacle_shelf,robby,13)).
neg(painttoshelf(obj1,receptacle_shelf,robby,14)).
neg(painttoshelf(obj1,receptacle_shelf,robby,15)).
neg(painttoshelf(obj1,receptacle_shelf,robby,16)).
neg(painttoshelf(obj1,receptacle_shelf,robby,2)).
neg(painttoshelf(obj1,receptacle_shelf,robby,3)).
neg(painttoshelf(obj1,receptacle_shelf,robby,4)).
neg(painttoshelf(obj1,receptacle_shelf,robby,5)).
neg(painttoshelf(obj1,receptacle_shelf,robby,6)).
neg(painttoshelf(obj1,receptacle_shelf,robby,7)).
neg(painttoshelf(obj1,receptacle_shelf,robby,8)).
neg(painttoshelf(obj1,receptacle_shelf,robby,9)).
neg(painttoshelf(obj2,receptacle_shelf,robby,0)).
neg(painttoshelf(obj2,receptacle_shelf,robby,1)).
neg(painttoshelf(obj2,receptacle_shelf,robby,10)).
neg(painttoshelf(obj2,receptacle_shelf,robby,11)).
neg(painttoshelf(obj2,receptacle_shelf,robby,12)).
neg(painttoshelf(obj2,receptacle_shelf,robby,13)).
neg(painttoshelf(obj2,receptacle_shelf,robby,14)).
neg(painttoshelf(obj2,receptacle_shelf,robby,15)).
neg(painttoshelf(obj2,receptacle_shelf,robby,16)).
neg(painttoshelf(obj2,receptacle_shelf,robby,2)).
neg(painttoshelf(obj2,receptacle_shelf,robby,3)).
neg(painttoshelf(obj2,receptacle_shelf,robby,4)).
neg(painttoshelf(obj2,receptacle_shelf,robby,5)).
neg(painttoshelf(obj2,receptacle_shelf,robby,7)).
neg(painttoshelf(obj2,receptacle_shelf,robby,8)).
neg(painttoshelf(obj2,receptacle_shelf,robby,9)).
neg(painttoshelf(obj3,receptacle_shelf,robby,0)).
neg(painttoshelf(obj3,receptacle_shelf,robby,1)).
neg(painttoshelf(obj3,receptacle_shelf,robby,10)).
neg(painttoshelf(obj3,receptacle_shelf,robby,11)).
neg(painttoshelf(obj3,receptacle_shelf,robby,12)).
neg(painttoshelf(obj3,receptacle_shelf,robby,13)).
neg(painttoshelf(obj3,receptacle_shelf,robby,14)).
neg(painttoshelf(obj3,receptacle_shelf,robby,15)).
neg(painttoshelf(obj3,receptacle_shelf,robby,16)).
neg(painttoshelf(obj3,receptacle_shelf,robby,2)).
neg(painttoshelf(obj3,receptacle_shelf,robby,3)).
neg(painttoshelf(obj3,receptacle_shelf,robby,4)).
neg(painttoshelf(obj3,receptacle_shelf,robby,5)).
neg(painttoshelf(obj3,receptacle_shelf,robby,6)).
neg(painttoshelf(obj3,receptacle_shelf,robby,7)).
neg(painttoshelf(obj3,receptacle_shelf,robby,8)).
neg(painttoshelf(obj3,receptacle_shelf,robby,9)).
