neg(next_cell(1,1,onecoin)).
neg(next_cell(1,1,twocoins)).
neg(next_cell(1,1,zerocoins)).
neg(next_cell(1,2,onecoin)).
neg(next_cell(1,2,twocoins)).
neg(next_cell(1,2,zerocoins)).
neg(next_cell(1,3,onecoin)).
neg(next_cell(1,3,twocoins)).
neg(next_cell(1,3,zerocoins)).
neg(next_cell(1,4,onecoin)).
neg(next_cell(1,4,twocoins)).
neg(next_cell(1,4,zerocoins)).
neg(next_cell(1,5,onecoin)).
neg(next_cell(1,5,twocoins)).
neg(next_cell(1,5,zerocoins)).
neg(next_cell(1,6,onecoin)).
neg(next_cell(1,6,twocoins)).
neg(next_cell(1,6,zerocoins)).
neg(next_cell(1,7,onecoin)).
neg(next_cell(1,7,twocoins)).
neg(next_cell(1,7,zerocoins)).
neg(next_cell(1,8,onecoin)).
neg(next_cell(1,8,twocoins)).
neg(next_cell(1,8,zerocoins)).
neg(next_cell(10,1,twocoins)).
neg(next_cell(10,1,zerocoins)).
neg(next_cell(10,2,onecoin)).
neg(next_cell(10,2,zerocoins)).
neg(next_cell(10,3,twocoins)).
neg(next_cell(10,3,zerocoins)).
neg(next_cell(10,4,twocoins)).
neg(next_cell(10,4,zerocoins)).
neg(next_cell(10,5,onecoin)).
neg(next_cell(10,5,twocoins)).
neg(next_cell(10,6,twocoins)).
neg(next_cell(10,6,zerocoins)).
neg(next_cell(10,7,twocoins)).
neg(next_cell(10,7,zerocoins)).
neg(next_cell(10,8,twocoins)).
neg(next_cell(10,8,zerocoins)).
neg(next_cell(100,1,onecoin)).
neg(next_cell(100,1,twocoins)).
neg(next_cell(100,1,zerocoins)).
neg(next_cell(100,2,onecoin)).
neg(next_cell(100,2,twocoins)).
neg(next_cell(100,2,zerocoins)).
neg(next_cell(100,3,onecoin)).
neg(next_cell(100,3,twocoins)).
neg(next_cell(100,3,zerocoins)).
neg(next_cell(100,4,onecoin)).
neg(next_cell(100,4,twocoins)).
neg(next_cell(100,4,zerocoins)).
neg(next_cell(100,5,onecoin)).
neg(next_cell(100,5,twocoins)).
neg(next_cell(100,5,zerocoins)).
neg(next_cell(100,6,onecoin)).
neg(next_cell(100,6,twocoins)).
neg(next_cell(100,6,zerocoins)).
neg(next_cell(100,7,onecoin)).
neg(next_cell(100,7,twocoins)).
neg(next_cell(100,7,zerocoins)).
neg(next_cell(100,8,onecoin)).
neg(next_cell(100,8,twocoins)).
neg(next_cell(100,8,zerocoins)).
neg(next_cell(101,1,twocoins)).
neg(next_cell(101,1,zerocoins)).
neg(next_cell(101,2,twocoins)).
neg(next_cell(101,2,zerocoins)).
neg(next_cell(101,3,twocoins)).
neg(next_cell(101,3,zerocoins)).
neg(next_cell(101,4,onecoin)).
neg(next_cell(101,4,zerocoins)).
neg(next_cell(101,5,twocoins)).
neg(next_cell(101,5,zerocoins)).
neg(next_cell(101,6,twocoins)).
neg(next_cell(101,6,zerocoins)).
neg(next_cell(101,7,onecoin)).
neg(next_cell(101,7,twocoins)).
neg(next_cell(101,8,twocoins)).
neg(next_cell(101,8,zerocoins)).
neg(next_cell(102,1,onecoin)).
neg(next_cell(102,1,twocoins)).
neg(next_cell(102,1,zerocoins)).
neg(next_cell(102,2,onecoin)).
neg(next_cell(102,2,twocoins)).
neg(next_cell(102,2,zerocoins)).
neg(next_cell(102,3,onecoin)).
neg(next_cell(102,3,twocoins)).
neg(next_cell(102,3,zerocoins)).
neg(next_cell(102,4,onecoin)).
neg(next_cell(102,4,twocoins)).
neg(next_cell(102,4,zerocoins)).
neg(next_cell(102,5,onecoin)).
neg(next_cell(102,5,twocoins)).
neg(next_cell(102,5,zerocoins)).
neg(next_cell(102,6,onecoin)).
neg(next_cell(102,6,twocoins)).
neg(next_cell(102,6,zerocoins)).
neg(next_cell(102,7,onecoin)).
neg(next_cell(102,7,twocoins)).
neg(next_cell(102,7,zerocoins)).
neg(next_cell(102,8,onecoin)).
neg(next_cell(102,8,twocoins)).
neg(next_cell(102,8,zerocoins)).
neg(next_cell(103,1,onecoin)).
neg(next_cell(103,1,zerocoins)).
neg(next_cell(103,2,onecoin)).
neg(next_cell(103,2,zerocoins)).
neg(next_cell(103,3,onecoin)).
neg(next_cell(103,3,twocoins)).
neg(next_cell(103,4,onecoin)).
neg(next_cell(103,4,twocoins)).
neg(next_cell(103,5,onecoin)).
neg(next_cell(103,5,twocoins)).
neg(next_cell(103,6,twocoins)).
neg(next_cell(103,6,zerocoins)).
neg(next_cell(103,7,twocoins)).
neg(next_cell(103,7,zerocoins)).
neg(next_cell(103,8,onecoin)).
neg(next_cell(103,8,zerocoins)).
neg(next_cell(104,1,onecoin)).
neg(next_cell(104,1,twocoins)).
neg(next_cell(104,1,zerocoins)).
neg(next_cell(104,2,onecoin)).
neg(next_cell(104,2,twocoins)).
neg(next_cell(104,2,zerocoins)).
neg(next_cell(104,3,onecoin)).
neg(next_cell(104,3,twocoins)).
neg(next_cell(104,3,zerocoins)).
neg(next_cell(104,4,onecoin)).
neg(next_cell(104,4,twocoins)).
neg(next_cell(104,4,zerocoins)).
neg(next_cell(104,5,onecoin)).
neg(next_cell(104,5,twocoins)).
neg(next_cell(104,5,zerocoins)).
neg(next_cell(104,6,onecoin)).
neg(next_cell(104,6,twocoins)).
neg(next_cell(104,6,zerocoins)).
neg(next_cell(104,7,onecoin)).
neg(next_cell(104,7,twocoins)).
neg(next_cell(104,7,zerocoins)).
neg(next_cell(104,8,onecoin)).
neg(next_cell(104,8,twocoins)).
neg(next_cell(104,8,zerocoins)).
neg(next_cell(105,1,onecoin)).
neg(next_cell(105,1,zerocoins)).
neg(next_cell(105,2,onecoin)).
neg(next_cell(105,2,zerocoins)).
neg(next_cell(105,3,onecoin)).
neg(next_cell(105,3,twocoins)).
neg(next_cell(105,4,onecoin)).
neg(next_cell(105,4,zerocoins)).
neg(next_cell(105,5,onecoin)).
neg(next_cell(105,5,twocoins)).
neg(next_cell(105,6,twocoins)).
neg(next_cell(105,6,zerocoins)).
neg(next_cell(105,7,twocoins)).
neg(next_cell(105,7,zerocoins)).
neg(next_cell(105,8,onecoin)).
neg(next_cell(105,8,twocoins)).
neg(next_cell(106,1,twocoins)).
neg(next_cell(106,1,zerocoins)).
neg(next_cell(106,2,twocoins)).
neg(next_cell(106,2,zerocoins)).
neg(next_cell(106,3,twocoins)).
neg(next_cell(106,3,zerocoins)).
neg(next_cell(106,4,onecoin)).
neg(next_cell(106,4,twocoins)).
neg(next_cell(106,5,twocoins)).
neg(next_cell(106,5,zerocoins)).
neg(next_cell(106,6,onecoin)).
neg(next_cell(106,6,twocoins)).
neg(next_cell(106,7,onecoin)).
neg(next_cell(106,7,zerocoins)).
neg(next_cell(106,8,onecoin)).
neg(next_cell(106,8,zerocoins)).
neg(next_cell(11,1,onecoin)).
neg(next_cell(11,1,zerocoins)).
neg(next_cell(11,2,twocoins)).
neg(next_cell(11,2,zerocoins)).
neg(next_cell(11,3,twocoins)).
neg(next_cell(11,3,zerocoins)).
neg(next_cell(11,4,onecoin)).
neg(next_cell(11,4,twocoins)).
neg(next_cell(11,5,onecoin)).
neg(next_cell(11,5,twocoins)).
neg(next_cell(11,6,onecoin)).
neg(next_cell(11,6,twocoins)).
neg(next_cell(11,7,onecoin)).
neg(next_cell(11,7,zerocoins)).
neg(next_cell(11,8,onecoin)).
neg(next_cell(11,8,zerocoins)).
neg(next_cell(12,1,onecoin)).
neg(next_cell(12,1,twocoins)).
neg(next_cell(12,1,zerocoins)).
neg(next_cell(12,2,onecoin)).
neg(next_cell(12,2,twocoins)).
neg(next_cell(12,2,zerocoins)).
neg(next_cell(12,3,onecoin)).
neg(next_cell(12,3,twocoins)).
neg(next_cell(12,3,zerocoins)).
neg(next_cell(12,4,onecoin)).
neg(next_cell(12,4,twocoins)).
neg(next_cell(12,4,zerocoins)).
neg(next_cell(12,5,onecoin)).
neg(next_cell(12,5,twocoins)).
neg(next_cell(12,5,zerocoins)).
neg(next_cell(12,6,onecoin)).
neg(next_cell(12,6,twocoins)).
neg(next_cell(12,6,zerocoins)).
neg(next_cell(12,7,onecoin)).
neg(next_cell(12,7,twocoins)).
neg(next_cell(12,7,zerocoins)).
neg(next_cell(12,8,onecoin)).
neg(next_cell(12,8,twocoins)).
neg(next_cell(12,8,zerocoins)).
neg(next_cell(13,1,onecoin)).
neg(next_cell(13,1,zerocoins)).
neg(next_cell(13,2,onecoin)).
neg(next_cell(13,2,zerocoins)).
neg(next_cell(13,3,onecoin)).
neg(next_cell(13,3,twocoins)).
neg(next_cell(13,4,onecoin)).
neg(next_cell(13,4,twocoins)).
neg(next_cell(13,5,onecoin)).
neg(next_cell(13,5,twocoins)).
neg(next_cell(13,6,twocoins)).
neg(next_cell(13,6,zerocoins)).
neg(next_cell(13,7,onecoin)).
neg(next_cell(13,7,zerocoins)).
neg(next_cell(13,8,twocoins)).
neg(next_cell(13,8,zerocoins)).
neg(next_cell(14,1,onecoin)).
neg(next_cell(14,1,twocoins)).
neg(next_cell(14,2,onecoin)).
neg(next_cell(14,2,zerocoins)).
neg(next_cell(14,3,onecoin)).
neg(next_cell(14,3,zerocoins)).
neg(next_cell(14,4,twocoins)).
neg(next_cell(14,4,zerocoins)).
neg(next_cell(14,5,onecoin)).
neg(next_cell(14,5,twocoins)).
neg(next_cell(14,6,twocoins)).
neg(next_cell(14,6,zerocoins)).
neg(next_cell(14,7,twocoins)).
neg(next_cell(14,7,zerocoins)).
neg(next_cell(14,8,twocoins)).
neg(next_cell(14,8,zerocoins)).
neg(next_cell(15,1,twocoins)).
neg(next_cell(15,1,zerocoins)).
neg(next_cell(15,2,twocoins)).
neg(next_cell(15,2,zerocoins)).
neg(next_cell(15,3,onecoin)).
neg(next_cell(15,3,zerocoins)).
neg(next_cell(15,4,twocoins)).
neg(next_cell(15,4,zerocoins)).
neg(next_cell(15,5,twocoins)).
neg(next_cell(15,5,zerocoins)).
neg(next_cell(15,6,onecoin)).
neg(next_cell(15,6,twocoins)).
neg(next_cell(15,7,twocoins)).
neg(next_cell(15,7,zerocoins)).
neg(next_cell(15,8,twocoins)).
neg(next_cell(15,8,zerocoins)).
neg(next_cell(16,1,onecoin)).
neg(next_cell(16,1,twocoins)).
neg(next_cell(16,1,zerocoins)).
neg(next_cell(16,2,onecoin)).
neg(next_cell(16,2,twocoins)).
neg(next_cell(16,2,zerocoins)).
neg(next_cell(16,3,onecoin)).
neg(next_cell(16,3,twocoins)).
neg(next_cell(16,3,zerocoins)).
neg(next_cell(16,4,onecoin)).
neg(next_cell(16,4,twocoins)).
neg(next_cell(16,4,zerocoins)).
neg(next_cell(16,5,onecoin)).
neg(next_cell(16,5,twocoins)).
neg(next_cell(16,5,zerocoins)).
neg(next_cell(16,6,onecoin)).
neg(next_cell(16,6,twocoins)).
neg(next_cell(16,6,zerocoins)).
neg(next_cell(16,7,onecoin)).
neg(next_cell(16,7,twocoins)).
neg(next_cell(16,7,zerocoins)).
neg(next_cell(16,8,onecoin)).
neg(next_cell(16,8,twocoins)).
neg(next_cell(16,8,zerocoins)).
neg(next_cell(17,1,onecoin)).
neg(next_cell(17,1,twocoins)).
neg(next_cell(17,2,twocoins)).
neg(next_cell(17,2,zerocoins)).
neg(next_cell(17,3,onecoin)).
neg(next_cell(17,3,twocoins)).
neg(next_cell(17,4,onecoin)).
neg(next_cell(17,4,zerocoins)).
neg(next_cell(17,5,onecoin)).
neg(next_cell(17,5,zerocoins)).
neg(next_cell(17,6,twocoins)).
neg(next_cell(17,6,zerocoins)).
neg(next_cell(17,7,twocoins)).
neg(next_cell(17,7,zerocoins)).
neg(next_cell(17,8,twocoins)).
neg(next_cell(17,8,zerocoins)).
neg(next_cell(18,1,onecoin)).
neg(next_cell(18,1,twocoins)).
neg(next_cell(18,1,zerocoins)).
neg(next_cell(18,2,onecoin)).
neg(next_cell(18,2,twocoins)).
neg(next_cell(18,2,zerocoins)).
neg(next_cell(18,3,onecoin)).
neg(next_cell(18,3,twocoins)).
neg(next_cell(18,3,zerocoins)).
neg(next_cell(18,4,onecoin)).
neg(next_cell(18,4,twocoins)).
neg(next_cell(18,4,zerocoins)).
neg(next_cell(18,5,onecoin)).
neg(next_cell(18,5,twocoins)).
neg(next_cell(18,5,zerocoins)).
neg(next_cell(18,6,onecoin)).
neg(next_cell(18,6,twocoins)).
neg(next_cell(18,6,zerocoins)).
neg(next_cell(18,7,onecoin)).
neg(next_cell(18,7,twocoins)).
neg(next_cell(18,7,zerocoins)).
neg(next_cell(18,8,onecoin)).
neg(next_cell(18,8,twocoins)).
neg(next_cell(18,8,zerocoins)).
neg(next_cell(19,1,onecoin)).
neg(next_cell(19,1,twocoins)).
neg(next_cell(19,2,onecoin)).
neg(next_cell(19,2,zerocoins)).
neg(next_cell(19,3,onecoin)).
neg(next_cell(19,3,zerocoins)).
neg(next_cell(19,4,onecoin)).
neg(next_cell(19,4,zerocoins)).
neg(next_cell(19,5,onecoin)).
neg(next_cell(19,5,twocoins)).
neg(next_cell(19,6,twocoins)).
neg(next_cell(19,6,zerocoins)).
neg(next_cell(19,7,twocoins)).
neg(next_cell(19,7,zerocoins)).
neg(next_cell(19,8,onecoin)).
neg(next_cell(19,8,twocoins)).
neg(next_cell(2,1,twocoins)).
neg(next_cell(2,1,zerocoins)).
neg(next_cell(2,2,onecoin)).
neg(next_cell(2,2,twocoins)).
neg(next_cell(2,3,twocoins)).
neg(next_cell(2,3,zerocoins)).
neg(next_cell(2,4,onecoin)).
neg(next_cell(2,4,zerocoins)).
neg(next_cell(2,5,onecoin)).
neg(next_cell(2,5,twocoins)).
neg(next_cell(2,6,onecoin)).
neg(next_cell(2,6,zerocoins)).
neg(next_cell(2,7,onecoin)).
neg(next_cell(2,7,twocoins)).
neg(next_cell(2,8,onecoin)).
neg(next_cell(2,8,zerocoins)).
neg(next_cell(20,1,onecoin)).
neg(next_cell(20,1,zerocoins)).
neg(next_cell(20,2,twocoins)).
neg(next_cell(20,2,zerocoins)).
neg(next_cell(20,3,twocoins)).
neg(next_cell(20,3,zerocoins)).
neg(next_cell(20,4,onecoin)).
neg(next_cell(20,4,twocoins)).
neg(next_cell(20,5,onecoin)).
neg(next_cell(20,5,twocoins)).
neg(next_cell(20,6,twocoins)).
neg(next_cell(20,6,zerocoins)).
neg(next_cell(20,7,twocoins)).
neg(next_cell(20,7,zerocoins)).
neg(next_cell(20,8,onecoin)).
neg(next_cell(20,8,zerocoins)).
neg(next_cell(21,1,onecoin)).
neg(next_cell(21,1,zerocoins)).
neg(next_cell(21,2,onecoin)).
neg(next_cell(21,2,zerocoins)).
neg(next_cell(21,3,onecoin)).
neg(next_cell(21,3,zerocoins)).
neg(next_cell(21,4,onecoin)).
neg(next_cell(21,4,twocoins)).
neg(next_cell(21,5,twocoins)).
neg(next_cell(21,5,zerocoins)).
neg(next_cell(21,6,onecoin)).
neg(next_cell(21,6,twocoins)).
neg(next_cell(21,7,twocoins)).
neg(next_cell(21,7,zerocoins)).
neg(next_cell(21,8,onecoin)).
neg(next_cell(21,8,twocoins)).
neg(next_cell(22,1,twocoins)).
neg(next_cell(22,1,zerocoins)).
neg(next_cell(22,2,onecoin)).
neg(next_cell(22,2,twocoins)).
neg(next_cell(22,3,twocoins)).
neg(next_cell(22,3,zerocoins)).
neg(next_cell(22,4,onecoin)).
neg(next_cell(22,4,twocoins)).
neg(next_cell(22,5,onecoin)).
neg(next_cell(22,5,twocoins)).
neg(next_cell(22,6,onecoin)).
neg(next_cell(22,6,zerocoins)).
neg(next_cell(22,7,onecoin)).
neg(next_cell(22,7,zerocoins)).
neg(next_cell(22,8,onecoin)).
neg(next_cell(22,8,zerocoins)).
neg(next_cell(23,1,onecoin)).
neg(next_cell(23,1,zerocoins)).
neg(next_cell(23,2,twocoins)).
neg(next_cell(23,2,zerocoins)).
neg(next_cell(23,3,twocoins)).
neg(next_cell(23,3,zerocoins)).
neg(next_cell(23,4,onecoin)).
neg(next_cell(23,4,twocoins)).
neg(next_cell(23,5,onecoin)).
neg(next_cell(23,5,zerocoins)).
neg(next_cell(23,6,twocoins)).
neg(next_cell(23,6,zerocoins)).
neg(next_cell(23,7,twocoins)).
neg(next_cell(23,7,zerocoins)).
neg(next_cell(23,8,onecoin)).
neg(next_cell(23,8,twocoins)).
neg(next_cell(24,1,twocoins)).
neg(next_cell(24,1,zerocoins)).
neg(next_cell(24,2,twocoins)).
neg(next_cell(24,2,zerocoins)).
neg(next_cell(24,3,onecoin)).
neg(next_cell(24,3,twocoins)).
neg(next_cell(24,4,twocoins)).
neg(next_cell(24,4,zerocoins)).
neg(next_cell(24,5,onecoin)).
neg(next_cell(24,5,twocoins)).
neg(next_cell(24,6,twocoins)).
neg(next_cell(24,6,zerocoins)).
neg(next_cell(24,7,onecoin)).
neg(next_cell(24,7,zerocoins)).
neg(next_cell(24,8,onecoin)).
neg(next_cell(24,8,zerocoins)).
neg(next_cell(25,1,onecoin)).
neg(next_cell(25,1,twocoins)).
neg(next_cell(25,1,zerocoins)).
neg(next_cell(25,2,onecoin)).
neg(next_cell(25,2,twocoins)).
neg(next_cell(25,2,zerocoins)).
neg(next_cell(25,3,onecoin)).
neg(next_cell(25,3,twocoins)).
neg(next_cell(25,3,zerocoins)).
neg(next_cell(25,4,onecoin)).
neg(next_cell(25,4,twocoins)).
neg(next_cell(25,4,zerocoins)).
neg(next_cell(25,5,onecoin)).
neg(next_cell(25,5,twocoins)).
neg(next_cell(25,5,zerocoins)).
neg(next_cell(25,6,onecoin)).
neg(next_cell(25,6,twocoins)).
neg(next_cell(25,6,zerocoins)).
neg(next_cell(25,7,onecoin)).
neg(next_cell(25,7,twocoins)).
neg(next_cell(25,7,zerocoins)).
neg(next_cell(25,8,onecoin)).
neg(next_cell(25,8,twocoins)).
neg(next_cell(25,8,zerocoins)).
neg(next_cell(26,1,onecoin)).
neg(next_cell(26,1,twocoins)).
neg(next_cell(26,2,onecoin)).
neg(next_cell(26,2,zerocoins)).
neg(next_cell(26,3,onecoin)).
neg(next_cell(26,3,zerocoins)).
neg(next_cell(26,4,onecoin)).
neg(next_cell(26,4,twocoins)).
neg(next_cell(26,5,onecoin)).
neg(next_cell(26,5,twocoins)).
neg(next_cell(26,6,onecoin)).
neg(next_cell(26,6,twocoins)).
neg(next_cell(26,7,onecoin)).
neg(next_cell(26,7,zerocoins)).
neg(next_cell(26,8,onecoin)).
neg(next_cell(26,8,zerocoins)).
neg(next_cell(27,1,onecoin)).
neg(next_cell(27,1,zerocoins)).
neg(next_cell(27,2,twocoins)).
neg(next_cell(27,2,zerocoins)).
neg(next_cell(27,3,onecoin)).
neg(next_cell(27,3,twocoins)).
neg(next_cell(27,4,onecoin)).
neg(next_cell(27,4,twocoins)).
neg(next_cell(27,5,onecoin)).
neg(next_cell(27,5,twocoins)).
neg(next_cell(27,6,onecoin)).
neg(next_cell(27,6,zerocoins)).
neg(next_cell(27,7,onecoin)).
neg(next_cell(27,7,zerocoins)).
neg(next_cell(27,8,twocoins)).
neg(next_cell(27,8,zerocoins)).
neg(next_cell(28,1,onecoin)).
neg(next_cell(28,1,zerocoins)).
neg(next_cell(28,2,onecoin)).
neg(next_cell(28,2,zerocoins)).
neg(next_cell(28,3,onecoin)).
neg(next_cell(28,3,twocoins)).
neg(next_cell(28,4,onecoin)).
neg(next_cell(28,4,twocoins)).
neg(next_cell(28,5,twocoins)).
neg(next_cell(28,5,zerocoins)).
neg(next_cell(28,6,onecoin)).
neg(next_cell(28,6,twocoins)).
neg(next_cell(28,7,onecoin)).
neg(next_cell(28,7,zerocoins)).
neg(next_cell(28,8,twocoins)).
neg(next_cell(28,8,zerocoins)).
neg(next_cell(29,1,onecoin)).
neg(next_cell(29,1,twocoins)).
neg(next_cell(29,1,zerocoins)).
neg(next_cell(29,2,onecoin)).
neg(next_cell(29,2,twocoins)).
neg(next_cell(29,2,zerocoins)).
neg(next_cell(29,3,onecoin)).
neg(next_cell(29,3,twocoins)).
neg(next_cell(29,3,zerocoins)).
neg(next_cell(29,4,onecoin)).
neg(next_cell(29,4,twocoins)).
neg(next_cell(29,4,zerocoins)).
neg(next_cell(29,5,onecoin)).
neg(next_cell(29,5,twocoins)).
neg(next_cell(29,5,zerocoins)).
neg(next_cell(29,6,onecoin)).
neg(next_cell(29,6,twocoins)).
neg(next_cell(29,6,zerocoins)).
neg(next_cell(29,7,onecoin)).
neg(next_cell(29,7,twocoins)).
neg(next_cell(29,7,zerocoins)).
neg(next_cell(29,8,onecoin)).
neg(next_cell(29,8,twocoins)).
neg(next_cell(29,8,zerocoins)).
neg(next_cell(3,1,onecoin)).
neg(next_cell(3,1,twocoins)).
neg(next_cell(3,1,zerocoins)).
neg(next_cell(3,2,onecoin)).
neg(next_cell(3,2,twocoins)).
neg(next_cell(3,2,zerocoins)).
neg(next_cell(3,3,onecoin)).
neg(next_cell(3,3,twocoins)).
neg(next_cell(3,3,zerocoins)).
neg(next_cell(3,4,onecoin)).
neg(next_cell(3,4,twocoins)).
neg(next_cell(3,4,zerocoins)).
neg(next_cell(3,5,onecoin)).
neg(next_cell(3,5,twocoins)).
neg(next_cell(3,5,zerocoins)).
neg(next_cell(3,6,onecoin)).
neg(next_cell(3,6,twocoins)).
neg(next_cell(3,6,zerocoins)).
neg(next_cell(3,7,onecoin)).
neg(next_cell(3,7,twocoins)).
neg(next_cell(3,7,zerocoins)).
neg(next_cell(3,8,onecoin)).
neg(next_cell(3,8,twocoins)).
neg(next_cell(3,8,zerocoins)).
neg(next_cell(30,1,twocoins)).
neg(next_cell(30,1,zerocoins)).
neg(next_cell(30,2,onecoin)).
neg(next_cell(30,2,twocoins)).
neg(next_cell(30,3,twocoins)).
neg(next_cell(30,3,zerocoins)).
neg(next_cell(30,4,onecoin)).
neg(next_cell(30,4,twocoins)).
neg(next_cell(30,5,twocoins)).
neg(next_cell(30,5,zerocoins)).
neg(next_cell(30,6,onecoin)).
neg(next_cell(30,6,zerocoins)).
neg(next_cell(30,7,onecoin)).
neg(next_cell(30,7,zerocoins)).
neg(next_cell(30,8,twocoins)).
neg(next_cell(30,8,zerocoins)).
neg(next_cell(31,1,onecoin)).
neg(next_cell(31,1,zerocoins)).
neg(next_cell(31,2,twocoins)).
neg(next_cell(31,2,zerocoins)).
neg(next_cell(31,3,onecoin)).
neg(next_cell(31,3,twocoins)).
neg(next_cell(31,4,twocoins)).
neg(next_cell(31,4,zerocoins)).
neg(next_cell(31,5,onecoin)).
neg(next_cell(31,5,twocoins)).
neg(next_cell(31,6,onecoin)).
neg(next_cell(31,6,zerocoins)).
neg(next_cell(31,7,twocoins)).
neg(next_cell(31,7,zerocoins)).
neg(next_cell(31,8,twocoins)).
neg(next_cell(31,8,zerocoins)).
neg(next_cell(32,1,onecoin)).
neg(next_cell(32,1,zerocoins)).
neg(next_cell(32,2,onecoin)).
neg(next_cell(32,2,twocoins)).
neg(next_cell(32,3,onecoin)).
neg(next_cell(32,3,zerocoins)).
neg(next_cell(32,4,onecoin)).
neg(next_cell(32,4,twocoins)).
neg(next_cell(32,5,onecoin)).
neg(next_cell(32,5,zerocoins)).
neg(next_cell(32,6,twocoins)).
neg(next_cell(32,6,zerocoins)).
neg(next_cell(32,7,onecoin)).
neg(next_cell(32,7,twocoins)).
neg(next_cell(32,8,twocoins)).
neg(next_cell(32,8,zerocoins)).
neg(next_cell(33,1,twocoins)).
neg(next_cell(33,1,zerocoins)).
neg(next_cell(33,2,twocoins)).
neg(next_cell(33,2,zerocoins)).
neg(next_cell(33,3,onecoin)).
neg(next_cell(33,3,zerocoins)).
neg(next_cell(33,4,twocoins)).
neg(next_cell(33,4,zerocoins)).
neg(next_cell(33,5,onecoin)).
neg(next_cell(33,5,twocoins)).
neg(next_cell(33,6,twocoins)).
neg(next_cell(33,6,zerocoins)).
neg(next_cell(33,7,onecoin)).
neg(next_cell(33,7,twocoins)).
neg(next_cell(33,8,onecoin)).
neg(next_cell(33,8,zerocoins)).
neg(next_cell(34,1,onecoin)).
neg(next_cell(34,1,twocoins)).
neg(next_cell(34,1,zerocoins)).
neg(next_cell(34,2,onecoin)).
neg(next_cell(34,2,twocoins)).
neg(next_cell(34,2,zerocoins)).
neg(next_cell(34,3,onecoin)).
neg(next_cell(34,3,twocoins)).
neg(next_cell(34,3,zerocoins)).
neg(next_cell(34,4,onecoin)).
neg(next_cell(34,4,twocoins)).
neg(next_cell(34,4,zerocoins)).
neg(next_cell(34,5,onecoin)).
neg(next_cell(34,5,twocoins)).
neg(next_cell(34,5,zerocoins)).
neg(next_cell(34,6,onecoin)).
neg(next_cell(34,6,twocoins)).
neg(next_cell(34,6,zerocoins)).
neg(next_cell(34,7,onecoin)).
neg(next_cell(34,7,twocoins)).
neg(next_cell(34,7,zerocoins)).
neg(next_cell(34,8,onecoin)).
neg(next_cell(34,8,twocoins)).
neg(next_cell(34,8,zerocoins)).
neg(next_cell(35,1,onecoin)).
neg(next_cell(35,1,zerocoins)).
neg(next_cell(35,2,onecoin)).
neg(next_cell(35,2,zerocoins)).
neg(next_cell(35,3,onecoin)).
neg(next_cell(35,3,twocoins)).
neg(next_cell(35,4,twocoins)).
neg(next_cell(35,4,zerocoins)).
neg(next_cell(35,5,onecoin)).
neg(next_cell(35,5,twocoins)).
neg(next_cell(35,6,onecoin)).
neg(next_cell(35,6,twocoins)).
neg(next_cell(35,7,twocoins)).
neg(next_cell(35,7,zerocoins)).
neg(next_cell(35,8,onecoin)).
neg(next_cell(35,8,zerocoins)).
neg(next_cell(36,1,onecoin)).
neg(next_cell(36,1,twocoins)).
neg(next_cell(36,2,twocoins)).
neg(next_cell(36,2,zerocoins)).
neg(next_cell(36,3,onecoin)).
neg(next_cell(36,3,twocoins)).
neg(next_cell(36,4,onecoin)).
neg(next_cell(36,4,zerocoins)).
neg(next_cell(36,5,onecoin)).
neg(next_cell(36,5,twocoins)).
neg(next_cell(36,6,onecoin)).
neg(next_cell(36,6,zerocoins)).
neg(next_cell(36,7,twocoins)).
neg(next_cell(36,7,zerocoins)).
neg(next_cell(36,8,onecoin)).
neg(next_cell(36,8,zerocoins)).
neg(next_cell(37,1,onecoin)).
neg(next_cell(37,1,twocoins)).
neg(next_cell(37,1,zerocoins)).
neg(next_cell(37,2,onecoin)).
neg(next_cell(37,2,twocoins)).
neg(next_cell(37,2,zerocoins)).
neg(next_cell(37,3,onecoin)).
neg(next_cell(37,3,twocoins)).
neg(next_cell(37,3,zerocoins)).
neg(next_cell(37,4,onecoin)).
neg(next_cell(37,4,twocoins)).
neg(next_cell(37,4,zerocoins)).
neg(next_cell(37,5,onecoin)).
neg(next_cell(37,5,twocoins)).
neg(next_cell(37,5,zerocoins)).
neg(next_cell(37,6,onecoin)).
neg(next_cell(37,6,twocoins)).
neg(next_cell(37,6,zerocoins)).
neg(next_cell(37,7,onecoin)).
neg(next_cell(37,7,twocoins)).
neg(next_cell(37,7,zerocoins)).
neg(next_cell(37,8,onecoin)).
neg(next_cell(37,8,twocoins)).
neg(next_cell(37,8,zerocoins)).
neg(next_cell(38,1,twocoins)).
neg(next_cell(38,1,zerocoins)).
neg(next_cell(38,2,twocoins)).
neg(next_cell(38,2,zerocoins)).
neg(next_cell(38,3,onecoin)).
neg(next_cell(38,3,zerocoins)).
neg(next_cell(38,4,onecoin)).
neg(next_cell(38,4,zerocoins)).
neg(next_cell(38,5,twocoins)).
neg(next_cell(38,5,zerocoins)).
neg(next_cell(38,6,onecoin)).
neg(next_cell(38,6,twocoins)).
neg(next_cell(38,7,twocoins)).
neg(next_cell(38,7,zerocoins)).
neg(next_cell(38,8,onecoin)).
neg(next_cell(38,8,twocoins)).
neg(next_cell(39,1,onecoin)).
neg(next_cell(39,1,zerocoins)).
neg(next_cell(39,2,onecoin)).
neg(next_cell(39,2,zerocoins)).
neg(next_cell(39,3,onecoin)).
neg(next_cell(39,3,twocoins)).
neg(next_cell(39,4,onecoin)).
neg(next_cell(39,4,zerocoins)).
neg(next_cell(39,5,onecoin)).
neg(next_cell(39,5,twocoins)).
neg(next_cell(39,6,twocoins)).
neg(next_cell(39,6,zerocoins)).
neg(next_cell(39,7,twocoins)).
neg(next_cell(39,7,zerocoins)).
neg(next_cell(39,8,onecoin)).
neg(next_cell(39,8,twocoins)).
neg(next_cell(4,1,twocoins)).
neg(next_cell(4,1,zerocoins)).
neg(next_cell(4,2,onecoin)).
neg(next_cell(4,2,twocoins)).
neg(next_cell(4,3,twocoins)).
neg(next_cell(4,3,zerocoins)).
neg(next_cell(4,4,twocoins)).
neg(next_cell(4,4,zerocoins)).
neg(next_cell(4,5,onecoin)).
neg(next_cell(4,5,twocoins)).
neg(next_cell(4,6,onecoin)).
neg(next_cell(4,6,zerocoins)).
neg(next_cell(4,7,twocoins)).
neg(next_cell(4,7,zerocoins)).
neg(next_cell(4,8,onecoin)).
neg(next_cell(4,8,zerocoins)).
neg(next_cell(40,1,twocoins)).
neg(next_cell(40,1,zerocoins)).
neg(next_cell(40,2,twocoins)).
neg(next_cell(40,2,zerocoins)).
neg(next_cell(40,3,onecoin)).
neg(next_cell(40,3,twocoins)).
neg(next_cell(40,4,twocoins)).
neg(next_cell(40,4,zerocoins)).
neg(next_cell(40,5,onecoin)).
neg(next_cell(40,5,zerocoins)).
neg(next_cell(40,6,onecoin)).
neg(next_cell(40,6,zerocoins)).
neg(next_cell(40,7,onecoin)).
neg(next_cell(40,7,twocoins)).
neg(next_cell(40,8,twocoins)).
neg(next_cell(40,8,zerocoins)).
neg(next_cell(41,1,onecoin)).
neg(next_cell(41,1,twocoins)).
neg(next_cell(41,2,twocoins)).
neg(next_cell(41,2,zerocoins)).
neg(next_cell(41,3,twocoins)).
neg(next_cell(41,3,zerocoins)).
neg(next_cell(41,4,onecoin)).
neg(next_cell(41,4,zerocoins)).
neg(next_cell(41,5,onecoin)).
neg(next_cell(41,5,twocoins)).
neg(next_cell(41,6,twocoins)).
neg(next_cell(41,6,zerocoins)).
neg(next_cell(41,7,twocoins)).
neg(next_cell(41,7,zerocoins)).
neg(next_cell(41,8,onecoin)).
neg(next_cell(41,8,zerocoins)).
neg(next_cell(42,1,twocoins)).
neg(next_cell(42,1,zerocoins)).
neg(next_cell(42,2,onecoin)).
neg(next_cell(42,2,zerocoins)).
neg(next_cell(42,3,twocoins)).
neg(next_cell(42,3,zerocoins)).
neg(next_cell(42,4,onecoin)).
neg(next_cell(42,4,twocoins)).
neg(next_cell(42,5,onecoin)).
neg(next_cell(42,5,twocoins)).
neg(next_cell(42,6,onecoin)).
neg(next_cell(42,6,twocoins)).
neg(next_cell(42,7,onecoin)).
neg(next_cell(42,7,zerocoins)).
neg(next_cell(42,8,onecoin)).
neg(next_cell(42,8,zerocoins)).
neg(next_cell(43,1,onecoin)).
neg(next_cell(43,1,zerocoins)).
neg(next_cell(43,2,twocoins)).
neg(next_cell(43,2,zerocoins)).
neg(next_cell(43,3,onecoin)).
neg(next_cell(43,3,twocoins)).
neg(next_cell(43,4,onecoin)).
neg(next_cell(43,4,twocoins)).
neg(next_cell(43,5,onecoin)).
neg(next_cell(43,5,zerocoins)).
neg(next_cell(43,6,onecoin)).
neg(next_cell(43,6,zerocoins)).
neg(next_cell(43,7,twocoins)).
neg(next_cell(43,7,zerocoins)).
neg(next_cell(43,8,onecoin)).
neg(next_cell(43,8,twocoins)).
neg(next_cell(44,1,twocoins)).
neg(next_cell(44,1,zerocoins)).
neg(next_cell(44,2,onecoin)).
neg(next_cell(44,2,zerocoins)).
neg(next_cell(44,3,onecoin)).
neg(next_cell(44,3,twocoins)).
neg(next_cell(44,4,onecoin)).
neg(next_cell(44,4,zerocoins)).
neg(next_cell(44,5,onecoin)).
neg(next_cell(44,5,twocoins)).
neg(next_cell(44,6,onecoin)).
neg(next_cell(44,6,zerocoins)).
neg(next_cell(44,7,twocoins)).
neg(next_cell(44,7,zerocoins)).
neg(next_cell(44,8,onecoin)).
neg(next_cell(44,8,twocoins)).
neg(next_cell(45,1,onecoin)).
neg(next_cell(45,1,zerocoins)).
neg(next_cell(45,2,onecoin)).
neg(next_cell(45,2,twocoins)).
neg(next_cell(45,3,twocoins)).
neg(next_cell(45,3,zerocoins)).
neg(next_cell(45,4,onecoin)).
neg(next_cell(45,4,twocoins)).
neg(next_cell(45,5,onecoin)).
neg(next_cell(45,5,twocoins)).
neg(next_cell(45,6,onecoin)).
neg(next_cell(45,6,zerocoins)).
neg(next_cell(45,7,onecoin)).
neg(next_cell(45,7,zerocoins)).
neg(next_cell(45,8,twocoins)).
neg(next_cell(45,8,zerocoins)).
neg(next_cell(46,1,twocoins)).
neg(next_cell(46,1,zerocoins)).
neg(next_cell(46,2,twocoins)).
neg(next_cell(46,2,zerocoins)).
neg(next_cell(46,3,twocoins)).
neg(next_cell(46,3,zerocoins)).
neg(next_cell(46,4,onecoin)).
neg(next_cell(46,4,twocoins)).
neg(next_cell(46,5,twocoins)).
neg(next_cell(46,5,zerocoins)).
neg(next_cell(46,6,twocoins)).
neg(next_cell(46,6,zerocoins)).
neg(next_cell(46,7,onecoin)).
neg(next_cell(46,7,zerocoins)).
neg(next_cell(46,8,twocoins)).
neg(next_cell(46,8,zerocoins)).
neg(next_cell(47,1,twocoins)).
neg(next_cell(47,1,zerocoins)).
neg(next_cell(47,2,onecoin)).
neg(next_cell(47,2,twocoins)).
neg(next_cell(47,3,onecoin)).
neg(next_cell(47,3,zerocoins)).
neg(next_cell(47,4,onecoin)).
neg(next_cell(47,4,zerocoins)).
neg(next_cell(47,5,onecoin)).
neg(next_cell(47,5,twocoins)).
neg(next_cell(47,6,twocoins)).
neg(next_cell(47,6,zerocoins)).
neg(next_cell(47,7,onecoin)).
neg(next_cell(47,7,twocoins)).
neg(next_cell(47,8,onecoin)).
neg(next_cell(47,8,zerocoins)).
neg(next_cell(48,1,onecoin)).
neg(next_cell(48,1,twocoins)).
neg(next_cell(48,1,zerocoins)).
neg(next_cell(48,2,onecoin)).
neg(next_cell(48,2,twocoins)).
neg(next_cell(48,2,zerocoins)).
neg(next_cell(48,3,onecoin)).
neg(next_cell(48,3,twocoins)).
neg(next_cell(48,3,zerocoins)).
neg(next_cell(48,4,onecoin)).
neg(next_cell(48,4,twocoins)).
neg(next_cell(48,4,zerocoins)).
neg(next_cell(48,5,onecoin)).
neg(next_cell(48,5,twocoins)).
neg(next_cell(48,5,zerocoins)).
neg(next_cell(48,6,onecoin)).
neg(next_cell(48,6,twocoins)).
neg(next_cell(48,6,zerocoins)).
neg(next_cell(48,7,onecoin)).
neg(next_cell(48,7,twocoins)).
neg(next_cell(48,7,zerocoins)).
neg(next_cell(48,8,onecoin)).
neg(next_cell(48,8,twocoins)).
neg(next_cell(48,8,zerocoins)).
neg(next_cell(49,1,onecoin)).
neg(next_cell(49,1,twocoins)).
neg(next_cell(49,2,twocoins)).
neg(next_cell(49,2,zerocoins)).
neg(next_cell(49,3,twocoins)).
neg(next_cell(49,3,zerocoins)).
neg(next_cell(49,4,onecoin)).
neg(next_cell(49,4,twocoins)).
neg(next_cell(49,5,onecoin)).
neg(next_cell(49,5,zerocoins)).
neg(next_cell(49,6,onecoin)).
neg(next_cell(49,6,twocoins)).
neg(next_cell(49,7,onecoin)).
neg(next_cell(49,7,zerocoins)).
neg(next_cell(49,8,onecoin)).
neg(next_cell(49,8,zerocoins)).
neg(next_cell(5,1,onecoin)).
neg(next_cell(5,1,twocoins)).
neg(next_cell(5,1,zerocoins)).
neg(next_cell(5,2,onecoin)).
neg(next_cell(5,2,twocoins)).
neg(next_cell(5,2,zerocoins)).
neg(next_cell(5,3,onecoin)).
neg(next_cell(5,3,twocoins)).
neg(next_cell(5,3,zerocoins)).
neg(next_cell(5,4,onecoin)).
neg(next_cell(5,4,twocoins)).
neg(next_cell(5,4,zerocoins)).
neg(next_cell(5,5,onecoin)).
neg(next_cell(5,5,twocoins)).
neg(next_cell(5,5,zerocoins)).
neg(next_cell(5,6,onecoin)).
neg(next_cell(5,6,twocoins)).
neg(next_cell(5,6,zerocoins)).
neg(next_cell(5,7,onecoin)).
neg(next_cell(5,7,twocoins)).
neg(next_cell(5,7,zerocoins)).
neg(next_cell(5,8,onecoin)).
neg(next_cell(5,8,twocoins)).
neg(next_cell(5,8,zerocoins)).
neg(next_cell(50,1,onecoin)).
neg(next_cell(50,1,twocoins)).
neg(next_cell(50,1,zerocoins)).
neg(next_cell(50,2,onecoin)).
neg(next_cell(50,2,twocoins)).
neg(next_cell(50,2,zerocoins)).
neg(next_cell(50,3,onecoin)).
neg(next_cell(50,3,twocoins)).
neg(next_cell(50,3,zerocoins)).
neg(next_cell(50,4,onecoin)).
neg(next_cell(50,4,twocoins)).
neg(next_cell(50,4,zerocoins)).
neg(next_cell(50,5,onecoin)).
neg(next_cell(50,5,twocoins)).
neg(next_cell(50,5,zerocoins)).
neg(next_cell(50,6,onecoin)).
neg(next_cell(50,6,twocoins)).
neg(next_cell(50,6,zerocoins)).
neg(next_cell(50,7,onecoin)).
neg(next_cell(50,7,twocoins)).
neg(next_cell(50,7,zerocoins)).
neg(next_cell(50,8,onecoin)).
neg(next_cell(50,8,twocoins)).
neg(next_cell(50,8,zerocoins)).
neg(next_cell(51,1,onecoin)).
neg(next_cell(51,1,zerocoins)).
neg(next_cell(51,2,twocoins)).
neg(next_cell(51,2,zerocoins)).
neg(next_cell(51,3,onecoin)).
neg(next_cell(51,3,twocoins)).
neg(next_cell(51,4,twocoins)).
neg(next_cell(51,4,zerocoins)).
neg(next_cell(51,5,onecoin)).
neg(next_cell(51,5,twocoins)).
neg(next_cell(51,6,onecoin)).
neg(next_cell(51,6,twocoins)).
neg(next_cell(51,7,onecoin)).
neg(next_cell(51,7,zerocoins)).
neg(next_cell(51,8,onecoin)).
neg(next_cell(51,8,zerocoins)).
neg(next_cell(52,1,onecoin)).
neg(next_cell(52,1,twocoins)).
neg(next_cell(52,1,zerocoins)).
neg(next_cell(52,2,onecoin)).
neg(next_cell(52,2,twocoins)).
neg(next_cell(52,2,zerocoins)).
neg(next_cell(52,3,onecoin)).
neg(next_cell(52,3,twocoins)).
neg(next_cell(52,3,zerocoins)).
neg(next_cell(52,4,onecoin)).
neg(next_cell(52,4,twocoins)).
neg(next_cell(52,4,zerocoins)).
neg(next_cell(52,5,onecoin)).
neg(next_cell(52,5,twocoins)).
neg(next_cell(52,5,zerocoins)).
neg(next_cell(52,6,onecoin)).
neg(next_cell(52,6,twocoins)).
neg(next_cell(52,6,zerocoins)).
neg(next_cell(52,7,onecoin)).
neg(next_cell(52,7,twocoins)).
neg(next_cell(52,7,zerocoins)).
neg(next_cell(52,8,onecoin)).
neg(next_cell(52,8,twocoins)).
neg(next_cell(52,8,zerocoins)).
neg(next_cell(53,1,twocoins)).
neg(next_cell(53,1,zerocoins)).
neg(next_cell(53,2,onecoin)).
neg(next_cell(53,2,zerocoins)).
neg(next_cell(53,3,twocoins)).
neg(next_cell(53,3,zerocoins)).
neg(next_cell(53,4,onecoin)).
neg(next_cell(53,4,twocoins)).
neg(next_cell(53,5,twocoins)).
neg(next_cell(53,5,zerocoins)).
neg(next_cell(53,6,onecoin)).
neg(next_cell(53,6,twocoins)).
neg(next_cell(53,7,onecoin)).
neg(next_cell(53,7,zerocoins)).
neg(next_cell(53,8,twocoins)).
neg(next_cell(53,8,zerocoins)).
neg(next_cell(54,1,onecoin)).
neg(next_cell(54,1,zerocoins)).
neg(next_cell(54,2,onecoin)).
neg(next_cell(54,2,zerocoins)).
neg(next_cell(54,3,onecoin)).
neg(next_cell(54,3,twocoins)).
neg(next_cell(54,4,onecoin)).
neg(next_cell(54,4,twocoins)).
neg(next_cell(54,5,onecoin)).
neg(next_cell(54,5,twocoins)).
neg(next_cell(54,6,twocoins)).
neg(next_cell(54,6,zerocoins)).
neg(next_cell(54,7,twocoins)).
neg(next_cell(54,7,zerocoins)).
neg(next_cell(54,8,onecoin)).
neg(next_cell(54,8,zerocoins)).
neg(next_cell(55,1,onecoin)).
neg(next_cell(55,1,twocoins)).
neg(next_cell(55,2,twocoins)).
neg(next_cell(55,2,zerocoins)).
neg(next_cell(55,3,twocoins)).
neg(next_cell(55,3,zerocoins)).
neg(next_cell(55,4,onecoin)).
neg(next_cell(55,4,twocoins)).
neg(next_cell(55,5,onecoin)).
neg(next_cell(55,5,zerocoins)).
neg(next_cell(55,6,onecoin)).
neg(next_cell(55,6,twocoins)).
neg(next_cell(55,7,onecoin)).
neg(next_cell(55,7,zerocoins)).
neg(next_cell(55,8,onecoin)).
neg(next_cell(55,8,zerocoins)).
neg(next_cell(56,1,onecoin)).
neg(next_cell(56,1,zerocoins)).
neg(next_cell(56,2,twocoins)).
neg(next_cell(56,2,zerocoins)).
neg(next_cell(56,3,twocoins)).
neg(next_cell(56,3,zerocoins)).
neg(next_cell(56,4,onecoin)).
neg(next_cell(56,4,twocoins)).
neg(next_cell(56,5,onecoin)).
neg(next_cell(56,5,zerocoins)).
neg(next_cell(56,6,twocoins)).
neg(next_cell(56,6,zerocoins)).
neg(next_cell(56,7,twocoins)).
neg(next_cell(56,7,zerocoins)).
neg(next_cell(56,8,onecoin)).
neg(next_cell(56,8,twocoins)).
neg(next_cell(57,1,onecoin)).
neg(next_cell(57,1,twocoins)).
neg(next_cell(57,1,zerocoins)).
neg(next_cell(57,2,onecoin)).
neg(next_cell(57,2,twocoins)).
neg(next_cell(57,2,zerocoins)).
neg(next_cell(57,3,onecoin)).
neg(next_cell(57,3,twocoins)).
neg(next_cell(57,3,zerocoins)).
neg(next_cell(57,4,onecoin)).
neg(next_cell(57,4,twocoins)).
neg(next_cell(57,4,zerocoins)).
neg(next_cell(57,5,onecoin)).
neg(next_cell(57,5,twocoins)).
neg(next_cell(57,5,zerocoins)).
neg(next_cell(57,6,onecoin)).
neg(next_cell(57,6,twocoins)).
neg(next_cell(57,6,zerocoins)).
neg(next_cell(57,7,onecoin)).
neg(next_cell(57,7,twocoins)).
neg(next_cell(57,7,zerocoins)).
neg(next_cell(57,8,onecoin)).
neg(next_cell(57,8,twocoins)).
neg(next_cell(57,8,zerocoins)).
neg(next_cell(58,1,onecoin)).
neg(next_cell(58,1,twocoins)).
neg(next_cell(58,1,zerocoins)).
neg(next_cell(58,2,onecoin)).
neg(next_cell(58,2,twocoins)).
neg(next_cell(58,2,zerocoins)).
neg(next_cell(58,3,onecoin)).
neg(next_cell(58,3,twocoins)).
neg(next_cell(58,3,zerocoins)).
neg(next_cell(58,4,onecoin)).
neg(next_cell(58,4,twocoins)).
neg(next_cell(58,4,zerocoins)).
neg(next_cell(58,5,onecoin)).
neg(next_cell(58,5,twocoins)).
neg(next_cell(58,5,zerocoins)).
neg(next_cell(58,6,onecoin)).
neg(next_cell(58,6,twocoins)).
neg(next_cell(58,6,zerocoins)).
neg(next_cell(58,7,onecoin)).
neg(next_cell(58,7,twocoins)).
neg(next_cell(58,7,zerocoins)).
neg(next_cell(58,8,onecoin)).
neg(next_cell(58,8,twocoins)).
neg(next_cell(58,8,zerocoins)).
neg(next_cell(59,1,onecoin)).
neg(next_cell(59,1,twocoins)).
neg(next_cell(59,1,zerocoins)).
neg(next_cell(59,2,onecoin)).
neg(next_cell(59,2,twocoins)).
neg(next_cell(59,2,zerocoins)).
neg(next_cell(59,3,onecoin)).
neg(next_cell(59,3,twocoins)).
neg(next_cell(59,3,zerocoins)).
neg(next_cell(59,4,onecoin)).
neg(next_cell(59,4,twocoins)).
neg(next_cell(59,4,zerocoins)).
neg(next_cell(59,5,onecoin)).
neg(next_cell(59,5,twocoins)).
neg(next_cell(59,5,zerocoins)).
neg(next_cell(59,6,onecoin)).
neg(next_cell(59,6,twocoins)).
neg(next_cell(59,6,zerocoins)).
neg(next_cell(59,7,onecoin)).
neg(next_cell(59,7,twocoins)).
neg(next_cell(59,7,zerocoins)).
neg(next_cell(59,8,onecoin)).
neg(next_cell(59,8,twocoins)).
neg(next_cell(59,8,zerocoins)).
neg(next_cell(6,1,onecoin)).
neg(next_cell(6,1,twocoins)).
neg(next_cell(6,1,zerocoins)).
neg(next_cell(6,2,onecoin)).
neg(next_cell(6,2,twocoins)).
neg(next_cell(6,2,zerocoins)).
neg(next_cell(6,3,onecoin)).
neg(next_cell(6,3,twocoins)).
neg(next_cell(6,3,zerocoins)).
neg(next_cell(6,4,onecoin)).
neg(next_cell(6,4,twocoins)).
neg(next_cell(6,4,zerocoins)).
neg(next_cell(6,5,onecoin)).
neg(next_cell(6,5,twocoins)).
neg(next_cell(6,5,zerocoins)).
neg(next_cell(6,6,onecoin)).
neg(next_cell(6,6,twocoins)).
neg(next_cell(6,6,zerocoins)).
neg(next_cell(6,7,onecoin)).
neg(next_cell(6,7,twocoins)).
neg(next_cell(6,7,zerocoins)).
neg(next_cell(6,8,onecoin)).
neg(next_cell(6,8,twocoins)).
neg(next_cell(6,8,zerocoins)).
neg(next_cell(60,1,onecoin)).
neg(next_cell(60,1,twocoins)).
neg(next_cell(60,1,zerocoins)).
neg(next_cell(60,2,onecoin)).
neg(next_cell(60,2,twocoins)).
neg(next_cell(60,2,zerocoins)).
neg(next_cell(60,3,onecoin)).
neg(next_cell(60,3,twocoins)).
neg(next_cell(60,3,zerocoins)).
neg(next_cell(60,4,onecoin)).
neg(next_cell(60,4,twocoins)).
neg(next_cell(60,4,zerocoins)).
neg(next_cell(60,5,onecoin)).
neg(next_cell(60,5,twocoins)).
neg(next_cell(60,5,zerocoins)).
neg(next_cell(60,6,onecoin)).
neg(next_cell(60,6,twocoins)).
neg(next_cell(60,6,zerocoins)).
neg(next_cell(60,7,onecoin)).
neg(next_cell(60,7,twocoins)).
neg(next_cell(60,7,zerocoins)).
neg(next_cell(60,8,onecoin)).
neg(next_cell(60,8,twocoins)).
neg(next_cell(60,8,zerocoins)).
neg(next_cell(61,1,twocoins)).
neg(next_cell(61,1,zerocoins)).
neg(next_cell(61,2,twocoins)).
neg(next_cell(61,2,zerocoins)).
neg(next_cell(61,3,onecoin)).
neg(next_cell(61,3,twocoins)).
neg(next_cell(61,4,twocoins)).
neg(next_cell(61,4,zerocoins)).
neg(next_cell(61,5,twocoins)).
neg(next_cell(61,5,zerocoins)).
neg(next_cell(61,6,onecoin)).
neg(next_cell(61,6,zerocoins)).
neg(next_cell(61,7,twocoins)).
neg(next_cell(61,7,zerocoins)).
neg(next_cell(61,8,twocoins)).
neg(next_cell(61,8,zerocoins)).
neg(next_cell(62,1,onecoin)).
neg(next_cell(62,1,zerocoins)).
neg(next_cell(62,2,twocoins)).
neg(next_cell(62,2,zerocoins)).
neg(next_cell(62,3,twocoins)).
neg(next_cell(62,3,zerocoins)).
neg(next_cell(62,4,onecoin)).
neg(next_cell(62,4,twocoins)).
neg(next_cell(62,5,onecoin)).
neg(next_cell(62,5,twocoins)).
neg(next_cell(62,6,onecoin)).
neg(next_cell(62,6,twocoins)).
neg(next_cell(62,7,onecoin)).
neg(next_cell(62,7,zerocoins)).
neg(next_cell(62,8,onecoin)).
neg(next_cell(62,8,zerocoins)).
neg(next_cell(63,1,onecoin)).
neg(next_cell(63,1,zerocoins)).
neg(next_cell(63,2,twocoins)).
neg(next_cell(63,2,zerocoins)).
neg(next_cell(63,3,twocoins)).
neg(next_cell(63,3,zerocoins)).
neg(next_cell(63,4,onecoin)).
neg(next_cell(63,4,twocoins)).
neg(next_cell(63,5,onecoin)).
neg(next_cell(63,5,twocoins)).
neg(next_cell(63,6,onecoin)).
neg(next_cell(63,6,zerocoins)).
neg(next_cell(63,7,onecoin)).
neg(next_cell(63,7,zerocoins)).
neg(next_cell(63,8,onecoin)).
neg(next_cell(63,8,twocoins)).
neg(next_cell(64,1,onecoin)).
neg(next_cell(64,1,zerocoins)).
neg(next_cell(64,2,twocoins)).
neg(next_cell(64,2,zerocoins)).
neg(next_cell(64,3,twocoins)).
neg(next_cell(64,3,zerocoins)).
neg(next_cell(64,4,onecoin)).
neg(next_cell(64,4,twocoins)).
neg(next_cell(64,5,twocoins)).
neg(next_cell(64,5,zerocoins)).
neg(next_cell(64,6,twocoins)).
neg(next_cell(64,6,zerocoins)).
neg(next_cell(64,7,twocoins)).
neg(next_cell(64,7,zerocoins)).
neg(next_cell(64,8,twocoins)).
neg(next_cell(64,8,zerocoins)).
neg(next_cell(65,1,onecoin)).
neg(next_cell(65,1,zerocoins)).
neg(next_cell(65,2,twocoins)).
neg(next_cell(65,2,zerocoins)).
neg(next_cell(65,3,onecoin)).
neg(next_cell(65,3,twocoins)).
neg(next_cell(65,4,onecoin)).
neg(next_cell(65,4,twocoins)).
neg(next_cell(65,5,twocoins)).
neg(next_cell(65,5,zerocoins)).
neg(next_cell(65,6,onecoin)).
neg(next_cell(65,6,twocoins)).
neg(next_cell(65,7,onecoin)).
neg(next_cell(65,7,zerocoins)).
neg(next_cell(65,8,onecoin)).
neg(next_cell(65,8,zerocoins)).
neg(next_cell(66,1,twocoins)).
neg(next_cell(66,1,zerocoins)).
neg(next_cell(66,2,onecoin)).
neg(next_cell(66,2,twocoins)).
neg(next_cell(66,3,twocoins)).
neg(next_cell(66,3,zerocoins)).
neg(next_cell(66,4,onecoin)).
neg(next_cell(66,4,zerocoins)).
neg(next_cell(66,5,onecoin)).
neg(next_cell(66,5,zerocoins)).
neg(next_cell(66,6,onecoin)).
neg(next_cell(66,6,twocoins)).
neg(next_cell(66,7,twocoins)).
neg(next_cell(66,7,zerocoins)).
neg(next_cell(66,8,twocoins)).
neg(next_cell(66,8,zerocoins)).
neg(next_cell(67,1,onecoin)).
neg(next_cell(67,1,twocoins)).
neg(next_cell(67,1,zerocoins)).
neg(next_cell(67,2,onecoin)).
neg(next_cell(67,2,twocoins)).
neg(next_cell(67,2,zerocoins)).
neg(next_cell(67,3,onecoin)).
neg(next_cell(67,3,twocoins)).
neg(next_cell(67,3,zerocoins)).
neg(next_cell(67,4,onecoin)).
neg(next_cell(67,4,twocoins)).
neg(next_cell(67,4,zerocoins)).
neg(next_cell(67,5,onecoin)).
neg(next_cell(67,5,twocoins)).
neg(next_cell(67,5,zerocoins)).
neg(next_cell(67,6,onecoin)).
neg(next_cell(67,6,twocoins)).
neg(next_cell(67,6,zerocoins)).
neg(next_cell(67,7,onecoin)).
neg(next_cell(67,7,twocoins)).
neg(next_cell(67,7,zerocoins)).
neg(next_cell(67,8,onecoin)).
neg(next_cell(67,8,twocoins)).
neg(next_cell(67,8,zerocoins)).
neg(next_cell(68,1,twocoins)).
neg(next_cell(68,1,zerocoins)).
neg(next_cell(68,2,twocoins)).
neg(next_cell(68,2,zerocoins)).
neg(next_cell(68,3,twocoins)).
neg(next_cell(68,3,zerocoins)).
neg(next_cell(68,4,twocoins)).
neg(next_cell(68,4,zerocoins)).
neg(next_cell(68,5,onecoin)).
neg(next_cell(68,5,twocoins)).
neg(next_cell(68,6,twocoins)).
neg(next_cell(68,6,zerocoins)).
neg(next_cell(68,7,twocoins)).
neg(next_cell(68,7,zerocoins)).
neg(next_cell(68,8,onecoin)).
neg(next_cell(68,8,zerocoins)).
neg(next_cell(69,1,onecoin)).
neg(next_cell(69,1,twocoins)).
neg(next_cell(69,1,zerocoins)).
neg(next_cell(69,2,onecoin)).
neg(next_cell(69,2,twocoins)).
neg(next_cell(69,2,zerocoins)).
neg(next_cell(69,3,onecoin)).
neg(next_cell(69,3,twocoins)).
neg(next_cell(69,3,zerocoins)).
neg(next_cell(69,4,onecoin)).
neg(next_cell(69,4,twocoins)).
neg(next_cell(69,4,zerocoins)).
neg(next_cell(69,5,onecoin)).
neg(next_cell(69,5,twocoins)).
neg(next_cell(69,5,zerocoins)).
neg(next_cell(69,6,onecoin)).
neg(next_cell(69,6,twocoins)).
neg(next_cell(69,6,zerocoins)).
neg(next_cell(69,7,onecoin)).
neg(next_cell(69,7,twocoins)).
neg(next_cell(69,7,zerocoins)).
neg(next_cell(69,8,onecoin)).
neg(next_cell(69,8,twocoins)).
neg(next_cell(69,8,zerocoins)).
neg(next_cell(7,1,twocoins)).
neg(next_cell(7,1,zerocoins)).
neg(next_cell(7,2,onecoin)).
neg(next_cell(7,2,zerocoins)).
neg(next_cell(7,3,onecoin)).
neg(next_cell(7,3,zerocoins)).
neg(next_cell(7,4,onecoin)).
neg(next_cell(7,4,twocoins)).
neg(next_cell(7,5,onecoin)).
neg(next_cell(7,5,twocoins)).
neg(next_cell(7,6,onecoin)).
neg(next_cell(7,6,twocoins)).
neg(next_cell(7,7,twocoins)).
neg(next_cell(7,7,zerocoins)).
neg(next_cell(7,8,onecoin)).
neg(next_cell(7,8,zerocoins)).
neg(next_cell(70,1,onecoin)).
neg(next_cell(70,1,twocoins)).
neg(next_cell(70,1,zerocoins)).
neg(next_cell(70,2,onecoin)).
neg(next_cell(70,2,twocoins)).
neg(next_cell(70,2,zerocoins)).
neg(next_cell(70,3,onecoin)).
neg(next_cell(70,3,twocoins)).
neg(next_cell(70,3,zerocoins)).
neg(next_cell(70,4,onecoin)).
neg(next_cell(70,4,twocoins)).
neg(next_cell(70,4,zerocoins)).
neg(next_cell(70,5,onecoin)).
neg(next_cell(70,5,twocoins)).
neg(next_cell(70,5,zerocoins)).
neg(next_cell(70,6,onecoin)).
neg(next_cell(70,6,twocoins)).
neg(next_cell(70,6,zerocoins)).
neg(next_cell(70,7,onecoin)).
neg(next_cell(70,7,twocoins)).
neg(next_cell(70,7,zerocoins)).
neg(next_cell(70,8,onecoin)).
neg(next_cell(70,8,twocoins)).
neg(next_cell(70,8,zerocoins)).
neg(next_cell(71,1,twocoins)).
neg(next_cell(71,1,zerocoins)).
neg(next_cell(71,2,onecoin)).
neg(next_cell(71,2,twocoins)).
neg(next_cell(71,3,onecoin)).
neg(next_cell(71,3,zerocoins)).
neg(next_cell(71,4,onecoin)).
neg(next_cell(71,4,twocoins)).
neg(next_cell(71,5,onecoin)).
neg(next_cell(71,5,zerocoins)).
neg(next_cell(71,6,onecoin)).
neg(next_cell(71,6,twocoins)).
neg(next_cell(71,7,twocoins)).
neg(next_cell(71,7,zerocoins)).
neg(next_cell(71,8,onecoin)).
neg(next_cell(71,8,zerocoins)).
neg(next_cell(72,1,onecoin)).
neg(next_cell(72,1,twocoins)).
neg(next_cell(72,2,onecoin)).
neg(next_cell(72,2,zerocoins)).
neg(next_cell(72,3,onecoin)).
neg(next_cell(72,3,zerocoins)).
neg(next_cell(72,4,onecoin)).
neg(next_cell(72,4,twocoins)).
neg(next_cell(72,5,twocoins)).
neg(next_cell(72,5,zerocoins)).
neg(next_cell(72,6,onecoin)).
neg(next_cell(72,6,twocoins)).
neg(next_cell(72,7,onecoin)).
neg(next_cell(72,7,zerocoins)).
neg(next_cell(72,8,twocoins)).
neg(next_cell(72,8,zerocoins)).
neg(next_cell(73,1,twocoins)).
neg(next_cell(73,1,zerocoins)).
neg(next_cell(73,2,onecoin)).
neg(next_cell(73,2,zerocoins)).
neg(next_cell(73,3,onecoin)).
neg(next_cell(73,3,zerocoins)).
neg(next_cell(73,4,twocoins)).
neg(next_cell(73,4,zerocoins)).
neg(next_cell(73,5,onecoin)).
neg(next_cell(73,5,twocoins)).
neg(next_cell(73,6,twocoins)).
neg(next_cell(73,6,zerocoins)).
neg(next_cell(73,7,onecoin)).
neg(next_cell(73,7,twocoins)).
neg(next_cell(73,8,twocoins)).
neg(next_cell(73,8,zerocoins)).
neg(next_cell(74,1,onecoin)).
neg(next_cell(74,1,twocoins)).
neg(next_cell(74,1,zerocoins)).
neg(next_cell(74,2,onecoin)).
neg(next_cell(74,2,twocoins)).
neg(next_cell(74,2,zerocoins)).
neg(next_cell(74,3,onecoin)).
neg(next_cell(74,3,twocoins)).
neg(next_cell(74,3,zerocoins)).
neg(next_cell(74,4,onecoin)).
neg(next_cell(74,4,twocoins)).
neg(next_cell(74,4,zerocoins)).
neg(next_cell(74,5,onecoin)).
neg(next_cell(74,5,twocoins)).
neg(next_cell(74,5,zerocoins)).
neg(next_cell(74,6,onecoin)).
neg(next_cell(74,6,twocoins)).
neg(next_cell(74,6,zerocoins)).
neg(next_cell(74,7,onecoin)).
neg(next_cell(74,7,twocoins)).
neg(next_cell(74,7,zerocoins)).
neg(next_cell(74,8,onecoin)).
neg(next_cell(74,8,twocoins)).
neg(next_cell(74,8,zerocoins)).
neg(next_cell(75,1,twocoins)).
neg(next_cell(75,1,zerocoins)).
neg(next_cell(75,2,twocoins)).
neg(next_cell(75,2,zerocoins)).
neg(next_cell(75,3,onecoin)).
neg(next_cell(75,3,twocoins)).
neg(next_cell(75,4,onecoin)).
neg(next_cell(75,4,zerocoins)).
neg(next_cell(75,5,onecoin)).
neg(next_cell(75,5,zerocoins)).
neg(next_cell(75,6,twocoins)).
neg(next_cell(75,6,zerocoins)).
neg(next_cell(75,7,onecoin)).
neg(next_cell(75,7,twocoins)).
neg(next_cell(75,8,twocoins)).
neg(next_cell(75,8,zerocoins)).
neg(next_cell(76,1,onecoin)).
neg(next_cell(76,1,twocoins)).
neg(next_cell(76,2,twocoins)).
neg(next_cell(76,2,zerocoins)).
neg(next_cell(76,3,twocoins)).
neg(next_cell(76,3,zerocoins)).
neg(next_cell(76,4,onecoin)).
neg(next_cell(76,4,zerocoins)).
neg(next_cell(76,5,onecoin)).
neg(next_cell(76,5,twocoins)).
neg(next_cell(76,6,twocoins)).
neg(next_cell(76,6,zerocoins)).
neg(next_cell(76,7,twocoins)).
neg(next_cell(76,7,zerocoins)).
neg(next_cell(76,8,onecoin)).
neg(next_cell(76,8,zerocoins)).
neg(next_cell(77,1,onecoin)).
neg(next_cell(77,1,twocoins)).
neg(next_cell(77,2,twocoins)).
neg(next_cell(77,2,zerocoins)).
neg(next_cell(77,3,twocoins)).
neg(next_cell(77,3,zerocoins)).
neg(next_cell(77,4,onecoin)).
neg(next_cell(77,4,zerocoins)).
neg(next_cell(77,5,twocoins)).
neg(next_cell(77,5,zerocoins)).
neg(next_cell(77,6,twocoins)).
neg(next_cell(77,6,zerocoins)).
neg(next_cell(77,7,twocoins)).
neg(next_cell(77,7,zerocoins)).
neg(next_cell(77,8,twocoins)).
neg(next_cell(77,8,zerocoins)).
neg(next_cell(78,1,onecoin)).
neg(next_cell(78,1,zerocoins)).
neg(next_cell(78,2,onecoin)).
neg(next_cell(78,2,zerocoins)).
neg(next_cell(78,3,onecoin)).
neg(next_cell(78,3,twocoins)).
neg(next_cell(78,4,onecoin)).
neg(next_cell(78,4,twocoins)).
neg(next_cell(78,5,onecoin)).
neg(next_cell(78,5,twocoins)).
neg(next_cell(78,6,onecoin)).
neg(next_cell(78,6,twocoins)).
neg(next_cell(78,7,onecoin)).
neg(next_cell(78,7,zerocoins)).
neg(next_cell(78,8,onecoin)).
neg(next_cell(78,8,zerocoins)).
neg(next_cell(79,1,twocoins)).
neg(next_cell(79,1,zerocoins)).
neg(next_cell(79,2,twocoins)).
neg(next_cell(79,2,zerocoins)).
neg(next_cell(79,3,onecoin)).
neg(next_cell(79,3,zerocoins)).
neg(next_cell(79,4,onecoin)).
neg(next_cell(79,4,twocoins)).
neg(next_cell(79,5,twocoins)).
neg(next_cell(79,5,zerocoins)).
neg(next_cell(79,6,onecoin)).
neg(next_cell(79,6,twocoins)).
neg(next_cell(79,7,twocoins)).
neg(next_cell(79,7,zerocoins)).
neg(next_cell(79,8,onecoin)).
neg(next_cell(79,8,zerocoins)).
neg(next_cell(8,1,twocoins)).
neg(next_cell(8,1,zerocoins)).
neg(next_cell(8,2,twocoins)).
neg(next_cell(8,2,zerocoins)).
neg(next_cell(8,3,onecoin)).
neg(next_cell(8,3,zerocoins)).
neg(next_cell(8,4,onecoin)).
neg(next_cell(8,4,zerocoins)).
neg(next_cell(8,5,onecoin)).
neg(next_cell(8,5,twocoins)).
neg(next_cell(8,6,twocoins)).
neg(next_cell(8,6,zerocoins)).
neg(next_cell(8,7,onecoin)).
neg(next_cell(8,7,twocoins)).
neg(next_cell(8,8,twocoins)).
neg(next_cell(8,8,zerocoins)).
neg(next_cell(80,1,onecoin)).
neg(next_cell(80,1,twocoins)).
neg(next_cell(80,1,zerocoins)).
neg(next_cell(80,2,onecoin)).
neg(next_cell(80,2,twocoins)).
neg(next_cell(80,2,zerocoins)).
neg(next_cell(80,3,onecoin)).
neg(next_cell(80,3,twocoins)).
neg(next_cell(80,3,zerocoins)).
neg(next_cell(80,4,onecoin)).
neg(next_cell(80,4,twocoins)).
neg(next_cell(80,4,zerocoins)).
neg(next_cell(80,5,onecoin)).
neg(next_cell(80,5,twocoins)).
neg(next_cell(80,5,zerocoins)).
neg(next_cell(80,6,onecoin)).
neg(next_cell(80,6,twocoins)).
neg(next_cell(80,6,zerocoins)).
neg(next_cell(80,7,onecoin)).
neg(next_cell(80,7,twocoins)).
neg(next_cell(80,7,zerocoins)).
neg(next_cell(80,8,onecoin)).
neg(next_cell(80,8,twocoins)).
neg(next_cell(80,8,zerocoins)).
neg(next_cell(81,1,onecoin)).
neg(next_cell(81,1,zerocoins)).
neg(next_cell(81,2,onecoin)).
neg(next_cell(81,2,twocoins)).
neg(next_cell(81,3,twocoins)).
neg(next_cell(81,3,zerocoins)).
neg(next_cell(81,4,onecoin)).
neg(next_cell(81,4,twocoins)).
neg(next_cell(81,5,onecoin)).
neg(next_cell(81,5,twocoins)).
neg(next_cell(81,6,twocoins)).
neg(next_cell(81,6,zerocoins)).
neg(next_cell(81,7,onecoin)).
neg(next_cell(81,7,zerocoins)).
neg(next_cell(81,8,onecoin)).
neg(next_cell(81,8,zerocoins)).
neg(next_cell(82,1,onecoin)).
neg(next_cell(82,1,twocoins)).
neg(next_cell(82,1,zerocoins)).
neg(next_cell(82,2,onecoin)).
neg(next_cell(82,2,twocoins)).
neg(next_cell(82,2,zerocoins)).
neg(next_cell(82,3,onecoin)).
neg(next_cell(82,3,twocoins)).
neg(next_cell(82,3,zerocoins)).
neg(next_cell(82,4,onecoin)).
neg(next_cell(82,4,twocoins)).
neg(next_cell(82,4,zerocoins)).
neg(next_cell(82,5,onecoin)).
neg(next_cell(82,5,twocoins)).
neg(next_cell(82,5,zerocoins)).
neg(next_cell(82,6,onecoin)).
neg(next_cell(82,6,twocoins)).
neg(next_cell(82,6,zerocoins)).
neg(next_cell(82,7,onecoin)).
neg(next_cell(82,7,twocoins)).
neg(next_cell(82,7,zerocoins)).
neg(next_cell(82,8,onecoin)).
neg(next_cell(82,8,twocoins)).
neg(next_cell(82,8,zerocoins)).
neg(next_cell(83,1,twocoins)).
neg(next_cell(83,1,zerocoins)).
neg(next_cell(83,2,twocoins)).
neg(next_cell(83,2,zerocoins)).
neg(next_cell(83,3,twocoins)).
neg(next_cell(83,3,zerocoins)).
neg(next_cell(83,4,twocoins)).
neg(next_cell(83,4,zerocoins)).
neg(next_cell(83,5,onecoin)).
neg(next_cell(83,5,zerocoins)).
neg(next_cell(83,6,twocoins)).
neg(next_cell(83,6,zerocoins)).
neg(next_cell(83,7,twocoins)).
neg(next_cell(83,7,zerocoins)).
neg(next_cell(83,8,onecoin)).
neg(next_cell(83,8,twocoins)).
neg(next_cell(84,1,onecoin)).
neg(next_cell(84,1,zerocoins)).
neg(next_cell(84,2,twocoins)).
neg(next_cell(84,2,zerocoins)).
neg(next_cell(84,3,twocoins)).
neg(next_cell(84,3,zerocoins)).
neg(next_cell(84,4,onecoin)).
neg(next_cell(84,4,twocoins)).
neg(next_cell(84,5,onecoin)).
neg(next_cell(84,5,twocoins)).
neg(next_cell(84,6,twocoins)).
neg(next_cell(84,6,zerocoins)).
neg(next_cell(84,7,onecoin)).
neg(next_cell(84,7,zerocoins)).
neg(next_cell(84,8,twocoins)).
neg(next_cell(84,8,zerocoins)).
neg(next_cell(85,1,onecoin)).
neg(next_cell(85,1,twocoins)).
neg(next_cell(85,1,zerocoins)).
neg(next_cell(85,2,onecoin)).
neg(next_cell(85,2,twocoins)).
neg(next_cell(85,2,zerocoins)).
neg(next_cell(85,3,onecoin)).
neg(next_cell(85,3,twocoins)).
neg(next_cell(85,3,zerocoins)).
neg(next_cell(85,4,onecoin)).
neg(next_cell(85,4,twocoins)).
neg(next_cell(85,4,zerocoins)).
neg(next_cell(85,5,onecoin)).
neg(next_cell(85,5,twocoins)).
neg(next_cell(85,5,zerocoins)).
neg(next_cell(85,6,onecoin)).
neg(next_cell(85,6,twocoins)).
neg(next_cell(85,6,zerocoins)).
neg(next_cell(85,7,onecoin)).
neg(next_cell(85,7,twocoins)).
neg(next_cell(85,7,zerocoins)).
neg(next_cell(85,8,onecoin)).
neg(next_cell(85,8,twocoins)).
neg(next_cell(85,8,zerocoins)).
neg(next_cell(86,1,onecoin)).
neg(next_cell(86,1,zerocoins)).
neg(next_cell(86,2,onecoin)).
neg(next_cell(86,2,zerocoins)).
neg(next_cell(86,3,onecoin)).
neg(next_cell(86,3,zerocoins)).
neg(next_cell(86,4,onecoin)).
neg(next_cell(86,4,twocoins)).
neg(next_cell(86,5,onecoin)).
neg(next_cell(86,5,twocoins)).
neg(next_cell(86,6,twocoins)).
neg(next_cell(86,6,zerocoins)).
neg(next_cell(86,7,onecoin)).
neg(next_cell(86,7,twocoins)).
neg(next_cell(86,8,twocoins)).
neg(next_cell(86,8,zerocoins)).
neg(next_cell(87,1,twocoins)).
neg(next_cell(87,1,zerocoins)).
neg(next_cell(87,2,onecoin)).
neg(next_cell(87,2,zerocoins)).
neg(next_cell(87,3,twocoins)).
neg(next_cell(87,3,zerocoins)).
neg(next_cell(87,4,twocoins)).
neg(next_cell(87,4,zerocoins)).
neg(next_cell(87,5,onecoin)).
neg(next_cell(87,5,twocoins)).
neg(next_cell(87,6,onecoin)).
neg(next_cell(87,6,twocoins)).
neg(next_cell(87,7,twocoins)).
neg(next_cell(87,7,zerocoins)).
neg(next_cell(87,8,onecoin)).
neg(next_cell(87,8,zerocoins)).
neg(next_cell(88,1,onecoin)).
neg(next_cell(88,1,twocoins)).
neg(next_cell(88,1,zerocoins)).
neg(next_cell(88,2,onecoin)).
neg(next_cell(88,2,twocoins)).
neg(next_cell(88,2,zerocoins)).
neg(next_cell(88,3,onecoin)).
neg(next_cell(88,3,twocoins)).
neg(next_cell(88,3,zerocoins)).
neg(next_cell(88,4,onecoin)).
neg(next_cell(88,4,twocoins)).
neg(next_cell(88,4,zerocoins)).
neg(next_cell(88,5,onecoin)).
neg(next_cell(88,5,twocoins)).
neg(next_cell(88,5,zerocoins)).
neg(next_cell(88,6,onecoin)).
neg(next_cell(88,6,twocoins)).
neg(next_cell(88,6,zerocoins)).
neg(next_cell(88,7,onecoin)).
neg(next_cell(88,7,twocoins)).
neg(next_cell(88,7,zerocoins)).
neg(next_cell(88,8,onecoin)).
neg(next_cell(88,8,twocoins)).
neg(next_cell(88,8,zerocoins)).
neg(next_cell(89,1,twocoins)).
neg(next_cell(89,1,zerocoins)).
neg(next_cell(89,2,onecoin)).
neg(next_cell(89,2,zerocoins)).
neg(next_cell(89,3,twocoins)).
neg(next_cell(89,3,zerocoins)).
neg(next_cell(89,4,onecoin)).
neg(next_cell(89,4,zerocoins)).
neg(next_cell(89,5,onecoin)).
neg(next_cell(89,5,twocoins)).
neg(next_cell(89,6,twocoins)).
neg(next_cell(89,6,zerocoins)).
neg(next_cell(89,7,twocoins)).
neg(next_cell(89,7,zerocoins)).
neg(next_cell(89,8,onecoin)).
neg(next_cell(89,8,twocoins)).
neg(next_cell(9,1,onecoin)).
neg(next_cell(9,1,twocoins)).
neg(next_cell(9,2,twocoins)).
neg(next_cell(9,2,zerocoins)).
neg(next_cell(9,3,onecoin)).
neg(next_cell(9,3,twocoins)).
neg(next_cell(9,4,onecoin)).
neg(next_cell(9,4,twocoins)).
neg(next_cell(9,5,onecoin)).
neg(next_cell(9,5,zerocoins)).
neg(next_cell(9,6,onecoin)).
neg(next_cell(9,6,zerocoins)).
neg(next_cell(9,7,onecoin)).
neg(next_cell(9,7,zerocoins)).
neg(next_cell(9,8,twocoins)).
neg(next_cell(9,8,zerocoins)).
neg(next_cell(90,1,onecoin)).
neg(next_cell(90,1,zerocoins)).
neg(next_cell(90,2,twocoins)).
neg(next_cell(90,2,zerocoins)).
neg(next_cell(90,3,onecoin)).
neg(next_cell(90,3,twocoins)).
neg(next_cell(90,4,onecoin)).
neg(next_cell(90,4,twocoins)).
neg(next_cell(90,5,twocoins)).
neg(next_cell(90,5,zerocoins)).
neg(next_cell(90,6,twocoins)).
neg(next_cell(90,6,zerocoins)).
neg(next_cell(90,7,onecoin)).
neg(next_cell(90,7,zerocoins)).
neg(next_cell(90,8,twocoins)).
neg(next_cell(90,8,zerocoins)).
neg(next_cell(91,1,twocoins)).
neg(next_cell(91,1,zerocoins)).
neg(next_cell(91,2,onecoin)).
neg(next_cell(91,2,zerocoins)).
neg(next_cell(91,3,onecoin)).
neg(next_cell(91,3,zerocoins)).
neg(next_cell(91,4,onecoin)).
neg(next_cell(91,4,twocoins)).
neg(next_cell(91,5,twocoins)).
neg(next_cell(91,5,zerocoins)).
neg(next_cell(91,6,onecoin)).
neg(next_cell(91,6,twocoins)).
neg(next_cell(91,7,twocoins)).
neg(next_cell(91,7,zerocoins)).
neg(next_cell(91,8,twocoins)).
neg(next_cell(91,8,zerocoins)).
neg(next_cell(92,1,onecoin)).
neg(next_cell(92,1,twocoins)).
neg(next_cell(92,1,zerocoins)).
neg(next_cell(92,2,onecoin)).
neg(next_cell(92,2,twocoins)).
neg(next_cell(92,2,zerocoins)).
neg(next_cell(92,3,onecoin)).
neg(next_cell(92,3,twocoins)).
neg(next_cell(92,3,zerocoins)).
neg(next_cell(92,4,onecoin)).
neg(next_cell(92,4,twocoins)).
neg(next_cell(92,4,zerocoins)).
neg(next_cell(92,5,onecoin)).
neg(next_cell(92,5,twocoins)).
neg(next_cell(92,5,zerocoins)).
neg(next_cell(92,6,onecoin)).
neg(next_cell(92,6,twocoins)).
neg(next_cell(92,6,zerocoins)).
neg(next_cell(92,7,onecoin)).
neg(next_cell(92,7,twocoins)).
neg(next_cell(92,7,zerocoins)).
neg(next_cell(92,8,onecoin)).
neg(next_cell(92,8,twocoins)).
neg(next_cell(92,8,zerocoins)).
neg(next_cell(93,1,onecoin)).
neg(next_cell(93,1,twocoins)).
neg(next_cell(93,2,onecoin)).
neg(next_cell(93,2,zerocoins)).
neg(next_cell(93,3,onecoin)).
neg(next_cell(93,3,zerocoins)).
neg(next_cell(93,4,onecoin)).
neg(next_cell(93,4,twocoins)).
neg(next_cell(93,5,onecoin)).
neg(next_cell(93,5,twocoins)).
neg(next_cell(93,6,twocoins)).
neg(next_cell(93,6,zerocoins)).
neg(next_cell(93,7,twocoins)).
neg(next_cell(93,7,zerocoins)).
neg(next_cell(93,8,onecoin)).
neg(next_cell(93,8,zerocoins)).
neg(next_cell(94,1,onecoin)).
neg(next_cell(94,1,twocoins)).
neg(next_cell(94,1,zerocoins)).
neg(next_cell(94,2,onecoin)).
neg(next_cell(94,2,twocoins)).
neg(next_cell(94,2,zerocoins)).
neg(next_cell(94,3,onecoin)).
neg(next_cell(94,3,twocoins)).
neg(next_cell(94,3,zerocoins)).
neg(next_cell(94,4,onecoin)).
neg(next_cell(94,4,twocoins)).
neg(next_cell(94,4,zerocoins)).
neg(next_cell(94,5,onecoin)).
neg(next_cell(94,5,twocoins)).
neg(next_cell(94,5,zerocoins)).
neg(next_cell(94,6,onecoin)).
neg(next_cell(94,6,twocoins)).
neg(next_cell(94,6,zerocoins)).
neg(next_cell(94,7,onecoin)).
neg(next_cell(94,7,twocoins)).
neg(next_cell(94,7,zerocoins)).
neg(next_cell(94,8,onecoin)).
neg(next_cell(94,8,twocoins)).
neg(next_cell(94,8,zerocoins)).
neg(next_cell(95,1,onecoin)).
neg(next_cell(95,1,twocoins)).
neg(next_cell(95,1,zerocoins)).
neg(next_cell(95,2,onecoin)).
neg(next_cell(95,2,twocoins)).
neg(next_cell(95,2,zerocoins)).
neg(next_cell(95,3,onecoin)).
neg(next_cell(95,3,twocoins)).
neg(next_cell(95,3,zerocoins)).
neg(next_cell(95,4,onecoin)).
neg(next_cell(95,4,twocoins)).
neg(next_cell(95,4,zerocoins)).
neg(next_cell(95,5,onecoin)).
neg(next_cell(95,5,twocoins)).
neg(next_cell(95,5,zerocoins)).
neg(next_cell(95,6,onecoin)).
neg(next_cell(95,6,twocoins)).
neg(next_cell(95,6,zerocoins)).
neg(next_cell(95,7,onecoin)).
neg(next_cell(95,7,twocoins)).
neg(next_cell(95,7,zerocoins)).
neg(next_cell(95,8,onecoin)).
neg(next_cell(95,8,twocoins)).
neg(next_cell(95,8,zerocoins)).
neg(next_cell(96,1,onecoin)).
neg(next_cell(96,1,zerocoins)).
neg(next_cell(96,2,onecoin)).
neg(next_cell(96,2,zerocoins)).
neg(next_cell(96,3,twocoins)).
neg(next_cell(96,3,zerocoins)).
neg(next_cell(96,4,onecoin)).
neg(next_cell(96,4,twocoins)).
neg(next_cell(96,5,twocoins)).
neg(next_cell(96,5,zerocoins)).
neg(next_cell(96,6,onecoin)).
neg(next_cell(96,6,twocoins)).
neg(next_cell(96,7,twocoins)).
neg(next_cell(96,7,zerocoins)).
neg(next_cell(96,8,twocoins)).
neg(next_cell(96,8,zerocoins)).
neg(next_cell(97,1,onecoin)).
neg(next_cell(97,1,twocoins)).
neg(next_cell(97,1,zerocoins)).
neg(next_cell(97,2,onecoin)).
neg(next_cell(97,2,twocoins)).
neg(next_cell(97,2,zerocoins)).
neg(next_cell(97,3,onecoin)).
neg(next_cell(97,3,twocoins)).
neg(next_cell(97,3,zerocoins)).
neg(next_cell(97,4,onecoin)).
neg(next_cell(97,4,twocoins)).
neg(next_cell(97,4,zerocoins)).
neg(next_cell(97,5,onecoin)).
neg(next_cell(97,5,twocoins)).
neg(next_cell(97,5,zerocoins)).
neg(next_cell(97,6,onecoin)).
neg(next_cell(97,6,twocoins)).
neg(next_cell(97,6,zerocoins)).
neg(next_cell(97,7,onecoin)).
neg(next_cell(97,7,twocoins)).
neg(next_cell(97,7,zerocoins)).
neg(next_cell(97,8,onecoin)).
neg(next_cell(97,8,twocoins)).
neg(next_cell(97,8,zerocoins)).
neg(next_cell(98,1,onecoin)).
neg(next_cell(98,1,twocoins)).
neg(next_cell(98,1,zerocoins)).
neg(next_cell(98,2,onecoin)).
neg(next_cell(98,2,twocoins)).
neg(next_cell(98,2,zerocoins)).
neg(next_cell(98,3,onecoin)).
neg(next_cell(98,3,twocoins)).
neg(next_cell(98,3,zerocoins)).
neg(next_cell(98,4,onecoin)).
neg(next_cell(98,4,twocoins)).
neg(next_cell(98,4,zerocoins)).
neg(next_cell(98,5,onecoin)).
neg(next_cell(98,5,twocoins)).
neg(next_cell(98,5,zerocoins)).
neg(next_cell(98,6,onecoin)).
neg(next_cell(98,6,twocoins)).
neg(next_cell(98,6,zerocoins)).
neg(next_cell(98,7,onecoin)).
neg(next_cell(98,7,twocoins)).
neg(next_cell(98,7,zerocoins)).
neg(next_cell(98,8,onecoin)).
neg(next_cell(98,8,twocoins)).
neg(next_cell(98,8,zerocoins)).
neg(next_cell(99,1,twocoins)).
neg(next_cell(99,1,zerocoins)).
neg(next_cell(99,2,twocoins)).
neg(next_cell(99,2,zerocoins)).
neg(next_cell(99,3,twocoins)).
neg(next_cell(99,3,zerocoins)).
neg(next_cell(99,4,onecoin)).
neg(next_cell(99,4,zerocoins)).
neg(next_cell(99,5,onecoin)).
neg(next_cell(99,5,zerocoins)).
neg(next_cell(99,6,onecoin)).
neg(next_cell(99,6,twocoins)).
neg(next_cell(99,7,twocoins)).
neg(next_cell(99,7,zerocoins)).
neg(next_cell(99,8,onecoin)).
neg(next_cell(99,8,twocoins)).
pos(next_cell(10,1,onecoin)).
pos(next_cell(10,2,twocoins)).
pos(next_cell(10,3,onecoin)).
pos(next_cell(10,4,onecoin)).
pos(next_cell(10,5,zerocoins)).
pos(next_cell(10,6,onecoin)).
pos(next_cell(10,7,onecoin)).
pos(next_cell(10,8,onecoin)).
pos(next_cell(101,1,onecoin)).
pos(next_cell(101,2,onecoin)).
pos(next_cell(101,3,onecoin)).
pos(next_cell(101,4,twocoins)).
pos(next_cell(101,5,onecoin)).
pos(next_cell(101,6,onecoin)).
pos(next_cell(101,7,zerocoins)).
pos(next_cell(101,8,onecoin)).
pos(next_cell(103,1,twocoins)).
pos(next_cell(103,2,twocoins)).
pos(next_cell(103,3,zerocoins)).
pos(next_cell(103,4,zerocoins)).
pos(next_cell(103,5,zerocoins)).
pos(next_cell(103,6,onecoin)).
pos(next_cell(103,7,onecoin)).
pos(next_cell(103,8,twocoins)).
pos(next_cell(105,1,twocoins)).
pos(next_cell(105,2,twocoins)).
pos(next_cell(105,3,zerocoins)).
pos(next_cell(105,4,twocoins)).
pos(next_cell(105,5,zerocoins)).
pos(next_cell(105,6,onecoin)).
pos(next_cell(105,7,onecoin)).
pos(next_cell(105,8,zerocoins)).
pos(next_cell(106,1,onecoin)).
pos(next_cell(106,2,onecoin)).
pos(next_cell(106,3,onecoin)).
pos(next_cell(106,4,zerocoins)).
pos(next_cell(106,5,onecoin)).
pos(next_cell(106,6,zerocoins)).
pos(next_cell(106,7,twocoins)).
pos(next_cell(106,8,twocoins)).
pos(next_cell(11,1,twocoins)).
pos(next_cell(11,2,onecoin)).
pos(next_cell(11,3,onecoin)).
pos(next_cell(11,4,zerocoins)).
pos(next_cell(11,5,zerocoins)).
pos(next_cell(11,6,zerocoins)).
pos(next_cell(11,7,twocoins)).
pos(next_cell(11,8,twocoins)).
pos(next_cell(13,1,twocoins)).
pos(next_cell(13,2,twocoins)).
pos(next_cell(13,3,zerocoins)).
pos(next_cell(13,4,zerocoins)).
pos(next_cell(13,5,zerocoins)).
pos(next_cell(13,6,onecoin)).
pos(next_cell(13,7,twocoins)).
pos(next_cell(13,8,onecoin)).
pos(next_cell(14,1,zerocoins)).
pos(next_cell(14,2,twocoins)).
pos(next_cell(14,3,twocoins)).
pos(next_cell(14,4,onecoin)).
pos(next_cell(14,5,zerocoins)).
pos(next_cell(14,6,onecoin)).
pos(next_cell(14,7,onecoin)).
pos(next_cell(14,8,onecoin)).
pos(next_cell(15,1,onecoin)).
pos(next_cell(15,2,onecoin)).
pos(next_cell(15,3,twocoins)).
pos(next_cell(15,4,onecoin)).
pos(next_cell(15,5,onecoin)).
pos(next_cell(15,6,zerocoins)).
pos(next_cell(15,7,onecoin)).
pos(next_cell(15,8,onecoin)).
pos(next_cell(17,1,zerocoins)).
pos(next_cell(17,2,onecoin)).
pos(next_cell(17,3,zerocoins)).
pos(next_cell(17,4,twocoins)).
pos(next_cell(17,5,twocoins)).
pos(next_cell(17,6,onecoin)).
pos(next_cell(17,7,onecoin)).
pos(next_cell(17,8,onecoin)).
pos(next_cell(19,1,zerocoins)).
pos(next_cell(19,2,twocoins)).
pos(next_cell(19,3,twocoins)).
pos(next_cell(19,4,twocoins)).
pos(next_cell(19,5,zerocoins)).
pos(next_cell(19,6,onecoin)).
pos(next_cell(19,7,onecoin)).
pos(next_cell(19,8,zerocoins)).
pos(next_cell(2,1,onecoin)).
pos(next_cell(2,2,zerocoins)).
pos(next_cell(2,3,onecoin)).
pos(next_cell(2,4,twocoins)).
pos(next_cell(2,5,zerocoins)).
pos(next_cell(2,6,twocoins)).
pos(next_cell(2,7,zerocoins)).
pos(next_cell(2,8,twocoins)).
pos(next_cell(20,1,twocoins)).
pos(next_cell(20,2,onecoin)).
pos(next_cell(20,3,onecoin)).
pos(next_cell(20,4,zerocoins)).
pos(next_cell(20,5,zerocoins)).
pos(next_cell(20,6,onecoin)).
pos(next_cell(20,7,onecoin)).
pos(next_cell(20,8,twocoins)).
pos(next_cell(21,1,twocoins)).
pos(next_cell(21,2,twocoins)).
pos(next_cell(21,3,twocoins)).
pos(next_cell(21,4,zerocoins)).
pos(next_cell(21,5,onecoin)).
pos(next_cell(21,6,zerocoins)).
pos(next_cell(21,7,onecoin)).
pos(next_cell(21,8,zerocoins)).
pos(next_cell(22,1,onecoin)).
pos(next_cell(22,2,zerocoins)).
pos(next_cell(22,3,onecoin)).
pos(next_cell(22,4,zerocoins)).
pos(next_cell(22,5,zerocoins)).
pos(next_cell(22,6,twocoins)).
pos(next_cell(22,7,twocoins)).
pos(next_cell(22,8,twocoins)).
pos(next_cell(23,1,twocoins)).
pos(next_cell(23,2,onecoin)).
pos(next_cell(23,3,onecoin)).
pos(next_cell(23,4,zerocoins)).
pos(next_cell(23,5,twocoins)).
pos(next_cell(23,6,onecoin)).
pos(next_cell(23,7,onecoin)).
pos(next_cell(23,8,zerocoins)).
pos(next_cell(24,1,onecoin)).
pos(next_cell(24,2,onecoin)).
pos(next_cell(24,3,zerocoins)).
pos(next_cell(24,4,onecoin)).
pos(next_cell(24,5,zerocoins)).
pos(next_cell(24,6,onecoin)).
pos(next_cell(24,7,twocoins)).
pos(next_cell(24,8,twocoins)).
pos(next_cell(26,1,zerocoins)).
pos(next_cell(26,2,twocoins)).
pos(next_cell(26,3,twocoins)).
pos(next_cell(26,4,zerocoins)).
pos(next_cell(26,5,zerocoins)).
pos(next_cell(26,6,zerocoins)).
pos(next_cell(26,7,twocoins)).
pos(next_cell(26,8,twocoins)).
pos(next_cell(27,1,twocoins)).
pos(next_cell(27,2,onecoin)).
pos(next_cell(27,3,zerocoins)).
pos(next_cell(27,4,zerocoins)).
pos(next_cell(27,5,zerocoins)).
pos(next_cell(27,6,twocoins)).
pos(next_cell(27,7,twocoins)).
pos(next_cell(27,8,onecoin)).
pos(next_cell(28,1,twocoins)).
pos(next_cell(28,2,twocoins)).
pos(next_cell(28,3,zerocoins)).
pos(next_cell(28,4,zerocoins)).
pos(next_cell(28,5,onecoin)).
pos(next_cell(28,6,zerocoins)).
pos(next_cell(28,7,twocoins)).
pos(next_cell(28,8,onecoin)).
pos(next_cell(30,1,onecoin)).
pos(next_cell(30,2,zerocoins)).
pos(next_cell(30,3,onecoin)).
pos(next_cell(30,4,zerocoins)).
pos(next_cell(30,5,onecoin)).
pos(next_cell(30,6,twocoins)).
pos(next_cell(30,7,twocoins)).
pos(next_cell(30,8,onecoin)).
pos(next_cell(31,1,twocoins)).
pos(next_cell(31,2,onecoin)).
pos(next_cell(31,3,zerocoins)).
pos(next_cell(31,4,onecoin)).
pos(next_cell(31,5,zerocoins)).
pos(next_cell(31,6,twocoins)).
pos(next_cell(31,7,onecoin)).
pos(next_cell(31,8,onecoin)).
pos(next_cell(32,1,twocoins)).
pos(next_cell(32,2,zerocoins)).
pos(next_cell(32,3,twocoins)).
pos(next_cell(32,4,zerocoins)).
pos(next_cell(32,5,twocoins)).
pos(next_cell(32,6,onecoin)).
pos(next_cell(32,7,zerocoins)).
pos(next_cell(32,8,onecoin)).
pos(next_cell(33,1,onecoin)).
pos(next_cell(33,2,onecoin)).
pos(next_cell(33,3,twocoins)).
pos(next_cell(33,4,onecoin)).
pos(next_cell(33,5,zerocoins)).
pos(next_cell(33,6,onecoin)).
pos(next_cell(33,7,zerocoins)).
pos(next_cell(33,8,twocoins)).
pos(next_cell(35,1,twocoins)).
pos(next_cell(35,2,twocoins)).
pos(next_cell(35,3,zerocoins)).
pos(next_cell(35,4,onecoin)).
pos(next_cell(35,5,zerocoins)).
pos(next_cell(35,6,zerocoins)).
pos(next_cell(35,7,onecoin)).
pos(next_cell(35,8,twocoins)).
pos(next_cell(36,1,zerocoins)).
pos(next_cell(36,2,onecoin)).
pos(next_cell(36,3,zerocoins)).
pos(next_cell(36,4,twocoins)).
pos(next_cell(36,5,zerocoins)).
pos(next_cell(36,6,twocoins)).
pos(next_cell(36,7,onecoin)).
pos(next_cell(36,8,twocoins)).
pos(next_cell(38,1,onecoin)).
pos(next_cell(38,2,onecoin)).
pos(next_cell(38,3,twocoins)).
pos(next_cell(38,4,twocoins)).
pos(next_cell(38,5,onecoin)).
pos(next_cell(38,6,zerocoins)).
pos(next_cell(38,7,onecoin)).
pos(next_cell(38,8,zerocoins)).
pos(next_cell(39,1,twocoins)).
pos(next_cell(39,2,twocoins)).
pos(next_cell(39,3,zerocoins)).
pos(next_cell(39,4,twocoins)).
pos(next_cell(39,5,zerocoins)).
pos(next_cell(39,6,onecoin)).
pos(next_cell(39,7,onecoin)).
pos(next_cell(39,8,zerocoins)).
pos(next_cell(4,1,onecoin)).
pos(next_cell(4,2,zerocoins)).
pos(next_cell(4,3,onecoin)).
pos(next_cell(4,4,onecoin)).
pos(next_cell(4,5,zerocoins)).
pos(next_cell(4,6,twocoins)).
pos(next_cell(4,7,onecoin)).
pos(next_cell(4,8,twocoins)).
pos(next_cell(40,1,onecoin)).
pos(next_cell(40,2,onecoin)).
pos(next_cell(40,3,zerocoins)).
pos(next_cell(40,4,onecoin)).
pos(next_cell(40,5,twocoins)).
pos(next_cell(40,6,twocoins)).
pos(next_cell(40,7,zerocoins)).
pos(next_cell(40,8,onecoin)).
pos(next_cell(41,1,zerocoins)).
pos(next_cell(41,2,onecoin)).
pos(next_cell(41,3,onecoin)).
pos(next_cell(41,4,twocoins)).
pos(next_cell(41,5,zerocoins)).
pos(next_cell(41,6,onecoin)).
pos(next_cell(41,7,onecoin)).
pos(next_cell(41,8,twocoins)).
pos(next_cell(42,1,onecoin)).
pos(next_cell(42,2,twocoins)).
pos(next_cell(42,3,onecoin)).
pos(next_cell(42,4,zerocoins)).
pos(next_cell(42,5,zerocoins)).
pos(next_cell(42,6,zerocoins)).
pos(next_cell(42,7,twocoins)).
pos(next_cell(42,8,twocoins)).
pos(next_cell(43,1,twocoins)).
pos(next_cell(43,2,onecoin)).
pos(next_cell(43,3,zerocoins)).
pos(next_cell(43,4,zerocoins)).
pos(next_cell(43,5,twocoins)).
pos(next_cell(43,6,twocoins)).
pos(next_cell(43,7,onecoin)).
pos(next_cell(43,8,zerocoins)).
pos(next_cell(44,1,onecoin)).
pos(next_cell(44,2,twocoins)).
pos(next_cell(44,3,zerocoins)).
pos(next_cell(44,4,twocoins)).
pos(next_cell(44,5,zerocoins)).
pos(next_cell(44,6,twocoins)).
pos(next_cell(44,7,onecoin)).
pos(next_cell(44,8,zerocoins)).
pos(next_cell(45,1,twocoins)).
pos(next_cell(45,2,zerocoins)).
pos(next_cell(45,3,onecoin)).
pos(next_cell(45,4,zerocoins)).
pos(next_cell(45,5,zerocoins)).
pos(next_cell(45,6,twocoins)).
pos(next_cell(45,7,twocoins)).
pos(next_cell(45,8,onecoin)).
pos(next_cell(46,1,onecoin)).
pos(next_cell(46,2,onecoin)).
pos(next_cell(46,3,onecoin)).
pos(next_cell(46,4,zerocoins)).
pos(next_cell(46,5,onecoin)).
pos(next_cell(46,6,onecoin)).
pos(next_cell(46,7,twocoins)).
pos(next_cell(46,8,onecoin)).
pos(next_cell(47,1,onecoin)).
pos(next_cell(47,2,zerocoins)).
pos(next_cell(47,3,twocoins)).
pos(next_cell(47,4,twocoins)).
pos(next_cell(47,5,zerocoins)).
pos(next_cell(47,6,onecoin)).
pos(next_cell(47,7,zerocoins)).
pos(next_cell(47,8,twocoins)).
pos(next_cell(49,1,zerocoins)).
pos(next_cell(49,2,onecoin)).
pos(next_cell(49,3,onecoin)).
pos(next_cell(49,4,zerocoins)).
pos(next_cell(49,5,twocoins)).
pos(next_cell(49,6,zerocoins)).
pos(next_cell(49,7,twocoins)).
pos(next_cell(49,8,twocoins)).
pos(next_cell(51,1,twocoins)).
pos(next_cell(51,2,onecoin)).
pos(next_cell(51,3,zerocoins)).
pos(next_cell(51,4,onecoin)).
pos(next_cell(51,5,zerocoins)).
pos(next_cell(51,6,zerocoins)).
pos(next_cell(51,7,twocoins)).
pos(next_cell(51,8,twocoins)).
pos(next_cell(53,1,onecoin)).
pos(next_cell(53,2,twocoins)).
pos(next_cell(53,3,onecoin)).
pos(next_cell(53,4,zerocoins)).
pos(next_cell(53,5,onecoin)).
pos(next_cell(53,6,zerocoins)).
pos(next_cell(53,7,twocoins)).
pos(next_cell(53,8,onecoin)).
pos(next_cell(54,1,twocoins)).
pos(next_cell(54,2,twocoins)).
pos(next_cell(54,3,zerocoins)).
pos(next_cell(54,4,zerocoins)).
pos(next_cell(54,5,zerocoins)).
pos(next_cell(54,6,onecoin)).
pos(next_cell(54,7,onecoin)).
pos(next_cell(54,8,twocoins)).
pos(next_cell(55,1,zerocoins)).
pos(next_cell(55,2,onecoin)).
pos(next_cell(55,3,onecoin)).
pos(next_cell(55,4,zerocoins)).
pos(next_cell(55,5,twocoins)).
pos(next_cell(55,6,zerocoins)).
pos(next_cell(55,7,twocoins)).
pos(next_cell(55,8,twocoins)).
pos(next_cell(56,1,twocoins)).
pos(next_cell(56,2,onecoin)).
pos(next_cell(56,3,onecoin)).
pos(next_cell(56,4,zerocoins)).
pos(next_cell(56,5,twocoins)).
pos(next_cell(56,6,onecoin)).
pos(next_cell(56,7,onecoin)).
pos(next_cell(56,8,zerocoins)).
pos(next_cell(61,1,onecoin)).
pos(next_cell(61,2,onecoin)).
pos(next_cell(61,3,zerocoins)).
pos(next_cell(61,4,onecoin)).
pos(next_cell(61,5,onecoin)).
pos(next_cell(61,6,twocoins)).
pos(next_cell(61,7,onecoin)).
pos(next_cell(61,8,onecoin)).
pos(next_cell(62,1,twocoins)).
pos(next_cell(62,2,onecoin)).
pos(next_cell(62,3,onecoin)).
pos(next_cell(62,4,zerocoins)).
pos(next_cell(62,5,zerocoins)).
pos(next_cell(62,6,zerocoins)).
pos(next_cell(62,7,twocoins)).
pos(next_cell(62,8,twocoins)).
pos(next_cell(63,1,twocoins)).
pos(next_cell(63,2,onecoin)).
pos(next_cell(63,3,onecoin)).
pos(next_cell(63,4,zerocoins)).
pos(next_cell(63,5,zerocoins)).
pos(next_cell(63,6,twocoins)).
pos(next_cell(63,7,twocoins)).
pos(next_cell(63,8,zerocoins)).
pos(next_cell(64,1,twocoins)).
pos(next_cell(64,2,onecoin)).
pos(next_cell(64,3,onecoin)).
pos(next_cell(64,4,zerocoins)).
pos(next_cell(64,5,onecoin)).
pos(next_cell(64,6,onecoin)).
pos(next_cell(64,7,onecoin)).
pos(next_cell(64,8,onecoin)).
pos(next_cell(65,1,twocoins)).
pos(next_cell(65,2,onecoin)).
pos(next_cell(65,3,zerocoins)).
pos(next_cell(65,4,zerocoins)).
pos(next_cell(65,5,onecoin)).
pos(next_cell(65,6,zerocoins)).
pos(next_cell(65,7,twocoins)).
pos(next_cell(65,8,twocoins)).
pos(next_cell(66,1,onecoin)).
pos(next_cell(66,2,zerocoins)).
pos(next_cell(66,3,onecoin)).
pos(next_cell(66,4,twocoins)).
pos(next_cell(66,5,twocoins)).
pos(next_cell(66,6,zerocoins)).
pos(next_cell(66,7,onecoin)).
pos(next_cell(66,8,onecoin)).
pos(next_cell(68,1,onecoin)).
pos(next_cell(68,2,onecoin)).
pos(next_cell(68,3,onecoin)).
pos(next_cell(68,4,onecoin)).
pos(next_cell(68,5,zerocoins)).
pos(next_cell(68,6,onecoin)).
pos(next_cell(68,7,onecoin)).
pos(next_cell(68,8,twocoins)).
pos(next_cell(7,1,onecoin)).
pos(next_cell(7,2,twocoins)).
pos(next_cell(7,3,twocoins)).
pos(next_cell(7,4,zerocoins)).
pos(next_cell(7,5,zerocoins)).
pos(next_cell(7,6,zerocoins)).
pos(next_cell(7,7,onecoin)).
pos(next_cell(7,8,twocoins)).
pos(next_cell(71,1,onecoin)).
pos(next_cell(71,2,zerocoins)).
pos(next_cell(71,3,twocoins)).
pos(next_cell(71,4,zerocoins)).
pos(next_cell(71,5,twocoins)).
pos(next_cell(71,6,zerocoins)).
pos(next_cell(71,7,onecoin)).
pos(next_cell(71,8,twocoins)).
pos(next_cell(72,1,zerocoins)).
pos(next_cell(72,2,twocoins)).
pos(next_cell(72,3,twocoins)).
pos(next_cell(72,4,zerocoins)).
pos(next_cell(72,5,onecoin)).
pos(next_cell(72,6,zerocoins)).
pos(next_cell(72,7,twocoins)).
pos(next_cell(72,8,onecoin)).
pos(next_cell(73,1,onecoin)).
pos(next_cell(73,2,twocoins)).
pos(next_cell(73,3,twocoins)).
pos(next_cell(73,4,onecoin)).
pos(next_cell(73,5,zerocoins)).
pos(next_cell(73,6,onecoin)).
pos(next_cell(73,7,zerocoins)).
pos(next_cell(73,8,onecoin)).
pos(next_cell(75,1,onecoin)).
pos(next_cell(75,2,onecoin)).
pos(next_cell(75,3,zerocoins)).
pos(next_cell(75,4,twocoins)).
pos(next_cell(75,5,twocoins)).
pos(next_cell(75,6,onecoin)).
pos(next_cell(75,7,zerocoins)).
pos(next_cell(75,8,onecoin)).
pos(next_cell(76,1,zerocoins)).
pos(next_cell(76,2,onecoin)).
pos(next_cell(76,3,onecoin)).
pos(next_cell(76,4,twocoins)).
pos(next_cell(76,5,zerocoins)).
pos(next_cell(76,6,onecoin)).
pos(next_cell(76,7,onecoin)).
pos(next_cell(76,8,twocoins)).
pos(next_cell(77,1,zerocoins)).
pos(next_cell(77,2,onecoin)).
pos(next_cell(77,3,onecoin)).
pos(next_cell(77,4,twocoins)).
pos(next_cell(77,5,onecoin)).
pos(next_cell(77,6,onecoin)).
pos(next_cell(77,7,onecoin)).
pos(next_cell(77,8,onecoin)).
pos(next_cell(78,1,twocoins)).
pos(next_cell(78,2,twocoins)).
pos(next_cell(78,3,zerocoins)).
pos(next_cell(78,4,zerocoins)).
pos(next_cell(78,5,zerocoins)).
pos(next_cell(78,6,zerocoins)).
pos(next_cell(78,7,twocoins)).
pos(next_cell(78,8,twocoins)).
pos(next_cell(79,1,onecoin)).
pos(next_cell(79,2,onecoin)).
pos(next_cell(79,3,twocoins)).
pos(next_cell(79,4,zerocoins)).
pos(next_cell(79,5,onecoin)).
pos(next_cell(79,6,zerocoins)).
pos(next_cell(79,7,onecoin)).
pos(next_cell(79,8,twocoins)).
pos(next_cell(8,1,onecoin)).
pos(next_cell(8,2,onecoin)).
pos(next_cell(8,3,twocoins)).
pos(next_cell(8,4,twocoins)).
pos(next_cell(8,5,zerocoins)).
pos(next_cell(8,6,onecoin)).
pos(next_cell(8,7,zerocoins)).
pos(next_cell(8,8,onecoin)).
pos(next_cell(81,1,twocoins)).
pos(next_cell(81,2,zerocoins)).
pos(next_cell(81,3,onecoin)).
pos(next_cell(81,4,zerocoins)).
pos(next_cell(81,5,zerocoins)).
pos(next_cell(81,6,onecoin)).
pos(next_cell(81,7,twocoins)).
pos(next_cell(81,8,twocoins)).
pos(next_cell(83,1,onecoin)).
pos(next_cell(83,2,onecoin)).
pos(next_cell(83,3,onecoin)).
pos(next_cell(83,4,onecoin)).
pos(next_cell(83,5,twocoins)).
pos(next_cell(83,6,onecoin)).
pos(next_cell(83,7,onecoin)).
pos(next_cell(83,8,zerocoins)).
pos(next_cell(84,1,twocoins)).
pos(next_cell(84,2,onecoin)).
pos(next_cell(84,3,onecoin)).
pos(next_cell(84,4,zerocoins)).
pos(next_cell(84,5,zerocoins)).
pos(next_cell(84,6,onecoin)).
pos(next_cell(84,7,twocoins)).
pos(next_cell(84,8,onecoin)).
pos(next_cell(86,1,twocoins)).
pos(next_cell(86,2,twocoins)).
pos(next_cell(86,3,twocoins)).
pos(next_cell(86,4,zerocoins)).
pos(next_cell(86,5,zerocoins)).
pos(next_cell(86,6,onecoin)).
pos(next_cell(86,7,zerocoins)).
pos(next_cell(86,8,onecoin)).
pos(next_cell(87,1,onecoin)).
pos(next_cell(87,2,twocoins)).
pos(next_cell(87,3,onecoin)).
pos(next_cell(87,4,onecoin)).
pos(next_cell(87,5,zerocoins)).
pos(next_cell(87,6,zerocoins)).
pos(next_cell(87,7,onecoin)).
pos(next_cell(87,8,twocoins)).
pos(next_cell(89,1,onecoin)).
pos(next_cell(89,2,twocoins)).
pos(next_cell(89,3,onecoin)).
pos(next_cell(89,4,twocoins)).
pos(next_cell(89,5,zerocoins)).
pos(next_cell(89,6,onecoin)).
pos(next_cell(89,7,onecoin)).
pos(next_cell(89,8,zerocoins)).
pos(next_cell(9,1,zerocoins)).
pos(next_cell(9,2,onecoin)).
pos(next_cell(9,3,zerocoins)).
pos(next_cell(9,4,zerocoins)).
pos(next_cell(9,5,twocoins)).
pos(next_cell(9,6,twocoins)).
pos(next_cell(9,7,twocoins)).
pos(next_cell(9,8,onecoin)).
pos(next_cell(90,1,twocoins)).
pos(next_cell(90,2,onecoin)).
pos(next_cell(90,3,zerocoins)).
pos(next_cell(90,4,zerocoins)).
pos(next_cell(90,5,onecoin)).
pos(next_cell(90,6,onecoin)).
pos(next_cell(90,7,twocoins)).
pos(next_cell(90,8,onecoin)).
pos(next_cell(91,1,onecoin)).
pos(next_cell(91,2,twocoins)).
pos(next_cell(91,3,twocoins)).
pos(next_cell(91,4,zerocoins)).
pos(next_cell(91,5,onecoin)).
pos(next_cell(91,6,zerocoins)).
pos(next_cell(91,7,onecoin)).
pos(next_cell(91,8,onecoin)).
pos(next_cell(93,1,zerocoins)).
pos(next_cell(93,2,twocoins)).
pos(next_cell(93,3,twocoins)).
pos(next_cell(93,4,zerocoins)).
pos(next_cell(93,5,zerocoins)).
pos(next_cell(93,6,onecoin)).
pos(next_cell(93,7,onecoin)).
pos(next_cell(93,8,twocoins)).
pos(next_cell(96,1,twocoins)).
pos(next_cell(96,2,twocoins)).
pos(next_cell(96,3,onecoin)).
pos(next_cell(96,4,zerocoins)).
pos(next_cell(96,5,onecoin)).
pos(next_cell(96,6,zerocoins)).
pos(next_cell(96,7,onecoin)).
pos(next_cell(96,8,onecoin)).
pos(next_cell(99,1,onecoin)).
pos(next_cell(99,2,onecoin)).
pos(next_cell(99,3,onecoin)).
pos(next_cell(99,4,twocoins)).
pos(next_cell(99,5,twocoins)).
pos(next_cell(99,6,zerocoins)).
pos(next_cell(99,7,onecoin)).
pos(next_cell(99,8,zerocoins)).