max_vars(5).
max_body(5).
max_clauses(2).

modeh(f,2).
modeb(f,2).
modeb(head,2).
modeb(tail,2).
modeb(element,2).
modeb(increment,2).
modeb(decrement,2).
modeb(geq,2).
modeb(empty,1).
modeb(even,1).
modeb(odd,1).
modeb(one,1).
modeb(zero,1).

type(f,(list,element)).
type(head,(list,element)).
type(tail,(list,list)).
type(element,(list,element)).
type(cons,(element,list,list)).
type(increment,(element,element)).
type(decrement,(element,element)).
type(geq,(element,element)).
type(empty,(list,)).
type(even,(element,)).
type(odd,(element,)).
type(one,(element,)).
type(zero,(element,)).

direction(f,(in,out)).
direction(head,(in,out)).
direction(tail,(in,out)).
direction(element,(in,out)).
direction(cons,(in,in,out)).
direction(increment,(in,out)).
direction(decrement,(in,out)).
direction(geq,(in,in)).
direction(empty,(in,)).
direction(even,(in,)).
direction(odd,(in,)).
direction(one,(in,)).
direction(zero,(out,)).